### ISSUE TITLE
Warn: You have not declared a namespacesRequired array on your page-level component: undefined. This will cause all namespaces to be sent down to the cli  ent, possibly negatively impacting the performance of your app. For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dep  endencies

### ISSUE THREAD

**Issue by chulphan** [isaachinman/next-i18next#100]
I have seen this error..
![image](https://user-images.githubusercontent.com/35016301/51251376-8bc5b400-19dc-11e9-9dc7-7dc65fcaef54.png)

but after delete the code.. (This code can see at example code of your repository)
![image](https://user-images.githubusercontent.com/35016301/51251446-b57edb00-19dc-11e9-9586-06cc36e13a68.png)

The Warning message disappeared.

Should specify the 'namespacesRequired'? then let me know how can resolve.

Thank you.^^

**Comment by isaachinman** [comment]
I don't understand your question. It's probably the error page, see #79. You should include `namespacesRequired` on all page-level components.

**Comment by chulphan** [comment]
When i specify namespacesRequired occur warn message as above every seconds.
But after the namespacesRequired then the warning message is disappear.

**Comment by isaachinman** [comment]
I do not understand what you are asking. Please read #79 as well as the README.

**Comment by kachkaev** [comment]
@chulphan do you have `pages/_error.jsx` in you project? This file should exist and it should also define `namespacesRequired`.

**Comment by chulphan** [comment]
@kachkaev After make the _error.tsx file in pages, the warning message is disappeared. Thank you!!^^. I refered your examples, but there are no file _error.jsx. I think if you can add _error.jsx in your example, then would be more helpful. 
I apperciate your help. (and sorry can't speak english, make you confuse..^^)

**Comment by chulphan** [comment]
@isaachinman I apperciate for you reflect my opinion^^
