### ISSUE TITLE
TypeError: Cannot read property 'getState' of null

### ISSUE THREAD

**Issue by pablohpsilva** [isaachinman/next-i18next#1001]
## Describe the bug
I'm literally just using the hooks and I'm getting this error:
```
TypeError: Cannot read property 'getState' of null
```

## Occurs in next-i18next version
```
"next-i18next": "^8.0.2",
```

## Steps to reproduce
I can't... the issue happens for no reason with a single component.

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Hi @pablohpsilva – I'll need a way to reproduce this error, in order to debug it.
