### ISSUE TITLE
No way to use next-i18next without Next.js i18n routing

### ISSUE THREAD

**Issue by pajasevi** [isaachinman/next-i18next#1002]
## Is your feature request related to a problem? Please describe.
Current next-i18next implementation (v8.x.x) depends on Next.js v10 internationalization functionality/configuration. This means that currently, there is no way of using next-i18next without opting-in for localized sub-path routing or domain routing.
I have an app that would actually do better without internationalized routes as there is no need for them, thus just using internationalization of text content.

I haven't found a way to disable internationalized routing directly in Next.js configuration while still being able to use core i18n functionality as I understand that this would not make sense for Next.js devs. Is there a possible way of solving this?

Thanks in advance for answering.

**Comment by isaachinman** [comment]
It is correct that `next-i18next` now relies on NextJs directly for routing. Any routing concerns/feedback should be direct to the NextJs repo. Thanks!
