### ISSUE TITLE
Namespaces are not dynamically loaded when using `useTranslation`

### ISSUE THREAD

**Issue by Alegt** [isaachinman/next-i18next#1004]
## Describe the bug
Using version 8.0 and up prevent namespaces to be dynamically loaded on the browser, this was possible on previous versions by only specifying them to the `useTranslation` hook when the namespace for the page in question was not present on the initial props `serverSideTranslations` after the update

Just doing this result on the error:
`Error: ReactDOMServer does not yet support Suspense.`

Setting the config on `next-i18next.config.js` to `react.useSuspense = false` solves this error, but the translations json is never downloaded on the browser

A workaround for this could be including the list of all the used namespaces on the `serverSideTranslations` config, but ideally we're able to take full advantage of `react-i18next` set of features

## Occurs in next-i18next version
8.0 and later

## Steps to reproduce
Call a namespace from `useTranslation` hook that is not specified on the page `serverSideTranslations`
[Here is a fork](https://github.com/Alegt/next-i18next/tree/onDemandi18n) with little changes on the [simple example](https://github.com/Alegt/next-i18next/commit/341ae1e7f1115fa9e38ead00ea8202df1b549795) to show the issue

## Expected behaviour
It should load the json file with the translations specified when they are not part of the translations populated on the server side
This is part of the `useTranslation` hook from [react-18next](https://react.i18next.com/latest/usetranslation-hook) library

## OS (please complete the following information)
 - Device: MBP 2018 15"
 - Browser: All

## Additional context
This used to work on previous versions as expected from the react-i18next docs, tried downgrading  react-i18next to previously used version here but the issue is still present, so it might be due to some changes as part of the new integration

**Comment by isaachinman** [comment]
You'll just need to add [i18next-http-middleware](https://github.com/i18next/i18next-http-middleware) via `config.use`. Good luck!

**Comment by dcodus** [comment]
@isaachinman is this all that's needed? Been having a hard time trying to get the the dynamic namespaces to load.


```js
// next-i18next.config.js
const middleware = require('i18next-http-middleware');

module.exports = {
  use: [middleware.LanguageDetector],
  i18n: { /*...*/ }
}

// _app.js
appWithTranslation(MyApp, nextI18NextConfig);
```

**Comment by dcodus** [comment]
Solution https://github.com/isaachinman/next-i18next/issues/1049#issuecomment-802398519

**Comment by Alegt** [comment]
Confirming that using `i18next-http-backend` with the setup on the comment linked by @dcodus is working as expected

Thanks guys
