### ISSUE TITLE
Module not found: Can't resolve 'fs' - i18next 8.0.3

### ISSUE THREAD

**Issue by rintala** [isaachinman/next-i18next#1010]
## Describe the bug
Error message that module is not found - can't resolve fs. Even though configurated correctly, and used as illustrated in the sample. Problem with webpack?

## Occurs in next-i18next version
next-i18next version: 8.0.3

## Steps to reproduce
**next.config.js:**
```
const withOptimizedImages = require("next-optimized-images");
const path = require('path');
module.exports = withOptimizedImages({
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'sv'],
    },
    localePath: path.resolve('./public/static/locales'),
    debug: true,
});
```

**_app.js**
```
function MyApp({ Component, pageProps }) {return <Component {...pageProps}/>}
export default appWithTranslation(MyApp)
```

**component implementation**
...
`const { t } = useTranslation("common");`
...
```
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});
```
 
## Expected behaviour
No error message - should be able to use the t variable for translations.

## OS
MBP 13-inch 2016
Chrome

Appreciate any help!

**EDIT:** 
Mistakenly named next-i18next.config.js instead of next.config.js in original post, as @isaachinman pointed out in his remark (1).

**Comment by isaachinman** [comment]
Hi @rintala – a couple issues I've noticed immediately:

1. You've mixed up `next-i18next.config.js` with `next.config.js`. You can't pass `withOptimizedImages` or any plugins into `next-i18next`.
2. You cannot put `getStaticProps` on components – the data fetching methods only work on pages.

Let me know if that helps.

**Comment by rintala** [comment]
Hi @isaachinman. Thanks a lot for the super-fast reply! I resolved the issue with help of your second point. I had removed all occurrences of getStaticProps from all components but had left the import of `import { serverSideTranslations } from "next-i18next/serverSideTranslations";` which caused the error. Thanks again for your solid work on this package. 🚀
