### ISSUE TITLE
SSR question regarding getServerSideProps and next10 with >  v8 upgrade

### ISSUE THREAD

**Issue by alsoscotland** [isaachinman/next-i18next#1011]
## Is your feature request related to a problem? Please describe.
I am currently working on upgrading to the latest next-i18next (v8.0.6) and nextjs(v10.0.7) from a previously working implementation I had configured with (v7.0.1 and v10.0.6).

The new setup after v8 is much simpler, however I have only been able to get things working with SSR by leveraging `getServerSideProps` which is not compatible with getInitialProps.

`getServerSideProps` allows making the translations populate correctly on the server-side, but `getInitialProps` has its own meaningful use-cases for populating domain data on the server side.  

Prior to the upgrade I have been leveraging redux and getInitialProps to fetch data and pre-populate a redux store on the server-side so that I have actual data on the initial render. The code is similar to the following snippet for a example domain object item [slug].tsx page:

```ts
Item.getInitialProps = async (ctx: NextPageContext) => {
    let id;
    try {
        const idRaw = ctx?.query?.slug ? idFromSlug(ctx?.query?.slug as string) : undefined;

        if (!idRaw) {
            return {
                namespacesRequired: ['common']
            };
        }

        id = Array.isArray(idRaw) ? idRaw[0] : idRaw;

        // note the access to next page context with the redux store here
        await fetchItemById(id)(ctx.store.dispatch);

        return {
            itemId: id,
            namespacesRequired: ['common']
        };
    } catch (err) {
        return {
            errors: err.message,
            namespacesRequired: ['common']
        };
    }
};
```

I have not found a way to make this function and also get the translations on initial render.
The page works fine with translations after replacing getInitialProps like so:

```ts
export const getServerSideProps = async ({ locale }: { locale: string }) => ({
    props: {
        ...(await serverSideTranslations(locale, ['common']))
    }
}));

Listing.defaultProps = {
    i18nNamespaces: ['common']
};
```

but it seems like losing the getInitialProps data fetching is a loss of a fundamental driver for why you would want SSR.  
Is there a recommended way to fetch data on the server side in this manner?

## Describe the solution you'd like
I am looking for a way to fetch and populate a redux store during SSR rendering that can work with a method of populating the translations on the server as well.

**Comment by isaachinman** [comment]
In general, you can perform any data fetching or logic that you'd like inside `getServerSideProps`. For your use case it should be nearly identical.

**Comment by alsoscotland** [comment]
@isaachinman thank you for the quick reply (and for the work on this package)

I was reading some threads last night and mistakenly read one which mentioned that context was not available in `getServerSideProps`.  I didn't realize it was discussing contextApi hooks.

Seems like I just need to extend NextPageContext with store and locale.

I appreciate the help.
