### ISSUE TITLE
Impossible to translate the _error page

### ISSUE THREAD

**Issue by alexpuertasr** [isaachinman/next-i18next#1020]
I'm migrating to the v8 and I have a problem when I try to translate my _error page because only supports the getInitialProps. Is this scenario contemplated?

**Comment by isaachinman** [comment]
As mentioned in the README, `getIntialProps` is not supported. However, you can use `getServerSideProps` on your error page and achieve the same result.

**Comment by alexpuertasr** [comment]
When I try to use the getServerSideProps on the _error page I'm getting this error running the build:
Error: Error for page /_error: pages with `getServerSideProps` can not be exported

**Comment by ruhaim** [comment]
Im having the same issue too...

-next-i18next lib needs to be initialized via getServerSideProps() or getStaticProps()
-My error page requires to be translation enabled AND dynamically generated (either via getServerSideProps() or getInitalProps())

**Comment by magnattic** [comment]
I don't understand why this is closed. This problem is unresolved, the propsed solution does not work.

**Comment by isaachinman** [comment]
The [custom error page](https://nextjs.org/docs/advanced-features/custom-error-page) supports all data-fetching methods. @magnattic Please refer to the docs.

**Comment by magnattic** [comment]
@isaachinman Where do you read that in the docs? The _error page only supports `getInitialProps`. See also [this comment from a next maintainer confirming this](https://github.com/zeit/next.js/discussions/11945#discussioncomment-6790).

I tried it myself and got 
>Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Error for page /_error: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export

**Comment by magnattic** [comment]
Yes, that example is using `getStaticProps` though, not `getServerSideProps`. :) Also it's not the _error page, but the 404 page (not sure if that difference matters).

You said multiple times in this thread that `getServerSideProps` is supported, but I don't think that is true. At least I haven't seen how that would work and all my attempts failed. As far as I understand now, the _error page has to be statically generated and cannot include any runtime info. I might be wrong though. 

When I use `getStaticProps` I can use the translations. I just can't include any runtime info from the request (like response error message). Or if it's possible, I haven't found out how yet.

**Comment by isaachinman** [comment]
The exact same pattern would work with `getServerSideProps`.

**Comment by magnattic** [comment]
I appreciate that you are taking the time to help, but as I said unfortunately that's not true. I copy pasted the example you provided and replaced `getStaticProps` with `getServerSideProps`. I get the error which seems quite clear:

> Build error occurred
>Error: `pages/404` can not have getInitialProps/getServerSideProps, https://nextjs.org/docs/messages/404-get-initial-props

Are you working on a different version of nextjs? I am currently on next v10.1.3

**Comment by ruhaim** [comment]
Hi I face the same issue as @magnattic.
404 pages support only getStaticProps()

This limitation seems to be coming from Nextjs itself.

The only way to get the error page to be passed dynamic props is via the
_error getInitialProps(). Though nextjs supports this next-i18next's latest
version does not support it. Best option is roll back to older version of
the module, it supports getInitialProps, or wait until nextjs itself
supports getServerSideProps for 404 page.

Its sort of a dilemma atm..

**Comment by isaachinman** [comment]
Just want to mention that `getInitialProps` should _also_ work, if you pass the props correctly. Relevant line of code [here](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L29). Please don't be afraid to read source code!

**Comment by kachkaev** [comment]
I faced the same issue when upgrading an old project from `next-i18next` v4 (before it used Next i18n routes).

The problem with `_error.jsx` is that it [only supports `getInitialProps`](https://nextjs.org/docs/advanced-features/custom-error-page#more-advanced-error-page-customizing). This function can be invoked on the client if an error has occurred after page load. This means that we can’t use `serverSideTranslations` in `_error.jsx`.

So what I did was creating `pages/404.jsx` and `pages/500.jsx` to handle not-found pages and server-side errors. Those pages call `serverSideTranslations` inside `getStaticProps` –  no problems with that. Then for client-side errors I imported [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary) and used it in `_app.jsx`. Translations work in it well as long as corresponding namespaces are preloaded by all pages. Error messages can be put into the `common` namespace because they can appear on any page.

Seems like the new setup works – I have been able to fully remove `_error.jsx` from the project.

**Comment by VladimirMikulic** [comment]
https://nextjs.org/docs/advanced-features/error-handling#handling-client-errors
For those looking to do this without adding another dependency (TS):

`PageErrorBoundary.tsx`

```ts
import { Component } from "react";
import { TFunction, withTranslation } from "next-i18next";

type Props = {
  t: TFunction;
};

type State = {
  hasError: boolean;
};

class PageErrorBoundary extends Component<Props, State> {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidUpdate(
    prevProps: Readonly<Props>,
    prevState: Readonly<State>,
    snapshot?: any
  ): void {
    // Resets state on page switch (from page with error to other page)
    if (prevState.hasError) this.setState({ hasError: false });
  }

  static getDerivedStateFromError(error) {
    return { hasError: true };
  }

  render() {
    if (!this.state.hasError) return this.props.children;
    return <p>{t("client-side-error-occured")}</p>
  }
}

export default withTranslation("common")(PageErrorBoundary);
```

In `app.tsx`, wrap `Component` with `PageErrorBoundary` and you're done.

**Comment by tkrotoff** [comment]
[Next.js](https://nextjs.org/docs/advanced-features/custom-error-page#caveats):
> `Error` does not currently support [...] `getStaticProps` or `getServerSideProps` [ed. only `getInitialProps`]

[next-i18next](https://github.com/isaachinman/next-i18next/blob/v11.0.0/README.md?plain=1#L130):
> `serverSideTranslations` is not compatible with `getInitialProps`, as it *only* can execute in a server environment, whereas `getInitialProps` is called on the client side when navigating between pages.

Next.js `Error` component source code: https://github.com/vercel/next.js/blob/v12.1.4/packages/next/pages/_error.tsx

**Comment by kaguya3222** [comment]
Why is this issue closed? 🤔 

`_error.jsx` is a replacement for Next.js `Error` component. `Error` component doesn't work with data-fetching methods like `getServerSideProps` or `getStaticProps`. next-i18next supports only `getServerSideProps` or `getStaticProps`. So I believe there is no way to translate Error using next-i18next

**Comment by kaguya3222** [comment]
> I faced the same issue when upgrading an old project from `next-i18next` v4 (before it used Next i18n routes).
> 
> The problem with `_error.jsx` is that it [only supports `getInitialProps`](https://nextjs.org/docs/advanced-features/custom-error-page#more-advanced-error-page-customizing). This function can be invoked on the client if an error has occurred after page load. This means that we can’t use `serverSideTranslations` in `_error.jsx`.
> 
> So what I did was creating `pages/404.jsx` and `pages/500.jsx` to handle not-found pages and server-side errors. Those pages call `serverSideTranslations` inside `getStaticProps` – no problems with that. Then for client-side errors I imported [`react-error-boundary`](https://github.com/bvaughn/react-error-boundary) and used it in `_app.jsx`. Translations work in it well as long as corresponding namespaces are preloaded by all pages. Error messages can be put into the `common` namespace because they can appear on any page.
> 
> Seems like the new setup works – I have been able to fully remove `_error.jsx` from the project.


@kachkaev Is there any case when the server can respond with a status code, that not equals 404 or 500? For example, 403. What page will be shown in this case ? 🤔

**Comment by nico-i** [comment]
@kaguya3222 FYI: I achieved this with a workaround. I posted my solution here: https://stackoverflow.com/a/76390043/13929165

**Comment by maxbethke** [comment]
I am also facing this issue, wondering how I would be able to translate my error pages. The only alternative while still using next-i18next I see would be to serve error pages only in english.

**Comment by karanshah229** [comment]
@isaachinman @adrai
Why is this issue closed ?

It is clearly still a problem.
The exact problem - https://github.com/i18next/next-i18next/issues/1020#issuecomment-1090060525

The best work around for now seems to be remove the Custom _error page and adopt an Error Boundary at Page level or load the translation on client side.
These are far from the ideal solution.

**Comment by adrai** [comment]
see https://github.com/i18next/next-i18next/issues/1950#issuecomment-1248489253
and https://github.com/i18next/next-i18next/issues/1950#issuecomment-1372633266

**Comment by flovilmart** [comment]
I believe I found a proper workaround.
You can use the `500.page.js` as your error page as a fallback to the `_error.page.js` 

By throwing an error when attempting to render _error.page.js, that will force next.js to fallback to `500` which can be SSG with all the translations you need.
One caveat is that you get an additional log for an error, but that's small price to pay.

```
// _error.page.js
import * as Sentry from "@sentry/nextjs";

function CustomErrorPage() {
  return null;
}

// This custom error page is only used to record issues in Sentry
// This will throw an error and force Next.js to render the static 500.page.js
//
CustomErrorPage.getInitialProps = async contextData => {
  // In case this is running in a serverless function, await this in order to give Sentry
  // time to send the error before the lambda exits
  await Sentry.captureUnderscoreErrorException(contextData);

  if (contextData.res) {
    throw new Error(
      "_error page reported issue to sentry - redirecting to 500.page.js",
    );
  }

  return {};
};

export default CustomErrorPage;
```

```
/// 500.page.js
import React from "react";

import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import ErrorPage from "components/ErrorPage/ErrorPage";
import { init } from "components/i18n/source";

export default function CustomErrorPage() {
  return <ErrorPage />;
}

export async function getStaticProps({ locale: ctxLocale }) {
  // FIXME: This is a Next.js bug where locale is sometimes undefined
  // https://github.com/vercel/next.js/issues/32309
  const locale = ctxLocale || "en-US";
  const translations = await serverSideTranslations(locale, ["common"]);

  init(locale, translations._nextI18Next.initialI18nStore);

  return {
    props: {
      ...translations,
    },
  };
}
```
