### ISSUE TITLE
serverSideTranslations not fetching translations, if locale has region written via dash symbol 

### ISSUE THREAD

**Issue by hirdbluebird** [isaachinman/next-i18next#1021]
## Describe the bug
When URL contains two characters (`en`, `de`) it works fine, as in the [simple-example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple). But when the region being added after the language (`en-us`, `de-de`) app crashes with `ReactDOMServer does not yet support Suspense` error, because in browser `initialI18nStore` has a key with an empty object.

## Occurs in next-i18next version
Occurs in 8.x.x versions with `serverSideTranslations` method

## Steps to reproduce
You can download [fork](https://github.com/hirdbluebird/next-i18next) of simple-example where `next-i18next.config.js` config was changed to 
```
i18n: {
    defaultLocale: 'en-us',
    locales: ['en-us', 'de-de'],
  }
```
and `public/locales/**` was renamed to what's set in the config file and catch the same error.

Check it, please.

Perhaps, it's because [this line](https://github.com/hirdbluebird/next-i18next/blob/4cbf7ca78c80f39d1a6e8c7f598d4159b457db89/src/serverSideTranslations.ts#L67)

![image](https://user-images.githubusercontent.com/15096016/109829025-da2e7f00-7c45-11eb-9612-fb745248684f.png)

The `i18n.services.resourceStore.data` contains region as uppercase, and because JS is a case-sensitive library cannot get the data.

**Comment by henryjin3** [comment]
I'm having a similar issue, where I get the `ReactDOMServer does not yet support Suspense` error, but so far only on `zh-<anything>`, for example `zh` works, but `zh-TW` or `zh-Hans` do not. However, `en-US` and `ru-RU` work just fine. See my sample repo: https://github.com/henryjin3/nextjs-locale-testbed

**Comment by isaachinman** [comment]
@hirdbluebird If I update your config to use properly-constructed locales, it works fine:

```
module.exports = {
  i18n: {
    defaultLocale: 'en-US',
    locales: ['en-US', 'de-DE'],
  },
}
```

Please make sure your locales are formatted correctly.

**Comment by henryjin3** [comment]
@isaachinman Does that apply in my case as well? I don't see anything wrong with my current locales, but I might be missing something. `zh-TW` is the one that is failing. https://github.com/henryjin3/nextjs-locale-testbed/blob/failurestate/next-i18next.config.js

```
module.exports = {
  i18n: {
    defaultLocale: 'fr',
    locales: ['en-US', 'fr', 'zh-TW', 'ru-RU'],
  },
};
```
