### ISSUE TITLE
Is there any way to use .po files instead of .json files for translations?

### ISSUE THREAD

**Issue by juagarc4** [isaachinman/next-i18next#1024]
## Is your feature request related to a problem? Please describe.
Many translations are done by external translators that usually work with POEditors to create the translations and save them into the corresponding .po files.

## Describe the solution you'd like
I would like to have the possibility to use .po files in the same way I'm using json files.

## Additional context
I've tried to use the module "https://github.com/openculinary/i18next-gettext-loader" but it doesn't seem to work with next-i18next.

Thanks in advance
Regards

**Comment by isaachinman** [comment]
Yes, just use the `localeExtension` config option. Good luck!

**Comment by juagarc4** [comment]
Thanks for the quick response.

Unfortunately it doesn't work. I think, it's not as easy as change a config option. 
The format of .po files is different from .json one.
I've just seen an old closed issue "https://github.com/isaachinman/next-i18next/issues/572" with the same question and unfortunately the author never posted whether he found a solution or not.

Anyway thanks for the answer. I'll continue searching for a solution.
Regards
