### ISSUE TITLE
i18n.loadLanguages does not load other languages

### ISSUE THREAD

**Issue by Cretezy** [isaachinman/next-i18next#1025]
## Describe the bug
In versions <8, the following code would work as expected:

```ts
const { t, i18n } = useTranslation(namespaces);

useEffect(async () => {
  await i18n.loadLanguages([someOtherLanguage]);

  console.log(t(key, { lng: someOtherLanguage }));
}, []);
```

This used to load the other language, and allow to translate to it.

In v8, the following behavior does not load the other language and translate only to the current validation.

## Occurs in next-i18next version

Any v8 releases.

**Comment by isaachinman** [comment]
Hi there, you'll just need to add [i18next-http-backend](https://github.com/i18next/i18next-http-backend) as a plugin via `config.use`. Good luck!

**Comment by Cretezy** [comment]
Could you provide a working example? I am unable to get this working:

```
const path = require("path");
// This may be a TS issue, but importing in the Node context vs the build context provided different results. This fixes it
const HttpApi =
  require("i18next-http-backend").default || require("i18next-http-backend");

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    serializeConfig: false,
    backend: {
      // We use the pre-v8 path style. I also tried without the backend configuration
      loadPath: "/public/static/locales/{{lng}}/{{ns}}.json",
    },
  },
  localePath: path.resolve("./public/static/locales"),
  react: {
    useSuspense: false,
    wait: true,
  },
  use: [new HttpApi()],
};
```

With the configuration import.

Now, no namespaces are being loaded.

**Comment by Cretezy** [comment]
Okay, I was able to hack together a solution:

**next-i18next.config.json**
```ts
/* eslint-disable */
const path = require("path");

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    serializeConfig: false,
  },
  localePath: path.resolve("./public/static/locales"),
  use: [],
};
```

**_app.ts**
```ts
onst use = [...nextI18NextConfig.use];

if (process.browser) {
  // Only import
  use.push(HttpApi);
}

export default appWithTranslation(
  wrapper.withRedux(RootApp) as React.FunctionComponent,
  {
    ...(nextI18NextConfig as any),
    use,
  }
);
```

This only loads the HttpApi backend on the client, so that the server can still server can resolve using the fs backend.

Additional, `loadLanguages` still was not working. I had to use `reloadResources(["fr"], ["forms"])` to load specific namespaces (it loaded only the `common` by default).

They is likely a fix for this that can be implemented in this package. Possibly an optional HTTP backend for the client as a option would be nice.

**Comment by isaachinman** [comment]
Not sure I understand – why don't you just do a `typeof window === 'undefined'` in your `next-i18next.config.js`?

> (it loaded only the common by default)

That is because `['common']` is the value of `config.ns`, most likely.

**Comment by Cretezy** [comment]
You're right, I was able to do:

```js
/* eslint-disable */
const path = require("path");
const HttpApi = require("i18next-http-backend").default;

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    serializeConfig: false,
  },
  react: {
    wait: true,
    useSuspense: false,
  },
  localePath: path.resolve("./public/static/locales"),
  use: process.browser ? [HttpApi] : [],
};
```
