### ISSUE TITLE
Having the config file not on the root folder

### ISSUE THREAD

**Issue by NiloDrumond** [isaachinman/next-i18next#1028]
## Is your feature request related to a problem? Please describe.
The request is related to the solution to this error:
`Server Error
Error: next-i18next was unable to find a user config`

## Describe the solution you'd like
All I want is to have my next-i18next.config file inside a config folder instead of clustering the root folder, but that throws the error I mentioned.

## Describe alternatives you've considered
You can solve it by importing the config and manually inserting on appWithTranslation and every serverSideTranslation.

I understand that the second parameter of those functions is supposed to be used when you want a specific config that isn't that default one, so I think there should be a way to set the config file location or something like that.

**Comment by isaachinman** [comment]
How would you propose declaring a different config location, besides passing it into the functions? How can we possibly know where your config file lives, otherwise?

**Comment by asherccohen** [comment]
I'm also experiencing something similar. I'm working in a Nx dev project and as far as I could understand this is not working as expected in a monorepo:

serversideTranslations.js line 23
```

  if (fs.existsSync(path.resolve(DEFAULT_CONFIG_PATH))) {
    userConfig = await import(path.resolve(DEFAULT_CONFIG_PATH))
  }
```

**Comment by isaachinman** [comment]
@asherccohen As stated, you can manually pass your config into `appWithTranslations` and `serverSideTranslations`, if you are unable to put a config file in the project root.

**Comment by asherccohen** [comment]
Oh I see, also explained in the docs, now I understand what they refer to. Tx

**Comment by shelooks16** [comment]
> @asherccohen As stated, you can manually pass your config into `appWithTranslations` and `serverSideTranslations`, if you are unable to put a config file in the project root.

Hi. Is there any other way to do that? Passing the config manually to every `serverSideTranslations` is really tedious. I'm using nx dev monorepo. Maybe an env variable just like [next-translate](https://github.com/vinissimus/next-translate) does? They allow to specify path to project folder using env variable

**Comment by isaachinman** [comment]
@shelooks16 While I genuinely do not understand the use case here, and env var would be a reasonable solution, and I would accept a PR for that.
