### ISSUE TITLE
Last version is not fetching other languages' locales

### ISSUE THREAD

**Issue by SalahAdDin** [isaachinman/next-i18next#1029]
## Describe the bug
Site is not fetching the locale files to the storage, hence It does not translate literals to other languages but english(default language). It also does not fetch the literals belonging to the `common` file (`defaultNs` by default).

## Occurs in next-i18next version
Version 8.0.6.

## Steps to reproduce
I made the changes for the config:
```javascript
module.exports = {
  i18n: {
    localeDetection: false,
    defaultLocale: "en",
    locales: ["en", "es", "tr"],
  },
  react: {
    useSuspense: false,
    wait: true,
  },
};
```

And this it is the specifical page:
```javascript
export const getStaticProps = async ({ locale }) => {
  const data = await getPageBySlug("about-me", false);

  return {
    props: {
      ...data?.pages[0],
      ...(await serverSideTranslations(locale, ["skill-type"])),
    },
    revalidate: 1,
  };
};
```

## Expected behaviour
It must load the other languages' literal files and also load the common file by default(i understood this).

## Screenshots
<img width="353" alt="Screen Shot 2021-03-06 at 18 04 47" src="https://user-images.githubusercontent.com/5034215/110211638-96877f80-7ea8-11eb-9736-5fe0434677ad.png">
This is my folder structure(following the documentation).

<img width="591" alt="Screen Shot 2021-03-06 at 18 02 49" src="https://user-images.githubusercontent.com/5034215/110211655-a901b900-7ea8-11eb-8ca9-793e0ef41fb4.png">
Here you can see it is neither loading the spanish/turkish files nor loading the common file from english folder.

## OS
 - Device: OsX 11
 - Browser: Chrome 88.0.4324.192

## Additional context
I just have a different namespace for just a specifical page: **About Me**, so, i think i should need to use `await serverSideTranslations(locale, ["skill-type"])` in every page just for loading the `defaultNS`.

I'm migrating from `7` version using **NextJS** `10.0.8`.

**Comment by isaachinman** [comment]
Sorry, I don't understand what question is being asked here. What behaviour are you expecting? You passed the namespace and the page loaded the namespace in the current `locale`.

**Comment by SalahAdDin** [comment]
@isaachinman if i switch the language to Spanish, or Turkish, for instance, it does not translate anything because it does not load the locale files.

**Comment by isaachinman** [comment]
Can you provide a reproducible repo?

**Comment by SalahAdDin** [comment]
> Can you provide a reproducible repo?

Yeah, [here](https://github.com/SalahAdDin/frontend) it is, the _route_ i'm testing is: `/about-me`.

**Comment by isaachinman** [comment]
@SalahAdDin I am getting graphql errors when attempting to run that repo. Can you simplify the example?

**Comment by SalahAdDin** [comment]
> @SalahAdDin I am getting graphql errors when attempting to run that repo. Can you simplify the example?

I will inform you when I can work on it.

Meanwhile, is correct the folder structure i'm handling?

**Comment by SalahAdDin** [comment]
> @SalahAdDin I am getting graphql errors when attempting to run that repo. Can you simplify the example?

You made me realize about a big problem i had with the backend, but it is solved now, thank you!

I think you can test it now.

**Comment by isaachinman** [comment]
@SalahAdDin I meant that your app is not a minimal repro – it shouldn't depend on graphql or any other services to demonstrate the bug. Can you please create a minimal repro?

**Comment by jvcmanke** [comment]
I took a look at your repository @SalahAdDin, and as far as I understand you shoud change locale via the router and not the i18n instance, when dealing with `next.js` internationalization.

Do this:

```javascript
const router = useRouter()

const handleLanguageChange = (event) => {
  router.push(router.pathname, router.asPath, {locale: event.target.value})
}
```

Instead of this:

```javascript
const { i18n } = useTranslation()

const handleLanguageChange = (event) => {
  i18n.changeLanguage(event.target.value)
}
```

You really should't load all your languages for every page, imagine you support 20 different languages your page would become massive very fast.

**Comment by SalahAdDin** [comment]
> I took a look at your repository @SalahAdDin, and as far as I understand you shoud change locale via the router and not the i18n instance, when dealing with `next.js` internationalization.
> 
> Do this:
> 
> ```js
> const router = useRouter()
> 
> const handleLanguageChange = (event) => {
>   router.push(router.pathname, router.asPath, {locale: event.target.value})
> }
> ```
> 
> Instead of this:
> 
> ```js
> const { i18n } = useTranslation()
> 
> const handleLanguageChange = (event) => {
>   i18n.changeLanguage(event.target.value)
> }
> ```
> 
> You really should't load all your languages for every page, imagine you support 20 different languages your page would become massive very fast.

So, i must, yes or yes, use the locale routing mechanism with the new version, isn't it? And it is also because it is a good practice, right?

**Comment by isaachinman** [comment]
@SalahAdDin To change the language, follow the NextJs docs – do not manipulate the i18n instance directly.

**Comment by jvcmanke** [comment]
@SalahAdDin Yes, you have to use the locale routing, I'm not sure about it being a good practice, but with `next-i18next` it's mandatory because `next.js` manages the language and run or fetch `getStaticProps`/`getServerSideProps` accordingly.

**Comment by SalahAdDin** [comment]
Ok, i got it, thanks for the explanation. I will review it then.
