### ISSUE TITLE
Type error for 8.1.0

### ISSUE THREAD

**Issue by janhesters** [isaachinman/next-i18next#1030]
## Describe the bug

Type checks fail because `locale` in `getServerSideProps` can be `undefined` but `serverSideTranslations` expects a `string`.

```ts
$ tsc --pretty --noEmit
src/pages/index.tsx:9:38 - error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

9     ...(await serverSideTranslations(locale, ['common', 'landing'])),
                                       ~~~~~~


Found 1 error.
```

## Occurs in next-i18next version

8.1.0

## Steps to reproduce

Use this package with the following `tsconfig.json`.

```json
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": "./src",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strictPropertyInitialization": true,
    "strictNullChecks": true,
    "strict": true,
    "target": "es5"
  },
  "exclude": ["node_modules", "cypress/"],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}

````

## Expected behaviour

No type errors.

## OS (please complete the following information)
 - Device: MBP 2021 13" M1
 - Browser: Version 1.19.90 Chromium: 88.0.4324.146 (Official Build) (arm64)

**Comment by isaachinman** [comment]
This is not a type error on the `next-i18next` side of things – `serverSideTranslations` genuinely will not accept `undefined` as an argument.
