### ISSUE TITLE
Disable the language detector that comes with i18next-express-middleware

### ISSUE THREAD

**Issue by YIZHUANG** [isaachinman/next-i18next#104]
What is the best way to disable  "i18n.use(i18nextMiddleware.LanguageDetector)" on the server-side? 
For example i have a website that is in "de", i want to set the default language to "de" no matter of the user's browser setting.

Currently i copy paste the "LanguageDetector" from "i18next-express-middleware" and change the "detect" function to return "de" no matter what, add it to the "use" array of the "next-i18next" 's config and it seems to work.

What is the consequence of this? Is there a better solution for this?

**Comment by jamuhl** [comment]
just remove the detector - create a own middleware setting `req.lng = 'de'` before the i18next middleware

or if `de` is the only language set in on init `i18next.init({ lng: 'de' })`

**Comment by jamuhl** [comment]
Ah...sorry was to much in the flow i did not check the repo this issue comes for - thought it was for i18next-express-middleware repo itself. Overwriting the detector with your custom one has no drawback.

But should not be needed - just make `de` de fallback and only language provided leaving otherLanguages empty: https://github.com/isaachinman/next-i18next#options

**Comment by YIZHUANG** [comment]
> Ah...sorry was to much in the flow i did not check the repo this issue comes for - thought it was for i18next-express-middleware repo itself. Overwriting the detector with your custom one has no drawback.
> 
> But should not be needed - just make `de` de defaultLanguage and only language provided leaving otherLanguages empty: https://github.com/isaachinman/next-i18next#options

Thanks, the defaultLanguage in the config does basically nothing at least on my side, it still gets overridden by  "i18next-express-middleware" on the server-side.. That's why i am trying to figure a way to override the default server-side detector.

**Comment by YIZHUANG** [comment]
The defaultLanguage still gonna be "en" even though i changed it on the config to be "de" because my browser setting is to "en".

**Comment by isaachinman** [comment]
Well, we have a `browserLanguageDetection` setting. I suppose we could add a `serverLanguageDetection` setting as well. But really you should be able to set a single language and not worry about it. What do you mean it "gets overridden"? How would your server be serving translation content which does not exist?

**Comment by YIZHUANG** [comment]
> Well, we have a `browserLanguageDetection` setting. I suppose we could add a `serverLanguageDetection` setting as well. But really you should be able to set a single language and not worry about it. What do you mean it "gets overridden"? How would your server be serving translation content which does not exist?

I am doing the exact same as from the example, my default language is set to "de" and other languages are set to "['en']", browser setting is English. I have the locales data in place inside the static folder. But when it comes to server-side is 'en' even thought i set it to 'de' when i do a `console.log(req.i18n)`, hence the content is also in English on the client-side,  and i think the cause is `i18n.use(i18nextMiddleware.LanguageDetector)`, i managed to override it with a custom detect that returns 'de' no matter what, but i am not entirely sure the drawback for such approach.

**Comment by kachkaev** [comment]
@YIZHUANG I've made a small example app that has a workaround, similar to the one you are searching for. Two domains, two languages: https://gitlab.com/kachkaev/website-frontend

Also hope there is a slightly better out-of-box support for this scenario.

**Comment by YIZHUANG** [comment]
> @YIZHUANG I've made a small example app that has a workaround, similar to the one you are searching for. Two domains, two languages: https://gitlab.com/kachkaev/website-frontend
> 
> Also hope there is a slightly better out-of-box support for this scenario.

Looks good, i am looking into it.

**Comment by isaachinman** [comment]
@YIZHUANG Are you saying you do want a `serverLanguageDetection` setting to disable `i18nextMiddleware.LanguageDetector`? It's easy enough, but I think it will affect other functionality. I don't understand - if you don't want your users to see anything in English, don't pass the English in?

**Comment by YIZHUANG** [comment]
> @YIZHUANG Are you saying you do want a `serverLanguageDetection` setting to disable `i18nextMiddleware.LanguageDetector`? It's easy enough, but I think it will affect other functionality. I don't understand - if you don't want your users to see anything in English, don't pass the English in?

Yes, it would be great if we can disable the server-side LanguageDetector.

**Comment by isaachinman** [comment]
Fixed by c3dbf08.
