### ISSUE TITLE
What is the correct configuration for client side translations?

### ISSUE THREAD

**Issue by Yandawl** [isaachinman/next-i18next#1042]
Hey. My project is translated correctly with locale routing. However, I am trying to also output translated text when I set a different language using a dropdown menu that changes component state, causing it to reload the component rather than navigate to an entirely different route.

```js
const ItemPage = (props) => {
    const { t, i18n } = props;
    
    return <>
        {t('mystring')}
    <>
}

ItemPage.getInitialProps = async () => ({
    namespacesRequired: ['common'],
})

export const getServerSideProps = async ({ locale }) => ({
    props: {
        ...await serverSideTranslations(locale, ['common']),
    }
})

export default withTranslation('common')(ItemPage)
```

Unfortunately I'm struggling to get this to work on the client side and would appreciate any pointers as to what the correct configuration is to achieve this, I can't see any examples here. Thank you!

**Comment by isaachinman** [comment]
Not sure what your question is exactly, but you should not be using `getInitialProps`. Please feel free to post on StackOverflow for help. Good luck!

**Comment by sergeu90** [comment]
@isaachinman withTranslation will work in 8 version? I have warning in the console. react-i18next:: You will need to pass in an i18next instance by using initReactI18next

**Comment by Yandawl** [comment]
@isaachinman to elaborate, I call `i18n.changeLanguage("de")` and update component state, but the translation chooses English on component reload, which isn't desired. In this case I don't want to navigate to a locale route, e.g. /de/mypage. I assumed your library could help me with this, so my question is how to configure it such that I can get next-i18next to respect manual language changes within components.

**Comment by isaachinman** [comment]
You should change the locale via NextJs, not `i18n`. Please see [the docs](https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales).

**Comment by Yandawl** [comment]
I've read the docs already, they suggest I use the router to navigate to the appropriate locale's route. This is something I don't want to do in this particular case as I've already stated, and is also default NextJs behaviour. 
Hence I am here asking you about the capabilities of your package and how it can help me solve my problem.

**Comment by ckeeney** [comment]
I don't think it's possible to use v8 unless you also use localized routing from nextjs.

In next-i18next:v7 localized routing was handled by next-i18next and was optional, and next-i18next also maintained the "current language" state for you.

In v8 we let nextjs control the "current language" state, and since nextjs gets this information from the current url, i think you have to use localized routing from nextjs to use v8.  Changing this would require a change in nextjs.

**Comment by Yandawl** [comment]
@ckeeney understood. Thank you for the response 👍
