### ISSUE TITLE
Above the fold prefetch of translations

### ISSUE THREAD

**Issue by enzoferey** [isaachinman/next-i18next#1043]
Hi ! 

Thanks for the great work and smooth update on `next@10`.

I'm opening an issue because I have noticed that translations are being prefetched multiple times by Next.js on page load if you have the same link more than once above the fold of the page. It's quite common for websites to have a signup button in both the jumbotron and the header, or to have a header with links to several pages. This means you could easily be fetching the translations of your whole website without noticing.

What could be a good strategy here ? Disable prefetch on all but one of the links for each page ? Something could be done by `next-i18next` ?

**Comment by isaachinman** [comment]
Hi @enzoferey – optimising for redundant/duplicate props in data fetching methods sounds like a great suggestion for the NextJs team, however, it is not specific to `next-i18next` in any way. Thanks!
