### ISSUE TITLE
withTranslation not worked

### ISSUE THREAD

**Issue by sergeu90** [isaachinman/next-i18next#1045]
Hello everyone. In the 7 version i used withTranslation on the component and it work. Now it is not working. Could you please answer it is supported?

**Comment by isaachinman** [comment]
Yes, it is supported. Can you provide a reproducible repo, demonstrating the error?

**Comment by sergeu90** [comment]
I think I understand. I have to page do
```
export const getStaticProps = async ({ locale }) => {
return ({
props: {
...await serverSideTranslations(locale),
},
});
};
```

and then in the components inside page withTranslation works

**Comment by isaachinman** [comment]
Yes, that is correct. You must use `serverSideTranslations` in `getStaticProps`.

**Comment by jim-king-2000** [comment]
We have to add `getStaticProps` to every pages, right?
