### ISSUE TITLE
Does library works with "next export"?

### ISSUE THREAD

**Issue by hirdbluebird** [isaachinman/next-i18next#1048]
As for now, it looks like the library works only on the server-side because of `serverSideTranslations`, which injecting the `i18n` instance in the application. 
During export to static HTML, I got an error `i18n support is not compatible with next export`.
So, the question is there any workaround? Or this library always worked only on the server and instead `i18next` should be used?

**Comment by isaachinman** [comment]
I believe the error you are seeing:

```
i18n support is not compatible with next export
```

Is coming directly from NextJs. So the answer is no – it's not supported by the NextJs framework.

**Comment by hirdbluebird** [comment]
@isaachinman 
Sorry to bother you, does the library plan to work with export to HTML? Or maybe it works, but something was misunderstood by me.

**Comment by isaachinman** [comment]
@hirdbluebird The NextJs framework does not support `next export` when using i18n features. There's nothing for the `next-i18next` package to do about that. You'd need to request this from the NextJs repo (which they will promptly decline).

**Comment by hirdbluebird** [comment]
@isaachinman thanks for your kind response

**Comment by adrai** [comment]
@hirdbluebird in case you missed it: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
