### ISSUE TITLE
Use React's Context API to simplify the interface

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#105]
What do you think about using the [Context API](https://reactjs.org/docs/context.html) for configuration and to share `next-i18next` options?  User's `_app.js` would transform to something like the following (changes annotated with comments):
```js
import React from 'react'
import App, { Container } from 'next/app'
// import { appWithTranslation } from '../i18n'  this line changes to...
import appWithTranslation from 'next-i18next'

// the user imports configuration from their file
import config from '../i18n'

class MyApp extends App {
  render () {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

// use config in appWithTranslation
export default appWithTranslation(MyApp, config)
```
Then references to things like:
```js
import { Link } from '../i18n';
```
can be changed to something like:
```js
import Link from 'next-i18next'
```
and we wouldn't have to wrap our components into functions to store configuration.  To me, the interface now feels more "package-like".  Thoughts?

**Comment by kachkaev** [comment]
IMO having Link and other components exported from  `../i18n` is somewhat better, because it creates a more straightforward dependency graph (even if `Link` in `../i18n` is the same as in `'next-i18next'`). A local `i18n.js` file becomes an entry point for all the i18n stuff ever happening in the app (the only exception is the middleware, which cannot be added to a `i18n.js` as this would bloat the client bundle.

@capellini you've probably seen my thoughts in https://github.com/isaachinman/next-i18next/issues/42, just sharing the link for others why might end up in this issue. Shame that I don't have enough time ATM to focus on developing the ideas further!

**Comment by capellini** [comment]
Thank you for your input @kachkaev.

> it creates a more straightforward dependency graph

Good point -- I can certainly appreciate not complicating the dependency graph.  In what I'm proposing, `next-i18next` would be the only "true" dependency. The user's `i18n.js` would strictly export a configuration object.

So the user's `i18n.js` file would transform from something like this:
```js
const NextI18Next = require('next-i18next')

module.exports = new NextI18Next({ otherLanguages: ['de'] })
```
to something like this:
```js
module.exports = { otherLanguages: ['de'] }
```
And if we make an exception in our middleware so as not to bloat the package size (which I completely understand and agree with), perhaps it's also a good idea to make an exception and slightly add to the dependency graph to adopt a more common pattern of having a configuration file that we pass in and then use the package straightaway?

It's a pretty standard usage pattern from the packages I've worked with, but I can't say that I've worked with them all. :smile: 

> you've probably seen my thoughts in #42

I apologize -- I hadn't looked deeply enough into that PR.  There are a lot of good suggestions in there.  I'll take some time in the near future to provide my input.

**Comment by capellini** [comment]
A few more notes:
- In the most trivial and contrived case, we don't even need an `i18n.js` file anymore.  If the user wants to go with the defaults, then just `export default appWithTranslation(myApp)` in their `_app.js` and off you go.  Of course, at the very least they would want to define `otherLanguages` if they have a real-world test case.
- We can expose a `NextI18NextConsumer` which would allow users to take their full `next-i18next` configuration and use it anywhere in their app that they would like.

**Comment by capellini** [comment]
@kachkaev I read more through #42 - I will post my thoughts for that PR when I can carve out some time to formulate my comments - but I don't see how any of your (very interesting and thought-provoking) comments preclude the use of React's Context API.  When you get a moment, could you please help me understand?

**Comment by kachkaev** [comment]
Speaking of getting rid of `i18n.js` in the app, we can theoretically move all the confing to `server.js`. Any values that are needed to configure client-side i18n can be read from the initial store (`__NEXT_DATA__`), just as this is currently done for `initialI18nStore`.

**Comment by isaachinman** [comment]
Hey @capellini and @kachkaev, thanks for adding your opinions here. Unfortunately I have been extremely busy with professional work recently and haven't had time to read through this thread yet.

That being said, I envisioned a 1.x production-ready release of this package being more or less the same as it is now (class-based approach), but with proper TypeScript support. Besides bug fixes, TypeScript is the only thing on the unofficial roadmap for a prod release.

Converting the codebase to use context would (if at all) happen after that. So it'd be awhile down the line. Does that make sense, and do both of you agree?

**Comment by capellini** [comment]
On the one hand, I am very excited for the production release.

On the other hand, as this is a large change to the API, this would be a major breaking change, which may be a bit more disruptive to our users post-production release.  Major breaking changes happen, so it's not a show-stopper, but if we could sort it out before then, I think that would be ideal.

I don't think it would take much effort to create a quick prototype to give you and @kachkaev an idea of what things would look like.  If, after seeing it, we decide to not go forward with it, no big deal.

**Comment by isaachinman** [comment]
I should have been more clear: I foresee the 1.x release being a TypeScript refactor of the current codebase. Anything context-driven would be 2.x or later.

Off the top of my head, there will be problems - context will most likely have to be accompanied by a functional approach as well, as the config object and i18n instance are needed by more than just React components. I'm not even sure I want to go down the functional road, as it makes usage much more complex for the end user (in my opinion).

@capellini If you had an idea for a context-driven approach that didn't necessitate a functional approach as well, I'd be interesting in hearing about it.

**Comment by capellini** [comment]
> I foresee the 1.x release being a TypeScript refactor of the current codebase. Anything context-driven would be 2.x or later.

Thank you for clarifying.  I understand now.

After further consideration, I think that I had 2 things in mind when I started this issue:

1. Passing configuration into React components.  For this, perhaps there are solutions better than the Context API (for example, a HoC may be better in this case).
2. Making `next-i18next` the entry point and have `i18n.js` just be a configuration file (and, as @kachkaev mentioned, perhaps have it incorporated into `server.js`).

I think that 1 is something that we can discuss and resolve more quickly than 2, which seems to me to be more involved and will require much more discussion.

Since this issue is still in the early stages, I'll close this one and open up two distinct issues.

**Comment by capellini** [comment]
> I foresee the 1.x release being a TypeScript refactor of the current codebase. Anything context-driven would be 2.x or later.

@isaachinman one caveat - IMO #90 should be resolved before we consider a production release.  Not only does it help solve some `localeSubpaths` problems, but the API is more what one would expect from express middleware.  I know that you're working on it and that it's a big PR, and of course I don't mention this to give you an impression that I'm pressuring you.  It's just my opinion that this is a critical PR.  Of course, ultimately the repository is yours.  This is just my opinion.

**Comment by isaachinman** [comment]
@capellini Yes, I agree with that. I've created [a 1.0 milestone](https://github.com/isaachinman/next-i18next/milestone/2) for us to track related work.
