### ISSUE TITLE
configOverride as a function

### ISSUE THREAD

**Issue by jvcmanke** [isaachinman/next-i18next#1050]
## Is your feature request related to a problem? Please describe.
Right now to override the configuration on `appWithTranslation` I have to pass in the whole configuration all over again.

This means you have to import the configuration from the `next-i18next.config.js`, make changes and then pass it to `appWithTranslation`.

The config file doesn't support ES imports + access to a few runtime globals like `window`, so some configurations like checking if you are in the client to load `i18next-http-backend` or enable suspense, have to be done this way, or use the deprecated `process.browser`.

## Describe the solution you'd like
I think it would it would be much easier and cleaner if I could pass in a function as the `configOverride` parameter, that receives the config as `next-i18next` already loaded it and returned an overriden config.

Could even give access to the generated translations if that could be useful to some workflows.

## Describe alternatives you've considered
Creating a function using the import from the config file is my alternative at the moment.

**Comment by jvcmanke** [comment]
P.S.: I can come up with a PR if you agree.

**Comment by isaachinman** [comment]
That is not the purpose of `configOverride` – the purpose is to allow users to bail out when their config is not serialisable.

There shouldn't be any reason why you cannot check `window` inside `next-i18next.config.js`.

Let me know if you have any other questions.

**Comment by jvcmanke** [comment]
@isaachinman Why close this so fast?

Sure maybe the purpose is not exaclty what I need it to, but why can't we work on a solution?

When the config is not serializable is the same problem I have it would be nice to not have reimport the config when `appWithTranslation` can provide it for you.

Dev experience is what this library is all about, in my opinion, making it the easiest and cleanest possible goes a long way.

Nevermind the fact that this would also allow to create sort of a plugin/middleware ecosystem:

"want client side translations? here is a http-backend override"
"want to use suspense? here is a suspense override"

and so on.

The `window` thing was wrong by me, I had an error because of another thing and read it wrong.

**Comment by jvcmanke** [comment]
For `configOverride` to **also** accept a function like this `(defaultConfig: UserConfig) => UserConfig`.

**Comment by jvcmanke** [comment]
The purpose was to provide a better api for overriding configs, to avoid having to import the configuration file as it is typically out of scope of the `src` folder for example. It is not usual to have users import the config file and pass it back to the library.

I understand the need to serialize the configuration because the config file is not really present on the client. However, this leads to `typeof window === 'undefined'` always being false, as the config is always serialized on the server.

My thought process was to include only the serializable configs in the `next-i18next.config.js` and handle the non-serializable plus browser overrides with the `overrideConfig` prop.

As I said before it is usual for overrides to either provide the parsed or in this case serialized version of the configuration for me to override only what I need to, or to accept a partial configuration that will then be merged.
