### ISSUE TITLE
Translations don't load without `serverSideTranslations`

### ISSUE THREAD

**Issue by oceandrama** [isaachinman/next-i18next#1051]
## Describe the bug
It's written in README, that
```
By default, next-i18next will send all your namespaces down to the client on each initial request.
```
But if you don't add `serverSideTranslations` to each page no translations load

## Occurs in next-i18next version
8.1.1

## Expected behaviour
All translations should load without `serverSideTranslations`

**Comment by isaachinman** [comment]
The `serverSideTranslations` function is _required_ for `next-i18next` to work. The documentation does not indicate otherwise. Good luck!

**Comment by jvcmanke** [comment]
@oceandrama To complement, when you call `serverSideTranslations` without an array of namespaces, `next-i18next` will load all namespaces.

Actually looking at it if you pass an empty array, it also loads all namespaces, this might be a bug, is that so @isaachinman?

**Comment by jvcmanke** [comment]
Done. #1052
