### ISSUE TITLE
8.1.1 cannot import appWithTranslation anymore

### ISSUE THREAD

**Issue by LeunensMichiel** [isaachinman/next-i18next#1053]
## Describe the bug
In _app.tsx:
`import { appWithTranslation } from 'next-i18next'` 
throws an error that it cannot find `appWithTranslation`. It does find `withTranslation` though.

## Occurs in next-i18next version
8.1.1

## Expected behaviour
We should be able to import this, or the docs are outdated. Version 8.1.0 does not have this problem.

## OS (please complete the following information)
 - Device: [MBP 2016 15"]

**Comment by isaachinman** [comment]
Hi @LeunensMichiel – if you check the link below, you'll see a TS example running `next-i18next@8.1.1` in strict mode without any issues.

If you can provide a reproducible repo, please do let me know.

**Comment by 95Rawan** [comment]
> Hi @LeunensMichiel – if you check the link below, you'll see a TS example running `next-i18next@8.1.1` in strict mode without any issues.

@LeunensMichiel  I can't see any link here, could you please point me to a link that uses TS, I'm using it and I'm having issues.
