### ISSUE TITLE
Build error with v8.1.1 and 404 or 500 pages

### ISSUE THREAD

**Issue by dohomi** [isaachinman/next-i18next#1055]
## Describe the bug
I run locally development mode without an issue. But as soon I try to run build I receive following error:
```js
> Build error occurred
Error: Export encountered errors on following paths:
        /404
        /404.html
        /500
        /de/500
        /en/500
        /fr/500
        /it/500

```

## Occurs in next-i18next version
Most recent next-18next and NextJS version

I am not sure, do I need to add 404 or 500 pages with the language code? I currently did not configure it.

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by dohomi** [comment]
Its related to NextJS 10.0.0.8, after upgrade to latest canary the error is gone:
https://github.com/vercel/next.js/issues/22815
