### ISSUE TITLE
Using yml file instead json

### ISSUE THREAD

**Issue by shadowangle** [isaachinman/next-i18next#106]
Hi, 
I am using currently the react-i18next project. and need to change to next-i18next to fully support ssr. I tried to setting i18next to support yml file in react-i18next project i use @alienfast/i18next-loader to read yml file. But it seem to not support with next-i18next 

> ## react-i18next Settings
> ```
> const i18n = require('i18next')
> const LanguageDetector = require('i18next-browser-languagedetector')
> const resources = require('./locales')
> const reactI18nextModule = require('react-i18next')
> 
> const options = {
>   fallbackLng: 'th',
>  load: 'languageOnly',
>   resources,
>   debug: false,
>   saveMissing: true,
>   interpolation: {
>     escapeValue: false
>  },
>   react: {
>     wait: true,
>     nsMode: 'fallback',
>     bindI18n: 'languageChanged loaded'
>   }
> }
> 
> if (process.browser) {
 >  i18n
 >    .use(LanguageDetector)
  >   .use(reactI18nextModule)
>     .init({
>       fallbackLng: 'th',
>       resources,
>       debug: true,
>       interpolation: {
>         escapeValue: false
>       },
 >      react: {
 >        wait: true,
  >       nsMode: 'fallback',
 >        bindI18n: 'languageChanged loaded'
>       }
 >    })
> }
> 
> if (!i18n.isInitialized) i18n.init(options)
> ```

> ## next-i18next Settings
> ```
> const NextI18Next = require('next-i18next').default
> const resources = require('../static/locales')
> 
> const options = {
>   fallbackLng: 'en',
>   load: 'languageOnly',
>   backend: {
>     loadPath: '/locales/{{lng}}/{{ns}}.yml'
>  },
 >  debug: false,
>   saveMissing: true,
 >  localeStructure: '{{lng}}/{{ns}}',
>   interpolation: {
 >  escapeValue: false,
 >   formatSeparator: ',',
  >  format: (value, format, lng) => {
 > if (format === 'uppercase') return value.toUpperCase()
  > return value
  > }
 > }
> }
> 
> module.exports = new NextI18Next(options, resources)
> ```

I think something wrong in my setting . Any suggestion ?

**Comment by isaachinman** [comment]
Can you provide a reproducible repo? That will allow me to help much faster.

**Comment by isaachinman** [comment]
> in react-i18next project i use @alienfast/i18next-loader to read yml file

This is probably the root of your problem. [i18next-node-fs-backend](https://www.npmjs.com/package/i18next-node-fs-backend) already has a yml loader built in.

**Comment by shadowangle** [comment]
Ok i will try to use i18next-node-fs-backend. but now i can to provide u a reprodu repo. Thank you

**Comment by isaachinman** [comment]
If you continue to have problems and can provide a reproducible example, I will be more than happy to reopen this and take a look.
