### ISSUE TITLE
Not falling to fallback lang (default locale) if file does not exist in locale path

### ISSUE THREAD

**Issue by ronfogel** [isaachinman/next-i18next#1061]
## Describe the bug
Let's say I have someComponent.json file under en (which is the default locale) directory, If I dont have same file (even empty) under other languages, it will not fall back to the default locale translations.

## Occurs in next-i18next version
8.1.0

## Steps to reproduce
just delete (or dont create) translation file under locale different then the default locale

## Expected behaviour
Fallback to default locale translations

## Screenshots
As you can see, the cookies modal has text (from default locale) because it takes it from common.js (which I created under that locale with empty object)
while the rest are not resolved at all.
<img width="1520" alt="Screen Shot 2021-03-13 at 23 17 13" src="https://user-images.githubusercontent.com/16741829/111044624-48e3b780-8452-11eb-9790-71c5924024be.png">

## OS (please complete the following information)
 - Device: Mac OS 10.15.7
 - Browser: Chrome Version 89.0.4389.72 (Official Build) beta (x86_64)

## Additional context
I tried to upgrade to 8.1.1 but there are other issues there (it mix text from default locale and current locale where I do have text and it shouldnt mix/take from default locale)

**Comment by isaachinman** [comment]
You are able to pass any i18next options in that you'd like. `next-i18next` is just a thin wrapper over i18next. Good luck!

**Comment by ronfogel** [comment]
> You are able to pass any i18next options in that you'd like. `next-i18next` is just a thin wrapper over i18next. Good luck!

@isaachinman I did pass fallbackLng and other options as well, nothing worked...

**Comment by isaachinman** [comment]
@ronfogel The config options available to you are the exact same which are available to `next-i18next`. As I said, it's just a thin wrapper. Perhaps you should open an issue on the i18next repo?
