### ISSUE TITLE
Language detection for Safari doesn't work.

### ISSUE THREAD

**Issue by sroepges** [isaachinman/next-i18next#1062]
## Describe the bug
The automatic language detection doesn't work in Safari.

## Occurs in next-i18next version
I've used the next-i18next repo @ master branch and set the i18next version to 8.1.1

## Steps to reproduce
Just test the repo @ master and launch the example/simple app in Safari.

## Expected behaviour
The language should have changed to 'de'.

## OS (please complete the following information)
 - Device: MBP 2018 15" with macOS 11.2.3
 - Browser: Safari 14.0.3 (16610.4.3.1.7)

**Comment by pdugan20** [comment]
Seeing this in Firefox as well where the language briefly flashes in 'es' on page load before partially switching to 'en'. Reverting to 8.1.0 fixed it.

**Comment by sroepges** [comment]
With v8.1.0 it still doesn't work with Safari.

Firefox 86.0.1 works fine.
Chrome 89.0.4389.90 works fine.
Brave 1.21.76 works fine.

**Comment by sroepges** [comment]
I don't know why but Safari wants language + region codes as shown in the screenshot. In Chrome, both are excepted language + region and language only codes.

<img width="477" alt="Bildschirmfoto 2021-03-14 um 22 48 55" src="https://user-images.githubusercontent.com/47949518/111085585-48155900-8518-11eb-92d5-a46c429aa470.png">
<img width="473" alt="Bildschirmfoto 2021-03-14 um 22 49 54" src="https://user-images.githubusercontent.com/47949518/111085588-49468600-8518-11eb-8e02-3cc85a2a63a8.png">

**Comment by isaachinman** [comment]
Language detection is handled by NextJs internally. Any issues should be raised on the NextJs repo. Good luck!
