### ISSUE TITLE
Memoization of server side instance causes pages to be rendered in the wrong language

### ISSUE THREAD

**Issue by skrivanos** [isaachinman/next-i18next#1063]
## Describe the bug
Pages are only rendered in one language on the server when using getServerSideProps OR when using the dev server with getStaticProps.

Caused by:
 https://github.com/isaachinman/next-i18next/blob/c6fc2e3bdbee07b53cb4a0871cf1abcd372c7b26/src/createClient/node.ts#L9-L11

Added in commit:
https://github.com/isaachinman/next-i18next/commit/e7c5fadae448e005e88886f546c59324b055d2f0

## Occurs in next-i18next version
8.1.1

## Steps to reproduce
Run example/simple, click switch locale and reload the page.

## Expected behaviour
To use the correct locale.

## Screenshots
<img width="1061" alt="Screenshot 2021-03-13 at 19 20 07" src="https://user-images.githubusercontent.com/87463/111039956-23928180-8431-11eb-8e30-9e0601db84e8.png">

## Additional context
This doesn't cause issues in production when using `getStaticProps` because the translations are stored upon build, but it messes up pages using getServerSideProps (they will always render in whatever language the i18n instance was firstly created as).

**Comment by sigo** [comment]
Hit the same today. I can also confirm this issue.

Temporary workaround is downgrading and pinning `next-i18next@8.1.0` until bugfix.

**Comment by isaachinman** [comment]
cc @adrai

**Comment by adrai** [comment]
I have not much Next.js knowledge, so I don't know why this warning exactly occurs.
Maybe this is the reason, why there was always a new instance created before....
will try to create a PR with cloneInstance... asap

**Comment by adrai** [comment]
@skrivanos I was not able to reproduce the warning with my PR can you also confirm?

**Comment by skrivanos** [comment]
@adrai Seems to work, however I'm not sure I'm a fan of creating a new instance each request. I tried this

```
  if (!instance) {
    instance = i18n.createInstance(config)
  } else if (config.lng && config.lng !== instance.language) {
    instance.changeLanguage(config.lng)
  }
```

Which seems to have done the trick as well... Are there any downsides to this?

**Comment by adrai** [comment]
creating a clone on every request was also done when used i18next-http-middleware in older versions of next-i18next...
beside this, i don't know if there is more than just the language that changes, if so changeLanguage should work too

**Comment by isaachinman** [comment]
@skrivanos I'm in favour of cloning, as I'm not sure how `changeLanguage` would handle concurrent reqs.

@adrai Is the entire point of cloning vs `createInstance` to prevent network requests to upstream data sources?

**Comment by adrai** [comment]
> @adrai Is the entire point of cloning vs `createInstance` to prevent network requests to upstream data sources?

yes

**Comment by kachar** [comment]
We were experiencing the same problem on `8.1.1`, migrating to `8.1.2` solved it. :tada: 

The server did cache the language initially, so the first language to be shown was always the initial one on SSR. The option `defaultLanguage` was not taken in account.
