### ISSUE TITLE
Not working with lowercase country code

### ISSUE THREAD

**Issue by qvil** [isaachinman/next-i18next#1066]
## Describe the bug

Not working with lowercase country code(en-us). 

I want to use a lowercase URL plan. So I add locales with lowercase to next-i18next.config.js. But not translated.

Just in case using country code with uppercase(en-US)

## Occurs in next-i18next version

- "next": "^10.0.8"
- "next-i18next": "^8.1.1"

## Steps to reproduce

- Repository: https://github.com/qvil/next-boilerplate
- Demo: https://next-boilerplate.vercel.app/en-uk/i18n-lowercase

## Expected behavior

I expect to translate, work normally.

## Screenshots

![demo](https://user-images.githubusercontent.com/8034392/111095194-467f7b80-8580-11eb-8e02-1fc7d16083ef.gif)

## OS (please complete the following information)
 - Windows 10 pro
 - Browser: Chrome 89.0.4389.82

## Additional context

I guess country code recognize with uppercase. Because I saw the i18n conosle.log.

**Comment by isaachinman** [comment]
Not sure if this is on the `i18next` side, or the NextJs side, but I have observed this behaviour previously. The short answer is that: (1) those are invalid locales (with lowercase), and (2) this is not handled by `next-i18next`.

**Comment by DuckThom** [comment]
To those stumbling upon this issue that don't want to use uppercase region codes in their urls: i18next provides a setting to allow lowercase region (ISO-3166) codes to be used: `lowerCaseLng` (See: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources )

It can be used like this with next-i18next:

```
module.exports = {
    i18n: {
        defaultLocale: 'nl',
        locales: ['en-us', 'nl'],
        lowerCaseLng: true
    }
};
```

**Comment by rossjohnsonMP** [comment]
Resurrecting this from the dead @DuckThom @isaachinman  but looks like this is no longer supported/not working?

```
warn  - Invalid next.config.js options detected: 
  - The value at .i18n has an unexpected property, lowerCaseLng, which is not in the list of allowed properties (defaultLocale, domains, localeDetection, locales).
 ```
 
 Was working on next 11 and next-i18next 10.3.0 but on 13 and 13 its not
