### ISSUE TITLE
Typescript error when building

### ISSUE THREAD

**Issue by LordTep** [isaachinman/next-i18next#1072]
## Describe the bug
I get a type error from typescript when using next build: 

Type error: Type '((props: AppProps) => Element) & NonReactStatics<ComponentType<any>, {}>' is not assignable to type 'ElementType<P>'.
  Type '((props: AppProps) => Element) & NonReactStatics<ComponentType<any>, {}>' is not assignable to type 'FunctionComponent<P>'.   
    Types of parameters 'props' and 'props' are incompatible.
      Property 'pageProps' is missing in type 'Record<string, unknown> & { children?: ReactNode; }' but required in type 'AppProps'.  

`
  59 |   }
  60 | 
> 61 |   return hoistNonReactStatics(AppWithTranslation, WrappedComponent)
     |   ^
  62 | }
  63 | `

## Occurs in next-i18next version
8.0.2

## Steps to reproduce
Not sure, we have a next project with next-i18next and typescript. It throws this error when trying to build.

## Expected behaviour
No error

## OS (please complete the following information)
 - Device: Razer Blade 15
 - Browser: N/A

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!

**Comment by LordTep** [comment]
After succesfully creating a new project with the same npm packages I just tried bumping the versions and got it to work. I couldnt pinpoint the problem to two specific packages and versions that did not work well unfortunately. But here's a screenshot of the diff of my package.json. Before with error and after that works. Thanks for a great package!

![image](https://user-images.githubusercontent.com/20333891/111162006-00381580-859c-11eb-9707-415184798fac.png)
