### ISSUE TITLE
Typescript - serverSideTranslations locale type shall accept string | undefined

### ISSUE THREAD

**Issue by njarraud** [isaachinman/next-i18next#1078]
## Is your feature request related to a problem? Please describe.
The current code throws a typescript error for _locale_:
```
export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});
```
GetStaticProps locale has the type string or undefined but serverSideTranslations currently only accepts string.

## Describe the solution you'd like
Maybe it would be possible to update serverSideTranslations so that if locale is undefined then it uses the default local provided in the config file.

_[next-i18next v.8.1.2]_

**Comment by isaachinman** [comment]
@njarraud The `locale` argument cannot be `undefined` – the absence of locale doesn't mean we are in the default locale, it means that NextJs i18n is not enabled.

**Comment by njarraud** [comment]
You are very quick at closing posts...

Did you even try with your simple example? You will see that it is not valid:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/45501180/111707549-22d27300-88a9-11eb-83a7-e5a7bef1b3be.png">

**Comment by isaachinman** [comment]
Hi @njarraud – I understand that NextJs has typed `locale` as `string | undefined`, however, _this package_ does not accept `locale` as `undefined`.

Feel free to use `locale as string`, or whatever you'd like!

**Comment by yovanoc** [comment]
Yes you're right but when creating a next lib we have to follow their rules. If you want just a 
```ts
if (!locale) throw new Error...
```
but it's a pain in the ass to do a global refactor to our codebase to replace all serverSideTranslations ..

**Comment by isaachinman** [comment]
@yovanoc Sure, that seems like an easy and useful PR.
