### ISSUE TITLE
next-i18next tried to access @babel/runtime, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by DStoyanoff** [isaachinman/next-i18next#1079]
Hello guys, I'm experiencing an issue in combination with Yarn2 and PnP.

## Describe the bug
When referencing next-18next, we get the following error from yarn:
```
error - ../../.yarn/$$virtual/next-i18next-virtual-9e82de204c/0/cache/next-i18next-npm-8.1.2-6f33ac777a-285a3d0a52.zip/node_modules/next-i18next/dist/esm/appWithTranslation.js:2:0
Module not found: next-i18next tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/runtime (via "@babel\runtime\helpers\defineProperty")
```

## Occurs in next-i18next version
8.1.1

## Steps to reproduce
I don't have a repro repository, but here is our setup:
We are using [yarn2 with PnP](https://yarnpkg.com/features/pnp#pnp-loose-mode) which is very strict in regards to what is being referenced (unless you use it with loose mode). Every time a library is used, without being listed as a dependency, it would throw this error.

## Expected behaviour
It should not throw an error

## OS (please complete the following information)
 - Windows 10

## Additional context
Workarounds:
The two options to workaround the issue, while fixed are:

- change pnp to loose mode (haven't tested, but should work in theory)
- add a configuration for this specific dependency problem in .yarnrc.yml
```
packageExtensions:
  next-i18next@*:
    dependencies:
      '@babel/runtime': '*'
```

**Comment by isaachinman** [comment]
Haven't encountered this before. Might need to move `@babel/plugin-transform-runtime` from devDeps into dependencies? PRs welcome.

**Comment by DStoyanoff** [comment]
It's included in the JS output, so yes, I suppose it should be a dependency, and not a dev dependency

**Comment by isaachinman** [comment]
Not entirely sure it's necessary anymore – may be a remnant of v7 and previous.

**Comment by yovanoc** [comment]
Have experienced the same today ...
![image](https://user-images.githubusercontent.com/7302317/112658956-373be000-8e54-11eb-9b9f-dc1b7db36cec.png)

**Comment by isaachinman** [comment]
@yovanoc What version of `next-i18next` are you on?

**Comment by yovanoc** [comment]
8.1.3

**Comment by davidcalhoun** [comment]
Another workaround that might work, from what I've encountered with these sorts of errors:

```diff
-yarn next build
-yarn pnpify next build
```

More info: https://next.yarnpkg.com/advanced/pnpify

**Comment by isaachinman** [comment]
@davidcalhoun Would be great to support pnp properly, and I think it should be fairly trivial. PRs welcomed!
