### ISSUE TITLE
hot reload

### ISSUE THREAD

**Issue by dimensi** [isaachinman/next-i18next#108]
Every time i change .json files i need fully restart server, have we there any way to solve this problem?

**Comment by isaachinman** [comment]
Sounds like a question for [react-i18next](https://github.com/i18next/react-i18next), not `next-i18next`. There are ways of forcing a reload, but I don't think we'll do it here.

**Comment by dimensi** [comment]
@isaachinman for hot reload need add code where i18n initing
https://github.com/i18next/react-i18next/issues/6#issuecomment-185300536
we need add hotreload in your package, not react-i18next

**Comment by isaachinman** [comment]
You can feel free to submit a PR with [i18next-resource-store-loader](https://www.npmjs.com/package/i18next-resource-store-loader) but it's not something I will be working on myself. Typically locale content is managed by non-devs, etc, and involves full deployments.

**Comment by felixmosh** [comment]
If still needed, I've developed [`i18next-hmr`](https://github.com/felixmosh/i18next-hmr) in-order to hot reload **client** & **server** when translations are changes... look it out :]
