### ISSUE TITLE
Can't use next-i18next with SSG

### ISSUE THREAD

**Issue by fritzzu** [isaachinman/next-i18next#1083]
Hi, in the readme it's written that next-i18next fully supports SSG but if i try to run "next export" task in order to generate the site I got: 
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment

Any help? 
Thanks.

**Comment by rintala** [comment]
Pretty sure the latest version does not support SSG unfortunately.

**Comment by isaachinman** [comment]
Hi @fritzzu – SSG is not the same as `next export`. The error `i18n support is not compatible with next export` comes from NextJs directly, not `next-i18next`.

If you'd like to generate a static website, please use `getStaticProps`. Good luck!

**Comment by miloshavlicek** [comment]
@isaachinman I use getStaticProps, however, I face this issue. What is the solution?

**Comment by isaachinman** [comment]
This issue isn't about `getStaticProps`, it's about `next export`.

**Comment by zhigang1992** [comment]
to get it working with `next export`

move your pages into folder `[lang]`.

```
export const getStaticProps = async ({ params: {lang} }) => ({
  props: {
    ...await serverSideTranslations(lang, ['second-page', 'footer']),
  },
})

export const getStaticPaths = async () => {
  return {
    paths: ["en", "de"].map((lang) => ({ params: { lang } })),
    fallback: false,
  };
};

```

But then you'd need to handle fallback on root.

**Comment by adrai** [comment]
@fritzzu in case you missed it: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd

**Comment by Abrar-Abdulwahed** [comment]
@isaachinman @adrai  I've faced problem as the title here, i cant use i18next with SSG,
It works only with one language, and the other lang doesnt work, and appear 404 page, 
On the other hand, when i'm in a ssg page('en/blogs/[id]') and trying to switch lang from there, this error shows up
![image](https://user-images.githubusercontent.com/96573043/232753661-cbeadf53-2165-4634-bee6-d20bacd3eaa8.png)

please help me

**Comment by adrai** [comment]
@Abrar-Abdulwahed seems a different issue...
Please provide a minimal reproducible example repository and create a new issue.
