### ISSUE TITLE
LocaleStructure not compatibility single brackets for namespace

### ISSUE THREAD

**Issue by vechnii2007** [isaachinman/next-i18next#1090]
## Describe the bug
I faced localeStructure and interpolation problem
my json is for variables with single brackets. 
like this
`"test": "Why {appName}?",`
and i used in code 
`{t("test", { appName: process.env.NEXT_PUBLIC_APP_NAME })}`

in the config it was stated that

```
localeStructure: "{lng} / {ns}",
    interpolation: {
        prefix: "{",
        suffix: "}",
    },
```
now such an entry does not work, I looked in the code and found that in
`node_modules/next-i18next/dist/commonjs/config/createConfig.js`
you are doing a replacement
`var defaultLocaleStructure = localeStructure.replace ('{{lng}}', lng) .replace ('{{ns}}', defaultNS);`
If you change it to single brackets or add an entry, then everything will work.
## Occurs in next-i18next version
8.1.2

## Steps to reproduce
like this. Use single brackets in common.json
`"test": "Why {appName}?",`
and i used in code 
`{t("test", { appName: process.env.NEXT_PUBLIC_APP_NAME })}`

## Expected behaviour
Expected result, that i can use single or more brackets for localeStructure and interpolation
## OS (please complete the following information)

MacOS 
Chrome 89.0.4389.90

**Comment by isaachinman** [comment]
@vechnii2007 The `localeStructure` config option is completely separate to what character i18next uses for interpolation. The `localeStructure` option is just used to declare how the localisation files are arranged in the directory. The `next-i18next` package doesn't consume `interpolation.prefix` or `interpolation.suffix` whatsoever, but that [is indeex](https://www.i18next.com/translation-function/interpolation#additional-options) the correct config object.

**Comment by zachguo** [comment]
I ran into the exact same issue.

A simple config like this would turn `t(...)` off across the site without warning or error.
```
module.exports = {
  i18n: {
    locales: ['en'],
    defaultLocale: 'en'
  },
  interpolation: {
    prefix: "{",
    suffix: "}",
  }
}
```

To make custom `prefix` and `suffix` work, I had to change `localeStructure` to match the new prefix and suffix pattern like the suggestion here https://github.com/isaachinman/next-i18next/issues/620
However, this broke `next-i18next` and I had to change the hardcoded `replace` as @vechnii2007 said. Then everything started to work properly.

**Comment by sbekrin** [comment]
hey @isaachinman, the underlying issue is that `next-i18next` [validates `localeStructure`](https://github.com/isaachinman/next-i18next/blob/7474c937a0ea049670786df6f784c6f713b12bfc/src/config/createConfig.ts#L59) assuming it uses double brackets syntax, however it depends on `interpolation` config on `i18next` side. It results in `defaultNSExists` check to always fail in dev mode with non-standard `interpolation.[prefix|suffix]`.

The only workaround for it at the moment is to create an empty file based on custom `[prefix|suffix]` options e.g. `./public/locales/%{lng}/%{ns}.json` (yes, with literlly that being the filesystem path) to trick it into passing the check.

**Comment by isaachinman** [comment]
@sbekrin @vechnii2007 Yep, that's correct – I misspoke when first commenting on this issue. The `interpolation` option for the i18next config is _not_ consumed in `localeStructure`, but it probably makes sense to do so. A PR would be welcome!

**Comment by ahakem** [comment]
@sbekrin your workaround worked with me, thank you.

**Comment by ahakem** [comment]
@zachguo this worked with me as well as you tried, but @sbekrin workaround is nice for now, till we made a PR.
