### ISSUE TITLE
Cannot Import `serverSideTranslations`

### ISSUE THREAD

**Issue by DovahBrownies** [isaachinman/next-i18next#1092]
## Describe the bug
When I try to **just import** `import { serverSideTranslations } from 'next-i18next/serverSideTranslations'` into any page, I'm immediately hit with `Module not found: Can't resolve 'fs'`.

I've read around and I know that the function is only supposed to be invoked on the SS. But I can't even import it without a crash.

Any hints/help would be greatly appreciated.

## Occurs in next-i18next version
```
"i18next": "^19.9.2",
"next": "^10.0.9",
"next-i18next": "^8.1.2",
```

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.
```
import React from 'react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

const Page = () => {
   return (<p>hello</p>);
}

export default Page
```

**Comment by isaachinman** [comment]
Please provide a reproducible repo.

**Comment by annbeemsterboer** [comment]
Maybe some comments in this issue are of use to you https://github.com/isaachinman/next-i18next/issues/1040#issuecomment-802843756

It seems like you are importing `serverSideTranslations` without using it.

**Comment by DovahBrownies** [comment]
> Maybe some comments in this issue are of use to you [#1040 (comment)](https://github.com/isaachinman/next-i18next/issues/1040#issuecomment-802843756)
> 
> It seems like you are importing `serverSideTranslations` without using it. When you are not calling it (in `getStaticProps` or `getServerSideProps`), it will be included in the client-side bundle and gives you this error.

💯
