### ISSUE TITLE
react-i18next:: You will need pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by LauraBenz** [isaachinman/next-i18next#1093]
## Describe the bug
There is an ongoing discussion under a [closed issue](https://github.com/isaachinman/next-i18next/issues/718#issuecomment-800891006) which affects several users including me.
Translations are not available after following the instructions in the README and the example files.

## Occurs in next-i18next version
next: 10.0.8,
next-i18next: 8.1.1

**Comment by isaachinman** [comment]
There are a number of ways to arrive at that error, which is why a number of users are experience the same output. If you believe you have found a bug within the source code of `next-i18next`, please do feel free to open an issue. Good luck!

**Comment by giacomoalonzi** [comment]
Same here, I've followed the docs again and again.
"next": "10.0.9",
"next-i18next": "^8.1.2",

**Comment by pot-code** [comment]
@giacomoalonzi I happened to have the same problem, which turns out that I have accidentally imported the `react-i18next` rather than `next-i18next`.

**Comment by giacomoalonzi** [comment]
@pot-code already checked. This is not my case. :\

**Comment by lemmingucwcz** [comment]
I also encountered this problem and spent several hours digging through next-i18next code and my own code using react-i18next. I found when I add:

`const { initReactI18next } = require('react-i18next');`

to next-i18next.config.js and use this module in config:

`module.exports = {
  (...) use: [  initReactI18next ],
}`

all starts working like a charm. But this should be done by next-i18next every time. Possibly some version incompatibility?

"react-i18next": "^11.8.11"
"next-i18next": "^8.1.2",

**Comment by giacomoalonzi** [comment]
ok, this is my config

```
next.config.js
const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
};

```

```
next.config.js
const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
};

```
next-i18next.config.js
module.exports = {
  initReactI18next: {
    defaultLocale: 'it',
    locales: ['it'],
  },
};
```

```
__app.tsx
import { appWithTranslation } from 'next-i18next';
function MyApp({ Component, pageProps }: AppProps) {
  return (
        <Component {...pageProps} />
  );
}

export default appWithTranslation(MyApp);
```

this is my config, followed the docs. :\

**Comment by talok** [comment]
@giacomoalonzi Check your page-level getServerSideProps too. Ensure that props _nextI18Next sent into your component.

**Comment by shtabnoy-fyndiq** [comment]
Hello guys. I have the same config as @giacomoalonzi wrote above, and I also followed the rules from the Readme. 
Tried to provide getServerSideProps to page-level components and it gives an error in the terminal
```
error - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:36:0
Module not found: Can't resolve 'fs'
```

**Comment by giacomoalonzi** [comment]
I totally forgot to use the SSR function. I've added

```
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
export const getServerSideProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'car-types'])),
  },
});
```

and all works! Thanks for the support guys!

**Comment by Braweria** [comment]
> SUMMARY: Confusion (at least in my case) was that useTranslation is contained in both react -i18next and next-i18next. I started introducing Next.JS into older code that used react-i18next. You have to either switch to next-i18next completely, or you have to configure next-i18next to properly initialize react-i18next as shown below:
> 
> I also encountered this problem and spent several hours digging through next-i18next code and my own code using react-i18next. I found when I add:
> 
> `const { initReactI18next } = require('react-i18next');`
> 
> to next-i18next.config.js and used this module in config:
> 
> `module.exports = { (...) use: [ initReactI18next ], }`
> 
> all starts working like a charm.

could you show your whole module code perhaps?
