### ISSUE TITLE
I got an error `Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL`

### ISSUE THREAD

**Issue by martin-badin** [isaachinman/next-i18next#1095]
Hi all,

I hope that I find a resolution to my issue here. I started using this package in my project. I did just one thing and that I wrap my app to `appWithTranslation`. After that, I got the error `Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL`. I am looking for some solution the whole day but I am no able to find anything.

Please, can anyone help me with this?

```
beforeAll(async () => {
    spyOn(common, 'testFunction');
    await asyncFunction();
});

fit('should call test function', () => {
    expect(common.testFunction).toHaveBeenCalledWith('param');
});
```

```
"jasmine": "^2.9.0",
"next": "^10.0.5",
"next-i18next": "^8.1.2",
"react": "^17.0.1",
"react-dom": "^17.0.1",
```

**Comment by isaachinman** [comment]
Hi @martin-badin – this is an issue tracker and is meant to track bugs and feature requests. Please post help requests on StackOverflow or similar. Good luck!
