### ISSUE TITLE
Translations in Dynamic Error pages 

### ISSUE THREAD

**Issue by ruhaim** [isaachinman/next-i18next#1096]
## Is your feature request related to a problem? Please describe.

**Few facts**
-next-i18next lib needs to be initialized via getServerSideProps() or getStaticProps() fns.
-NextJS only allows getStaticProps() OR getInitialProps() for a custom _error page.

**My Requirement**
-My error page requires to be translation enabled AND dynamically generated (either via getServerSideProps() or getInitalProps()).

## Describe the solution you'd like
Have a way to initialize i18next outside of getServerSideProps() or getStaticProps()

## Describe alternatives you've considered
Ive tried to mix and match the getStaticProps and getIntialProps, still build fails :(

**Comment by isaachinman** [comment]
@ruhaim This is a great point, and something I discussed recently with @tomevans18. However, `next-i18next` does not support `getInitialProps` and doesn't have control over NextJs internals, so issue should actually be placed on the main NextJs repo. It seems very reasonable to want to use `getServerSideProps` on your error page. Thanks!
