### ISSUE TITLE
Instructions on how to build Docker image

### ISSUE THREAD

**Issue by tiagostutz** [isaachinman/next-i18next#1097]
## Is your feature request related to a problem? Please describe.
I struggled building a NextJS Docker image because the provided Docker image doesn't have the `COPY --from=builder /app/next-i18next.config.js ./` instruction. So I had problems with `Initial locale argument was not passed into serverSideTranslations` and `next-i18next was unable to find a user config`

## Describe the solution you'd like
There could be in the README instructions a section "Deploying with Docker" that has the instructions on how to put the config file in the build process

## Describe alternatives you've considered
This could be:
```
## Deployment Tips
When building your Docker image following NextJS instructions, please remember to:
- uncomment the line `COPY --from=builder /app/next.config.js ./`
- add the following line right above that: `COPY --from=builder /app/next-i18next.config.js ./`
```

## Additional context
N/A

**Comment by isaachinman** [comment]
Of course, when building in Docker, you'll need to copy `next-i18next.config.js` just like all other source files. If you feel mentioning this is relevant, feel free to open a PR to update the documentation.

**Comment by fangyibkk** [comment]
Encounter the same problem and found this really help. Thanks a lot, I will create the PR.
