### ISSUE TITLE
Locales containing dashes are not loaded

### ISSUE THREAD

**Issue by totalolage** [isaachinman/next-i18next#1098]
## Describe the bug
If the locale name contains a dash ("en-gb" in my example"), the translations are not loaded.

## Occurs in next-i18next version
8.1.2

## Steps to reproduce
Just change one of the locales to include a dash and it will break.

## Expected behaviour
Locales should be loaded from the corresponding path regardless of what their names look like.

## OS
 - Device: Desktop Linux Arch, also tested on iPhone 8 and ZTE Axon 10 pro
 - Browser: Chrome/89.0.4389.91, Safari 14, Vivaldi 3.7.2221.27

**Comment by isaachinman** [comment]
This issue has been raised and answered several times. `en-gb` is not a valid locale. You should use `en-GB`. This has nothing to do with `next-i18next` and cannot be "fixed" from within this repo. Good luck!

**Comment by totalolage** [comment]
> This issue has been raised and answered several times. `en-gb` is not a valid locale. You should use `en-GB`. This has nothing to do with `next-i18next` and cannot be "fixed" from within this repo. Good luck!

Yet "en_gb" seemingly is valid? I think a warning message would be warranted when trying to load an unsupported locale.

**Comment by isaachinman** [comment]
@totalolage Yeah that's a fair point, but as I mentioned, this is handled by upstream packages – i18next and NextJs. You'd have to pass this request along on those respective repos.
