### ISSUE TITLE
Languages do not load on default locale

### ISSUE THREAD

**Issue by totalolage** [isaachinman/next-i18next#1099]
## Describe the bug
Calling `i18n.loadLanguages` on the default locale does not load the requested languages.

## Occurs in next-i18next version
8.1.2

## Steps to reproduce
[sandbox](https://codesandbox.io/s/github/totalolage/next-i18next-debug)

## Expected behaviour
Locales should be loaded (as they were before v8)

## OS (please complete the following information)
 - Device: Desktop Linux Arch
 - Browser: Chrome/89.0.4389.91

**Comment by isaachinman** [comment]
That is correct. You would need to add the `i18next-http-backend` plugin for client side loading of translation data.
