### ISSUE TITLE
Conditionally load NS globally

### ISSUE THREAD

**Issue by bastischulz** [isaachinman/next-i18next#1100]
Hi guys,
I have had a tiny problem since one of the latest updates.

I'd like to load a second namespace globally, without writing it on every page seperately. I know, there is an option to preload multiple NS's initially, but the 2nd NS is connected a condition (authentication).

Previously I used the _app's 'getInitialProps' method, but I can't get it to work again with the latest version of nexti18next.

Here is the example code of the previously working solution.

```
const mergeRequiredNameSpaces = (pageProps, isAuth) => {
    const defaultNamepaces = [
        'common',
        !isAuth && 'guest'
    ].filter(Boolean)

    return {
        ...pageProps,
        namespacesRequired: pageProps.namespacesRequired
            ? [...defaultNamepaces, ...pageProps.namespacesRequired]
            : defaultNamepaces
    }

const globalGetInitialProps = async globalCtx => {
    const { Component, ctx } = globalCtx
    const componentPageProps = Component.getInitialProps ? (await Component.getInitialProps(globalCtx)) : {}

    const isAuth = await processToken(ctx, ctx.apolloClient)

    const pageProps = mergeRequiredNameSpaces(componentPageProps, isAuth)
    pageProps.initialSnacks = pageProps.initialSnacks && pageProps.initialSnacks.length === 0
        ? null
        : pageProps.initialSnacks
    return { pageProps }
}
```

**Comment by isaachinman** [comment]
You should be able to solve this by writing your own helper function or HOC. Good luck!
