### ISSUE TITLE
Memory leak caused by cloning the i18n instance

### ISSUE THREAD

**Issue by dcodus** [isaachinman/next-i18next#1101]
## Describe the bug
The #1073 pr introduced a significant memory leak when using `getServerSideProps`.

## Occurs in next-i18next version
[v8.1.2](https://github.com/isaachinman/next-i18next/releases/tag/v8.1.2)

## Steps to reproduce
1. using [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple) from repo.
2. use `getServerSideProps` instead of `getStaticProps` in [index.js](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L42)
3. run `yarn build` on the example repo
4. start server in [debug mode](https://nextjs.org/docs/advanced-features/debugging#step-1-start-nextjs-in-debug-mode). In your `package.json`
```js
"start": "NODE_OPTIONS='--inspect' next start -p ${PORT:=3000}"
```
5. In chrome open `chrome://inspect` url then click on inspect
<img width="257" alt="Screen Shot 2021-03-28 at 2 28 15 PM" src="https://user-images.githubusercontent.com/12925816/112763310-ece06d80-8fd1-11eb-8497-777e9d8fd884.png">

6. Tab to the `Memory` tab.
7. Load `localhost:3000`. Take a snapshot (base).
8. Use [loadtest](https://www.npmjs.com/package/loadtest) or any other load testing library to hit localhost:3000 (2000 total requests). Send 1000 requests, stop the load, click collect garbage, take snapshot. Inspect the retained data.
9. Send another 1000 requests, stop the load test, click collect garbage, take a snapshot. Inspect the retained data. NOTE: it will take some time for the snapshot because of the tree created by the leak.
10. Observer the memory significantly increased and the GC never releases it.
11. Inspect the retained objects and you will see the i18n references.

## Expected behaviour
After stopping the loadtest and manually triggering GC (or waiting for it to auto trigger) memory should go back to baseline (plus any additional memory used post first request).
This is the behaviour in [v8.1.1](https://github.com/isaachinman/next-i18next/releases/tag/v8.1.1)

## Screenshots
As you can see the exact same test with the only difference being the version does not show a memory leak.
In 8.1.1 we go from 11.3 -> 12.3
In 8.1.2 we go from 11.3 -> 66.3

**8.1.2**
<img width="894" alt="Screen Shot 2021-03-28 at 2 47 22 PM" src="https://user-images.githubusercontent.com/12925816/112764002-c243e400-8fd4-11eb-9d1f-9400d95520ac.png">
<img width="898" alt="Screen Shot 2021-03-28 at 2 42 18 PM" src="https://user-images.githubusercontent.com/12925816/112764006-c40da780-8fd4-11eb-9c06-d803ffd31dca.png">
<img width="894" alt="Screen Shot 2021-03-28 at 2 42 08 PM" src="https://user-images.githubusercontent.com/12925816/112764007-c53ed480-8fd4-11eb-8445-1d253ae46383.png">
<img width="891" alt="Screen Shot 2021-03-28 at 2 41 57 PM" src="https://user-images.githubusercontent.com/12925816/112764008-c5d76b00-8fd4-11eb-8d25-e9a76b0c756f.png">

**8.1.1**
<img width="895" alt="Screen Shot 2021-03-28 at 2 51 52 PM" src="https://user-images.githubusercontent.com/12925816/112764125-35e5f100-8fd5-11eb-9b2c-3999372d15b5.png">

## OS (please complete the following information)
 - Device: [MacBook Pro (16-inch, 2019)]
 - Browser: [Chrome Version 89.0.4389.90]

**Comment by dcodus** [comment]
cc @adrai

**Comment by isaachinman** [comment]
I would be fine with complete reverting the clone PR. In my opinion, the i18next backend itself should handle memoisation/caching.

**Comment by dcodus** [comment]
Reverting to 8.1.0 is probably worst for anyone using custom backends. As you can see from the screenshots below, our servers simply crash on 8.1.0 because of all the extra calls being made. We support 20+ locales and in our case a memory leak is more manageable until we find a proper solution.

<img width="1025" alt="Screen Shot 2021-03-28 at 5 13 14 PM" src="https://user-images.githubusercontent.com/12925816/112768241-18228700-8fe9-11eb-9bf4-b9ef764b067d.png"> 

<img width="1027" alt="Screen Shot 2021-03-28 at 5 13 22 PM" src="https://user-images.githubusercontent.com/12925816/112768238-1658c380-8fe9-11eb-8410-58afa00dadd1.png">

**Comment by adrai** [comment]
@dcodus Do I understand correctly?
Creating a clone creates a memory leak, but creating a new instance not?

**Comment by adrai** [comment]
@dcodus sorry if I'm asking, but how should the code be changed to work with getServerSideProps ? I'm not a next.js expert... i'm not able to see the memory leak with the original example.

**Comment by adrai** [comment]
Can you try with this change?

![image](https://user-images.githubusercontent.com/1086194/112797214-5cef0200-906b-11eb-91ec-081340fd238b.png)

**Comment by adrai** [comment]
created a PR: https://github.com/isaachinman/next-i18next/pull/1108

**Comment by dcodus** [comment]
@adrai I tried your changes locally and it's looking promising! I'm trying against our app now, will let you know soon.

**Comment by dcodus** [comment]
@adrai Can confirm this fixes the leak for us! Not sure if this has any other side effects but our servers are stable and ssr works as expected and no leak detected after several thousand requests.

**Comment by dcodus** [comment]
> @dcodus sorry if I'm asking, but how should the code be changed to work with getServerSideProps ? I'm not a next.js expert... i'm not able to see the memory leak with the original example.

Simply change [this](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L42) function name from `getStaticProps` to `getServerSideProps`

**Comment by adrai** [comment]
> ...Not sure if this has any other side effects...

If there are concurrent request issues, the singleton fix will not work, and we need to keep cloneInstance...
As said, I don't know how next.js handles or not handles this.
That's why cloneInstance is for sure more safe.

**Comment by adrai** [comment]
I have another idea...

**Comment by adrai** [comment]
alternative: #1109

**Comment by isaachinman** [comment]
> Reverting to 8.1.0 is probably worst for anyone using custom backends. As you can see from the screenshots below, our servers simply crash on 8.1.0 because of all the extra calls being made.

@dcodus Right, but I'm not sure you understood my point. If your i18next backend used a in-mem or fs-based cache, it wouldn't be an issue at all.

@adrai Is right that a global singleton is not an option due to concurrency.

However, [this line](https://github.com/isaachinman/next-i18next/pull/1109/files#diff-efdc11553404a81e7b6f986b1b13dafcbe4c0400d71c0ae8c61f92607a8574daR12) is essentially a crude form the of caching/memoisation that I was suggesting live inside the i18next backend in the first place.

Let me know your thoughts @adrai and @dcodus – regardless of the implementation we choose, I'm confident we can get this fixed quickly.

**Comment by adrai** [comment]
Ok, then I suggest to go back to the createInstance implementation (v8.1.0)  and use a caching backend, like [here](https://github.com/locize/next-i18next-locize/tree/local-caching#optional-server-side-caching-to-filesystem)

**Comment by adrai** [comment]
i fixed it with cloneInstance ;-)

**Comment by adrai** [comment]
here we go: https://github.com/isaachinman/next-i18next/pull/1110

**Comment by dcodus** [comment]
@adrai Looks good on my end! No memory leaks detected with this fix

**Comment by isaachinman** [comment]
Published in v8.1.3. @dcodus Can you please test the release and see if the issue is resolved?

**Comment by dcodus** [comment]
@isaachinman @adrai Everything is looking great in prod, our servers are very happy! On behalf of my team and myself thank you for the fix and for being awesome! Much appreciated!

**Comment by isaachinman** [comment]
Great. If you are indeed using OSS for that volume of prod traffic, I would encourage you sponsor packages, or contribute PRs in the future.
