### ISSUE TITLE
useTranslation hook does not allow an array of namespaces

### ISSUE THREAD

**Issue by austinhale** [isaachinman/next-i18next#1102]
## Describe the bug
In the [i18next](https://react.i18next.com/latest/usetranslation-hook) documentation, it says you're allowed to pass an array of namespaces to the `useTranslation` hook. However, when imported directly from  `next-i18next` per the README, it only grabs the first value in the array and ignores everything else. 

Planning on opening a PR probably next week or so when my time frees up, but in case anyone beats me to it, I figured I should document the behavior. 

## Occurs in next-i18next version
Only tested in 8.1.2

## Steps to reproduce
1. Create a brand new Next app 
2. Add `next-i18next to the install 
3. Add at least two namespaces i.e. `common` and `homepage` 
4. Add an array to the useTranslation hook, like `const { t } = useTranslation(["common", "homepage"]);`
5. Anything in `common` will be translated, but not anything in `homepage`. You can swap positions and the opposite will be true. 

Or

Clone my [example repo](https://github.com/austinhale/next-i18next-hook-array-issue)

## Expected behaviour
Both namespaces would be utilized. 

## Screenshots
![image](https://user-images.githubusercontent.com/6180399/112777699-dc031c80-9010-11eb-8061-05f4663de97a.png)

## OS (please complete the following information)
Latest Chrome on Windows 10

## Sidenote
Unrelated to this issue, but also included in the example repo, I was trying to recreate the issue I mentioned a few days back when doing an inline conditional. I figured out it's only while using the [useUser](https://auth0.github.io/nextjs-auth0/modules/frontend_use_user.html) client hook on the official Auth0 [Nextjs SDK](https://github.com/auth0/nextjs-auth0). It's a bit odd. If I use the hook with _only_ user, `const { user } = useUser();` and use the `{user ? <ButtonOne /> : <ButtonTwo />` conditional logic, I get the i18 instance error. Even more odd, `{!user ? <ButtonTwo /> : <ButtonOne />}` works without issue.

I assume this means there are probably other use cases / libraries / etc. where an unresolvable promise during the server render process would similarly cause issues. 

If I use `error` and `isLoading` as a sort of catch, it works perfectly. This is what I'm doing for now. 

e.g. 
```
const { user, error, isLoading } = useUser();

if (error) return <div>failed to load</div>;
if (isLoading) return <div>loading...</div>;

return ( 
{user ? ( 
  <Button>{t('dashboard')</Button>
) : (
  <Button>t('login')</Button>
)}
```

I assume there's some weird state where `user` is an unresolved Promise or something to that effect that's causing the issue. For now, I've added the `error` and `isLoading` catch since I didn't have time to go on a deep dive over the weekend. Will try to dig deeper later.

**Comment by isaachinman** [comment]
Weird... We are exporting `useTranslation` [directly from `react-i18next`](https://github.com/isaachinman/next-i18next/blob/master/src/index.tsx#L1). I'm not sure what to make of your `useUser` example, but are we sure that the `useTranslation` issue is related to `next-i18next`?

**Comment by isaachinman** [comment]
@austinhale Let me know if you have any update on this. As we export `useTranslation` without any form of mutation, I highly doubt this is a `next-i18next` bug.

**Comment by alexsimkovich** [comment]
@austinhale @isaachinman it works, please read the documentation carefully :)
```
// load multiple namespaces
// the t function will be set to first namespace as default
const { t, i18n } = useTranslation(['ns1', 'ns2', 'ns3']);
t('key'); // will be looked up from namespace ns1
t('ns2:key'); // will be looked up from namespace ns2
```

**Comment by austinhale** [comment]
My bad. Thank you @alexsimkovich 🙏
