### ISSUE TITLE
Locale change during hydration causes flickering (wrong page is served)

### ISSUE THREAD

**Issue by vlad-elagin** [isaachinman/next-i18next#1114]
## Describe the bug
I have an app with 4 locales using sub-path routing. During development it works nice, but after building static pages and running `next start` wrong pages are served. F.e. I have `de` page served and during hydration it switches to `en`. It causes flickering and looks bad. I couldn't figure out a patter there since I get pages of all 4 locales served, `en` now, `de` then, then `fr`. And all of them then turn `en` when loaded. This happens both locally and on production (I use vercel). And it doesn't depend on active sub-path (I get random page version on `example.com`, `example.com/fr` etc).

## Occurs in next-i18next version
8.1.1

## Steps to reproduce
My `next-i18next.config.js`
```
const path = require("path");

module.exports = {
  i18n: {
    defaultNS: [],
    defaultLocale: "en",
    locales: ["en", "de", "fr", "cn"],
    fallbackLng: "en",
    localeDetection: false,
  },
  localePath: path.resolve("./src/locales"),
};
```

Example of `getStaticProps`:
```
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, [
        "navigation",
        "features",
        "footer",
      ])),
    },
  };
};
```

## Expected behaviour
Correct page version is served on request and no flickering happens
Request to `example.com` -> serve default locale (en)
Request to `example.com/fr` -> serve french version 

## OS (please complete the following information)
 - Device: MBP 2015 15" (for local env) and Vercel's servers
 - Browser: Chrome 89.0.4389.90 (Official Build) (x86_64)

**Comment by vlad-elagin** [comment]
@isaachinman typescript's assertion on the fact that locale will be defined. It is typed as `string | undefined`. Though it is always defined - I've checked it via console logs. Don't think that it is the source of problem.

**Comment by vlad-elagin** [comment]
Can't get it to work in isolated project. Probably because hydration happens to soon (my app is heavy on ui). Any clues where I should look to get more information?

**Comment by isaachinman** [comment]
@vlad-elagin Sorry, not really sure how to help. If you cannot reproduce the bug in an isolated project, obviously the bug lies somewhere in the diff of those two projects.

**Comment by vlad-elagin** [comment]
So, after future investigation I figured out that the issue is not with wrong page served, but with wrong resources set used for current locale.

My `getStaticProps` for `src/pages/index.tsx`
```typescript
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  console.log("getting static props for", locale);
  return {
    props: {
      ...(await serverSideTranslations(locale!, [
        "navigation",
        "fileTypes",
        "features",
        "footer",
      ])),
    },
  };
};
```

then my `src/pages/index.tsx` itself
```tsx
const IndexPage = () => {
  const { locale } = useRouter();
  console.log('rendering index page for', locale);

  return <div><Navbar /></div>
}
```

and `src/components/Navbar`
```tsx
const Navbar = () => {
  const { locale } = useRouter();
  const { t } = useTranslation('navigation');

  console.log(`from nav: locale is ${locale} and translation is ${t('navigation:pricing')}`);

  return <nav>...</nav>
}
```

Now, when I do `next build` I get messages in following order:
- getting static props for en
- getting static props for de
- getting static props for fr
- getting static props for cn
- from nav: locale is en and translation is Tarifs
- rendering index page for en
- from nav: locale is de and translation is Tarifs
- rendering index page for de
- from nav: locale is fr and translation is Preise
- rendering index page for fr
- from nav: locale is cn and translation is Preise
- rendering index page for cn

Doesn't it mean that issue lies somewhere in `createClient` or `appWithTranslation`? It seems that next's renderer doesn't wait until i18n instance changes locale and loads new set of resources. I'm trying to replicate that issue in separate repo but with no luck for now. Any help would be appreciated

**Comment by isaachinman** [comment]
Until you can reproduce it in a simple repo, unfortunately there's not much I can offer in terms of help.
