### ISSUE TITLE
Add translations to _app.js

### ISSUE THREAD

**Issue by amphineko** [isaachinman/next-i18next#1115]
I'm attempting to add next-i18next into my app.

Currently, I have some contents like the navigation bar. So I need to add translations for them.

To my understand, `getStaticProps` with `serverSideTranslations` needs to be added to every page that use next-i18next. But next.js says that `_app.js` cannot have a `getStaticProps` (https://nextjs.org/docs/advanced-features/custom-app#caveats).

I have attempted adding the following codes to my `_app.tsx`.

```typescript
export default appWithTranslation(Application)

export const getServerSideProps = async (ctx: { locale: string }): Promise<{ props: SSRConfig }> => ({
    props: {
        ...await serverSideTranslations(ctx.locale, ['app', 'common'])
    }
})
```

The console has some warnings show up and the translation doesn't work.

```
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```

Are there any workarounds available?

**Comment by isaachinman** [comment]
There's no need for a "workaround" – the `_app` file is not a page. As long as you follow the documentation and add `serverSideTranslations` to each of your pages, you can use the `useTranslation` hook inside `_app`. Good luck!

**Comment by amphineko** [comment]
Thank you! Your advice saved my day. 

I simply added `getServerSideProps` to each page and include the namespace for `_app.js`. And `_app.js` can now read the translations it needs.

**Comment by ripern** [comment]
@amphineko I'm having the same issue. How did you fix this for your navbar component?  I assume it's not a page itself and I assume it's still inside your _app.tsx?

Mine:
`import Navbar from '../components/Navbar'
import { appWithTranslation, useTranslation } from 'next-i18next'

function MyApp({ Component, pageProps }) {
  const { t } = useTranslation('navbar')

  return (
    <>
      <Navbar title={t('title')} />
      <Component {...pageProps} />
      <Toaster />
    </>
  )
}

export default appWithTranslation(MyApp)`

@isaachinman I feel that I'm misunderstanding something, do you understand what from my details?

Cheers

**Comment by amphineko** [comment]
@ripern To my understanding, `appWithTranslation` is sufficient to provide translations in `_app`.

```ts
export default appWithTranslation(Application)
```

This will inject any providers that required by `useTranslations`. However, you will need to load one of your pages besides `_app.tsx` (e.g `index.tsx`) to inject the actual translations into i18next. 

So I have put the following lines into all of the pages.

```ts
export const getStaticProps = async (ctx: { locale: string }): Promise<{ props: SSRConfig }> => ({
    props: {
        ...await serverSideTranslations(ctx.locale, ['app'])
    }
})
```

**Comment by adrianbienias** [comment]
> There's no need for a "workaround" – the `_app` file is not a page. As long as you follow the documentation and add `serverSideTranslations` to each of your pages, you can use the `useTranslation` hook inside `_app`. Good luck!

So in case of having translations in `_app` file, can we safely treat the following warning as false positive?
```
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```

Is this warning may indicate problems in other places besides using translations in `_app`?
If so, then how to hide this warning when it refers to `_app` but no other places?

**Comment by amphineko** [comment]
@adrianbienias It doesn’t look like a false warning but your code consumed `useTranslation` before the provider has been injected.

**Comment by adrianbienias** [comment]
@amphineko Right, but ultimately translation works. I'm just thinking about a case when the warning indicates that I messed something up in another place, but I ignored it because it won't stand out of current warnings.

**Comment by adrianbienias** [comment]
@isaachinman how about error pages e.g. 404?
They are static pages and the layout like navbar/footer placed in `_app` doesn't get translations on those pages.

**Comment by JayMGurav** [comment]
@isaachinman is there anyway where I can load translations for the layout components at `_app`?, I'm not able to find my way through getting them loaded for the components that sit above the pages, Thanks!

**Comment by isaachinman** [comment]
No, translations are currently loaded at the page level. If the Vercel team adds support for `getStaticProps`/`getServerSideProps` to `_app`, it would then be possible to load translations there.

**Comment by AndysonDK** [comment]
> > There's no need for a "workaround" – the `_app` file is not a page. As long as you follow the documentation and add `serverSideTranslations` to each of your pages, you can use the `useTranslation` hook inside `_app`. Good luck!
> 
> @isaachinman So in case of having translations in `_app` file, can we safely treat the following warning as false positive?
> 
> ```
> react-i18next:: You will need to pass in an i18next instance by using initReactI18next
> ```
> 
> Is this warning may indicate problems in other places besides using translations in `_app`? If so, then how to hide this warning when it refers to `_app` but no other places?

I know why it's happening! You want to define a [404](https://nextjs.org/docs/advanced-features/custom-error-page#404-page ) and a [500](https://nextjs.org/docs/advanced-features/custom-error-page#500-page) page, and define `getStaticProps` with the `serverSideTranslations` function in both pages!

**Comment by LeoGeneret** [comment]
> > > There's no need for a "workaround" – the `_app` file is not a page. As long as you follow the documentation and add `serverSideTranslations` to each of your pages, you can use the `useTranslation` hook inside `_app`. Good luck!
> > 
> > 
> > @isaachinman So in case of having translations in `_app` file, can we safely treat the following warning as false positive?
> > ```
> > react-i18next:: You will need to pass in an i18next instance by using initReactI18next
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this warning may indicate problems in other places besides using translations in `_app`? If so, then how to hide this warning when it refers to `_app` but no other places?
> 
> I know why it's happening! You want to define a [404](https://nextjs.org/docs/advanced-features/custom-error-page#404-page) and a [500](https://nextjs.org/docs/advanced-features/custom-error-page#500-page) page, and define `getStaticProps` with the `serverSideTranslations` function in both pages!


you saved my day, thanks !
