### ISSUE TITLE
Auto detecting locale, redirecting not working

### ISSUE THREAD

**Issue by klimazarin** [isaachinman/next-i18next#1117]
In my nextjs app, I just installed next-i18next (latest version - 8.1.2) without another libraries such as i18next, react-i18next.
Now I want to make a language setting which is controlled on browser level(cookie or local storage).
My code looks something like belows.

```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    defaultNS: 'common',
    locales: ['en', 'de'],
    initImmediate: false,
    fallbackLng: 'en',
    detection: {
      order: ['cookie', 'localStorage'],
      lookupCookie: 'next-i18next',
      lookupLocalStorage: 'i18nextLng',
      caches: ['cookie', 'localStorage'],
    },
    localePath: 'public/locales',
    localeSubpaths: {
      en: 'en',
      de: 'de',
    },
  },
};
```

When I change setting, 
```
<Link href="/account/edit" locale="de">Dutch</Link>
```

And in useEffect
```
  useEffect(() => {
    i18n.changeLanguage(locale);
  }, [locale]);  // locale comes from next useRouter
```

It seems changing locale.. however it is not saved at all when I refresh the page with a default locale.

Is there something that I missed to store the changed locale manually?
I thought it is automatically operated.

**Comment by isaachinman** [comment]
You're mixing up old API params with the new V8 setup. Please read the docs carefully. Good luck!

**Comment by klimazarin** [comment]
Hi Isaachinman! thanks for your quick response.

I have just read it again, however I couldn't have found words regarding browser detection setting.
Could you please be more specific?
Or can you give me a sample code?

Thanks.

**Comment by isaachinman** [comment]
The sample code is in the example directory. Browser detection is now handled by NextJs automatically.

**Comment by klimazarin** [comment]
I cloned the sample code and run it locally..
However, it also didn't detect the locale that I changed ( e.g. I changed it de ) when I visit a home page ( / ).
It is supposed to detect the locale automatically and redirect to /de.

**Comment by natterstefan** [comment]
Hi @klimazarin,

maybe one of those links helps you to solve your problem.

- [Leveraging the NEXT_LOCALE cookie](https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie)
- [How to save the user-defined language](https://github.com/vinissimus/next-translate#10-how-to-save-the-user-defined-language)
- [How I translated my Next.js Blog](https://www.infoxicator.com/how-i-translated-my-next-js-blog)

Good luck 👋

**Comment by klimazarin** [comment]
Thank you very much, Natterstefan!
Manual setting cookie make it work!

**Comment by natterstefan** [comment]
You're welcome @klimazarin

**Comment by klimazarin** [comment]
Hi Natterstefan!
Could you also help me on this issue?

https://github.com/isaachinman/next-i18next/issues/1133
https://stackoverflow.com/questions/67014108/next-i18next-initial-locale-argument-was-not-passed-into-serversidetranslations

Thank you in advance!
