### ISSUE TITLE
Translation does not work in client side rendered components

### ISSUE THREAD

**Issue by mdegrees** [isaachinman/next-i18next#1118]
## the bug
I followed the exact steps described in readme, I got SSR translations to work just fine with getServerSideProps. For some reason I can't get next-i18nNext to work with client-side rendered components. Persisted nav bar for e.g. Is this the way intended to be? Should I use react-i18nNext for non SSR?  

## Occurs in next-i18next version
1.8.3

**Comment by isaachinman** [comment]
To open a bug issue on a GitHub repository, you will need to provide steps to reproduce it, at a minimum. Thanks!

**Comment by mdegrees** [comment]
@isaachinman I'm not even sure if that's a bug or a feature request. It's more of a question/discussion about: how would one go about translating the persisted components in Next.js with next-i18next? What I intend to do is something like

```javascript
import { appWithTranslation } from "next-i18next";
import { useTranslation } from "next-i18next";

// pages/_app.js
function MyApp({ Component, pageProps }) {
  return (
    <div>
      <NavBar />
      <Component {...pageProps} />
    </div>
  );
}

export default appWithTranslation(MyApp);

function NavBar() {
  const { t } = useTranslation("common");
  return (
    <div style={{ backgroundColor: "yellow" }}>{t("hello_from_nav_bar")}</div>
  );
}
```
Obviously that's not gonna work as useTranslation does not have access to the localization provider yet. My question was how to go about this use case? 

Sandbox:
https://codesandbox.io/s/recursing-worker-bkmkq?file=/pages/_app.js:0-436

**Comment by isaachinman** [comment]
You need to use `serverSideTranslations` in your `index.js` page. Please read the docs carefully. Good luck!

**Comment by mdegrees** [comment]
@isaachinman thank you for the quick response. In fact I have no problem with server-side, page-level translations. They work just fine. My question is about the persisting component that Next.js supports https://nextjs.org/docs/advanced-features/custom-app. In Next js you can add persisting components which are client side rendered. How could we translate content living under those components.

**Comment by isaachinman** [comment]
I have directly answered your question. Look at [the example](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js).

Using `serverSideTranslations` is mandatory for _all pages_.

Here is a [sandbox](https://codesandbox.io/s/youthful-rubin-xstbd?file=/pages/index.js).

Please take your time to read documentation carefully before opening issues on OSS repos. Good luck!

**Comment by mdegrees** [comment]
My bad! now I see what you're talking about. Thanks a ton. So the dictionary fetching is always delegated to Next fetching methods. If that could help, my confusion came from the "hooks way" of doing things. I assumed ``useTranslation`` was doing all the work, fetching dictionary included. 

Referencing this [comment on issue](https://github.com/isaachinman/next-i18next/issues/718#issuecomment-809983584) where the same discussion was going

**Comment by nv-cho** [comment]
After 6 hours of debbugin and almost going crazy, this post solved my problem! thanks!!

**Comment by Nassoyan** [comment]
well I have the same issue, but I am using all neccessary thing, i have set up next.config.js and next-i18next.config.js file, in my header i am mapping and rendering the data inside t(link.name) but it won't work

**Comment by aiddroid** [comment]
I need a simple clientside i18n, BUT Not working too, not warnings, no errors, I think it must be the most tedious i18n solution. Is there anything wrong? :-(

next.config.js
```
const nextConfig = {
  reactStrictMode: true,
  i18n: {
        locales: ['en'],
        defaultLocale: 'en',
        localeDetection: false,
  }
}

module.exports = nextConfig
```

public/locales/en/common.json
```
{
   "test": "just for test"
}

```


pages/index.tsx
```

import { useTranslation } from "next-i18next";

export default function HomePage() {
  const { t } = useTranslation('common');

  return (
    <>
      <MainLayout>
			<div>{ t('test') }</div>
      </MainLayout>
    </>
  );
}
```

**Comment by adrai** [comment]
@aiddroid https://github.com/i18next/i18next-http-backend/tree/master/example/next ?

**Comment by aiddroid** [comment]
> @aiddroid [i18next/i18next-http-backend@`master`/example/next](https://github.com/i18next/i18next-http-backend/tree/master/example/next?rgh-link-date=2024-04-22T13%3A35%3A29Z) ?

It looks more difficult than Vuejs, from beginner to give up,  my fault.🤣

**Comment by tetyemillynha** [comment]
I solved changing the backed loadPath to:

 backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
},
