### ISSUE TITLE
Can't use format function in interpolation option

### ISSUE THREAD

**Issue by petruspierre** [isaachinman/next-i18next#1126]
## Describe the bug
I'm trying to format a date following the instructions in this issue https://github.com/i18next/i18next/issues/1201#issuecomment-462730686

But I'm getting
```
Server Error
Error: Error serializing `._nextI18Next.userConfig.interpolation.format` returned from `getStaticProps` in "/".
Reason: `function` cannot be serialized as JSON. Please only return JSON serializable data types.

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

## Occurs in next-i18next version
8.1.3

## Steps to reproduce
Add interpolation option to `next-i18next.config.js` file
```js
interpolation: {
    format: (value, format, lng) => {
      if (format === "intlDate") {
        console.log(new Intl.DateTimeFormat(lng).format(value));
      }

      return value;
    },
  },
```

Export your _app.js page
```js
export default appWithTranslation(MyApp, nextI18NextConfig);
```

Call `t` function
```js
const { t } = useTranslation("feeds");

t("date", { date: new Date() })
```

In en locale JSON you should have:
```json
"date": "{{date, intlDate}}"
```

## Expected behaviour
`t` function must return date in MM/DD/YYYY format

**Comment by isaachinman** [comment]
This is explicitly documented in the README:

https://github.com/isaachinman/next-i18next#unserialisable-configs

**Comment by Flcwl** [comment]
> This is explicitly documented in the README:
> 
> https://github.com/isaachinman/next-i18next#unserialisable-configs

the link can not  visit

**Comment by adrai** [comment]
> > This is explicitly documented in the README:
> > https://github.com/isaachinman/next-i18next#unserialisable-configs
> 
> the link can not visit

https://github.com/i18next/next-i18next?tab=readme-ov-file#unserializable-configs
