### ISSUE TITLE
Use i18n instance outside of server pages or components

### ISSUE THREAD

**Issue by sMteX** [isaachinman/next-i18next#1127]
I'm not sure if this is the right place to ask, but is there a way to use the i18n instance in general server-side content (I assume)?

I have the instance set up with `new NextI18Next` as usual and everything works in my frontend when I use it in components. However, part of my application is sending emails, which is done server-side (but not in SSR page), like so:

```ts
export const sendMail = async (email, content) => {
  const subject = 'Translate me please'
  await emailService.sendMail(email, subject, content)
}
```

And I would like to be able to translate `subject` here. When I import and log the `i18n` object that's exported from the file, I can see the config, that the inner `i18n` object `isInitialized` yet nothing I tried (directly using `i8n.i18n.t`, cloning instance, reloading resources...) works (and I always get the translation _key_ returned instead of the translated thing)

Additionally, it would help me translate in pretty much static content too (I have a file `utils/constants.ts` which could use translations too).

Any possibility to achieve what I'd like to do? (I should mention that it seems we're running on `6.0.3` version but there shouldn't be a problem to update if needed)

**Comment by isaachinman** [comment]
Hi @sMteX – if you'd like an i18next instance to perform localisation in your API routes, which is what it sounds like, you are probably better off initialising a separate i18next instance, which loads _all_ your locales and namespaces. Remember that you'll need to send the user's locale in API reqs.

If you have any further questions about implementation specifics, please direct them to StackOverflow or similar. Good luck!

**Comment by zeing** [comment]
this lib can use like https://react.i18next.com/legacy-v9/i18next-instance ?

**Comment by isaachinman** [comment]
There's no need to use anything legacy, just use a normal [i18next instance](https://www.i18next.com/overview/getting-started).

**Comment by zeing** [comment]
> There's no need to use anything legacy, just use a normal [i18next instance](https://www.i18next.com/overview/getting-started).

Excuse me `i18next` is still okay using with next.js?

**Comment by isaachinman** [comment]
@zeing This user was specifically asking about localising their API endpoints, which is not something that `next-i18next` really focuses on, although you could probably import the global singleton instance:

```tsx
import { i18n } from 'next-i18next'

export default function handler(req, res) {
  res.status(200).json({ name: i18n.t('hello') })
}
```

**Comment by joseazevedo88** [comment]
I have the same use case, but i18n is null when using next start, even though it works in dev. Any thoughts?

**Comment by marnixhoh** [comment]
@isaachinman  I use the i18n instance from `import { i18n } from 'next-i18next'  in `getStaticProps`. In development this works as expected, but in production it is null. Just as @joseazevedo88 describes. Any thoughts on what might be cause this?

**Comment by isaachinman** [comment]
The global `i18n` instance will be null until the React app mounts, so you can only use it during runtime, not during initialisation.

**Comment by marnixhoh** [comment]
@isaachinman thanks for your reply. Yep I understand. What I ended up doing was simply check if i18n is defined in `getStaticProps()` and if so, then use it. The very first time the app renders it is null, in which a case a fallback is used. All renders after this however, it is defined and everything works as expected. It leaves me with a slightly uncomfortable feeling that it takes one render for the i18n instance to be initialized (maybe I'm using it wrong?), but hey it works :)
