### ISSUE TITLE
Unhandled runtime error originated from Invalid URL - 404 component doesn't render

### ISSUE THREAD

**Issue by danielsimao** [isaachinman/next-i18next#1128]
## Describe the bug
In the root of the application, adding 2 slashes ("//"), generates a unhandled run time error (example: [](https://e3zds.sse.codesandbox.io//)) and ends up not rendering the 404 page.

❌  https://e3zds.sse.codesandbox.io// - breaks
✅  https://e3zds.sse.codesandbox.io/about// - handled correctly with 404 rendered

**At first I thought it was a next problem, but the error only occurred when I added next-i18next.** Please follow the repos I have provided below

## Occurs in next-i18next version
8.1.3

## Steps to reproduce
CodeSandBox **with** next-i18next: https://codesandbox.io/s/goofy-bas-e3zds?file=/pages/404.js
CodeSandBox **without** next-i18next: https://codesandbox.io/s/modern-sea-ngyzq?file=/pages/404.js

## Expected behaviour
Should handle invalid URL with 404 page.

## Screenshots
![image](https://user-images.githubusercontent.com/43269067/113880794-b6fe6e80-97b3-11eb-927e-f4c77573ffea.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

Thank you in advance

**Comment by isaachinman** [comment]
Looks like you may have found a NextJs bug. If I change `next.config.js` in your "working" example to:

```tsx
module.exports = {
  basePath: '/docs',
  assetPrefix: '/docs',
  i18n: {
    defaultLocale: 'en-US',
    locales: ['en-US', 'fr'],
  },
}
```

The behaviour changes as well. This indicates the bug is not related to `next-i18next`.

For what it's worth, I have personally found loads of trailing-slash bugs in NextJs/Vercel over the past 6 months or so. Please raise this issue on the NextJs repo.

**Comment by danielsimao** [comment]
Yup, you are right @isaachinman. 😅  Im sorry for the trouble and thank you for the swift response. Cheers.
