### ISSUE TITLE
Passing configuration to React components

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#113]
This issue is a follow-up on the first point mentioned in [this comment](https://github.com/isaachinman/next-i18next/issues/105#issuecomment-455535621) in #105.

What do you think about passing `next-i18next` configuration to our react components by using a HoC?  This allows our React component files to be less cluttered.  As a side benefit, we also won't run into cyclomatic complexity problems as easily with CodeClimate because our components won't be wrapped into a function.  Overall, IMO it seems to be much more "React-like" to use a HoC, since we're using props to pass our config.

In practice, we would need to add a HoC (say `withConfig`) and then in `src/index.js` change the lines like this:
```js
    this.Link = Link.apply(this)
```
to this:
```js
    this.Link = withConfig(Link, config)
```
Changes would all be transparent to the user, so no breaking change.  To be clear. this does not address the second point mentioned in the comment.  Thoughts?

PR with an example forthcoming.

**Comment by isaachinman** [comment]
Fixed via #114.
