### ISSUE TITLE
Next "build" command does not import static assets used at runtime

### ISSUE THREAD

**Issue by lucksp** [isaachinman/next-i18next#1130]
## Describe the bug
When running my production build, with `next-i18next`, the static translation files inside my `public` dir are not being found.  My site displays the translation "key" not the full string text.

## Occurs in next-i18next version
    "next": "^10.0.2",
    "next-i18next": "^8.1.1",

## Steps to reproduce
next-i18next.config.js file:
```
const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  localePath: path.resolve('./public/static/locales'),
};

```

next.config.js file:
```
const defaultConfig = {
  i18n,
  redirects: require('./next-redirects'),
}
```

_app.js:
```
function MyApp({ Component, pageProps }) {
   /// snipped
}

export default appWithTranslation(MyApp);
```

page with error (not limited to just this single page)
```
export const SearchPage = () => {
  const router = useRouter();
  const { t } = useTranslation('search'); 

  // snipped //

  return (
    <>
      <Head>
        <title>{`${t('searchTitle')}`}</title>
        <meta
          property="og:title"
          content={`${t('searchTitle')}`}
          key="title"
        />
        <meta
          name="description"
          content={t('metaDescription')}
        />
      </Head>
      <ItemsContext.Provider
        value={{snipped}}>
         <Search />
      </ItemsContext.Provider>
    </>
  );
};

SearchPage.namespace = 'SearchPage';

export const getServerSideProps = async ({ locale }) => ({
  // exposes `_nextI18Next` as props which includes our namespaced files
  props: {
    ...await serverSideTranslations(locale, ['common', 'search']),
  }
});

export default SearchPage;
```

Commands used:
```
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "cypress.test": "npx cypress run",
```

running `yarn dev` works fine as show in expected screenshot below
running `yarn build && yarn start && yarn cypress.test` will output the Actual screenshot below causing my test to fail.

## Expected behaviour
Development on local machine:
![image](https://user-images.githubusercontent.com/15162169/113939518-583bf380-97b9-11eb-9045-366d23e4b563.png)

## Actual Error Screenshots

Production build as seen on Cypress:
![image](https://user-images.githubusercontent.com/15162169/113939742-9802db00-97b9-11eb-8281-1ae5b4fa3be7.png)

## OS (please complete the following information)
 - Device: MBP 2019 v 11.2.3
 - Browser: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
 - 
## Additional context
From the [nextJS docs](https://nextjs.org/docs/basic-features/static-file-serving) on static file serving:

> Note: Only assets that are in the public directory at build time will be served by Next.js. Files added at runtime won't be available. We recommend using a third party service like AWS S3 for persistent file storage.

It appears that the `serverSideTranslations` function might be considered runtime - because my pages are not pre-built when related to dynamic path URLs.

Please advise on `serverSideTranslations` considered runtime vs buildtime?

**Comment by isaachinman** [comment]
Please provide a reproducible repo.

**Comment by lucksp** [comment]
ok, might be a moment since it's my work repo that this is occurring in...would need to establish a new repo & project & circle ci & cypress env.

**Comment by lucksp** [comment]
@isaachinman can you clarify: is the `serverSideTranslations` considered runtime or buildtime?

```
export const getServerSideProps = async ({ locale }) => ({
  // exposes `_nextI18Next` as props which includes our namespaced files
  props: {
    ...await serverSideTranslations(locale, ['common', 'search']),
  }
});
```

**Comment by isaachinman** [comment]
It can be either runtime or build time, depending on which data-fetching method you use.

**Comment by Dig-Doug** [comment]
Hi, I'm also having the same issue. I created a repro using the example [here](https://github.com/Dig-Doug/next-i18next).

When you deploy the example on vercel, the `getServerSideProps` function fails to read the translation files from `public`. It looks like the directory isn't available to the serverless function for some reason.

```
2021-04-24T22:55:40.956Z	18b25db2-e48d-4a87-9383-4fb3a823bf7f	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/en'
    at Object.readdirSync (fs.js:1021:3)
    at getAllNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:129:21)
    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:134:29)
    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:117:53)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/public/locales/en'
}
```

**Comment by lucksp** [comment]
does this happen locally or in an environment like CircleCI + Cypress?

**Comment by Dig-Doug** [comment]
This only happens when I deploy the production build on [vercel](https://vercel.com/). Locally everything works fine.

**Comment by isaachinman** [comment]
@Dig-Doug You need to use `path.resolve` on Vercel, to get their runtime to include the files in the serverless output.

**Comment by Dig-Doug** [comment]
Thanks that's what I was missing. For future readers, here's what I added to my config:

```js
// next-i18n.config.js
const path = require('path');

module.exports = {
  i18n: {
    ...
  },
  localePath: path.resolve('./public/locales'), // Added
}
```
