### ISSUE TITLE
Documentation must be updated

### ISSUE THREAD

**Issue by eraygundogmus** [isaachinman/next-i18next#1132]
## Documentation must be updated.

Documentation is not clear and does not have enough description and code example. 
Even in your only one - simple example, people have no idea what to do when they need to add more functionality to their projects with i18n or other Next features.

You can simply reject that suggest by saying you need to read other docs to understand it and close this issue too but please consider that next-i18next directly affects _app.js, config files, components, even hooks which comes from react-i18next.

I lost a lot of time to understand how next-i18next works and how to use it. I know other people have the same issue.
If you need proof, check out closed 800 issues.

Thanks for your time, great work except this.

**Comment by isaachinman** [comment]
Hi @eraygundogmus – any interest in contributing? A PR to improve documentation would be great.

**Comment by eraygundogmus** [comment]
@isaachinman Of course, I would like to contribute to improve docs if you also think it will be useful to the community.

**Comment by isaachinman** [comment]
What areas of the package do you feel are lacking documentation? I think at most, we probably just need to link to the relevant NextJs and i18next documentation pages, as `next-i18next` is just a thin wrapper between the two.

**Comment by eraygundogmus** [comment]
You made a good point with that. 

Firstly, I feel like two more title in README.md must be added .
A Why Next-i18next title that briefly explains to the community why its use can be useful and a How It Works title that explains the community the logic of working and helps them learn quickly.

And I think at least one deeper example must be added that uses translation hook with overview options. Which I still don't sure about that options are available or not because I used i18next.store to get JSON from ns.

Additionaly I can clearly see that people gets confused about async getStaticProps with serverSideTranslations. 
It can be regular function with return value and clarificative comments instead of arrow function. This way, fewer issues can be opened.

if you agree, I can think about a more detailed improvement and start to work on creating a PR.

**Comment by rtrembecky** [comment]
Hi, I'm just setting `next-i18next` up on a new project and I noticed a thing about the namespaces part, though this is more example-related than readme-related. The docs mention route-based namespaces as the best practice, however, in the `examples/simple` the namespaces are `'common'` and `'footer'`. Do I understand correctly that the best split would be `['common', 'home', 'second-page']` instead? With Footer description being in `'common'` namespace, as it is used across pages.

**Comment by eraygundogmus** [comment]
![image](https://user-images.githubusercontent.com/74984741/115905448-c85fa000-a46e-11eb-8cf9-7ebfdbd7528f.png)
@rtrembecky
