### ISSUE TITLE
Handle changeLanguage from i18n

### ISSUE THREAD

**Issue by MhmdNdri** [isaachinman/next-i18next#1140]
## Is your feature request related to a problem? Please describe.

I'm trying to use i18n and i18-i18next to change my language without changing the URL like this: 

```
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

const Homepage = () => {
  const { i18n, t } = useTranslation("common");

  return (
    <>
      <button
        type="button"
        onClick={() => {
          i18n.changeLanguage(i18n.language === "en" ? "de" : "en");
        }}
      >
        {t("change-locale")}
      </button>
      {t("title")}
    </>
  );
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});

export default Homepage;
```

## Describe the solution you'd like
When I log i18n, I see that the language changed, but I don't access to my common.json file to translate it.

## Describe alternatives you've considered
Changing Language without changing the URL from i18n.

**Comment by isaachinman** [comment]
Please check the NextJs documentation. Do not change the language via i18next.

**Comment by natterstefan** [comment]
Hi @MhmdNdri, if you do not know where to look it up in the docs take a look at my answer in a related issue: https://github.com/isaachinman/next-i18next/issues/1117#issuecomment-813064583

**Comment by MhmdNdri** [comment]
> Hi @MhmdNdri, if you do not know where to look it up in the docs, take a look at my answer in a related issue: [#1117 (comment)](https://github.com/isaachinman/next-i18next/issues/1117#issuecomment-813064583)

Hi @natterstefan, Thanks a lot, You give me the correct way that I have been looking for.
