### ISSUE TITLE
getServerSideProps doesn't support serverSideTranslations

### ISSUE THREAD

**Issue by MarvinZeising** [isaachinman/next-i18next#1141]
## Description
When using `serverSideTranslations` inside `getServerSideProps`, the page doesn't load.
It does work with a production build locally, but not if pushed to Vercel.

I know this has to be some kind of deployment issue, but maybe someone knows what I can do about it. I've looked into the next-i18next code trying to understand what's going wrong but I don't have enough NextJS knowledge.

Maybe there's a documentation page for this repo? Aside from the README, I couldn't find anything.

## Occurs in next-i18next version
```
"i18next": "^20.2.1",
"next": "10.0.5",
"next-i18next": "^8.1.3",
"react": "^17.0.2",
"react-dom": "^17.0.2"
```

## Steps to reproduce
I took the "simple" example from this repo and changed the `getStaticProps` on the second page to `getServerSideProps`. Added the missing packages to the package.json and deployed it to vercel (https://simple-2e6voz5th-marvinzeising.vercel.app).

![image](https://user-images.githubusercontent.com/12305625/114420798-ef87b900-9bb4-11eb-9fcc-30b4da68d9b4.png)

Opening the second page now results in a 500 error page.

![image](https://user-images.githubusercontent.com/12305625/114421632-c9164d80-9bb5-11eb-951e-c01cceb775e3.png)

On the server, I can see this:

![image](https://user-images.githubusercontent.com/12305625/114420924-0f1ee180-9bb5-11eb-8754-c864d33f65ed.png)

Is `getServerSideProps` not supported? I found an issue (#652) regarding that but I think that one is quite old.

## Expected behaviour
For it to work just like in `getStaticProps`, I guess.

## Screenshots
See above.

## OS (please complete the following information)
 - Device: MBP 2018 15"
 - Browser: Microsoft Edge Version 89.0.774.54 (Official build) (64-bit)

**Comment by isaachinman** [comment]
You need to use:

```tsx
localePath: path.resolve("./src/locales")
```

**Comment by JavierCaroelli** [comment]
How can you fix it ?

**Comment by MuhammadHasham23** [comment]
Any updates on this one?

**Comment by isaachinman** [comment]
@JavierCaroelli @MuhammadHasham23 This issue had nothing to do with `getServerSideProps`. When deploying to Vercel, you must use `path.resolve` to force the Vercel serverless build to include your locales directory.
