### ISSUE TITLE
Interpolation format is not used during build/server phase

### ISSUE THREAD

**Issue by hakonkrogh** [isaachinman/next-i18next#1145]
## Describe the bug
We're experiencing a translation issue on our Next.JS boilerplate which uses next-i18next for translations.
The boilerplate: https://github.com/CrystallizeAPI/crystallize-nextjs-boilerplate

The interpolation format function does not get executed on the server, resulting in wrong translation output in the initial server response. The correct formatting is applied _after_ client hydration.

## Occurs in next-i18next version
8.1.3

## Steps to reproduce
1) Go to the production website, https://furniture.superfast.shop/
2) Open devtools
3) Turn off Javascript
4) Refresh page to see the result from the build

## Expected behaviour
Prices should be in the format of e.g.: €60

### Before hydration
![result-from-server](https://user-images.githubusercontent.com/1568176/114839324-ef1a3880-9dd5-11eb-85d1-810b6d211f69.png)

### After hydration
![result-after-hydration](https://user-images.githubusercontent.com/1568176/114839424-06f1bc80-9dd6-11eb-97dd-779544fd139e.png)

## Minimum reproduction

```
git clone git@github.com:hakonkrogh/i18next-simple.git
```
```
cd i18next-simple
```
```
npm install
```
```
yarn dev
```

Then
1) Open http://localhost:3000
2) Open devtools
3) Turn off Javascript
4) Refresh page to see the result from the build

**Comment by isaachinman** [comment]
You'll need to provide a _minimum_ reproduction in order for others to debug.

**Comment by hakonkrogh** [comment]
> You'll need to provide a _minimum_ reproduction in order for others to debug.

I've added a minimum reproduction now

**Comment by isaachinman** [comment]
@hakonkrogh What I meant was that the repo you provided is complex and your problem most likely lies therein. If you would like assistance, you will need to reproduce your error in a simple repo, preferably a copy of the [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple).

Normally in these cases, you will end up discovering an implementation error in the process of creating a minimal repro.

Good luck!

**Comment by hakonkrogh** [comment]
Sounds like a fair request, I'll get on that 👍

**Comment by isaachinman** [comment]
Great. Happy to reopen if you can provide a minimum repro.

**Comment by hakonkrogh** [comment]
Created a minimum repo: https://github.com/hakonkrogh/i18next-simple

**Comment by isaachinman** [comment]
Is the [`Intl` API](https://github.com/hakonkrogh/i18next-simple/blob/main/pages/_app.js#L17) defined in your server environment?

**Comment by hakonkrogh** [comment]
> Is the [`Intl` API](https://github.com/hakonkrogh/i18next-simple/blob/main/pages/_app.js#L17) defined in your server environment?

Yes, you should assume Node v14 here as the runtime (I forgot to mention that before)

**Comment by isaachinman** [comment]
Why did you choose to override your config only in `_app`? That is the root of your problem. Please read the documentation carefully. If you want to override the config in either `_app` or `serverSideTranslations`, you will need to do so consistently. I recommend just moving your changes into your `next-i18next.config.js` if they are serialisable.

Good luck!

**Comment by hakonkrogh** [comment]
> Why did you choose to override your config only in `_app`? That is the root of your problem. Please read the documentation carefully. If you want to override the config in either `_app` or `serverSideTranslations`, you will need to do so consistently. I recommend just moving your changes into your `next-i18next.config.js` if they are serialisable.
> 
> Good luck!

The issue with this is that functions cannot be serialised as JSON, so we cannot have the interpolation.format function in the next-i18next.js file.

**Comment by isaachinman** [comment]
I've just seen we're actually [missing the bit](https://github.com/isaachinman/next-i18next#unserialisable-configs) about also passing the unserialisable config into `serverSideTranslations`! That's a mistake.

If you're using TypeScript, you should be able to see the function call signature. This would be a great PR to improve documentation.

**Comment by hakonkrogh** [comment]
> I've just seen we're actually [missing the bit](https://github.com/isaachinman/next-i18next#unserialisable-configs) about also passing the unserialisable config into `serverSideTranslations`! That's a mistake.
> 
> If you're using TypeScript, you should be able to see the function call signature. This would be a great PR to improve documentation.

This is the solution. We're not using typescript in the boilerplate, that would have helped reveal the possible configuration options. I just pushed an update to our boilerplate unserialising the config, and then moving the format function into the proper config file: https://github.com/CrystallizeAPI/crystallize-nextjs-boilerplate/commit/1135ac465fc0c3a55f277d4e05ea7c688748a925.

Thanks for helping out resolving this issue 👍

**Comment by isaachinman** [comment]
@hakonkrogh Great! Would you be interested in creating a PR to update the docs?

**Comment by hakonkrogh** [comment]
> @hakonkrogh Great! Would you be interested in creating a PR to update the docs?

Yup, on it right now
