### ISSUE TITLE
ftr-request: change language via subpath

### ISSUE THREAD

**Issue by benpetsch** [isaachinman/next-i18next#115]
Three ways to change the language:

1) One may change the language via button click like mentioned in the example.

2) Change language via browser subpath
A) Current path: `/path` (language: defaultLanguage). Requesting `/de/path/` should change language to `de`.
B) Current path: `/de/path` (language: defaultLanguage). Requesting `/fr/path/` should change language to `fr`.
C) Current path: `/de/path` (language: defaultLanguage). Requesting `/NOT-A-LANGUAGE-CODE/path/` should change language to `defaultLanguage` + redirect to consumer friendly `/language-error` page.

***Current behaviour:***

1 and 2A do work.

***Requested additional behaviour:***

Please add browser subpath detection to solve 2B and 2C

***From the example section:***

```
// pages/index.js

import { i18n } from 'path/to/i18n';

// ...

<Button
  onClick={() =>
     i18n.changeLanguage(i18n.language === 'en' ? 'de' : 'en')
  }
>
  Change language
</Button>
```

```
// i18n.js - config

{
  otherLanguages: ['de', 'fr'],

  localeSubpaths: true,
  defaultLanguage: 'en',
  browserLanguageDetection: true
}
```

**Comment by isaachinman** [comment]
If you want to change a user's language, you should call `i18n.changeLanguage`. 

2A happens [here](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lng-path-detector.js#L12), and works this way to support SEO and indexing - if a user is coming to your web app via an organic search on a foreign URL, they should see content in that locale.

2B is not a supported way of changing a user's language, but should be supported for incoming routing similarly to 2A. That did require a fix, and should be remedied with 6cb73dd.

I don't understand 2C. That's probably outside the scope of this package. If a users lands on `/does-not-exist/path`, they will be redirected to `/de/does-not-exist/path` (for example), which will then produce a 404.
