### ISSUE TITLE
Import serverSideTranslations breaks pages

### ISSUE THREAD

**Issue by Alex01d** [isaachinman/next-i18next#1156]
## Describe the bug
When I import serverSideTranslations and don't use it in getServerSideProps or getStaticProps, I get:

> error - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:48:0
> Module not found: Can't resolve 'fs'
> null
> Could not find files for /test in .next/build-manifest.json

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
Use examples/simple with the following page:
```
import React from 'react';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const Page = () => {
    return (
        <div>test</div>
    );
};

// export const getServerSideProps = async ({ locale }) => ({
//     props: {
//         ...await serverSideTranslations(locale, ['common']),
//     },
// });

export default Page;
```

Uncomment getServerSideProps to get the page working.

## Expected behaviour
Import should not break the app.

## OS (please complete the following information)
 - Device: [Linux PC]
 - Browser: [e.g. Chrome 90.0.4430.85]

**Comment by isaachinman** [comment]
This is down to how NextJs strips/optimises client/server bundles. If you don't use the import in a server-side data fetching method, NextJs won't know to strip it from your client bundle.

**Comment by MonstraG** [comment]
> 
> 
> This is down to how NextJs strips/optimises client/server bundles. If you don't use the import in a server-side data fetching method, NextJs won't know to strip it from your client bundle.

I've faced this issue when I've attempted to reduce amount of stuff I need to write in every getServerSideProps:

```ts
export const getServerSideProps = async (ctx: GetServerSidePropsContext) =>
	await getPropsWithTranslations(ctx, ["psychologists"], {
		data: fetch("/api/get", ctx),
	});
```
where getPropsWithTranslations is in another `helpers.ts` file:
```
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getPropsWithTranslations = async (
	ctx: GetServerSidePropsContext,
	namespaces: string[],
	request: Promise<any>
) => ({
	props: {
		...(await request),
		...(await serverSideTranslations(ctx.locale, namespaces))
	}
});
```
How could I get around this issue?

**Comment by Qclaire** [comment]
So what's the solution to the original problem? You've closed the issue but I see away to fix it @isaachinman
