### ISSUE TITLE
Optimization when the keys equal the source language

### ISSUE THREAD

**Issue by queicherius** [isaachinman/next-i18next#1158]
First off, thanks for the library! It's probably the easiest to set up translation library I have used so far.

All of my translation keys look like this, where the key is equal to the source language:

```tsx
<Trans>Sign in to your account</Trans>
t('Sign in to your account')
```

This enables an optimization for other languages, where the fallback language can get removed. This works with `fallbackLng: false` in the config. 👍

It would also enable another optimization where `__NEXT_DATA__` is not written into the HTML at all for the source language, but I could not figure out a way to make that work. Is that an option currently, or if not is that something that would be a potential future feature?

**Comment by queicherius** [comment]
Managed to get it working with this:

```
export const getStaticProps: GetStaticProps = async ({ locale }) => ({
  props: {
    ...(locale !== 'en' ? await serverSideTranslations(locale as string) : undefined),
  },
})
```

Does that have any side effects I am not aware of?

**Comment by isaachinman** [comment]
@queicherius Yeah, that would probably work, and to be honest I think this type of logic should be left up to users, and not incorporated into `next-i18next` itself, as it's quite opinionated.

**Comment by queicherius** [comment]
Small warning if anyone else is trying this as a bundle optimization:

This breaks plural handling via `<Trans count={count}>` (and probably context handling too)
