### ISSUE TITLE
Automatic key compression

### ISSUE THREAD

**Issue by queicherius** [isaachinman/next-i18next#1159]
It would be an interesting feature to automatically compress the keys into a short hash of their contents:

```ts
t('The email address cannot be longer than 256 characters.')
// -> Compressed to t('ad6b8') in source
// Resulting translation files:
// en.json: {"ad6b8":"The email address cannot be longer than 256 characters."}
// de.json: {"ad6b8":"Die E-Mail Addresse kann nicht laenger als 256 Zeichen sein."}
```

This way the resulting JS bundle would be smaller, the resulting `__NEXT_DATA__` code embedded in the HTML would be smaller and the JSON locale files would be smaller.

Original idea from here: https://github.com/lingui/js-lingui/issues/139

**Comment by isaachinman** [comment]
Sounds like a cool idea. PRs welcome!

**Comment by queicherius** [comment]
I might try my hand at this, but I am unsure of some details.

- Replacing the keys in the resulting `__NEXT_DATA__` is pretty straightforward, and I think I already found the spot to do this.
- The JSON locale files are served from the public directory, I am not sure how to pre-process them before handing them to the browser. Maybe a Next plugin?
- Same thing with the JS bundle, I am not sure how to pre-process the AST to rewrite the keys before handing the JS bundle to the browser.

**Comment by isaachinman** [comment]
@queicherius Assuming all HTML/JS/JSON is being passed through gzip or brotli compressed in users' deployed envs, would this type of optimisation even have an effect? I'd like to see some real-world measurements before actually proceeding.

**Comment by queicherius** [comment]
I did a small test with the localization files of a simple sign-in page, with 18 entries:

Locale JSON files (the HTML embed would exhibit the same behaviour):

- `en/sign-in.json`: 474b gzip
- `en/sign-in-compressed.json`: 516b gzip (+42b, +8.86%)
- `de/sign-in.json`: 773b gzip
- `de/sign-in-compressed.json`: 674b gzip (-189b, -12.80%)

JS files, served independently from language:

- `sign-in.js`: 3878b gzip
- `sign-in-compressed.js`: 3763b gzip (-115b, -2.96%)

Another thing I noticed while manually replacing values to put these numbers together, is that `<Trans>` that have JSX in them, e.g. `<Trans>Read more <a>here</a></Trans>` can't be replaced, so those would be untouched by this optimization. This affected 2 keys in this test.

**Comment by queicherius** [comment]
I ended up writing a little package to do this, it already works for most simple cases but is missing a little bit of logic for interpolation (interpolated React components already work tho!). At the moment, the savings are about 50% of the locale file size ([here's a table](https://github.com/devoxa/next-i18next-compress/pull/3#issue-653227654)).

-> https://github.com/devoxa/next-i18next-compress

**Comment by isaachinman** [comment]
Cool work, @queicherius! If you ever felt like it's stable enough to merge into `next-i18next` core, please do let me know.
