### ISSUE TITLE
i18n.dir is not a function

### ISSUE THREAD

**Issue by birdwell** [isaachinman/next-i18next#1165]
## Describe the bug
You must provide a clear and concise description of what the bug is.
i18n isn't populated with anything. It's an empty object.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.
"^8.2.0"

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.
```
  const { i18n } = useTranslation();
  const direction = i18n.dir(language);
```

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.
That you would be able to use i18n off the useTranslation. We switched from react-i18next and it worked without having to do anything else.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]
 - MBP 2017 16''
 - Chrome

**Comment by isaachinman** [comment]
Cannot reproduce in the [simple example](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L13). Please provide a reproducible repo. Thanks!

**Comment by birdwell** [comment]
@isaachinman I created two examples:
Typescript - https://codesandbox.io/s/condescending-grass-qg6nr
Javascript - https://codesandbox.io/s/heuristic-villani-nyhzy

Typescript I'm still working on getting going it's throwing an error. Javascript the pages need the getStaticProps | getServerSideProps to work properly. I didn't realize that was a requirement for the library. I thought it was optional for some reason. I will add that and report back.

**Comment by birdwell** [comment]
I have added getServerSide and had to change the serialization to import the config directly. 

Now, I've got this error: 
```
Error: You are passing a wrong module! Please check the object you are passing to i18next.use()
```

**Comment by isaachinman** [comment]
@birdwell I've loaded your JS codesandbox, and don't see any errors. Please provide a reproducible repo.

**Comment by birdwell** [comment]
I finally got it all set up correctly. It was a mix of making the next-i18next.config.js use export default instead of module.exports once it's imported into _app.

**Comment by isaachinman** [comment]
Glad to hear it!
