### ISSUE TITLE
How to use serverSideTranslations in dynamic route page

### ISSUE THREAD

**Issue by bnlambert** [isaachinman/next-i18next#1166]
I want to use `serverSideTranslations` inside my dynamic route page. 

I keep having build error

`... en/product/5 was not fount in page/product/[[...id]] ...`

How can I resolve this given that I need both `serverSideTranslations`  and dynamic route?

**Comment by isaachinman** [comment]
Hi @bnlambert – I don't think I understand your issue. The `serverSideTranslations` method should work fine for dynamic routes. If you believe you have found a bug, can you please provide a reproducible example?

**Comment by bnlambert** [comment]
I was able to resolve the issue, thank you @isaachinman
