### ISSUE TITLE
Initial locale argument was not passed into serverSideTranslations

### ISSUE THREAD

**Issue by AhsanNissar** [isaachinman/next-i18next#1167]
## Describe the bug
The bug appears during the build of nextjs app but no bug appears while running the app. Since the build does not get passed, there I cannot deploy the application

> Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
> Error: Initial locale argument was not passed into serverSideTranslations

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
My project structure is almost the same as in the example at master branch. I have a pages directory with _app.tsx file and index.tsx file. There are other folders like login, register, forgot-password etc. All of them have in them this code with a difference in just namespace names

index.tsx

```
import { useAuth } from 'common/roq-hooks/use-auth';
import { MainLayout } from 'layouts/main/main.layout';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import React, { FunctionComponent } from 'react';
import { useTranslation } from 'react-i18next';

const HomePage: FunctionComponent = () => {
  const { t } = useTranslation('common');
  const { accessToken } = useAuth({ redirectTo: '/login' });

  if (!accessToken) {
    return <div>{t('loading')}</div>;
  }

  return <MainLayout title={t('homePage.title')}>{t('homePage.title')}</MainLayout>;
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});

// eslint-disable-next-line @roq/no-invalid-page-resource
export default HomePage;
```

## Expected behaviour
I kept building the app but it failed everytime so I passed 'en' value in place of locale inside `serverSideTranslations` method of every page and the build was successfull but then the `en` got setup as the only language and it wasn't even changing. So I think that while building the app locale should get initialized with default language but must be changeable too when running the application.

## OS (please complete the following information)
 - Device: [e.g. T460 Lenovo"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
You will need to provide an _entire_ reproducible repository so that I can debug. Thanks!

**Comment by AhsanNissar** [comment]
Its quite impossible for me to provide a reproducible example. I know that the example repo works fine during build too but the build is failing in my case. Now i literally have no clue what could be wrong or how I can create an example for you

**Comment by AhsanNissar** [comment]
@isaachinman you were right, there was no issue with next-i18 but with our own config file `next.config.ts`. I had added i18n in it but inside the development phase block so when making a build for production i18n was not getting initialized. I got the idea from this link https://stackoverflow.com/a/67066847/11746564.
