### ISSUE TITLE
router.push() add one locale after the previous one

### ISSUE THREAD

**Issue by Alfxjx** [isaachinman/next-i18next#1168]
## Describe the bug
I use "zh" as the defaultLocale, when I use router.push, the routes add zh after /en-US.
```
// localhost:3000 => default zh
router.push(router.locale === 'zh' ? '/en-US' : '/zh');
// localhost:3000/en-US => change to en
router.push(router.locale === 'zh' ? '/en-US' : '/zh');
// localhost:3000/en-US/zh 
```
## Occurs in next-i18next version

"next": "^10.0.9",
"next-i18next": "^8.2.0",

## Steps to reproduce
```
const Index = () => {
  const router = useRouter();
  const { t } = useTranslation('common');
  const handleClick = (e) => {
    e.preventDefault();
    router.push(router.locale === 'zh' ? '/en-US' : '/zh');
  };
  return (
    <Main>
      <p>{t('h1')}</p>
      <button
        type="button"
        style={{ marginLeft: 5 }}
        className="border-2 border-blue-500"
        onClick={handleClick}
      >
        {t('change-locale')}
      </button>
    </Main>
  );
};
```
## Expected behaviour
I want when push /zh the route to be localhost:3000/zh and then when click the button, the route will be replace to localhost:3000/en-US, not localhost:3000/zh/en-US

## OS (please complete the following information)
 - Device: [e.g. MBP 2020 13"]
 - Browser: [e.g. Edge 90.0.818.46]

**Comment by isaachinman** [comment]
Please check the [NextJs documentation](https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales) on how to change the locale. Good luck!

**Comment by Alfxjx** [comment]
> Please check the [NextJs documentation](https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales) on how to change the locale. Good luck!

thank you for reply I'm new to nextjs
