### ISSUE TITLE
Loosing translation between route transitions. 

### ISSUE THREAD

**Issue by meliborn** [isaachinman/next-i18next#1177]
## Describe the bug
Before visiting a new page, but right after when you clicks on the ```<Link/>``` there is a time moment when I'm able to see the page without translation (only keys).

## Steps to reproduce
```javascript
export const getServerSideProps: GetServerSideProps = async ({ locale }) => ({
	props: {
		...(await serverSideTranslations(locale as string, ['signUp', 'footer', 'common', 'header'])),
	},
});

const { t } = useTranslation('signUp');
```
## Expected behaviour
No loosing translations

## Screenshots

https://user-images.githubusercontent.com/735194/116944712-b2c45480-ac7e-11eb-87f8-6b4d080521fd.mov

**Comment by isaachinman** [comment]
Can you please provide a reproducible repository?

**Comment by meliborn** [comment]
@isaachinman I realized it's because of using http://reactcommunity.org/react-transition-group/ between page transitions. Without wrapping in ```<Transition>``` it works, but I have no idea how to fix it.

**Comment by isaachinman** [comment]
Can you provide a reproducible repo? Ideally repro the issue in the [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple). Thanks!

**Comment by meliborn** [comment]
@isaachinman https://github.com/meliborn/next-i18n

**Comment by isaachinman** [comment]
@meliborn That is because you put `<Transition>` inside `_app`, which gets wrapped entirely by `appWithTranslation`. If you want this to work smoothly, you'll need to make sure `<Transition>` goes _outside_ `appWithTranslation`, so that it can persist instead of remounting:

```tsx
import { appWithTranslation } from 'next-i18next'
import { useRouter } from 'next/router'

const MyApp = ({ Component, pageProps }) => <Component {...pageProps} />

export default function AppWithTransition(props) {
  const App = appWithTranslation(MyApp)
  const router = useRouter();
  return <Transition location={router.pathname}><App {...props} /></Transition>
}
```

Good luck!

**Comment by meliborn** [comment]
@isaachinman what if I have the following components structure:
```
<App>
  <Header />
  <Page />
<App />
```
and need to wrap with <Transition> only <Page> component because <Header /> always keep the same. But I use translation in Header too.

**Comment by YusukeSano** [comment]
@isaachinman 
I bumped into the same issue.

> @isaachinman what if I have the following components structure:
> 
> ```
> <App>
>   <Header />
>   <Page />
> <App />
> ```
> 
> and need to wrap with `<Transition>` only `<Page>` component because `<Header />` always keep the same. But I use translation in Header too.

If you want to apply the route transition animation only to the Page component, appWithTranslation cannot support the Header component.

Is there any solution?
