### ISSUE TITLE
Language detector doesn't work on subpaths

### ISSUE THREAD

**Issue by marekSurak** [isaachinman/next-i18next#1178]
## Describe the bug
Language detector works fine when opening the app on root URL (www.mysite.com) but when opening the app with subpath (www.mysite.com/something) it does not detect language and instead of it is using `defaultLocale` variable.
The same problem you can see on your own demo https://next-i18next.com.
When you open the app with https://next-i18next.com it works fine, but it should also detect the language when you open https://next-i18next.com/second-page.
I don't see any reason why it should work only for the root path. Or it should be at least configurable.

**Comment by isaachinman** [comment]
Yep, that's currently the functionality offered by NextJs as a framework. Please feel free to check out the documentation. Good luck!
