### ISSUE TITLE
Is there a way to prevent loading the default locale when the user is on a different one?

### ISSUE THREAD

**Issue by hpsantos** [isaachinman/next-i18next#1179]
I'm adding internationalization to a Next.js 9.5.5 app, using next-i18next 7.0.1.
Assuming the following configs (the ones in the example for v7.0.1):
```
module.exports = new NextI18Next({
  otherLanguages: ['de'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales')
})
```
```
new NextI18Next({
  localeSubpaths: {
    de: 'de'
  }
})
```

After building the app and running it with `npm run start`.
When I access a page with my locale set to 'de', the server will send me both the german and english resource files.

Is there a way to circumvent this and get the resources only for the currently selected locale?
I've noticed that if I set `fallbackLng: true` it will behave "correctly" as if there was no fallback, but I'm wondering if this can lead to problems later down the road.

**Comment by isaachinman** [comment]
Hi @hpsantos – unfortunately I don't have the bandwidth to support previous versions of `next-i18next` actively. That said, if you want to open a PR to add a new feature to v7.x, I would certainly review and merge it. Thanks!

**Comment by hpsantos** [comment]
Hi @isaachinman, I'm short on time at the moment but if I get around to to it I'll let you know. Thanks
