### ISSUE TITLE
Missing namespaces if they are not in the defaultLanguage (but exist in the fallbackLng)

### ISSUE THREAD

**Issue by Nikoms** [isaachinman/next-i18next#1181]
## Is your feature request related to a problem? Please describe.
The methods `getAllNamespaces()`used in `serverSideTranslations.ts` and  `createConfig.ts` are only used with the `defaultLocale`. The problem is that `fallbackLng` may have more namespaces. If we do not take the namespaces from the fallback too, we have missing fallback translations displayed

## Describe the solution you'd like
Instead of just taking the translations in `${localePath}/${defaultLocale}`, we should also take the namespace from `${localePath}/${config.fallbackLng}`

## Describe alternatives you've considered
Good question :) I've also seen that right now `fallbackLng` can only be a string, but in the "official doc", it may be an array, an object or even a function (this one is more complicated). I would make a big "merge" of all languages to get all the namespaces. And maybe put a warning if the `fallbackLng` is a function 😁

For the moment, I made the loop myself in `next-i18next.config.js` AND I also had to give the same list (of all namespaces) to `originalServerSideTranslations`

I'm considering making a PR, but I just have to find the time 😅 

Thanks for the lib, it really helps us to smoothly migrate from react to nextjs

**Comment by isaachinman** [comment]
@Nikoms Are you saying that you have namespaces in alternate locales which don't exist for your default locale?

**Comment by Nikoms** [comment]
@isaachinman exactly. 

Quick example: I'm building different website depending on some locales. For one of them, my prefered (default) language is en-GB. But I don't have all translations in it because it only overwrites some "en" translations.

I don't want to put "en" as default locale because it is used as "fallback" only


I don't know if that makes sense 😇

**Comment by isaachinman** [comment]
Yep, makes sense. A PR would be welcomed.
