### ISSUE TITLE
Multi Fallback Language 

### ISSUE THREAD

**Issue by EslaM-M** [isaachinman/next-i18next#1182]
## Describe the bug
The issue is when define fallbackLng as an object with multiple fallback options it deson't work 
`  fallbackLng: {
      'en-eg': ['en'],
  }`
  it only works if I defined the fallbackLng as a string like 
  fallbackLng: 'en'

after some investigation on the library itself i found this block of code 
`  if (typeof config.fallbackLng === 'string') {
              initialI18nStore[config.fallbackLng] = {};
            }`
which means the fallback language assigned if it's a string only.
## Occurs in next-i18next version
8.2.0

## Steps to reproduce

- in the next-i18next.config.js file add this as i18n  object 
```
module.exports = {
  i18n: {
    locales: ['en', 'en-eg', 'ar-eg'],
    defaultLocale: 'en-eg',
    otherLanguages: ['en', 'en-eg', 'ar-eg'],
    fallbackLng: {
      'en-eg': ['en'],
    },
    load: 'all',
    debug: true,
    lowerCaseLng: true,
  },
};
```

- add the local files in the following path

![test](https://user-images.githubusercontent.com/7307221/117303711-4c595500-ae7d-11eb-92d5-0c8dc2bcc89f.png)

try to use a translation key that exists on the en/common.json while your language is
ar-en. you will find that the key is not translated hover it's defined as a fallback language
`

## Expected behavior
if  you define a fallback language for a specific language it should be working probably 

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Browser: [e.g. Chrome  89.0.4389.90 ]

**Comment by isaachinman** [comment]
Your `next-i18next.config.js` is incorrect, the `i18n` nested object is _only_ for NextJs i18n config – i18next options should be siblings to that nested object. Good luck!

**Comment by EslaM-M** [comment]
@isaachinman I'm sorry but I didn't get what you mean?
