### ISSUE TITLE
Incorrect peer dependency i18next

### ISSUE THREAD

**Issue by HeadFox** [isaachinman/next-i18next#119]
Hi guys ! :)
I have this warning during my yarn install. Is it from your package.json or am I missing something ?
Thanks !

Error:
```warning "next-i18next > react-i18next@9.0.7" has incorrect peer dependency "i18next@>= 13.1.3".```

Packages: 
- next: 7.0.2
- next-i18next: 0.20.0

**Comment by isaachinman** [comment]
It was on our side, but was not affecting anything. Fixed with e4f588a.
