### ISSUE TITLE
i18next-http-backend causes the resource store to be empty

### ISSUE THREAD

**Issue by birdwell** [isaachinman/next-i18next#1194]
## Describe the bug
You must provide a clear and concise description of what the bug is.
I have created a replicable version based on the basic example provided in this repo. [https://codesandbox.io/s/heuristic-villani-nyhzy](https://codesandbox.io/s/heuristic-villani-nyhzy
)
 i18next-http-backend when added into the use array causes the translations to not resolve. I dove into the code to realize the resource store for i18next is empty. I haven't dug into why it happens when the i19next-http-backend is introduced. I plan on doing that soon. 

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explicit commit causing the issue.
v8.2.0

## Steps to reproduce
You must provide a reproducible repository or copy/paste blocks of code that are sufficient to reproduce the bug.
Add `const I18NextHttpBackend = require("i18next-http-backend/cjs");` to the next-i18next.config.js and add it to the use array `use: [I18NextHttpBackend]`.  [https://codesandbox.io/s/heuristic-villani-nyhzy](https://codesandbox.io/s/heuristic-villani-nyhzy
)

## Expected behavior
You must provide a clear and concise description of what you expected to happen.
That the resource store would be filled with the translations. 

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
Working before the plugin is enabled
![Screen Shot 2021-05-11 at 1 35 20 PM](https://user-images.githubusercontent.com/3323856/117868815-a84a2200-b25f-11eb-91f9-ae7c32d75d4f.png)

Broken after the plugin is enabled
![Screen Shot 2021-05-11 at 1 35 48 PM](https://user-images.githubusercontent.com/3323856/117868810-a6805e80-b25f-11eb-94de-80ec1a80690f.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
@birdwell That error stack is not helpful at all, but generally speaking you should be changing the lang via NextJs, not `i18n. changeLanguage`. Good luck!

**Comment by birdwell** [comment]
@isaachinman Right, the error stack gives no indication in AppWithTranslation what error occurred. In our case, we are not wanting to go the route lang approach. We want to stay at the base route and not cause a full re-render when the app changes languages.

**Comment by isaachinman** [comment]
@birdwell NextJs handles all routing, so you would need to raise that feature request to the NextJs team directly.
