### ISSUE TITLE
Can't resolve 'fs' when page is not in "pages" folder but exported from another component

### ISSUE THREAD

**Issue by martinratinaud** [isaachinman/next-i18next#1195]
## Describe the bug
I use today an approach by module in all projects I develop
Nextjs is not really adapted for that as all pages are located in the `pages` folder.

I thus create a page in the `pages` folder that only re-export everything from a file placed in another folder like `src/modules/Common/pages`

Using this syntax in `src/pages/home.jsx`

```
export { default, getStaticProps } from "../modules/Common/pages/home";
```

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
I made a repo on github that you can find here https://github.com/martinratinaud/next-i18nnext-issue

```
git clone https://github.com/martinratinaud/next-i18nnext-issue
cd next-i18nnext-issue
yarn
yarn dev
```

## Expected behaviour
There should not be any problem and especially not 

```
Failed to compile
./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:48:0
Module not found: Can't resolve 'fs'
null
```

## OS (please complete the following information)
 - MBP 2019 16"
 - Firefox 88.0.1 (64 bits)

**Comment by isaachinman** [comment]
NextJs performs automatic bundle splitting, as your `getStaticProps` function only runs in a server environment, and needs access to NodeJs APIs like `fs`.

If you want to organise your pages/data fetching functions in some sort of custom way, you'll need to make this feature request to the NextJs team directly.

Good luck!

**Comment by martinratinaud** [comment]
Thanks @isaachinman for the quick answer
