### ISSUE TITLE
Use next.config.js

### ISSUE THREAD

**Issue by wagerfield** [isaachinman/next-i18next#1200]
## Is your feature request related to a problem? Please describe.

Rather than having a separate config file for `next-i18next` I think it would be great if the library could simply use Next's `next.config.js`.

This is the approach all other Next.js plugins take (as far as I'm aware) and I would prefer to keep my repo as "clean/minimal" as possible.

For backwards compatibility, `next-i18next` could look for both config files and "favor" the `next-i18next.config.js` over `next.config.js` when both exist perhaps?

## Describe the solution you'd like

Make `next-i18next.config.js` _optional_ and when not found, use `next.config.js`

## Additional context

Happy to put in a PR for this if it's something that you're open to @isaachinman?

**Comment by isaachinman** [comment]
@wagerfield How would that work? Are you suggesting a nested object inside `next.config.js`? As far as I know, NextJs validates `next.config.js` pretty strictly, which is why I didn't want to go that route.

**Comment by wagerfield** [comment]
@isaachinman I would suggest adding a `i18next` field alongside Next's `i18n` field that would be home to all of `i18next`'s options as well as the ones provided through your package. Either that or merge them in with Next's `i18n` object. I guess the former is the slightly "safer" option.

With regards to Next's config validation—there are some checks—but they're for backwards compatibility (eg. warn that an option is being deprecated or no longer supported) OR to validate Next's configuration options.

However, thirdparty options are allowed eg. you can have a `next.config.js` that looks like this:

```js
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
    foo: 1,
    bar: "abc",
  },
  foo: 1,
  bar: "abc",
  i18next: {
    foo: 1,
    bar: "abc",
  },
}
```

...and Next does not complain about the foreign fields within and alongside the `i18n` config object.

My rationale for wanting to just have one config object (Next's one) are two fold:

1. I would prefer to have one config object over two to appease my OCD and keep the configuration and maintenance of `i18n` stuff in one place/file
2. You have to have a `next.config.js` for `i18n` (with or without `next-i18next`) —but you don't need the `next-i18next.config.js` IMO since the `i18n` object is being shared/pulled into Next's config from the `next-i18next` config

Here's what I propose the `next.config.js` could look like:

```js
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en", "fr"],
  },
  i18next: {
    // next-i18next options
    defaultNS: "core",
    localePath: "./locales",

    // i18next options
    preload: true,
    cleanCode: true,
  },
}
```

**Comment by isaachinman** [comment]
> However, thirdparty options are allowed

Has the Vercel team explicitly stated this anywhere? I wouldn't want to go down this path unless we have explicit permission to use `next.config.js` for third party purposes.

**Comment by wagerfield** [comment]
When I said that they "are allowed" I meant that Next does not bork during the build phase when it parses the `next.config.js`

There are no official docs giving permission to use the `next.config.js` for your own plugins per se, but there is a [GH Discussion RFC](https://github.com/vercel/next.js/discussions/9133) in the works for making Next more extensible to thirdparty plugins with lifecycle hooks etc...however it's been pretty quiet from the maintainers.

Popular libraries like `next-pwa` augment the `next.config.js` with functions like `withPWA` —https://www.npmjs.com/package/next-pwa

...so there is no "official" way of doing things as far as I'm aware.

Having an isolated `i18next` config object alongside Next's official `i18n` one in the `next.config.js` seems like a pretty safe and nice alternative to having a separate config IMO—but perhaps that's just me?

**Comment by isaachinman** [comment]
Perhaps it might be best to open an issue on the NextJs repo and explicitly ask the Vercel team if this is something they recommend/support?

**Comment by wagerfield** [comment]
@isaachinman I trawled through [Next's issues (open and closed)](https://github.com/vercel/next.js/issues?q=is%3Aissue+plugin+) as well as the [discussions board](https://github.com/vercel/next.js/discussions?discussions_q=plugin) about all things plugin related and as you can imagine, there's already **_a lot_** of chatter.

The most relevant discussion I could find is the [Plugins RFC](https://github.com/vercel/next.js/discussions/9133) that I linked to above, however the discussion has fizzled out and the [last comment from one of the core maintainers was back in Nov 2019](https://github.com/vercel/next.js/discussions/9133). 

The [most recent comment (from Mar of this year)](https://github.com/vercel/next.js/discussions/9133#discussioncomment-427763) is from someone asking what the status is on this feature, so repeating that question is unlikely to achieve anything.

I thought about opening an issue, but it's more of a question—so I decided against it. Starting another discussion thread is also unlikely to receive any kind of official response or permission from the Next.js team given the mountain of issues and discussion threads that they already have open.

My question for permission would simply get lost in a sea of noise.

So until such times that we see this much needed and requested feature land, it's very much the Wild West I'm afraid.

Having said that, what I am suggesting is not uncommon—in fact it's very much the norm, so I don't see any issues in supporting an `i18next` configuration object alongside Next's `i18n` one.

Even if Next decide to rollout an update that sanitises their config and `pick` only the official supported keys during the build phase, this will have no effect on what I am proposing because they're being read independently.

The worst thing Next could do is analyse the config and throw an Error during the build phase if it finds any unofficial keys in the config object. However, that would be a pretty serious breaking change since **_a number_** of popular plugins are already doing this, so it would break this ecosystem.

Here are some examples I grabbed from [Awesome Next's Extensions list](https://github.com/unicodeveloper/awesome-nextjs#extensions):

- [next-pwa](https://github.com/shadowwalker/next-pwa)
- [next-plugin-graphql](https://github.com/lfades/next-plugin-graphql)
- [nextein](https://github.com/elmasse/nextein)
- [next-mdx-blog](https://github.com/hipstersmoothie/next-mdx-blog)
- [next-purgecss](https://github.com/lucleray/next-purgecss)

This pattern is so common that there's even a plugin for composing plugins in Next's config: [next-compose-plugins](https://www.npmjs.com/package/next-compose-plugins)

**Comment by isaachinman** [comment]
Thanks for this detailed and comprehensive report @wagerfield. It's clear that you're a motivated contributor and it'd be great to work together. I will ask the Vercel team about their opinion on this via Slack and let you know what they say. Thanks!

**Comment by isaachinman** [comment]
Hey @wagerfield – I remembered why I didn't use `next.config.js` initially. The Vercel platform performs some perf/in-memory optimisations of the config file, so if you try to import it via `fs` on Vercel, you will find that it doesn't actually exist in the filesystem.

Any idea how those other plugins may or may not work on Vercel? The Vercel team has specifically advised to not import anything from `next.config.js`.

**Comment by wagerfield** [comment]
Hey @isaachinman I was unaware of the special treatment of the `next.config.js` on Vercel.

I had a play around and managed to pull in the `next.config.js` using `require` in the `getStaticProps` method.

Not sure if this is ok or not...but it works haha.

Anyway, here's the repo: https://github.com/wagerfield/vercel-next-config-test

...and here's the deployed Next.js site on Vercel: https://vercel-next-config-test.vercel.app

...not sure how useful this is given what you wrote above, but at least it demonstrates that the `next.config.js` can be read and used server side on Vercel.

**Comment by isaachinman** [comment]
Thanks @wagerfield. Even if it technically _can_ be read at the present moment, I would prefer not to rely on unofficial/undocumented features, as the Vercel team tends to move quickly and things can change pretty drastically, even in minor version bumps.

For now, having a separate config file seems like the safest bet. I hope the Vercel team improves the ecosystem by introducing first-class plugin support soon.
