### ISSUE TITLE
You are passing a wrong module! Please check the object you are passing to i18next.use()

### ISSUE THREAD

**Issue by hiru15** [isaachinman/next-i18next#1201]
Hello and thank you very much for the work done.

update to v8.2, and I get the following message: Error: You are passing a wrong module! Please check the object you are passing to i18next.use()

--------------
my next-i18next.config.js contains:

const Fetch = require('i18next-fetch-backend')
const use = [Fetch]

module.exports = {
  i18n: {
    defaultLocale: 'es',
    locales: ['en', 'es'],
    ns: ['common'],
    defaultNS: "common",
    localeStructure: "{{lng}}/{{ns}}",
    serializeConfig: false,
    use,
    backend: {
        loadPath: "https://xxx.com/locales/{{lng}}/{{ns}}.json",
        requestOptions: {
          mode: 'no-cors',
          credentials: 'include',
          cache: 'default'
        },
        crossDomain: true,
         keySeparator: false,
         nsSeparator: false,
      },
  }
}
----------------------------
my next.config.js contains: 

const { i18n } = require('./next-i18next.config.js')

module.exports = {
  i18n
}

---------------------------

in my _app.js using:

import { appWithTranslation } from 'next-i18next'
import nextI18NextConfig from './../next-i18next.config.js'

export default appWithTranslation(MyApp,nextI18NextConfig)

--------------------------

and in my page using: 

import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from './../../next-i18next.config.js'

export async function getStaticProps({ locale }) {
return { props: {
    ...await serverSideTranslations(locale, ['common'],nextI18NextConfig),
    }
  }
  
  
 The main problem that I saw (from my point of view), is that when the next-i18next instance is created with the use, it does not manage to pass the module to the i18next layer, and this is where this message jumps. If I delete these lines, the instance manages to initialize but does not load any json through the backend.

**Comment by isaachinman** [comment]
Your config is incorrect. It should look like this:

```tsx
module.exports = {
  i18n: {
    defaultLocale: 'es'
  },
  use, // This is a top level property, not inside i18n
}
```

**Comment by hiru15** [comment]
Pass the use out of the i18n, and I keep getting the same error, by any chance do you have an example using backend?

**Comment by AlexandrePhilibert** [comment]
Here is an example of my next-i18next.config.js using `i18next-http-backend` :

```javascript
const I18NextHttpBackend = require("i18next-http-backend");

module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["de", "en", "fr", "it"],
  },
  serializeConfig: false,
  // There seems to be an issue with the way the plugins are being loaded, this should ensure
  // that you always pass a valid plugin
  use: [I18NextHttpBackend.default ?? I18NextHttpBackend],
  backend: {
    // Your custom path
    loadPath: "http://localhost:3000/assets/translations/{{lng}}/{{ns}}.json",
    backends: [I18NextHttpBackend],
  },
};

```
