### ISSUE TITLE
8.2.0 is not properly bundled

### ISSUE THREAD

**Issue by RihardKrauz** [isaachinman/next-i18next#1203]
## Describe the bug
Language for me is not changing properly, because the result bundle in npm does not match the code on github.

## Occurs in next-i18next version
`"next-18next": "8.2.0"`

## Steps to reproduce
Compare files, for example:
 - in github: `/src/serverSideTranslations.ts` lines **50-52**
 - in result bundle (from npm): `dist/commonjs/serverSideTranslations.js` line **128**

## Expected behaviour
```
config.locales.forEach(lng => {
    initialI18nStore[lng] = {}
  })
```
  
  should be presented in the result bundle

**Comment by RihardKrauz** [comment]
**archive 8.2.0 - serverSideTranslations.ts**
```
const initialI18nStore: Record<string, any> = {
    [initialLocale]: {},
  }

  if (typeof config.fallbackLng === 'string') {
    initialI18nStore[config.fallbackLng] = {}
  }

  if (namespacesRequired.length === 0) {
    const getAllNamespaces = (path: string) =>
      fs.readdirSync(path)
        .map(file => file.replace(`.${localeExtension}`, ''))

    namespacesRequired = getAllNamespaces(path.resolve(process.cwd(), `${localePath}/${defaultLocale}`))
  }
```

**github (actual) - serverSideTranslations.ts**
```
const initialI18nStore: Record<string, any> = {}

  config.locales.forEach(lng => {
    initialI18nStore[lng] = {}
  })

  if (namespacesRequired.length === 0) {
    const getAllNamespaces = (path: string) =>
      fs.readdirSync(path)
        .map(file => file.replace(`.${localeExtension}`, ''))

    namespacesRequired = getAllNamespaces(path.resolve(process.cwd(), `${localePath}/${defaultLocale}`))
  }
```

**Comment by isaachinman** [comment]
I have not published the package in awhile – I always add a commit to the `master` branch to indicate release. Thanks!
