### ISSUE TITLE
How to acess a folder which has a same name as locale in 'public'?

### ISSUE THREAD

**Issue by sheruce** [isaachinman/next-i18next#1209]
I have a folder named 'jp' in my  /public. But in my locales has a '/jp' too. 
![2021-05-17 2 39 02](https://user-images.githubusercontent.com/48618708/118442799-a8459880-b71d-11eb-98f7-9394e53dc242.png)
So when I want to access files by localhost:3000/jp/50off.png .  The route seems to want to lead me to a page, but this is not what I want.
Is there any way to solve this problem without changing the file name?
Thanks！

**Comment by isaachinman** [comment]
Sounds like a general sort of NextJs question. Perhaps try StackOverflow, or similar. Good luck!
