### ISSUE TITLE
locale is undefined when using getServerSideProps with Express server

### ISSUE THREAD

**Issue by Slowl** [isaachinman/next-i18next#1211]
## Describe the bug
Hi ! I've been using next-i18next v4.5.0 for a while now. I finally decided to update to 8.3.0 and adapt all my pages with getStaticProps and getServerSideProps instead of the getInitialProps.

But I've encountered multiple issues in this migration, and the one I still can't resolve is having `locale` undefined when using `getServerSideProps` which returns : 

```bash
Error: Initial locale argument was not passed into serverSideTranslations
```

BUT, it works when using getStaticProps, the `locale` is correct and not undefined

Worth mentioning is that I use a custom Node.js / Express server

## Occurs in next-i18next version
"next-i18next": "8.3.0",

## Steps to reproduce
I will share all of the usefull code / files 

### next.config.js

```js
const { i18n } = require('./next-i18next.config.js')

module.exports = {
	i18n,
	compress: true,
	distDir: '../www',
	future: {
		webpack5: true,
	},
	poweredByHeader: false,
}
```

### next-i18next.config.js

```js
const path = require('path')

module.exports = {
	i18n: {
		defaultLocale: 'fr',
		locales: ['fr', 'en', 'es'],
	},
	localePath: path.resolve('./src/public/locales'),
	supportedLngs: ['fr', 'en', 'es'],
	defaultLanguage: 'fr',
}
```

### _app.tsx

```tsx
  import type { AppProps, } from 'next/app'
  import Head from 'next/head'
  import { appWithTranslation } from 'next-i18next'
  
  import { ThemeProvider } from 'styled-components'
  
  import THEME from '../utils/theme'
  
  const MyApp = ({ Component, pageProps }: AppProps) => {
  
	  return (
		  <>
			  <Head>
				  <meta name='viewport' content='width=device-width, initial-scale=1' />
			  </Head>
			  <ThemeProvider theme={THEME}>
				  <Component {...pageProps} />
			  </ThemeProvider>
		  </>
	  )
  }
  
 export default appWithTranslation(MyApp)
```

### Page with `getServerSideProps` where `locale` is undefined

```jsx
export async function getServerSideProps({ query, locale }) {

  return {
    props: {
      ...(await serverSideTranslations(locale, ['homeTalent', 'navbar', 'downloadApp', 'footer'], nextI18NextConfig)),
      missions: query?.data?.missions,
    },
  }
}

```

### Page with `getStaticProps` where `locale` is correct

```jsx
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['homepage', 'navbar', 'offers', 'footer'], nextI18NextConfig)),
    }
  } 
}
```

## Expected behaviour
`locale` should have the correct current locale, the same way it is for static pages

## OS (please complete the following information)
 - Device: Ubuntu 20.10
 - Browser: Mozilla Firefox v88.0.1

## Additional context
I can add Express code if needed.

The issue is resolved when using page folder navigation and when I access to the page with it's file name, but not when requested through a custom server

**Comment by isaachinman** [comment]
I don't think that recent v10+ versions of NextJs support custom servers at all actually. I don't have any knowledge in this area, so you'd have to post on StackOverflow or the NextJs repo for assistance. Sorry I couldn't be of more use. Good luck!

**Comment by MSefer** [comment]
Did you find any solution for this issue? @Slowl

**Comment by Slowl** [comment]
No ... Unfortunately the only way I found to fix this issue was to handle the locale myself with my custom server.

Meaning that I handle the routing with Express.js, and then, I pass the language parameter of the requested URL as my `locale`

I can explain more in detail with code examples, if needed.
