### ISSUE TITLE
Build error no such file or directory exists

### ISSUE THREAD

**Issue by AhsanNissar** [isaachinman/next-i18next#1214]
## Describe the bug
You must provide a clear and concise description of what the bug is.

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
There is a pages directory and inside it I have a edit page for companies which will be rendered with an [id]. Even though everything works and page does get rendered. But on building the application I get error

## Expected behaviour
Build should pass.

## Screenshots
![Screenshot (537)](https://user-images.githubusercontent.com/14846851/119006702-071f4200-b9aa-11eb-9a62-2e5051efebbe.png)

Here is the code for my edit page

```
import { WithAuthorization } from 'common/roq-hocs';
import { MainLayout } from 'layouts';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import React, { FunctionComponent } from 'react';
import { CompaniesEditView } from 'views/companies-edit';

const CompanyCreatePage: FunctionComponent = () => {
  const { t } = useTranslation('companiesEdit');
  return (
    <MainLayout title={t('title')}>
      <WithAuthorization
        permissionKey="companies.update"
        failComponent={
          <div className="mt-16 text-2xl text-center text-gray-600">
            <span>{t('noView')}</span>
          </div>
        }
      >
        <CompaniesEditView />
      </WithAuthorization>
    </MainLayout>
  );
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'companiesEdit'])),
  },
});

export const getStaticPaths = () => ({
  paths: ['/companies/edit/[id]'],
  fallback: true,
});

export default CompanyCreatePage;
```

**Comment by AhsanNissar** [comment]
@isaachinman Please take a look at this. I am not sure why the build is failing and inside the export folder no file like [id] gets created there when the build is running and therefore this error shows up but don't know why

**Comment by isaachinman** [comment]
First, it seems like you haven't properly wrapped your `_app` with `appWithTranslation`. Second, the ENOENT error doesn't look related to `next-i18next` at all. Please post on StackOverflow for help. Good luck!

**Comment by AhsanNissar** [comment]
`_app` is wrapped with `appWithTranslation` like this `export default appWithTranslation(MyApp);`

**Comment by AhsanNissar** [comment]
The error is occuring while build the next app and is completely related to next-i18 because without next-i18 other builds are working fine

**Comment by AhsanNissar** [comment]
@isaachinman please take a look at this thread here. I am still unable to resolve it https://stackoverflow.com/questions/67624322/nextjs-dynamic-routes-with-next-i18next-build-error

**Comment by isaachinman** [comment]
I am out of office for the next two weeks. Pinging this thread repeatedly will not achieve anything for you.
