### ISSUE TITLE
TypeError: Cannot read property 'allLanguages' of undefined

### ISSUE THREAD

**Issue by ngocketit** [isaachinman/next-i18next#122]
Hi,

I tried the example in the documentation against the latest version (0.20.0) and got lots of warnings and errors:

```
warning  in ./pages/_app.js

"export 'appWithTranslation' was not found in '../i18n'

 warning  in ./pages/_app.js

"export 'i18n' was not found in '../i18n'

 warning  in ./components/NavBar.js

"export 'withNamespaces' was not found in '../i18n'

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'allLanguages' of undefined
    at _default (../app/store/node_modules/next-i18next/dist/middlewares/next-i18next-middleware.js:25:29)
```

Here is the `i18n.js` file:
```
import NextI18Next from 'next-i18next';

const options = {
  localePath: 'public/locales',
};
export default new NextI18Next(options);
```

**Comment by ngocketit** [comment]
This seems to happen only when I use `withNamespaces()` in a non-page component. Any ideas?

**Comment by isaachinman** [comment]
Please provide a reproducible repository. Thanks!

**Comment by ngocketit** [comment]
Sorry it seems to be my own mistake. It's all good now.

**Comment by isaachinman** [comment]
The first part of this issue is related to #138, and a fix is incoming. However, I'm not sure about this part:

> This seems to happen only when I use withNamespaces() in a non-page component. Any ideas?

**Comment by jterrazz** [comment]
I had the same error when I was using the basic `react-i18next` provider.

In my `_app.js`:
```javascript
import {I18nextProvider} from 'react-i18next'; // Remove this
import i18next from '../utils/i18n'; // Remove this

class MyApp extends App {
  render() {
    return (
      <I18nextProvider i18n={i18next}>
         ...
        <Component {...pageProps} />
        ...
      </I18nextProvider>
    )
  }
}
```

**Comment by max-software-net** [comment]
I solved it by passing nextI18next.default in my server.js like this:

`server.use(nextI18NextMiddleware(nextI18next.default))`
