### ISSUE TITLE
Provide additional namespaces to the 'ns' list

### ISSUE THREAD

**Issue by mycodedig** [isaachinman/next-i18next#1222]
## Is your feature request related to a problem? Please describe.
How can I provide an extra `ns` custom values in the options of next-i18next.config.js

## Describe the solution you'd like
n/A

## Describe alternatives you've considered
n/A

## Additional context
```
const extraNs = ['scope1/ns1', 'scope2/ns2'];
module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'fr'],
    },
    localePath: path.resolve('./public/locales'),
    localeStructure: '{{lng}}/{{ns}}',
    saveMissing: true,
    ns: extraNS,        

// I want to add some values in `ns` object like `extraNS` above so that it will get added to those `ns` values which is there 
// if i do not provide `ns` custom list in the next-i18next.config.js. If I provide `ns` object like above, the whole `ns` 
// object values will be replaced by the extraNS...I want to add the values by `extraNS` not a complete replacement of `ns`
};
```

**Comment by mycodedig** [comment]
The requirement is I have my locale file like
```
public 
	- static
		- locales
			- en
				- Scope1
					- ns1
				- Scope2
					- ns2
				ns3
				ns4
				ns5
			- fr
				- Scope1
					- ns1
				- Scope2
					-ns2
				ns3
				ns4
				ns5
```

So, to load the namespaces present under scope, I have to provide them to the `ns` options like `ns = ['Scope1/ns1', 'Scope2/ns2']`
And for the namespaces which are out of any scope, I want them as it is.

**Comment by isaachinman** [comment]
If you pass `ns` into your config, you will need to pass the complete array.

**Comment by mycodedig** [comment]
Thanks @isaachinman for the quick response. I provided complete array and it worked.
But I am not able to see language translations appearing after changing the language though I am able to see the language is changed in the cookies respective to `next-i18next` but it is appearing in `i18n` object. Do you have any early thoughts on this ?
