### ISSUE TITLE
next-18next appWithTranslation lighthouse page speed problem

### ISSUE THREAD

**Issue by escalepion** [isaachinman/next-i18next#1223]
## Describe the bug
Hello everyone. We have been getting really low  score from browser's lighthouse tab and google page speed insights. We tried many things and we figured out that wrapping the app.js with "appWithTranslation" effecting our app in a very bad way. Is there anyway to implement next-18next in another way ?

## Occurs in next-i18next version
"next-i18next": "^4.5.0"

## Steps to reproduce
Removing main wrapper which collapsing whole app (appWithTranslation).

## Expected behaviour
Wrapping application shouldn't effect the performance in a bad way.

## Screenshots
Before / After
![image](https://user-images.githubusercontent.com/26687352/119687057-8ea7fd80-be4f-11eb-86d3-b8f21009d7c4.png)
![image](https://user-images.githubusercontent.com/26687352/119687103-99fb2900-be4f-11eb-862c-ac8cb901b4b2.png)

## OS (please complete the following information)
 Tried both windows and osx, and chrome and opera browsers.

**Comment by isaachinman** [comment]
Previous versions of `next-i18next` are not supported.
