### ISSUE TITLE
Error: Default namespace not found at public/locales/%{lng}/%{ns}.json

### ISSUE THREAD

**Issue by ahakem** [isaachinman/next-i18next#1224]
## Describe the bug
getting error
`Error: Default namespace not found at public/locales/%{lng}/%{ns}.json`
![image](https://user-images.githubusercontent.com/299959/119718890-6ed10380-be68-11eb-9300-985c9136597c.png)

## Occurs in next-i18next version
`"next-i18next": "^8.3.0"`

## Steps to reproduce
with the follwing config
``` module.exports = {
  i18n: {
    defaultLanguage:'en',
    defaultLocale: 'en',
    fallbackLng:"en",
    locales: ['en','de','fr'],
    localeStructure: '%{lng}/%{ns}',
    interpolation: {
      prefix: '%{',
      suffix: '}',
    }
  },
}```

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by ahakem** [comment]
@isaachinman I was trying just with the test repo, here you go I pushed it here
https://github.com/ahakem/next-i18n-test

**Comment by Selvdrap** [comment]
I'm having the same error. Is it correct to pass `fallbackLng` option directly to i18n object? 


```
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'es'],
        localePath: path.resolve('./public/translations'),
        fallbackLng: 'en',
    },
```

**Comment by ahakem** [comment]
> I'm having the same error. Is it correct to pass `fallbackLng` option directly to i18n object?
> 
> ```
>     i18n: {
>         defaultLocale: 'en',
>         locales: ['en', 'es'],
>         localePath: path.resolve('./public/translations'),
>         fallbackLng: 'en',
>     },
> ```

@Selvdrap I'm already using a fallbackLng, but he can't find the path, also I'm using the local path

**Comment by isaachinman** [comment]
@ahakem The `interpolation` value is for actual i18next translations, not for `lng` and `ns` in `localePath`. Check [this line](https://github.com/isaachinman/next-i18next/blob/master/src/config/createConfig.ts#L59). You will need to update your `localePath` value to use `{{lng}}` and `{{ns}}`.

**Comment by ahakem** [comment]
@isaachinman yes I understand that the `interprlations` for the translations it self but when I do so I get no translations at all and I added the `localeStructure` based on your comment [here](https://github.com/isaachinman/next-i18next/issues/620#issuecomment-576636654) 
so I'm not sure what is the right configration or how to write the `localePath` in the right way.
