### ISSUE TITLE
nextI18NextRewrites not available for v8

### ISSUE THREAD

**Issue by ahakem** [isaachinman/next-i18next#1233]
trying to migrate from version 6 to v8 and have issues with the localSubPaths

in my project, we have this kind of subpaths
```
const localeSubpaths = {
  de: 'motorrad-mieten',
  fr: 'location-moto',
  es: 'alquiler-de-motos',
  nl: 'motorverhuur',
  it: 'noleggio-moto',
  pt: 'aluguel-de-motos',
  ru: 'ru',
  ar: 'ar',
  ko: 'ko',
  sv: 'sv',
  no: 'motorsykkelleie',
  da: 'motorcykeludlejninger',
  ja: 'ja',
};
```

in the old versions, I was using 
`nextI18NextRewrites(localeSubpaths)` into nextJS rewrite but seem this no longer available in version 8, 
any clue to achieve this?

**Comment by isaachinman** [comment]
Read the documentation carefully, please. In v8+, NextJs itself [handles the routing](https://nextjs.org/docs/advanced-features/i18n-routing).
