### ISSUE TITLE
How to integrate custom server with next internationalized routing feature

### ISSUE THREAD

**Issue by aNyMoRe0505** [isaachinman/next-i18next#1234]
I think this issue is about how Next.js implement internationalized routing and custom server.

I post here is because it related to i18n and want to seek for help 

Please let me know if I need to delete this issue or not.

I'm sorry if there is any offense.

Currently I have a next application with custom server and i18n

since `v10.0.0`,  next.js has built-in support for internationalized routing

so I refactor my code and update my package (next-i18next included)

but I found seems currently has no way to integrate custom server and internationalized routing feature

here is [sample code](https://github.com/aNyMoRe0505/next-custom-server-i18n)

(npm i && npm run dev)

when I landing to a page, I can't get the locale info by router

Is there has any way to integrate custom server and internationalized routing feature ?

**Comment by isaachinman** [comment]
The `next-i18next` package no longer relies on any aspect of custom servers or middlewares. If you'd like to use a custom server, just read up on the [relevant documentation](https://nextjs.org/docs/advanced-features/custom-server).
