### ISSUE TITLE
Unable to use within a dynamic route

### ISSUE THREAD

**Issue by herbievine** [isaachinman/next-i18next#1237]
## Describe the bug
Unable to use the `useStaticProps` or `useServerSideProps` in a dynamic route.

## Occurs in next-i18next version
next-i18next v.^8.4.0

## Steps to reproduce
Simply create a dynamic route in nextjs like `users/[id].tsx`

## Expected behavior
It's supposed to work with a dynamic route

## Screenshots
<img width="1440" alt="Screen Shot 2021-06-03 at 10 35 12" src="https://user-images.githubusercontent.com/41120535/120614346-6a53ae80-c457-11eb-94c4-fec9ec851ef1.png">

## OS (please complete the following information)
 - Device: MacBook Pro OSX Yosemite 10.10.5 (14F2109)
 - Browser: Firefox Developer v78

## Additional context
If this is an expected error could you please provide a fix or workaround as I'm somewhat new to the whole SSR/SSG stuff. Thanks! :)

**Comment by herbievine** [comment]
Here is a [link](https://github.com/herbievine/blog/blob/main/pages/post/%5Bslug%5D.tsx#L59-L63) to the repo/file with the issue.

**Comment by isaachinman** [comment]
@herbievine This seems like a general NextJs help question, and StackOverflow is probably more suitable. Good luck!

**Comment by EliasTouil** [comment]
@herbievine as stated by the error, you can't use getStaticProps and getServerSideProps for the same page.

That being said have you solved your issue? I'm also unable to get a translation working in a dynamic route (src/pages/userProfile/[id].tsx).

**Comment by herbievine** [comment]
Yes, I've found a solution. So you basically need to statically generate the routes using [`getStaticPaths`](https://www.notion.so/herbie/8ef8154fdcd54f828df5807e28d54993?v=18e761ba18a0487387324dd49c686f15). So let's say you have an array of paths like so:

```
[
  'path-1',
  'path-2',
  'path-3'
]
```

You would want to render it like so (with ts):

```typescript
export const getStaticProps: GetStaticProps = async ({ params, locale }) => {
  const data = // fetch your page data

  return {
    props: {
      post: data,
      ...(await serverSideTranslations(locale, ["common", "post-[slug]"])), // ["common", "post-[slug]"] these the files you want to use in this page. no need to import unnecessary translations
    },
  };
};

export const getStaticPaths: GetStaticPaths = async ({ locales }) => {
  const data = [
    'path-1',
    'path-2',
    'path-3'
  ]

  const paths = locales.reduce(
    (acc, next) => [
      ...acc,
      ...data.map(path => ({
        params: {
          slug,
        },
        locale: next,
      })),
    ],
    []
  );

  return {
    paths,
    fallback: false,
  };
};

```

If you need more help feel free to ask. Here's a [link](https://github.com/herbievine/blog/blob/main/pages/post/%5Bslug%5D.tsx) to the repo where I had this issue for the full code

**Comment by christophby** [comment]
Instead of the locales.**reduce** above I used this (more readable way) inside the `getStaticPaths` function:

```js
let paths: Array<{ locale: string; params: { slug: string } }> = [];

locales.forEach((locale) => {
    data.forEach((path) => {
        paths.push({
          locale,
          params: { slug: path },
        });
    });
});
```
