### ISSUE TITLE
TypeError: Cannot read property 'namespacesRequired' of undefined

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#124]
I got this error after update the package to version 0.20.0
```
TypeError: Cannot read property 'namespacesRequired' of undefined
    at Function._callee$ (xxx\node_modules\next-i18next\dist\hocs\app-with-translation.js:169:69)
    at tryCatch (xxx\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (xxx\node_modules\regenerator-runtime\runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (xxx\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (xxx\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (xxx\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```
After investigated. I found that the error occur when I add getInitialProps in _app.jsx like below.
```
class MyApp extends App {
  static async getInitialProps({ ctx }) {
    return {}
  }

  render () {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Component {...pageProps} />
      </Container>
    )
  }
}

export default appWithTranslation(MyApp)
```

**Comment by capellini** [comment]
I think you should remove your 'getInitialProps` method.

**Comment by vimutti77** [comment]
Actually, I have the code that need to run in `getInitialProps` method of every page. But I don't want to write the same code on every page. So I need to write it on _app.js.

**Comment by vimutti77** [comment]
I got it! Thank you for your explanation.

**Comment by isaachinman** [comment]
This is exactly as the official [NextJs](https://github.com/zeit/next.js#custom-app) docs show as well.

**Comment by joeonmars** [comment]
Caveat is that you have to name pageProps as is in the doc, changing the prop name would results in undefined error from app-with-translation.js.

**Comment by isaachinman** [comment]
@joeonmars That's correct, but that's just a NextJs thing. Would you like us to throw a more descriptive error?

**Comment by joeonmars** [comment]
@isaachinman throwing an error would be nice for this case with a link to the code example/next.js doc.

**Comment by isaachinman** [comment]
@joeonmars Fixed with 8e195bb.

**Comment by tkow** [comment]
I don't know if my problem is same at this. But I faced the same error in server side when production build though it don't reproduce in development server.
Also,  I deploy my app by firebase hosting so it may be related to cookie unavailable without named __session. Do you have any idea about this situation?

![2019-02-14 21 15 27](https://user-images.githubusercontent.com/7004725/52786429-27127d80-309e-11e9-855c-efebbfa0948a.png)

**Comment by tkow** [comment]
I found my problem is possible to pass pageProps is undefined in my production mode `_app.js` codes.I solved this use
```
const pageProps = context.Component.getInitialProps ? await context.Component.getInitialProps(context.ctx) : {}
```
instead of 
```
const pageProps = context.Component.getInitialProps && await context.Component.getInitialProps(context.ctx)
```
I don't know why previous code works in development , but you may care about this if you are in same situation.

**Comment by fhourdin** [comment]
Got a similar issue, I'm using other HOC like "withRedux" and "withRedux" saga, My problem was fixed by moving "appWithTranslation" to the first level :

```export default withRedux(makeStore)(withReduxSaga(appWithTranslation(MyApp)))```

**Comment by hellojere** [comment]
Had a similar issue as well, but with `getInitialProps`. Solved it by moving `appWithTranslation` to the functional component as well.

Did not work: 
```
const MyApp =  ({ ...props }) => (
  <App />
);

export default appWithTranslation(MyApp);
```

Works: 
```
const MyApp = appWithTranslation(
  ({ ...props }) => (
    <App />
  )
);

export default MyApp;
```
