### ISSUE TITLE
support for class component as well 

### ISSUE THREAD

**Issue by Ali-A-Koye** [isaachinman/next-i18next#1241]
not sure if the package actually supports Class Components but i have been facing an issue with Hooks can only be called inside the body of a function component whenever i try to use useTranslation in a body of render of class component o_O 

its also not mentioned in the documentation

**Comment by isaachinman** [comment]
For class components, you can use the [`withTranslation` HOC](https://react.i18next.com/latest/withtranslation-hoc). You can import this from `next-i18next` directly:

```tsx
import React from 'react'
import { withTranslation } from 'next-i18next'

class MyComponent extends React.Component {
  render() {
    return (
      <div>{this.props.t('hello-world')}</div>
    )
  }
}

export default withTranslation()(MyComponent)
```
