### ISSUE TITLE
Error on placeholder type

### ISSUE THREAD

**Issue by RicardoBrito1938** [isaachinman/next-i18next#1247]
Hello team, the translation is working as desired, but i am facing an issue with placeholder prop on input tag  with typescript

![image](https://user-images.githubusercontent.com/51454097/121070844-964b9880-c7a5-11eb-8096-be970edf4f16.png)

is happening this error on typescript

Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2322)
index.d.ts(2106, 9): The expected type comes from property 'placeholder' which is declared here on type 'DetailedHTMLProps<InputHTML

i am currently using     "next-i18next": "^8.2.0",

**Comment by isaachinman** [comment]
This is not related to `next-i18next` – typings for the `t` function come from `i18next`, and I assume they are valid. You can cast to a string if you are sure it will return as a string.

**Comment by RicardoBrito1938** [comment]
Hello, thanks for the reply, i did the cast and the error stopped, thanks
