### ISSUE TITLE
react-i18next:: You will need to pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by m2vi** [isaachinman/next-i18next#1249]
## Describe the bug
I recently added the package and got this error. I have followed all the steps as far as I know. 

## Occurs in next-i18next version
8.4.0

## Steps to reproduce
https://github.com/m2vi/downloader

## OS
 - Device: POP OS
 - Browser: Brave

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!

**Comment by semasad** [comment]
Hi! I had the same problem. After iterate a lot of solutions, the fix was very unexpected. 
At the layout "page" I just exported withTransaltion & getStaticProps. At the end of the file I just added:

```
export const getStaticProps = async ({ locale }) => ({
	props: {
		...await serverSideTranslations(locale, ['common', 'footer', 'menu']),
	},
})

export default withTranslation('common')(Layout);
```

**Comment by isaachinman** [comment]
Use of `withTranslation` is not required whatsoever. The `appWithTranslation` HOC wraps your entire app in a provider.

**Comment by dmi3y** [comment]
Yup, that what I figured out later, my mistake was not including `getStaticProps`. Thanks!
