### ISSUE TITLE
ns option being overridden on the client to [defaultNS]

### ISSUE THREAD

**Issue by wagerfield** [isaachinman/next-i18next#1250]
## Describe the bug

The `ns` option is being [overridden client side to `[defaultNS]`](https://github.com/isaachinman/next-i18next/blob/c83e7460ce7116932175ac0176e86384a17a776a/src/config/createConfig.ts#L143) within `createConfig` which is preventing `i18next-hmr` from referencing the user-provided `ns` option.

Here's the issue thread: https://github.com/felixmosh/i18next-hmr/issues/32#issuecomment-858366571

## Occurs in next-i18next version

    next-i18next@8.4.0

## Steps to reproduce

```jsx
// pages/index.jsx

import { serverSideTranslations } from "next-i18next/serverSideTranslations"
import { useTranslation } from "next-i18next"

export const IndexPage = () => {
  const { i18n } = useTranslation()
  const ns = i18n?.options.ns ?? []

  console.log(ns) // always [defaultNS] on the client

  return <h1>Namespaces: <pre>{JSON.stringify(ns)}</pre></h1>
}

export default IndexPage

export const getStaticProps = async ({ locale }) => ({
  props: await serverSideTranslations(locale),
})
```

## Screenshot

<img width="889" alt="Screenshot 2021-06-10 at 10 08 38" src="https://user-images.githubusercontent.com/412747/121498170-122b2800-c9d4-11eb-884b-00ea6f6f25fe.png">

In the screenshot above, I am rendering `JSON.stringify(i18n.options.ns)`

Here's the code: https://github.com/wagerfield/i18next-hmr-hook/blob/main/src/components/page.jsx#L44

## Expected behaviour

The `i18n.options.ns` value should be the same as the provided option in `next-i18next.config.js` on the client and server.

## OS (please complete the following information)

- Device: MBP 2019 16"
- Browser: Chrome 91.0.4472.77 (Official Build) (x86_64)

## Additional context

As mentioned above, this bug is preventing `i18next-hmr` from being able to perform HMR on the client for all user provided namespaces. It only works for the `defaultNS` due to the line referenced above. Commenting out this line results in the `ns` being correct on the client and `i18next-hmr` works as expected:

    // combinedConfig.ns = [defaultNS]

I expect the fix for this is to wrap the assignment line like so:

```js
if (!Array.isArray(combinedConfig.ns)) {
  combinedConfig.ns = [defaultNS]
}
```

**Comment by isaachinman** [comment]
Yep, wrapping the assignment with that type of guard seems like a good simple fix. Are you willing to put together a PR? We will also need test coverage for this case.

**Comment by wagerfield** [comment]
Sure thing, I'll put something together this evening 🙌
