### ISSUE TITLE
Use `--build` with TypeScript

### ISSUE THREAD

**Issue by RA80533** [isaachinman/next-i18next#1253]
The `--build` flag enables speed optimizations by storing compilation metadata in a file. It will reduce build times *significantly* if `tsc --build` is called at least once prior. For example, if `tsc --build` is called immediately after a previous call without any new changes having been made, the command will be almost instant.

- Untrack tsconfig.tsbuildinfo via .gitignore
- Update every occurrence of `tsc` with `tsc --build`

Enjoy much faster builds!

EDIT: Some of the files are entangled with circular dependencies. Those would have to be refactored out before any speed improvements can be obtained.

**Comment by isaachinman** [comment]
1. We are not tracking any `tsconfig.tsbuildinfo` file via git
2. Build times for `next-i18next` are not a concern to maintainers at this time
