### ISSUE TITLE
query string is disappear after change language when localeSubpaths is true

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#126]
When I enable `localeSubpaths`. If I change language, the query string will be removed from the url.

### Expected behavior
1. Start on the url like `http://localhost:3000/?foo=123`
2. Change language by using `i18n.changeLanguage('de')`
3. The url will changed to `http://localhost:3000/de/?foo=123`

### Actual behavior
1. Start on the url like `http://localhost:3000/?foo=123`
2. Change language by using `i18n.changeLanguage('de')`
3. The url will changed to `http://localhost:3000/de/`

**Comment by isaachinman** [comment]
I wonder if that is indeed the expected behaviour. I can see arguments for both sides.

@capellini What is your opinion?

**Comment by radeno** [comment]
@vimutti77 @isaachinman by my opinion both ways are correct, its about about expression.
Method `changeLanguage` doesn't say anything more than it changes language.

I think there should be option to prevent or do not prevent change of actual URL.

Preventing of change:
`domain.com/de/page/123?foo=bar#row1` => `domain.com/es/page/123?foo=bar#row1`
`domain.com/page/123?foo=bar&lang=de#row1` => `domain.com/page/123?foo=bar&lang=es#row1`

Do not preventing
`domain.com/de/page/123?foo=bar#row1` => `domain.com/es`
`domain.com/page/123?foo=bar&lang=de#row1` => `domain.com/es`

Or third option:

Define full URL (without domain) and language is appended automatically.

**Comment by capellini** [comment]
IMO the query string should be preserved (`http://localhost:3000/de/?foo=123`).  But I believe that #96 should also fix this.

@vimutti77 Can you confirm that this problem goes away if you temporarily install this branch in your project?

```bash
npm i git://github.com/capellini/next-i18next.git#app-with-translation-custom-routes
```

**Comment by capellini** [comment]
> Method `changeLanguage` doesn't say anything more than it changes language.

This is why I believe we should preserve the URL in its entirety, except for making the `localeSubpaths` change, as needed.

Whether or not the query parameters are removed should be an implementation decision outside the scope of this project.  If those query parameters are needed elsewhere by internal application logic, we will break the app.

If the user wants to manipulate the query or hash on their own by adding/removing them or leave them intact, depending on their requirements, they are free to do so.  However, I don't think that falls within the purview of `next-i18next`.

**Comment by isaachinman** [comment]
> However, I don't think that falls within the purview of next-i18next.

Agreed. Please find out if #96 fixes this, and mark it as such if so. Thanks!

**Comment by ngocketit** [comment]
While this may be a bit different but in my case, I need to have different query for different languages. For example, the slug will be language specific, e.g, `/en/english-slug` and `/de/german-slug`. Currently, when changing the language, only the langcode is changed but the query remains the same. Is there any way I could achieve get?

**Comment by isaachinman** [comment]
@ngocketit No, that's well outside the scope of `next-i18next` at the moment, and you're better off rolling your own implementation, taking guidance from this project and other examples of custom routing.

**Comment by ngocketit** [comment]
@isaachinman Thanks! I guess I'll need to leave out `localeSubpaths` and handle the route change automatically when the locale is changed. Btw, does it support listening for the locale change?

**Comment by capellini** [comment]
@ngocketit We're working on PR #90 which would help to handle your use case server-side.  You would just call your middleware after `server.use(nextI18NextMiddleware(nextI18next))` in your `server.js` file, and modify your `req` object as needed.

I would need to think more about how to do the client-side routing, but my initial inclination is that, with Next's router object, withRouter HoC, and [something similar to what we do in `appWithTranslation` in PR #96](https://github.com/isaachinman/next-i18next/blob/1559b70104b3b2b252794325ea7f361035ea8e36/src/hocs/app-with-translation.js#L20-L29), it can be done.

**Comment by AhsanNissar** [comment]
@isaachinman Hi, can I get support for this thread? https://stackoverflow.com/questions/67591370/next-i18next-translations-with-dynamic-id-and-query-param
