### ISSUE TITLE
Adding `i18next-ICU` plugin gives an error

### ISSUE THREAD

**Issue by hazem3500** [isaachinman/next-i18next#1261]
## Describe the bug
When I add the `i18next-ICU` plugin it gives an error of
```
TypeError: Cannot read property 'type' of undefined
at PROJECT_DIRECTORY\node_modules\next-i18next\dist\commonjs\createClient\node.js:64:16
```

## Occurs in next-i18next version
`^8.5.0` with `i18next-icu` -> `^2.0.3`

## Steps to reproduce

Add the `i18next-icu` plugin
```
// next-i18next.config.js

const ICU = require('i18next-icu').default

module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de'],
        use: [ICU],
    },
    serializeConfig: false,
}
```

then do the other steps for handling [unserializable configs](https://github.com/isaachinman/next-i18next#unserialisable-configs)

## Expected behaviour
It should work without giving an error

## OS (please complete the following information)
 - Device: Desktop, Windows 10
 - Browser: Chrome 91.0.4472.101

**Comment by isaachinman** [comment]
That is [this line](https://github.com/isaachinman/next-i18next/blob/master/src/createClient/node.ts#L22) it sounds like your `const ICU` import is actually `undefined`. You probably don't need the `.default`. Good luck!

**Comment by hazem3500** [comment]
I've tried using it without `.default` but it gave another error
```
Error: You are passing a wrong module! Please check the object you are passing to i18next.use()
```

**Comment by flex-junwoo** [comment]
@isaachinman i have the same issue.

```
SerializableError: Error serializing `._nextI18Next.userConfig.use[0]` returned from `getStaticProps` in "/".
Reason: `object` ("[object Object]") cannot be serialized as JSON. Please only return JSON serializable data types
```
it is error messages.

My guess is that 'UserConfig.use' should contain an object that can be decomposed into JSON.
and `i18next-icu`is return `Class Function`.

This is where the problem arises.

please check it. and fixed. 🙏

**Comment by hazem3500** [comment]
you need to set the `config.serialzeConfig` to `false` as mentioned [here](https://github.com/isaachinman/next-i18next#unserialisable-configs)

**Comment by flex-junwoo** [comment]
oh my god. thankyou!

**Comment by hazem3500** [comment]
@flex-junwoo did it work for you after setting `config.serialzeConfig`? because after I set it, it gives me the error above.

**Comment by flex-junwoo** [comment]
Yes.  it is work!! try it.

**Comment by hazem3500** [comment]
Can you send your config? cause I've tried it and it doesn't seem to work

**Comment by flex-junwoo** [comment]
of course, here it is
![스크린샷 2021-06-17 오후 5 48 22](https://user-images.githubusercontent.com/72372724/122363821-37033a80-cf94-11eb-8bc8-79c27a02f083.png)

**Comment by flex-junwoo** [comment]
i think your code doesn't fit the format.

```js
// next-i18next.config.js

const ICU = require('i18next-icu').default

module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de'],
        use: [ICU],
    },
    serializeConfig: false,
}
```

to 

```js
// next-i18next.config.js

const ICU = require('i18next-icu').default

module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de'],
    },
    use: [ICU],
    serializeConfig: false,
}
```

**Comment by hazem3500** [comment]
Thanks @flex-junwoo 😄, will try your fix out!

**Comment by hazem-osama** [comment]
I'm still getting the error

here are my configs
```js
// next-i18next-config.js

const ICU = require('i18next-icu')

module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'de', 'ar'],
    },
    use: [ICU],
    serializeConfig: false,
}
```

```js
// next.config.js

const { i18n } = require('./next-i18next.config')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')(['react-children-utilities'])

module.exports = withPlugins([
    [i18n],
    [withTM],
])
```

```js
// _app.js
import App from 'next/app'
import { appWithTranslation } from 'next-i18next'
import nextI18nextConfig from '../../next-i18next.config'

function MyApp({ Component, pageProps }) {
    // ...
}

MyApp.getInitialProps = async (appContext) => {
    const appProps = await App.getInitialProps(appContext)
    return { ...appProps }
}

export default appWithTranslation(MyApp, nextI18nextConfig)
```

```js
// page.js
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import nextI18NextConfig from '../../next-i18next.config'

function Page() {
    // ...
}

export async function getStaticProps() {
    return {
        props: {
            ...(await serverSideTranslations(
                'en',
                ['common'],
                nextI18NextConfig
            )),
        },
    }
}

export default Page
```

and here is the error 

![image](https://user-images.githubusercontent.com/74589180/123593225-8ea07200-d7ee-11eb-96f4-40d20921c9f6.png)

my package versions
```json
{
  "i18next-icu": "^2.0.3",
  "next-i18next": "^8.5.0",
  "next": "^10.2.3"
}
```

is there something wrong that I'm not seeing?

**Comment by ecklf** [comment]
@hazem-osama did you manage to solve this issue? Facing the exact same.

**Comment by hazem3500** [comment]
@ecklf nope, didn't manage to solve it 😅

**Comment by ecklf** [comment]
I've decided to use https://www.i18next.com/translation-function/plurals instead. This does not solve the issue but might be a good alternative without introducing a new dependency.
