### ISSUE TITLE
next-i18next fails silently if translation JSON fails to parse

### ISSUE THREAD

**Issue by Newbytee** [isaachinman/next-i18next#1265]
## Describe the bug
Currently, if next-i18next fails to parse the translation JSON, instead of telling the developer about this and making it clear that this is the reason their translations aren't working, next-i18next stays silent and acts as though the translation isn't there. This may apply to other uses of JSON in next-i18next too, but I did not attempt to reproduce it with those.

## Occurs in next-i18next version
8.5.0 and 8.4.0. Presumably earlier versions too, but I have not tested those.

## Steps to reproduce
Set up a sample next-i18next app and write JSON that will fail to parse, e.g. by adding a trailing comma:

```json
{
  "start-create-account": "Start by creating your account.",
  "welcome": "Welcome",
}
```

## Expected behaviour
next-i18next makes it clear that it failed to parse the JSON and shows an error.

## OS (please complete the following information)
 - Device: Self-built PC running Fedora 34
 - Browser: Firefox 89.0 and Ungoogled Chromium 88.0.4324.150

**Comment by isaachinman** [comment]
PRs welcome.

**Comment by adrai** [comment]
#1294
