### ISSUE TITLE
when i try to use multiple serverSideTranslations in getStaticProps it doesn't works.

### ISSUE THREAD

**Issue by shivika24** [isaachinman/next-i18next#1266]
when i try to use multiple serverSideTranslations in getStaticProps it doesn't works.

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["landingPage", "LogoutBanner"])),
    ...(await serverSideTranslations(locale, ["translation", "PrivateLayout"])),
    ...(await serverSideTranslations(locale, ["header", "HomepageBanner"])),
  },
});

this overrides the translations.

**Comment by isaachinman** [comment]
Why are you attempting to do this in the first place? Just pass all your namespaces into one array. Good luck!
