### ISSUE TITLE
Loads all languages after migrate to next.js v11 (webpack 5)

### ISSUE THREAD

**Issue by olehkhalin** [isaachinman/next-i18next#1267]
It used to work well before updating.
Namespaces works fine, but load all languages:
![image](https://user-images.githubusercontent.com/63460724/122644817-cdb03280-d11f-11eb-89a8-8b0267d1f825.png)

**Comment by isaachinman** [comment]
You'll need to provide a reproducible repository. Thanks!

**Comment by olehkhalin** [comment]
Yeah, sorry for that. It wasn't good from my side.

Git repo: https://github.com/olehkhalin/next-i18next-bug
Deployment preview: https://next-i18next-bug-tau.vercel.app/

**Comment by isaachinman** [comment]
This is actually not specific to NextJs v11, and is a regression introduced by #1186, cc @ktml. I will revert those changes now.
