### ISSUE TITLE
componentDidMount called twice when using withNamespaces

### ISSUE THREAD

**Issue by devrasec** [isaachinman/next-i18next#127]
The lifecycle method componentDidMount of the wrapped component is called twice when using withNamespaces.

**Comment by jamuhl** [comment]
Just made a quick test on the sample here: https://github.com/i18next/react-i18next/tree/master/example/react

I did not get the componentDidMount called twice - but might be some wrapped component deeper in the JSX tree that gets deleted and mounted again - hard to tell.

Would be great if @devrasec could provide a pure react-i18next sample to reproduce, eg. based on https://codesandbox.io/s/l4qrory2nl

**Comment by isaachinman** [comment]
I tested this within the [example](https://github.com/isaachinman/next-i18next/tree/master/example) and found no issues. Please provide a reproducible example.
