### ISSUE TITLE
about translation file format

### ISSUE THREAD

**Issue by hanseonghye** [isaachinman/next-i18next#1277]
Hi! I`m using 'next-i18next' well. I have some question about translation file format.

Our company give translation file like this.

```json
{
  "team" : "team name"
  "messsage" :  {
    "service_name" : {
        "key1" : "value1",
        "key2" : "value2",
    }
  }
}
```

of course, If i change file like this, It is ok.
```json
 {
      "key1" : "value1",
      "key2" : "value2",
 }
```

 But I wonder if it is possible to translate without changing the contents of the file.

**Comment by isaachinman** [comment]
Yes, please read the appropriate i18next documentation. The [`keySeparator` option](https://www.i18next.com/overview/configuration-options#misc) is relevant in your case. Good luck!

**Comment by hanseonghye** [comment]
> Yes, please read the appropriate i18next documentation. The [`keySeparator` option](https://www.i18next.com/overview/configuration-options#misc) is relevant in your case. Good luck!

Thank you. It was implemented using 'keySeparator' and deep key.
Then we have to approach 'path1.path2.real_key' , is there a way to specify the deep key('path1.path2)? 
I want to only access by key('real_key')
