### ISSUE TITLE
changeLanguage not working with next-i18next

### ISSUE THREAD

**Issue by shivika24** [isaachinman/next-i18next#1279]
const { i18n } = useTranslation();

when i am trying to use i18n.changeLanguage("en") it gives an error(TypeError: i18n.changeLanguage is not a function)

**Comment by isaachinman** [comment]
https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales

**Comment by shivika24** [comment]
but i don't want to pass locale in the URL?

**Comment by nightwolf-041** [comment]
> but i don't want to pass locale in the URL?

i have this problem too,
but i can't get answers...
