### ISSUE TITLE
Patch detect-node until there is a more testable version?

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#128]
Currently, we're using `detect-node` by importing it straightaway:
```js
import isNode from 'detect-node'
// ...
if (isNode) { //...
``` 
Since `detect-node` exports only a boolean, this requires is to create two unit test files for every file that uses `detect-node`. which is less than ideal.  I have an issue in with detect-node (iliakan/detect-node#13) to see if there is a better way to do a unit test, or if they want to make a more testable version, but have not heard back yet.

In the meantime (and in case they don't agree), we can make our own `detect-node` by doing something like the following in a separate file:
```js
import isNode from `detect-node`

export { isNode }
```
And then we can use it as a named import, like so:
```js
import { isNode } from 'util/detect-node'
// ...
if (isNode) { // ...
```
The only thing that changes is the import, from a default to a named import.  But now we can test like so:
```js
import detectNode from 'util/detect-node'
jest.mock('util/detect-node', () => ({
  isNode: true
}))
```
and then just change the value of `detectNode.isNode` as required in our tests, allowing us to combine tests into one.

To me, it's a very small change that would allow us to greatly improve the readability of our tests.  What do you think?  If you agree, I'll create a PR for it.

**Comment by isaachinman** [comment]
It looks like `detect-node` is not actively maintained. That said, there are like 4 million weekly downloads on the package. Someone must be unit testing, somehow. Are you absolutely sure there's no way to do this, or another similar package that treats testing as a first class citizen?

If the answer to both of those is no, I am fine with the approach outlined above.

**Comment by capellini** [comment]
Given the popularity of `detect-node` and how simple it is (just exports a boolean), I'd rather keep it.

I figured out a way to use [`jest.resetModules`](https://jestjs.io/docs/en/23.x/jest-object#jestresetmodules) to make this work without any added workarounds.  PR forthcoming.
