### ISSUE TITLE
language not save when refresh page

### ISSUE THREAD

**Issue by benamm** [isaachinman/next-i18next#1281]
i have issue with change language 

i used     "next-i18next": "^8.5.1",
and this is my next-i18next.config.js 
```
module.exports = {
  i18n: {
    defaultLocale: 'fr',
    locales: ['en', 'fr'],
    otherLanguages: ['en'],
    localePath: path.resolve('./public/static/locales'),
    detection: {
      lookupCookie: 'next-i18next',
      order: ['cookie', 'querystring', 'localStorage', 'path', 'subdomain'],
      caches: ['cookie'],
    },
  },
};

```

and this next-config.js
```
module.exports = {
  i18n,
};

```

language not saved in cookie

how fix that ?

**Comment by isaachinman** [comment]
You are confusing old configuration options with new ones. Please read the [migration guide](https://github.com/isaachinman/next-i18next/blob/master/docs/v8-migration.md). NextJs itself handles the language cookie now. You can also read about the [`NEXT_LOCALE` cookie](https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie).

Good luck!
