### ISSUE TITLE
Access to createClient function outside

### ISSUE THREAD

**Issue by ivansky** [isaachinman/next-i18next#1282]
## Is your feature request related to a problem? Please describe.
I'm trying to upgrade out 2 year old application to latest next-i18next version from 4th major release.

## Describe the solution you'd like
The only thing I would like to have is possibility to export createClient for our custom express server to create server side i18n instance for nodejs backend with custom language detection.
Also would be great to use advantage of caching i18n instance with SSR rendering within the same createClient module.

## Describe alternatives you've considered
Alternative is just directly import from dist module.

## Additional context
We could not just move from getInitialProps and custom express server, we have a lot differencies with general applications, we don't use language prefixes, our routes have different words based on language, e.g. (/search - en, /suchen - de). Unfortunately.

**Comment by isaachinman** [comment]
You'd need to import that directly from `i18next`. Good luck!
