### ISSUE TITLE
Revalidation stop working after a while time

### ISSUE THREAD

**Issue by VitaliyInshakov** [isaachinman/next-i18next#1283]
## Describe the bug
Hi! No one has encountered such a problem that on the main page of the application, after a while time, it is on the English locale that the revalidate in the _getStaticProps_ stops working, as soon as I change the language to any other and refresh the page, fresh data comes

## Occurs in next-i18next version
Nextjs v11.0.1, next-i18next v8.5.1

**Comment by isaachinman** [comment]
Are you able to provide any further info or documentation of this issue?
