### ISSUE TITLE
how to use next-i18next outside a component

### ISSUE THREAD

**Issue by shivika24** [isaachinman/next-i18next#1284]
i want to use useTanslation hook inside a reducer. is there any way to do that?

**Comment by codeBelt** [comment]
I too would like to know how to use i18next outside of components. I use MobX stores and need to toast notifications with text from i18n.

The approach I am going to take is setting a reference to `i18n` in a global store and then I can reference in other places that are outside of components.

```ts
// _app.tsx
const NextApp= (props) => {
  const { i18n } = useTranslation();

  useEffect(() => {
    globalStore.seti18n(i18n);
  }, [i18n]);

  return <>...</>;
};

export default appWithTranslation(NextApp);
```

```ts
// AboutPage.store.ts
export class AboutPageStore {
  constructor() {
    makeAutoObservable(this);
  }

  loadSomething() {
    const i18next = globalStore.geti18n();

    axios
      .get('/user?ID=12345')
      .then(function (response) {
        toastSuccessMessage(i18next.t('about:successMessage'));
      })
      .catch(function () {
        toastErrorMessage(i18next.t('about:errorMessage'));
      });
  }
}

// AboutPage.tsx
export const AboutPage = (props) => {
  const [localStore] = useState(() => new AboutPageStore());

  useEffect(() => {
    localStore.loadSomething();
  }, [localStore]);

  return <>...</>;
};
```

If there is a better approach, please let me know.

**Comment by isaachinman** [comment]
You can import a global `i18n` instance:

```tsx
import { i18n } from 'next-i18next'
```

**Comment by shivika24** [comment]
console.log("i18n ", i18n.t(`errorResponses:article.articleNotFound`), i18n) this is not working.

**Comment by exipnus** [comment]
This is not working! 

```
import { i18n } from 'next-i18next'
```

i18n is null

**Comment by KubaZachacz** [comment]
FML, I've tested this
`import { i18n } from 'next-i18next'` 
a few months ago and I'm sure it didn't work, I turned all consts placed outside .tsx files to functions with `t` as argument, but being tired of it I came here again looking for a legit way to use translations outside component and IT SEEMS TO WORK NOW! 

@exipnus as TypeScript says about imported i18n `(alias) let i18n: I18NextClient | null` so it can be null, but using optional chaining `i18n?.t('...')` might help
