### ISSUE TITLE
If i pass multiple parameters to useTranslation hook it doesn't works

### ISSUE THREAD

**Issue by shivika24** [isaachinman/next-i18next#1285]
const { t } = useTranslation(['groups','translation'])
 Here groups and translation are both json files.

**Comment by codeBelt** [comment]
What do you mean it doesn't work? How doesn't it work? Does it work when you pass `useTranslation('groups')` or `useTranslation('translation')`?

Are you passing  `['groups', 'translation']` to `serverSideTranslations` on the same page you are using `useTranslation` on?

```js
export const getServerSideProps: GetServerSideProps = async (context) => ({
  props: {
    ...(await serverSideTranslations(context.locale, ['groups', 'translation'])),
  },
});
```

**Comment by codeBelt** [comment]
I just started using `next-i18next` two days. All I can say is it works for me ;). Check out my example branch and see if I am doing things different than you https://github.com/codeBelt/my-next.js-starter/pull/7 . Hopefully this helps. It's hard to trouble shoot if there is no example with the issue.

**Comment by rafagomes** [comment]
@codeBelt Quick question about that multiple translation. Can I use t([multiple items])? I think that was the question. I'm passing 
```
...(await serverSideTranslations(locale, ['common', 'home']))
```
But I can't call multiple. It would be great if we had an example like that, if you give me the proper way, I can enhace the example.

Like:
`const { t } = useTranslation(['common', home'])` or the proper way to use as multiple cases.

**Comment by codeBelt** [comment]
You are going to have to create a public Github repo with a simple example of `next-i18next` that has the issue for me to look at.

What you are showing me should work:

```js
const SomePage = () => {
  const { t } = useTranslation(['common', 'home']);

  return (
    <>
      <div>{t('title')}</div>
      <div>{t('home:h1')}</div>
    </>
  );
};

export const getServerSideProps = async (context) => ({
  props: {
    ...(await typedServerSideTranslations(context.locale, ['common', 'home'])),
  },
});

export default SomePage;
```

**Comment by rafagomes** [comment]
@codeBelt Can I fork your [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple) and enhance over there? This will allow us to have just one source of truth.

**Comment by codeBelt** [comment]
Sure for my example branch https://github.com/codeBelt/my-next.js-starter/tree/next-i18next

**Comment by rafagomes** [comment]
@codeBelt Sure. Will do. :)

**Comment by rafagomes** [comment]
@codeBelt After analyze your code, I think it's more than clear the example about how to use. I think it is a matter of `maybe` change our documentation. Maybe something like: Change:
This demo app is the simple example - nothing more, nothing less.
To:
This demo app is the simple example - nothing more, nothing less. If you want a more complex example, please take a look into this (link to your example).

You're authorizing, I can make that change.

**Comment by codeBelt** [comment]
When you say:

> change our documentation. 

Are you a contributor of `next-i18next`?
___

I would say don't link to my example because I am just playing around and I would need to clean it up. Maybe I will write an [article](https://medium.com/@robertsavian) about my example which may help other people.

**Comment by rafagomes** [comment]
@codeBelt I don't! I would suggest an PR :)

Awesome idea! Have a good one, then. Just trying to help <3

**Comment by isaachinman** [comment]
We don't need to add a new example, but blogs and further documentation are always great. Thanks!
