### ISSUE TITLE
Issue with handling language change

### ISSUE THREAD

**Issue by VeraRibeiro** [isaachinman/next-i18next#1286]
## Describe the bug
Hello. I've an app using react and typescript. I've created a handleLanguageChange,  I can see on the console that the locale has been loaded, however my interface won't change and I won't see the new language (not even after refreshing)
I've seen that in your app the language change is handled through routing, isn't there another way I could do it?
Thanks in advance

## Occurs in next-i18next version
Version 8
"next-i18next": "^8.5.1",

## Steps to reproduce
Here's my code 

next-i18next.config.js
`const path = require('path')

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'pt', 'es'],
    browserLanguageDetection: true,
	  serverLanguageDetection: true,
  },
  debug: false,
  localePath: path.resolve('./apps/app/public/locales'),
};
`

On change

`import { serverSideTranslations } from 'next-i18next/serverSideTranslations'	

const { t, i18n } = useTranslation()

	const handleLanguageChange = (event: React.ChangeEvent<any>) => {
		i18n.changeLanguage(event.target.value as string, () => {
		})
	}`

## Expected behaviour
Expected dashboard to load new translation

## OS (please complete the following information)
 - Chrome

**Comment by codingtub** [comment]
I'm having the same issue in my app, we are using the following versions:

- "next": "^11.0.1"
- "next-i18next": "^8.5.1"

I can't pinpoint it exactly but I think switching languages stopped working with the upgrade to Next.js 11.

@VeraRibeiro which Next.js version are you using? 

In my case the issue occurs on every major browser on MacOS.

**Comment by VeraRibeiro** [comment]
@codingtub I'm using "next": "10.2.3", I'm also on MacOs
In my case I've updated from i18n v7 to v8, next is still on 10

**Comment by isaachinman** [comment]
https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales

Good luck!

**Comment by VeraRibeiro** [comment]
Thank you! It works
