### ISSUE TITLE
Emit a warning message if syntax error in common.json file

### ISSUE THREAD

**Issue by jasonnet** [isaachinman/next-i18next#1294]
## Is your feature request related to a problem? Please describe.

I just lost a couple wall-clock days for a very stupid error.   My common.json file was using apostrophes instead of quotation marks.  And the list within the common.json file had a trailing comma.   (The file was derived from a .js file being used by a different implementation of i18n support.)   Each of these problems made the file illegal json and caused the file to be ignored.   But the only feedback was the t() function returning only the default translation rather than the en, de, fr... translation.   I ended up taking the working next-i18next example and my broken example and gradually swapping parts to see if behavior would change.  As time went on, the source code of the two project became increasingly similar, but they still behaved differently.   Then I swapped the common.json files and noticed that the problem went away.  After it took me only a few minutes to determine the real problem that I'm documenting here.

## Describe the solution you'd like
I'd like a warning message if a ./public/locale/* file is found by the code, but ignored due to invalid JSON.

## Describe alternatives you've considered
I think what I've just suggested is probably the easiest solution and should be sufficient.  The more detailed the message the better, but extra detail should be considered extra credit.

## Additional context

Thanks.

**Comment by isaachinman** [comment]
Sure, if the functionality is simple enough, we could merge a PR to achieve this.

**Comment by adrai** [comment]
A warning should already be shown in the console if setting debug to true

**Comment by isaachinman** [comment]
Thanks @adrai!
