### ISSUE TITLE
Migration guide implies compatibility with getInitialProps

### ISSUE THREAD

**Issue by MonstraG** [isaachinman/next-i18next#1295]
Point 5 of [migration guide](https://github.com/isaachinman/next-i18next/blob/master/docs/v8-migration.md#step-by-step-migration-guide):

> Add to `getServerSideProps `or `getInitialProps` in the return as props `...(await serverSideTranslations(locale, [<YOUR_NAMESPACES>]))`.

This implies that it will work on `getInitialProps`, but it doesn't.

It probably should be 

> `getServerSideProps` or `getStaticProps`, 

as per https://github.com/isaachinman/next-i18next#serversidetranslations

**Comment by natterstefan** [comment]
Hi @MonstraG,

yes, that's a typo that cost me hours of debugging as well. After reading through lots of issues it was clear to me that I cannot upgrade to 8.x because of that.

> (...) next-i18next does not support getInitialProps and doesn't have control over NextJs internals, so issue should actually be placed on the main NextJs repo. ([src](https://github.com/isaachinman/next-i18next/issues/1096#issuecomment-805082941))

> (...) Not sure what your question is exactly, but you should not be using getInitialProps. (...) ([src](https://github.com/isaachinman/next-i18next/issues/1042#issuecomment-792807274))

We can't use it in all our apps anymore, mainly because of they dropped the support for `getInitialProps` now.

> (...) Using `serverSideTranslations` is mandatory for _all pages_. (...) ([src](https://github.com/isaachinman/next-i18next/issues/1118#issuecomment-813338470))

**Comment by isaachinman** [comment]
Great catch, and sorry about that. @MonstraG @natterstefan Would either of you be willing to open a quick PR?

**Comment by natterstefan** [comment]
> Great catch, and sorry about that. @MonstraG @natterstefan Would either of you be willing to open a quick PR?

Sure, I'll when I'm back at work or later today. 👍🏻

**Comment by DanilaNagornyi** [comment]
Guys, I can't screw your package next-i18next! Me project is large and it doesn't work out of the file _app.js  getInitialProps, there are a lot of logs written there. Is it possible to get around this somehow? can screw the package react-i18next? or is it a crutch? or do you still need to rewrite the project without getInitialProps?

**Comment by MonstraG** [comment]
> Guys, I can't screw your package next-i18next! Me project is large and it doesn't work out of the file _app.js getInitialProps, there are a lot of logs written there. Is it possible to get around this somehow? can screw the package react-i18next? or is it a crutch? or do you still need to rewrite the project without getInitialProps?

You have 2 options:
1. rewrite the whole application without getInitialProps
2. downgrade to v7.0.1 of next-i18next

**Comment by DanilaNagornyi** [comment]
> > Guys, I can't screw your package next-i18next! Me project is large and it doesn't work out of the file _app.js getInitialProps, there are a lot of logs written there. Is it possible to get around this somehow? can screw the package react-i18next? or is it a crutch? or do you still need to rewrite the project without getInitialProps?
> 
> You have 2 options:
> 
>     1. rewrite the whole application without getInitialProps
> 
>     2. downgrade to v7.0.1 of next-i18next (this is a valid approach, we have an application in production that stays on 7 for, it seems, well, ever)

Thank you!
