### ISSUE TITLE
Router.query returns type number

### ISSUE THREAD

**Issue by ffan0811** [isaachinman/next-i18next#1296]
## Describe the bug
I tried to redirect url from `...?testNumber=4` to `...?testNumber=8` by using the method, `push`. To debug the URL, I did  `console.log('router.query', Router, Router.query)`(check my `i18n.ts` below to see where i import the `Router`) and it shows me two different results which is
![image](https://user-images.githubusercontent.com/37147911/124445227-54207180-ddba-11eb-9a42-0c6558bd2633.png)
As you can see, `console.log(Router)` shows a type of `testNumber` is string but `console.log(Router.query)` shows a type of `testNumber` is number. At the end, the type of `Router.query` also turns to string but my useEffect runs twice because of the testNumber type.

Here is my i18n.ts
```
// i18n.ts
import NextI18Next from 'next-i18next';

import path from 'path';

const NextI18NextInstance = new NextI18Next({
    defaultLanguage: 'en',
    defaultNS: 'common',
    otherLanguages: ['ko'],
    localeSubpaths: {
        en: 'en',
        ko: 'ko',
    },
    localePath: path.resolve('./public/static/locales'),
    strictMode: false,
});

// The Router i used for this case
export const { i18n, appWithTranslation, withTranslation, useTranslation, Link, Router, Trans } =
    NextI18NextInstance;
export default NextI18NextInstance;
```

## Occurs in next-i18next version
^6.0.2

## Expected behaviour
The type of `testNumber` should be string when I do `console.log(Router, Router.query)`.
I thought parameters from an URL always strings but I guess not?

## OS (please complete the following information)
 - Device: MacBook Pro (16-inch, 2019), Mac OS Big Sur 11.2.3 (20D91)
 - Browser: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by isaachinman** [comment]
Please first upgrade to the latest version of `next-i18next`. Good luck!
