### ISSUE TITLE
Get all translation key

### ISSUE THREAD

**Issue by kai0310** [isaachinman/next-i18next#1303]
## Is your feature request related to a problem? Please describe.

How do most users add the translation key to the json file when translating?
Manually...? 😧

## Describe the solution you'd like
I'm trying to get all the translation keys used on all the pages.
Also, is it possible to get the untranslated translation keys automatically?

## Describe alternatives you've considered
None

## Additional context
None

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!
