### ISSUE TITLE
How could it be possible to translate Layout using next-i18next?

### ISSUE THREAD

**Issue by reza-sed** [isaachinman/next-i18next#1308]
Hi , I have structured my project with layout component which is wrapper around <Component /> in _app.js. How can I use this library to translate the data in Layout component ?

```javascript
function MyApp({ Component, pageProps }) {
  const { pathname, locale } = useRouter();

  return (
    <Layout locale={locale} path={pathname}>
      <Component {...pageProps} />
    </Layout>
  );
}

export default appWithTranslation(MyApp);
```

**Comment by isaachinman** [comment]
This has been discussed in issues on this repo numerous times. You should be able to use the `t` function within `Layout` without any issue. Good luck!

**Comment by m-belica** [comment]
Hi, I have also encountered similar issue and could not find a solution for it anywhere. I use common namespace in my Layout component and everything works fine, but only if a page loads that namespace. 
Is there any possibility to load a specific namespace during the initialization by default?

**Comment by m-belica** [comment]
Yep, my common module is 'common.json' and I see that it is by default set to 'common', but I added it explicitly (just to be sure):
```
// next-i18next.config.js
module.exports = {
    i18n: {
        locales: ['en', 'sk', 'cs', 'hu', 'de'],
        defaultNS: 'common',
        defaultLocale: 'en',
        ns: ['common', 'home'],
    },
    reloadOnPrerender: true,
};
```

But those translations are not loaded by default. It seems like the i18n is not even initialized at all until a page calls `serverSideTranslations` method.

**Comment by abduraufsherkulov** [comment]
@belicam Did you solve this issue? I am having the same issue. I am setting defaultNS to desired namespace ('yup' in my case). However, if I don't feed it through `getStaticProps`, all I get is missingKey error on console. Is there any way of feeding certain namespace (it is global, I don't want to feed it in every single page)? @isaachinman Do you have any suggestions?

**Comment by belicam** [comment]
> @belicam Did you solve this issue? I am having the same issue. I am setting defaultNS to desired namespace ('yup' in my case). However, if I don't feed it through `getStaticProps` in a page, all I get is missingKey error on console. Is there any way of feeding certain namespace globally (in _app, layout, header that is not dependent on any page)? @isaachinman Do you have any suggestions?

@abduraufsherkulov  Sadly, nope. For now I'm just forcing it to load in every page. I did not find any other solution.

**Comment by pikooli** [comment]
It seem like "getStaticProps" or "getServerSideProps" are always needed in page to load the translation.
"defaultNS" only allow you to no specify some NS in the "serverSideTranslations".

I wanted to try to wrap my page in a HOC, so i don't have to type each type the "getServerSideProps", but it don't work.
It seem that importing "serverSideTranslations" into a component that not a page crash, as it don't have access to fs.

Haven't find any workaround.

**Comment by nail361** [comment]
```js
// next-i18next.config.js
const HttpBackend = require("i18next-http-backend/cjs");
const ChainedBackend = require("i18next-chained-backend").default;
const LocalStorageBackend = require("i18next-localstorage-backend").default;

const isBrowser = typeof window !== "undefined";

module.exports = {
  debug: process.env.NODE_ENV === "development",
  backend: {
    backendOptions: [{ expirationTime: 60 * 60 * 1000 }, {}], // 1 hour
    backends: isBrowser ? [LocalStorageBackend, HttpBackend] : [],
  },
  i18n: {
    defaultLocale: "ru",
    locales: ["en", "ru"],
  },
  defaultNS: [],
  react: {
    wait: true,
  },
  use: isBrowser ? [ChainedBackend] : [],
};
```

```js
//index.js - some page
import type { NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { GetStaticProps } from "next";

const Welcome: NextPage = () => {
  const { t } = useTranslation("welcome-page");

  return (
    <div>
        <p>{t("text")}</p>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const locale = context.locale!;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["welcome-page"])),
    },
    revalidate: 10,
  };
};

export default Welcome;
```

```js
//common header in layout
import { FunctionComponent, useEffect } from "react";
import { useTranslation } from "next-i18next";

const Header: FunctionComponent = () => {
  const { t, i18n } = useTranslation(["header"], {
    bindI18n: "languageChanged loaded",
  });

  useEffect(() => {
    i18n.reloadResources(i18n.resolvedLanguage, ["header"]);
  }, [i18n]);

  return (
      <div>
        <p suppressHydrationWarning>{t("title")}</p>
    </div>
  );
};

export default Header;
```

**Comment by nail361** [comment]
This work for me, but throw error if navigate to 404 custom page.

```js
// next-i18next.config.js
const HttpBackend = require("i18next-http-backend/cjs");
const ChainedBackend = require("i18next-chained-backend").default;
const LocalStorageBackend = require("i18next-localstorage-backend").default;

const isBrowser = typeof window !== "undefined";

module.exports = {
  debug: process.env.NODE_ENV === "development",
  backend: {
    backendOptions: [{ expirationTime: 60 * 60 * 1000 }, {}], // 1 hour
    backends: isBrowser ? [LocalStorageBackend, HttpBackend] : [],
  },
  i18n: {
    defaultLocale: "ru",
    locales: ["en", "ru"],
  },
  defaultNS: [],
  react: {
    wait: true,
  },
  use: isBrowser ? [ChainedBackend] : [],
};
```

```js
//index.js - some page
import type { NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { GetStaticProps } from "next";

const Welcome: NextPage = () => {
  const { t } = useTranslation("welcome-page");

  return (
    <div>
        <p>{t("text")}</p>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const locale = context.locale!;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["welcome-page"])),
    },
    revalidate: 10,
  };
};

export default Welcome;
```

```js
//common header in layout
import { FunctionComponent, useEffect } from "react";
import { useTranslation } from "next-i18next";

const Header: FunctionComponent = () => {
  const { t, i18n } = useTranslation(["header"], {
    bindI18n: "languageChanged loaded",
  });

  useEffect(() => {
    i18n.reloadResources(i18n.resolvedLanguage, ["header"]);
  }, [i18n]);

  return (
      <div>
        <p suppressHydrationWarning>{t("title")}</p>
    </div>
  );
};

export default Header;
```

**Comment by nail361** [comment]
```js
// next-i18next.config.js
const HttpBackend = require("i18next-http-backend/cjs");
const ChainedBackend = require("i18next-chained-backend").default;
const LocalStorageBackend = require("i18next-localstorage-backend").default;

const isBrowser = typeof window !== "undefined";

module.exports = {
  debug: process.env.NODE_ENV === "development",
  backend: {
    backendOptions: [{ expirationTime: 60 * 60 * 1000 }, {}], // 1 hour
    backends: isBrowser ? [LocalStorageBackend, HttpBackend] : [],
  },
  i18n: {
    defaultLocale: "ru",
    locales: ["en", "ru"],
  },
  defaultNS: [],
  react: {
    wait: true,
    useSuspense: true
  },
  use: isBrowser ? [ChainedBackend] : [],
};
```

```js
//index.js - some page
import type { NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import { GetStaticProps } from "next";

const Welcome: NextPage = () => {
  const { t } = useTranslation("welcome-page");

  return (
    <div>
        <p>{t("text")}</p>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const locale = context.locale!;

  return {
    props: {
      ...(await serverSideTranslations(locale, ["welcome-page"])),
    },
    revalidate: 10,
  };
};

export default Welcome;
```

```js
//common header in layout
import { FunctionComponent, useEffect } from "react";
import { useTranslation } from "next-i18next";

const Header: FunctionComponent = () => {
  const { t, i18n } = useTranslation(["header"], {
    bindI18n: "languageChanged loaded",
  });

  useEffect(() => {
    i18n.reloadResources(i18n.resolvedLanguage, ["header"]);
  }, [i18n]);

  return (
      <div>
        <p suppressHydrationWarning>{t("title")}</p>
    </div>
  );
};

export default Header;
```

**Comment by HendryVarianto14** [comment]
Any Solutions yet?

I already Wrapped appWithTranslation in my _app.js and tried to use it without serverSideTranslation, and its still not working on the Layout
I guess you really need serverSideTranslation

**Comment by tleperou** [comment]
+1 in here.

Providing the namespace through `getServerSideProps` is the most effective way I ended up with too.

**Comment by almaron** [comment]
But even if you add the entry, you still have to pretty much duplicate `getStaticProps` or `getServersideProps` on every single even if there's nothing really there to i18nize other than the layout.

**Comment by codeaid** [comment]
I had a similar issue. `App` (which also includes my layout) is wrapped in the `appWithTranslation` HOC yet when I tried to use translations using the `useTranslation` hook only strings coming from the `common` module got properly translated. Everything else generated warnings in the console saying the key is missing.

The solution that worked for me was to pass `{ nsMode: 'fallback' }` as the second parameter to the hook. No idea what the default fallback mode does but apparently it doesn't look up keys in other namespaces if they're missing.

**Comment by moskalakamil** [comment]
I think that the best way is to add normally `<Layout />` into _app file:
```typescript
<Layout>
            <Component {...pageProps} />
</Layout>
```
and in every file in `page` folder you should add 
```typescript
export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});
```

**Comment by moskalakamil** [comment]
> @moskalakamil It worked, thanks. Just curious. Why does it work? It's a bit inconvenient having to pass `common` in every `page`

@neodmy it work, because u giving access for common.json file in every page. Layout component is used too in every page so this component have access to transaled languages. You are right that it's inconvenient but i think its the best option - you need to make it only once, and anyway you ofter use `serverSideTranslation` in pages file in `getStaticProps` or `getServerSideProps`, so you need to add only `'common'` text.

**Comment by Ostefanini** [comment]
@moskalakamil thank you for finding the workaround. In addition, If you encounter an error such as ` locale argument was not passed into serverSideTranslations` consider importing i18n object from `next-i18next-config.js` into the module exported from `next.config.js` and restart your development server.

This configuration is the same as the simple example https://github.com/i18next/next-i18next/tree/master/examples/simple
