### ISSUE TITLE
NextJS build fails with next-i18next when target is set to serverless

### ISSUE THREAD

**Issue by phbernard** [isaachinman/next-i18next#1311]
## Describe the bug
When a NextJS app is built with `npm run build` while `target` is set to `serverless` in `next.config.js`, the build fails with:

    Unhandled error during request: Error: Cannot find module '/path/to/project/next-i18next.config.js'

## Occurs in next-i18next version
next-i18next Npm package version 8.5.3

### With a sample project

Positive case:

    git clone https://github.com/phbernard/next-i18next-issue.git
    npm install
    npm run build # Works, as expected

Now, edit `next.config.js` and uncomment the line `//target: 'serverless',`. Then, build again:

    npm run build # This time, the build fails

### From scratch

To re-create the demo project above and check for yourself:
- Create a NextJS app with `yarn create next-app`
- Perform a basic next-i18next setup, following the [project README](https://github.com/isaachinman/next-i18next):
  - Install next-i18next
  - Create some `common.json` (make them empty)
  - Create and populate `next-i18next.config.js`
  - Modify `next.config.js`
  - Modify `pages/_app.js`
  - Add `getStaticProps` to `pages/index.js`
 
Then proceed as above:
- Run `npm run build`: it works
- Set `target: 'serverless'` in `next.config.js`, run  `npm run build` again: it fails

## Expected behaviour
Build should succeed with `target` set to `serverless`. Or there should be a documented workaround.

## Additional context
Note that `serverless` is a requirement for [Netlify](https://github.com/netlify/next-on-netlify), which is a mainstream way to deploy Next. Therefore, this issue might be often encountered.

This issue has already been described in https://github.com/isaachinman/next-i18next/issues/911 . I opened a new one because I felt the title was clearer, plus it comes with a demo repos to reproduce it.

**Comment by isaachinman** [comment]
Can you provide official documentation on `target: 'serverless'`? I'm not sure if this config option is still officially supported, as I can't find anything relevant on it.

**Comment by isaachinman** [comment]
Please see: https://github.com/vercel/next.js/issues/20487#issuecomment-753884085

**Comment by phbernard** [comment]
Thank you for your quick answer!

Here I'm focusing on deployment on Netlify, which is my target environment as you can guess.

Unfortunately, removing `target: 'serverless'` does not work. In Netlify build logs, it is stated that `target` is automatically set to this value:

    ────────────────────────────────────────────────────────────────
    3:34:41 PM:   1. onPreBuild command from @netlify/plugin-nextjs             
    3:34:41 PM: ────────────────────────────────────────────────────────────────
    3:34:41 PM: ​
    3:34:41 PM: Using Next.js 11.0.1
    3:34:41 PM: info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
    3:34:41 PM: The "target" config property must be one of "serverless", "experimental-serverless-trace". Building with "serverless" target.

So I tried with `target: 'experimental-serverless-trace'`, the other accepted value. It works: there is no longer an issue with `next-i18next.config.js` and the application can be successfully deployed on Netlify.

I'm not very satisfied with this trial-and-error process, but clearly this has nothing to do with next-i18next anymore. Thanks again!

**Comment by madshargreave** [comment]
Encountering the same issue

**Comment by phbernard** [comment]
@madshargreave Does experimental-serverless-trace help?

**Comment by tgmarinho** [comment]
I created this issue: https://github.com/netlify/netlify-plugin-nextjs/issues/595
same error here.

**Comment by miinnnn2** [comment]
Anyone solve this problem?

**Comment by miinnnn2** [comment]
> I'm having the same issue using `serverless` framework with next + next-i18next. Seems like change the `target` to `experimental-serverless-trace` doesn't fix on deploy using `serverless` framework. Can anyone help me to understand the root cause ?

Would you solve this problem?

**Comment by lucascampelo** [comment]
> > I'm having the same issue using `serverless` framework with next + next-i18next. Seems like change the `target` to `experimental-serverless-trace` doesn't fix on deploy using `serverless` framework. Can anyone help me to understand the root cause ?
> 
> Would you solve this problem?

Not yet. Currently I'm deploying on Vercel's servers stead of configure my own deploy with `serverless` framework.

**Comment by guiferreira-vx** [comment]
Has anyone found a solution to the problem?
