### ISSUE TITLE
version 6.0.2 unable to see output of target language in testing environment

### ISSUE THREAD

**Issue by stefansalv** [isaachinman/next-i18next#1312]
Hello, 
I am trying to test a project that uses next-i18next 6.0.2 however no matter what I try I am not able to render my components text correctly to jsdom. 
For example when I use t('loginPage:forgotPassword') in one of my components, in testing environment it renders "forgotPassword" key instead of corresponding text. 

For testing I am wrapping the component with i18nextProvider and I am passing the i18n instance imported from "i18next" such as below.
```
<I18nextProvider i18n={i18n}>
          <ExampleComponent />
</I18nextProvider>
```

I tried to pass my i18config file as prop to provider but it throws error (react is not defined).

Info:
In my components I use withTranslation
I get " t " as prop.
In my _app.js I use appWithTranslation

the examples that present in https://react.i18next.com/misc/testing did not work. 
Can anyone provide any example configuration for testing environment for v6?

**Comment by isaachinman** [comment]
Previous versions are not actively supported. If anyone does wish to fork and support v6, please feel free to update us here.
