### ISSUE TITLE
Can't initilize with resources option

### ISSUE THREAD

**Issue by mastrayer** [isaachinman/next-i18next#1318]
serverSideTranslations function's resources option is ignored.
It returned only common namespace like below.
```javascript
_nextI18Next: {
  initialI18nStore: { 
    en: {
      common: { ... },
      // where is "test" namespace?
    }
  },
  ...
}
```

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
```javascript
export const getServerSideProps = async ({ locale }) => {
  return {
    props: {
      await serverSideTranslations(locale, ["common"], {
        i18n: {
          defaultLocale: "en",
          locales: ["en"],
        },
        resources: {
          en: {
            test: {
              testKey: "123"
            }
          }
        }
      })
    },
  };
};
```

## Expected behaviour
```javascript
// return of serverSideTranslations
_nextI18Next: {
  initialI18nStore: { 
    en: {
      common: { ... },
      test: {
        testKey: "123"
      }
    }
  },
  ...
}
```

**Comment by isaachinman** [comment]
Relevant line is [here](https://github.com/isaachinman/next-i18next/blob/master/src/serverSideTranslations.ts#L54). Have you been able to debug?

**Comment by mastrayer** [comment]
@isaachinman 
https://github.com/isaachinman/next-i18next/blob/0162dbd825be1ea6b68f444eb6be735b09a50de2/src/serverSideTranslations.ts#L47

I think this code is bug.
because i18next.config.js will use instead of merge with configOverride arg.

**Comment by mastrayer** [comment]
Sorry. this bug fixed v8.5.3
I will upgrade my package version.

**Comment by mastrayer** [comment]
@isaachinman 
still not working with resources.
passing resources arg, return only arg namespace,
and don't pass resources arg, return other translation files.

**Comment by isaachinman** [comment]
@mastrayer The `backend` option is one which we [deep merge](https://github.com/isaachinman/next-i18next/blob/master/src/config/createConfig.ts#L154) between the user provided config, and the default config.

You can see in the [i18next documentation](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources) that a backend option will override the `resources` option.

So given `next-i18next`'s current behaviour, you will need to override `backend`, or provide a custom `backend`.

**Comment by adithep** [comment]
@isaachinman How do you override backend?

**Comment by isaachinman** [comment]
@adithep By passing the [relevant config options](https://www.i18next.com/overview/plugins-and-utils#backends) in `next-i18next.config.js`.
