### ISSUE TITLE
Are there any known issues with catch all routes?

### ISSUE THREAD

**Issue by dohomi** [isaachinman/next-i18next#1320]
## Describe the bug
I have a catch all route in the root of my pages folder similar like this: 
```
[...slug].tsx
login.tsx
profile.tsx
```
login.tsx and profile.tsx are loading the translations without any issue. But all catch-all routes from `[...slug].tsx` are not loading any translations.

## Occurs in next-i18next version
v8.5.5 and Next 11.0.1

## Expected behaviour
Translations in catch all routes should load

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
all

Does this occur to anyone? I tried to reproduce put currently I am backed up with lot of tasks that I could not manage to isolate where this issue belongs

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by dohomi** [comment]
@isaachinman I realised it only happened on Vercel deployments: https://github.com/isaachinman/next-i18next/issues/750

It might be cool to mention that repo you wired up for Vercel users, that would be convenient! Everything works as expected after modifying the config file
