### ISSUE TITLE
Cant seem to get TypeScript's strong typing to work for t function

### ISSUE THREAD

**Issue by opolo** [isaachinman/next-i18next#1321]
Hi! 

I might be the one goofing around, since I am new to Typescript, but have spent a few hours now + have not been able to solve my issue, so in case I am not the one goofing (or in case other has this problem and also cannot find the reason), I will create a ticket that can help me and others as well. 

## Describe the bug
I am running typescript in my NextJS 10 solution. Using the t function returned by useTranslation, I cannot seem to get a strong mapping between the JSON files and the strings I provide as param to the t-function. E.g. 
`
const { t } = useTranslation(LOCALE_NAMESPACES.anExistingNamespace);
t('random-string')
`, 
raises no compile-time errors for me. I have set up i18next according to the guide here: https://react.i18next.com/latest/typescript.

## Occurs in next-i18next version
8.5.5

## Steps to reproduce
See describe the bug. 

## Expected behaviour
Would be disallowed from parsing in a non-existing ID to the translation function.

## OS (please complete the following information)
 - Device: Windows 10, Lenovo.
 - Browser: Chrome

## Additional context
I suspect I might be just a single mistake away from getting it to work. I can see in some former issues a TFunction is mentioned, but searching on it at Google and at i18n-react yielded no results for me. I can see its exported from next-i18next, so I tried doing:
`
const { t } = useTranslation<TFunction>(LOCALE_NAMESPACES.aNamespace);
`
But while that would compile, it did not stop the t-function from accepting non-existing IDs.

Hope I have given enough info! :)

**Comment by isaachinman** [comment]
I don't think per-key typing is something i18next ever claimed to have. Please open this on the i18next repo if you think it's a reasonable request. Good luck!

**Comment by opolo** [comment]
Hey! 

Thanks for the quick response. I managed to get the string-input to t() to be strongly typed, so it complains compile time, if the provided string is not a valid ID/key in our localized files. 

This was the code that did the trick, in case someone else has the same problem and finds this:
`
import 'react-i18next';
// import all namespaces (for the default language, only)
import footer from 'public/locales/en/footer.json';
import header from 'public/locales/en/header.json';
import common from 'public/locales/en/common.json';

declare module 'react-i18next' {
  // and extend them!
  interface CustomTypeOptions {
    // custom namespace type if you changed it
    defaultNS: 'common';
    // custom resources type
    resources: {
      footer: typeof footer;
      header: typeof header;
      common: typeof common;
    };
  }
}
`

I do not know if it is necessary to manually import all the locale files, but found no way around it. 

NB. Remember to have your tsconfig file load the above d.ts file.
