### ISSUE TITLE
global i18next instance only returns default language translations outside page-components 

### ISSUE THREAD

**Issue by opolo** [isaachinman/next-i18next#1327]
Hi!

## Describe the bug
When building our site, we followed the following recommendation from NextJS: https://nextjs.org/docs/basic-features/layouts.
They suggest having a layout file outside the <Component /> within _app.js that contains the <Header /> and <Footer />. This way, those components keep their state and does not rerender, when moving between pages. 
Since the <Layout> component is located outside any page, there is no way to use getStaticProps in order to use serverSideTranslations. To accomodate this, we use   
`import { i18n } from 'next-i18next';`
to get the i18n instance and its translate function. We then want to use this translation function to get our localized texts. This works partially. It does provide translations, but they always belong to the default locale. In the same component, we can use NextJS's:
`const { locale } = useRouter();`
and see our locale is e.g. "da", while it still returns the "en" translations.

## Occurs in next-i18next version
11.0.1

## Steps to reproduce

_app.js:

```
const MainApp = () => {
   return (
      <Layout>
         <Component {...pageProps} err={err} />
      </Layout>
   )
}
export default appWithTranslation(MainApp);
```

Layout.js:
As described above (use the translation function in here, and it returns the translations from the default locale, despite the locale returned by useRouter).

next-i18next.config.js:
```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'da'],
  },
};

```

## Expected behaviour
i18n returns translations corresponding to the same locale currently returned by NextJS' useRouter.

## OS (please complete the following information)
 - Windows 10
 - Chrome (newest public release)

## Additional context
Same issue seems to be the case, when I use 
`const { i18n } = useTranslation();`
or `withTranslation `HOC to get the i18n instance. I am unsure, whether I was allowed to use those outside a page though (vs. using the global i18n and then check, when the app had mounted and it was not null), but... Anyway I tried to see what would happen, so hope the extra info helps!

**Comment by isaachinman** [comment]
You can use the regular i18next hooks inside `Layout` without any issue. You don't need to interact with the global i18n instance at all. Good luck!

**Comment by kicaal** [comment]
Any examples please??
