### ISSUE TITLE
react-i18next:: You will need to pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by remcotak** [isaachinman/next-i18next#1328]
## Describe the bug
After following the docs, each time I start the build process and navigate to a page which uses the useTranslation hook I get the following notification in my server log `react-i18next:: You will need to pass in an i18next instance by using initReactI18next`

## Occurs in next-i18next version
next-i18next 8.5.5
next 10.0.0
webpack 4

## Steps to reproduce
Follow the docs and build the app.

I wrapped my App in `_app.js` in `appWithTranslation`.
I added the `serverSideTranslations` in the `getStaticProps` function on the page, following the docs
My next-i18Next.config.js is as following:
```module.exports = {
  i18n: {
    defaultLocale: 'en',
    // Uncomment below to activate other languages
    // locales: ['en', 'fr', 'nl'], 
    locales: ['en'],
    react: { useSuspense: false }
  },
};```

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!

**Comment by remcotak** [comment]
@dmi3y thanks for your reply, I had already tried that solution with no success. I used it like this, maybe you can see if there is something wrong:

```
import { withTranslation } from 'next-i18next';

const LoginPage = ({ t }) => {
  return <Seo title={t('pageTitle')} />
};

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'login'])),
  },
});

export default withTranslation(['login', 'common'])(LoginPage);
```

**Comment by dmi3y** [comment]
@remcotak Assuming you have set up your `_app.tsx` with `appWithTranslation`, I do not see `import { serverSideTranslations } from 'next-i18next/serverSideTranslations';` in the provided snippet. The rest looks good to me, except I'm using hook.

**Comment by isaachinman** [comment]
Use of `withTranslation` is not required whatsoever. The `appWithTranslation` HOC wraps your entire app in a provider.
