### ISSUE TITLE
Different namespace for each page

### ISSUE THREAD

**Issue by jashwant** [isaachinman/next-i18next#1329]
I have a page `my-page/sub-page/example`.

I want to load a `common.json` file + another file which has translations of this page only. 
 
 My getStaticProps looks like this,

```javascript
export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'my-page/sub-page/example'])),
    },
  };
};
```
 
 And I am using it like this.
```javascript
const { t } = useTranslation('my-page/sub-page/example');
```

This throws error 
[Error: ReactDOMServer does not yet support Suspense](https://github.com/isaachinman/next-i18next/issues/1255)

If I remove `useSuspense`, 

```javascript
const { t } = useTranslation('page/sub-page/sub-page-2/example', { useSuspense: false });
```

Error is fixed, but it does not translate and shows translate key as fallback.

**How do I keep a different translation file for each page ?**

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!
