### ISSUE TITLE
appWithTranslation issue

### ISSUE THREAD

**Issue by LB22** [isaachinman/next-i18next#1331]
I have an issue with my e-commerce site - When I switch between languages my cart get's reset. This is my code.

```javascript
import { ThemeProvider } from "next-themes";
import { CartProvider } from "../components/cart/CartContext";
import { appWithTranslation } from "next-i18next";

function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider defaultTheme="system">
      <CartProvider>
        <Component {...pageProps} />
      </CartProvider>
    </ThemeProvider>
  );
}

export default appWithTranslation(MyApp);
```

Obviously, the cart needs to have the outer scope and not the next-i18next. How can I use a next-i18next provider component (is there one?) instead of this HOC "appWithTranslation"? The docs only provide example with HOC.

**Comment by isaachinman** [comment]
Not sure what you're asking here. Please post on StackOverflow for help. Good luck!

**Comment by LB22** [comment]
@Isaachinman Thanks for your answer. I'm asking if there is a way to NOT use the HOC "appWithTranslation" and instead do something like this?

```javascript
import { ThemeProvider } from "next-themes";
import { CartProvider } from "../components/cart/CartContext";
import { i18nProvider} from "next-i18next";

export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider defaultTheme="system">
      <CartProvider>
        <i18nProvider>
          <Component {...pageProps} />
        </i18nProvider>
      </CartProvider>
    </ThemeProvider>
  );
}

```

**Comment by isaachinman** [comment]
No, but there are several different ways you can achieve the nesting pattern you are after, simply by reorganising your components.

**Comment by LB22** [comment]
@Isaachinman Okay I have tried fixing it for a while now. Do you mind giving a hint if you know the answer? I can do a pull request and update the docs if you help me here

**Comment by isaachinman** [comment]
It has nothing to do with docs – this is your own code.

```tsx
import { ThemeProvider } from "next-themes";
import { CartProvider } from "../components/cart/CartContext";
import { appWithTranslation } from "next-i18next";

const MyApp = ({ Component, pageProps }) => (
  <ThemeProvider defaultTheme="system">
      <Component {...pageProps} />
  </ThemeProvider>
);

const AppWithTranslation = appWithTranslation(MyApp)
const AppWithCart = () => (
  <CartProvider>
    <AppWithTranslation />
  </CartProvider>
)

export default AppWithCart
```

Next time please post on StackOverflow instead of opening issue(s).

**Comment by LB22** [comment]
Thank you for answering

**Comment by LB22** [comment]
Doing this gives me an error: 

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`
