### ISSUE TITLE
How to use it on Client Side Rendering(dynamic import) page

### ISSUE THREAD

**Issue by fadhilx** [isaachinman/next-i18next#1333]
current solution is using `serverSideTranslations` on `getStaticProps` or `getServerProps` but my code look like this

```tsx
import dynamic from "next/dynamic";
import { withTranslation  } from "next-i18next";
import { serverSideTranslations, } from "next-i18next/serverSideTranslations";
const CartCheckout = dynamic(
  () => import("./../components/templates/CartCheckout/CartCheckout"),
  {
    ssr: false,
  }
);
export default function CartPage() {
  return <CartCheckout></CartCheckout>;
}

```

how to implement `serverSideTranslations` if i didnt specify the getProps function

**Comment by isaachinman** [comment]
You need to either use `getStaticProps` or `getServerSideProps` – that's how `next-i18next` works. Good luck!

**Comment by fadhilx** [comment]
@isaachinman Understandable, Have a Nice Day
