### ISSUE TITLE
How to display loader when the translations are being loaded

### ISSUE THREAD

**Issue by shivika24** [isaachinman/next-i18next#1345]
Initially when i use next-i18next on my nextjs app, the translations take some time to load or when i refresh the same page, initially i see "loginMenu.title" for few seconds then after that i see "Home" i.e this is the value of translation  provided in locales. How can we directly see the title on the screen and not see "loginMenu.title" or display a loader instead.

**Comment by isaachinman** [comment]
If you are seeing translation keys instead of values, you have probably configured something incorrectly. Please post on StackOverflow for help. Good luck!
