### ISSUE TITLE
Types missmatching with custom Application

### ISSUE THREAD

**Issue by SalahAdDin** [isaachinman/next-i18next#1348]
## Describe the bug
We made a custom `App` for our website as follows:
```typescript
const clientSideEmotionCache = createEmotionCache();

export function reportWebVitals(metric: NextWebVitalsMetric): void {
  if (process.env.NODE_ENV === "development") console.log(metric);
}

interface Props extends AppProps {
  // title: string;
  navLinks: INavLink[];
  emotionCache?: EmotionCache;
}

const FolioApp = ({
  Component,
  pageProps,
  navLinks,
  emotionCache = clientSideEmotionCache,
}: Props) => {
  return (
    <CacheProvider value={emotionCache}>
      <Meta />
      <ThemeProvider theme={theme}>
        {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
        <CssBaseline />
        <Nav navLinks={navLinks} />
        <Component {...pageProps} />
        <Footer navLinks={navLinks} />
      </ThemeProvider>
    </CacheProvider>
  );
};

FolioApp.getInitialProps = async (appContext: AppContext) => {
  const appProps = await App.getInitialProps(appContext);

  const navLinks: INavLink[] = [];
  /*await getPageTitlesBySlugSet(
    menuLinks.map(({ label }: IMenuLink) => label)
  );*/

  return { ...appProps, navLinks };
};

export default appWithTranslation(FolioApp);
```

This code gives us a type error at `appWithTranslation`:
```shell
<html>TS2345: Argument of type '{ ({ Component, pageProps, navLinks }: Props): JSX.Element; getInitialProps(appContext: AppContext): Promise&lt;{ navLinks: INavLink[]; pageProps: any; }&gt;; }' is not assignable to parameter of type 'ComponentClass&lt;AppProps, any&gt; | FunctionComponent&lt;AppProps&gt;'.<br/>Type '{ ({ Component, pageProps, navLinks }: Props): JSX.Element; getInitialProps(appContext: AppContext): Promise&lt;{ navLinks: INavLink[]; pageProps: any; }&gt;; }' is not assignable to type 'FunctionComponent&lt;AppProps&gt;'.<br/>Types of parameters '__0' and 'props' are incompatible.<br/>Property 'navLinks' is missing in type 'PropsWithChildren&lt;AppProps&gt;' but required in type 'Props'.
```

## Occurs in next-i18next version
Setup:
```json

    "next": "11.0.1",
    "next-compose-plugins": "^2.2.1",
    "next-i18next": "^8.5.5",
    "next-offline": "^5.0.5",
    "next-seo": "^4.26.0",
    "next-unused": "^0.0.6",

```

## Steps to reproduce

1. Write the code above on the IDE/Text Editor.
2. Look at lint analyser results.

## Expected behaviour
It should not be a type error.

## Screenshots
![image](https://user-images.githubusercontent.com/5034215/128646405-a375b96e-bd2d-4125-b500-2c7a686365b2.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: Chrome 92

**Comment by isaachinman** [comment]
How would you expect `next-i18next` to resolve this issue? This is a matter of user configuration.

**Comment by SalahAdDin** [comment]
> How would you expect `next-i18next` to resolve this issue? This is a matter of user configuration.

why is it a problem with user configuration?

We are extending the default **Next**'s `App` by adding some additional props; are we doing this in a wrong way?

**Comment by isaachinman** [comment]
The problem you have described is common to _all_ HOCs when using TypeScript.

**Comment by SalahAdDin** [comment]
> The problem you have described is common to _all_ HOCs when using TypeScript.

Then, you suggest just to ignore it, right?

I have been searching about that and the common solution is to modify the HOC type definition. The problem comes when we add a required custom variable (we think that since passing `emotionCache?` in props does not give any error.

**Comment by isaachinman** [comment]
In what way would you want to modify the HOC type definition? We already pass along [AppProps](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L21).

**Comment by SalahAdDin** [comment]
> In what way would you want to modify the HOC type definition? We already pass along [AppProps](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L21).

But `AppProps` does not pass `navLinks: INavLink[]`, which is our custom additional variable.

**Comment by isaachinman** [comment]
In what way would you want to modify the HOC type definition?

**Comment by SalahAdDin** [comment]
> In what way would you want to modify the HOC type definition?

Actually, I don't know, I trying to realize what the proper way to solve this problem.

**Comment by isaachinman** [comment]
Open to suggestions. Let me know if you'd like to reopen.

**Comment by despin** [comment]
I think it would be a good idea to change the type definition of `appWithTranslation`'s props from `<AppProps>` to `<T extends AppProps>`.
So, since the OP's custom props are extended from AppProps, there should be no types problem.

**Comment by petarvujovic98** [comment]
I started using this awesome library a few days ago and came across this issue. IMO you should make the WrappedComponent argument's type generic so that people could pass their custom App components something like this 
```typescript
export const appWithTranslation = <Props extends AppProps = AppProps>(
  WrappedComponent: React.ComponentType<Props> | React.ElementType<Props>,
  configOverride: UserConfig | null = null,
) => {
  const AppWithTranslation = (props: Props) => {
...
```

**Comment by isaachinman** [comment]
@petarvujovic98 Sure, a PR would be appreciated!

**Comment by petarvujovic98** [comment]
Sure, I'll give it a go

**Comment by petarvujovic98** [comment]
@isaachinman Why do we need `React.ElementType<AppProps>` type for WrappedComponent?

**Comment by SalahAdDin** [comment]
> I started using this awesome library a few days ago and came across this issue. IMO you should make the WrappedComponent argument's type generic so that people could pass their custom App components something like this
> 
> ```ts
> export const appWithTranslation = <Props extends AppProps = AppProps>(
>   WrappedComponent: React.ComponentType<Props> | React.ElementType<Props>,
>   configOverride: UserConfig | null = null,
> ) => {
>   const AppWithTranslation = (props: Props) => {
> ...
> ```

As far as I remember, I argues a lot about this and the answer I got was i should need to do everything by muself. So, i dropped it.

Good luck man, i hope you are satisfied with this library.

**Comment by petarvujovic98** [comment]
This issue is resolved in the upcoming v9 release. So you will get proper types when using your custom app components when the next version gets released

**Comment by ivoba** [comment]
@petarvujovic98 is there an example for this?

I also get this:

>TS2345: Argument of type '{ i18n: { debug: boolean; ns: string[]; defaultNS: string; locales: string[]; defaultLocale: string; serializeConfig: boolean; localePath: (locale: any, namespace: any) => string; }; }'
is not assignable to parameter of type 'UserConfig'.
Types of property 'i18n' are incompatible. 
Type '{ debug: boolean; ns: string[]; defaultNS: string; locales: string[]; defaultLocale: string; serializeConfig: boolean; localePath: (locale: any, namespace: any) => string; }' is not assignable to type 'NextJsI18NConfig'. 
Object literal may only specify known properties, and 'debug' does not exist in type 'NextJsI18NConfig'

with

`export default appWithTranslation(App, nextI18NextConfig);`

and

```
"next": "13.1.1",
"next-i18next": "^13.0.3",
```

**Comment by petarvujovic98** [comment]
@ivoba Hey! I haven't been using the most recent releases so I am not sure about this issue you are having. Maybe try asking the core contributors as I only played a minor role for this particular issue and haven't participated in the recent changes. Hope you find a solution!

**Comment by ivoba** [comment]
my bad:
i should have added additional configs not in i18n prop but one level up:

```
module.exports = {
  i18n: {
    locales: ['de', 'en'],
    defaultLocale: 'de',
  },
  serializeConfig: false,
  defaultNS: 'global',
  ns: ['global'],
  localePath: (locale, namespace) =>
    `./public/locales/${namespace}.${locale}.json`,
};
```
