### ISSUE TITLE
Use peer dependencies

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#136]
The discussion of peer dependencies in #129 got me thinking - what do you think about moving `react-i18next`, `i18next` (and perhaps other associated `i18next` packages), and `react` to dev dependencies and also including them as peer dependencies (much like the `next-i18next` package does with `i18next` and `react`)?  It would help communicate minimum compatible versions of each package and would help us avoid yarn warnings like this one:

'warning "next-i18next > react-i18next@9.0.9" has incorrect peer dependency "i18next@>= 14.0.1".

In this case, our package.json specifies `i18next@^13.1.3`, but the `next-i18next` `package.json` specifies `react-i18next@^9.0.4` (currently v9.0.9) which has a peer dependency of `i18next@^14.0.1`. I think that we're going to constantly run into these incorrect peer dependency warnings unless we just specify `next-i18next` as a peer dependency (with the lowest compatible version number).  Then users could install our package alongside the other peer dependencies when they want to use `next-i18next`.

We would still have to keep the dev dependencies up to date, but the warnings would not show up for our users and I think it communicates more effectively that these packages are to be installed _with_ our package and we only need to install them _in_ our package if we're doing some sort of development (e.g. our e2e tests).

**Comment by isaachinman** [comment]
Yes, that sounds very sensible to me. Let's do that.

**Comment by capellini** [comment]
Per #139 - also include `core-js` and `@babel/polyfill` as peer dependencies.

**Comment by isaachinman** [comment]
Fixed with 9c23e89. I don't think `core-js` or `@babel/polyfill` belong in peer deps.

**Comment by capellini** [comment]
If `i18next` and `react` are `peerDependencies`, then they shouldn't also be `dependencies`.  They should be moved to `devDependencies`.

Should `react-i18next` also be a peer dependency?

**Comment by capellini** [comment]
If we don't enforce `core-js` as a `peerDependency`, don't we run the risk of having #129 happening again?  My understanding is that, with the way that babel polyfills work, the `core-js` that matters is one that is installed in the root `node_modules` folder of whatever project is _using_ `next-i18next`, not necessarily what we have installed in our `node_modules` folder.

**Comment by kachkaev** [comment]
Possibly related: https://github.com/isaachinman/next-i18next/issues/152

**Comment by isaachinman** [comment]
Removed polyfill with 4bf9d37.

And no, `react-i18next` shouldn't be a peer dep as our users never need to touch it.

**Comment by capellini** [comment]
If `i18next` and `react` are `peerDependencies`, then they shouldn't also be `dependencies`. They should be moved to `devDependencies`.

**Comment by isaachinman** [comment]
@capellini Ah, sorry - missed that. Fixed with f35cc48.

**Comment by capellini** [comment]
No worries.  Thanks!

**Comment by kachkaev** [comment]
I might be wrong, but it seems that moving `i18next` to `devDependencies` means that setup changes from 

```
yarn add next-i18next
```

to

```
yarn add next-i18next i18next
```

This library has `react-i18next` as a direct dependency, but that library does not directly depend on `i18next` (see its [package.json](https://github.com/i18next/react-i18next/blob/master/package.json)).

**Comment by isaachinman** [comment]
@kachkaev That's what a peer dependency is. Please refer to the [README](https://github.com/isaachinman/next-i18next#1-installation) for updated installation instructions.

**Comment by isaachinman** [comment]
@kachkaev From @capellini:

> In this case, our package.json specifies i18next@^13.1.3, but the next-i18next package.json specifies react-i18next@^9.0.4 (currently v9.0.9) which has a peer dependency of i18next@^14.0.1. I think that we're going to constantly run into these incorrect peer dependency warnings

Please discuss if you feel you have another solution.

**Comment by kachkaev** [comment]
> In this case, our package.json specifies i18next@^13.1.3
@capellini do you mean `package.json` in your app? IMO either both `i18next` and `react-i18next` need to belong to it, or none of those. In the first case, both libs will be `peerDependencies` of this lib and app devs will be able to choose their version, in the latter case `next-i18next` will pick the versions for us. I personally prefer the former case, because this reduces the likelihood of `next-i18next` being incompatible with its tight dependencies. See `@zeit/next-css`'s [`package.json`](https://github.com/zeit/next-plugins/blob/master/packages/next-css/package.json
) that does exactly that for what it needs.

Either way, classifying `i18next` and `react-i18next` differently feels suboptimal to me.

**Comment by isaachinman** [comment]
@kachkaev Yes, I think I agree with you. The only true peer deps here are `next` and `react`.

@capellini To answer your question, I want `next-i18next` to be a replace for _both_ `react-i18next` and `i18next`. In general there is quite a lot of confusion and lack of knowledge in the dev community about i18next and it's ecosystem, and this package attempts to hide a lot of that away and allow users to just think about their JSON namespaces and get on with it.

> However, for advanced use cases, I believe that users may still need to use i18next

What cases? If there are situations where users need to install and import `i18next` directly, that probably means we've failed to expose some part of the API.

**Comment by isaachinman** [comment]
Added `i18next` back to deps with 249c597. Sorry for the back and forth on this one. We're going to move forward with the assumption that `next` and `react` are the only peer deps of this package.

**Comment by capellini** [comment]
> What cases? If there are situations where users need to install and import `i18next` directly, that probably means we've failed to expose some part of the API.

Again, perhaps I'm revealing the extent of my ignorance of `i18next`.  The zero config defaults work for me, so maybe I'm trying to solve a problem that doesn't exist.  But does anyone know why `react-i18next` believes that `i18next` should be a `peerDependency`?  It seems to me that indicates that there are cases where one would need to install `i18next` alongside `react-i18next`.  Perhaps the use cases that require them to include it as a `peerDependency` don't apply to our package?

Either way, the defaults work for me, so I have no objections to `react` and `next` being the only `peerDependencies`.  If it becomes a problem at some point in the future, we can always revisit this.

**Comment by isaachinman** [comment]
> But does anyone know why react-i18next believes that i18next should be a peerDependency?

I guess the fact that this question is asked means we're doing a good job here. Take a look at the [example implementation](https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/react/src/i18n.js) from the `react-i18next` repo. It's much more hands-on, and you definitely touch `i18next` directly.

**Comment by capellini** [comment]
Understood.  It makes much more sense now that I see the example implementation.  Thanks.
