### ISSUE TITLE
Run a function before t

### ISSUE THREAD

**Issue by nblthree** [isaachinman/next-i18next#1367]
## Is your feature request related to a problem? Please describe.
I would like to work with the argument of `t` in `const { t } = useTranslation('common')`

## Describe the solution you'd like
I would like to do something like this

```
import { appWithTranslation } from 'next-i18next'

function MyApp({ Component, pageProps }) {
  return (
      <Component {...pageProps} />
  )
}

export default appWithTranslation(MyApp, (t-argument) => {
\\ do some stuff
return result-to-t
})
```

**Comment by isaachinman** [comment]
You can do:

```tsx
import { i18n } from 'next-i18next'

i18n.t()
```

**Comment by nblthree** [comment]
@isaachinman  you mean I can do this `i18n.t((t-arg) => \\do something with t-arg then return result)`

**Comment by isaachinman** [comment]
Not sure I understand your "return result" requirement. Please post on StackOverflow for help. Good luck!

**Comment by nblthree** [comment]
Here is a simple example of what I want

`<div>{t('some text')}</div>`

here is a function `const fun = (arg) => arg.replace(' ', '-')`

so instead of doing `<div>{t(fun('some text'))}</div>` each time I call `t`. I want to pass `fun` to `appWithTranslation` so that it run automaticaly
