### ISSUE TITLE
Dynamic locales loading

### ISSUE THREAD

**Issue by belgattitude** [isaachinman/next-i18next#1371]
## Is your feature request related to a problem? 

The current approach rely on injecting namespaces, languages from getServerSideProps/getStaticProps. This has few drawbacks regarding page performance (html size, lighthouse). When using this for example

<details>
<summary>Example with getServerSideProps</summary>

```typescript
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

export default function MyFeatureRoute(
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  const { t } = useTranslation();
  return <MyFeaturePage>{t('common:page.title')}</MyFeaturePage>;
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  return {
    props: {
      ...(await serverSideTranslations(context.locale, ['common', 'a-feature-specific-namespace'])),
    },
  };
};
```
</details>

The resulting html page will contain all 'common' and 'a-feature-specific-namespace' in the target language + the default language (so it can fallback). i.e:

<details>
   <summary>Extract of props</summary>

```html
<script id='__NEXT_DATA__' type='application/json'>{
  "props": {
    "pageProps": {
      "locale": "fr",
      "_nextI18Next": {
        "initialI18nStore": {
          "fr": {
            "common": {
              "general": {
                "save": "Enregistrer",
                "cancel": "Annuler"
              },
```

</details>

On bigger projects this can lead to a lot a waste... 

Depending on features, we sometimes have **> 100kb (unzipped)** injected in the html. 

## Describe the solution you'd like

I'm wondering if we could improve that, by loading bundled namespaces part of the page loading...

i.e:

```typescript tsx
import Script from 'next/script'

export default function MyFeatureRoute({locale}) {
  
   // Something in the line of doing, either in app.js or per page

   <Script
      src="/mybundled-locales/?namespaces=common,a-feature-namespace/langs=en,fr"
      strategy="beforeInteractive"
    />

  return <MyFeaturePage>{t('common:page.title')}</MyFeaturePage>;
}

```

I'm wondering if you had some ideas about that ?

I partially see a road that I'd like to experiment

- Inject some webpack config that would expose bundles locales per namespace (par of the nextjs build, nice so assets are hashed and can live on the edge / cdn).
- Create a DynamicLoader (appWithDynamicTranslations for example), that would load the scripts.

@isaachinman Have you some things in mind about that problem ? And BTW thanks a lot for this package

**Comment by isaachinman** [comment]
This is [already supported by i18next](https://www.i18next.com/how-to/add-or-load-translations#add-after-init). Does that answer your question?

**Comment by belgattitude** [comment]
Mmm not totally, I'll need to test this out... 

I know we can load locales dynamically with i18next. But It's not clear yet how to set it up with next-i18next in a getServerSideProps context. Keeping all the beautiful features of if it at the same time :smile:

**Comment by isaachinman** [comment]
> But It's not clear yet how to set it up with next-i18next in a getServerSideProps context

Not sure what you mean. You simply use `serverSideTranslations` inside `getServerSideProps`.

**Comment by belgattitude** [comment]
>  You simply use serverSideTranslations inside getServerSideProps.

Yep I do and it's working great. 

```typescript tsx
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

export default function MyFeatureRoute(
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  const { t } = useTranslation();
  return <MyFeaturePage>{t('common:page.title')}</MyFeaturePage>;
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  return {
    props: {
      ...(await serverSideTranslations(context.locale, ['common', 'a-feature-specific-namespace'])),
    },
  };
};
``` 

The side effect of this approach is the resulting html page size... Cause props will be inlined.

> But It's not clear yet how to set it up with next-i18next in a getServerSideProps context

I see here is that weto no rely on injected props.

https://github.com/isaachinman/next-i18next/blob/93136a4f411e42059e660ec928408ca3b9619df0/src/appWithTranslation.tsx#L52

I'm wondering if an `appWithDynamicallyLoadedTranslations` would be an option. 

In this scenario, locales (namespace / languages) would be built and present in the dist folder (.next/static/locales/ns1-NEXT_BUILD_HASH.fr.js) so we can load them up with https://www.i18next.com/how-to/add-or-load-translations#add-after-init



My question is more would it make sense in your experience ?

**Comment by isaachinman** [comment]
I don't understand what exactly you are suggesting. You already have access to `addResourceBundle` if you want to dynamically load a namespace on the client. Nothing needs to be "built" or "present in the dist folder" for you to use this functionality.

In general, adding translation data to page props is _exactly_ how this package works, because that is how _NextJs works_. Our translation data is indeed a data dependency of the page, and is therefore handled as such.

**Comment by belgattitude** [comment]
> In general, adding translation data to page props is exactly how this package works, because that is how NextJs works

I'm just suggesting something, I'm aware of the props. Just trying to figure out how to circumvent html size increase due locales inlining, in my context I have a deal with quite big locales... 

> You already have access to addResourceBundle if you want to dynamically load a namespace on the client. 

I'll try this thanks. In this scenario we would remove "big" namespaces and load them dynamically with addResourceBundle..

> Nothing needs to be "built" or "present in the dist folder" for you to use this functionality.

Maybe overseeing the thing :smile:

**Comment by isaachinman** [comment]
> Just trying to figure out how to circumvent html size increase due locales inlining, in my context I have to deal with quite big locales

The current idea is to split your translations into different namespaces to address this issue. In the future, the hope is that static analysis of translation data will be possible.
