### ISSUE TITLE
Can't access locales inside Provider wrapping _app.jsx

### ISSUE THREAD

**Issue by huarmenta** [isaachinman/next-i18next#1377]
I'm not exactly sure if this is an actual bug but I read this issue #1215 and @oceandrama points that when you set an `undefined` on `serverSideTranslations` **i18next** loads all the resources, which is true and I agree that this could be the default behaviour and we can eliminate the need to add `getStaticProps` in all pages, and lead me to think about how **next-i18next** works with loading resources.

So I'll try to point exactly what I need to do and the expected behaviour.

## Describe the bug
Not loading locales inside a Provider that wraps _app.jsx.

## Occurs in next-i18next version
**next-i18next@8.6.0**

## Steps to reproduce
I have a page that loads specific `serverSideTranslations(locale, 'page')` and over that page on _app I wrap the whole application with a Provider which needs translations too.
```
const MyApp = ({Component, pageProps}) => {
  return (
    <SWRConfig value={{fetcher}}>
      <Toaster />
      <ErrorProvider> // THIS IS THE PROVIDER THAT NEEDS TRANSLATIONS
        <Component {...pageProps} />
      </ErrorProvider>
    </SWRConfig>
  );
};
```
If I set `serverSideTranslations(locale, undefined)` then all translations are loaded and I can use them in the Provider, but if I set a specific locale, then **next-i18next** or **i18next** (I honestly don't know which one does it) loads locales from the pages and not the ones I need in the Provider.

## Expected behaviour
Access `useTranslation('error')` locales inside a Provider that wraps _app.jsx

My questions are: 
Is there any way to load specific locales inside my Provider even if it's not a page?, or 
Should I need to add `undefined` in every page so I can access all of the locales everywhere?

I appreciate any kind of guidance for this, I'm having trouble finding a way to translate components that are not pages.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - macOS Big Sur
 - Versión 1.28.106 Chromium: 92.0.4515.159 (Build oficial) (x86_64)

**Comment by isaachinman** [comment]
> Is there any way to load specific locales inside my Provider even if it's not a page?

Yes, by adding the namespaces to each of your pages' `serverSideTranslations`. It's as simple as that. Please post any future help requests on StackOverflow. Good luck!

**Comment by laclance** [comment]
_app is not a page though? only solution I have found is by using the I18nextProvider to MyApp.
