### ISSUE TITLE
Localized strings get replaced by strings name on page change

### ISSUE THREAD

**Issue by jpvalery** [isaachinman/next-i18next#1378]
Hi there,

_I'm not 100% sure that /issues is the best place to share my problem but I didn't see a Discussions tab. Apologies in advance if it wasn't the right place._

I've started implementing next-i18next on my Next.js site to localize content in English (default) and French.

I'm a bit puzzled as to why the localization of the header (done in _app.js) works on index.js (both / and /fr) but as soon as I load another page, the localized text reverts back to the name of the variable. 

**How to reproduce**
1. Go to https://guestsite-git-i18n-jpvalery.vercel.app/ and make sure you're seeing the english version
2. Click on About on the top menu
3. Page will change to /about
4. Witness the text changing to menuAbout

![ezgif com-gif-maker](https://user-images.githubusercontent.com/4112343/130700246-78f2db42-bac5-4018-a9f8-1bdd52b99778.gif)

**Repository**
https://github.com/MontrealPhotoClub/guestsite/tree/i18n

The content of the /about and /contact pages linked in the menu is being generated by pages/[slug].js which is not using next-i18next yet. However, the menu is imported in _app.js.

What am I missing or doing wrong here?

Thanks in advance for your help,

**Comment by isaachinman** [comment]
You need to implement `serverSideTranslations` on _all_ pages you want to translate. Good luck!
