### ISSUE TITLE
useTranslation function not work for me

### ISSUE THREAD

**Issue by rczupa** [isaachinman/next-i18next#1393]
Hi, my name is Renan, and I have problems to use useTranslation function

I follow the step by step of the documentation, but, when i try use useTranslation function, the translation process doenst ocurr.

I need help guys, tks a lot

## Occurs in next-i18next version
next-i18next: 8.6.0

## Steps to reproduce
_app file
`import React, { useEffect } from 'react'
import { appWithTranslation } from 'next-i18next'
import Layout from '../Containers/Layout'
import Snack from '../Components/Snack'
import { Provider, useSelector, useDispatch } from 'react-redux'
import { compose } from 'redux'
import { getCookieFromBrowser } from '../utils/cookie'
import { store, persistor } from '../redux/store'
import { PersistGate } from 'redux-persist/integration/react'
import Loading from '../Components/Loading/index'
import { removeError } from '../redux/error'
import { showSnack } from '../redux/snack'
import { getUser, logOut } from '../redux/auth'
import PrivateRoute from '../Components/PrivateRoute/PrivateRoute'
import wrapper from '../redux/reduxWrapper'

const MyApp = ({ Component, pageProps }) => {
  const dispatch = useDispatch()
  const error = useSelector<any, any>((state) => state.error?.error)
  const snack = useSelector<any, any>((state) => state.snack?.snack)
  const usuario = useSelector<any, any>((state) => state.usuario?.usuario)

  const rotasProtegidas = ['/usuario/pagamentos', '/usuario/meus-anuncios', '/usuario/manter-anuncio/criar-anuncio', '/usuario/conta']

  useEffect(() => {
    if (error) {
      dispatch(showSnack('error', error.message))
      dispatch(removeError())
    }
  }, [error])

  useEffect(() => {
    const token = getCookieFromBrowser('token')
    if (token) dispatch(getUser(token))
  }, [usuario])

  return (
    <>
      <Provider store={store}>
        <PersistGate loading={<Loading />} persistor={persistor}>
          <Layout>
            <PrivateRoute protectedRoutes={rotasProtegidas}>
              <Component {...pageProps} />
            </PrivateRoute>
          </Layout>
        </PersistGate>
      </Provider>
      {snack && <Snack />}
    </>
  )
}

MyApp.getInitialProps = async ({ Component, ctx }) => {
  return {
    pageProps: Component.getInitialProps ? await Component.getInitialProps(ctx) : {}
  }
}

export default compose(appWithTranslation, wrapper.withRedux)(MyApp)

//export default wrapper.withRedux(MyApp)
`

My page, that the translation process didnt work
`import React from 'react'
import Anuncio from './Anuncio'
import FormularioAnuncio from '../../../Containers/Anuncio/formulario-anuncio'
import { requirePageAuth } from '../../../utils/withAuthServerSide'
import { GetServerSideProps } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'

export const getServerSideProps: GetServerSideProps = requirePageAuth(async (context) => {
  const novoAnuncio = {
    ano: '',
    cambio: '',
    carroceria: '',
    cidade: '',
    cilindrada: '',
    combustivel: '',
    cor: '',
    descricao: '',
    estado: {},
    estilo: '',
    marca: '',
    marcaId: '',
    modelo: '',
    motor: '',
    preco: '',
    quilometragem: '',
    sobrealimentado: '',
    suspencao: '',
    items: {
      airbag: false,
      alarme: false,
      arQuente: false,
      regulagemDeAltura: false,
      computadorDeBordo: false,
      controleDeTracao: false,
      desembacadorTraseiro: false,
      arCondicionado: false,
      esconstoDeCabecaTraseiro: false,
      abs: false,
      limpadorTraseiro: false,
      radio: false,
      retrovisoresEletrico: false,
      rodasLigaLeve: false,
      sensorDeChuva: false,
      sensorDeEstacionamento: false,
      tetoSolar: false,
      retrovisorFotocromico: false,
      travasEletricas: false,
      vidrosEletricos: false,
      bancoEmCouro: false,
      farolDeXenonio: false,
      gps: false
    }
  } as Anuncio

  return {
    props: {
      anuncio: novoAnuncio,
      ...(await serverSideTranslations(context.locale, ['common']))
    }
  }
})

const CriarAnuncio = (props) => {
  console.log('props ', props)
  const { t } = useTranslation('common')

  return (
    <div>
      <span>Eitcha {t('test')}</span>
      <FormularioAnuncio anuncio={props.anuncio} />
    </div>
  )
}

export default CriarAnuncio
`

I dont know what can I do to solve this problem.

Tks a lot

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!
