### ISSUE TITLE
Initial locale argument was not passed into serverSideTranslations

### ISSUE THREAD

**Issue by grace618** [isaachinman/next-i18next#1398]
when next.js use custom server

**Comment by grace618** [comment]
I have solved this problem, if someone is like me, please pay attention to next.config.js, you can write it like this for the time being to test

const {i18n} = require('./next-i18next.config');
module.exports = {
    i18n
}

**Comment by davidkhan4747** [comment]
Server Error
Error: Initial locale argument was not passed into serverSideTranslations  
что мне делать объясните пожалуйста
