### ISSUE TITLE
Is getServerSideProps  mandatory for every page just to have translations ?

### ISSUE THREAD

**Issue by kristijorgji** [isaachinman/next-i18next#1399]
After migrating to version 8, from 6 translations are not working anymore with old code.

To fix it , we have to declare getServerSideProps for every page like this (even if page does not need at all any serversidedata)

```
const tNamespaces = ['header'];
export async function getServerSideProps({
    locale,
}: GetServerSidePropsContext): Promise<GetServerSidePropsResult<any>> {
    return {
        props: {
            ...(await serverSideTranslations(locale || 'en_US', tNamespaces)),
        },
    };
}
```

Does this reduce performance in any way, and seems to be mandatory

**Comment by isaachinman** [comment]
You should use `getStaticProps` unless you specifically need SSR.

**Comment by kristijorgji** [comment]
@isaachinman I used initially getStaticProps, then had trouble as needed to define also getStaticPathsMethod (next build was failing). So mandatory to define those 2 routes just to get translations work ?

**Comment by kristijorgji** [comment]
What should be the content of getStaticPaths in such case for a page that does not need anything from server, but just translations ?

Before these pages had only frontend logic + needing translations and be able to use `t` function, that came inside via `withTranslation` wrapper

**Comment by isaachinman** [comment]
Please check the NextJs documentation directly for answers to all of your questions.

**Comment by hugefunwoo** [comment]
just in case anyone who dig this far and look for a way out

when using `getStaticPaths` we need to pass `locale` info into each path, which said

```
export async function getStaticPaths({ locales }: { locales: Array<string> }) {
  const data = ['foo', 'bar'];
  const paths = data
    .map((item) =>
      locales.map((locale) => ({
        locale,
        params: { name: item },
      }))
    )
    .flat();
  return {
    paths,
    fallback: false,
  };
}

export const getStaticProps = async ({
  locale,
  params: { name },
}: {
  locale: string;
  params: { name: 'foo' | 'bar' };
}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
      name,
    },
  };
};
```

**Comment by kristijorgji** [comment]
> just in case anyone who dig this far and look for a way out
> 
> when using `getStaticPaths` we need to pass `locale` info into each path, which said
> 
> ```
> export async function getStaticPaths({ locales }: { locales: Array<string> }) {
>   const data = ['foo', 'bar'];
>   const paths = data
>     .map((item) =>
>       locales.map((locale) => ({
>         locale,
>         params: { name: item },
>       }))
>     )
>     .flat();
>   return {
>     paths,
>     fallback: false,
>   };
> }
> 
> export const getStaticProps = async ({
>   locale,
>   params: { name },
> }: {
>   locale: string;
>   params: { name: 'foo' | 'bar' };
> }) => {
>   return {
>     props: {
>       ...(await serverSideTranslations(locale, ['common'])),
>       name,
>     },
>   };
> };
> ```

thanks for the hint.

In my case I don't have getStaticPaths and still have issue of all possible translations returned.

I have only `getServerSideProps` method as explained in my post, passing the locale to next-i18next and still in response i get back translations for all languages, which is increasing the response size a lot.

If I open domain.com/de/somepage i need back only de_DE (de-DE) translations, not everything de fr en and so on

**Comment by bryantobing12** [comment]
> just in case anyone who dig this far and look for a way out
> 
> when using `getStaticPaths` we need to pass `locale` info into each path, which said
> 
> ```
> export async function getStaticPaths({ locales }: { locales: Array<string> }) {
>   const data = ['foo', 'bar'];
>   const paths = data
>     .map((item) =>
>       locales.map((locale) => ({
>         locale,
>         params: { name: item },
>       }))
>     )
>     .flat();
>   return {
>     paths,
>     fallback: false,
>   };
> }
> 
> export const getStaticProps = async ({
>   locale,
>   params: { name },
> }: {
>   locale: string;
>   params: { name: 'foo' | 'bar' };
> }) => {
>   return {
>     props: {
>       ...(await serverSideTranslations(locale, ['common'])),
>       name,
>     },
>   };
> };
> ```

```
const data = ['foo', 'bar'];
```

as stated there we need to define every path

In my case, I'm building a user details page, I have approx 1000 users.

my path
`/users/[id]`

so to get the translation working I need to fetch all my users from DB in `getStaticPaths`  just to get the paths and define the locale in there?
