### ISSUE TITLE
Using i18next-fs-backend gives Can't resolve 'fs' error

### ISSUE THREAD

**Issue by gablabelle** [isaachinman/next-i18next#1401]
Hello,

Our app is meant to be used in various contexts. As a stand-alone app, embedded in Microsoft Teams app, via iframes, etc... So we unfortunately need to map the locales we received in the URL from the host apps using some custom fallback logic that is a bit more complex than simply going from, for example, fr-ca to fr.

```
/* next-i18next.config.js */

const {
  defaultNextLocale,
  getSupportedLegacyLocale,
  supportedNextLocales,
} = require('@monorepo/i18n');

const Backend = require('i18next-fs-backend');

module.exports = {
  i18n: {
    locales: supportedNextLocales,
    defaultLocale: defaultNextLocale,
  },
  lowerCaseLng: true,
  reloadOnPrerender: process.env.NODE_ENV === 'development',
  use: [Backend],
  backend: {
    loadPath: (nextLocale) => {
      const supportedLegacyLocale = String(
        getSupportedLegacyLocale(nextLocale),
      );
      return `/locales/${supportedLegacyLocale}/{{ns}}.json`;
    },
  },
  serializeConfig: false,
};

```

```
/* _app.tsx */

import nextI18NextConfig from '../next-i18next.config';

export default appWithTranslation(App as FunctionComponent<AppProps>, nextI18NextConfig);
```

```
/* login.tsx */

import { defaultNextLocale } from '@monorepo/i18n';
import { useTranslation } from 'next-i18next';
import { GetStaticPropsContext } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import nextI18NextConfig from '../../next-i18next.config';

export async function getStaticProps({
  locale = defaultNextLocale,
}: GetStaticPropsContext) {
  console.log({ locale });
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'], nextI18NextConfig)),
    },
  };
}

function LoginPage() {
  const { t, i18n } = useTranslation('common');
  console.log('----- i18n.language', i18n.language);
  console.log('-----', t('common:all_actionContinue'));
... ...
```

But I get the following error

```
wait  - compiling...
error - ../../node_modules/i18next-fs-backend/cjs/fs.js:2:0
Module not found: Can't resolve 'fs'
```

**Comment by KGALLET** [comment]
Look's like I also have the problem..

**Comment by isaachinman** [comment]
Please provide a full stacktrace, or a reproducible repository.

**Comment by KGALLET** [comment]
> Please provide a full stacktrace, or a reproducible repository.

Here you are : https://github.com/KGALLET/next-i18n-issue

➜ node -v 
v14.16.1

➜ "next": "^11.1.0",
➜ "next-i18next": "^8.6.0",
➜ "react": "^17.0.2",
➜ "react-dom": "^17.0.2"

**Comment by isaachinman** [comment]
You are attempting to use `getStaticProps` on an arbitrary React component, not within the `pages` directory. This is not how NextJs works. Please take a closer look at the documentation. Good luck!

**Comment by gablabelle** [comment]
Hello @isaachinman since I'm the original author of this issue please consider checking ths following stackblitz app where you'll be able to reproduce the error by uncommenting **line 1** and **line 17 to 26**

https://stackblitz.com/edit/nextjs-y6aamt?file=next-i18next.config.js

I'm using `getStaticProps` on `pages/index.js` 

![Screen Shot 2021-09-06 at 10 09 48](https://user-images.githubusercontent.com/1565793/132229943-9b6403e7-7e6c-4b32-9037-5b1028ddb99f.png)

**Comment by isaachinman** [comment]
Ah, I see. So the issue here is that `getStaticProps` and `getServerSideProps` have any NodeJs dependencies stripped away when bundled for the client, but `_app` does not.

Moreover, when `serializeConfig` is `true`, you can omit passing your config into `appWithTranslation`, but when `serializeConfig` is `false`, we have no way of passing the config from the page level to `_app`, so it is a requirement to pass the config into `appWithTranslation`.

Open to suggestions on how to solve this issue.

**Comment by gablabelle** [comment]
OK if I understand this correctly, we have 3 possibilities:

1) Not use serialize at `false` in the first place but we'll get the `SerializableError: Error serializing '._nextI18Next.userConfig.use[0]' returned from 'getStaticProps'` error because of our config file.

2) Find an alternate way to do the mapping without using i18next-fs-backend if that is possible?

3) Make sure that fs code doesn't run client side?

@isaachinman Any suggestions for points 1 or 2?

On my side, I've tried the point 3 on this stackblitz fork (using webpack 4): https://stackblitz.com/edit/nextjs-do2zxq?file=next.config.js and now get the `Error: You are passing a wrong module! Please check the object you are passing to i18next.use()` as you will see.

When running that code locally in my project using webpack 5, the app boots but I see the translation keys instead of the translated texts.

![Screen Shot 2021-09-06 at 11 39 37](https://user-images.githubusercontent.com/1565793/132240256-8b171e2f-ea86-4749-9b5d-49af6434f3c4.png)

**Comment by isaachinman** [comment]
@gablabelle I haven't looked into your mapping setup and therefore cannot advise you on whether or not use of `i18next-fs-backend` is mandatory in your case.

The third option you presented is probably the easiest. Instead of messing with webpack config, simply conditionally require/import the dependency based on `typeof window === 'undefined'`.

It would be nice to solve this problem at the `next-i18next` level, though.

**Comment by gablabelle** [comment]
@isaachinman I'm beginning to look at the source code and it seems that you're already using `i18next-fs-backend` so I guess you must already be doing something in this regard in order to make sure that all the props that `serverSideTranslations` passes down can be serialized.

So maybe the best solution here would be to support merging with the existing next-i18next's i18next-fs-backend options by exposing for example `fsBackend`.

![Screen Shot 2021-09-06 at 13 37 30](https://user-images.githubusercontent.com/1565793/132249586-2eeb7522-c7ea-4a6d-a70e-74c8df60244d.png)

**Comment by gablabelle** [comment]
Decided to simply use `i18next-http-backend` instead. Does the fetching at build time so basically does the same thing without having to `fs` error popin' up.

```
const {
  defaultLocale,
  defaultLocaleNamespace,
  getSupportedLocale,
  supportedNextLocales,
} = require('@monorepo/i18n');
const httpBackend = require('i18next-http-backend');

module.exports = {
  i18n: {
    locales: supportedLocales,
    defaultLocale,
  },
  ns: [defaultLocaleNamespace],
  defaultNS: defaultLocaleNamespace,
  lowerCaseLng: true,
  reloadOnPrerender: process.env.NODE_ENV === 'development',
  use: [httpBackend],
  backend: {
    loadPath: (
      locales = [defaultLocale],
      namespaces = [defaultLocaleNamespace],
    ) => {
      const [nextLocale] = locales;
      const [namespace] = namespaces;
      // Custom fallback logic
      const locale = getSupportedLocale(nextLocale);
      // This URL is only used during build, localhost:5000 is always OK
      // in that context (inside Docker container or during local dev)
      return `http://localhost:5000/locales/${String(locale)}/${String(
        namespace,
      )}.json`;
    },
  },
  load: 'all',
  // Because our config contains functions, it can't be serialized
  // and has to be passed manually to app and pages.
  serializeConfig: false,
  react: {
    useSuspense: false,
  },
  debug: false,
};
```

Thanks for your time and help @isaachinman

**Comment by theabdulmateen** [comment]
> @gablabelle I haven't looked into your mapping setup and therefore cannot advise you on whether or not use of `i18next-fs-backend` is mandatory in your case.
> 
> The third option you presented is probably the easiest. Instead of messing with webpack config, simply conditionally require/import the dependency based on `typeof window === 'undefined'`.
> 
> It would be nice to solve this problem at the `next-i18next` level, though.

Make sure not to use a variable for `typeof window === 'undefined'` when you conditionally require the plugins. You need to make the check inline like so:

```js
---
backend: {
    backends:
      typeof window === 'undefined'
        ? [
            require('i18next-fs-backend/cjs'),
            require('i18next-http-backend/cjs'),
          ]
        : [],
}
---
```
