### ISSUE TITLE
i18next properties dont seem to do anything

### ISSUE THREAD

**Issue by MauriceNino** [isaachinman/next-i18next#1412]
## Describe the bug
I want to support sub-locales. So for example, if someone calls my website with `Accept-Language: de-DE`, then `de` should be loaded.

For this, there seems to be the property `nonExplicitSupportedLngs` in i18next. I tried adding it to the config, but it is being ignored.

```js
// next-i18next.config.js
const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de']
  },
  fallbackLng: 'en',
  supportedLngs: ['en', 'de'],
  nonExplicitSupportedLngs: true,
  load: 'all',
  reloadOnPrerender: !isProd
};
```

## Occurs in next-i18next version
v8.7.0

## Steps to reproduce
This commit on my repository has the "bug": https://github.com/MauriceNino/portfolio/commit/792997f0b7df0de41e592fb58ac672d2b523afc9

You can also send a GET request against the live version:

```http
# Does not work
GET mauz.io HTTP/1.1
Accept-Language: de-DE

###

# Works
GET mauz.io HTTP/1.1
Accept-Language: de
```

**Comment by isaachinman** [comment]
All handling of locales is done by NextJs directly. If you want `de-DE` to fallback to `de`, you will need to investigate how to make that happen via NextJs itself. Good luck!

**Comment by MauriceNino** [comment]
What are the i18next properties for, then? Do I even pass them at the correct position?  @isaachinman

**Comment by isaachinman** [comment]
The i18next properties all work as normal, with the caveat that NextJs dictates the current locale, as it handles internationalised routing. Hope that makes sense.

**Comment by MauriceNino** [comment]
Makes sense. Can I somehow implement a custom language detection function? Seems like it was possible with older versions of this library (#208).

If not, are there any plans on supporting that again?

Thanks a lot for taking your time for me!

**Comment by isaachinman** [comment]
> Can I somehow implement a custom language detection function?

Not at the moment, to my knowledge.

> Seems like it was possible with older versions of this library

Yes, that's correct. Previously, `next-i18next` handled all aspects of localisation, including detection and routing. The Vercel team's ultimate goal is to support internationalisation first class, completely, but they decided to start with just the detection + routing aspect.

Therefore, any detection or routing concerns should be forwarded to the NextJs repo.

**Comment by MauriceNino** [comment]
Understood, thanks a lot!

**Comment by MauriceNino** [comment]
As a quick update, in case anyone stumbles upon this issue later on, I solved it using next's `getServerSideProps`, like in the following snippet: https://gist.github.com/MauriceNino/bcb3d7361148153c4c7da84ffe128d39

**Comment by yoangau** [comment]
I am going to add two notes to @MauriceNino last comment to help people who stumbles on this problem. 

+ If you happen to use Vercel as a platform, you might fall into a problem where all your pages are now 404 even if it works in local and the build didn't have any errors (see #462 ). If you go in serverless functions you will see the error, but here is the fix:

```ts
// next-i18next.config.js
const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'fr'],
    nonExplicitSupportedLngs: true,
    localePath: path.resolve('./public/locales'),
  },
};

```

+ The last point is more of a trick than anything else, you define your getServerSideProps function in one place and use it in every page you want:

```ts
// helpers/localisation.ts
export const getServerSideProps: GetServerSideProps = async ({ req, locale, locales }) => {
  ...
};
```

```ts
// All pages except for 404
import { getServerSideProps } from 'helpers/localisation';
...
export { getServerSideProps };
export default CurrentPage;
```
