### ISSUE TITLE
serverSideTranslations is returning all locales for page rendered in a single language

### ISSUE THREAD

**Issue by kristijorgji** [isaachinman/next-i18next#1414]
We have a page that is only generated statically at build time.
As documented, we are using `serverSideTranslations` at `getStaticProps` only.

For the default locale en_US we get back in next props only en_US translations which is great and the expected result.

But for other locales (not default), like de_DE we get back all the locales even not current ones like en_US. This is increasing json response size unecessary.

So the response coming from 
`http://localhost:3000/_next/data/6yqLeicBjnkdsm2O59mZU/de_DE/posts.json`
is (of interest only is the fact that under initialI18nStore is also key en_US which adds extra size to the transfer)
```
{
  "pageProps": {
    "_nextI18Next": {
      "initialI18nStore": {
        "de_DE": {
          "header": {
            "home": "Hause",
            "posts": "Trainingseinheiten"
          },
          "footer": {
            "description": "@TEST 2020"
          },
          "posts-page": {
            "pageTitle": "Posts"
          }
        },
        "en_US": {
          "header": {
            "home": "Home",
            "posts": "Posts"
          },
          "footer": {
            "description": "@TEST 2020"
          },
          "posts-page": {
            "pageTitle": "Posts"
          }
        }
      },
      "initialLocale": "de_DE",
      "userConfig": {
        "localePath": "testnext/public/static/locales",
        "i18n": {
          "defaultLocale": "en_US",
          "locales": [
            "en_US",
            "de_DE"
          ]
        },
        "default": {
          "localePath": "testnext/public/static/locales",
          "i18n": {
            "defaultLocale": "en_US",
            "locales": [
              "en_US",
              "de_DE"
            ]
          }
        }
      }
    }
  },
  "__N_SSG": true
}
```

For the default locale en_US getting
`http://localhost:3000/_next/data/6yqLeicBjnkdsm2O59mZU/en_US/posts.json`
gives back only en_US key in int translations.
![Screenshot 2021-09-07 at 18 25 10](https://user-images.githubusercontent.com/15630854/132379101-aa8c3f94-dda4-41df-8062-e5889fe99dc6.png)

And here is the code of the page, where we implemented next-i18next

pages/posts.ts
```
import React from 'react';
import Head from 'next/head';
import { SSRConfig, withTranslation } from 'next-i18next';
import { NextPageProps } from '../types/NextPageProps';
import { GetStaticPropsContext, GetStaticPropsResult } from 'next';
import { useRouter } from 'next/router';
import { linkRendered } from '../utils/linkRenderer';
import { PostModel } from '../components/types';
import PostsPage from '../components/pages/PostsPage/PostsPage';
import { formPostModels } from '../components/mappers/postsMapper';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { DEFAULT_LOCALE } from '../constants';
import { useQuery } from 'react-query';
import { getPosts } from '../services/queries';

const Posts = ({ t }: NextPageProps) => {
    const router = useRouter();
    const { data: posts, status, error } = useQuery<PostModel[], Error>('posts', () =>
        getPosts().then(formPostModels)
    );

    return (
        <>
            <Head>
                <title>{t('posts-page:pageTitle')}</title>
    </Head>
    <main>
    {posts && (
        <PostsPage
            posts={posts}
        onCreateClick={() => {
        router.push('/posts/create');
    }}
        renderLink={linkRendered}
        />
    )}
    </main>
    </>
);
};

const tNamespaces = ['header', 'footer', 'posts-page'];
export async function getStaticProps({ locale }: GetStaticPropsContext): Promise<GetStaticPropsResult<SSRConfig>> {
    return {
        props: {
            ...(await serverSideTranslations(locale || DEFAULT_LOCALE, tNamespaces)),
        },
    };
}

export default withTranslation(tNamespaces)(Posts as any);

```

Is there any way to return for a particular statically generated page only the translations for that locale ?

so for de_DE need to return only de_DE i18n translations ?

I debugged and getStaticProps props function is called correctly only 2 times by next, each time with different locale en_US first then de_DE but I don't know why the generated `_next/data/6yqLeicBjnkdsm2O59mZU/de_DE/posts.json` props contain both language translations

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by kristijorgji** [comment]
> Please provide a reproducible repository.

I will try to do that soon, as have to strip down remove a lot of code.

But please, from a first look do you have any suggestion at top of the mind ?

**Comment by isaachinman** [comment]
Yes, that `de_DE` is not a valid locale. You probably want `de-DE`.

**Comment by kristijorgji** [comment]
I changed to de-DE, but I still got same result, having both locales returned

**Comment by isaachinman** [comment]
You'll need to provide a reproducible repository.

**Comment by kristijorgji** [comment]
Hi, here is a reproducible repository that I created for the community to use as a starter template of next + all custom features i set up

https://github.com/kristijorgji/next-ts-storybook-example-project

To  reproduce:
1. clone, yarn install && yarn build && yarn start
2. change locale to de_DE, then refresh page for example while being in localhost:3000/de_DE/anmelden, check .json response and you will see also en_US translations are returned in the json response. If you open the page in english just localhost:3000/login, then response is correct and only en_US values are in the i18n json response

**Comment by isaachinman** [comment]
@kristijorgji The behaviour you are observing is the [automatic assignment of `defaultLocale` to `fallbackLng`](https://github.com/isaachinman/next-i18next/blob/master/src/config/createConfig.ts#L42) if it is not provided by the user, which [then gets set in `initialI18nStore`](https://github.com/isaachinman/next-i18next/blob/master/src/serverSideTranslations.ts#L84).

If you _don't want_ this behaviour, simply set `fallbackLng: []`.

**Comment by kristijorgji** [comment]
> fallbackLng
Thanks, one more question, where can i set fallbackLng: [] for all pages ?

**Comment by isaachinman** [comment]
In your `next-i18next.config.js`.
