### ISSUE TITLE
Pass missingKeyHandler option in configuration

### ISSUE THREAD

**Issue by clement-faure** [isaachinman/next-i18next#1415]
## Describe the bug
When adding **missingKeyHandler** options in next-i18next-config.js, getStaticProps crash due to the fact that function is not serializable

## Occurs in next-i18next version
"next-i18next": "^8.5.1",

## Steps to reproduce
Create next-i18next-config.js file with 
`
module.exports = {
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
    saveMissing: true,
    missingKeyHandler: (lngs, ns, key, fallbackValue, updateMissing, options) => {}
  },
};

`

## Expected behaviour
It should work normally.
As said in the README :

> All other i18next options can be passed in as well.

## OS (please complete the following information)
 - Device: MBP 2019 16
 - Browser: Chrome 93.0.4577.63

**Comment by isaachinman** [comment]
https://github.com/isaachinman/next-i18next#unserialisable-configs

**Comment by clement-faure** [comment]
> https://github.com/isaachinman/next-i18next#unserialisable-configs

Thank you so much, i missed this part ...
