### ISSUE TITLE
Use a single JSON file for the translations

### ISSUE THREAD

**Issue by El-bana** [isaachinman/next-i18next#1417]
I looked through the documentation but I can't seem to find a way to do this
I want to use a single JSON file for all the translation languages
something like this

```json
{
  "en": {
    "common": {
      "key": "value"
    },
    "page1": {
      "key": "value"
    }
  },
  "de": {
    "common": {
      "key": "value"
    },
    "page1": {
      "key": "value"
    }
  }
}
```
why do I need that?
because I want the translations to be a redux store that I can edit with actions

**Comment by isaachinman** [comment]
You should be able to do that, and pass the translations into i18next [via `config.resources` manually](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources). Good luck!
