### ISSUE TITLE
Lazy loading additional translation files client side

### ISSUE THREAD

**Issue by JosephChotard** [isaachinman/next-i18next#1424]
## Is your feature request related to a problem? Please describe.
Some of our pages require lazyloading components (think of a popup login modal). This modal actually has a lot of translations due to error handling and all that. Currently, we need to load the auth.json file for every page inside `serverSideTranslations`.

Is there a way to tell `useTranslation` to use a translation file that hasn't yet been loaded with `serverSideTranslations`?

## Describe the solution you'd like
Not sure what the most efficient way to approach this would be? Maybe an optional parameter to pass to `useTranslation` or some other hook to add to the page.

## Describe alternatives you've considered
The current solution simply seems to be package all these translations in every page.

I'm more than happy to (try to) write this feature myself and/or write the documentation for it once I've understood how. Any guidance would be appreciated!

**Comment by isaachinman** [comment]
This has already been asked, and answered, many times (https://github.com/isaachinman/next-i18next/issues/1371, as one example).

You can simply use [`addResourceBundle`](https://www.i18next.com/how-to/add-or-load-translations#add-after-init):

```tsx
import { i18n } from 'next-i18next'

const AuthComponent = () => {
  const { locale } = useRouter()

  useEffect(() => {
    i18n.addResourceBundle(locale, 'auth')
  })
}
```

**Comment by JosephChotard** [comment]
Sorry about that... Do you mind if I make a PR to add it to the docs? It can hopefully help other people not ask the same question

**Comment by mauliksoni110** [comment]
Hello @isaachinman 
With this setup using `serverSideTranslations`, why does `useTranslation('some_new_ns_not_included_in_serverSideTranslations')` doesn't use the backend to fetch the "new" NS?
In other words, why does the default functionality of `useTranslation` doesn't work, which is to fetch the "new" NS using the config backend? and so we have to do the `i18n.addResourceBundle(locale, 'some_new_ns_not_included_in_serverSideTranslations')` ?

**Comment by isaachinman** [comment]
Hey @mauliksoni110 – that would be a question for the i18next team, as `next-i18next` doesn't control that behaviour.

**Comment by mauliksoni110** [comment]
Thanks @isaachinman 
I think I missed something in i18next config.
added `partialBundledLanguages` as `true`, and used my custom `backend` conditionally when `process.browser` is true.

So I get to use my custom `lazy loaded NS backend` on Client-side, while SSR works as it is using local files.
