### ISSUE TITLE
8.8.0 regression when using custom locale

### ISSUE THREAD

**Issue by smcyr** [isaachinman/next-i18next#1426]
## Describe the bug
I am not using Next.js i18n feature because it doesn't work for my case. So I pass the locale in `getStaticProps` like that:
```JAVASCRIPT
const locale = sanitizeLanguage(context.params.uri[0]);

return {
  props: {
    ...(await serverSideTranslations(locale)),
    locale,
    ....
  },
}
```
It was working fine before because next-i18next is using the initial language parameter passed to `serverSideTranslations` to initialize i18next. But now, you are using the locale from the router (`const { locale } = props.router`) which is undefined in my case, because I don't use the official i18n config of Next.js.

## Occurs in next-i18next version
This commit cause the issue: https://github.com/isaachinman/next-i18next/commit/1f981771427c2142c65d3fd914857482c16a596c, specifically in the `src/appWithTranslation.tsx` file.

## Steps to reproduce
Call `serverSideTranslations` with a language without using Next.js i18n implementation.

## Expected behaviour
It should work as before, initializing i18next with the right locale without having to use Next.js i18n implementation.

## OS (please complete the following information)
 - Device: Windows 10 Pro
 - Browser: Chrome 93.0.4577.82

**Comment by isaachinman** [comment]
`next-i18next` relies on the NextJs i18n functionality. Unfortunately your use case is not supported. I would suggest you pin to a previous version, and raise your use case to the NextJs team so that it might be supported first-class.

**Comment by Osirys25** [comment]
We have similar issue. We have implemented Next.js i18n but `initialLocale` in `serverSideTranslations` function does not work in 8.8.0 version. We need to change language by `initialLocale` value as in `8.7.0` for each page.
Can you resolve this?
