### ISSUE TITLE
Inexplicable 404 error on vercel

### ISSUE THREAD

**Issue by so1ve** [isaachinman/next-i18next#1435]
## Describe the bug
If next-i18next is used on the dynamically generated page, a 500 error displayed as 404 will appear. (provided _error.tsx is not configured)

## Occurs in next-i18next version
8.8.0

## Steps to reproduce
[Here](https://github.com/so1ve/next-vercel-404)

## Expected behaviour
No 500 error (404?)

## Screenshots
![)98$QVWMQEC 3SZAF3O3N8N](https://user-images.githubusercontent.com/58381667/134445767-333f89b6-13f4-415c-9f9d-01bb50eb8178.png)

## OS (please complete the following information)
 - Device: ASUS Musketeers
 - Browser: Edge (93.0.961.52)

**Comment by isaachinman** [comment]
Not sure I understand what issue you are reporting. Can you provide a stack trace?

**Comment by so1ve** [comment]
This problem has been fixed with the help of vercel staff.
[vercel-support/next-vercel-404](https://github.com/vercel-support/next-vercel-404)
