### ISSUE TITLE
version 8.8.8 has error

### ISSUE THREAD

**Issue by skyboy2020** [isaachinman/next-i18next#1436]
version 8.8.8 can't switch the language text, it has bug.

version 8.8.8 console.log(t)  : 

[Function: fixedT] { lngs: null, ns: 'common', keyPrefix: undefined }

version 8.5.1 console.log(t) : 

[Function: fixedT] { lngs: null, ns: 'common' }

**Comment by isaachinman** [comment]
Not sure I understand your point, can you elaborate?

**Comment by fazi8808** [comment]
@isaachinman So, here is the current flow. I have two pages in my fresh nextjs project `index.js` and `login.js`. Only for login page i have that locale in the right folder as you can see the screenshot below. 

![image](https://user-images.githubusercontent.com/26847943/134817320-522012aa-2f1e-4276-bee1-24d6b067ed85.png)

I get error that says "Default namespace not found at public/locales/en/common.json"

![image](https://user-images.githubusercontent.com/26847943/134817343-bbe859d9-2d47-4187-baf1-340d8b9f9882.png)

Question is, why this is necessary to include the `common.json` file in the `en` folder? 

@skyboy2020 you can resolve it quickly via creating an empty `common.json` file.

**Comment by isaachinman** [comment]
@fazi8808 You do not, it just happens to be the default value for `defaultNS`. Please read [the docs](https://github.com/isaachinman/next-i18next#options).
