### ISSUE TITLE
Is there a way to get `t` function outside functional component, or without hook ?

### ISSUE THREAD

**Issue by kristijorgji** [isaachinman/next-i18next#1437]
Hi,
I was looking for a way to get `t` function outside functional component context or without using hook
(as was described here https://github.com/isaachinman/next-i18next/issues/983) but at the moment could not find such.

I have a utils file utils.ts, and export there a dialog function, and need to add t func there to translate from common namespace

export const salert = new Alert(Swal, // need T function here);

How can I get t fn there

I tried this
```
import { i18n } from 'next-i18next';
i18n?.t as TFunction
```

but did not work

**Comment by isaachinman** [comment]
> but did not work

Can you explain more?

**Comment by kristijorgji** [comment]
Yes I can explain
1. I tested useTranslation hook, not inside a functional component but just in a normal `ts` file and got error "cannot use hook outside functional component context"
2. I tested 
```
import { i18n } from 'next-i18next';
i18n?.t as TFunction 
```
and i18n.t was undefined

3. How can I fetch the `t` function from a normal ts/js file that is not using a react component ?

I have a normal ts file that needs to translate some strings.
This is imported by a next application, that is using of course appWithTranslations

**Comment by isaachinman** [comment]
Check the value of `i18n`. It will be `null` until the global `i18n` instance initialises. You can only call `i18n.t` _after_ your app has initialised.

**Comment by kristijorgji** [comment]
Why is the app not initializing then to create i18n, app is the first thing running, then importing this utility file....

**Comment by kristijorgji** [comment]
> Check the value of `i18n`. It will be `null` until the global `i18n` instance initialises. You can only call `i18n.t` _after_ your app has initialised.

I checked sometimes i18n is not null other times null.

Is there a way to listen for i18n status ? maybe by registering a callback event or something like that

**Comment by bryantobing12** [comment]
still can't get this work done

**Comment by Spell28** [comment]
@bryantobing12 
I didn't understand how to do it the first time either, it ended up like this:
```ts
import { i18n } from 'next-i18next'; // Import
i18n?.init() // Initialize i18n
i18n?.t('translate_key') // get something from your translation json file using current Language

**Comment by sagargulati** [comment]
Any example for using `useTranslation` on /api/ route endpoints with Next.js?

I tried `import { i18n } from 'next-i18next';`

but `i18n?.init()` always returns `null`

**Comment by micktg** [comment]
> @bryantobing12 I didn't understand how to do it the first time either, it ended up like this:
> 
> ```ts
> import { i18n } from 'next-i18next'; // Import
> i18n?.init() // Initialize i18n
> i18n?.t('translate_key') // get something from your translation json file using current Language
> ```

This does not work.
i18n is always null

**Comment by AljazGornik** [comment]
@micktg did you manage to resolve this?  we are facing the same issue

**Comment by micktg** [comment]
> @micktg did you manage to resolve this? we are facing the same issue

I used https://github.com/JCQuintas/ni18n for this.

**Comment by asilliahmet** [comment]
for future reference, here is how i fixed it with async.
just await and use it: `const t = await t_hook`

`import i18next from "i18next";

const t_hook = (async ()=>{
    if (i18next.isInitialized) {
        return i18next.t;
    }
    await i18next.init();
    return i18next.t;
})();

export default t_hook;`

**Comment by zjy365** [comment]
I think we should reopen this issue. It seems that there is no good way to solve this problem.

**Comment by illicit-oblivion** [comment]
> ```ts
> i18n?.init() 
> ```
can you show how to use this particular library outside the component?

**Comment by illicit-oblivion** [comment]
> > @micktg did you manage to resolve this? we are facing the same issue
> 
> I used https://github.com/JCQuintas/ni18n for this.


i18n?.init() 
can you show how to use this particular library outside the component?
