### ISSUE TITLE
<Link href="/"> from next-i18next links to root without subpath

### ISSUE THREAD

**Issue by andylacko** [isaachinman/next-i18next#144]
<Link href="/"> with localeSubpaths: true

expected target: '/en' , when non default locale

given target '/'

**Comment by capellini** [comment]
Hi @andylacko - Are you using the `Link` in `next/link` or are you using the `Link` provided in your `i18n.js` file?

**Comment by andylacko** [comment]
Using link provided from i18n.js

**Comment by capellini** [comment]
Hmmm.  I can't seem to replicate this in our examples.

Could I please see:
1. Your `next-i18next` version?
2. Your `i18n.js` file?

**Comment by isaachinman** [comment]
@capellini Isn't this exact functionality covered by unit tests?

I need to add issue templates to this repository - reproducible examples are a mandatory requirement.

**Comment by capellini** [comment]
> Isn't this exact functionality covered by unit tests?

Yes

> I need to add issue templates to this repository - reproducible examples are a mandatory requirement.

Agreed.  Or, at the very least, to start it would be good to see the `i18n.js` and `server.js` files.  Having version numbers (e.g. `node`, `next-i18next`, etc) also helps.

**Comment by andylacko** [comment]
ach sorry guys, just forgot to rewrite one next/link occurance, everything works fine
