### ISSUE TITLE
Descriptive warnings on missing namespaces for page

### ISSUE THREAD

**Issue by DT-Jari** [isaachinman/next-i18next#1444]
Hi there!

We have the following issue: we have pages that have translated content, as well as shared components that may be used across pages and have translated content as well. An example of their paths and namespaces might be:
- `src/pages/page-1.tsx` -> `'page-1'`
- `src/pages/page-2.tsx` -> `'page-2'`
- `src/components/hero-banner.tsx` -> `'hero-banner'`

Say we have `page-1` set up with the following namespaces (in `getStaticProps`): `['page-1', 'hero-banner']`, but `page-2` has just this namespace: `['page-2']`. Both pages use the `<HeroBanner />` component and thus need to use the `'hero-banner'` namespace.

What we would like is either for `next` to tell us in the build that we're missing a namespace, or for this to produce a runtime warning/debug message to let us know we're missing something.

What happens now is one of:
- An obscure message saying 'The error above occurred in `<YourPageComponent>`', with no error above. This was fixed by adding `react.useSuspense: false` in the config.
- An error about mismatching client/server translations.

Neither of the situations we've encountered hints us towards inspecting the namespaces required in `serverSideTranslations`, while that is the source of the issue.

Please let me know if this explanation is insufficient and a repro is necessary.

**Comment by isaachinman** [comment]
If I understand what you're requesting correctly, we'd have to use tree-traversal, which would make manual declaration of namespaces pointless in the first place, right?

I would certainly support an optional `useTreeTraversal` option in `next-i18next`, which would traverse the entire React tree and automatically compile all necessary namespaces for that tree.

There are some gotchas:

1. Dynamic/runtime required namespaces can't be known on first render, whereas humans can hardcode configs with that knowledge
2. Tree traversal may or may not be trivial, depending on `react-i18next` and `i18next` APIs
3. Tree traversal introduces a performance hit, and is probably only appropriate for SSG, not SSR

**Comment by DT-Jari** [comment]
I think you may be misunderstanding my suggestion. Let's see if I can clarify further:

What I would suggest is adding some check (opt-in through options, I'd imagine) that fires when the `useTranslation` hook encounters a namespace that wasn't included by the page's `getStaticProps` and `serverSideTranslations`.

I stumbled upon this bit of code in `react-i18next` (`src/useTranslation.js:58`):
```js
if (!ready && !useSuspense) {
  loadNamespaces(i18n, namespaces, () => {
    if (isMounted.current) setT(getT);
  });
}
```

Since I'm not sure about how `next-i18next` and `react-i18next` interact, I figured I'd include it to steer you in the right direction :)

Is this a sufficient explanation?

**Comment by isaachinman** [comment]
Sure, that's a lot simpler and is probably a request for `react-i18next` directly.

**Comment by DT-Jari** [comment]
Will contact them with our use case. Thanks!
