### ISSUE TITLE
Routes are 404 on vercel deployment

### ISSUE THREAD

**Issue by ekinndev** [isaachinman/next-i18next#1448]
## Describe the bug
Hi last night I encountered I think a bug. There is no problem on local development(npm run dev) or even production(npm run build && npm start) on my machine everthing works fine. But when I deploy my application on vercel. All the routes are 404.

Example url https://v2.bestizmirege.org/

## Occurs in next-i18next version
^8.8.0
next version:11.1.2

## Steps to reproduce
Here is the repository https://github.com/ekinndev/best-izmir-v2

## Additional context
I saw 500 error code on network tab 
![image](https://user-images.githubusercontent.com/53966235/135895479-ecffbe86-387d-47ea-88bf-78e2730a23b9.png)

![image](https://user-images.githubusercontent.com/53966235/135895535-b60d4bb0-311f-410a-b1c6-ef775860bdeb.png)

I checked vercel logs 
![image](https://user-images.githubusercontent.com/53966235/135897904-531b1a60-80c5-45c7-ba47-efd1dbe16603.png)

Somehow it can't find locales folder maybe?

The build output folder structure

![image](https://user-images.githubusercontent.com/53966235/135898084-dc2c73e6-07b7-4103-8c80-610204640e07.png)

**Comment by isaachinman** [comment]
You'll need to provide more information/logs. At the moment I have no idea how to help you.

**Comment by ekinndev** [comment]
I added vercel logs and showing build folder structure maybe it can help to figure it out what's going on.

**Comment by isaachinman** [comment]
This issue with the Vercel fs has been discussed numerous times on this repo. You need to add `localePath: path.resolve('./my/custom/path')` to your config.
