### ISSUE TITLE
Revise README.md given otherLanguages requirement

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#145]
Given the error that we now throw if `otherLanguages` is empty, we should probably revise [the Project Setup part of our docs](https://github.com/isaachinman/next-i18next#3-project-setup).  If we now initialize `next-i18next` with an empty object, it will throw the error.

Alternatively, I think that it will be OK if we don't throw the error in case someone wants to try out `next-i18next` with zero config.

Let me know which you would prefer and I'll submit the PR.

**Comment by isaachinman** [comment]
> Alternatively, I think that it will be OK if we don't throw the error in case someone wants to try out next-i18next with zero config.

Please refer to #120 (and others). If we don't throw this error, we're going to constantly having people opening issues with user error cases.

I've updated the docs appropriately with 359e213.

The truth is, this package is not truly zero config - the minimum we need to know at the very least is what languages we're serving.
