### ISSUE TITLE
Random path without lang redirects to browser's internal 404 page

### ISSUE THREAD

**Issue by ffan0811** [isaachinman/next-i18next#1464]
## Describe the bug
For example, when I go to
- `www.mysite.com/en`, it works as expected.
- `www.mysite.com/en/existingpage`, it works as expected.
- `www.mysite.com/existingpage`, it works as expected that it automatically redirects to `www.mysite.com/en/existingpage` and show a nextjs custom 404 page
- `www.mysite.com/nonexistingpage`, it gives me
![image](https://user-images.githubusercontent.com/37147911/136912991-56f9a901-6aa9-4a38-ad88-b1f346adf2be.png) when it's supposed to redirect to a custom 404 page with `www.mysite.com/en/nonexistingpage`

## Occurs in next-i18next version
^6.0.2

## Config
```
// next-i18next config
import NextI18Next from 'next-i18next';

import path from 'path';

const NextI18NextInstance = new NextI18Next({
    defaultLanguage: 'en',
    defaultNS: 'common',
    otherLanguages: ['ko'],
    localeSubpaths: {
        en: 'en',
        ko: 'ko',
    },
    fallbackLng: 'en',
    localePath: path.resolve('./public/static/locales'),
    strictMode: false,
});

export const { i18n, appWithTranslation, withTranslation, useTranslation, Link, Router, Trans } =
    NextI18NextInstance;
export default NextI18NextInstance;
```

```
// next.config.js
const nextConfig = {
    ...
    rewrites: async () => nextI18NextRewrites(localeSubpaths),
    ...
}
```

## Expected behaviour
When I change the URL manually with a random path and without defined language, It should redirect to a custom 404 page with an updated URL with a default language (in my case, `en`)

## Additional context
Please let me know If I use `next-i18next` wrong or If there is a related post about the same issue that I'm having. I spent a few hours to find a solution but I couldn't find it. Thank you for the awesome library. :)

**Comment by isaachinman** [comment]
Hi there. Unfortunately I am only a single maintainer, so I do not have enough time to actively maintain previous versions of the package.

If you're unable to upgrade to the latest version, I would suggest debugging the output of `nextI18NextRewrites`. Good luck!
