### ISSUE TITLE
How to use with Static Export

### ISSUE THREAD

**Issue by siamekanto19** [isaachinman/next-i18next#1466]
@isaachinman is there a way to use this library with Nextjs Static Export? Next's built-in i18n feature does not work when we want to export a website statically to serve it using a custom backend. Can we somehow solve this problem using this library? I think it could work in Static Export if Nextjs generates all of the pages for each locales in build time and export it normally like a Staic SPA.

**Comment by adrai** [comment]
@siamekanto19 in case you missed it: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
