### ISSUE TITLE
Can't resolve 'components'

### ISSUE THREAD

**Issue by jaqua** [isaachinman/next-i18next#147]
## Describe the bug
Running `next build` returns the error:

```
> Failed to build
{ Error: (client) ./node_modules/next-i18next/src/index.js
Module not found: Error: Can't resolve 'components' in '/Users/project/node_modules/next-i18next/src'
 @ ./node_modules/next-i18next/src/index.js 6:0-40 25:28-33 26:27-31
 @ ./lib/i18n.js
 @ ./pages/_app.js
 @ multi ./pages/_app.js
...
```

While running in dev mode is working without any problems.

## Occurs in next-i18next version
0.23.3

**Comment by isaachinman** [comment]
Can you check your lockfile? Most likely you were getting v0.23.4, which has now been reverted. If you pick up v0.23.5, everything should be good to go.

Sorry, this project is in a pre-release phase and things are moving quickly. Thank you for your patience.

**Comment by jaqua** [comment]
You are right. It's working again.
