### ISSUE TITLE
How to remove subpath in Ajax request?

### ISSUE THREAD

**Issue by callmewhy** [isaachinman/next-i18next#148]
## Describe the bug
When I use axios or fetch to make a ajax request, all of my request path were added with the subpath prefix.

## Occurs in next-i18next version
i18n-next 0.23.1 

## Steps to reproduce
```
fetch('/api/hand/convert')
```
will make a request to '/en/api/hand/convert'

## Expected behaviour
```
fetch('/api/hand/convert')
```
will make a request to '/api/hand/convert'

## OS (please complete the following information)
 - Device: MBP
 - Browser: Chrome

is it a bug or feature? How can I disable it? thanks

**Comment by isaachinman** [comment]
@callmewhy Please explain why you closed the issue so that future users can learn from it.

**Comment by callmewhy** [comment]
Sorry.

It's not a problem caused by next-i18next. the original ajax request path is corret, but got a 302 redirect by express in server.js.

proxy should be put before nexti18next plugin, so the correct config is:

```js
 server.use('/api', apiProxy)

  server.use(nextI18NextMiddleware(nextI18next))
  server.get('*', (req, res) => handle(req, res))
```

**Comment by isaachinman** [comment]
@callmewhy You can also just use the `ignoreRoutes` config option:

```jsx
const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de'],
  ignoreRoutes: ['/_next', '/static', '/api'].
})
```
