### ISSUE TITLE
Servers with custom locales are no longer supported

### ISSUE THREAD

**Issue by karoun** [isaachinman/next-i18next#1484]
## Describe the bug

As of #1064, `next-i18next` relies on the Next `locale` to determine the current language (rather than `serverSideTranslations.initialLanguage` as before).

Since [Next only supports domain- and subpath-based locale handling](https://github.com/vercel/next.js/discussions/25253), this breaks `next-i18n` for package consumers who implement their own locale support. Ideally, Next would support this use case, but failing that, it'd be excellent for `next-i18n` to continue to support the workaround removed in #1064.

## Occurs in next-i18next version

8.8.0

## Steps to reproduce

Pass a custom locale to `serverSideTranslations`; observe that when renderer server-side, the default locale is used, and when rendered client-side, translations are missing.

```tsx
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

export const Footer = () => {
  const { t, i18n } = useTranslation('footer');
  // i18n.language #=> 'en', but should be 'fr'
  return (
    <footer>
      <p>{t('description')}</p>
    </footer>
  );
};

export async function getStaticProps() {
  return { props: await serverSideTranslations('fr') };
}
```

## Expected behaviour

`i18n.language` should be French (`fr`), but it is instead English (`en`).

## Screenshots

N/A

## OS (please complete the following information)
 - Device: MBP 2017 13"
 - Browser: Firefox 93.0

## Additional context

N/A

**Comment by TheFullResolution** [comment]
I agree with @karoun. An optional override would solve the current inconveniences of using the next.js locale logic. I think alternatives will emerge once middleware API matures, but I do not see an alternative right now.

**Comment by jimhaakman** [comment]
I'm experiencing the same issue. Passing a string as language to `serverSideTranslations` works in 8.7.0 but not from 8.8.0+.

Example:

```
export const getServerSideProps = async (context) => {
  const locale = 'nl'

  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    }
  }
}
```

**Comment by isaachinman** [comment]
I will be able to get out a v9.0.0 release later this week which addresses this issue. Thanks for your patience, everyone!

**Comment by isaachinman** [comment]
Anyone have time to review and/or test #1512? Hoping to get it out today.

**Comment by TheFullResolution** [comment]
> Anyone have time to review and/or test #1512? Hoping to get it out today.

I had a look, I do not see any issues with the changes. It looks like you are reverting to previous behavior which is great for this issue. I think there is a way to support both optional custom locale and to use `router.locale` as default, but after poking around I see I need to get deeper into the source code before I can give you any specific suggestions.

**Comment by isaachinman** [comment]
@TheFullResolution It's not a full revert – the main point of #1064 was to better support shallow routing, which should be retained.

> use router.locale as default

This is tricky, because as far as I know, it's not available in data-fetching methods (outside of being passed as an arg).

v9.0.0 has been released now. Any issues, please do let me know.

**Comment by TheFullResolution** [comment]
I just tested it with the swapfiets.com - all works as expected 👍

**Comment by armandoarmando** [comment]
Hello everyone! I updated the version to 9.2.0 and still having the issue:

![image](https://user-images.githubusercontent.com/46790753/143290721-8d4f3344-7c6f-473c-8ed5-0eba85e632ba.png)
