### ISSUE TITLE
when use with 'serverless-next.js'

### ISSUE THREAD

**Issue by miinnnn2** [isaachinman/next-i18next#1490]
First of all, Thanks for your great work!
I use your library and work well in my local.

However, I deployed my project(Next.Js + next-i18next) with 'serverless-next'
it caused error.

here is error message.
`Error: Cannot find module '/my/local/path/next-i18next.config.js`

I have 4 folders(en, ko, cn, jp) but all they are occur error.
`Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error`

**next-i18next.config.js**
```
const path = require('path');

module.exports = {
  i18n: {
    // locales: ['ko-KR', 'en-US', 'ja-JP', 'zh-CN'],
    // defaultLocale: 'en-US',
    locales: ['en', 'ko', 'jp', 'cn'],
    defaultLocale: 'ko',
  },
  localePath: path.resolve('./src/util/i18n/locales'),
};
```

**next.config.js**
```
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

const { i18n } = require('./next-i18next.config');

module.exports = withBundleAnalyzer({
  target: 'experimental-serverless-trace',
  i18n,
  compress: true, // 파일들을 gzip으로 압축해줌
  webpack(config, { webpack }) {
    const prod = process.env.NODE_ENV === 'production';
    const plugins = [...config.plugins];

    return {
      ...config,
      mode: prod ? 'production' : 'development',
      devtool: prod ? 'hidden-source-map' : 'eval',
      plugins,
    };
  },
});
```

**Comment by isaachinman** [comment]
Where are you deploying your app?

**Comment by miinnnn2** [comment]
aws!

**Comment by isaachinman** [comment]
Please search previous issues.

**Comment by isaachinman** [comment]
@miinnnn2 Perhaps this is related? https://github.com/serverless-nextjs/serverless-next.js/issues/1634

I highly doubt this is an issue with `next-i18next` – it looks like your serverless setup is failing to include the config file in the lambda runtime.

Good luck!
