### ISSUE TITLE
about useTranslation

### ISSUE THREAD

**Issue by wwMichelle** [isaachinman/next-i18next#1499]
I using your next-i18next in my project, and Really Thanks for you great work!
I wonder one thing.

I want to use two files in one page.
so I import two files in getStaticProps, and useTranslation.
but useTranslation couldn't recognize two files.

my Folder Structrue is
`locales > en > common.json`
`locales > en > terms.json`

I want to use Two files all in one page.

My code is here.
```
export const getStaticProps: GetStaticProps = wrapper.getStaticProps(store => async (context: GetStaticPropsContext): Promise<any> => {
  const locale = context.locale;
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'terms'])),
    },
  }
});
```

`const { t } = useTranslation(['common', 'terms']);`

What's my problem?
I'll thank you in advance!

**Comment by wwMichelle** [comment]
I found my fault. really sorry :(

**Comment by tiagobbraga** [comment]
What was?

**Comment by tiagobbraga** [comment]
> What was?

For "problem" reference:
[https://react.i18next.com/latest/usetranslation-hook](https://react.i18next.com/latest/usetranslation-hook)
