### ISSUE TITLE
react-i18next:: You will need to pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by konradmlecz** [isaachinman/next-i18next#1501]
Hej

I have issue with the message is displayed in console...

"react-i18next:: You will need to pass in an i18next instance by using initReactI18next"

but i all working fine... 

My setting i basic: 
My version:   "next-i18next": "^8.9.0",

next-i18next.config:
`
module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en','pl'],
    },
};
`
next.config.js
`
const { i18n } = require('./next-i18next.config');
module.exports = {
  reactStrictMode: true,
  i18n,
}
`

What I should do with setting?

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. Good luck!
