### ISSUE TITLE
Changing language cause to reset context state

### ISSUE THREAD

**Issue by enesozturk** [isaachinman/next-i18next#1502]
## Describe the bug
Hi, thanks for providing such a useful library. Before creating issue, I searched my problem in other issues, articles, discussions but can not find the reason to it. I use React Context API for some data like the user, shopping cart, etc. I set `next-i18next` up and everything works as expected. When I route, I still see my data in context. 

**When I change my language, context data is reset.** Followed Next.js's [Internatlization](https://nextjs.org/docs/advanced-features/i18n-routing) docs, checked all the setup but not sure this is the normal behaviour or not.

### How I change language:

```js
import Link from "next/link";
import { useTranslation } from "next-i18next";
import { useRouter } from "next/router";

const { translate, i18n } = useTranslation();
const router = useRouter();

<Link
  href={router.asPath}
  locale={router.locale === "tr" ? "en" : "tr"}
>
{i18n.language}
</Link>
```

## Occurs in next-i18next version
```js
"next": "^12.0.1",
"next-i18next": "^8.10.0",
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

## Expected behaviour
Context data should be same when I change the language;
From `/cart` -> `/tr/cart` or any route else.

## OS (please complete the following information)
 - Device: MBP 2019 16" Big Sur
 - Browser: 94.0.4606.81

**Comment by isaachinman** [comment]
I think you may be searching for shallow routing. Regardless, routing is handled entirely by NextJs itself, and has nothing to do with `next-i18next`. Good luck!

**Comment by enesozturk** [comment]
Thanks!
