### ISSUE TITLE
Alternative for customDetectors

### ISSUE THREAD

**Issue by glenngijsberts** [isaachinman/next-i18next#1503]
## Is your feature request related to a problem? Please describe.
We want to migrate from version 7 to version 8+. We already updated our Next.js setup to the i18n routing. However, updating to version 8+ of this package will break some things for us. This is because we're having certain domains that don't have dedicated translation files.

For example

```
domainLocales: [
  { domain: 'be.glenn.ticketswap.pizza', defaultLocale: 'nl-BE' },
]
```

Will be using the `nl` translations in our version 7 setup of this package, because we've set up the `customDetectors` option in the config of next-i18next. In version 8 we didn't find something similar, so when landing to the example above it will look inside the `nl-BE` folder, which is not there, breaking our app.

## Describe the solution you'd like
A similar approach as the `customDetectors` option for version 8 of this package, or another way to declare which translations to use for certain domains instead.

## Describe alternatives you've considered
Only other thing considered is adding `nl-BE` (and other translations for other domains where we don't have translation files for, and use a different translation from a different domain, e.g. `nl` in this example) translation files but that will mean that we have more translations to maintain, which is not ideal to us.

**Comment by isaachinman** [comment]
I'm not sure what you're asking. NextJs handles the routing, and the relevant i18next packages handle the actual loading and management of translation content.

What outcome do you want?

**Comment by isaachinman** [comment]
@glenngijsberts Happy to chat through your desired outcome further, but I'm not clear on what you're asking for at this point.
