### ISSUE TITLE
issue with conditional rendering and savemissing

### ISSUE THREAD

**Issue by Freundschaft** [isaachinman/next-i18next#1504]
hi, when I use this library with conditional rendering and savemissing, the hidden elements never get saved to the missing.json file.
I assume that on page render, the server side translation is retrieved, and when the translation cannot be found, the backend isnt prompted again, right?
this results in the missing translations from hidden elements, that are shown later (in my case a multi step form), will never be added to the missing.json

**Comment by isaachinman** [comment]
Hi @Freundschaft – I don't know what you're asking. All i18next options can be passed into the `next-i18next` config, so you'll probably just need to play around with config options. Please post on StackOverflow for further help. Good luck!

**Comment by Freundschaft** [comment]
what I mean is that if I have elements that are not shown immediately on page load, but rendered conditionally by react, then these elements dont show up the files savemissing generates.
Which means that the option "saveMissing" provided by i18n-next cannot be reliably used with this library if I am not mistaken

**Comment by isaachinman** [comment]
If it's possible with NextJs in general, it's possible with `next-i18next`. This package is a very thin layer between the two.

**Comment by Freundschaft** [comment]
i understand, but i think due to the way how the nextjs server side rendering is implemented in this library, all the translations are grabbed on page load through getstaticprops.
and then when I use useTranslation and t('anytext') in a dynamically rendered component, it looks like there is no request sent to the backend to notify of a missing translation, which as far as I understand, after setting the saveMissing flag should be the correct behavior.
Without knowing any details, I assume that there is some issue with the backend lookup not being triggered, but i cant say for sure if next-i18next is to blame or i18next.

**Comment by isaachinman** [comment]
As I said, you'll need to adjust your i18next config.
