### ISSUE TITLE
Rewrites language path is not working on next@v10.1.0

### ISSUE THREAD

**Issue by levu304** [isaachinman/next-i18next#1513]
## Describe the bug
i upgraded from v7.0.1 to v8.0.0 to preparing upgrade next@v12.
My issue is in v7.0.1, i can rewrite locale subpath using **nextI18NextRewrites** but after upgrade v8.0.0, it's not work

## Occurs in next-i18next version
next-i18next@v8.0.0
next@v10.1.0

## Steps to reproduce
// next-i18next.config.js
`
module.exports = {
  i18n: {
    defaultLocale: "vi",
    locales: ["en", "vi", "jp"],
    localeDetection: false,
  },
};
`
// next.config.js
`
  rewrites: async () => [
    {
      source: "/:lang{/}?",
      destination: "/",
    },
    {
      source: "/:lang/:path*",
      destination: "/:path*",
    },
  ],
`

## Expected behaviour
Subpath locale can be rewrited like

**Comment by isaachinman** [comment]
As you probably know from reading the documentation and/or migration guide, the main difference in `next-i18next` v8 is that it no longer handles _any routing whatsoever_. All routing is handled by NextJs directly.

If you believe you've found a bug, please open an issue on the NextJs repository directly.

Please note that the NextJs internationalised routing solution does not offer 1:1 functionality with what `next-i18next` <=7  previously offered.
