### ISSUE TITLE
Dynamic translations within translations

### ISSUE THREAD

**Issue by phil-the-dev** [isaachinman/next-i18next#1517]
## Is your feature request related to a problem? Please describe.
Working at a company, we usually have shifts in terms/branding/features, and trying to go through and comb all the translations across all the pages is cumbersome. 

Example: "To access the new Posting feature, upgrade to Pro today" may need to convert to "To access the **Megaphone** feature, upgrade to **Gold tier** today" (bolding to denote what changed)

## Describe the solution you'd like
I would love to see an implementation where I could use something like `t{{companyTerms:KEY}}` within translation so the above example would look like `To access the t{{corpInc:Post2.0}}, upgrade to t{{corpInc:tier2}} today`

## Describe alternatives you've considered
The only alternative I believe would be to continually pass in variables to the translations, but it gets more difficult to scale as terms could be used across the site. i18n variables seems best when there's data that is dynamic to that session, not a business rule.

## Additional context
Sorry if this is an abuse of the package, I just know the struggles with trying to keep messaging/feature names consistent across a platform. Totally open to new strategies for this situation.

**Comment by isaachinman** [comment]
This is called [interpolation](https://www.i18next.com/translation-function/interpolation), and is of course supported by i18next. Good luck!
