### ISSUE TITLE
Duplicate core-js module in the app's prod bundle due to polyfilling

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#152]
## Describe the bug

After upgrading `next-i18next` from version 0.18.1,  I've started seeing two copies of `core-js` in my prod bundle. This may be related to the fact that it's in `next-i18next`'s `dependencies` and is also because of `@babel/polyfill` in `.babelrc` ([9c96479e](https://github.com/isaachinman/next-i18next/commit/9c96479e27297e300d04b62b17db3d3aa80ae4c4)).

Before / after:

<img width="771" alt="screenshot 2019-02-03 at 16 53 06" src="https://user-images.githubusercontent.com/608862/52179598-70c4b380-27d4-11e9-80d7-f08901ec4b84.png">

<img width="804" alt="screenshot 2019-02-03 at 16 53 15" src="https://user-images.githubusercontent.com/608862/52179596-702c1d00-27d4-11e9-8e45-e86a76d2d907.png">

The problem may be to do with the fact that `core-js` is now used as both an es module and a commonjs one by webpack when the app is built.

## Occurs in next-i18next version
0.20.0...0.25.0

## Steps to reproduce

Run bundle analyzer for the Next.js app

## OS (please complete the following information)
 - Device:  MBP 2017 15"
 - Browser: N/A

## Additional context
Perhaps, polyfilling should be removed from the library completely – doing it only once on the app level ensures that it's not done twice and so there are no duplicate items in the final bundle. As a replacement, the README could advise on what an app developer should do to support older browsers. Some thoughts are here: https://github.com/isaachinman/next-i18next/issues/107

**Comment by kachkaev** [comment]
Yes, I had two versions of `core-js`, but even if I forced one of them via `yarn` and `package.json` `resolutions`, this did not help.

Looking into `node_modules`, reveals that `core-js` is shipped in multiple variants:

<img width="188" alt="screenshot 2019-02-03 at 17 34 18" src="https://user-images.githubusercontent.com/608862/52180103-fac34b00-27d9-11e9-844e-dd03ac8a9ec8.png">

`next-i18next` is built as commonjs, which in turn uses a commonjs variant of `core-js`. On the other hand, the polyfills I mention in my app's js modules, resolve into a different variant and this is how two copies of `core-js` end up in the bundle.

**Comment by isaachinman** [comment]
I think we should reopen #129, and figure out how to properly transpile our source without relying on runtime polyfills.

@kachkaev @capellini Thoughts?

**Comment by kachkaev** [comment]
How about transpiling to `esnext` and `commonjs`? The former will be used on the client and the latter will be used on the server side. I'm not very experienced in compiling libraries to multiple targets, so my suggestion can be just garbage 😅

**Comment by kachkaev** [comment]
Actually, what will happen if `core-js` and `@babel/preset-env` are simply removed? All worked before v0.19, the only issue was IE11 (https://github.com/isaachinman/next-i18next/issues/107). As I said earlier, polyfilling for that browser can be done on the app level rather than when building the library.

**Comment by capellini** [comment]
> polyfilling for that browser can be done on the app level rather than when building the library

I agree.  I think that polyfilling and determining what browsers to support should be made at the app-level.

**Comment by kachkaev** [comment]
> In general I do want to expose at least the option of using the distributed source of this package directly in a browser without needing a build pipeline. It's just good practice.


This library is Next.js specific, so I can’t imagine a use case when there is no build pipeline (ie `next build`).

**Comment by isaachinman** [comment]
Sorry, wasn't the entire point of your problem that you were not transpiling deps to an IE11 target in your build step?

**Comment by isaachinman** [comment]
Fixed with 4bf9d37. Hoping to release this at the same time as the `rollup` work so that there won't be a lapse in ES5 support.
