### ISSUE TITLE
Warning: Text content did not match. Server: "title" Client: "Hello World"

### ISSUE THREAD

**Issue by aquelegustavo** [isaachinman/next-i18next#1521]
Hi guys, how are you? Could someone help me?

## Describe the bug
The i18n system works perfectly fine, but the error "Warning: Text content did not match." appears when rendering.

## Occurs in next-i18next version
^9.0.0

## Steps to reproduce
index.ts
```ts

import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import { GetStaticProps, GetStaticPropsContext } from "next";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';



const Home: NextPage = () => {
  const { t } = useTranslation('common');

  return (
    <div>
     {t('title')}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (ctx : GetStaticPropsContext) => {
  console.log(ctx)
  // => { locales: [ 'pt-BR', 'es', 'en' ],  locale: 'pt-BR', defaultLocale: 'pt-BR }

  return {
    props: {
      ...(await serverSideTranslations( ctx.locale ?? "pt-BR", ['common'])),
    },
    revalidate: 60 * 60 * 24, // 24 hours
  };
}

export default Home;
```
app.ts
```ts
import '../styles/jam/globals.scss'
import type { AppProps } from 'next/app'
import { appWithTranslation } from 'next-i18next';


function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />
}

export default appWithTranslation(App)
```
next.config.js
```js
const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
  reactStrictMode: true,
}
```
next-i18next.config.js
```js
module.exports = {
  i18n: {
    defaultLocale: 'pt-BR',
    locales: ['pt-BR', 'es', 'en'],
  },
}
```
## Expected behaviour
I would like this problem to go away

## Screenshots
Application working in english language but error being triggered:
![Captura de Tela 2021-11-14 às 11 20 08](https://user-images.githubusercontent.com/36718581/141685080-f5580e1e-8318-4ee9-9140-a9e34d053c28.png)

Application working in portuguese language but error being triggered:
![Captura de Tela 2021-11-14 às 11 20 24](https://user-images.githubusercontent.com/36718581/141685095-7305bf9c-70f8-49a2-9d85-68114f3f507c.png)

## OS (please complete the following information)
 - Device: MacBook Air (11-inch, Early 2015), macOS Monterey
 - Browser: Chrome Version 95.0.4638.69 (Versão oficial) (x86_64)

**Comment by aquelegustavo** [comment]
Also, a message "You will need to pass in an i18next instance by using initReactI18next" appears at server startup. It only appears once, and never again.

```js
yarn run v1.22.17
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled successfully in 4.9s (219 modules)
wait  - compiling /...
event - compiled successfully in 514 ms (224 modules)
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```

**Comment by isaachinman** [comment]
Can you provide a reproducible repo?

**Comment by mprandot** [comment]
@isaachinman why did you close it after one day? I have the same problem.
To me, the message was not being translated.

@aquelegustavo do you fix this problem in your project?

**Comment by aquelegustavo** [comment]
Hi,

Sorry for not giving an answer. Unfortunately, for legal reasons, I cannot provide a reproducible repository.

I fix the problem, but I have no ideia how. I just decided to go back to a code version without the library installed and, then, start all over again and then magically the error message disappeared.

Sorry I can't help more :(

But, anyway, good luck!

**Comment by aquelegustavo** [comment]
I've compared my project's branches, and see if any of the solutions below solve your problem:

next-i18next.config.js
```js

console.log(process.env.NODE_ENV);

module.exports = {
    i18n: {
      defaultLocale: 'pt-BR',
      locales: ['pt-BR', 'es', 'en'],
    },
    reloadOnPrerender: process.env.NODE_ENV == "development"
  };
  
  ````
  
  next.config.js
  ```js
  const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
  reactStrictMode: true,
}
```

index,ts (props)
```js

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "pt-BR", [
        "index",
      ])),
    },
    // revalidate: 60 * 60 * 24 // Try to remove revalidate
  };
};
```

**Comment by isaachinman** [comment]
@mprandot We'll need a minimal repository in which we can reproduce the issue.

**Comment by lilonghe** [comment]
I got the same error and resolve it, hope it helps someone in the back.
`Warning: Text content did not match. Server: "Welcome" Client: "title"`

[demo repo](https://github.com/lilonghe/experiment/blob/1178ce2efbf02f6afd9ce36da4b575939bdc277c/react/ssr/next-js/src/pages/index.js)
bad:
```
...(await serverSideTranslations(locale, [])),
```

good:
```
...(await serverSideTranslations(locale)),
```
---
I found this description at readme, but i do not understand what's meaning.   
I think the render both server and client, their status should be the same.
> To do that, you can pass an array of required namespaces for each page into serverSideTranslations. You can see this approach in [examples/simple/pages/index.js](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js). Passing in an empty array of required namespaces will send no namespaces.

**Comment by lvfxbr** [comment]
I discovered some evidence between locales with dash (pt-br) and locales without dash (ptbr). In the first case, triggers the error of this issue and the second one work without problem. I don't know why it happens, maybe a bug of Next.js or this repository. Here is the link that show what triggers the error:

https://github.com/lvfxbr/lab/commits/next-i18next-2

PS.: Still investigating what causes the issue. If someone discover too, please post here.

**Comment by isaachinman** [comment]
@olafurns7 Those are invalid locales. Try `en-US` and `en-GB`.

**Comment by george-hong** [comment]
> I got the same error and resolve it, hope it helps someone in the back. `Warning: Text content did not match. Server: "Welcome" Client: "title"`
> 
> [demo repo](https://github.com/lilonghe/experiment/blob/1178ce2efbf02f6afd9ce36da4b575939bdc277c/react/ssr/next-js/src/pages/index.js) bad:
> 
> ```
> ...(await serverSideTranslations(locale, [])),
> ```
> 
> good:
> 
> ```
> ...(await serverSideTranslations(locale)),
> ```
> 
> I found this description at readme, but i do not understand what's meaning. I think the render both server and client, their status should be the same.
> 
> > To do that, you can pass an array of required namespaces for each page into serverSideTranslations. You can see this approach in [examples/simple/pages/index.js](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js). Passing in an empty array of required namespaces will send no namespaces.

Thank you, I fix my problom with your comment.
I think this issue was caused by that we pass the incorrect translation module name.

**Comment by bublinec** [comment]
In my case, I was importing useTranslation from **`react-i18next`** instead of **`next-i18next`**

**Comment by that-one-arab** [comment]
> In my case, I was importing useTranslation from **`react-i18next`** instead of **`next-i18next`**

This was the fix.

**Comment by george-hong** [comment]
您好，本人在上学，放假后将会尽快与您联系！

**Comment by RidaEn-nasry** [comment]
can anyone please explain why/how @bublinec is the fix?

**Comment by george-hong** [comment]
您好，本人在上学，放假后将会尽快与您联系！

**Comment by stephenndegwa** [comment]
I resolved the issue by capitalizing the country codes in the locale identifiers. In the locales array, I used uppercase country codes, like this:

`const path = require('path');

module.exports = {
  i18n: {
    locales: ['en-KE', 'fr-RW', 'en', 'fr'], // Defined locales with uppercase country codes
    defaultLocale: 'en-KE', // Set default locale
    localeDetection: false, // Disabled automatic locale detection
    localePath: path.resolve('./src/locales'), // Path to translation files
  },
};
`

**Comment by george-hong** [comment]
您好，本人在上学，放假后将会尽快与您联系！
