### ISSUE TITLE
requiredNamespaces not recognized after navigation

### ISSUE THREAD

**Issue by MelleB** [isaachinman/next-i18next#153]
## Describe the bug
After upgrading from v0.16 to v0.25 I'm receiving errors that the `requiredNamespaces` array is not set in the initial props.

This error does not occur on the initial page load, but only happens after I click a link within the app. I notice in the Network inspector that the `common.json` namespace file is being sent before the page, while the other namespaces are not. 

The exact error (note component name!)
```
You have not declared a namespacesRequired array on your page-level comp  onent: Connect(LoadNamespace(MyPageComponent)). This will cause all name  spaces to be sent down to the client, possibly negatively impacting the perfor  mance of your app. For more info, see: https://github.com/isaachinman/next-i18  next#4-declaring-namespace-dependencies
```

`MyPageComponent` is a React-component which extends a `BasePage` component. This component has a `getInitialProps` method which defines the `namespacesRequired` array. 

My config: (I've tried a bunch of things here :D)
```
{
    lng: 'nl',
    defaultLanguage: 'nl',
    otherLanguages: ['en', 'nl'],
    fallbackLng: 'nl',
    ignoreRoutes: ['/_next', '/static'],
    localePath: 'client/static/locales',
    serverLanguageDetection: false,
    browserLanguageDetection: false
}
```

`getInitialProps` as defined in `BasePage` Component:
```
class BasePage extends Component {

  static async getInitialProps(ctx) {
    
    // For next-i18next:
    const namespacesRequired = ['common', 'header', 'footer']

    return { namespacesRequired }
  }
}
```

## Expected behaviour
I'd expect this warning not to be there.

## Occurs in next-i18next version
`v0.25.0`

**Comment by isaachinman** [comment]
Closing due to lack of response. Happy to reopen if you can provide steps to reproduce.
