### ISSUE TITLE
not able to get value using key in t('')

### ISSUE THREAD

**Issue by JoaoOxOc** [isaachinman/next-i18next#1534]
## Describe the bug
I'm trying to use next-i18next, but the function t('') instead of returning the value from the json file, it returns the key itself.
Code:
```
`import Dropdown from 'react-bootstrap/Dropdown';
import LanguageSelector from './language-selector';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';
import { IoSettingsOutline } from 'react-icons/io5';

export async function getStaticProps({locale}) {
    console.log(locale);
    return {
        props: {
            ...(await serverSideTranslations(locale, ["header"]))
        }
    }
}

///https://app.i18nexus.com/
export default function ProfileDropdown(props) {
    const { t } = useTranslation();

    console.log(t("profile-menu"),props);

   return (
        <Dropdown style={{'margin-left': 'auto', 'margin-right': '10px'}}>
            <Dropdown.Toggle variant="success" id="dropdown-basic">
                <IoSettingsOutline/> {t("profile-menu")}
            </Dropdown.Toggle>

            <Dropdown.Menu>
                <LanguageSelector/>
                <Dropdown.Divider/>
                <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
            </Dropdown.Menu>
        </Dropdown>
    );
}
`
```

## Occurs in next-i18next version
Using version 9.1.0

## Steps to reproduce
Just do the initial setup and try to use translations

## Expected behaviour
I should see the label translated, not the key

## Screenshots
![image](https://user-images.githubusercontent.com/13114921/142617834-f3ac46da-e3b9-4f30-a6f8-c1dd95ae652b.png)

## OS (please complete the following information)
 - Windows 10
 - Chrome

**Comment by isaachinman** [comment]
You will need to provide a reproducible repository.

**Comment by JoaoOxOc** [comment]
@isaachinman sent you an invite for the repository, please use develop branch

**Comment by isaachinman** [comment]
@JoaoOxOc It will need to be a public repository, and it will need to be as minimal as possible.

**Comment by JoaoOxOc** [comment]
@isaachinman public repository (use develop branch): https://github.com/JoaoOxOc/cooperativa-website

**Comment by isaachinman** [comment]
It will need to be as minimal as possible.

**Comment by JoaoOxOc** [comment]
@isaachinman use this with a minimum installation: https://github.com/JoaoOxOc/react-i18n
I set the translation on components/head.js file

also, can you attach a link please on how to change the language? On an older version I was using i18n.changeLanguage() function, but now I can't use it/don't know how to

**Comment by isaachinman** [comment]
You are not using `serverSideTranslations` in [this file](https://github.com/JoaoOxOc/react-i18n/blob/main/pages/index.js). Please read the documentation carefully.

> also, can you attach a link please on how to change the language?

[Sure.](https://nextjs.org/docs/advanced-features/i18n-routing#transition-between-locales)

**Comment by JoaoOxOc** [comment]
@isaachinman now I got it, so serverSideTranslations is always at the pages right? So if I have multiple components using different locale files, do I have to declare all of them in serverSideTranslations of the page?
now I'm getting a new error: `Error: next-i18next was unable to find a user config`

**Comment by isaachinman** [comment]
Your config file is named incorrectly. It needs to be `next-i18next.config.js`. Please read the documentation carefully.

**Comment by JoaoOxOc** [comment]
never thought the name should be exactly like the documentation. Thank you so much for all your help
