### ISSUE TITLE
i18next formatters not applied to translation values

### ISSUE THREAD

**Issue by jacknevitt** [isaachinman/next-i18next#1535]
## Describe the bug
Unable to format translations with built in i18next formatters (currency, number etc)

## Occurs in next-i18next version
`9.1.0`

## Steps to reproduce
Example Repo: https://github.com/jacknevitt/next-i18next-no-format

## Expected behaviour
Translations with formats provided will display the translation with formatter applied. In the above repo, I expect to see "123" as "£123.00" for EN (GBP) and "123" as "€123.00" for DE (EUR).

## Screenshots
Not applicable

## OS (please complete the following information)
 - Device: MBP 2019 16"
 - Browser: Chrome 96.0.4664.55

## Additional context
There is no mention of formatters on the main readme for next-i18next. See https://www.i18next.com/translation-function/formatting#built-in-formats for i18next documentation.

**Comment by isaachinman** [comment]
@adrai Any ideas on this one?

**Comment by adrai** [comment]
the default formatting is probably not working, because the legacy format function is still used here: https://github.com/isaachinman/next-i18next/blob/93d4f88b96b385bb5a5eea9eb327d87b3b0c06df/src/config/defaultConfig.ts#L20

**Comment by jacknevitt** [comment]
Thanks for the quick reply. Can the i18next built-in formatters be imported here? Is `appWithTranslation` the best place to add my own in the meantime?
I'm assuming I can't add my own the way described in the i18next docs https://www.i18next.com/translation-function/formatting#adding-custom-format-function?
Thanks

**Comment by adrai** [comment]
https://codesandbox.io/s/react-i18next-example-forked-ycwbo?file=/src/i18n.js:1480-1567

**Comment by isaachinman** [comment]
@jacknevitt You should be able to pass your own `interpolation.format` via `next-i18next.config`. Let me know if you have any issues 👍 

@adrai Would you recommend changing that line in `defaultConfig`? I honestly do not remember why it's set that way.

**Comment by adrai** [comment]
> @adrai Would you recommend changing that line in `defaultConfig`? I honestly do not remember why it's set that way.

I would remove that line, this way the default formats would work and in user code you can choose to use the new or the legacy formatting api...

**Comment by dnbastos** [comment]
I still had doubts to add custom format functions and keep the new built-in functions, because the new formatting api can not be used when `interpolation.format` option is used.

In the i18next docs, it is described to add custom functions after `i18next.init(options)`. But with next-i18next we don't call `i18next.init()`, so we don't have access to the i18next instance in the `next-i18next.config` file.

So I'm not sure where is the ideal place to add my own functions.

**Comment by adrai** [comment]
> I still had doubts to add custom format functions and keep the new built-in functions, because the new formatting api can not be used when `interpolation.format` option is used.
> 
> In the i18next docs, it is described to add custom functions after `i18next.init(options)`. But with next-i18next we don't call `i18next.init()`, so we don't have access to the i18next instance in the `next-i18next.config` file.
> 
> So I'm not sure where is the ideal place to add my own functions.

If there is no possibility to access the i18next instance after init, there's a workaround using plugins, like this:

```js
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  serializeConfig: false,
  use: [{
    init: (i18next) => {
      i18next.services.formatter.add('lowercase', (value) => value.toLowerCase())
    },
    type: '3rdParty',
  }],
}
```

But then the config is not serializable anymore and you need to pass it in...

**Comment by natterstefan** [comment]
Hi @adrai @isaachinman,

I know this issue is closed, but I don't see how one can add custom formatters like the one @adrai posted in the last comment above:

```js
i18next.services.formatter.add('lowercase', (value) => value.toLowerCase())
```

How can one do that now?

**Comment by adrai** [comment]
Like said in my previous comment, currently the only way to do so is adding a special 3rdParty plugin in the use array:
```js
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  serializeConfig: false,
  use: [{
    init: (i18next) => {
      i18next.services.formatter.add('lowercase', (value) => value.toLowerCase())
    },
    type: '3rdParty',
  }],
}
```

and make sure the next-i18next.config is passed, like described here: https://github.com/isaachinman/next-i18next#unserialisable-configs

**Comment by natterstefan** [comment]
Thanks for your help @adrai. I appreciate it and will try it.

**Comment by sunknudsen** [comment]
@adrai Thanks for helping out! How do we call `t` to leverage plugin? `t("foo", { format: "lowercase" })` doesn’t appear to work.

**Comment by adrai** [comment]
> @adrai Thanks for helping out! How do we call `t` to leverage plugin? `t("foo", { format: "lowercase" })` doesn’t appear to work.

// having this key in the translations:
// "foo": "my translation {{someVal, lowercase}}"
t("foo", { someVal: 'TEST' }) // my translation test

https://www.i18next.com/translation-function/formatting

**Comment by sunknudsen** [comment]
@adrai Trying to solve for following use case… how can one set first letter of translations to uppercase using custom plugin (or any other way that applies to all translations) so that one doesn’t have to create multiple contextualized versions of translations. Possible? I believe docs doesn’t cover this use case.

**Comment by adrai** [comment]
A formatter only formats the interpolated value (https://www.i18next.com/translation-function/interpolation), like described here: https://www.i18next.com/translation-function/formatting#basic-usage

So you don't want to format your interpolated values, but you want all your translations to all start capitalized?
Just change your translations then... that's the fastest and simplest way.


Alternatively (not recommended), you can create your custom post-processor: https://www.i18next.com/overview/plugins-and-utils#post-processors => https://www.i18next.com/misc/creating-own-plugins#post-processor
Here an example of a postProcessor: https://github.com/i18next/i18next-emoji-postprocessor

Something like this:

```js
const defaultLocale = /** @type {"en" | "fr"} */ ("fr")
const locales = /** @type {(typeof defaultLocale)[]} */ (["en", "fr"])

const capitalizeFirstLetter = (value, language) => {
  const firstLetter = value.charAt(0).toLocaleUpperCase(language)
  const restOfString = value.slice(1)
  return `${firstLetter}${restOfString}`
}

module.exports = {
  i18n: {
    defaultLocale: defaultLocale,
    locales: locales,
  },
  reloadOnPrerender: process.env.NODE_ENV === "development",
  serializeConfig: false,
  postProcess: 'capitalizer',
  postProcessPassResolved: true,
  use: [
    {
      name: 'capitalizer',
      type: 'postProcessor',

      options: {},

      setOptions (options) {},

      process (value, key, options) {
        capitalizeFirstLetter(value, options. i18nResolved.usedLng)
      },

      overloadTranslationOptionHandler (args) {
        return {
          postProcess: 'capitalizer'
        }
      }
    },
  ],
}
```

**Comment by sunknudsen** [comment]
First, thanks so much for helping out.

> So you don't want to format your interpolated values, but you want all your translations to all start capitalized?

Only when needed… for example, say one has the following translation.

```json
{
  "topic": "topic",
}
```

One might use word “topic” at the beginning of sentence or not… when at the beginning of sentence, “topic” should be “Topic”.

Trying to avoid managing two translations for the same word only because I sometime need first letter to be capitalized.

I was hoping there was a way to handle this programatically.

**Comment by adrai** [comment]
> Why is this not recommended?

Complicated solution for something that can be solved in your code...
Honestly, I would prefer to maintain 2 separate translations, or capitalize directly in your code where needed... but you can for sure also try with the postprocessor approach

**Comment by sunknudsen** [comment]
@adrai How does one use `capitalizer`? I believe this is not explained in [docs](https://www.i18next.com/misc/creating-own-plugins#post-processor).

**Comment by sunknudsen** [comment]
Figured it out… `t("hello", { postProcess: "capitalizer" })`

**Comment by adrai** [comment]
make sure you set these 2 options:

```
postProcess: 'capitalizer', // enables t("hello") without having to pass: t("hello", { postProcess: "capitalizer" })
postProcessPassResolved: true, // will inject i18nResolved via options
```

**Comment by sunknudsen** [comment]
Last question… and thanks again… you have been so helpful!

Is it bad practice to use post processors in Next.js app? Asking given you mentioned option was not recommended… are there performance trade-offs for example?

If not, what powerful feature!

**Comment by adrai** [comment]
never used a postprocessor in Next.js directy, but there should be no extra trade-off
