### ISSUE TITLE
Default config is not serializeable 

### ISSUE THREAD

**Issue by sbekrin** [isaachinman/next-i18next#1537]
## Describe the bug
Hey there! After a recent version bump of next-i18next I've noticed that the [default config](https://github.com/isaachinman/next-i18next/blob/master/src/config/defaultConfig.ts#L20) contains non-serializable `interpolation.format` making the `userConfig` autoloading setup unusable/obsolete.

## Occurs in next-i18next version
Since v8.0.0

## Steps to reproduce
Setup a new next.js project with next-i18next using its defaults.

## Expected behaviour
The default config is either is serializable out-of-box, or the API and docs imply that `userConfig` is mandatory for `appWithTranslation`.

**Comment by isaachinman** [comment]
The [example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple) composes off the default config, and does not have any serialisation errors.

Do you mind explaining exactly what issue you are facing?

Could be related to: https://github.com/isaachinman/next-i18next/issues/1535#issuecomment-974094030

**Comment by sbekrin** [comment]
@isaachinman ah good catch, it happens _only_ if `interpolation` config is provided, [here's the minimal repro.](https://github.com/sbekrin/next-i18next-interpolation-prop-bug/blob/main/next-i18next.config.js#L7) if it helps. probably a long shot but could this be a merging issue or smh?

**Comment by isaachinman** [comment]
That's really strange – why would providing an empty object result in `interpolation.format` being populated?

**Comment by isaachinman** [comment]
Had some time to look into this issue this morning.

This is indeed somewhat related to #1535, but is mostly a deep reference issue – if you replace the default value of [`interpolation`](https://github.com/isaachinman/next-i18next/blob/master/src/config/defaultConfig.ts#L18) with an empty object, `i18next` will mutate that nested object reference to _its_ default `format` function, [when we call `i18n.createInstance`](https://github.com/isaachinman/next-i18next/blob/master/src/createClient/node.ts#L11).

cc @adrai – we need a deep clone at some point. Do you think it belongs on the i18next side, or the end user side?

**Comment by adrai** [comment]
> cc @adrai – we need a deep clone at some point. Do you think it belongs on the i18next side, or the end user side?

I have not checked that right now, but it may be this would be solved, if the interpolation option would be cloned here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L68

**Comment by isaachinman** [comment]
Yes you could manually clone the nested `interpolation` object there, but you'll hit other nested reference issues in the future unless you grab something like [`clone-deep`](https://www.npmjs.com/package/clone-deep) (or implement it yourself).

**Comment by adrai** [comment]
i18next v21.5.3 should fix this

**Comment by isaachinman** [comment]
Thanks @adrai!

**Comment by sbekrin** [comment]
@isaachinman @adrai thank you both!
