### ISSUE TITLE
Critical dependency warning when compiling NextJS pages

### ISSUE THREAD

**Issue by azuken** [isaachinman/next-i18next#1545]
## Describe the bug
When NextJS is compiling pages on the fly, console shows a warning : 

```
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
```

next-i18next is still working, but log is spamming, and maybe it will break with future NextJS updates ?

## Occurs in next-i18next version
"next-i18next": "^9.1.0"

## Steps to reproduce
NextJS project with version 12.0.4

## Expected behaviour
No warning

## OS (please complete the following information)
 - Device: MBP 2019 16
 - Browser: Chrome 96.0.4664.55

**Comment by isaachinman** [comment]
Do you have a line that the error points to?

**Comment by azuken** [comment]
Unfortunately, no...

Here is an example of usage, when I'm doing some modifications in code : 

```
/usr/local/bin/node /usr/local/Cellar/yarn/1.22.17/libexec/bin/yarn.js run dev
yarn run v1.22.17
$ yarn run build:css && next
$ postcss src/styles/index.css -o public/next/tailwind.css
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/XXXXXXXXXX/.env
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling /...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling /...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling /_error (client only)...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
wait  - compiling...
warn  - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Critical dependency: the request of a dependency is an expression
```

**Comment by isaachinman** [comment]
That error typically means a module/import did not resolve. Can you provide a minimal repro?

**Comment by azuken** [comment]
Here is a clean sample of my project : 
[repro.zip](https://github.com/isaachinman/next-i18next/files/7594241/repro.zip)

But warning is not here. Is there a required dependency for this library ?

**Comment by isaachinman** [comment]
There are no required dependencies besides `react` and `next`.

**Comment by azuken** [comment]
Ok, so I will search further more, and come back to share what I found !

**Comment by junhoyeo** [comment]
My temporary workaround to suppress this annoying warning is to set `module.exprContextCritical` to `false` at webpack config:

```tsx
// next.config.js
module.exports = {
  i18n,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve = {
        ...config.resolve,
        fallback: {
          ...config.resolve.fallback,
          fs: false,
        },
      };
    }
    (...)
    config.module = {
      ...config.module,
      exprContextCritical: false,
    };
    return config;
  },
  (...)
}
```

**Comment by azuken** [comment]
> 

It works, but it seems to be more a workaround than a solution. It would be great to have a real explanation of this warning !

**Comment by isaachinman** [comment]
> It would be great to have a real explanation of this warning

As I stated, it's normally due to a broken import somewhere. To debug the issue, we will need a reproducible repository.

**Comment by coder6583** [comment]
In my case this warning was caused because I was calling serverSideTranslations inside a file that is not in the pages folder.

**Comment by blackblue2712** [comment]
Any update, In my case this problem cause hard reload when  I navigate to other page

**Comment by sunknudsen** [comment]
> In my case this warning was caused because I was calling serverSideTranslations inside a file that is not in the pages folder.

@coder6583 Did you ever manage to find a workaround to use `serverSideTranslations` in components outside of pages directory?

**Comment by adamtowle** [comment]
> > In my case this warning was caused because I was calling serverSideTranslations inside a file that is not in the pages folder.
> 
> @coder6583 Did you ever manage to find a workaround to use `serverSideTranslations` in components outside of pages directory?

Correct me if I am wrong but it's okay to import the module in a file that isn't in the pages directory, for us the issue was caused by a barrel file of exports which contained modules for both the server and client, as a result the module was imported implicitly in the client.

The warning went away when we moved the module into it's own file and imported it directly in our pages.

See: https://github.com/i18next/next-i18next#serversidetranslations
> Note that serverSideTranslations must be imported from next-i18next/serverSideTranslations – this is a separate module that contains NodeJs-specific code.

**Comment by j4tmr** [comment]
> My temporary workaround to suppress this annoying warning is to set `module.exprContextCritical` to `false` at webpack config:
> 
> ```tsx
> // next.config.js
> module.exports = {
>   i18n,
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.resolve = {
>         ...config.resolve,
>         fallback: {
>           ...config.resolve.fallback,
>           fs: false,
>         },
>       };
>     }
>     (...)
>     config.module = {
>       ...config.module,
>       exprContextCritical: false,
>     };
>     return config;
>   },
>   (...)
> }
> ```

too dirty
