### ISSUE TITLE
migration v6 to v9

### ISSUE THREAD

**Issue by kyun** [isaachinman/next-i18next#1547]
I am struggling with migration v6 to v9.

There are big changes so I can not follow up on the changes. 

I was using 
`export const { appWithTranslation, withTranslation, i18n, Link, useTranslation, Router } = nextI18NextInstance;` 
in my `i18n.ts`.
But in v9 it is used no more. 

I have found `{ appWithTranslation, withTranslation, useTranslation } from 'next-i18next'`,
but I couldn't find `{ Link, Router, i18n}`. 

And, I was using `const { nextI18NextRewrites } = require('next-i18next/rewrites');` but it also gone somewhere.

I can find only [migration guide v7 to v8](https://github.com/isaachinman/next-i18next/blob/master/docs/v8-migration.md). 
but it doesn't fit on me perfectly.

If there is a guide v6 to v7, it must be helpful to me.

**Comment by isaachinman** [comment]
The changes which you describe are between v7 and v8, and should be handled by the existing migration guide. There is no longer any `Link` or `Router` export. There _is_ still an `i18n` export.

Let me know if you have any other questions.

**Comment by kyun** [comment]
@isaachinman Thank you for your kind answer. :) 
My project is still using `Link` and `Router`, what can I replace them to?
and also I want to know about `nextI18NextRewrites`.

**Comment by isaachinman** [comment]
`nextI18NextRewrites` is no longer necessary. Please read the [NextJs documentation](https://nextjs.org/docs/advanced-features/i18n-routing) for `Link` and `Router` replacements.
