### ISSUE TITLE
UseContext error caused by changing language

### ISSUE THREAD

**Issue by JasonLamv-t** [isaachinman/next-i18next#1549]
## Describe the bug
On some pages, I use 'useContext' for caching data. And if change language via `<Link>`, it would not refresh the page totally so the page will break because the URL changed makes useContext invalid.

## Occurs in next-i18next version
I think it will happen in most versions.

## Steps to reproduce
Use some URL dependented hook and change language via `<Link>`.

## Expected behavior
The language of the website will be changed and everything works well.

## Solution
Using `<a>` instead of `<Link>`:
```ts
<a
  href={
    router.locale === 'zh'
      ? '/en' + router.asPath
      : router.asPath
  }
>
  switch language
</a>
```

## Additional context
This issue was released for others to provide ideas for others to solve problems that may arise for the same reason.
It can be closed immediately.

**Comment by isaachinman** [comment]
Hi @JasonLamv-t. Not sure I understand your point entirely, but `next-i18next` doesn't handle routing or navigation at all anymore, so if anything, this issue is probably best suited for the main NextJs repo. Thanks!
