### ISSUE TITLE
Change function signature for lngPathCorrector

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#155]
## Is your feature request related to a problem? Please describe.
1. Currently, the `lngPathCorrector` receives as an argument, the `i18n` object which is used only to determine a default argument for language.  However, I don't think that there's an instance where we don't know the right language to pass into `lngPathCorrector` and, in some cases (e.g. `Link`), it's better to use the `lng` prop anyway.
2. Also, the `lngPathCorrector` takes in an object with an `as` string and an `href` object, but we could easily change this to be more user-friendly by taking in an `href` object or string and, optionally, an `as` string.  If the `as` string is not provided, we can determine what it is from the `href` string/object.  Currently, we do this, but the logic for doing so is not perfomed within `lngPathCorrector` but, instead, is done in `Link`  and `appWithTranslation`.  But I think the logic belongs inside the `lngPathCorrector`.

## Describe the solution you'd like
1. Make the language a required parameter and remove the need to pass in `i18n`.
2. Have `lngPathCorrector` take in an object with the `href` string or object and, optionally, the `as` string and perform any necessary steps needed to just return the corrected `as` string and `href` object.

## Describe alternatives you've considered
We could keep things the way they are, but it's better to keep all of the logic inside of `lngPathCorrector`.  Also, should we decide someday to expose this function, it's easier to use in the proposed form.

## Additional context
N/A

**Comment by capellini** [comment]
This would also prevent bugs like the one pointed out [with passing the `href` prop into `NextRouter` here](https://github.com/isaachinman/next-i18next/pull/150#issuecomment-460381854).  All the user would get is an `as` and `href` that they are safe to pass on to `next` via `next`'s `Link`, `Router`, etc.

**Comment by isaachinman** [comment]
My main worry with the first item is that future contributors _won't_ know where to get the correct lang from. Using `i18n.languages[0]` is wrong in many cases.

The second item seems more logistical and does not affect core logic as much. Please post the exact function signature (preferably with typing) here, so I can see your actual proposal.

**Comment by capellini** [comment]
> Using `i18n.languages[0]` is wrong in many cases

This adds even more credence to removing the `i18n` argument entirely.

> Please post the exact function signature (preferably with typing) here, so I can see your actual proposal.

```js
lngPathCorrector(
  config: object,
  { href: object | string, as?: string },
  language: string
): [string, object]
```
Or, if you prefer to return an object that can more easily be destructured for greater code clarity:
```js
lngPathCorrector(
  config: object,
  { href: object | string, as?: string },
  language: string
): { as: string, href: object }
```

**Comment by isaachinman** [comment]
Yes, much better to return an object than an array. What is `config`? Is that a `next-i18next` config object?

**Comment by capellini** [comment]
> Yes, much better to return an object than an array.

Agreed.

> What is `config`? Is that a `next-i18next` config object?

Yes.  I suppose a more accurate signature would be:
```js
lngPathCorrector(
  { defaultLanguage: string, allLanguages: string[] },
  { href: object | string, as?: string },
  language: string
): { as: string, href: object }
```

**Comment by isaachinman** [comment]
@capellini Yes, that signature looks great to me. I'd accept a PR with those changes. We'd need to be careful about not introducing any regressions.
