### ISSUE TITLE
How to use next-i18next with SPA-rendered pages?

### ISSUE THREAD

**Issue by EfrainRodriguez** [isaachinman/next-i18next#1550]
## Is your feature request related to a problem? Please describe.
I have tried adding translation to a Nextjs app. It works with SSG and SSR pages/components, however it dont works with SPA-rendered components.

## Describe the solution you'd like
Configuration to support non-SSG or SSR pages/components.

## Describe alternatives you've considered
I tried using the configuration given in the documentation.

## Additional context
...

**Comment by isaachinman** [comment]
Can you explain what you mean by "SPA-rendered"? This package works via `getStaticProps`/`getServerSideProps` and is agnostic of how you render your app.

**Comment by EfrainRodriguez** [comment]
In my application I have some pages that do not use getStaticProps or getServeSideProps. In those pages the translations do not work.

**Comment by isaachinman** [comment]
That would be correct, yes. We rely on those data fetching methods to pass the actual translation content into your app in the first place.
