### ISSUE TITLE
getting 'header.user_area.my_profile' instead of its value 'My Profile' while in another page

### ISSUE THREAD

**Issue by murlipillamari** [isaachinman/next-i18next#1551]
## Describe the bug
Getting 'header.user_area.my_profile' instead of its value 'My Profile' while on another page, it was working on home page , but while navigate to another page and uses same navigation links , its not working on another page
## Occurs in next-i18next version
 "next-i18next": "^9.1.0",

## Steps to reproduce
detaileView.tsx
import { useTranslation } from 'next-i18next';
//some code
  const { t } = useTranslation('common');
//some code
              Total Amounttt -{t('header.user_info.my_orders')}-:

## Expected behaviour
it shou show "My Profile" value instead of its  'header.user_area.my_profile' 

## Screenshots
![image](https://user-images.githubusercontent.com/90892610/143765945-d2f624e3-07b9-4c14-8edc-92f1c5630fbc.png)

## OS (please complete the following information)
 - Lenovo(windows 10)
 - Brave Browser

**Comment by isaachinman** [comment]
You will need to provide a minimal repository in which we can reproduce the issue.

**Comment by murlipillamari** [comment]
> You will need to provide a minimal repository in which we can reproduce the issue.

Thank you for your concern, I got the solution , actually I need to use getStaticProps method in each page wherever we need to translate the page.
