### ISSUE TITLE
broken rendering when using @azure/msal-react

### ISSUE THREAD

**Issue by igorovic** [isaachinman/next-i18next#1560]
## Describe the bug
The function `appWithTranslation` breaks the rendering of components provided by the microsoft authentication lib: `@azure/msal-react`.

## Occurs in next-i18next version
9.2.0

## Steps to reproduce
here is the reproduction repo. 
[https://github.com/igorovic/msal-issue-1560](https://github.com/igorovic/msal-issue-1560)

## Expected behaviour
The components should render after the navigation.

## OS (please complete the following information)
 - Device: [e.g. MBP 2019 16"]
 - Browser: Chrome@latest, Firefox@latest

If I remove `appWithTranslation` rendering is working properly. So I assume there is a conflict with @azure/msal-react and next-18next.

**Comment by igorovic** [comment]
I was able to workaround this issue with this code. If someone needs it.

```_app.tsx
function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

const App2 = appWithTranslation(MyApp);

function MsalApp(props: AppProps) {
  const router = useRouter();
  const navigationClient = new CustomNavigationClient(router);
  msalInstance.setNavigationClient(navigationClient);
  return (
    <MsalProvider instance={msalInstance}>
      <App2 {...props} />
    </MsalProvider>
  );
}

export default MsalApp;
```

**Comment by isaachinman** [comment]
Thanks @igorovic!
