### ISSUE TITLE
Can anyone guide me about how can I use "t" function in a component which is not a page in Next.js

### ISSUE THREAD

**Issue by ahmedraza11** [isaachinman/next-i18next#1561]
## Is your feature request related to a problem? Please describe.
I saw a method in docs about how I can load translation in a component rather than a page in Next.js but I wondering how can I use this method and show translation to component according to locale:
```
 useEffect(() => {
    i18n.addResourceBundle(locale, 'common');
  }, []);
```

kindly guide me about this.

**Comment by isaachinman** [comment]
I don't think I fully understand your question, but `next-i18next` is not intended to be used in applications/pages which are not in NextJs. Please feel free to post on StackOverflow for further help.

**Comment by petarstojkovski1** [comment]
> @isaachinman how can I use client side translate function when I am using ![image](https://user-images.githubusercontent.com/16984365/144626615-d9276498-dc6a-4e12-9020-af826dbf0ee7.png)

@ahmedraza11 Did you found a solution? I have the same problem, i18n is null in this situation.

**Comment by ahmedraza11** [comment]
Yes, I have found a solution to load locale namespaces manually on client side you can further this issue:
https://github.com/isaachinman/next-i18next/issues/1476#issuecomment-948380040
