### ISSUE TITLE
Localization keys differentiates between browsers

### ISSUE THREAD

**Issue by gunnartorfis** [isaachinman/next-i18next#1565]
## Describe the bug
In our project we currently have three languages, English, Portuguese and Icelandic, ```["en", "pt", "is"]``` as locales. 
When ```localeDetection: true```is set, it seems like Safari processes Icelandic as "is-is" but Google Chrome as "is" (expected). 

I understand this is not related to next-i18next but I thought there was some mechanism that would handle it. It fallbacks to the default language (en) and the same for "pt-PT" where we would like that to fallback to "pt".

Is there some way around this already? If not, what is the easiest way to solve this? The only solution I could figure out was to duplicate the localization folders to include another one called "is-is", "pt-PT", etc but I'm not sure what consequences that would have, especially w.r.t. translations payloads. 

## Occurs in next-i18next version
^9.2.0

## Steps to reproduce
Have an "is" locale, switch Safari to Icelandic to see the default locale take over. Works as expected on Chrome. 

## Expected behaviour
Icelandic should appear although Safari tells "is-is". 

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: MBP 13" M1
 - Browser: Safari 15.0 (16612.1.29.41.4, 16612)

**Comment by isaachinman** [comment]
Locale detection is handled by NextJs directly. Can you please open (or search for) an issue on the main NextJs repo? Thanks!

**Comment by isaachinman** [comment]
Some more info on defining [fallbacks](https://www.i18next.com/principles/fallback#fallback-to-different-languages).
