### ISSUE TITLE
Doesn't work on fresh NextJS installation

### ISSUE THREAD

**Issue by msnegurski** [isaachinman/next-i18next#1584]
## Describe the bug
Doesn't work on fresh NextJS installation and outputs `react-i18next:: You will need to pass in an i18next instance by using initReactI18next` warning to console. Shows translation key instead of translation string, as if this translation did not exist.

## Occurs in next-i18next version
`"next": "12.0.7", "next-i18next": "^10.0.1", "react": "17.0.2", "react-dom": "17.0.2"`

## Steps to reproduce
Repo for reproduction https://github.com/msnegurski/i18n-bug

## Expected behaviour
Proper translation is shown on the page.

## OS (please complete the following information)
 - Device: MBP 2020 13" M1
 - Browser: Chrome 96.0.4664.55

**Comment by msnegurski** [comment]
Something very strange going on here, I have copied setup from examples folder, bumped versions to latest and it works. So problem is somewhere in my setup, but I cannot find anything wrong with it.

I have seen issues here with similar symptoms and console message, so other people encountered this behaviour too.

**Comment by isaachinman** [comment]
You didn't add `serverSideTranslations` to your page. Please follow the documentation carefully.

**Comment by msnegurski** [comment]
Well, this is embarassing. Thank you for help and sorry for wasting your time.
