### ISSUE TITLE
httpOnly attribute of next-i18next cookie.

### ISSUE THREAD

**Issue by Adrianlafontaine** [isaachinman/next-i18next#1587]
I want to enable the httpOnly attribute that is off by default.
I implemented next-i18next with typescript, and I have tried the following configuration:

```
import NextI18Next from 'next-i18next'
import config from 'next/config'
import path from 'path'

const { useTranslation, appWithTranslation, Router } = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['es'],
  localeSubpaths: config().publicRuntimeConfig.localeSubpaths,
  localePath: path.resolve('./public/locales'),
  detection: {
    httpOnly: true,
    cookieSecure: true,
    cookieDomain: 'localhost',
    lookupCookie: 'next-i18next',
  },
})

export { useTranslation, appWithTranslation, Router }
```
This is not working, httpOnly is not getting set:

![image](https://user-images.githubusercontent.com/91551081/146809446-13297897-e771-4ca5-870a-05e74df3e756.png)

Is there a reason why this attribute is set false by default? Another way to managed with this configuration?

Thank you in advance.

**Comment by isaachinman** [comment]
What version of `next-i18next` are you using?

**Comment by Adrianlafontaine** [comment]
My current version is:
 
next-i18next: 7.0.1

**Comment by isaachinman** [comment]
Please upgrade to a recent version for further support.

**Comment by Adrianlafontaine** [comment]
ok, I will update to a recent version. Just one last question, is there a reason why this attribute is set false by default? Does the library needs to have access to that cookie in order to locate the language and do the corresponding translation work?

thank you very much for your response.

**Comment by isaachinman** [comment]
In recent versions, NextJs handles cookie/locale management directly, so `next-i18next` isn't involved at all. Let me know if you have any other questions.
