### ISSUE TITLE
enable "Fake locale" to fix default locale

### ISSUE THREAD

**Issue by kyun** [isaachinman/next-i18next#1601]
## Is your feature request related to a problem? Please describe.
in Next 12, the default locale can be skipped. 
```js
/* next-i18next.config.js */
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ko'],
  }
}
```
And if my browser's first language is English, I can move to `/` and `/en` both.
But I want to make `/` disabled, and I only want to use like `/[locale]`. 
I've found [a tricky way](https://github.com/vercel/next.js/discussions/18419#discussioncomment-327128) but I got a problem.

> error - Error: ENOENT: no such file or directory, scandir '/Users/user1/workspace/my-next-project/public/locales/catchAll'

I could solve this by making a string for `catchAll` but I think it doesn't look good because `catchAll` is a fake locale.

## Describe the solution you'd like
I want to be able to set a fake locale.
```js
/* next-i18next.config.js */
module.exports = {
  i18n: {
    defaultLocale: 'catchAll',
    locales: ['catchAll', 'en', 'ko'],
    fakeLocale: 'catchAll', // I can not of think the proper name for this.
  }
}
```

or

```js
/* next-i18next.config.js */
module.exports = {
  i18n: {
    defaultLocale: 'catchAll',
    locales: ['catchAll', 'en', 'ko'],
    shareLng: {
      'catchAll': 'en', // It looks like `fallbackLng` that is deprecated.
     }
  }
}
```

## Describe alternatives you've considered
:( 

## Additional context
I am sorry about my poor English.

**Comment by isaachinman** [comment]
This sounds like a routing request that should be directed to the NextJs repository directly. Creating fake locales is obviously a workaround, and not something we'd look to support first-class.

**Comment by TheGooner93** [comment]
@kyun were you able to get this to work ?
