### ISSUE TITLE
Latest JSON format breaks TypeScript support

### ISSUE THREAD

**Issue by LukasCornille** [isaachinman/next-i18next#1602]
## Describe the bug
When updating my translations, following [the lastest V4 JSON spec](https://www.i18next.com/translation-function/plurals#singular-plural) regarding plurals, the TypeScript isn't picking this up correctly.

## Occurs in next-i18next version
10.0.1

## Steps to reproduce
In a TS repo, add a translation file with:

```json
{
  "Extra" : {
    "remainingItem_one": "{{count}} item left",
    "remainingItem_other": "{{count}} items left"
  }
}
```

When trying to use the `t()` function this gives an error (see first screenshot).

It also tries to hint me to pick `one` or `other` (see second screenshot).

## Expected behaviour
I would expect it not to give a TS error and IntelliSense to pick this up properly.
I'm working in a project where I'm using react-18next and this works properly (see third screenshot).

## Screenshots

![afbeelding](https://user-images.githubusercontent.com/36887321/147652671-bbe0af28-fd7c-4c77-995d-def7c7538b15.png)

![afbeelding](https://user-images.githubusercontent.com/36887321/147652830-153d303e-6b7d-4e15-9fa1-a50026d64a04.png)

![afbeelding](https://user-images.githubusercontent.com/36887321/147653060-be2b3422-ecbe-48ae-aeec-844898875ff2.png)

## Additional context
I believe updating the dependencies should fix this problem.

**Comment by isaachinman** [comment]
I believe our i18next deps are up to date. Do you mind forcing dependency upgrades via `resolutions` in `package.json`, and let me know if any of those upgrades fix the issue?

**Comment by LukasCornille** [comment]
Bumping to 10.1.0 seemed to have triggered an error on the CI stating my `@ts-expect-error` was no longer required.
When I updated locally, I was able to delete this and confirm everything is working as intended now!
