### ISSUE TITLE
Custom resources doesn't override the initial resources

### ISSUE THREAD

**Issue by rubayethossain** [isaachinman/next-i18next#1603]
https://github.com/isaachinman/next-i18next/blob/4d0132784097b4e15195f2e3b07b7cdac065738a/src/appWithTranslation.tsx#L57

I have been trying to pass `resources` as an override config with `appWithTranslations`. It's not working and on the above reference line it seems like the custom `resources` is override by the `initialI18nStore`. Here how I am trying to do it,

```jsx
const en = {
 about: {
  "title": "About us"
 }
}

const no = {
 about: {
  "title": "Om oss"
 }
}

const configOverride = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'no'],
  },
  resources: {
    en,
    no,
  },
}

// export default MyApp
export default appWithTranslation(MyApp, configOverride)
```

**Comment by isaachinman** [comment]
@rubayethossain Would you be able to work on a PR to fix this issue?

**Comment by rubayethossain** [comment]
Sure @isaachinman . Wondering is there any contribution guideline?

**Comment by isaachinman** [comment]
Yes, [here](https://github.com/isaachinman/next-i18next/blob/master/CONTRIBUTING.md), although it may be a little out of date. Let me know if you have any questions.
