### ISSUE TITLE
can we export  const { t } = useTranslation('common') ?

### ISSUE THREAD

**Issue by murlipillamari** [isaachinman/next-i18next#1612]
i wants to use key in array , which is being exported from somewhere,

here is the array:
export const saleSortArray: ArrayType[] = [
  { id: 1, name: t('component.constants.relevance'), value: '' },
  { id: 2, name: 'discount - low to high', value: 'asc' },
  { id: 3, name: 'discount - high to low', value: 'desc' }
];
in that i want to translate "name" field

## Occurs in next-i18next version
        "next-i18next": "^9.2.0",

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
 i want to translate array field which is already being export from somewhere, so is it possible that i will export t from compoent and will use it on that page where array is being export.

## OS (please complete the following information)
 - WINDOWS 10
 - chrome

**Comment by isaachinman** [comment]
Not sure I understand the question. You can use the `useTranslation` hook anywhere inside your app, including pages.
