### ISSUE TITLE
Docs Question: Loading namespaces dynamically is unclear

### ISSUE THREAD

**Issue by gtothesquare** [isaachinman/next-i18next#1620]
## Describe the bug

Some background:

We are not using the i18n integration with next.js i18n. We actually use the folder structure to load the locale as shown in this image:

![image](https://user-images.githubusercontent.com/370567/149110028-99d85f32-46fb-4986-ab8e-a06a21c27370.png)

So, in the `getStaticProps` `locale` is not populated. We instead get it via `params` like this

```
export const getStaticProps: GetStaticProps<{ metaData: { title: string; description: string }}> = async ({ params }) => {
  const marketSlug = (params?.marketSlug as string) || 'uk';
  const translations = await serverSideTranslations(marketSlug, ['namespace']);
  return {
    props: {
      ...translations,
    },
  };
};
```

This will not work in the 404 custom page because next js renders and serve from /pages and not from the pages path if I got to a url like `/de/support/fdafdafdas`. 

A work around is too load this client side (in `_middleware.ts` setting the locale as a cookie) and reading it client side and then loading the translations in the client like state here https://github.com/isaachinman/next-i18next#loading-namespaces-dynamically-client-side.  However, the example code looks incomplete or not in par with `addResourceBundle` intended usage: to add the translations, not to load them via a http/fetch.

## Occurs in next-i18next version

version `10.0.1`

## Steps to reproduce
See description above

## Expected behaviour
![image](https://user-images.githubusercontent.com/370567/149116255-deba5d5d-b730-4dea-83e8-377c1e626f1d.png)

I expect based on the readme code (see image) the translations will be loaded and usage of `useTranslation` will work.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device:  MBP 2018 15
 - Browser:  Chrome 96.0.4664.110 (Official Build) (x86_64)

**Comment by isaachinman** [comment]
> to add the translations, not to load them via a http/fetch

Not sure I follow. If you are in a client side environment and want a new namespace, it _has_ to be loaded via HTTP.

**Comment by gtothesquare** [comment]
If the nameSpace is already added to the app and I want to load the file via the client instead of using the server side method you provide, I thought one did it via the addReasources as showed in the readme. Is this supported or do I need to add a backend for it ?

**Comment by isaachinman** [comment]
Yes, you will most likely want to use [i18next-http-backend](https://github.com/i18next/i18next-http-backend).

If you feel the docs aren't clear, it would be great if you had time to open a PR to clarify.

**Comment by isaachinman** [comment]
The i18next team is now maintaining a proper example [here](https://github.com/locize/next-i18next-locize/blob/main/next-i18next.config.js). It's also linked in the `next-i18next` README.
