### ISSUE TITLE
[Vercel][getServerSideProps][serverSideTranslations] 500 when trying to read the locales

### ISSUE THREAD

**Issue by atanaskanchev** [isaachinman/next-i18next#1623]
## Describe the bug
Following the recommended settings for Vercel here https://github.com/isaachinman/next-i18next/issues/1552#issuecomment-981156476 `serverSideTranslations` called inside `getServerSideProps` fails on Vercel because it can't find the path to the locales, even though they are available in the Vercel workspace.

**next-i18next.config.js**
```javascript
const path = require('path');

const isRunningInBrowser = typeof window !== undefined;

const isRunningOnLocalhost =
  !!process.env['NEXT_PUBLIC_IS_RUNNING_ON_LOCALHOST'];

const isRunningOnVercel = !!process.env.VERCEL;

console.log({
  isRunningInBrowser,
  isRunningOnLocalhost,
  isRunningOnVercel,
});

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],

    ...(isRunningOnLocalhost && {
      localePath: path.resolve(
        './apps/next-i18next-vercel-issue/public/public/locales'
      ),
    }),
    ...(isRunningOnVercel && {
      localePath: path.resolve('./public/locales'),
    }),
  },
};
```

## Occurs in next-i18next version
10.2.0

## Steps to reproduce
I've created a minimal required setup repo here https://github.com/atanaskanchev/next-i18next-vercel-issue that's deployed on Vercel here https://next-i18next-vercel-issue-3qamiihrg-atanaskanchev.vercel.app/

## Expected behaviour
Error on Vercel to not occur
![image](https://user-images.githubusercontent.com/4958587/149311146-144e4df3-2389-403a-9d9a-b61fe16cf949.png)

## Screenshots
The locale files are available in the Vercel workspace
![image](https://user-images.githubusercontent.com/4958587/149312092-87a5ea5d-0ecc-46ab-b553-2e8d01f0492e.png)

Locally it works fine
![image](https://user-images.githubusercontent.com/4958587/149312423-13c036ad-f275-4433-bc65-95d7e851c31a.png)
![image](https://user-images.githubusercontent.com/4958587/149312671-9a7af1da-c573-4259-807c-19cfeff243dc.png)
![image](https://user-images.githubusercontent.com/4958587/149312800-e8288beb-3041-4070-a9bc-1b0c13b8cbd4.png)

**Comment by isaachinman** [comment]
Please read the [documentation](https://github.com/isaachinman/next-i18next#vercel-and-netlify), or search previous issues.

**Comment by isaachinman** [comment]
Not sure what to tell you, except that whatever issue you are facing is related to your own unique setup, undoubtedly. If you are using a monorepo, there are further complexities.

Side note, it seems odd that `isRunningInBrowser` and `isRunningOnVercel` would be true at the same time.

**Comment by atanaskanchev** [comment]
@isaachinman I've tried with the a bare-bone next.js app here https://github.com/atanaskanchev/next-i18next-vercel-cna and indeed it works as expected. However there's some issue with monorepos, for which I couldn't find any example of successful implementation.

**Comment by isaachinman** [comment]
Unfortunately my only recommendation is to contact the Vercel team directly, as monorepo support is an ongoing pain point with their platform.

**Comment by 2bdelghafour** [comment]
@atanaskanchev Did you figure out a solution to this issue yet since I've run into the same problem while using an NX mono repo?

**Comment by atanaskanchev** [comment]
@2bdelghafour Unfortunately not, I am still blocked with this issue. I couldn't find any other i18 package that work with my stack either: nx + vercel

**Comment by 2bdelghafour** [comment]
@atanaskanchev After some trial and error and following a throw against the wall and see what sticks approach '^^, I've managed to figure out a workaround to get the i18n working with Vercel + NX, what you need to do is create a dummy page and inside it you override the **localePath** property to this `localePath: path.resolve('./public/locales')` and set the one inside the i18n config file to `localePath: path.resolve('./apps/[app_name]/publics/locales')` which is going to be used for the real pages.
I've forked your repo to do use it as a testing playground and you can check the source code from here after I added another language and some pages for testing purposes:
https://github.com/2bdelghafour/next-i18next-vercel-issue

Your project settings on Vercel should look like this.
![image](https://user-images.githubusercontent.com/8062454/151633870-1771aad6-47a6-4794-aa21-36c2a399f0b9.png)

You can preview the changes from here:
https://next-i18next-vercel-issue-one.vercel.app/

**Comment by isaachinman** [comment]
@2bdelghafour Do you think `next-i18next` can improve to assist this use case in any way?

**Comment by 2bdelghafour** [comment]
@isaachinman The workaround I suggested is forcing Vercel to include those files in the bundle for serverless functions so if `next-i18next` can provide something to force Vercel to include files in a certain directory without having to create this dummy page as a workaround, it would be much better.

**Comment by atanaskanchev** [comment]
@2bdelghafour @isaachinman Thanks for your input, much appreciated. I can confirm that the workaround is working on Vercel

**Comment by fs-nathan** [comment]
> @atanaskanchev After some trial and error and following a throw against the wall and see what sticks approach '^^, I've managed to figure out a workaround to get the i18n working with Vercel + NX, what you need to do is create a dummy page and inside it you override the **localePath** property to this `localePath: path.resolve('./public/locales')` and set the one inside the i18n config file to `localePath: path.resolve('./apps/[app_name]/public/locales')` which is going to be used for the real pages.
> 
> I've forked your repo to do use it as a testing playground and you can check the source code from here after I added another language and some pages for testing purposes: https://github.com/2bdelghafour/next-i18next-vercel-issue
> 
> Your project settings on Vercel should look like this. ![image](https://user-images.githubusercontent.com/8062454/151633870-1771aad6-47a6-4794-aa21-36c2a399f0b9.png)
> 
> You can preview the changes from here: https://next-i18next-vercel-issue-one.vercel.app/

Hi @2bdelghafour Can you share your repository again? For now, [the link](https://github.com/2bdelghafour/next-i18next-vercel-issue) is no longer available.
Thanks!

**Comment by hedysnika** [comment]
So do I need workaround or did i18n added solution ??
