### ISSUE TITLE
Locales like en-us doesn't work

### ISSUE THREAD

**Issue by alexmtch** [isaachinman/next-i18next#1627]
## Describe the bug
With this config 

```
module.exports = {
  i18n: {
    ns: ['common'],
    defaultLocale: 'en-gb',
    locales: [
      'en-gb',
      'en-us',
    ]
  }
};
```

accessing to mydomain/en-us/ will not provide translations

## Occurs in next-i18next version
^11.11.4

## Steps to reproduce
Put the config, create common.json in localePath/en-us/

## Expected behaviour
Gt the translated string in front

**Comment by isaachinman** [comment]
That is not a valid locale. Try `en-US`.
