### ISSUE TITLE
Next/Link causing app to unmount

### ISSUE THREAD

**Issue by JonahLund** [isaachinman/next-i18next#1628]
## Describe the bug
For some reason if you use a next/link component and click the same link twice, the entire app will unmount and mount itself, causing some parts of my application to behave weirdly. Upon further inspection, clicking a link your already on will set the locale key on App to null (which is probably what's causing the issue). It seems that this only happens in production (im using vercel). 

**next-i18next.config.js**
`module.exports = {
  i18n: {
    defaultLocale: "en-US",
    locales: ["en-US", "sv-SE"],
  },
};
`

## Occurs in next-i18next version
10.1.0

## Steps to reproduce
I have created a minimal setup [repo](https://github.com/JonahLund/next-i18next_link_bug) that's deployed to [vercel](https://next-i18next-link-bug.vercel.app/)

## Expected behaviour
The app should not unmount if you click on a next/link component twice.

## Screenshots
Everything fine
![image](https://user-images.githubusercontent.com/73796695/149537528-e1891a63-8583-4d24-8e66-f0a9a904e078.png)
Until you click on the same link again
![image](https://user-images.githubusercontent.com/73796695/149537577-78e51f4e-2fcc-49f3-acba-c58f1347c1d6.png)

**Comment by isaachinman** [comment]
And what is `router.locale`?

**Comment by JonahLund** [comment]
> And what is `router.locale`?

router.locale stays the same, checked it.

**Comment by JonahLund** [comment]
Just to be sure, i made another branch where i removed turborepo, so now its basically a fresh nextjs project with an extremely basic next-i18next configuration, problem still persists. [vercel deployment](https://next-i18next-link-bug-p290t57rt-skinrod.vercel.app/)

**Comment by hengwangsay** [comment]
look like we have a same problem, this issue also happen when use router.push/replace

**Comment by isaachinman** [comment]
@JonahLund Can you link to the repo without turborepo?

**Comment by JonahLund** [comment]
> @JonahLund Can you link to the repo without turborepo?

https://github.com/JonahLund/next-i18next_link_bug/tree/no-monorepo-test

**Comment by isaachinman** [comment]
How do I build and run this application in production mode? Can you remove the `turbo` dependency?

**Comment by JonahLund** [comment]
> How do I build and run this application in production mode? Can you remove the `turbo` dependency?

I removed turborepo in the repo i linked, so its just a basic nextjs project, build using `yarn run build`, i deployed it using vercel.

**Comment by JonahLund** [comment]
Update: No need to deploy to vercel. I tested it with a production build locally, the problem still persists. So this is a global issue. Testing the prod build locally: `yarn run build`, and `yarn run start`.

**Comment by isaachinman** [comment]
Thanks for your help! I have been able to identify the issue. It's [this `useMemo`](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L31) call. When the same locale is passed multiple times, `useMemo` is not called, and thus `locale` remains equal to its instantiated value of `null`.

@JonahLund Would you be willing to work on a PR for this bug fix?

**Comment by JonahLund** [comment]
> Thanks for your help! I have been able to identify the issue. It's [this `useMemo`](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L31) call. When the same locale is passed multiple times, `useMemo` is not called, and thus `locale` remains equal to its instantiated value of `null`.
> 
> @JonahLund Would you be willing to work on a PR for this bug fix?

Great! Yeah can do a PR to fix the issue.

**Comment by sharpn** [comment]
I also seem to be getting this issue when running the dev server
