### ISSUE TITLE
addResourceBundle inside getStaticProps

### ISSUE THREAD

**Issue by adithep** [isaachinman/next-i18next#1641]
## Is your feature request related to a problem? Please describe.
I have a translation file, and some additional translation exist on the server. I am aware that I can call `addResourceBundle` in the client side, but I am wondering if this step could be done inside `getStaticProps` so `addResourceBundle` is done during page build. If so, can someone provide minimal example. Thank you

## Describe the solution you'd like
An example of calling `addResourceBundle` inside `getStaticProps`

**Comment by isaachinman** [comment]
Why? Just add the namespace to `serverSideTranslations`.

**Comment by adithep** [comment]
@isaachinman , in this scenario, I get additional resource from `getStaticProps` and wish to append this to existing resource that comes from json file in the locale folder. If this can be done via `serverSideTranslations` please show me an example.

When using `addResourceBundle` on the client side, it would be done this way:

```
useEffect(() => {
    i18next.addResourceBundle(locale, '<namespace name>', dataFromRemoteServer, true, false);
  }, [dataFromRemoteServer])
```

Is there a way to achieve similar effect purely via `getStaticProps`?  Needs additional translation from the remote server to append to existing translation on the locale folder.

**Comment by isaachinman** [comment]
I've answered similar questions many times in issues on this repo. Of course it's possible to do what you are describing, but I'd first suggest you simply download the external data source as a build step prior to even running NextJs, and ensure it already exists in your `public/locales` directory.

**Comment by adithep** [comment]
@isaachinman sorry I have spent hours looked through the issues, I cannot get any example for this kind of scenario, its probably my fault but I really have tried. (In this case the translation is dynamic so it cannot be downloaded into locales before hand)

**Comment by SirMoustache** [comment]
Hey @adithep  I think I had a similar issue, I was calling my translation server and then merging dictionaries 

```TypeScript
export async function getStaticProps() {
  /// ....

  // this is a dictionary object
  const serverTranslations = await translationService.fetch(locale, ['namespace']);
  // See https://github.com/isaachinman/next-i18next/blob/cfaba2659f09451aa695b2af7cefaabeda8a9da7/src/serverSideTranslations.ts#L107
  // for data type
  const fileTranslations = await serverSideTranslations(locale, ['namespace']);

  return {
    props: {
      ...mergeTranslations(serverTranslations, fileTranslations),
    },
  };
}
```

**Comment by isaachinman** [comment]
@adithep If you definitely need to do this in your NextJs runtime, you'll want to follow @SirMoustache's advice. You may need to wait for #1642. Let me know if I can answer any other questions 👍
