### ISSUE TITLE
Trans component error

### ISSUE THREAD

**Issue by TutoDS** [isaachinman/next-i18next#1644]
## Describe the bug
When I try use the `<Trans ...` component appears the error: `Error: Trans(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

## Occurs in next-i18next version
Version: `"next-i18next": "^10.2.0",`

## Steps to reproduce
Example of usage:

```ts
<Trans
		i18nKey={`experience:${title}`}
		components={{
			bold: <strong />,
			small: <small />,
			dot: <>.</>,
			separator: (
			<Icon
				className={'inline'}
				icon={'fluent:line-horizontal-1-20-regular'}
			 />
		)
	}}
/>
```

[Repo](https://github.com/TutoDS/dsousa-portfolio)

## Expected behaviour
Is expected the translation of this key or the default text with replacement of `components `

## Screenshots
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/18479474/150808103-a8faac37-8a21-42d7-96d6-cd4020b1b8e3.png">

## OS (please complete the following information)
 - Device: iMac 27"
 - Browser: Safari

**Comment by kachkaev** [comment]
Please follow the issue template when reporting a bug:

https://github.com/isaachinman/next-i18next/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by TutoDS** [comment]
> Please follow the issue template when reporting a bug:
> 
> https://github.com/isaachinman/next-i18next/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Already update with template

**Comment by isaachinman** [comment]
@TutoDS Can you create a _minimal_ reproduction of the error, so that we can isolate the issue? The repository you've linked is not minimal.
