### ISSUE TITLE
useTranslation is not work

### ISSUE THREAD

**Issue by marklee1972** [isaachinman/next-i18next#1653]
version:
next-i18next@10.2.0

I copy and paste the sample code into my app.
However it did not work.

My folder path:
_root\public\locales\en\common.json
root\public\locales\de\common.json
root\pages\index.js
root\pages\_app.js
root\next.config.js
root\next-i18next.config.js_

Both of common.json's content are :
```
{
  "description": "This is a non-page component that requires its own namespace"
}

```
My _app.js
```
import { appWithTranslation } from 'next-i18next'
const MyApp = ({ Component, pageProps }) => <Component {...pageProps} />
export default appWithTranslation(MyApp)
```

next.config.js and next-i18next.config.js are copied from source without any modify.

My index.js

```
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const SampleCard = (props)=> {
	const { t } = useTranslation('common');
    return <h2>Hello,{t('description')}</h2>;
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"]))
    }
  };
}
function Home(prop) {
  return(
	 <SampleCard name="peipei"/>
  )
}
export default Home;
```

However the result of browser render:
**Hello,description**

I have no idea what's wrong with this issue.
Do I have any options to trace this?
Ex: debug=true....

**Comment by isaachinman** [comment]
@marklee1972 Can you provide a reproducible repository?

**Comment by marklee1972** [comment]
@isaachinman
I can't explain this mircle....

It's work suddenly after I received your reply !
I didn't modify any code even restart npm run.
No matter how many times I do the same action before this.
Forgive my strange issue please.
Thank you very much.
