### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_nextI18Next')

### ISSUE THREAD

**Issue by juanirosmirez** [isaachinman/next-i18next#1657]
## Describe the bug
TypeError: Cannot read properties of undefined (reading '_nextI18Next')

I'm following the configuration instructions provided by next-i18next but I can't get it to work

"next-i18next": "^10.2.0",
"next": "11.1.2",

**Comment by isaachinman** [comment]
Please follow the issue template when opening a new issue.

**Comment by omar-crackle** [comment]
I am having the same issue.

**Comment by byeokim** [comment]
You might want to put [`serverSideTranslations`](https://github.com/isaachinman/next-i18next#serversidetranslations) into the page which spitted error:

```js
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

...

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
      // Will be passed to the page component as props
    },
  };
}
```

**Comment by omar-crackle** [comment]
Thanks for that!

From: Byeonggi Kim ***@***.***>
Date: Thursday, April 28, 2022 at 5:59 PM
To: isaachinman/next-i18next ***@***.***>
Cc: Omar Amer ***@***.***>, Comment ***@***.***>
Subject: Re: [isaachinman/next-i18next] TypeError: Cannot read properties of undefined (reading '_nextI18Next') (Issue #1657)

You might want to put serverSideTranslations<https://github.com/isaachinman/next-i18next#serversidetranslations> into the page which spitted error:

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';



...



export async function getStaticProps({ locale }) {

  return {

    props: {

      ...(await serverSideTranslations(locale, ['common', 'footer'])),

      // Will be passed to the page component as props

    },

  };

}

**Comment by eseQ** [comment]
For every one who can't get why this error is exist: **check your locale files is correct** and doesn't content special symbols out of quotes

**Comment by ahristov314** [comment]
FWIW in my case it was that I was trying to access a locale that wasn't explicitly listed in `next-i18next.config.js`  - you may have all the JSON files in place, but unless the locale is listed in i18n.locales, it will fail with the above error.

```
module.exports = {
    i18n: {
        defaultLocale: 'en',
        locales: ['en', 'es', ... other locales.... ],
    },
};
```
