### ISSUE TITLE
How to use it in a layout component in next.js

### ISSUE THREAD

**Issue by StupidManYI** [isaachinman/next-i18next#1666]
## Describe the bug
when I use nextjs and next-i18next, I hava a layout component with BottomNavigation , the words on BottomNavigation  needs i18n , how could I use this framework in a layout Component?  

## Occurs in next-i18next version
10.0.5

![image](https://user-images.githubusercontent.com/50037510/152100101-23b906c2-4eff-4bc2-a0c0-bc8de87374ea.png)
![image](https://user-images.githubusercontent.com/50037510/152099983-e682e544-24af-4ea2-b69b-622470579eed.png)
![image](https://user-images.githubusercontent.com/50037510/152100025-0806f6a4-dfc0-4780-a057-f53494f9e5e7.png)

**Comment by StupidManYI** [comment]
find the answer in other issue

**Comment by Hexi1997** [comment]
> 

hi, can i ask you how do you solve this problem?

**Comment by soxft** [comment]
It seems that, you just need to add a getStaticProps function in page where you import this layout,

**Comment by Hexi1997** [comment]
> It seems that, you just need to add a getStaticProps function in page where you import this layout

yeh, I solved this problem, thanks
