### ISSUE TITLE
Cannot 'changeLanguage' with 'next-i18next'

### ISSUE THREAD

**Issue by robert-barcelona** [isaachinman/next-i18next#168]
## Describe the bug
This may be a confusion on my part on how to use 'next-18next', but as I understand it is a wrapper for 'i18next' and 'react-i18next', and in those I should be able to call `changeLanguage`.  Here I can't do that -- `changeLanguage` is not a function, and I don't see it anywhere.  How do I access `changeLanguage` (and other i18Next functions) from the singleton I created like this?

```
const NextI18Next = require('next-i18next');

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'es',
  otherLanguages: ['de'],
});

```

module.exports = NextI18NextInstance;

## Occurs in next-i18next version
0.27.0

## Steps to reproduce

   import i18NextInstance, { withNamespaces } from '../../../i18n';

    i18NextInstance.changeLanguage('de');

## Expected behaviour
Should change the language

**Comment by capellini** [comment]
Hi @robert-barcelona.  Please see our [example index page](https://github.com/isaachinman/next-i18next/blob/b5b515ea78b0421197b855e8ddd7c865da10bde4/examples/simple/pages/index.js) for how to do this.

Instead of the default import, what we normally recommend is to import the named `i18n` import that has the `changeLanguage` method.

```js
import { i18n } from '../../../i18n'

i18n.changeLanguage('de')
```

**Comment by robert-barcelona** [comment]
Thanks!  That did it....

**Comment by AhsanNissar** [comment]
I am gollowing this example [https://github.com/isaachinman/next-i18next/tree/master/examples/simple](url). But whenever I use `changeLanguage('de')` it doesn't change the translation. On printing i18n instance in console I see that language property is set to 'de' but its not fetching the translations from `public/locales/de/login.json` file

**Comment by isaachinman** [comment]
@AhsanNissar Check [this](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L22).

**Comment by paulisloud** [comment]
> @AhsanNissar Check [this](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L22).

This in no way addresses the question @AhsanNissar asked. His question was about using `changeLanguage` to change the language, not changing it on a route changes. Also, your answer assumes we want to use the /{locale} style route structure. Many apps do not. This library should maintain the functionality provided by the `i18n-next` dependency.

**Comment by isaachinman** [comment]
Ah, I get what you're asking. No, `next-i18next` relies directly on the first class NextJs internationalised routing, and the NextJs router itself keeps track of the locale. You would need to make this request upstream to NextJs themselves.

**Comment by paulisloud** [comment]
Ok thanks for clarifying

**Comment by mcAnastasiou** [comment]
Does this mean that all api calls will be made on every language change?

**Comment by prabu-ssb** [comment]
This is a really frustrating change. we invested much time in getting `i18n.changeLanguage` to work in our project and with this it is completely unclean what needs to be done. 

I have use this wrapper for `router.push` calls to send the current new locale, but the pages continue to use the old language bundles.

```react
// hocs/useRouter.js
import { useRouter as nextRouter } from 'next/router';

export const useRouter = () => {
  const router = nextRouter();
  const { i18n } = useTranslation();
  
  const push = (path) => {
    const { language: locale } = i18n;
    router.push(path, path, { locale });
  }

  return { push };
}
``` 

@isaachinman : After `i18n.changeLanguage` is called, I see that the redirects point to the `{newLocale}/{path}` correctly, but the page content continues to be from the old bundle. Not sure what I am getting wrong here.. any thoughts?

**Comment by jackhkmatthews** [comment]
Not entirely sure my issue / want is related to this issue in particular but I wanted to post this somewhere:

```ts
      onClick={() => {
        i18n.changeLanguage(lang, () => {
          router.push({ pathname, query }, asPath, {
            locale: lang,
            scroll: false,
            shallow: true,
          });
        });
      }
```

I wanted to change locale (including the sub-path as my project uses [NextJS sub-path routing][1]) but without re-triggering other API requests that a route might need and hence any potential re-renders (I was getting some ugly white flashes).

The key bit is using the `i18n.changeLanguage` callback param.

As `changeLanguage` is async (which I hadn't considered although obvious as it requests translation files from the server) it needs to complete before using `router.push`.


  [1]: https://nextjs.org/docs/advanced-features/i18n-routing#sub-path-routing
