### ISSUE TITLE
next-i18next not working correctly with wrapped tRPC when SSR is enabled

### ISSUE THREAD

**Issue by medihack** [isaachinman/next-i18next#1682]
## Describe the bug
When wrapping an app with [`withTRPC`](https://trpc.io/docs/nextjs#4-configure-_apptsx) that is already wrapped with `appWithTranslation` leads to the error `react-i18next:: You will need pass in an i18next instance by using initReactI18next` on the server console when SSR is enabled for tRPC (otherwise everything works fine).
Maybe this is associated with #718 where some have issues with a proper setup.
I also opened an issue at tRPC as I am not sure which "fault" it is (https://github.com/trpc/trpc/issues/1507). Just stumbled upon it.

## Occurs in next-i18next version
"next-i18next": "^10.2.0"
"@trpc/next": "^9.18.0"

## Steps to reproduce
```
export default withTRPC<AppRouter>({
  config({ ctx }) {
    let url = process.env.TRPC_URL!
    return { url }
  },
  ssr: true, // no error when set to false
})(appWithTranslation(MyApp))
```

## Expected behaviour
It should also work with tRPC.

## OS (please complete the following information)
 - Device: Gitpod Cloud (but also tested locally)
 - Browser: Chrome

**Comment by medihack** [comment]
Ok, the problem is caused by tRPC which doesn't work with `getServerSideProps` when SSR is enabled, see
https://github.com/trpc/trpc/issues/1361
https://github.com/trpc/trpc/issues/596

If anyone stumbles upon this then please vote this issue up for a solution:
https://github.com/vercel/next.js/discussions/28183

Closing this issue now as it is not a next-i18next problem.

**Comment by electroheadfx** [comment]
i18next simply doesn't work (without error), just it doesn't translate, without SSR. Anyone experienced it ? thanks

**Comment by lodisy** [comment]
> i18next simply doesn't work (without error), just it doesn't translate, without SSR. Anyone experienced it ? thanks

Try [next-intl](https://github.com/amannn/next-intl), it works for me.
