### ISSUE TITLE
appWithTranslation defaults my context api to it's initialState everytime I move from a page with no serverSideTranslations to a page with serverSideTranslations

### ISSUE THREAD

**Issue by AhmedSarhan** [isaachinman/next-i18next#1683]
I have two pages the home page where I'm using serverSideTranslations and cars page where I'm, choosing a specific car to show on home page and not calling serverSideTranslations 
whenever I navigate to the home page after selecting a car
the context state changes once more with no actions being dispatched and goes back to its initial state
once I add serverSideTranslations  to my other page the issue is fixed but feels like inconvenient

**Comment by isaachinman** [comment]
> feels like inconvenient

`serverSideTranslations` is the only mechanism by which `next-i18next` can pass translation data as props into your pages. It is a consequence of the NextJs framework architecture.
