### ISSUE TITLE
i18n support is not compatible with next export

### ISSUE THREAD

**Issue by alexlam184** [isaachinman/next-i18next#1690]
Describe the bug
---
I want to build a portfolio website with i18n feature. However, it is not working when I tried to deploy my web in github page.
I got the following error
`i18n support is not compatible with next export`
I am confused for that and I cannot export a static web in order to host in GitHub.
For my case, should I give up to use next-i18next?

Occurs in next-i18next version
---
```
  "dependencies": {
    "all": "^0.0.0",
    "autoprefixer": "^10.4.2",
    "gh-pages": "^3.2.3",
    "husky": "^7.0.4",
    "next": "12.0.7",
    "next-i18next": "^10.2.0",
    "postcss": "^8.4.5",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icon": "^1.0.0",
    "react-icons": "^4.3.1",
    "tailwindcss": "^3.0.13",
    "typed.js": "^2.0.12"
  },
```

Steps to reproduce
---
`yarn next export`

Expected behaviour
---
export static web successfully

OS (please complete the following information)
---
Browser: Brave [Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (64-bit)](https://brave.com/latest/)

Additional context
---
My code:
https://github.com/alexlam184/personal-website

**Comment by isaachinman** [comment]
That message is coming from NextJs directly, not `next-i18next`. Please search previous issues.

**Comment by adrai** [comment]
@alexlam184 https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd
