### ISSUE TITLE
Import with type: "module"

### ISSUE THREAD

**Issue by Sandroggy** [isaachinman/next-i18next#1691]
## Is your feature request related to a problem? Please describe.
The package cannot be imported if the nextjs project us type: "module" in the package.json
Error: require is not defined in ES module scope

## Describe the solution you'd like
Import the package in a project with  type: "module" without error

## Describe alternatives you've considered
Use .cjs instead of .js without sucess

**Comment by isaachinman** [comment]
We export to multiple targets. Please check the `dist` dir, `package.json`, and feel free to suggest a resolution.
