### ISSUE TITLE
node >=9

### ISSUE THREAD

**Issue by littletower** [isaachinman/next-i18next#17]
Hi,

I noticed the following line in your `package.json`:
```json
"engines": {
    "node": ">=9"
}
```

And I was wondering, would that mean that you cannot use this package on a `next.js` app deployed with `now`? The Now Platform docs state the following:
```
The Node.js version used is the latest in the 8 branch.
```
EDIT:
deployed the example and getting this error:
```
error next-i18next@0.4.0: The engine "node" is incompatible with this module. Expected version ">=9". Got "8.10.0"
```

Is a node 9 dependency really necessary?

**Comment by isaachinman** [comment]
Hi @littletower - good question. I don't personally use `now`, so I wasn't aware of that. Surprised they use such an old version of node.

For future reference, the Node version is mentioned in the `now` docs [here](https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node/#node.js-version).

The `dist` dir (what end users consume) is transpiled via the default settings of [@babel/env](https://github.com/isaachinman/next-i18next/blob/master/.babelrc#L3). It should work with quite old versions of node without any issues.

Dropping down to >=8 with ba7a897.

**Comment by littletower** [comment]
thanks, AFAIK, they use node 8 because it uses less resources than the versions above, since now runs on AWS, it's a way to reduce costs.
