### ISSUE TITLE
[bug] cannot use option `lng` of `t()` function

### ISSUE THREAD

**Issue by kytosai** [isaachinman/next-i18next#1705]
## Describe the bug
I have setup locale

```js
// file:  next-i18next.config.js  
module.exports = {
  i18n: {
    defaultLocale: 'vi-VN',
    locales: ['vi-VN', 'en-US'],
  },
  defaultNS: 'common',
  localeExtension: 'json',
  reloadOnPrerender,
  localePath: path.resolve('./src/locales'),
};
```

Then I did all the steps according to the instructions of the README. When i want to show translate with `en-US` for a key in vi-VN default locale with option `lng` in `t()` function but it don't work

## Occurs in next-i18next version
It show error when i use `t()` with option `lng` containing value is locale other (en-US) than locale default (vi-VN)

[![a1bc324a1f7afa57be775ad9ad74e314.jpg](https://uphinh.vn/images/2022/02/22/a1bc324a1f7afa57be775ad9ad74e314.jpg)](https://uphinh.vn/image/tQY4Sr)

## Expected behaviour
- I think when i use t() function with lng option. It must work normal like i18next 

```js
import { NextPage } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'next-i18next';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
    },
  };
}

const TestPage: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div>
      {t('page:test.title', {
        lng: 'en-US', // it doesn't work, show error in console
      })}
    </div>
  );
};

export default TestPage;
```

## OS (please complete the following information)
 - Device: Macbook pro 2021 M1 Pro
 - Browser: Chrome Version 98.0.4758.102

**Comment by isaachinman** [comment]
Can you provide a reproducible repository?

**Comment by isaachinman** [comment]
I cannot run this repo:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2fpro-duotone-svg-icons: Not found".
```

Can you provide a minimal reproduction?

**Comment by kytosai** [comment]
> I cannot run this repo:
> 
> ```
> error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome%2fpro-duotone-svg-icons: Not found".
> ```
> 
> Can you provide a minimal reproduction?

This is minimal repo: https://github.com/kytosai/next-18next-issue/blob/main/src/pages/test/index.js#L19

**Comment by isaachinman** [comment]
The reason you have a render mismatch is because you are translating into a language which is not currently active. Thus, the `en-US` messages are not passed to the client side as props, and the browser has to revert to `vi-VN`, as it's the default locale and you are on the default locale path.

If you go to `http://localhost:3000/en-US/test`, the page works as expected.

I suggest you read [the docs](https://nextjs.org/docs/advanced-features/i18n-routing) carefully, to understand how NextJs localised routing works.
