### ISSUE TITLE
next-auth: Session breaks when the language is changed

### ISSUE THREAD

**Issue by Oliv6176** [isaachinman/next-i18next#1710]
## Describe the bug
[next-auth.js](https://next-auth.js.org/).
When a User is sign in and change the language, the user appears as they are signed out.
Refreshing the page fixes the issue (no need to actually click "Sign in" again).

## Occurs in next-i18next version
^10.4.0

## Steps to reproduce
Clone https://github.com/Oliv6176/next-auth-with-i18n
    Add NEXTAUTH_SECRET, [GITHUB_ID and GITHUB_SECRET](https://next-auth.js.org/providers/github) in .env.local
    Log in; notice "Signed in as…" banner appear in header.tsx.
    Navigate to one of the "Translation" routes marked /en or /de (that's route /en/with-await or /de/with-await.
    Note "Signed in as…" status has disappared. "Sign in" button available as user now appears logged out.
    Refresh the page to bring back the "Signed in as… " header (no need to actually click "Sign in" again).

## Expected behaviour
Clicking links or using router.push() shouldn't affect the state of a "signed in" user.

## Screenshots
When I click on /en or /de links, the "Signed in as…" status changes to appear that the user is signed out.
![image](https://user-images.githubusercontent.com/32340667/155855957-53585099-80b0-4b55-8e50-14c2901685ea.png)

## OS (please complete the following information)
 - Device: POP!_OS 21.10
 - Browser: Firefox

**Comment by isaachinman** [comment]
This is not a minimal repro, so I will not be able to debug for you. Most likely, you need to put `SessionProvider` _outside_ `appWithTranslation`, as I've mentioned in various other related issues.

**Comment by JonahLund** [comment]
@Oliv6176 Are you sure that you are using the latest next-i18next version? Because in the repo you linked, the next-i18next version is *"^10.2.0"*. Just wondering.

**Comment by isaachinman** [comment]
@Oliv6176 Any update?

**Comment by Oliv6176** [comment]
@JonahLund My mistake I forgot to push my update to the repo....
@isaachinman I moved my SessionProvider outside of appWithTranslation and now it's more reliable thx!

**Comment by chr-ge** [comment]
@OliverGeneser Mind sharing how you wrapped the SessionProvider around `appWithTranslation`?

**Comment by saintego** [comment]
@chr-ge I found this, but it didn't help to solve my problem https://github.com/isaachinman/next-i18next/issues/1075#issuecomment-1053347974
