### ISSUE TITLE
Getting it to work on a monorepo like nrwl/nx

### ISSUE THREAD

**Issue by AmruthPillai** [isaachinman/next-i18next#1711]
Just putting it out there for the folks who are struggling to get this up and running with a monorepo architecture similar to Nx where NextJS is not on the root directory, you can add the `localePath` property to your `next-18next.config.js` as such:

```
{
  localePath: './apps/<nextjs-app>/public/locales',
}
```

Within _app.tsx, you can also append the configuration when calling appWithTranslation, like so:

```
import i18nConfig from '../next-i18next.config';
...
export default appWithTranslation(App, i18nConfig);
```

This should start working for client side translations, but for the pages that have server side or static generation, you would have to use getServerSideProps or getStaticProps as mentioned in the README, but you would also need to pass your config there, as below:

```
import i18nConfig from '../next-i18next.config';
...
export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', ...otherNamespaces], i18nConfig)),
    },
  };
}
...
const Title = () => {
  const { t } = useTranslation();

  return t('title');
};
```

Hope that helps someone! ⭐

**Comment by kbooz** [comment]
Thank you very much @AmruthPillai <3

**Comment by kbooz** [comment]
I've created an file called `utils/next-i18next` with all the methods overridings that use my config file, to prevent importing it everywhere

```ts
import { appWithTranslation as ni18next_appWithTranslation } from 'next-i18next';
import { serverSideTranslations as ni18next_serverSideTranslations } from 'next-i18next/serverSideTranslations';

import nextI18NextConfig from '../next-i18next.config.js';

export const appWithTranslation: typeof ni18next_appWithTranslation = (
  component
) => appWithTranslation(component, nextI18NextConfig);

export const serverSideTranslations: typeof ni18next_serverSideTranslations = (
  locale,
  namespaces
) => ni18next_serverSideTranslations(locale, namespaces, nextI18NextConfig);
```

**Comment by electroheadfx** [comment]
Hey @AmruthPillai  and @kbooz Iam struggle to make it working, no error, just no translation (local path are recognized), I use NX with a T3 Stack, do you have a repo to share about your setup ? thanks to you all
