### ISSUE TITLE
Support for storybook

### ISSUE THREAD

**Issue by HasinaNjaratin** [isaachinman/next-i18next#1713]
I get errors while opening on storybook

`ERROR in ./.yarn/__virtual__/next-i18next-virtual-409ba6e5a4/0/cache/next-i18next-npm-10.4.0-908dce9031-49176ba4b1.zip/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js 78:33-46
Module not found: Error: Can't resolve 'fs' in '/usr/src/app/.yarn/__virtual__/next-i18next-virtual-409ba6e5a4/0/cache/next-i18next-npm-10.4.0-908dce9031-49176ba4b1.zip/node_modules/next-i18next/dist/commonjs'`

**Comment by isaachinman** [comment]
Please search around before copy/pasting an error and opening an issue. Resolution of `fs` is not the responsibility of `next-i18next`.

Here's one lead: https://github.com/storybookjs/storybook/issues/4082
