### ISSUE TITLE
Another way to access `t` function properly outside react component

### ISSUE THREAD

**Issue by bryantobing12** [isaachinman/next-i18next#1722]
## Describe the bug
Sorry for bringing this up again. But I still couldn't find a workaround for my case after reading others' issues about this
https://github.com/isaachinman/next-i18next/issues?q=outside+react+component

## Occurs in next-i18next version
10.4.0

## Steps to reproduce
My case is just simply that I need a way to use `t` outside react component. Since i will use `t` for many cases like in my `yup` validation schema which will be in its own file for separation of concern, and my other `utils`

## Expected behaviour
https://github.com/i18next/react-i18next/issues/1042#issuecomment-572959286 something like this. I have tried using a global instance based on this PR https://github.com/isaachinman/next-i18next/pull/986/files. which i believe exported as `i18n`

```typescript
import type { GetStaticProps, NextPage } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { i18n } from "next-i18next";

const name = i18n?.t("name"); // always undefined on first render or when refreshing page

const Home: NextPage = () => {
  return <div>{name} tests</div>;
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(locale &&
        (await serverSideTranslations(locale, ["common", "footer"]))),
    },
  };
};

export default Home;

```
I always get undefined on first render or when i refresh the page. The `string` sometimes show up after i made changes in my local for example updating `return <div>{name} tests</div>;` to become `return <div>{name} tests updated</div>;`

## Screenshots
1. on first render or when refreshing the page
![image](https://user-images.githubusercontent.com/46083126/156202784-9de4a5ef-4c1b-47d8-8084-246f8b719b68.png)
2. after making changes in local on hot reload
![image](https://user-images.githubusercontent.com/46083126/156202979-60f6834d-d7ee-4323-b578-b836b902ca1a.png)

## OS (please complete the following information)
 - Device: Windows 11 
 - Browser: Microsoft Edge

## Additional context
1. Other things that I have tried
Check if i18n is initialized
```typescript
const name = i18n?.isInitialized && i18n?.t("name"); // always undefined on first render or when refreshing page
```
2. package.json
```json
{
  "name": "my-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "12.1.0",
    "next-i18next": "^10.4.0",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@types/node": "17.0.21",
    "@types/react": "17.0.39",
    "eslint": "8.10.0",
    "eslint-config-next": "12.1.0",
    "typescript": "4.6.2"
  }
}

```

**Comment by isaachinman** [comment]
> Other things that I have tried
> Check if i18n is initialized

That is exactly what you will have to do. It is quite literally impossible to export an initialised i18n client without initialisation.

**Comment by bryantobing12** [comment]
I don't really understand. Is that means we need to initialize manually for client side translation? Like creating our own instance of next18next?

**Comment by bryantobing12** [comment]
When exactly it will be initialized?. Can't find it at my case.  I have tried the i18n.isInitialized but that's not work.

**Comment by bryantobing12** [comment]
how you would implement this if you want to use `t` function from `util` file? @isaachinman  could you provide some example. I'm getting lost right now. I have tried many possible solution but nothing seems work until now.

**Comment by EugeneGohh** [comment]
> > it always undefined on first render of the page
> 
> Well obviously – you are defining the variable once upon load.
> 
> You can try this pattern:
> 
> ```tsx
> const name = () => i18n?.t("name")
> 
> // Elsewhere
> <div>{name()}</div>
> ```

It's not working.

**Comment by Ti-tanium** [comment]
> > it always undefined on first render of the page
> 
> Well obviously – you are defining the variable once upon load.
> 
> You can try this pattern:
> 
> ```tsx
> const name = () => i18n?.t("name")
> 
> // Elsewhere
> <div>{name()}</div>
> ```

It's causing hydration error: `Text content does not match server-rendered HTML`
