### ISSUE TITLE
QUESTION: Is keyPrefix supported?

### ISSUE THREAD

**Issue by VladimirMikulic** [isaachinman/next-i18next#1723]
Hi,

I wasn't able to find this anywhere so decided to ask.
Is `keyPrefix` option supported with `useTranslation`?

https://react.i18next.com/latest/usetranslation-hook#optional-keyprefix-option

I tried this as described on the link above, but it has no effect.

Thanks.

**Comment by isaachinman** [comment]
Yes, it's supported. What did you try?

**Comment by VladimirMikulic** [comment]
Thanks for the fast reply @isaachinman.
I tried it exactly as specified on react-i18next link above but it seems it doesn't even exist.
(it's not in i18n either)

![Screenshot_20220302_001837](https://user-images.githubusercontent.com/35997844/156265188-9cc222c8-afe8-4ee5-bf14-c3f592cfee0f.png)

**Comment by isaachinman** [comment]
Released in v10.5.0.

**Comment by VladimirMikulic** [comment]
Thank you so much @isaachinman!
