### ISSUE TITLE
how to remove the /[lang tag] from url using nextjs?

### ISSUE THREAD

**Issue by Odinwan** [isaachinman/next-i18next#1725]
Everything works fine, but how can I get rid of the locale from the url.
  I don't want any locale to be selected.
  
<img width="831" alt="image" src="https://user-images.githubusercontent.com/47388945/156647341-982b7111-f533-4d7c-8355-871097f23f58.png">

**Comment by MurazAslan** [comment]
Hello,how to fixed this problem ?
