### ISSUE TITLE
Adding types to `t()` function from `react-i18next`

### ISSUE THREAD

**Issue by vricop** [isaachinman/next-i18next#1732]
How can we [create a declaration file as in `react-i18next`](https://react.i18next.com/latest/typescript#create-a-declaration-file)?

If `next-i18next` bundles `i18next` & `react-i18next`, how can we type our json files while using the `t()` function returned by `useTranslation` hook in our components? This is great for type safe and autocomplete features.

Sample from `react-i18next` documentation site:

```ts
// import the original type declarations
import 'react-i18next';
// import all namespaces (for the default language, only)
import ns1 from 'locales/en/ns1.json';
import ns2 from 'locales/en/ns2.json';


// react-i18next versions lower than 11.11.0
declare module 'react-i18next' {
  // and extend them!
  interface Resources {
    ns1: typeof ns1;
    ns2: typeof ns2;
  }
}

// react-i18next versions higher than 11.11.0
declare module 'react-i18next' {
  // and extend them!
  interface CustomTypeOptions {
    // custom namespace type if you changed it
    defaultNS: 'ns1';
    // custom resources type
    resources: {
      ns1: typeof ns1;
      ns2: typeof ns2;
    };
  };
};
```

## I'm doing this in my app

I don't have access to `react-i18next` package, so I guess I've gotta do this instead. But it won't work. Do you know how can we take advantage of `reac-i18next`'s `CustomTypeOptions` interface to achieve this?

```ts
/* next-18n-next.d.ts */

import 'next-i18next'
import common from './public/locales/en/common.json'
import home from './public/locales/en/home.json'

declare module 'react-i18next' {
  interface CustomTypeOptions {
    common: typeof common
    home: typeof home
  }
}
```

```diff
/* next-18n-next.d.ts */

import 'next-i18next'
import common from './public/locales/en/common.json'
import home from './public/locales/en/home.json'

- declare module 'react-i18next' {
+ declare module 'next-i18next' {
  interface CustomTypeOptions {
    common: typeof common
    home: typeof home
  }
}
```

Thanks in advance @isaachinman and congrats for this great library.

**Comment by vricop** [comment]
Ok, I was doing it completely wrong. This is how it goes:

```ts
import 'react-i18next'
import common from './public/locales/en/common.json'
import home from './public/locales/en/home.json'

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNs: 'common'
    resources: {
      common: typeof common
      home: typeof home
    }
  }
}
```

This is how I was doing it at the beginning but I was using the wrong package reference (`next-i18next`). Sorry about it. Have a nice day.

**Comment by ashkan-pm** [comment]
> Ok, I was doing it completely wrong. This is how it goes:
> 
> ```ts
> import 'react-i18next'
> import common from './public/locales/en/common.json'
> import home from './public/locales/en/home.json'
> 
> declare module 'react-i18next' {
>   interface CustomTypeOptions {
>     defaultNs: 'common'
>     resources: {
>       common: typeof common
>       home: typeof home
>     }
>   }
> }
> ```
> 
> This is how I was doing it at the beginning but I was using the wrong package reference (`next-i18next`). Sorry about it. Have a nice day.

But adding this to my project in a `react-i18next.d.ts` file does not make the `t()` function type safe. It does nothing.

**Comment by vricop** [comment]
> > Ok, I was doing it completely wrong. This is how it goes:
> > ```ts
> > import 'react-i18next'
> > import common from './public/locales/en/common.json'
> > import home from './public/locales/en/home.json'
> > 
> > declare module 'react-i18next' {
> >   interface CustomTypeOptions {
> >     defaultNs: 'common'
> >     resources: {
> >       common: typeof common
> >       home: typeof home
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how I was doing it at the beginning but I was using the wrong package reference (`next-i18next`). Sorry about it. Have a nice day.
> 
> But adding this to my project in a `react-i18next.d.ts` file does not make the `t()` function type safe. It does nothing.



> > Ok, I was doing it completely wrong. This is how it goes:
> > ```ts
> > import 'react-i18next'
> > import common from './public/locales/en/common.json'
> > import home from './public/locales/en/home.json'
> > 
> > declare module 'react-i18next' {
> >   interface CustomTypeOptions {
> >     defaultNs: 'common'
> >     resources: {
> >       common: typeof common
> >       home: typeof home
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how I was doing it at the beginning but I was using the wrong package reference (`next-i18next`). Sorry about it. Have a nice day.
> 
> But adding this to my project in a `react-i18next.d.ts` file does not make the `t()` function type safe. It does nothing.

Try changing the declaration file name to something arbitrary `like whatever.d.ts`. If it works it has something to do with some kind of conflict with another declaration file. It did work for me.

**Comment by ashkan-pm** [comment]
My bad, this is actually working. Here was my problem. I was banging myself against the wall all day. Maybe it would help someone if you're trying to use type augmentation and have a type-safe `t()` function. I was following the exact guide for setting this up as mentioned here, but I would get `Module '"react-i18next"' has no exported member 'useTranslation'` errors. Obviously there was something wrong with the augmentation. Turns out the problem was the priority of types. I was able to solve my problem by adding the directory of my `.d.ts` file to `tsconfig.json` before `node_modules`.

```ts
  {
    "compilerOptions": {
      "typeRoots": ["src/types/", "node_modules/@types/"]
    }
  }
```

**Comment by vricop** [comment]
> My bad, this is actually working. Here was my problem. I was banging myself against the wall all day. Maybe it would help someone if you're trying to use type augmentation and have a type-safe `t()` function. I was following the exact guide for setting this up as mentioned here, but I would get `Module '"react-i18next"' has no exported member 'useTranslation'` errors. Obviously there was something wrong with the augmentation. Turns out the problem was the priority of types. I was able to solve my problem by adding the directory of my `.d.ts` file to `tsconfig.json` before `node_modules`.
> 
> ```ts
>   {
>     "compilerOptions": {
>       "typeRoots": ["src/types/*", "node_modules/@types/"]
>     }
>   }
> ```

That's interesting, I didn't know about that. Thanks!

**Comment by vricop** [comment]
@ashkan-pm could you please tell the source where you found this answer? Thanks in advance.

**Comment by ashkan-pm** [comment]
@vricop Not exactly the same case, but it was the same problem [https://stackoverflow.com/questions/60704234/augment-imported-module-declaration](https://stackoverflow.com/questions/60704234/augment-imported-module-declaration)

**Comment by bryantobing12** [comment]
is there any step by step on how to achieve this?

**Comment by ricardo-rp** [comment]
There **really** needs to be a step-by-step guide for this in the readme. It's fairly easy to do in react-i18next and i18next, but I haven't yet managed to do it in my project. Adding typeRoots to my tsconfig did nothing sadly.
I'm ready to make a PR adding instructions to the doc as soon as I figure out how to fix this.

**Comment by campanflaviu** [comment]
I managed to solve this by changing the import and module declaration from `react-i18next` or `next-i18next` to just `i18next` like this:
```
import 'i18next'
import common from './public/locales/en/common.json'
import home from './public/locales/en/home.json'

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNs: 'common'
    resources: {
      common: typeof common
      home: typeof home
    }
  }
}
```
