### ISSUE TITLE
The `userConfig.localePath` will be exposed in production

### ISSUE THREAD

**Issue by u3u** [isaachinman/next-i18next#1745]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/20062482/158747560-1b178347-0ffc-456d-9b94-8de92472b678.png">

**Comment by isaachinman** [comment]
You are free to use whatever filesystem setup you deem appropriate, in terms of your own security concerns. I am not convinced that redacting fs paths is functionality that belongs in `next-i18next`.
