### ISSUE TITLE
Multiple options with useTranslation doesn't print some values of json files (only prints param value of function)

### ISSUE THREAD

**Issue by santyas** [isaachinman/next-i18next#1748]
Hi! Some values in multiple json file doesn't print correctly, for example using: 
`const { t } = useTranslation(['footer', 'faqs'])`. 
Some values of faqs (Second one) only prints the param value, not the result of the json.

## Occurs in next-i18next version
"next-i18next": "10.5.0",

## Steps to reproduce
Printing texts from two or more json files, using:
`<Trans t={t} i18nKey="faq"/>`
or
`{ t('title') }`

## OS (please complete the following information)
 - Browser: All

**Comment by isaachinman** [comment]
The `useTranslation` hook comes from the `react-i18next` repository. Any issues with it should be reported there.
