### ISSUE TITLE
Are nested JSONs supported? if so, how to use it? 

### ISSUE THREAD

**Issue by saikarthikp9** [isaachinman/next-i18next#1754]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
A way to use nested JSONs from the translation files

## Describe alternatives you've considered
N/A

**Comment by isaachinman** [comment]
All i18next features are supported.

**Comment by seebham** [comment]
@saikarthikp9 - You can checkout - https://www.i18next.com/translation-function/nesting#passing-options-to-nestings
