### ISSUE TITLE
Lose translation during page transition animation in layout

### ISSUE THREAD

**Issue by YusukeSano** [isaachinman/next-i18next#1767]
## Describe the bug
The translated string is turned into a key before the transition is completed and then re-rendered.

## Occurs in next-i18next version
10.5.0

## Steps to reproduce
https://github.com/YusukeSano/next-i18next-issue1767

## Expected behaviour
No loosing translations

## Screenshots
![report](https://user-images.githubusercontent.com/54178415/160987207-37f52c70-4c13-456b-a7af-0368663b3ada.gif)

## OS (please complete the following information)
 - Device: MBP 2017 13
 - Browser: Chrome 99.0.4844.84

## Additional context
Related to issue #1177

**Comment by isaachinman** [comment]
Where did this `getLayout` pattern come from? It is obviously what is causing this issue.

**Comment by bu3alwa** [comment]
@isaachinman it's a pattern for having a per page layout system https://nextjs.org/docs/basic-features/layouts#per-page-layouts

> The translated string is turned into a key before the transition is completed and then re-rendered.

Using the ready from the useTranslation hook might solve your issue by the sound of it.

**Comment by isaachinman** [comment]
Or, if you want to do some arbitrary persistant `getLayout` thing, you should do it one layer above `appWithTranslation`. Please keep in mind that `appWithTranslation` is just a simple HOC and can be wrapped itself.

**Comment by YusukeSano** [comment]
I was able to resolve this issue by wrapping useTranslation in new hooks using useMemo, as in this code!

```
import { useMemo } from "react";
import { useTranslation as useNextTranslation } from 'next-i18next'

export default function useTranslation(namespace, options) {
	const { t, i18n } = useNextTranslation(namespace, options);
	const T = useMemo(() => t, [i18n]);
	return { t: T, i18n };
}
```

This code is based on the next-translate issue.
https://github.com/vinissimus/next-translate/issues/513

I have also pushed the solution to the repository in question.
https://github.com/YusukeSano/next-i18next-issue1767
