### ISSUE TITLE
Does not support pageExtensions with values "x.js" or "page.js"

### ISSUE THREAD

**Issue by olafur-palsson** [isaachinman/next-i18next#1777]
## Describe the bug
Show's the key instead of translating, displays the following in the console.
```
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```

## Occurs in next-i18next version  
Package.json  `"version": "11.0.0",`

## Steps to reproduce
1. Use the `examples/simple`
2. Change `next.config.js` 
```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
+ pageExtensions: ['page.js']
}
```
3. Change names of pages to `index.page.js` and `second-page.page.js`
4. 
## Expected behaviour
`t('h1')` is the title as string.
`t('h1')` is "h1"

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Firefox 70.0.3538.77]

## Additional context

**Comment by olafur-palsson** [comment]
This one is pretty essential to have a modular pages in next.js. With for example `pages/product/components` without the components becoming pages.

**Comment by isaachinman** [comment]
`pageExtensions` is not a valid config option. As long as you use `serverSideTranslations`, `next-i18next` will work – it is completely agnostic of your file extensions.

**Comment by olafur-palsson** [comment]
Sorry, about the type-oh. This is how it looks.

![image](https://user-images.githubusercontent.com/19432526/161834276-92bc22d4-fb81-490b-9113-2482c162e229.png)

**Comment by isaachinman** [comment]
If you believe you have found a bug within `next-i18next`, please provide a reproducible repository.

**Comment by olafur-palsson** [comment]
Here you go 

https://github.com/olafur-palsson/next-i18next

**Comment by isaachinman** [comment]
Thanks! I'm quite surprised to see that this does indeed appear to be a genuine issue, for some reason.

@olafur-palsson Are you able to debug at all? This initially seems like potentially a bug within NextJs to me.

**Comment by olafur-palsson** [comment]
Yeah, I'm poking around, but I've found nothing yet. This is my first time reading this code after all. And I do see you've kept your house clean and minimal so now I'm also surprised about this bug.

**Comment by isaachinman** [comment]
Well, this ended up being a simple one. If you want to use page extensions like this, you also need to rename `_app.js` to `_app.page.js`.

They do mention this explicitly in [the documentation](https://nextjs.org/docs/api-reference/next.config.js/custom-page-extensions):

![Screenshot 2022-04-06 at 08 14 09](https://user-images.githubusercontent.com/10575782/161917006-e41d0a65-9f12-44c0-b312-55f16cdea3f1.png)

**Comment by olafur-palsson** [comment]
This makes so much sense and I feel dumb now. 😂
