### ISSUE TITLE
 next-i18next crashes app in getStaticProps during runtime

### ISSUE THREAD

**Issue by ryankauk** [isaachinman/next-i18next#1778]
## Describe the bug

On completely static pages it builds and loads but you can see the error happen in the background on Vercel logs. To note I am using a mono repo structure. I would expect the serverSideTranslations to simply use something like fetch on relative url "/locales/en.json" to avoid trying to read the file itself.

## Occurs in next-i18next version
Test 10-11

## Steps to reproduce
```typescript
/// test/[slug]
import { GetStaticPropsContext } from 'next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

export const getStaticProps = async (ctx: GetStaticPropsContext) => {
  return {
    props: {
      ...(await serverSideTranslations(ctx.locale!, ['common', 'links'])),
    },
  }
}

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: 'blocking',
  }
}

const Index = () => {
  return <p>test</p>
}

export default Index
```

```bash
ffd2e5d0-fe94-45ae-9fa3-3c93ea4bbc8b	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/frontend/public/locales/en'
    at Object.readdirSync (fs.js:1047:3)
    at getLocaleNamespaces (/var/task/frontend/node_modules/next-i18next/dist/commonjs/config/createConfig.js:203:23)
    at /var/task/frontend/node_modules/next-i18next/dist/commonjs/config/createConfig.js:209:20
    at Array.map (<anonymous>)
    at getNamespaces (/var/task/frontend/node_modules/next-i18next/dist/commonjs/config/createConfig.js:208:44)
    at createConfig (/var/task/frontend/node_modules/next-i18next/dist/commonjs/config/createConfig.js:249:29)
    at _callee$ (/var/task/frontend/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:199:53)
    at tryCatch (/var/task/frontend/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/frontend/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/var/task/frontend/node_modules/regenerator-runtime/runtime.js:118:21) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/frontend/public/locales/en',
  page: '/test/[slug]'
}
RequestId: ffd2e5d0-fe94-45ae-9fa3-3c93ea4bbc8b Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Please share your `next-i18next.config.js` file.

**Comment by skve** [comment]
We're running into this issue, but only on Vercel – the project dev server runs fine. When accessing a page using dynamic routing (`[id].tsx` for example) we get an error in the Vercel logs (see attached).

![Screenshot 2022-04-07 at 10 58 55](https://user-images.githubusercontent.com/47612057/162162018-e5ac884d-d216-457d-a058-3f8bfefebe59.png)

**Comment by isaachinman** [comment]
Read [the docs](https://github.com/isaachinman/next-i18next#vercel-and-netlify).

**Comment by skve** [comment]
Thanks for the pointer
