### ISSUE TITLE
localeSubpaths not resetting to default lang via url - expected?

### ISSUE THREAD

**Issue by reactor81** [isaachinman/next-i18next#178]
## Describe the bug
My NextI18Next constructor options are: 
{localeSubpaths: true,
 defaultLanguage: 'en',
 otherLanguages: ['de']}

As expected, when I go to http://localhost:3000/de I see my page using de strings. 

Then, I edit the address in the browser address bar to http://localhost:3000  .. I was expecting it to show en strings... Does it automatically go to de because of the i18next cookie?

If so, how can I go 'back' to en strings? It seems I can go back by doing http://localhost:3000/en .. and now I am back to english by default.. Or, do I have to make a UI switcher to switch back to english?

I was thinking typing http://localhost:3000 would automatically put me back to defualtLanguage (en) mode.. but I guess it remembers to forward to /de... Is that intended? I guess we do that so user A always sees the same language, without having to manually add /de ?

## Occurs in next-i18next version
0.31.0

**Comment by isaachinman** [comment]
Yes, this is intended. Please see #60 and #73.
