### ISSUE TITLE
`localePath` expose website location on the server

### ISSUE THREAD

**Issue by SarkarKurdish** [isaachinman/next-i18next#1780]
![image](https://user-images.githubusercontent.com/37934074/162301701-c2178c73-0bef-405b-8c9b-a75198780d4a.png)

revealing the server path is a nightmare when hosting the nextjs app on your own server we do so much work to hide our server's usernames while nextjs with i18n will just give it away like that, I mean it is not something that get your server hacked but it's not something that should be shown in the client. 

can we please get an explanation how and why this variable is returned to the client and how it's been used?
does removing this variable break the application?

Thanks.

**Comment by isaachinman** [comment]
`localePath: typeof window === 'undefined' ? serverPath : clientPath`
