### ISSUE TITLE
Type 'TFunctionResult' is not assignable to type 'string'. #515

### ISSUE THREAD

**Issue by HT-Moh** [isaachinman/next-i18next#1781]
After upgrading  `react ` and  `react-dom ` from  `17.0.2 ` to   `18.0.0 ` the issue `Type 'TFunctionResult' is not assignable to type 'string' error appears - apparently this was an issue before https://github.com/isaachinman/next-i18next/issues/515 
  
using next `"next": "12.1.4"`  and `    "next-i18next": "^11.0.0",` 
```
  "compilerOptions": {
    "target": "es6",
    "esModuleInterop": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "dom.iterable",
      "esnext",
      "es5",
      "es6"
    ],
```
when I downgrade to     "react": "^17.0.2",  everything works as before.

**Comment by heikomat** [comment]
One quick and very dirty workaround is to just overwrite the return-type of that i18next-function:

```TypeScript
import * as i18next from 'i18next';

// Workaround for https://github.com/isaachinman/next-i18next/issues/1781
declare module 'i18next' {
  interface TFunction {
    <
      TKeys extends i18next.TFunctionKeys = string,
      TInterpolationMap extends object = i18next.StringMap
    >(
      key: TKeys,
      options?: i18next.TOptions<TInterpolationMap> | string,
    ): string;
  }
}
```

The culprit is here: https://github.com/i18next/i18next/blob/9ca694db52fe5b6f10da5debf3e106e6f615b907/index.d.ts#L685-L707

the result type of the function extends `TFunctionResult`, which is defined as
```TypeScript
type TFunctionResult = string | object | Array<string | object> | undefined | null;
```

So to typescript the result of that function can be pretty much anything.

What i haven't found out yet is: Why was this not an issue before with react 17?

**Comment by gunaygultekin** [comment]
hi, I have the same issue. I added dirty workaround it was sold. I hope this will be fixed soon. Thanks @heikomat

**Comment by supercutcat** [comment]
My project also ran into this problem and I hope to be solved soon

**Comment by yoshikawa** [comment]
I have the same issue. I added this [issue comment's code](https://github.com/isaachinman/next-i18next/issues/1781#issuecomment-1092620082).
Thanks @heikomat !!

Perhaps these references may be useful for this project.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/46691
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210

**Comment by HT-Moh** [comment]
@heikomat I added the workaround on `.d.ts`  but it didn't work. 

```javascript

// declare module '*.yml' {
//   const data: any;
//   export default data;
// }
// declare module '*.graphql' {
//   const gql: any;
//   export default gql;
// }
// declare module '*.pem' {
//   const pem: any;
//   export default pem;
// }
// declare module '*.json' {
//   const value: any;
//   export default value;
// }

window.sa_event = window.sa_event || {};

declare global {
    var prisma: PrismaClient;
    interface Window {
      cardano:any;
    }
}
// force the file to be registered as a module, not a script
// export {}

import * as i18next from 'i18next';

// Workaround for https://github.com/isaachinman/next-i18next/issues/1781
declare module 'i18next' {
  interface TFunction {
    <
      TKeys extends i18next.TFunctionKeys = string,
      TInterpolationMap extends object = i18next.StringMap
    >(
      key: TKeys,
      options?: i18next.TOptions<TInterpolationMap> | string,
    ): string;
  }
}

```

**Comment by isaachinman** [comment]
Hi all. This is an issue on upstream i18next types. Has anyone opened an issue in the relevant i18next repo? cc @adrai

**Comment by adrai** [comment]
> Hi all. This is an issue on upstream i18next types. Has anyone opened an issue in the relevant i18next repo? cc @adrai

I'm not a TypeScript user... maybe related to: https://github.com/i18next/react-i18next/issues/1466 or https://github.com/i18next/react-i18next/issues/1476 ? @pedrodurek

**Comment by adrai** [comment]
react-i18next v11.16.4 fixes this

**Comment by isaachinman** [comment]
Great, I don't think there's anything actionable on the `next-i18next` side. Users can either regenerate their lockfiles, or use `resolutions` in their package.json.

**Comment by Fosol** [comment]
workaround doesn't work for me.  I can't upgrade to v18 because of this.

**Comment by meness** [comment]
@Fosol and everyone else still wondering how to fix this please read this comment. The issue was with `react-i18next` and it's been fixed with v11.16.4. To fix this issue, @isaachinman should release a version with latest commits. Another workaround is install `react-i18next` too.

**Comment by isaachinman** [comment]
@meness The update you described will not force any lockfile changes in user applications. Users need to fix this within their own apps.

**Comment by pureliani** [comment]
A quick solution for me was to define `TFunction2` and use it instead
```ts
import { TOptionsBase, type TFunction } from "i18next";
import { $Dictionary } from "i18next/typescript/helpers";

type _TFunctionKey = Exclude<
  Exclude<
    Parameters<TFunction>["0"],
    TemplateStringsArray | string | string[]
  >[number],
  TemplateStringsArray
>;

type _TFunctionOptions = Extract<
  Parameters<TFunction>["1"],
  TOptionsBase & $Dictionary
>;

export type TFunction2 = (
  key: _TFunctionKey,
  options?: _TFunctionOptions
) => string;

```
