### ISSUE TITLE
./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:78:0 Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by Qclaire** [isaachinman/next-i18next#1782]
## Describe the bug
importing serverSideTranslations breaks the page with the error message: 
`./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:78:0 Module not found: Can't resolve 'fs'`

## Occurs in next-i18next version
`next-i18next: ^11.0.0`

## Steps to reproduce

```
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

 export async function getStaticProps({ locale }) {
       return {
           props: {
                ...(await serverSideTranslations(locale, ["homepage"])),
           },
        };
}
```

## Expected behaviour
The error should not occur and translations should work as expected

## Screenshots
<img width="803" alt="image" src="https://user-images.githubusercontent.com/38317525/162450761-4aa07b4c-8306-4266-bda4-cc4bafcbf798.png">

<img width="723" alt="image" src="https://user-images.githubusercontent.com/38317525/162451152-03612db4-2ead-4552-90b0-a04681741c16.png">

## OS (please complete the following information)
 - Device: MBP M1
 - Browser: any browser

## Additional context
I noticed this issue opened by another person but the issue is closed with any pointer as to how to solve it.

**Comment by deema089786** [comment]
Check this
https://stackoverflow.com/questions/64926174/module-not-found-cant-resolve-fs-in-next-js-application

**Comment by isaachinman** [comment]
Unrelated to `next-i18next`.
