### ISSUE TITLE
Plurals (count) not detected for locales with underscore

### ISSUE THREAD

**Issue by marlein-rusch** [isaachinman/next-i18next#1784]
## Bug
When using the **count** attribute in a `<Trans>` component (or t-function), the corresponding "_one" and "_other" values in the common.json files are not detected/taken for certain locales, from what I've seen the locales containing underscores. The translation will fall back to either the common.json files of the defaultLocale (if that's a locale without underscore), or to the default value in the Trans component (in JSX). Note that normal & interpolated values ARE picked up well.

Version specs:
    - "next": "12.1.4",
    - "next-i18next": "^11.0.0"
    - "typescript": "4.6.3"

## Steps to reproduce
See it in action at: https://github.com/marlein-rusch/next-ts-next-i18next-locale-bug
To test it:
- Pull branch, `npm i`, `npm run dev`, and try out some locales in the browser. In summary, the outcome when running:

Locales that work as expected:
`http://localhost:3000/en-US` (same for `en-150`, `en`)
Translated outcome in browser:
```
2 cars from common en-US
From common file en-US
Interpolated value bar in common en-US
```

Locales that do NOT work as expected:
`http://localhost:3000/en_US` (same for `en_150`, `en150`)
Translated outcome in browser:
```
2 car, default in JSX file (👎 )
From common file en_US
Interpolated value bar in common en_US
```

## Expected behaviour
I would expect usage of "count" to work, i.e. grab the "_one" or "_other" value from the (in this case) `common.json` file.
In the example in the repo, more specifically, I expect the outcome in the browser resulting from lines 13 to 15 in `Index.tsx` to be:
"2 cars from common en_US"
and not
"2 car, default in JSX file"

Also, it's weird that common.json values ARE picked up for non-count related Trans usage (normal and interpolation) for the locales that do not seem to support the count functionality.

## OS (please complete the following information)
 - Browser: Chrome latest version

**Comment by isaachinman** [comment]
`en_US` is not a valid locale. Underscores are not interchangeable with dashes.

**Comment by luxus1337** [comment]
en_US is a valid locale: https://en.wikipedia.org/wiki/Locale_(computer_software)

It's the linux standard even (using _). Also it works for replacements why shouldn't it work for plural.

**Comment by chrisneven** [comment]
> `en_US` is not a valid locale. Underscores are not interchangeable with dashes.

How is `en_US` not a locale? Would like it to flexible as well

**Comment by isaachinman** [comment]
`next-i18next` has no control over the set of accepted locales – it's completely agnostic. That functionality lies entirely with the i18next and NextJs projects.
