### ISSUE TITLE
Plurals half-working for 1 langauge and entirely working for another

### ISSUE THREAD

**Issue by Nikola-Milovic** [isaachinman/next-i18next#1798]
## Describe the bug
I have 2 languages, Croatian and English, on the English side all plurals are working as expected, on the Croatian side, half of the translations work (even when the same key is used!)

## Occurs in next-i18next version
  "next-i18next": "^10.2.0",

## Code used 

```
    const { t } = useTranslation("campaigns");
    
        const options = [
        { count: 0, duration: "day" },
        { count: 1, duration: "week" },
        { count: 2, duration: "week" }, // this doesn't work in croatian
        { count: 3, duration: "week" }, // nor this
        { count: 1, duration: "month" },  
        { count: 3, duration: "month" }, // nor this
        { count: 6, duration: "month" },
    ];

             <select>
                    {options.map((it) => (
                        <option
                            key={it.count + it.duration}
                            label={t(
                                "common:fields.items." + it.duration, //duration is month/week/day
                                { count: it.count },
                            )}
                            value={it.count + " " + it.duration}
                            className="w-full py-2"
                        ></option>
                    ))}
                </select>
```

And my translations are as follows

```
//hr/common.json
      "items": {
        "day_one": "{{count}} dan",
        "day_other": "{{count}} dana",
        "month_one": "{{count}} mjesec",
        "month_other": "{{count}} mjeseci",
        "week_other": "{{count}} tjedna",
        "week_one": "{{count}} tjedan"
      },
   
   
   //en/common.json
         "items": {
        "day_one": "{{count}} day",
        "day_other": "{{count}} days",
        "month_one": "{{count}} month",
        "month_other": "{{count}} months",
        "week_other": "{{count}} weeks",
        "week_one": "{{count}} week"
      },
```
   

## Screenshots
Here are the two translations 
![en](https://user-images.githubusercontent.com/50072027/163672682-2ac36b85-f657-4665-85b1-6ce7e329bcbb.png)
![croatian1](https://user-images.githubusercontent.com/50072027/163672683-c10e4198-3323-4687-bd8e-6a2a0f03b092.png)

## OS (please complete the following information)
 - Device: Ubuntu 20.04
 - Browser: Chromium Version 100.0.4896.127 (Official Build) snap (64-bit)

**Comment by isaachinman** [comment]
Based on the snippets you've provided, the translation keys _are not_ the same.

**Comment by Nikola-Milovic** [comment]
@isaachinman  Whoops, edited the issue, the translations do match up, it was just a typo as I was simplifying it for this issue.

It's clear to see that 1 month works, 6 months work, but for some reason 3 months doesn't. And the only difference between 6 and 3 months is the count

**Comment by isaachinman** [comment]
I highly doubt this is an issue with `next-i18next`. Can you please open an issue in the main i18next repository?

**Comment by sonianedea21** [comment]
@Nikola-Milovic did you open an issue on the main i18next repository? I can't find it. 
If no, did you find out what the problem was?

**Comment by Nikola-Milovic** [comment]
> @Nikola-Milovic did you open an issue on the main i18next repository? I can't find it. If no, did you find out what the problem was?

The issue was with the language itself, basically Croatian has 2 plural forms. 

```
"exclusivityPeriodItems": {
        "day_one": "{{count}} dan",
        "day_few": "{{count}} dana",
        "day_other": "{{count}} dana",
        "month_one": "{{count}} mjesec",
        "month_few": "{{count}} mjeseca",
        "month_other": "{{count}} mjeseci",
        "week_other": "{{count}} tjedana",
        "week_few": "{{count}} tjedana",
        "week_one": "{{count}} tjedan"
      },
```

There is both `_few` and `_other` forms, there is a specification for this but I dont remember the link, more languages have their own quirks.

**Comment by sonianedea21** [comment]
fixed. i had the romanian translation and it had worked for a long time, my issue was that i had not updated them to the new version. 

used to be 
`   "room_0": "cameră",
    "room_1": "camere",
    "room_2": "de camere",`

now it is 

`    "room_one": "cameră",
    "room_few": "camere",
    "room_other": "de camere",`


fiddle to identify correct plural form is also update https://jsfiddle.net/6bpxsgd4
