### ISSUE TITLE
Some values not showing in email templates

### ISSUE THREAD

**Issue by waptik** [isaachinman/next-i18next#1799]
## Describe the bug
Vales for certain keys don't display in the generated emails as seen in the below screenshots.
I wonder why is that. I might have missed something.

## Occurs in next-i18next version
v11.0.0

## Locale namespace (email.json)
```json
{
  "reset_password_subject": "Asorei.app: Reset password instructions",
  "hi_user_name": "Hi {{name}}",
  "someone_requested_password_reset": "Someone has requested a link to change your password.",
  "password_reset_instructions": "If you didn't request this, you can safely ignore this email and your password will not be changed.",
  "change_password": "Change Password",
  "reset_password": "Reset Password",
  "have_any_questions": "Have questions? We're here to help.",
  "contact_our_support_team": "Contact our support team",
  "user_invited_you": "{{user}} invited you to join the team {{team}} on Asorei.app",
  "system_generated_username": {
    "subject": "Asore.app: System auto-generated username",
    "message": "Because we changed our authentication system, we generated a username for you to use. Your username is: {{username}}",
    "instructions": "To get started, click the link below to request for a new password."
  }
}

```

## Code
A simplified version of the entire code is available at https://gist.github.com/waptik/5aa4a7e57317053ab045273f985503bf

## Expected behavior
The email with username should be like this:
```text
Hi John Doe,

Because we changed our authentication system, we generated a username for you to use. Your username is: john-doe12345
````

## Screenshots
![image](https://user-images.githubusercontent.com/1687551/163678551-6b7cab36-3cd7-475d-a0c6-e265567c9d9f.png)
![image](https://user-images.githubusercontent.com/1687551/163678596-16cc558b-bd39-4a64-b8c2-2c73e8d0baf0.png)
// inside API route https://gist.github.com/waptik/5aa4a7e57317053ab045273f985503bf#file-api-route-ts-L92
![image](https://user-images.githubusercontent.com/1687551/163679323-84f9e49e-adc9-4bf3-a062-d81767343aaa.png)

## OS (please complete the following information)
 - Device: Windows 10
 - Browser: Chromium: 100.0.4896.88 (Official Build) beta (64-bit)](https://brave.com/latest/)

**Comment by isaachinman** [comment]
This package is not intended to be used in API routes. If you do want to use `next-i18next` in API routes, you will need to manually initialise an i18next instance.

**Comment by waptik** [comment]
> This package is not intended to be used in API routes. If you do want to use `next-i18next` in API routes, you will need to manually initialise an i18next instance.

Okay. I thin I did but forgot to add the code to the gist. Here's the code for [getTranslation](https://gist.github.com/waptik/5aa4a7e57317053ab045273f985503bf#file-api-route-ts-L12)

```
// copied from https://github.com/calcom/cal.com/blob/main/apps/web/server/lib/i18n.ts
import i18next from "i18next";
import { i18n as nexti18next } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getTranslation = async (locale: string, ns: string) => {
  const create = async () => {
    const { _nextI18Next } = await serverSideTranslations(locale, [ns]);
    const _i18n = i18next.createInstance();
    _i18n.init({
      lng: locale,
      resources: _nextI18Next.initialI18nStore,
      fallbackLng: _nextI18Next.userConfig?.i18n.defaultLocale,
    });
    return _i18n;
  };
  const _i18n = nexti18next != null ? nexti18next : await create();
  return _i18n.getFixedT(locale, ns);
};

```

Since I did initialize a new instance, is there a way to make it work???
