### ISSUE TITLE
TS issue with <I18nContext.Consumer>

### ISSUE THREAD

**Issue by IdkMan2Usertive** [isaachinman/next-i18next#1807]
## Describe the bug
In React 18 `ReactNode` type has changed and this change affects next-i18next types.
Function passed to `<I18nContext.Consumer>` block incorrectly narrows the return type of the function.

```tsx
<I18nContext.Consumer>
  {({i18n}) => i18n.t('test')}
</I18nContext.Consumer>
```

TS error:
```
TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode'.   Type 'object' is not assignable to type 'ReactNode'. 
```

As I have investigated - `object` is no longer a valid member of the `ReactNode` union type.

A quick fix is to explicitly define the return type of the `t` function:
```tsx
<I18nContext.Consumer>
  {({i18n}) => i18n.t<string>('test')}
</I18nContext.Consumer>
```

## Occurs in next-i18next version
Latest version, 11.0.0.

## Steps to reproduce
I have created a small reproduction repository:
https://github.com/usertive/next-i18next-issue-reproduction

## Expected behavior
I would like not to explicitly define the return type of the `t` function every time I want to use it. I have a very specific use case for which I am using `<I18nContext.Consumer>` and not use `translation()` hook.

## Screenshots
![image](https://user-images.githubusercontent.com/82803183/164191824-1fdb6728-39ab-4f5e-946e-2b6ff2381e8e.png)

## OS (please complete the following information)
 - Device: MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
 - Browser: Chrome 100.0.4896.127 (Official) (x86_64)

**Comment by isaachinman** [comment]
@IdkMan2Usertive This is an issue with upstream i18next types. Please open an issue on the appropriate i18next repository.

cc @adrai

**Comment by IdkMan2Usertive** [comment]
https://github.com/i18next/i18next/issues/1756#issue-1209470611
