### ISSUE TITLE
Accessing rewrite for /api/endpoint triggers react-i18next error

### ISSUE THREAD

**Issue by marckornberger** [isaachinman/next-i18next#1808]
## Describe the bug
Accessing any API file (first noticed after setting up rewrite to proxy to another API) causes "react-i18next:: You will need to pass in an i18next instance by using initReactI18next" warning to be displayed in console logs.

## Occurs in next-i18next version
v11.0.0

## Steps to reproduce
1. Create rewrite in next.config.js
```javascript
const nextConfig = {
  ...
  // API Proxy Redirects
  async rewrites() {
    return [
      {
        source: '/api/login',
        destination: apiAdress + '/login'
      }
    ]
  }
}
```
2. Access localhost:3000/api/login (Browser requires Ctrl+F5 Reload to trigger)
3. Warning logged on console

## Expected behaviour
Do not execute any i18n related Code on rewrites for proxying purposes (or at least add the ability to disable them)

## OS (please complete the following information)
 - Device: Windows 10
 - Browser: Chrome 100.0.4896.127

## Additional context
I already tried using 'ignoreRoutes: ['/api/login/']' in the i18n configuration file, however this didn't resolve the issue

**Comment by isaachinman** [comment]
Please provide a minimal reproduction.

**Comment by marckornberger** [comment]
I actually figured out the issue myself: A component was using the useTranslation() hook inside my _app.js, which was causing the issue, since next-i18next hadn't been initialized at that point.

_app.js:
```javascript
import { appWithTranslation, useTranslation } from 'next-i18next'
import '../styles/globals.css'

function MyApp({ Component, pageProps }) {

  // Usage of useTranslation() before next-i18next is initialized
  const { t } = useTranslation();
  const heading = t('exa_heading');

  return <Component {...pageProps} />
}

export default appWithTranslation(MyApp)
```

Thank you for the quick response anyways. However I am still wondering if it would be possible to make the useTranslation() hook usable in _app.js, since I would like to put elements like my Navbar in there.

**Comment by isaachinman** [comment]
> However I am still wondering if it would be possible to make the useTranslation() hook usable in _app.js

That question has been asked and answered many times in issues on this repo. The short answer is that your hook calls need to be inside the `appWithTranslation` HOC.
