### ISSUE TITLE
404 page after reload with custom localePath & localeSubpaths true

### ISSUE THREAD

**Issue by singgihnn** [isaachinman/next-i18next#181]
## Describe the bug
I knew that we need custom localeStructure when we use custom localePath, so maybe this isn't a bug but rather than it's me that don't know how to configure it.

here's my config:
{
  defaultLanguage: 'id',
  otherLanguages: ['en'],
  localePath: 'src/static/locales',
  localeSubpaths: true,
}

## Steps to reproduce
- I change the language to other language in home page, ex: `localhost:3000` to `localhost:3000/en`
- Hit Reload and I got 404 page

## Expected behaviour
It supposed to be in the home page with language `en`

## Additional context
When I delete the `/en` from url then I hit enter, my localhost successfully open the home page and adding url `/en` automatically.

**Comment by joeyzone** [comment]
I found the same bug

**Comment by isaachinman** [comment]
The locales dir shouldn't affect locale subpaths - that's controlled by `allLanguages`, which is the combination of `defaultLanguage` and `otherLanguages`.

@singgihnn @joeyzone Can one of you please provide a reproducible repository? I can then fix the problem very quickly.

**Comment by joeyzone** [comment]
![image](https://user-images.githubusercontent.com/1586972/52774766-0552cf80-3079-11e9-9563-7f05b518bc1d.png)
![image](https://user-images.githubusercontent.com/1586972/52774778-0d127400-3079-11e9-8917-4beba019db4a.png)

**Comment by isaachinman** [comment]
Where is your `static` dir? @joeyzone It seems you're having a different issue than @singgihnn.

**Comment by joeyzone** [comment]
[123.mp4.zip](https://github.com/isaachinman/next-i18next/files/2864121/123.mp4.zip)
i use example, and code this
![image](https://user-images.githubusercontent.com/1586972/52776142-fc173200-307b-11e9-81e5-657ccb214e3e.png)

**Comment by singgihnn** [comment]
hi @isaachinman I just upload the project here https://github.com/singgihnn/next-starter

**Steps to reproduce:**
Try to change the language to 'en' and hit refresh

**Comment by isaachinman** [comment]
@singgihnn You're using the server middleware incorrectly. Please check the latest docs:

```jsx
server.use(nextI18NextMiddleware(nextI18next))
```

**Comment by singgihnn** [comment]
thanks @isaachinman
