### ISSUE TITLE
Typing error with React 18

### ISSUE THREAD

**Issue by azuken** [isaachinman/next-i18next#1817]
## Describe the bug
NextJS build is failing with React 18 and usage of <Trans> component.

## Occurs in next-i18next version
11.0.0

## Steps to reproduce

```
info  - Loaded env from /.env
Failed to compile.

./src/components/Component.tsx:179:56
Type error: Type '{ freeDays: number; }' is not assignable to type 'ReactNode'.
  Object literal may only specify known properties, and 'freeDays' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal'.

  177 |                     <Trans i18nKey="subscribe.freeDays">
  178 |                       You get
> 179 |                       <span className="family-bold">{{ freeDays }}</span>
      |                                                        ^
  180 |                       &nbsp;starting today
  181 |                     </Trans>
  182 |                   </p>
info  - Checking validity of types .%   
```

## Expected behaviour
No typing errors when using variables in Trans component

## OS (please complete the following information)
 - Device: MBP 2019 16
 - Browser: Chrome 100.0.4896.127

**Comment by isaachinman** [comment]
Typings for the `Trans` component come from `react-i18next`, not this package. Please open an issue there.

**Comment by azuken** [comment]
For tracking : https://github.com/i18next/react-i18next/issues/1483

**Comment by adrai** [comment]
@azuken would such a TypeScript option like `allowObjectInHTMLChildren` work for you?
Please comment here: https://github.com/i18next/react-i18next/issues/1483
And maybe check also this PR: https://github.com/i18next/react-i18next/pull/1492
@isaachinman if you have some inputs regarding that, let us know...

**Comment by adrai** [comment]
> @adrai Since it seems that there is no better solution, yeah it would be great to have this in this package.

fyi: allowObjectInHTMLChildren was already introduced in react-i18next, so you might just update your dependencies

**Comment by adrai** [comment]
> @adrai this is just what I've done and I have no such option in Trans component. I'm importing component from next-i18next, not react-i18next

you might need to delete your node_modules folder... react-i18next is a dependency of next-i18next

**Comment by azuken** [comment]
This is what I'm doing everytime I update packages.
I've just removed yarn lock in case of, same behaviour :

```
info  - Linting and checking validity of types .Failed to compile.

./src/components/Coupon/Confirm.tsx:186:56
Type error: Type '{ freeDays: number; }' is not assignable to type 'ReactNode'.
  Object literal may only specify known properties, and 'freeDays' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal'.

  184 |                     <Trans i18nKey="subscribe.freeDays" allowObjectInHTMLChildren={true}>
  185 |                       You get
> 186 |                       <span className="family-bold">{{ freeDays }}</span>
      |                                                        ^
  187 |                       &nbsp;starting today
  188 |                     </Trans>
  189 |                   </p>

> Build error occurred
```

My code :

```tsx
<Trans i18nKey="subscribe.freeDays" allowObjectInHTMLChildren={true}>
  You get
  <span className="family-bold">{{ freeDays }}</span>
  &nbsp;starting today
</Trans>
```

**Comment by adrai** [comment]
> This is what I'm doing everytime I update packages. I've just removed yarn lock in case of, same behaviour :
> 
> ```
> info  - Linting and checking validity of types .Failed to compile.
> 
> ./src/components/Coupon/Confirm.tsx:186:56
> Type error: Type '{ freeDays: number; }' is not assignable to type 'ReactNode'.
>   Object literal may only specify known properties, and 'freeDays' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal'.
> 
>   184 |                     <Trans i18nKey="subscribe.freeDays" allowObjectInHTMLChildren={true}>
>   185 |                       You get
> > 186 |                       <span className="family-bold">{{ freeDays }}</span>
>       |                                                        ^
>   187 |                       &nbsp;starting today
>   188 |                     </Trans>
>   189 |                   </p>
> 
> > Build error occurred
> ```
> 
> My code :
> 
> ```tsx
> <Trans i18nKey="subscribe.freeDays" allowObjectInHTMLChildren={true}>
>   You get
>   <span className="family-bold">{{ freeDays }}</span>
>   &nbsp;starting today
> </Trans>
> ```

I'm not a TypeScrirpt user, but allowObjectInHTMLChildren is not a Trans prop, but should probably be used like this: https://github.com/i18next/react-i18next/blob/master/ts4.1/index.d.ts#L29

@pedrodurek correct me if I'm wrong

**Comment by pedrodurek** [comment]
yeah @adrai, that's correct! `allowObjectInHTMLChildren` will allow all html elements to accept object as children.

**Comment by azuken** [comment]
@adrai I see no usage example in your link, just interface. I do not understand how to implement this option.

**Comment by adrai** [comment]
Do you mean this? https://react.i18next.com/latest/typescript

**Comment by azuken** [comment]
Ok, I didn't understand that it was an i18n configuration.

But still not working.

My configuration : 

`next-i18next.config.js`

```js
const intervalPlural = require('i18next-intervalplural-postprocessor');

module.exports = {
  i18n: {
    defaultNS: 'translation',
    serializeConfig: false,
    fallbackLng: 'fr-FR',
    locales: ['fr-FR', 'en-US', 'es-ES', 'de-DE', 'catchAll'],
    defaultLocale: 'catchAll',
    interpolation: {
      escapeValue: false
    },
    react: {
      transKeepBasicHtmlNodesFor: ['br', 'strong', 'i', 'p', 'u']
    },
    use: [intervalPlural],
    allowObjectInHTMLChildren: true
  }
};
```

Error :

```
Type error: Type '{ freeDays: number; }' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.
  Object literal may only specify known properties, and 'freeDays' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal | Iterable<ReactI18NextChild>'.

  184 |                     <Trans i18nKey="subscribe.freeDays">
  185 |                       You get
> 186 |                       <span className="family-bold">{{ freeDays }}</span>
      |                                                        ^
  187 |                       &nbsp;starting today
  188 |                     </Trans>
  189 |                   </p>

> Build error occurred
```

**Comment by pedrodurek** [comment]
@azuken Ohh sorry, only `react-i18next` is supporting it right now, I'd recommend to change the react types manually then.
1 - Create a `react.d.ts` file in your src path.
2 - Add the following code to the file:
```
import React from 'react';
type ReactI18NextChild = React.ReactNode | Record<string, unknown>;

declare module 'react' {
  interface HTMLAttributes<T> {
    children?: ReactI18NextChild | Iterable<ReactI18NextChild>;
  }
}
```

**Comment by azuken** [comment]
Ok it's working if I move definition file into src folder, instead in root!

Thank you for your help, is there any ticket, issue, MR opened to track when this will be implemented in this library ?
