### ISSUE TITLE
next-i18next with Material-UI get TypeError: Cannot read property 'sheetsRegistry' of undefined

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [isaachinman/next-i18next#182]
# next-i18next with Material-UI get TypeError: Cannot read property 'sheetsRegistry' of undefined

Good afternoon, trying to use your library with [material-ui](https://material-ui.com/) library. But I get an error:

```
Warn: You have not declared a namespacesRequired array on your page-level comp  onent: ErrorPage. This will cause all namespaces to be sent down to the client  , possibly negatively impacting the performance of your app. For more info, se  e: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependenc  ies

TypeError: Cannot read property 'sheetsRegistry' of undefined
    at Function.module.exports../pages/_document.js.MyDocument.getInitialProps (C:\Users\bboyc\Downloads\hello-world\.next\server\static\development\pages\_document.js:4211:29)
    at Object.loadGetInitialProps (C:\Users\bboyc\Downloads\hello-world\node_modules\next-server\dist\lib\utils.js:44:35)
    at Object.renderToHTML (C:\Users\bboyc\Downloads\hello-world\node_modules\next-server\dist\server\render.js:98:36)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

## Steps to reproduce
I made a simple example with Sandbox:
[Link to example](https://codesandbox.io/s/5k1yxz4o9l)

Could you help me with this bug? Also I use Apollo Client in production.

**Comment by isaachinman** [comment]
Looks related to [this line](https://github.com/mui-org/material-ui/blob/next/examples/nextjs/pages/_document.js#L79) of the `material-ui` library's NextJs example, but I'm not too sure as I don't use that library.

Try following the example and let me know if you still have issues.

**Comment by AlexanderVishnevsky** [comment]
@isaachinman Thank you, this solved my problem. But from today a new version 0.32.0 has been added and now an error occurs:
```
TypeError: this.language.toLowerCase is not a function
    at I18n.loadResources
```
Any thoughts about it?

**Comment by isaachinman** [comment]
I don't seen anything obvious that would be causing that error. Please provide a reproducible example.

**Comment by isaachinman** [comment]
Your sandbox link appears to be working just fine now.
