### ISSUE TITLE
How to translate Layout component of NextJS Application?

### ISSUE THREAD

**Issue by Sotatek-PhuongNguyen4** [isaachinman/next-i18next#1840]
I used Layout components in _app.tsx and I want to translate content inside it but it's seem next-i18next only translate content inside page level.
Is there any solutions?

This is my code (_app.tsx)
<img width="884" alt="image" src="https://user-images.githubusercontent.com/91860823/170472654-7869c55e-970f-433c-a7f1-e27608bcd71d.png">

Thanks a lot!

**Comment by alextaymx** [comment]
+1

**Comment by GabenGar** [comment]
Make a separate namespace for layout and pass it in the response of every single page in the project. Then layout can just use `useTranslation("layout-namespace")`.

**Comment by isaachinman** [comment]
Yes, @GabenGar is correct. Please remember that `_app` itself gets wrapped by `next-i18next`'s `appWithTranslation`, so _anything_ inside `_app` or below can be translated.

**Comment by AkiraVoid** [comment]
Eh, I think maybe you're asking how to translate contents without hooks? As I know there are no such things. If you have some reasons that cannot add hooks into layout component (e.g. this component is from other libraries), you could make a wrapper component.

**Comment by adams100111** [comment]
I had the same problem and passed a translation instance to the layout here is an example:

const LoginPage = () => {}

export async function getStaticProps<GetStaticProps>({ locale }: GetStaticPropsContext) {
    return {
        props: {
            ...(await serverSideTranslations(locale as string))
        },
    }
}

LoginPage.getLayout = function getLayout(page: ReactElement) {
    const translation = undefined//useTranslation();
    return <GuestLayout translation={translation}>{page}</GuestLayout>;
};

export default LoginPage;

**Comment by moskalakamil** [comment]
I think that the best way is to add normally `<Layout />` into _app file:
```typescript
import Layout from "components/layout";
const App = ({ Component, pageProps }: AppProps) => {
   <Layout>
            <Component {...pageProps} />
   </Layout>
}
export default App
```
and in ***every*** file in `page` folder you should add 
```typescript
export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});
```
Then you can normally use `const { t } = useTranslation("common")` in Layout file

**Comment by zakidze** [comment]
> Make a separate namespace for layout and pass it in the response of every single page in the project. Then layout can just use `useTranslation("layout-namespace")`.

how can you give example please

**Comment by moskalakamil** [comment]
> > Make a separate namespace for layout and pass it in the response of every single page in the project. Then layout can just use `useTranslation("layout-namespace")`.
> 
> how can you give example please

In every page you shoud add
```typescript
export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ["layout-namespace"])),
  },
});
``` 
and then in layout component you have acces to this file and you just use
```typescript
const {t} = useTranlsation("layout-namespace")
```

**Comment by zakidze** [comment]
> > > Make a separate namespace for layout and pass it in the response of every single page in the project. Then layout can just use `useTranslation("layout-namespace")`.
> > 
> > 
> > how can you give example please
> 
> In every page you shoud add
> 
> ```ts
> export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
>   props: {
>     ...(await serverSideTranslations(locale, ["layout-namespace"])),
>   },
> });
> ```
> 
> and then in layout component you have acces to this file and you just use
> 
> ```ts
> const {t} = useTranlsation("layout-namespace")
> ```
> 
> _**It's not about app directory**_

i have 

headertranslation.json
footertranslation.json

pagetranslation.json

still dont understand how to do what you told me how

**Comment by moskalakamil** [comment]
> > > > Make a separate namespace for layout and pass it in the response of every single page in the project. Then layout can just use `useTranslation("layout-namespace")`.
> > > 
> > > 
> > > how can you give example please
> > 
> > 
> > In every page you shoud add
> > ```ts
> > export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
> >   props: {
> >     ...(await serverSideTranslations(locale, ["layout-namespace"])),
> >   },
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then in layout component you have acces to this file and you just use
> > ```ts
> > const {t} = useTranlsation("layout-namespace")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _**It's not about app directory**_
> 
> i have
> 
> headertranslation.json footertranslation.json
> 
> pagetranslation.json
> 
> still dont understand how to do what you told me how

If in `Layout` component you use headertranslation.json and footertranslation.json you shoud implement this on every single page:
```typescript
export const getStaticProps: GetStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ["headertranslation", "footertranslation"])),
  },
});
```
and then in Layout component you have access to both of this files

**Comment by zakidze** [comment]
thank you soo much that what i was searching for i will try

**Comment by zakidze** [comment]
what if also translattions are inside folders????
example 
--en
page1.json
page2.json
-----en/dashboard
index-dashboard.json
page-dashboard.json
-----
---en/layouts
header.json
footer.json
what to do in this case
