### ISSUE TITLE
[Error: ENOENT: no such file or directory, rename `some` to `some`

### ISSUE THREAD

**Issue by ksielyov** [isaachinman/next-i18next#1852]
## Describe the bug
run `yarn build`
It gives the error:
```
info  - Generating static pages (54/54)

> Build error occurred
[Error: ENOENT: no such file or directory, rename '/Users/mikhailkiselyov/WebstormProjects/tajwork/.next/export/ru/index/index/Footer.html' -> '/Users/mikhailkiselyov/WebstormProjects/tajwork/.next/server/pages/ru/index/index/index/Footer.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/mikhailkiselyov/WebstormProjects/tajwork/.next/export/ru/index/index/Footer.html',
  dest: '/Users/mikhailkiselyov/WebstormProjects/tajwork/.next/server/pages/ru/index/index/index/Footer.html'
}
error Command failed with exit code 1.
```

## Occurs in next-i18next version
^11.0.0

## Steps to reproduce
1. `yarn build`
done

## Expected behaviour
Correct build

## Screenshots
Not required

## OS (please complete the following information)
```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101
Binaries:
  Node: 14.17.5
  npm: 7.21.1
  Yarn: 1.22.11
  pnpm: N/A
Relevant packages:
  next: 12.1.7-canary.29
  react: 18.1.0
  react-dom: 18.1.0
```

**Comment by isaachinman** [comment]
Please seek help on StackOverflow.

**Comment by ksielyov** [comment]
I am sure, it`s a bug in the next-i18next. Removing one solves the problem

**Comment by isaachinman** [comment]
Then you would need to provide a minimum reproduction. The issue you wrote does  not give any information whatsoever.

**Comment by fxck** [comment]
happens on build as well, can't figure out why

**Comment by SSylvain1989** [comment]
@fxck @GemN @ksielyov hello , did you find a solution about that ? Thanks

**Comment by marco910** [comment]
Had the same issue with my Next.js app. The reason was that I had a route inside of `paths` returned by `getStaticProps` and also inside my `pages` directory. So the route existed twice.
