### ISSUE TITLE
Current language is undefined on initial rendering

### ISSUE THREAD

**Issue by alexpryshchepa** [isaachinman/next-i18next#187]
After upgrading to v0.28.0 we lost **i18n.language** on SSR.

This change is the issue.
![1](https://user-images.githubusercontent.com/20517323/52948436-186be500-3382-11e9-98e3-d1919d783a20.png)

**Comment by isaachinman** [comment]
Hi @alexpryshchepa - the latest is v0.32.0. Can you use that and let me know if you have an issue still? If so, can you please provide a reproducible repo?

**Comment by alexpryshchepa** [comment]
@isaachinman, yes, v0.32.0 has the same issue. You can just add
`constructor() {
    super()
    console.log(i18n.language);
}`
to index.js in the simple example.
Expected to log the current language as it is in v0.27.0 but got undefined.
![1](https://user-images.githubusercontent.com/20517323/52951734-486bb600-338b-11e9-997d-5b0dd33749cb.png)

**Comment by isaachinman** [comment]
That's mostly likely related to the singleton fix via `req` serialisation with #141, and is entirely expected and a _good thing_. If you need the current lang during SSR, you need to use the `req` object.
