### ISSUE TITLE
Browser language detection

### ISSUE THREAD

**Issue by olivier-voutat** [isaachinman/next-i18next#1872]
## Is your feature request related to a problem? Please describe.
I'm creating a new project from scratch.
I want my website to be in three language: en, fr, pt
en is the fallback language.
But if my browser languages has pt-BR and not pt, en is served.

## Describe the solution you'd like
Is there a way to indicate that if browser languages detects pt-BR, fr-CH, etc, it fallback to pt, fr, etc ?

**Comment by isaachinman** [comment]
Browser detection is handled by NextJs directly. Please open any questions/requests on that repo.

**Comment by dvird** [comment]
@isaachinman its not working

**Comment by olivier-voutat** [comment]
> @isaachinman its not working

I found this issue https://github.com/vercel/next.js/issues/18676 and added a proposal solution.
