### ISSUE TITLE
The custom-routing example doesn't work at all

### ISSUE THREAD

**Issue by ahmedmusawir** [isaachinman/next-i18next#188]
## Describe the bug
You must provide a clear and concise description of what the bug is.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
@ahmedmusawir In the future, please fill in the issue templates. They are there for a reason.
