### ISSUE TITLE
ICU support

### ISSUE THREAD

**Issue by Volizik** [isaachinman/next-i18next#1882]
Hi everyone! After updated next-i18next from v7 to v11 can't use i18next-icu plugin. It was in i18n.ts file, and worked fine. But now, when i deleted i18n.ts file I tried to use it in next-i18next.config.js, like documentation says, and received error "ICU is not a constructor".
![image](https://user-images.githubusercontent.com/29004553/175517708-365c6c3f-e18b-43eb-af43-8510647d717a.png)

It works fine if I move ICU initialization to _app.ts like in i18next-icu documentation. 
![image](https://user-images.githubusercontent.com/29004553/175518671-be6c67bd-21aa-4076-9c7e-c735c1510e06.png)

But I not sure it is right way to do it
![image](https://user-images.githubusercontent.com/29004553/175518926-3fac630c-6f72-469d-a0fe-eaceacb42f10.png)

**Comment by isaachinman** [comment]
Please post on StackOverflow for help.

**Comment by vanyadymousky** [comment]
@Volizik Hello! Have you managed to resolve an issue?

**Comment by Volizik** [comment]
@vanyadymousky I resolved it by adding nextI18NextConfig to appWithTranslation, getStaticProps and getServerSideProps manualy like in [documentation](https://github.com/i18next/next-i18next#unserializable-configs). To avoid copy/paste on every single page I've made helpers like createGetStaticProps where puted nextI18NextConfig.

**Comment by OussamaFadlaoui** [comment]
> @vanyadymousky I resolved it by adding nextI18NextConfig to appWithTranslation, getStaticProps and getServerSideProps manualy like in [documentation](https://github.com/i18next/next-i18next#unserializable-configs). To avoid copy/paste on every single page I've made helpers like createGetStaticProps where puted nextI18NextConfig. Don't forget add "serializeConfig": false to your config file ![image](https://user-images.githubusercontent.com/29004553/202409054-63b01c5f-5cb8-411b-bdaa-dab308c6736d.png)

Thanks a lot for this.
