### ISSUE TITLE
initialI18nStore is empty

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#19]
Hi @isaachinman! I'm playing with your plugin and am thinking of replacing my custom i18next integration with it – this will be so awesome!

What I've noticed after a switch is that `initialI18nStore` does not contain any strings at the point when the client-side app is being initialized. Here's what I see in the page source:

```js
__NEXT_DATA__ = {
  props: { initialI18nStore: { en: {} }, initialLanguage: "en", pageProps: {} },
  page: "/hello",
  query: {},
  buildId: "development",
};
__NEXT_LOADED_PAGES__ = [];
__NEXT_REGISTER_PAGE = function(r, f) {
  __NEXT_LOADED_PAGES__.push([r, f]);
};
```

Both client-side and server-side translations work fine, so there is no flickering between i18n keys vs values etc. However, because the namespaces are not in `initialI18nStore`, redundant requests like `static/locales/en/common.json` are being made from the client right after the page load. This can potentially increase _time to interactive_, so I've decided to open this issue. WDYT?

**Comment by isaachinman** [comment]
Here's what I'm seeing in the [example](https://github.com/isaachinman/next-i18next/tree/master/example) app, both in dev and prod modes:

<img width="1438" alt="screen shot 2018-12-01 at 18 04 37" src="https://user-images.githubusercontent.com/10575782/49333827-c772fe80-f593-11e8-9e06-15197075462a.png">

So - you'll need to provide a repo and/or CodeSandbox that reproduces the bug you're experiencing. Thanks!

**Comment by kachkaev** [comment]
Right. I’ll have a look!

**Comment by isaachinman** [comment]
Hey @kachkaev - any update?

**Comment by kachkaev** [comment]
Hi @isaachinman and sorry for a delay with the response. The problem is in my side project, so I’ll be able to study it on an evening or during the weekend. I still rememberer about it and am very interested in digging out the cause.

**Comment by isaachinman** [comment]
Sure, it is probably related to HOCs somehow. I'll reopen if you can reproduce it. Thanks.

**Comment by kachkaev** [comment]
The reason why I was getting an empty store in the first project was simple: I was importing `withNamespaces` directly from `react-i18next` instead of from my local `./i18n.js`😅 

Hope this investigation helps future users 😉 Please not that it's `react-i18next@0.8.0` at the time of writing.
