### ISSUE TITLE
Least you can do is the match the example with the doc ...

### ISSUE THREAD

**Issue by ahmedmusawir** [isaachinman/next-i18next#190]
This is absolutely crazy!! Doc says one thing and example is done in a different way...

**Comment by isaachinman** [comment]
Hi there, I'm sorry the documentation has confused you. This is an open source project which we maintain in our free time for the benefit of others. If you point out the discrepancies, I will have them fixed immediately.

In general the example is the source of truth, as it's an app that actually runs.

In the future I would suggest you modify your tone.
