### ISSUE TITLE
Unexpected spread operator in bundle?

### ISSUE THREAD

**Issue by te-online** [isaachinman/next-i18next#191]
## Describe the bug
It's a little hard for me to describe, because there are a lot of assumptions. I'm sorry! 🙈 

After I replaced the old `i18next` configuration in a `next.js` app and added this module instead, tests are failing, because the _electron browser_ of `cypress` can't understand some spread operators in the bundle. I couldn't really find the place where it's introduced, because comparing compressed bundles is pretty hard and the headless browser of cypress doesn't really give any further details about the error.

However, I could narrow down the problem to the commit where I added this package. 

**I'm kind of ignorantly hoping that it's something simple with this module and you might have an idea what it could be, so that I can avoid reverting back to the old configuration...** 

~~Meanwhile, I'll try to create an example of the problem in a code sandbox. (So that you don't think I'm *completely* lazy...)~~

## Occurs in next-i18next version
I tested `0.28.0` and `0.32.0`.

## Steps to reproduce
- Use in a next.js project
- Use `next/babel` in `.babelrc`
- Try evaluating the resulting bundle in older browser

--------------

**Update:** I was able to fix the issue by transpiling the module with https://www.npmjs.com/package/next-transpile-modules. **Question:** Is it intended that this module still needs to be transpiled? Then we can close this issue!

**Comment by isaachinman** [comment]
Are you using `@babel/preset-env`? It sounds like your transpiled bundle has JavaScript features which are newer than your target (cypress) can understand. You'll need to change your transpilation target to something older.

That's 100% outside the scope of `next-i18next`. We do export CJS but for the most part your Next app is going to be consuming our ESM exports.

I'd recommend posting on StackOverflow for Babel questions. Good luck!

**Comment by te-online** [comment]
Thanks for taking the time to respond. I'm using the presets recommend for `next`:
``` JS
presets: ['next/babel', '@zeit/next-typescript/babel']
```

**Comment by isaachinman** [comment]
If the spread operator is causing a runtime error in your env, you'll need to transpile down. For example, you might need to use [this plugin](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread).

**Comment by te-online** [comment]
Exactly. However, `next/babel` include that already, see https://github.com/zeit/next.js/#customizing-babel-config. 

By default, I believe, node_modules are not transpiled anyways, right? So it doesn't really matter which presets I use. 

Bear with me, if I'm not completely on top of the latest developments regarding the existing ways to export modules 😉, but I had assumed that most modules still need to be exported in common js... 😳

**Comment by isaachinman** [comment]
@te-online Correct, but we _are_ exporting CJS if you want it.

Happy to reopen this if people are upset with that solution/answer.

**Comment by emirotin** [comment]
I've hit this issue with Edge which [doesn't support rest operator in destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility).
I see you're providing CJS but how do I configure next to use it? By default, it seems to follow the `module` entry in the package.json

**Comment by isaachinman** [comment]
Import from `next-i18next/dist/commonjs` if you want the CJS target.

**Comment by isaachinman** [comment]
Just a heads up - it's annoying but I might change the structure of export targets before a prod release. I'm starting to think CJS should be the default so that we don't catch people out like this.

**Comment by te-online** [comment]
@emirotin Not exactly what you're asking for, but I've started using `next-transpile-modules` and added `next-i18next` to the array of untranspiled modules. Works great 😉

**Comment by emirotin** [comment]
@te-online that's what I've done for now but... :)
@isaachinman yeah I could go with dist but I'd like to keep knowledge about your (any) module internal structure outside of our codebase.
I think CJS with some common denominator of transpilation is the way to go at this stage of JS evolution.

**Comment by isaachinman** [comment]
> I think CJS with some common denominator of transpilation is the way to go at this stage of JS evolution.

We have a difference of opinion - I believe that transpilation of modules/deps should fall to the end user, as everyone has different targets. I believe the JavaScript world will slowly move this way, but it'll take years.

In the meantime, as I said, I might change the structure of our exports here. Until then you will need to import from the `commonjs` directory. Not much else to add.

**Comment by emirotin** [comment]
Sure thing, the problem is solvable and thus the rest is more or less debatable. But the current state-of-art is node_modules are normally _not_ transpiled and it's expected from the libraries to deliver the _commonly_ usable bundle.
I think it's mostly because transpiling the entire dependency tree is too slow at the moment.

**Comment by isaachinman** [comment]
> I think it's mostly because transpiling the entire dependency tree is too slow at the moment.

I would not have thought that is the sticking point. What makes you think that? The problem is that it requires a bit of a paradigm shift in the JavaScript world, and will require a lot of new tooling.

**Comment by emirotin** [comment]
Why do projects like Next.js exclude `node_modules` from transpiling? It should make no harm, right? Like if the code is already ES5/6/2017/whatever it shouldn't harm re-transpiling it, correct? And the tooling is in place, webpack is already bundling stuff, babel can transpile any module. So why? Because the dependency tree of the modern real-world app is deep and wide and re-transpiling it on a file change is _slooooow_.

**Comment by isaachinman** [comment]
> Like if the code is already ES5/6/2017/whatever it shouldn't harm re-transpiling it, correct?

No, it's actually dangerous to re-transpile code. Anyways, if you are interested in this topic, a lot of the discussion takes place in the NextJs repo, and I can say that some of the core maintainers are actively working on a solution to this exact issue of dep transpilation.

**Comment by emirotin** [comment]
Huh, interesting. Would be thankful for the link as well as some
post/article why retranspiling is dangerous
