### ISSUE TITLE
Next.js App fails to start with next-i18next-middleware.js in server.js ...

### ISSUE THREAD

**Issue by ahmedmusawir** [isaachinman/next-i18next#193]
Everything works without the middleware, but as soon as I add that, in fact, added the same server.js as the example, I get the following:
```
(node:80820) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `allLanguages` of 'undefined' or 'null'.
    at _default (/Volumes/HDD80GB/Users/moose/Documents/_DEV/react-apps/deep_cast/dc_next_pwa/node_modules/next-i18next/dist/commonjs/middlewares/next-i18next-middleware.js:29:7)

    at /Volumes/HDD80GB/Users/moose/Documents/_DEV/react-apps/deep_cast/dc_next_pwa/server.js:15:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:80820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:80820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
Mooses-High-Sierra:dc_next_pwa moose$ node -v
v8.12.0
```

Also, to even get up to here I had to replace my i18n.js from the following:

```
import NextI18Next from 'next-i18next';

const NextI18NextInstance = new NextI18Next({
	defaultLanguage: 'en',
	otherLanguages: ['de', 'es'],
	localeSubpaths: true,
});

export default NextI18NextInstance;

/* Export class methods as named exports. This is a must! */
export const {
	i18n,
	appWithTranslation,
	withNamespaces,
	Link,
	Trans,
} = NextI18NextInstance;

```
To the following: 
```

const NextI18Next = require('next-i18next').default;

const NextI18NextInstance = new NextI18Next({
	defaultLanguage: 'en',
	otherLanguages: ['de', 'es'],
	localeSubpaths: true,
});

```
Because, otherwise, the server won't start with this error:
```SyntaxError: Unexpected token import```

**Comment by isaachinman** [comment]
Transpiling your server code is up to you. Can you please provide a reproducible example? Are you exporting your class?

**Comment by isaachinman** [comment]
@ahmedmusawir If you are having troubles using this package, I would request that you open **one** issue with a link to a reproducible example (repo), and a clear account of what is going wrong.

**Comment by ahmedmusawir** [comment]
Thank you very much for your reply. Great job with the plugin by the way. The app's lang support is functional without this plugin, only I'm having some issues at the first load. Here is a working repo:

https://github.com/ahmedmusawir/dc_next_pwa_stage_7

Plz let me know if I'm doing something wrong. Thanx in advance.

**Comment by isaachinman** [comment]
Please keep your questions contained to a single issue.
