### ISSUE TITLE
Is there any simple tutorial?

### ISSUE THREAD

**Issue by mehrad77** [isaachinman/next-i18next#197]
I read all the readme.MD file but I can't find a way of how to add this lib to my project. Is there any tutorial or walkthrough (step by step) on the internet?

**Comment by isaachinman** [comment]
Hi @mehrad77. No, to my knowledge there is no tutorial or walkthrough yet. Can you explain what information you need? If the README isn't explanatory enough, we should improve it.

**Comment by mehrad77** [comment]
Sorry for the delayed answer.
well, I can not understand the `3. Project setup` step. where should I config it after adding NPM package? how can I trigger switching language?

even a simple youtube video or a post in [dev.to](https://dev.to) or anywhere else would be helpfull. a walkthrough of adding it to the project. step by step for dummies.

**Comment by isaachinman** [comment]
I will consider writing an article and posting it on Medium. Unfortunately it takes a lot of time to do these walk throughs and gather all the necessary images, etc.

For now, are there any specific questions I can answer?

**Comment by mehrad77** [comment]
Thank you for considering.
No, I'll wait for it. <3

**Comment by isaachinman** [comment]
Okay, not exactly sure when I will have time. It will be at least 1-2 weeks. Thank you for your patience.

**Comment by isaachinman** [comment]
Hey @mehrad77, I wrote [an article for you](https://medium.com/@isaac_74258/creating-localised-nextjs-apps-with-next-i18next-f01d5e610307). Let me know if it helps.

**Comment by mehrad77** [comment]
Thank you, Well it helped me to get the first insight and not get confused at first.

**Comment by isaachinman** [comment]
Any suggestions or feedback? Anything you think needs more clarification?

I was thinking also of creating a diagram to show how the whole system works between the server and client.
