### ISSUE TITLE
Localized Route

### ISSUE THREAD

**Issue by hubydev** [isaachinman/next-i18next#199]
Hi,

I've been looking for a way to create localized route for each language using next-i18next, but I haven't found anything that could actually help.

I need to have my route as follow:

EN - example.com/products/car/red-toyota
FR - example.com/produits/voiture/toyota-rouge

I believe it should be done in the middleware? Also if we are on the EN page, how can we trigger a full page reload and display the FR url?

**Comment by isaachinman** [comment]
> I've been looking for a way to create localized route for each language using next-i18next

You'll need to declare custom routes in your server. There is an example of this in the README.

> Also if we are on the EN page, how can we trigger a full page reload and display the FR url?

We don't do hard reloads. One of the main points of this package is supporting multiple locales without breaking SPA principles.
