### ISSUE TITLE
Losing language when page get's reload

### ISSUE THREAD

**Issue by RizziWilliam** [isaachinman/next-i18next#202]
## Describe the bug
When in home and i set the langague of the page to en (pt is my default) and go to other page, let's say contact and go back to home the language go back to pt.

## Occurs in next-i18next version
version 0.32.0

## Expected behaviour
Should not lose the set language.

## OS (please complete the following information)
 - Browser: Chrome

## Additional context
When going back to the home page, it get's reload.
Sorry for the bad english.

**Comment by RizziWilliam** [comment]
Just realize that no cookie ins been saved.

**Comment by isaachinman** [comment]
> Just realize that no cookie ins been saved.

Do you think this is the fault of `next-i18next`, or something else? Please provide a reproducible example.

**Comment by RizziWilliam** [comment]
Everything works fine, e set up the cookies in options and it appears on the i18n object, but just dont save the langague when it gets changed. 

I'm using Router.push to change the routes, it do work for other pages, but for the Home page ('/') this get the page to reload's and then the language get to default value.

Can't link repo because is private (company).

This is my I18 options.

```const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
  defaultNS: 'phrases',
  serverLanguageDetection: false,
  browserLanguageDetection: false,
  defaultLanguage: 'pt',
  otherLanguages: ['en'],
  cookie: 'language',
})```

**Comment by isaachinman** [comment]
You're disabling `serverLanguageDetection`. That disables cookie set/detect functionality. That's what it means.

**Comment by RizziWilliam** [comment]
Just for the record, i do have to get serverLanguageDetection and browserLanguageDetection to true for the cookie to work, when setting false for one of then the cookie was getting saved but when the page was reload it loses the set language and go to the default language. 

Thanks for the quick feedback, 👍
