### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by RizziWilliam** [isaachinman/next-i18next#205]
It does support Edge?

**Comment by isaachinman** [comment]
CJS export targets latest Node. See the [babelrc ](https://github.com/isaachinman/next-i18next/blob/master/.babelrc).

Also see #191.

If people want to request different targets for the CJS export, I will consider that.

**Comment by RizziWilliam** [comment]
I'm using the next-i18next, it do work's fine in chrome and firefox, but now on edge things are just not work. For example i have a title that uses the translation function, and now it just don't appears (if i inspect the dom tree the text is there). I go back to a point where the next-i18next wasn't being using yet and it do work's. You can check in here https://cwi.com.br/.

**Comment by isaachinman** [comment]
Do you understand my point about transpilation targets?

**Comment by RizziWilliam** [comment]
Not really. I have been looking in the code and find out that em the link component of next-i18next, there is a const with name 'as' and this is a reserved word and edge don't seen to work like chrome that accept it.

```const {
      as,
      children,
      href: hrefProp,
      lng,
      nextI18NextConfig,
      ...props
    } = this.props;```

I already try to use babel costume config from next.js to use @babel/plugin-transform-reserved-words but i don't think this work in file's in node modules. 
Don't really know what to do to get this to work.

**Comment by isaachinman** [comment]
Hi @RizziWilliam. As far as I know, `as` is [not a reserved word in JavaScript](https://www.w3schools.com/js/js_reserved.asp).

The file I linked is our `babelrc`, which tells Babel what targets we would like to transpile to. Our target for CJS is the latest Node, as I've said.

**Comment by isaachinman** [comment]
Depending on if this is a transpilation/JS-feature issue or some other sort of "reserved keyword" issue, we can decide how to proceed. Let me know.

**Comment by RizziWilliam** [comment]
Ok, i do found a away to get this to work, when using next we create a next.congif.js, in this file we have : 

```
 webpack(config, options) {
config.module.rules.push({
      test: /\.(txt|jpg|png|svg|ico)$/,
      use: [
        {
          loader: 'url-loader',
          options: {
            limit: 10000,
            name: '[path][name].[hash].[ext]',
            publicPath: '/_next',
          },
        },
      ],
    })
}
```
what i did was also put this inside webpack : 
```
config.module.rules.push({
      test: /\.js$/,
      include: /node_modules/,
      use: [options.defaultLoaders.babel],
    })
```

**Comment by isaachinman** [comment]
Yes that's correct - you're transpiling the dep to your specific target. That said, can you copy/paste your Babel settings? I'm fine to change our target to make this easier for you and others.

**Comment by RizziWilliam** [comment]
I actually don't have a custom babel config, it only uses the babel config from the next.js.

**Comment by isaachinman** [comment]
That's a really good point - we should transpile to the same target as Next.

**Comment by isaachinman** [comment]
Hey @RizziWilliam - with v0.36.0 we are transpiling the CJS output to the exact same target that NextJs does. This means if you don't want to transpile your deps you can consume `next-i18next/dist/commonjs` for the same browser support that NextJs delivers out of the box.

**Comment by 2WheelCoder** [comment]
@isaachinman Thanks for your work here. My next app is being compiled to a static site using `yarn run build` and `yarn run export`. Unfortunately, Edge and IE failed with this error when I upgraded from `0.8.0` to `0.32.1`:

`SCRIPT 1028: Expected identifier, string or number`

I just upgraded to `0.36.0` and updated my config file to use `i18next/dist/commonjs`:
```
const NextI18Next = require('next-i18next/dist/commonjs').default

const options = {
  defaultLanguage: 'en',
  otherLanguages: ['fr'],
}
module.exports = new NextI18Next(options)
```

Edge now loads correctly. IE has some other errors but they may not be related to this project. I think it'd be useful to document the commonjs target in the README for others who experience this same issue. Thanks!

**Comment by isaachinman** [comment]
Hi @2WheelCoder - a couple things:

This project does not support `export` explicitly as it breaks universal rendering. See the [README](https://github.com/isaachinman/next-i18next#notes).

Second, what exactly would you like to have added to the README? [The example targets the CJS export](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/i18n.js#L3).

**Comment by RizziWilliam** [comment]
Hey, going to update to the new version. Thank you for the attention on this issue 👍

**Comment by isaachinman** [comment]
@RizziWilliam Please let me know if it fixes your issue!

**Comment by RizziWilliam** [comment]
@isaachinman it's working as expected in edge (and the others browser's, didn't look IE). Doesn't need do put any code on next.config for this to work anymore. Thank you for the quickly fix.

**Comment by 2WheelCoder** [comment]
@isaachinman Apologies, I missed that example.

I haven't added the site's second language yet. Looks like I'll have to think through my usage of this package when I do. I only need to toggle translations on the clientside so perhaps all I need is react-i18next, not this package...

**Comment by isaachinman** [comment]
@2WheelCoder One of the main reasons you might want SSR (especially in the context of localisation) is for indexing. Just something to keep in mind. Good luck in your exploration!

**Comment by isaachinman** [comment]
@RizziWilliam I am very glad to hear it.

**Comment by 2WheelCoder** [comment]
Yeah, that's true. The main reason I went with Next was that I could switch over to SSR when we need it and that may be the trigger. But for the next month or so we are supporting only one language so the static site setup is simple to manage.

**Comment by isaachinman** [comment]
@2WheelCoder The new serverless stuff in v8 may be of interest to you.
