### ISSUE TITLE
How to use translate

### ISSUE THREAD

**Issue by winhackger** [isaachinman/next-i18next#206]
I add new file for translate.
can not translate

**Comment by isaachinman** [comment]
Please provide a reproducible example.

**Comment by winhackger** [comment]
import React from 'react'
import PropTypes from 'prop-types'

import { withNamespaces, Link } from '../i18n'

class SecondPage extends React.Component {

  static async getInitialProps() {
    return {
      namespacesRequired: ['second-page'],
    }
  }

  render() {
    const { t } = this.props
    return (
      <React.Fragment>
        <h1>{t('h1')}</h1>
      </React.Fragment>
    )
  }
}

SecondPage.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withNamespaces('second-page')(SecondPage)
==============

if i have new file ex-page.json
i do like this
namespacesRequired: ['second-page, 'ex-page'],

**Comment by winhackger** [comment]
`import React from 'react'
import PropTypes from 'prop-types'

import { withNamespaces, Link } from '../i18n'

class SecondPage extends React.Component {

  static async getInitialProps() {
    return {
      namespacesRequired: ['second-page'],
    }
  }

  render() {
    const { t } = this.props
    return (
      <React.Fragment>
        <h1>{t('h1')}</h1>
        <Link href='/'>
          <button
            type='button'
          >
            {t('back-to-home')}
          </button>
        </Link>
      </React.Fragment>
    )
  }
}

SecondPage.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withNamespaces('second-page')(SecondPage)`
==========
i have new file ex-page.json

i do like this
namespacesRequired: ['second-page', 'ex-page'],

**Comment by isaachinman** [comment]
Sorry, I don't understand your question.

**Comment by winhackger** [comment]
in project i add new file in static -> locales -> en -> ex-page.json

ex. ex-page.json

```json
{"title": "Hello"}
```

now i use same like this. 
but not work.
i don't understand how to use
```js
import React from 'react'
import PropTypes from 'prop-types'

import { withNamespaces, Link } from '../i18n'

class SecondPage extends React.Component {

  static async getInitialProps() {
    return {
      namespacesRequired: ['ex-page'],
    }
  }

  render() {
    const { t } = this.props
    return (
      <React.Fragment>
        <h1>{t('title')}</h1>
    )
  }
}

SecondPage.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withNamespaces('second-page')(SecondPage)
```

**Comment by isaachinman** [comment]
If you want to use a namespace within a component, you need to pass it into the `withNamespaces` HOC. So:

```jsx
withNamespaces(['second-page', 'ex-page'])
```
