### ISSUE TITLE
[Question] Custom language detection middleware (SSR)

### ISSUE THREAD

**Issue by WardVH** [isaachinman/next-i18next#208]
Hi there,

First off thanks for the effort of creating the package.
I'm currently trying to migrate our custom i18next implementation with next to using this package.

We are doing detection of the language based upon a custom header that is passed down.
We used to have a custom i18nextMiddleware (with the i18next-express-middleware package) that detected this for us - and then we were able to set the order detection to only use that specific detection method.

Do you have any suggestions on setting the default language based upon this provided header?
We don't really need in-app language switching so we should be fine with just setting the default language correctly once when initialising the i18next config but since we don't have access to that header when building the server I think that approach is in possible.

Do you have any suggestions on how I can perhaps re-use our custom middleware in order to detect the language?

Kind regards,
Ward

**Comment by isaachinman** [comment]
Hi @WardVH

> since we don't have access to that header when building the server I think that approach is in possible

Not sure I understand - languages should be selected at runtime, not build time. Default language cannot be set at runtime - that's a configuration-level option. It wouldn't make sense to choose a default language based on a user's headers. The default language is the default language _of your app_. Can you explain your desired approach?

**Comment by WardVH** [comment]
Hi @isaachinman 

Thanks for the fast reply.

I think our use-case is a bit odd. We have multiple entries into our application (each with their own custom header) and users don't have the functionality to switch languages in the application so we don't really need to supply this.

I was able to set the initial language by using a using a custom express middleware and some knowledge from your middleware implementation and disabling the browserLanguageDetection.

`
server.use(function(req, res, next) {
    if (isI18nRoute(req.url)) {
      req.lng = req.get("custom-header") || "nl-NL";
    }
    next();
  });
`
The only problem at this stage is that we have a fallback mechanism set:
So "nl-NL" should fall back to "nl" and finally even to "en".

Seems like it's doing that on the client but not on the server. Any idea what could cause this?

Kind regards,
Ward

**Comment by WardVH** [comment]
Hi @isaachinman 

Seems I was able to achieve the same thing with the following configuration:

```
const languageDetectionBasedUponHeader = {
  name: "language-detection-header",
  lookup: (req, res, options) => {
    return req.get("header") || "nl-NL";
  }
};

const NextI18NextInstance = new NextI18Next({
  debug: true,
  browserLanguageDetection: false,
  fallbackLng: inUseLocales.toFallbackLanguagesObject(),
  otherLanguages: inUseLocales.toString(),
  customDetectors: [languageDetectionBasedUponHeader],
  detection: {
    order: ["language-detection-header"]
  }
});
```

The issue with the fallback logic still occurs tho.

Kind regards,
Ward

**Comment by WardVH** [comment]
Seems like it might be due to the fact that i'm using the following structure as the fallbackLng

```
{ 'de-BE': [ 'de', 'en' ],
  'fr-BE': [ 'fr', 'en' ],
  'nl-BE': [ 'nl', 'en' ],
  'de-CH': [ 'de', 'en' ],
  'fr-CH': [ 'fr', 'en' ],
  'it-CH': [ 'it', 'en' ],
  'de-LU': [ 'de', 'en' ],
  'fr-LU': [ 'fr', 'en' ],
  'fr-CA': [ 'fr', 'en' ],
  'fr-FR': [ 'fr', 'en' ],
  'nl-NL': [ 'nl', 'en' ],
  'de-AT': [ 'de', 'en' ],
  'de-DE': [ 'de', 'en' ],
  'da-DK': [ 'da', 'en' ],
  'fi-FI': [ 'fi', 'en' ],
  'it-IT': [ 'it', 'en' ],
  'no-NO': [ 'no', 'en' ],
  'sv-SE': [ 'sv', 'en' ],
  default: [ 'en' ] }
```

When looking at your code at https://github.com/isaachinman/next-i18next/blob/4b318fe11ce71cfbf4ee0ac8c015eba27c0b0341/src/hocs/app-with-translation.js#L87
it feels to me that you only support one fallbackLng.

Can this be true?

**Comment by isaachinman** [comment]
A couple things to note:

1. We do not support regional locales (yet) whatsoever
2. Fallback language is for the entire app. There is no concept of per-language fallbacks

**Comment by WardVH** [comment]
Well, 

Since it already works on the client-side I had a little look at how the namespaces are loaded on the server side (see https://github.com/isaachinman/next-i18next/pull/209).

Can you help me with this? I'm not afraid to contribute so please let me know how I can help you.

Kind regards,
Ward

**Comment by isaachinman** [comment]
@WardVH This is not something we can or will support. This package wraps `react-i18next` and simply extends the config options. Please see [the documentation](https://react.i18next.com/latest/i18next-instance) for more info.

**Comment by WardVH** [comment]
@isaachinman 

From my understanding this package wraps `react-i18next` yes which is a wrap of the `i18next` package.

Looking at your documentation link they link the [docs](https://www.i18next.com/configuration-options.html) where you can find more information about the fallbackLng configuration setting.

They even explain how you can do the fallback that I am trying to achieve [here](https://www.i18next.com/principles/fallback#fallback-language). 

So conclusion for me is that this package should support this and even already support this client-side.

**Comment by isaachinman** [comment]
@WardVH Ah, looks like you're totally right. @jamuhl - do you mind confirming that? I wasn't even aware that `fallbackLng` could be a string, array, _or_ object... Not my first choice but if it's supported by `i18next` and `react-i18next` passes it through, we should indeed support it here.

**Comment by isaachinman** [comment]
Hey @WardVH - although your work with #209 is in progress and a great contribution, this issue was originally about middleware. Can we safely close it, or do you want to continue discussing?

**Comment by jamuhl** [comment]
@isaachinman yes it's supported...but never meant to be used like this:

```js
{ 'de-BE': [ 'de', 'en' ],
  'fr-BE': [ 'fr', 'en' ],
  'nl-BE': [ 'nl', 'en' ],
  'de-CH': [ 'de', 'en' ],
  'fr-CH': [ 'fr', 'en' ],
  'it-CH': [ 'it', 'en' ],
  'de-LU': [ 'de', 'en' ],
  'fr-LU': [ 'fr', 'en' ],
  'fr-CA': [ 'fr', 'en' ],
  'fr-FR': [ 'fr', 'en' ],
  'nl-NL': [ 'nl', 'en' ],
  'de-AT': [ 'de', 'en' ],
  'de-DE': [ 'de', 'en' ],
  'da-DK': [ 'da', 'en' ],
  'fi-FI': [ 'fi', 'en' ],
  'it-IT': [ 'it', 'en' ],
  'no-NO': [ 'no', 'en' ],
  'sv-SE': [ 'sv', 'en' ],
  default: [ 'en' ] }
```

sample `de-CH` already will fallback to `de` before fallback to `en`

it's more about eg. my italian friends prefer reading spanish before english

```js
{
it-IT: ['es', 'en'],
default: 'en'
}
```

**Comment by WardVH** [comment]
@jamuhl The second "en" is indeed not necessary since we have the en as the default fallback configured right ? Why is not meant to be used like that ? 

The main reason we use the current setup is that it allows us to translate everything for EN and then override some specific keys for en-AU for example without having to translate the entire set of translations.

**Comment by jamuhl** [comment]
because the failover regional locale (en-AU) will already per default fallback to the language `en` before going to the defined fallbackLng: https://www.i18next.com/principles/fallback#locals-resolving

**Comment by WardVH** [comment]
@jamuhl That's super interesting but does this package also load both languages (`en-AU` and `en`)  server side?

**Comment by jamuhl** [comment]
that should all be handled in the i18next internals - only setting `load: 'languageOnly|currentOnly'` on init will change this behaviour

**Comment by WardVH** [comment]
Okay, but this package does handle the loading of the namespaces right? From what i could read from the code (and my understanding of it) it does only load the initialLanguage it's namespaces. So it wouldn't load the per default fallback when using a regional locale. 

@isaachinman Is that also a reason why you don't support regional locales?

@jamuhl aside from our misusing the fallback configuration - it's still is somewhat supported and thus the corresponding PR isn't a waste of time? :)

**Comment by isaachinman** [comment]
So: we are setting `config.load` to `currentOnly` [here](https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.js#L17). You can indeed override this via the config provided at the time of class instantiation, but locale subpaths probably aren't going to work as expected... never tried it myself.

@WardVH Did you mean that you have regional locales working client side in a `next-i18next` app?

> my guess it was design decision to keep things simpler in the start

Yeah, that's right. We can probably support regional locales in subpaths at some point, but the whole thing ends up becoming so opinionated, and users will complain. We'd probably end up asking users to provide a subpath string for each locale, or something.

> Okay, but this package does handle the loading of the namespaces right

Yes, of course. We need all locales and namespaces loaded prior to SSR. Not just the `initialLanguage`. The express middleware will determine which language to assign to a given `req`, and the top-level `getInitialProps` will pick this up and serve it accordingly.

**Comment by WardVH** [comment]
Some insights to our setup:
We have multiple domains (regional based) that are all matched with a specific locale:
For example: 
- en-be, nl-be, fr-be and de-be

We are using PhraseApp for managing the translations but they are just JSON files that we download into our application. So we have folders for each locale and for the languages. 

It's capable to use keys from the en-BE JSON files and fallback to the en JSON files when needed.

So we don't really need to have the regional locales in subpaths since the regional locales are defined by the domains.

We have issues with our current solution (setup pre existence of this package) where it sometimes fails to load the JSON files (the namespaces are just empty for some reason). We are not sure if it's even related to the current implementation and it's not something server related / racing conditions related to our hosting solution (kubernetes).

In the end it's always a good idea to move away from a custom implementation if you are unsure about the way it performs, that's why I tried to switch to using this package and discovered the issues with our current config of the fallback languages.

> Yes, of course. We need all locales and namespaces loaded prior to SSR. Not just the initialLanguage. The express middleware will determine which language to assign to a given req, and the top-level getInitialProps will pick this up and serve it accordingly.

Does that mean that if we set the initialLanguage to `en-BE` for example (if we change the `config.load`) that the correct namespaces will be loaded SSR side?

**Comment by jamuhl** [comment]
i lost you with the word "phraseapp" -> you shall use our service  https://locize.com if using i18next 🥺

**Comment by WardVH** [comment]
@jamuhl I don't really see why it would be a problem that we use PhraseApp for the translations itself.
It shouldn't have any impact on the usage of i18next right?

**Comment by jamuhl** [comment]
@WardVH it was a joke...it was about i18next is open source but also we provide a translation management coming with it - which is https://locize.com and not phraseapp ;)

for sure has not impact on this working or not...

**Comment by isaachinman** [comment]
@WardVH Thanks for explaining your setup. In general, that's not really how `next-i18next` is intended to work. Do you mean that you're proxying a single Node application to multiple subdomains, and then (at runtime) trying to figure out what subdomain you're on and serve the right language?

Why not run one app per subdomain and hardcode the language as an environment variable? Seems a lot simpler.

Otherwise, why not hook into your `_app`'s `getInitialProps`, figure out the subdomain , override the language there?

**Comment by palaumarc** [comment]
Hi @isaachinman,

we are following the approach you mentioned in the last message.

> Otherwise, why not hook into your _app's getInitialProps, figure out the subdomain , override the language there

However, it is always loading default language translations. Changing it in the client works perfectly, so I think I am missing something when doing it in _app.js

A simplified example is something like this:

__app.js_
```
class CustomApp extends App {
  static async getInitialProps({ ctx, Component }) {
    if (req) {
      const countryId = requestUtils.getCountryFromSubdomain(req);
      const language = languageUtils.getLanguageByCountryId(countryId);
      await i18n.changeLanguage(language)
    }
    // do more non related stuff
  }
}
```

What we see is that it always loads default language specified in our i18n config, instead of subdomain one.

Does it should work or we are following a wrong approach?

Thanks!

**Comment by isaachinman** [comment]
@palaumarc You need a custom language detector at the i18n level.
