### ISSUE TITLE
When i use next-i18next not return ssr

### ISSUE THREAD

**Issue by chayakornwc** [isaachinman/next-i18next#210]
## Describe the bug
You must provide a clear and concise description of what the bug is.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
How do you expect me to help with this in any way, whatsoever? Please provide reproducible examples when opening issues, and pay attention to the issue templates - they're there for a reason.

**Comment by chayakornwc** [comment]
@isaachinman  Before that's i use
```
await server.use(nextI18NextMiddleware(nextI18next))
```
that's not have promise error but my next js application not return server side rendering

**Comment by isaachinman** [comment]
So your `server` is `undefined`? Please post on StackOverflow.

**Comment by chayakornwc** [comment]
👍

**Comment by chayakornwc** [comment]
Here is more detail
```
next-i18next-middleware.js:21:10)
    at app.prepare.then 
    at process._tickCallback 
(node:33387) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33387) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
i'm not sure that's error from express

**Comment by isaachinman** [comment]
That doesn't tell me anything, you'd need to post the full error. I'm quite sure you should post this type of question on StackOverflow. Thanks.
