### ISSUE TITLE
Transpile CJS to the same target as NextJs

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/next-i18next#212]
https://github.com/isaachinman/next-i18next/issues/205#issuecomment-468627569

**Comment by rsslldnphy** [comment]
Hi @isaachinman , i noticed you've cut a release of this but haven't pushed it to npm yet (though you have pushed another release made on the same day). Just checking if this was an oversight or if you're planning on pushing it soon? Thanks.

**Comment by isaachinman** [comment]
Hey @rsslldnphy, it was both an oversight and intentional - wanted to check on something beforehand. Released v0.36.0 just now.

Are you consuming the CJS export? Can you let me know if this ends up working well for you?

**Comment by rsslldnphy** [comment]
Yes - can confirm that's fixed our issue! Thanks @isaachinman  😄.
