### ISSUE TITLE
AppWithTranslation class can break HOC logics

### ISSUE THREAD

**Issue by mshahov** [isaachinman/next-i18next#22]
I came with an issue using appWithTranslation HOC. It seems that in HOC we have a call to getInitialProps of wrappedcomponent, but this can easily break many ongoing projects as they might rely on something which is set in the initialprops of _app.js. 

`
// Run getInitialProps on wrapped _app
      if (WrappedComponent.getInitialProps) {
        const { pageProps: wrappedPageProps, ...rest } = await WrappedComponent
          .getInitialProps({ Component, ctx })
        pageProps = {
          ...pageProps,
          ...wrappedPageProps,
        }
        regularProps = rest
      }
`

**Comment by isaachinman** [comment]
Not sure what you mean. Can you provide a reproducible example via CodeSandbox?

**Comment by isaachinman** [comment]
Closing due to lack of response. I'll reopen if you provide a reproducible example.
