### ISSUE TITLE
namespaceRequired on LoadNamespace(Component)

### ISSUE THREAD

**Issue by RizziWilliam** [isaachinman/next-i18next#222]
Hey @isaachinman, here i go again. After the update to v0.36.0 a warn start to appears on my console.
```
You have not declared a namespacesRequired array on your page-level component: LoadNamespace(Component).
```

I already look into my page level components and every single one of then is being export with his nameSpace and the also have namespaceRequired on the getInitialProps. Don't know if this is something about the new version or if this is something a change in the code, hoping that you can give some more info about that. Everything still work as expected.

**Comment by isaachinman** [comment]
Hey @RizziWilliam, sorry you continue to experience issues. Which version did you upgrade from? It would be helpful to know the diff. Do you have a link to the repository?

**Comment by RizziWilliam** [comment]
I was using version v0.32.0 before upgrade to the new one. I can't link the repository because it's form the company that i work and it's private (sorry about that).

**Comment by isaachinman** [comment]
> that's deep in the react tree (component inside component inside a page from example) i do export him withnameSpace, don't know if this could be causing the warning to show up.

No, that's perfectly expected and should be fine. Moreover, the warning is at the [app-with-translation](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L42) level and is not triggered by `withNamespaces`.

Unfortunately I'm really busy at the moment and won't be able to look into this unless there's a reproducible example.

**Comment by RizziWilliam** [comment]
@isaachinman hey, thanks for the feedback. That's ok, i will take a close look into this by myself in the future. Will let you know when i have a update about this problem.

**Comment by isaachinman** [comment]
Okay, thanks.

**Comment by isaachinman** [comment]
Hi @RizziWilliam - any update?

**Comment by RizziWilliam** [comment]
@isaachinman hey i couldn't give the properly attention for this because of the others things i have to do, but what i figure out is that this happens in the pages that get export with others things, for example : 
```
export default withnameSpaces('phrases')(withResponsive(Perfil))
```

withResponsive is responsible to tell me if the device is a desktop or a phone.
Think this could be something i'm doing wrong.

**Comment by isaachinman** [comment]
Hi @RizziWilliam - sorry, can't help unless I know what `withResponsive` is. In general, `withNamespaces` comes directly from `react-i18next` and provides the wrapped component with a `t` (translate) function as a prop. It seems like you're wrapping a wrapper, which might not be passing props along correctly. Not entirely sure.

The "You have not declared a namespacesRequired array" error is an entirely different issue.

**Comment by RizziWilliam** [comment]
@isaachinman Hey, finally get some time to take a look into this. The problem wasn't with next-i18next, as i said before this happens when i have a page that is export with others things, the real problem is the ```withResponsive```, it's a wrapper and when a export the page, let's say Home, with it i lose the getInitialProps, then it doesn't get execute by the the ```_app.jsx```. Looking into the next.js docs this is said. That's the link for the issue in the next GitHub https://github.com/zeit/next.js/issues/7216#event-2316761259.
