### ISSUE TITLE
i18next object always being console.logged event with debug: false

### ISSUE THREAD

**Issue by marcelothomaz** [isaachinman/next-i18next#226]
## Describe the bug
Even with debug:false when initializing, I always get console.log with several i18next objects being logged

## Occurs in next-i18next version
      "next": "^8.0.3",
      "next-i18next": "^0.34.0",

## Steps to reproduce
Just initialize as per documentation:
```
const { localeSubpaths } = require('../next.config').publicRuntimeConfig
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
   otherLanguages: ['pt', 'es'],
   defaultLanguage: 'pt',
   localeSubpaths,
   debug: false,
})
```
## Expected behaviour
Should see no console.log (either terminal or browser)

## Screenshots
![image](https://user-images.githubusercontent.com/13681852/54086898-8c1f6300-432c-11e9-82ea-43d3b8277b17.png)
![image](https://user-images.githubusercontent.com/13681852/54086917-c38e0f80-432c-11e9-9efb-1ebb11070bcb.png)

## OS (please complete the following information)
 - OS: Ubuntu 16.04
 - Browser: Chrome 72.0.3626.121 (Versão oficial) 64 bits

**Comment by isaachinman** [comment]
Hi @marcelothomaz, can you please explain what you mean? Where is the `console.log` call coming from?

**Comment by marcelothomaz** [comment]
Hi @isaachinman,

There are no console.log, however it cleaned up after I restarted my server...maybe some issue with next caching. Can you please remove this as it is invalid?

Thank you.
