### ISSUE TITLE
How to combine next-routes & next-i18next Link?

### ISSUE THREAD

**Issue by felixmosh** [isaachinman/next-i18next#228]
## Is your feature request related to a problem? Please describe.
Both [next-routes](https://github.com/fridays/next-routes) and this lib provides a Link component in order to enable a better dev experience, the problem is how one should combine them together, the issue is that both Link components are using Next's Link component.

## Describe the solution you'd like
Maybe it is better to expose `As` attribute so the component that will be rendered will be the next-routes Link component.

One would be able to create a Combining Link, something like that:
```javascript
import Link as I18nLink from '../i18n';
import Link as RoutesLink from '../routes';

export Link = ({children, ...rest})  => (
   <I18nLink as={RoutesLink} {...rest}>{children}</I18nLink>
);
```

Maybe it should be the opposite, that nextRoutes Link component will expose that.

**Comment by felixmosh** [comment]
Just from reading the sourceCode of NextRoutes, I've found that it allows to get an external Link  & Router.

https://github.com/fridays/next-routes/blob/master/src/index.js#L11

**Comment by isaachinman** [comment]
Hi @felixmosh - it's not recommended to use `next-routes` in conjunction with `next-i18next`, or really to use `next-routes` in general.

**Comment by felixmosh** [comment]
@isaachinman why?
How would you generate dynamic pages?

**Comment by isaachinman** [comment]
You can check the docs section on [custom routing](https://github.com/isaachinman/next-i18next#custom-routing). The `next-routes` implementation is problematic last I checked - you can search issues in the NextJs repo.

**Comment by weishiji** [comment]
> @isaachinman why?
> How would you generate dynamic pages?

Finally, how did you resolve this question. It troubled me a long time.

**Comment by felixmosh** [comment]
@weishiji next-routes allow you to [pass Link Component & Router](https://github.com/fridays/next-routes/blob/master/src/index.js#L11-L12) to the constructor, so, you can pass the next-i18next Link & Router to it.

**Comment by weishiji** [comment]
> @weishiji next-routes allow you to [pass Link Component & Router](https://github.com/fridays/next-routes/blob/master/src/index.js#L11-L12) to the constructor, so, you can pass the next-i18next Link & Router to it.

Can you give me a demo?

**Comment by weishiji** [comment]
> > @weishiji next-routes allow you to [pass Link Component & Router](https://github.com/fridays/next-routes/blob/master/src/index.js#L11-L12) to the constructor, so, you can pass the next-i18next Link & Router to it.
> 
> Can you give me a demo? I do not understand how he did it

Yes,I got it 
![image](https://user-images.githubusercontent.com/3954134/55535370-9c3b2000-56e9-11e9-9ab2-945427b4b4b1.png)
