### ISSUE TITLE
How to implement runtime extraction with next-i18next

### ISSUE THREAD

**Issue by goran-paunovic** [isaachinman/next-i18next#229]
Sorry if this is not a question for you, but I'm trying to use next-i18next and I have a problem...

These are my options for next-i18next
```
const NextI18Next = require('next-i18next/dist/commonjs');

module.exports = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['sr'],
  saveMissing: true,
  fallbackLng: 'en',
  backend: {
    addPath: '/locales/{{lng}}/{{ns}}.missing.json'
  }
});
```
I am trying to implement runtime extraction of missing keys. I tried to add missing route handler like here  [https://github.com/i18next/i18next-express-middleware#add-routes](https://github.com/i18next/i18next-express-middleware#add-routes), but there is no missingKeyHandler function in next-i18next/middleware.

What is the right way to implement this with next-i18next?

Thank you.

**Comment by isaachinman** [comment]
That's right, we're not exposing a `missingKeyHandler` function. It's very important to realise that `next-i18next/middleware` is different from `i18next-express-middleware` - it's another layer on top.

I suppose you could import `i18next-express-middleware` in your own project and set up the route manually. Do you want to try that and let me know if it works? Otherwise we can expose `missingKeyHandler`.

**Comment by goran-paunovic** [comment]
I understand that `next-i18next/middleware` is another layer on top. I was going through it's code trying to understand what's underneath. 
I will try to set everything up using` i18next-express-middleware` as you suggested and will let you know if everything works (no reason why it should not work).

**Comment by isaachinman** [comment]
@goran-paunovic Okay, please let me know if I can help in any possible way.

**Comment by isaachinman** [comment]
Hi, any update?

**Comment by poacher2k** [comment]
I achieved what I wanted with this:

```
const {
  serverRuntimeConfig: { isServer },
} = getConfig();

const NextI18NextInstance = new NextI18Next({
  localeSubpaths: 'foreign',
  defaultLanguage: 'nb',
  otherLanguages: ['en'],
  saveMissing: true,
  saveMissingTo: 'all',
  nsSeparator: false,
  keySeparator: false,
  missingKeyHandler: isServer
    ? (lng, ns, key, fallbackValue) => {
        const i18n = NextI18NextInstance.i18n;

        i18n.services.backendConnector.saveMissing(
          i18n.options.allLanguages,
          ns,
          key,
          fallbackValue
        );
      }
    : () => {},
  serverLanguageDetection: false,
});
```

**Comment by laidinidis** [comment]
@poacher2k How do you deal with keys in modals (client-side render). Also, do you get duplicate missing keys (I mean keys that are reported as missing but they are not)

**Comment by isaachinman** [comment]
@laidinidis If you don't include your modal's namespace in `namespacesRequired`, it won't be sent down to the client, and should be fetched at runtime. Let me know if you have any issues.

**Comment by poacher2k** [comment]
> 
> 
> @poacher2k How do you deal with keys in modals (client-side render). Also, do you get duplicate missing keys (I mean keys that are reported as missing but they are not)

I solved this by making a route that only exist in development, for reporting missing keys client side.

i18n.js
```
const hasReported = [];
...
...
missingKeyHandler: isDev
    ? (lng, ns, key, fallbackValue) => {
        if (isServer) {
          const i18n = NextI18NextInstance.i18n;

          i18n.services.backendConnector.saveMissing(
            i18n.options.allLanguages,
            ns,
            key,
            fallbackValue
          );
        } else {
          const reportKey = ns + key + fallbackValue;
          if (!hasReported.includes(reportKey)) {
            hasReported.push(reportKey);

            fetch('/api/i18n', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                ns,
                key,
                fallbackValue,
              }),
            });
          }
        }
      }
    : () => {},
```

server.js
```
if (dev) {
    server.post('/api/i18n', (req, res) => {
      const { ns, key, fallbackValue } = req.body;

      if (ns && key && fallbackValue) {
        nextI18next.i18n.services.backendConnector.saveMissing(
          nextI18next.i18n.options.allLanguages,
          ns,
          key,
          fallbackValue
        );
      }

      return res.sendStatus(200);
    });
}
```

**Comment by laidinidis** [comment]
@poacher2k thanks, that's what I was planning to do.

@isaachinman do you think this is a good idea or I should use an [extraction tool](https://react.i18next.com/guides/extracting-translations#2-using-an-extraction-tool)?

**Comment by isaachinman** [comment]
@laidinidis Sorry, I don't really have an opinion. Feel free to ask in one of the i18next repos.
