### ISSUE TITLE
How to get language inside nextjs getInitialProps method

### ISSUE THREAD

**Issue by kekebeen** [isaachinman/next-i18next#231]
Hi .
Is there any chance I can get current language inside nextjs getInitialProps method so I can do some SSR calls based on language.

Thanks .

**Comment by isaachinman** [comment]
You can check page props for `initialLanguage`.

**Comment by isaachinman** [comment]
Let me know if you have any other questions.

**Comment by a-barbieri** [comment]
> You can check page props for initialLanguage.

Can you be more specific? I keep getting `undefined`. 

I tried this, but it's not working.

```js
class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }
    
    console.log({initLang: pageProps.initialLanguage})

    return { pageProps, namespacesRequired: ["common"] };
  }
```

**Comment by a-barbieri** [comment]
Maybe you meant `req.i18n.language`. Still I don't get how to make this info available to nested components in an smart way.

**Comment by isaachinman** [comment]
> Still I don't get how to make this info available to nested components in an smart way.

The current language is passed as a prop called `lng` via the `withNamespaces` HOC. If you need the current language in your `_document` component, you'll need to take one of the above approaches.

**Comment by a-barbieri** [comment]
> The current language is passed as a prop called lng via the withNamespaces HOC.

Ok. Totally missed it.
Thanks.

**Comment by BondoS** [comment]
> you'll need to take one of the above approaches.

@isaachinman Sorry, What are the above approaches, can't see them!

**Comment by isaachinman** [comment]
Use of `lng` in `_document` is well documented. Feel free to have a look around or post on StackOverflow.

**Comment by BondoS** [comment]
@isaachinman Thank you for the prompt response,

Why lngFromReq function returns the fallback array of languages? it is not logical for me!
I need to filter out all languages except the current language but I can't do it because lngFromReq returns the fallback array, not the current language from request!!
![image](https://user-images.githubusercontent.com/2457873/62051679-26b50b80-b214-11e9-9ea4-3223684013c9.png)
