### ISSUE TITLE
Client side language is undefined

### ISSUE THREAD

**Issue by kenanbalija** [isaachinman/next-i18next#232]
Hello. Great library so far. I have one question regarding client side language property.
In my custom server.js I'm passing down language from express midleware to the route and its working fine.

```
const queryObj = {
     lng: req.language,
     test: “test”,
     test2: “test2"
   };
   const queryParams = Object.assign({}, req.params, queryObj);
   const actualPage = “/news”;
   app.render(req, res, actualPage, queryParams);
```

Now on the news route I need to get language inside nextjs initialProps and pass it to the api call. On page refresh everything works fine (I gues server side is fine and ctx.req is working) but when I use Link component ctx.req and query is undefined and I import language from the config. Is this right approach or I can get language from another property on the client ? 

Thanks
```
import { i18n } from “../../i18n”;

static async getInitialProps(ctx) {
   const language = (ctx.req ? ctx.req.lng : ctx.query.lng) || i18n.language;
   const resp = await getSomeData(language)
}
```

**Comment by isaachinman** [comment]
Sorry, I don't really understand what you're trying to achieve. If you want the language on the client, you should wrap your component in `withNamespaces` - that will provide `props.lng`.

The `Link` component shouldn't _ever_ result in a hard reload as that is a client-side navigation.

For more complex questions, please provide a full repository. Thanks!
