### ISSUE TITLE
Does not respect Next config value `assetPrefix`

### ISSUE THREAD

**Issue by stuart-williams** [isaachinman/next-i18next#244]
My application uses `assetPrefix` in `next.config.js` to prefix all static assets. `next-i18next` doesn't seem to respect that so requests for language files by the client are always hitting `/static/locales/es/common.json` when I need it to hit `/somewhere-else/locales/es/common.json` for example. Is it possible to do this?

**Comment by isaachinman** [comment]
Do you mean your directory structure is different, or you only want the _client_ to request a different path? If it's the former, it's supported via `localePath`. If it's the latter, it's not supported and I don't see a great reason to do that. You can map the routes on your server, or add a 301.

**Comment by stuart-williams** [comment]
Apologies, this is a duplicate of #133
