### ISSUE TITLE
How to use it with next-url-prettifier

### ISSUE THREAD

**Issue by a-barbieri** [isaachinman/next-i18next#246]
## Is your feature request related to a problem? Please describe.
I'd love to implement [next-url-prettyfier](https://github.com/BDav24/next-url-prettifier). I've done it while I was using [react-i18next](https://github.com/i18next/react-i18next), it should be doable with this library as well.

## Describe the solution you'd like
The current routing solution should not interfere with _next-url-prettifier_ [implementation](https://github.com/BDav24/next-url-prettifier/tree/973fff4f07d01cbe06ef5bbac4400633a8461229#in-your-serverjs-file-example-with-expressjs).

## Describe alternatives you've considered
If a neat implementation isn't possible, there should be a guideline to explain how to make both work together.

## Additional context
I've already tried to install them on the same application with this configuration, but there's some magic that happens which makes using _next-url-prettifier_ a bit too complex. 

Also I'd love to make an example, but with the current setup it's not possible for me to create a new example in that folder until there's a _how to contribute_ guideline.

**Comment by a-barbieri** [comment]
I think I've sorted out myself, but I'll leave it here for future reference.

## Working example with `next-url-prettifier` e `express`

The following files are expected to be on the root directory. If you want to change location, just remember to update the `require` statement.

The routes configuration 

```js
// ./routes.js

const UrlPrettifier = require("next-url-prettifier").default;
const i18n = require("./nextI18next").i18n;
const defaultLang = i18n.options.defaultLanguage;

const routes = [
  {
    page: "index",
    url: ({ lng }) => digestUrl(lng),
    patterns: [
      { pattern: "/", defaultParams: { lng: defaultLang } },
      { pattern: "/:lng(it||en)" }
    ]
  },
  {
    page: "page",
    url: ({ lng, slug }) => digestPagesUrl(lng, slug),
    patterns: [
      { pattern: `/pages/:slug`, defaultParams: { lng: defaultLang } },
      { pattern: `/en/pages/:slug`, defaultParams: { lng: "en" } },
      { pattern: `/it/pagine/:slug`, defaultParams: { lng: "it" } }
    ]
  }
];

/**
 * DIGEST PAGES URL
 */
function digestPagesUrl(lng, slug = "") {
  let path;
  if (lng === "it") {
    path = `/pagine/${slug}`;
  } else {
    path = `/pages/${slug}`;
  }
  return digestUrl(lng, path);
}

/**
 * DIGEST  INDEX URL
 **/
function digestUrl(lng, path = "") {
  if (typeof lng === "undefined") {
    return `/${path}`;
  }
  return `/${path}`;
}

const urlPrettifier = new UrlPrettifier(
  routes.map(({ url, patterns, ...rest }) => {
    return { prettyUrl: url, prettyUrlPatterns: patterns, ...rest };
  })
);

module.exports = {
  routes,
  Router: urlPrettifier
};
```

The custom server:

```js
// server.js

const express = require("express");
const next = require("next");
const nextI18NextMiddleware = require("next-i18next/middleware");
const nextI18next = require("./nextI18next");
const Router = require("./routes").Router;

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = express();
  server.use(nextI18NextMiddleware(nextI18next));

  Router.forEachPrettyPattern((page, pattern, defaultParams) =>
    server.get(pattern, (req, res) =>
      app.render(
        req,
        res,
        `/${page}`,
        Object.assign({}, defaultParams, req.query, req.params)
      )
    )
  );

  // TODO this should lead to 404 page
  server.get("*", (req, res) => {
    return handle(req, res);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

Page implementation:

```js
// somewhere in your component
import React, { Component }  from "react";
import { Router } from "./routes";
import { withNamespaces } from "next-i18next";

class HomeButton extends Component {
  render(){
    return (
      <Link route={Router.getPrettyUrl("index", { this.props.lng })}>
        <a>
          Home sweet home
        </a>
      </Link>
    );
  }
}
export default withNamespaces('your-namespace')(HomeButton);

```

**Comment by a-barbieri** [comment]
I did try my best to get them work together, but not knowing the magic behind the routing implementation makes very difficult to guess routes and params.

**Comment by a-barbieri** [comment]
The main issue is with `Router.getPrettyUrl`. As _next-i18next_ modifies _Next Router_ directly, it makes impossible to guess the route on _next-url-prettifier_ configuration because you should take out the `lng` param, but then the whole thing gets very inconsistent.

I wouldn't say it's a _next-url-prettifier_ issue because, from a [convention over configuration](https://en.wikipedia.org/wiki/Convention_over_configuration) perspective Next Router should remain untouched.

**Comment by a-barbieri** [comment]
I've seen that it's a known issue, as anything relying on the default _NextJS Router_ cannot be used with this library.

https://github.com/isaachinman/next-i18next/blob/8bf6fb4899e3baab7f1e76f540f2a1c8c04c13e3/src/router/wrap-router.js#L9-L10

Therefore either _next-url-prettifier_ should depend on your _Router_ rather NextJS one or your Router should integrate the _next-url-prettifier_ one. Not sure what's the most feasible solution...

**Comment by isaachinman** [comment]
Hi @a-barbieri - why do you want to use `next-url-prettifier` with `next-i18next`? It's the first time I've heard of that package. What problem does it solve, exactly?

**Comment by a-barbieri** [comment]
`next-url-prettifier` enhances the custom routing system.

You can see it working along with `react-I18next` on [this website](https://www.arcarreda.it) we've done few months ago.

It let's you have completely translated routes for the same page:

```
https://www.arcarreda.it/it/pagine/design-contemporaneo
https://www.arcarreda.it/en/pages/contemporary-design
```

**Comment by dayze** [comment]
@a-barbieri It'll we be a requirement in my current project too.

**Comment by isaachinman** [comment]
If someone wants to look into what changes `next-i18next` would have to make to support `next-url-prettifier`, I am willing to hear those requests and consider it.

However, I will not be undertaking this work at the moment. If `next-url-prettifier` becomes more popular, we'll definitely reconsider and perhaps even pull it in as a dep.

**Comment by isaachinman** [comment]
> I've seen that it's a known issue, as anything relying on the default NextJS Router cannot be used with this library.

It's not a known issue, it's an implementation detail. We _extend_ the Next Router and add redirects automatically. You're free to use the Next Router as you like if you don't want to use `localeSubpaths`. Please read the documentation.

**Comment by a-barbieri** [comment]
> If next-url-prettifier becomes more popular, we'll definitely reconsider and perhaps even pull it in as a dep.

Makes sense. I'll work the other way around to see if I can get `next-url-prettifier` to work along with this library.

> You're free to use the Next Router as you like if you don't want to use `localeSubpaths`. 

I'll be using Next Router to get this done. I might keep asking for details, hope you don't mind. 

For sure the first thing is: if I don't use `localeSubpaths` do I still have to implement `server.use(nextI18NextMiddleware(nextI18next))`? Do I need to implement it if I don't use `next-i18next Router`?

**Comment by isaachinman** [comment]
> I might keep asking for details, hope you don't mind.

Not a problem. If you feel like relevant details come up, feel free to submit PRs to improve the documentation.

>  if I don't use localeSubpaths do I still have to implement nextI18NextMiddleware

The express middleware does more than just set up routes - it also does language detection based on browser headers, cookies, etc. You're pretty much always going to want to use the middleware, unless:

1. You don't want to do any user-language detection
2. You don't want to persist user language across refreshes/sessions

**Comment by isaachinman** [comment]
Closing for now - happy to reopen in the future if we want to discuss again.
