### ISSUE TITLE
Impossible to use with Apollo without SSR broken.

### ISSUE THREAD

**Issue by alex-knyazev** [isaachinman/next-i18next#247]
I found this issue: 

https://github.com/isaachinman/next-i18next/issues/59

But it's not actual for now. Problem is still here.

Is it possible to use Apollo client and next-i18next together? Maybe there are some crunch at least?

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by alex-knyazev** [comment]
https://github.com/alex-knyazev/next-i18n-material-ui-apollo-redux-boilerplate

**Comment by alex-knyazev** [comment]
P.S.
 
I think understand when we get problem. In my last commit in https://github.com/alex-knyazev/next-i18n-material-ui-apollo-redux-boilerplate  SSR works.

Summary:

When we use withNamespace

**Comment by alex-knyazev** [comment]
P.S.

I think understand when we get problem. 
In my last commit in https://github.com/alex-knyazev/next-i18n-material-ui-apollo-redux-boilerplate SSR works.

<b>Summary</b>:

When we use withNamespace as a wrapper for component where Apollo Query exists - SSR is broken.

[Example of such component](https://github.com/alex-knyazev/next-i18n-material-ui-apollo-redux-boilerplate/blob/43e12ba3a091f4d1199e6174192cbf2d077b42fb/src/components/DefaultLayout.js)

In the example above we use apollo Query component inside component which wrapped by withNamespaces HOC.

But if we have withNamespaces HOC inside Query component, all works as expected. SSR isn't broken.

It;s look like function getDataFromTree from Apollo can't get requests from components which wrapped by withNamespaces.

**Comment by isaachinman** [comment]
That is some fantastic debugging - thank you. Indeed it can be hard to get these decorators to play nicely together, and Apollo's `getDataFromTree` is using `react-tree-walker` if I remember correctly.

Unfortunately I am not sure if I will have time in the next day or two to look at this. Are you saying that you found a temporary solution by reordering your HOCs?

I do assure you that this will be looked into - just not sure of timeframe.

**Comment by isaachinman** [comment]
> It;s look like function getDataFromTree from Apollo can't get requests from components which wrapped by withNamespaces.

@alex-knyazev Can you find any other examples of this sort of thing? I know that Apollo tends to have a lot of problems integrating with other libraries.

We are [directly exporting `withNamespaces` from `react-i18next`](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L24), so you might want to close this and open an issue over there.

**Comment by alex-knyazev** [comment]
@isaachinman  Yes, I too think problem isn't in next-i18next.
It is very sad, but I cant find god solution for my project which will combines all technologies I want. I can't refuse by apollo, so, i think I will load all languages in React Context and use it from there ((. Thank you for answer. I will write to reacti18next
