### ISSUE TITLE
module initialization error: Error

### ISSUE THREAD

**Issue by Gmulti** [isaachinman/next-i18next#249]
## Describe the bug
When trying to deploy my application with Now/Zeit v2, I get an error because of the i18n module

Module initialization error: Error
    at Object.fs.readdirSync (fs.js:904:18)
    at getAllNamespaces (/var/task/page.js:66:34570)
    at _default (/var/task/page.js:66:34813)
    at new NextI18Next (/var/task/page.js:90:121185)
    at Object.k7Sn (/var/task/page.js:66:72239)
    at __webpack_require__ (/var/task/page.js:1:339)
    at Object.1TCz (/var/task/page.js:9:69542)
    at __webpack_require__ (/var/task/page.js:1:339)
    at Module.ftYo (/var/task/page.js:60:271396)
    at __webpack_require__ (/var/task/page.js:1:339)

## Occurs in next-i18next version
0.36.5

## Steps to reproduce
Just example

## Screenshots
![Capture d’écran 2019-03-29 à 09 14 58](https://user-images.githubusercontent.com/5682535/55218733-33443b80-5203-11e9-82af-366c7ff03018.png)

**Comment by isaachinman** [comment]
I'm not a `now` user, so you'll have to help provide more details to debug. Can you provide the full error stack?

**Comment by Gmulti** [comment]
Unfortunately, there is no more :/
I also opened a message on Spectrum from now:  https://spectrum.chat/next-js/general/module-initialization-error-with-nexti18next~3f3e6d70-1de4-4418-9b93-479d1431d5bf

Here are the logs of the example project deployed on Now, it's another error but it still doesn't work.
I am waiting to see what is happening on their side as well, perhaps it is coming from them.

https://zeit.co/deployments/example-i18n.gmulti.now.sh/logs

**Comment by isaachinman** [comment]
@Gmulti Seems pretty straightforward to me:

> (node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/var/task/static/locales/en'

Am I misunderstanding something?

**Comment by Gmulti** [comment]
No idea, since their v2 it's a disaster...
We're supposed to be able to put the trads in the static folder...

**Comment by Gmulti** [comment]
https://spectrum.chat/zeit/general/next-with-i18next-on-now-v2-requires-a-custom-server~e9fb69db-7bc6-47ed-a9a1-06287a2c3509

**Comment by isaachinman** [comment]
Closing because it seems like a filesystem problem. Happy to reopen if you have more details that are related to `next-i18next`.
