### ISSUE TITLE
TypeError: Cannot read property 'wait' of null

### ISSUE THREAD

**Issue by janus-reith** [isaachinman/next-i18next#252]
## Describe the bug
Occurs, whenever I use withNamespaces on any component.
Implemented i18next the way it is described and also compared with the example.

Trying to add i18n to https://github.com/reactioncommerce/reaction-next-starterkit.
Got it to work before, now broke it after huge merges and sadly can't reproduce the exact point where it started to fail.

If I leave out `withNamespaces` and inspect the props in my React tree, `i18nServerInstance` is `{null}` - I wonder if this might be related?

If I edit my component to be wrapped in `withNamespaces` with a corresponding namespace and use that during render `<p>{props.t('example')}</p>`, Hot Reloading kicks in and the text is displayed properly. When I do a full refresh then, server console throws the error again and the page stays blank.

## Occurs in next-i18next version
0.36.5

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
Component that is wrapped in `withNamespaces` should work properly instead of throwing Errors on the server.

## OS (I doubt this is related to the issue)
 - Fedora 29 Host running docker image with node 10 on Alpine

## Additional context
Error thrown multiple times in the server console:

```
TypeError: Cannot read property 'wait' of null
    at NamespacesConsumerComponent.render (/usr/local/src/node_modules/react-i18next/dist/commonjs/NamespacesConsumer.js:220:33)
    at processChild (/usr/local/src/node_modules/react-dom/cjs/react-dom-server.node.development.js:2863:18)
    at resolve (/usr/local/src/node_modules/react-dom/cjs/react-dom-server.node.development.js:2716:5)
    at ReactDOMServerRenderer.render (/usr/local/src/node_modules/react-dom/cjs/react-dom-server.node.development.js:3100:22)
    at ReactDOMServerRenderer.read (/usr/local/src/node_modules/react-dom/cjs/react-dom-server.node.development.js:3059:29)
    at renderToStaticMarkup (/usr/local/src/node_modules/react-dom/cjs/react-dom-server.node.development.js:3541:27)
    at process (/usr/local/src/node_modules/react-apollo/react-apollo.umd.js:118:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

What I just noticed: When the server starts I get the message: react-i18next:: You will need pass in an i18next instance either by props, using I18nextProvider or by using i18nextReactModule. Learn more https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow

That link doesn't work.
As both `react-i18next` and `i18next` are dependencies of `next-i18next` I did not import or install them manually.

**Comment by isaachinman** [comment]
Sounds like you haven't set up `next-i18next` correctly. Perhaps read through [this article](https://medium.com/@isaachinman/creating-localised-nextjs-apps-with-next-i18next-f01d5e610307) and let me know if you have any questions.

**Comment by janus-reith** [comment]
I read that already, rechecked, and the setup in`i18n.js` really isn't that complex.

**Comment by isaachinman** [comment]
If you'd like some help, please link me directly to:

1. Your `i18n.js` file
2. Wherever you are implementing the `next-i18next-middleware`
3. An example of a component where you are using `withNamespaces`

**Comment by janus-reith** [comment]
Sadly there currently is no public repo atm, but these are relevant files.
I know that this isn't an optimal example, will prepare and upload a complete example on my github if this issue persists - But here on the short term:

i18n.js:
```
const NextI18Next = require('next-i18next/dist/commonjs');

module.exports = new NextI18Next({
    otherLanguages: ["en"],
    defaultLanguage: "de",
    localePath: "src/static/locales",
    fallbackLng: "de"
})
```
server.js
```
const cookieParser = require("cookie-parser");
const cookieSession = require("cookie-session");
const express = require("express");
const compression = require("compression");
const nextApp = require("next");
const { useStaticRendering } = require("mobx-react");
const nextI18NextMiddleware = require('next-i18next/middleware')
const nextI18next = require('./i18n')
const config = require("./config");
const logger = require("./lib/logger");
const router = require("./routes");
const { configureAuthForServer } = require("./serverAuth");
const { sitemapRoutesHandler } = require("./sitemapRoutesHandler");

const app = nextApp({
  dev: config.isDev,
  dir: "./src"
});

useStaticRendering(true);

app
  .prepare()
  .then(() => {
    const server = express();
    server.use(compression());
    server.use(nextI18NextMiddleware(nextI18next));

    server.use(cookieSession({
      keys: [config.SESSION_SECRET],
      maxAge: config.SESSION_MAX_AGE_MS,
      name: "storefront-session"
    }));
    server.use(cookieParser());

    configureAuthForServer(server);

    server.use(/^\/sitemap.*\.xml$/, sitemapRoutesHandler);
    const routeHandler = router.getRequestHandler(app);
    server.use(routeHandler);

    return server.listen(config.PORT, (err) => {
      if (err) throw err;
      logger.appStarted("localhost", config.PORT);
    });
  })
  .catch((ex) => {
    logger.error(ex.stack);
    process.exit(1);
  });

module.exports = app;

```

Example component:

```
import React from "react";
import PropTypes from "prop-types";
import { withStyles } from "@material-ui/core/styles";
import Typography from "@material-ui/core/Typography";
import { i18n, withNamespaces } from '../../i18n'

const styles = (theme) => ({
  footer: {
     // Unrelated
  },
  footerContent: {
     // Unrelated
  }
});

const Footer = ({ ...props }) => (
  <footer className={props.classes.footer}>
    <div className={props.classes.footerContent}>
      <Typography variant="caption" color="inherit">
        <p>{props.t('h1')}</p>
      </Typography>
    </div>
  </footer>
);

Footer.getInitialProps = () => {
  return {
    namespacesRequired: ["common"]
  }
}

Footer.propTypes = {
  classes: PropTypes.object
};

export default withNamespaces("common")(withStyles(styles, { name: "SkFooter" })(Footer));
```

**Comment by isaachinman** [comment]
What happens if you switch the nesting order of `withStyles` and `withNamespaces`? In general at this point I'd need a reproducible repo to be able to help - your setup looks valid.

**Comment by janus-reith** [comment]
Doesn't make a diference - I also feel like the actual error originates somewhere else.
Will take the time and prepare a full example.

**Comment by isaachinman** [comment]
Okay - just let me know.

**Comment by janus-reith** [comment]
@isaachinman I pushed a repo to demonstrate the issue:
https://github.com/janus-reith/reaction-next-starterkit-i18n/tree/develop

Prerequisites: Docker, git account with ssh.
As this does not run on its own, these are the steps to get it up and running, please excuse the inconvenience:

`git clone git@github.com:reactioncommerce/reaction-platform.git`
`cd reaction-platform`
`make`

Wait for it to finish, then:

`make stop`
`rm -rf reaction-next starterkit`
`git clone git@github.com:janus-reith/reaction-next-starterkit-i18n.git -b develop reaction-next-starterkit`
`make start`

**Comment by isaachinman** [comment]
Sorry, that's not a minimal reproducible example. I don't know if it will even be helpful for me to try and debug something with that level of complexity.

**Comment by isaachinman** [comment]
At a high level, I imagine your problem lies somewhere in [here](https://github.com/janus-reith/reaction-next-starterkit-i18n/blob/develop/src/pages/_app.js#L27). Absolutely no idea what all these decorators are doing, or if they're all passing context and statics down correctly.

Sorry, but this is well outside the scope of OSS support.

**Comment by janus-reith** [comment]
Alright, Nevermind. Wasn't trying to let someone else debug my codebase, the basic idea is just that there could be people who expected a similar issue, including you who appareantly developed most of this wrapper.

I think the issue won't be related to the decorator syntax, experienced the same issue without it.

As the only occurences in `NamespacesConsumer.js` where a property wait is mentioned are on `i18nOptions` which in turn is derived from props, is seems like there actually is some issue regarding props not passed properly somehow. NamespacesConsumer however is part of `react-i18next` and the only occurence of `i18nOptions` in `next-i18next`was on the Link component.

**Comment by janus-reith** [comment]
Solved it. Actually was about the appWithTranslation HOC.
So, for any one experiencing the issue mentioned in the title, a troubleshooting step could be to check if Apollo is used, and if make sure that `ApolloProvider` is  wrapping `appWithTranslation`, not the other way around.

**Comment by isaachinman** [comment]
@janus-reith That's great to hear! Yes, we've had various reports of Apollo users having issues. Any idea if there's room for improvement on the `next-i18next` side of things? We should be passing along all props and statics, so I'm not sure what would be breaking. Worth saying that Apollo takes some unconventional approaches as a library.

**Comment by isaachinman** [comment]
A general note for anyone reading this: if you're having trouble with decorators/HOCs, the _order does matter_.

**Comment by nisargrthakkar** [comment]
Is there any update on this?

**Comment by isaachinman** [comment]
@nisargrthakkar Hi there - not sure what you mean by "still", as this is the first we've heard from you. If you have a reproducible example (repo), I can take a look for you.

**Comment by nisargrthakkar** [comment]
Sorry, It's my bad. I missed some configuration.
