### ISSUE TITLE
How to make plurals?

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#254]
I'm trying to follow the docs in i18next about plurals. However, I figure out that it doesn't work here:

https://www.i18next.com/translation-function/plurals

Is always using the simple form and never is taking the `key_plural` ...

How can I configure it with `next-i18next`?

**Comment by aralroca** [comment]
Ok, I realized that the variable name should be always `{{count}}` and I was using another one 😅

**Comment by kachkaev** [comment]
You can check out i18next-icu plugin. It switches translation stings to the ICU format, which is a pretty solid framework!

**Comment by otroboe** [comment]
For lazy people like me, here's an example:
```
{
    "amount": "{{count}} vehicle", 
    "amount_plural": "{{count}} vehicles"
}
```

**Comment by JarnoRFB** [comment]
The new fomat according to https://www.i18next.com/translation-function/plurals is apparently 
```json
{
    "amount_one": "{{count}} vehicle", 
    "amount_other": "{{count}} vehicles"
}
```
