### ISSUE TITLE
Add YAML Support

### ISSUE THREAD

**Issue by ckeeney** [isaachinman/next-i18next#257]
## Is your feature request related to a problem? Please describe.
The backend supports YAML but the loader is hard coded with a JSON extension and it is not possible to override as written right now.

https://github.com/isaachinman/next-i18next/blob/c15256e16070b101467ab21be51d0170aad7bf11/src/config/create-config.js#L42-L54

If we want to keep the `backend` options as rigid as they are, we could expose a `fileExtension` option and use that.

If it is possible to use YAML with this library can you please show an example?  I know [you've already mentioned](https://github.com/isaachinman/next-i18next/issues/106#issuecomment-455552249) that [`i18next-node-fs-backend` already supports YAML](https://www.npmjs.com/package/i18next-node-fs-backend), but I can't figure out how to get it working without doing more work than I feel I should have to when using this library.

**Comment by isaachinman** [comment]
Yes, we can definitely add a `localeFileExtension` option.

**Comment by isaachinman** [comment]
Fixed by #258.

**Comment by isaachinman** [comment]
Fixed by #302. Sorry for the delay @ckeeney.

**Comment by felixmosh** [comment]
Additional problem related to Yaml support, `i18next-http-backend` by default parses as JSON (using `options.backend.parse` field).
Currently there is no way to add this `parse` field (it gets overridden by next-i18next)
