### ISSUE TITLE
ICU plugin not working

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#26]
While investigating https://github.com/isaachinman/next-i18next/issues/19, I've noticed that [next-i18next](https://github.com/isaachinman/next-i18next) has stopped working in my project after switching to `next-i18next`. See MWE in https://github.com/kachkaev/next-i18next/tree/icu/example + [commit](https://github.com/kachkaev/next-i18next/commit/670ec4501b436ac441b4ee0029f6453466eb99bc).

ICU templates don't get parsed as if ICU is not included. Could it be that I incorrectly loaded the plugin? If so, it'd be great to see an example. Cheers! 🙌

**PS:** I did not upgrade `yarn.lock` in my fork, because the diff was full of integrity check additions. This is probably because you're still using yarn 1.9, which does not dump this field into the lock file. Upgrading to 1.10+ and committing the diff once should make further contributions simpler.

**Comment by isaachinman** [comment]
This is related to the general problem of plugin use being discussed in #14. A fix will come soon(ish).

I'm using yarn `1.12.3`, by the way. No one should be committing lockfiles unless they're changing deps.

**Comment by kachkaev** [comment]
I see. I was using a different major version of `i18next` before trying `next-i18next` and actually did not realize that the issue can be simply upstream.

As of yarn I'm now not sure why those integrity diffs popped out – I do see the value in both `yarn.lock` files in the repo 🤔. The reason why I had it changed in the first place was because of adding `next-icu` to the MWE. That diff is wiped now, I can't recall what it was exactly.
