### ISSUE TITLE
Hashing translations

### ISSUE THREAD

**Issue by peacefulseeker** [isaachinman/next-i18next#265]
Is it possible to control caching of translations(e.g. common.json file), by adding unique hash to it on every change on deploy?
Saw this on `react-i18next`. 
https://github.com/i18next/react-i18next/issues/803
Seems actual for us as, too, but using with your provided package

**Comment by isaachinman** [comment]
Change your `localeStructure` config setting as per https://github.com/i18next/react-i18next/issues/803#issuecomment-476074147.
