### ISSUE TITLE
defaultLanguage do not work different than en

### ISSUE THREAD

**Issue by joeyzone** [isaachinman/next-i18next#269]
## Describe the bug
In example/simple, i just update code like this, it didn't work
![image](https://user-images.githubusercontent.com/1586972/56259312-2b423200-6105-11e9-8d9f-7fe453879027.png)

## Occurs in next-i18next version
0.37.0
## Steps to reproduce
In example/simple

## Expected behaviour
none

## Screenshots
![image](https://user-images.githubusercontent.com/1586972/56259312-2b423200-6105-11e9-8d9f-7fe453879027.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Do you mean you literally copy/pasted it? The `localeSubpaths` option there is being defined as a shorthand via [this import](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/i18n.js#L2) from our Next config.

Just set it to a string. Please read the [docs](https://github.com/isaachinman/next-i18next#5-locale-subpaths).

**Comment by joeyzone** [comment]
![image](https://user-images.githubusercontent.com/1586972/56267841-8df5f680-6122-11e9-973e-11d1250d1f48.png)
it's your example/simple, I just set otherLanguages: ['en'], and   defaultLanguage: 'de',

**Comment by joeyzone** [comment]
> Do you mean you literally copy/pasted it? The `localeSubpaths` option there is being defined as a shorthand via [this import](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/i18n.js#L2) from our Next config.
> 
> Just set it to a string. Please read the [docs](https://github.com/isaachinman/next-i18next#5-locale-subpaths).

t's your example/simple, I just set otherLanguages: ['en'], and defaultLanguage: 'de',
