### ISSUE TITLE
Didn't work with defaultLanguage different than en?

### ISSUE THREAD

**Issue by endigo** [isaachinman/next-i18next#27]
server.js
```javascript
app.prepare().then(() => {
    const server = express();

    if (!dev) {
        server.use(compression({threshold: 0}));
    }

    nextI18NextMiddleware(app, server);
...
```
i18n.js
```javascript
module.exports = new NextI18Next({
  defaultLanguage: 'mn',
  otherLanguages: ['en'],
});
```

My App starts with **en** not **mn**

**Comment by revskill10** [comment]
This issue might related to original library `i18next`, not react issue.
The API is too much confusing on this.
Take for example, `intl` library, it allows explicitly set locale from anywhere you want, cookie, querystring, accept,... you have control for that.
You might need to make an issue on original library though.

**Comment by kachkaev** [comment]
@revskill10 all was working for me when I just used `i18next` + `react-i18next` + custom language detectors. The latter is being discussed in https://github.com/isaachinman/next-i18next/pull/8, however even setting `defaultLanguage` option does not seem to work at the moment.

**Comment by jamuhl** [comment]
@revskill10 you have full control over detection - just use no detector and pass `lng: 'yourLng'` on init options...https://www.i18next.com/overview/getting-started#basic-sample

**Comment by revskill10** [comment]
@jamuhl No, what i mean is that `'yourLng'` is a function from `(req)`, not fix string ;)

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-express-middleware/blob/master/src/LanguageDetector.js#L47 but guess we drifting away from the issue here...so let's keep this here on the topic of the defaultLanguage setting not working.

It's a design decision to use the express middleware. I wouldn't say it's a fault. Support for koa, serverless,... can be sure taken into account but needs the contribution of the community using those stacks.

**Comment by endigo** [comment]
I added {lng: 'mn'} option it works. But first shows English texts.

**Comment by jamuhl** [comment]
@endigo that's for sure not the intended solution - let's wait for @isaachinman to have a look.

**Comment by isaachinman** [comment]
Hi @endigo, sorry to hear you are having problems. In my projects, English is always the default language, so I haven't run into these problems yet.

Can you please create a quick reproducible example via CodeSandbox?

**Comment by isaachinman** [comment]
I switched `de` and `en` in [the example](https://github.com/isaachinman/next-i18next/tree/master/example), changed my browser language to German, and opened `localhost:3000` in an incognito window. It loaded the app in German.

**Comment by isaachinman** [comment]
@revskill10 Please don't discuss unrelated topics in issues. This is open source software that we develop in our free time - we are not here to engineer the perfect solution for _you_. PRs are always welcome.

**Comment by kachkaev** [comment]
@isaachinman I [replaced](https://github.com/kachkaev/next-i18next/commit/c23f6b073a66a02ab52bc22474f2cb39e848b0bc) `defaultLanguage` from `en` to `de`, but Chrome still rendered `en` for me.

**Comment by isaachinman** [comment]
@kachkaev Did you do this in an incognito window with your browser language set to German?

**Comment by isaachinman** [comment]
It's not magic - with `localeSubpaths`, preference is always given the route. With `localeSubpaths` enabled, the behaviour you're describing would indeed take place.

Otherwise, [i18next-browser-languagedetector](https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L4) is used.

There might actually be a case for removing it once #28 lands, but I think it might be more complicated than that.

**Comment by p77u4n** [comment]
If you select the language of i18n to be 'en' in the previous session, the i18next-browser-languageDetector will cache language 'en' by assigning the value of 'next-i18next (lookupCookie key) of the cookies on the browser to be 'en'. So in the next session, the users use your website, in the initial request to get your website, the cookies that attached in req object will have the value of 'next-i18next' to be 'en' regardless of which language to be set as default language or the value of Accepted-Language field in the header -> your rendering server will send the 'en' version of your website, and obligate browser to set (again) the value of 'next-i18next' in the website cookies to be 'en' (the LanguageDetector of i18next-express-middleware will do that for you). So your website locale will forever be 'en', unless you clear the value of 'next-i18next' and assign it to be your rather language. My solution is clear the value of 'next-i18next' on the server-side to make your website`s 'locale setting' to be pristine.

`  server.use((req, res, nextMD) => {
    res.clearCookie('next-i18next');
    nextMD();
  });
`

**Comment by jamuhl** [comment]
I visit your website and search for the language toggle -> set language to English -> why would I not like to have your site in English the next time I visit it - but prefer the header field I already override last time?

Your use-case is unclear to me.

**Comment by isaachinman** [comment]
@p77u4n That's a fundamentally confused and hacky approach. I suggest you look carefully through the `i18next` options, especially the [detector options](https://github.com/i18next/i18next-browser-languageDetector#detector-options).

**Comment by ahmedengu** [comment]
I was able to resolve this issue by removing 'header' from detectors by adding the following to my config:
```  
detection: {
    lookupCookie: 'next-i18next',
    order: ['cookie', 'querystring', 'localStorage', 'path', 'subdomain'],
    caches: ['cookie'],
  },
```


so the set up would be:
```
import NextI18Next from 'next-i18next'

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'ar',
  otherLanguages: ['de'],
  detection: {
    lookupCookie: 'next-i18next',
    order: ['cookie', 'querystring', 'localStorage', 'path', 'subdomain'],
    caches: ['cookie'],
  },
})

export default NextI18NextInstance

/* Optionally, export class methods as named exports */
export const {
  appWithTranslation,
  withTranslation,
} = NextI18NextInstance

```

**Comment by nemanja-s** [comment]
Simple and quick solution:
1. Rename the directory `en` _(/public/locales/en)_ to something else, such as `eng`.
2. Edit `i18n.js` (an example where Serbian is the default language) :
`const NextI18Next = require("next-i18next").default;

module.exports = new NextI18Next({
    defaultLanguage: "sr",
    otherLanguages: ["eng"],
    localePath: typeof window === "undefined" ? "public/locales" : "locales"
});`

**Comment by barakat-turki** [comment]
Thanks, @ahmedengu this works for me.

**Comment by rozakbuhari** [comment]
Thank you very much @ahmedengu, you saved my day.

**Comment by elyash14** [comment]
Hello everyone. but I had this problem and when I changed my default language to something like "fa" in the config, nothing happened and the "en" json file was loaded. I didn't have any custom server like server.js and after some search and playing with NextI18Next configs, set serverLanguageDetection option to false and everything worked properly. 
`new NextI18Next({
  defaultLanguage: 'fa',
  otherLanguages: ['en'],
  defaultNS: 'agro',
  localePath: path.resolve('./public/locales'),
  debug: true,
  browserLanguageDetection: true,
  serverLanguageDetection: false,
});`
