### ISSUE TITLE
queryString setting for languageDetector

### ISSUE THREAD

**Issue by designbyadrian** [isaachinman/next-i18next#276]
react-i18next supports appending a language code as a URL parameter:

`mydomain.com?lng=se`

https://react.i18next.com/legacy-v9/step-by-step-guide#c-auto-detect-the-user-language

There doesn't seem to be any support for this pattern, nor how to change the parameter.

**Comment by isaachinman** [comment]
All config options from `react-i18next` are available. You are probably going to want to look into the `detection` object. You can start by checking out the [default values here](https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.js#L35). You'll need to put `querystring` ahead of `cookie` and `header` if you want to override.

**Comment by designbyadrian** [comment]
Woop! There it is!

**Comment by devohda** [comment]
@isaachinman Is `?lang=en` still available to detect user language?
