### ISSUE TITLE
Link component doesn't automatically append queryString

### ISSUE THREAD

**Issue by designbyadrian** [isaachinman/next-i18next#277]
When using option `localeSubpaths: 'foreign'`, clicking on a <Link> automatically handles going to the correct sub page, domain.com/lng/pageA -> domain.com/lng/pageB.

But with the queryString settings:

```
detection: {
    order: ['querystring', 'cookie', 'header'],
}
```

query parameter isn't retained domain.com/pageA?lng=lng -> domain.com/lng/pageB

## Occurs in next-i18next version
0.37.0

## OS
 - Device: MBP 2017 15
 - Browser: Chrome 73.0.3683.103

**Comment by designbyadrian** [comment]
I've got a site that uses queryStrings only to determine language.

I've so far combined the settings:

```
  localeSubpaths: 'foreign',
  detection: {
    order: ['querystring', 'cookie', 'header'],
  }
```

but for now the site redirects to, for example, domain.com/de/?lng=de. I'm not sure how to delete the query-string parameter without breaking the redirect to /de/.

**Comment by isaachinman** [comment]
Why do you want to use a query string param and locale subpaths at the same time? What is the use case?

**Comment by designbyadrian** [comment]
I don't, but it's the only way the <Link> component retains the language if I've set up queryString and not a localeSubpath

**Comment by isaachinman** [comment]
> I don't

> I've so far combined the settings

Please explain? You'll need to set your `localeSubpaths` to `none`.

**Comment by designbyadrian** [comment]
Thank you! It seems that you understood even after my vague description 😄 

So, to recap:

I've got a site that requires the use of ?lng= in the URL query params.

I set this option for NextI18Next:

``` javascript
detection: {
    order: ['querystring', 'cookie', 'header'],
}
```

I could successfully update the language by visiting the site on domain.com/?lng=en or domain.com/?lng=en

I could _not_ keep the language setting when changing route using the <Link /> element from NextI18Next, so I set these options instead, thinking I could do some horrible express redirects:

```javascript
localeSubpaths: 'foreign',
detection: {
    order: ['querystring', 'cookie', 'header'],
}
```

It worked, but then I got URLs in this format: domain.com/de/?lng=de, which dumb, but it was a solution I could do with for a few weeks while waiting for someone here to help.

# Solution

As you wrote, this should be the setting:

```javascript
localeSubpaths: 'none',
detection: {
    order: ['querystring', 'cookie', 'header'],
}
```

What's weird is that `none` is the default value, but I couldn't get it to work at first. Removing the line seems to be working fine? I wonder if my dev server does some caching it shouldn't do. I've been scratching my head for too long.

I consider this issue to be closed, nonetheless.

**Comment by isaachinman** [comment]
If you're not using `localeSubpaths`, you don't need to import any of the navigation/link components from `next-i18next` - just use the normal NextJs ones.
