### ISSUE TITLE
Get current language

### ISSUE THREAD

**Issue by mengqing** [isaachinman/next-i18next#278]
## Describe the bug
Previously I was able to get the current language by importing `i18n` from the i18n config file, and calling `i18n.language`.

But after I upgraded to the latest version of npm package, I now get `Attempted import error: 'i18n' is not exported from 'i18n'.

## Occurs in next-i18next version
v0.37.0

## Steps to reproduce
Previously my i18n config file is as following

```
const NextI18Next = require('next-i18next');

module.exports = new NextI18Next({ defaultLanguage: 'en'});
```

After updating to the following, this is no longer working

```
import NextI18Next from 'next-i18next';

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en'
});

export default NextI18NextInstance;
```

**Comment by isaachinman** [comment]
Please follow the [docs](https://github.com/isaachinman/next-i18next#3-project-setup). Specifically:

```
/* Optionally, export class methods as named exports */
```

**Comment by mengqing** [comment]
I did try

```
export const {
  appWithTranslation,
  withNamespaces,
  i18n,
} = NextI18NextInstance;
```

but i18n is undefined when I try to call it

**Comment by isaachinman** [comment]
Unless `NextI18NextInstance.i18n` itself is undefined, this is unrelated to `next-i18next`. Moreover, if you need access to the current language, it's better to use the `withNamespaces` HOC.

Good luck!
