### ISSUE TITLE
Support regional locales 

### ISSUE THREAD

**Issue by bobsingor** [isaachinman/next-i18next#279]
## Is your feature request related to a problem? Please describe.
In a current project we have a distinction between American english and Great Britten english. It seems that if I add the language 'en-GB' and serverLanguageDetection is true and my browser primary language is 'en-GB' that it will select 'en' and not 'en-GB'

## Describe the solution you'd like
I would like to be able to support regional locales. Please let me know your thoughts about this feature.

**Comment by isaachinman** [comment]
Hi @bobsingor - that's correct: we don't currently support regional locales. It interacts slightly weirdly with `localeSubpaths`, so we've just avoided the complication so far. It's certainly possible to do that piece of work and support regional locale codes, both in terms of detection and also subpaths.

However, I don't personally have this need in any of my projects at the moment, so it's not something I will be personally undertaking anytime in the near future.

Regardless, we'll leave this issue open to track the feature request and see how many others need it.

**Comment by porfirialex** [comment]
Is there any quick work around?

**Comment by BondoS** [comment]
@porfirialex fully functional, but, still work in progress
https://github.com/BondoS/next-i18next-ex

**Comment by isaachinman** [comment]
Hi @porfirialex. I plan to implement this relatively soon. The new API will require you to provide the actual subpath for each locale that you want. Will look something like:

```jsx
const nextI18NextConfig = {
  ...otherConfigStuff,
  localeSubpaths: {
    en: '/en',
    'en-GB': '/custom-uk-path',
    es: '/for-spanish-traffic',
  }
}
```

I think this is the most sensible and flexible approach, unless someone else has another idea?

In the meantime, the workaround is just to use normal NextJs custom routes.

**Comment by porfirialex** [comment]
Hi @isaachinman  It seems good to me. Let me know if you need help.

**Comment by isaachinman** [comment]
The biggest issue here is we need to decide what happens if a user provides some locale subpaths, but not all.

@porfirialex If you feel like getting into it, please feel free.

**Comment by porfirialex** [comment]
i'm not sure if i understand you correctly. 
Possible solution:
`const nextI18NextConfig = {
  ...otherConfigStuff,
  localeSubpaths: 'xxx',
  localeRegions: {
    'en-GB': '/custom-uk-path',
     'es-AR': '/custom-argentine',
  }
}`

**Comment by PeerRich** [comment]
neither zh-CN nor sc is working for us :( any ideas? https://github.com/calendso/calendso/issues/1605

**Comment by isaachinman** [comment]
@PeerRich The `next-i18next` package doesn't touch locales at all, anymore. They are handled directly by NextJs and i18next. Happy to help debug if you provide more info, but ultimately the solution will lie somewhere outside `next-i18next`.
