### ISSUE TITLE
Provide option to disable redirects for API usage

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#281]
Hello, I would like to reuse a single i18next instance for the page and api router in my express application. In `foreign` mode all api requests are [redirected](https://github.com/isaachinman/next-i18next/blob/1d0f50d2fce5c1a34d338843a692f526e50c6821/src/utils/lng-path-detector.js#L31) with a prefix of the detected language for

```
/api/foo         ---> incoming request
/de/api/foo      ---> redirect
```
this is not ideal and it should be possible to disable it.

e.g with another option `redirect: <boolean>`

```js
const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de'],
  redirect: false
})
```

My workaround is to create a different instance with `localeSubpaths: NONE`.

**Comment by Ktchan825** [comment]
Would this config works for you?
```
const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de'],
  ignoreRoutes | ['/_next', '/static', '/api']
})
```

**Comment by StarpTech** [comment]
I don't think so because then everything is ignored and if you look at the middleware code the default language won't be set right?

**Comment by StarpTech** [comment]
@ktchan825 no, I think you're right I will test it thanks!

**Comment by StarpTech** [comment]
@Ktchan825 This doesn't work if I ignore `/api` the `req.t` helper function isn't set.

**Comment by isaachinman** [comment]
The `ignoreRoutes` option causes the pattern to be skipped completely by `i18next-express-middleware` - that's what puts the translate function on the `req`.

While this is an interesting request / use case, I'm not sure that using a React/Next package to do NodeJs localisation is appropriate. What do you need to translate in your API that is outside your React tree? I would think that having two i18n instances is acceptable and actually preferable in that case.

@StarpTech Do you have a proposed solution for how `next-i18next` might support your use case?

**Comment by Ktchan825** [comment]
@StarpTech I see, You need translation for /api request without redirect. I think [Multiple Zone](https://github.com/zeit/next.js/#multi-zones) might what you need.

Btw, it sounds a valid case not to redirect some specific path. Can we have a new config and have a check before adding the locale subpath in `lng-path-corrector.js`?

**Comment by StarpTech** [comment]
Hi @isaachinman,

> While this is an interesting request / use case, I'm not sure that using a React/Next package to do NodeJs localisation is appropriate. What do you need to translate in your API that is outside your React tree?

I maintain a single api for client and SSR. I render the data as it is and some text is generated conditionally e.g prices. When no price is available in the country the price "On request" is returned. This can be moved to the view but it was easier to maintain that logic in a single place. In other cases my api serve as simple content store for landing pages. Instead to translate it directly in the view the app has to only consume the api with correct lang settings. 

You're definitely right that this can be moved to the view in many cases and I will but my use case can be very beneficial in some cases.

**Comment by isaachinman** [comment]
> my use case can also be very beneficial

Sure - but `next-i18next` is a package that aims to translate React views. I'm hesitant to increase the scope in any sort of way to start supporting non-view-based localisation.

Supporting `localeSubpaths` is already complicated enough as-is, and adding the ability to blacklist subpaths is not something that I see happening. Let's see if we can keep discussing this issue and discover a solution that doesn't involve adding/changing the package's API.

**Comment by StarpTech** [comment]
> Sure - but next-i18next is a package that aims to translate React views

That's right but a middleware or http routing is already out of the scope of React views and therefore we can tackle also related problems but I'm totally fine with creating a second instance. I see your point regaring complexity.

**Comment by isaachinman** [comment]
> I'm totally fine with creating a second instance

This is what I would recommend. You'll just need to make sure that you use the same config settings (especially cookie value) across both instances, and you shouldn't have any problems whatsoever.

**Comment by StarpTech** [comment]
@isaachinman thanks!

**Comment by isaachinman** [comment]
I'm going to mark this as closed, but happy to reopen and continue discussion if anyone would like.
