### ISSUE TITLE
Inline required namespaces in page

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#282]
Hello,
is it possible to inline resource files in the page? This would simplify caching and speed up for components which are rendered on client side only.
Thank you.

**Comment by isaachinman** [comment]
Can you explain in a bit more detail what you mean? If you pass your resource dependency into `namespacesRequired`, it'll be available on first render.

**Comment by StarpTech** [comment]
My page has to require 3 namespaces. Except for the common it will make 2 XHR requests in order fetch the others. How can I avoid it?

**Comment by isaachinman** [comment]
> How can I avoid it?

If you pass your resource dependency into namespacesRequired, it'll be available on first render.

See the [docs here](https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies).
