### ISSUE TITLE
Explain common/default namespace better

### ISSUE THREAD

**Issue by quorak** [isaachinman/next-i18next#284]
## Describe the bug
From the description I thought the common namespace lenguage keys will be always available. They are for the `defaultLanguage`, but not for other `otherLanguages: ['de']` . I had to use the `i18nKey="common:skip"` instead of `i18nKey="skip"` . It works but I had to figure it out and it came not naturally, even though `i18nKey="skip"` worked for the default english language.

## Occurs in next-i18next version
0.37.0

## Steps to reproduce
```
import React from 'react';
import { i18n, Link, withNamespaces, Trans } from '../src/i18n'


class SolutionPage extends React.Component {
  static async getInitialProps() {
    return {
      namespacesRequired: ['common','onboarding'],
    }
  }
    return (
      <React.Fragment>
      <Trans i18nKey='common:skip'/>
      <Trans i18nKey='skip'/>
      </React.Fragment>
    );
  }
}

SolutionPage.propTypes = {
  classes: PropTypes.object,
};

export default withRoot(withNamespaces('onboarding')(withStyles(styles)(SolutionPage)));
```

## Expected behaviour
```<Trans i18nKey='skip'/>``` would also work for otherLanguages

## Screenshots
![image](https://user-images.githubusercontent.com/68172/56890142-ec06d000-6a78-11e9-83b9-bd8b69c537b4.png)

**Comment by isaachinman** [comment]
Not sure exactly what your point is here, but it seems like you have a problem with how `react-i18next` works? Please open an issue over there. Good luck.
