### ISSUE TITLE
Improve development experience

### ISSUE THREAD

**Issue by quorak** [isaachinman/next-i18next#285]
## Is your feature request related to a problem? Please describe.
When adding new keys to the translation files, they are only picked-up after a restart of the nextjs environment environment.

## Describe the solution you'd like
instant recompilation

## Describe alternatives you've considered
* switching default ant otherLanguages

**Comment by isaachinman** [comment]
Duplicate of #214.

**Comment by felixmosh** [comment]
I've developed [`i18next-hmr`](https://github.com/felixmosh/i18next-hmr) in-order to hot reload **client** & **server** when translations are changes
