### ISSUE TITLE
Incomplete list of options in README

### ISSUE THREAD

**Issue by amrelhosseiny** [isaachinman/next-i18next#29]
The options section in README.md state that a full list of options is : 

defaultLanguage 
otherLanguages 
localePath
localeStructure 
localeSubpaths 
defaultNS 
use 

But i couldn't change the language to a specific language, i.e. "en-us" instead of "en".
Exploring the default configuration at node_modules\next-i18next\dist\config\default-config.js, I found 
'load' is set to  'languageOnly', so in my i18n.js I did this:

const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next(
    { 
        defaultLanguage: "en-us",
        otherLanguages: ['de'],
        load: 'all'
    }
)

and it works fine, so are all the options in that file configurable? if so then the README was a little misleading.

**Comment by kachkaev** [comment]
I somewhat agree. The way the [table with options](beefy packs https://concentra-analytics.visualstudio.com/_git/orgvue-js/pullrequest/1538​​​​​​​) is presented in README suggests that no other keys would change anything. But in fact, the same options get passed to I18n, which actually makes it possible to tweak quite a few things.

**Comment by isaachinman** [comment]
The options tables contains those options which are _specific to `next-i18next`_.

Pretty much all other i18next options can be passed in, as you've discovered.

**Comment by kachkaev** [comment]
>Pretty much all other i18next options can be passed in, as you've discovered.

An extra line in README stating this can be a big help for newcomers.

**Comment by isaachinman** [comment]
c353671
