### ISSUE TITLE
Use custom express middleware

### ISSUE THREAD

**Issue by haf** [isaachinman/next-i18next#294]
Hello,

I'm trying to use the `i18next-node-locize-backend` middleware, so I can speed up my translating of my site. I've asked the Locize team [in this issue](https://github.com/locize/locize-examples/issues/2#issuecomment-488768926) and I've tried a few alternatives to add their middleware too this module, but currently to no avail. (Details in the linked comment)

I've tried; adding the middleware to the `use` array, and adding an instantiated `Backend` instance to the same, with different error messages.

## Occurs in next-i18next version
`"next-i18next": "^0.37.0"`

## Behaviour

I get an error Error: Invalid URI "/Users/h/dev/qv2/static/locales/en/common.json"

## Screenshots

![image](https://user-images.githubusercontent.com/193115/57158964-062c0f80-6de5-11e9-98dd-7b749caa3786.png)

## Summary

Thanks for a great project; it's working fabulously for me. I hope you can find the time to answer this question.

**Comment by isaachinman** [comment]
Can you check #151 and see if that helps with your use case?

**Comment by haf** [comment]
I read through 151 and it goes through how to configure custom file locations as far as I can tell; it doesn't seem to go through how to instantiate dynamic backends that themselves fetch. This is consistent with the behaviour I'm getting, with an error mentioning the file system rather than anything from the API call.

**Comment by isaachinman** [comment]
@haf Perhaps let's start like this: can you copy/paste a full `react-i18next` configuration that you would expect to work with your desired setup? I can then work backwards to see what it would take for us to support it, if we don't already.

I am going on holiday shortly but know that I am committed to helping users as much as humanly possible - just might take a bit longer.

**Comment by haf** [comment]
```js
import NextI18Next, { defaultConfig } from 'next-i18next'

const locizeConfig = {
  // the id of your locize project
  projectId: 'CHANGEME',
  // add an api key if you want to send missing keys
  apiKey: 'CHANGEME',
  // the reference language of your project
  referenceLng: 'en',
  saveMissing: true,
  // version - defaults to latest
  version: '2.0.0',
  // private - set to true if you version on locize is set to use private publish
  private: false
}

// https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/locize
const defaultConfig = {
  defaultLanguage: 'en',
  otherLanguages: ['sv'],
  use: process.browser ? [] : [ require('i18next-node-locize-backend') ],
  backend: locizeConfig
}

const instance = new NextI18Next(defaultConfig)
export const config = instance.config
export const i18n = instance.i18n
export const appWithTranslation = instance.appWithTranslation
export const withNamespaces = instance.withNamespaces
export const Trans = instance.Trans
export const Link = instance.Link
export const Router = instance.Router
export default instance
```

**Comment by isaachinman** [comment]
So first of all, `i18n.use(i18nextNodeBackend)` is indeed hard coded [here](https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L15).

I think we need to step back and consider how best to support flexible backends in a sensible way. Users without a `fs` backend would probably need to manually specify all their namespaces as well, so that i18next knows what to load.

I'm not 100% sure that `i18next-express-middleware` works without `i18next-node-fs-backend`. @jamuhl are those interdependent, or independent?

**Comment by jamuhl** [comment]
this i18n.js is what i came up with:

```js
const isNode = require("detect-node");
const i18nextLocizeBackend = require("i18next-locize-backend");
const { localeSubpaths } = require("next/config").default().publicRuntimeConfig;
const NextI18Next = require("next-i18next/dist/commonjs");

const use = [];

if (isNode) {
  const i18nextNodeLocizeBackend = eval(
    "require('i18next-node-locize-backend')"
  );
  use.push(i18nextNodeLocizeBackend);
} else {
  use.push(i18nextLocizeBackend.default);
}

module.exports = new NextI18Next({
  otherLanguages: ["de"],
  localeSubpaths,
  use,
  saveMissing: true,
  backend: {
    loadPath: "https://api.locize.io/{{projectId}}/{{version}}/{{lng}}/{{ns}}",
    addPath: "https://api.locize.io/missing/{{projectId}}/{{version}}/{{lng}}/{{ns}}",
    referenceLng: "en",
    projectId: "9dc2239d-a752-4973-a6e7-f622b2b76508",
    apiKey: "9f019666-2e71-4c58-9648-e6a4ed1e15ae",
    version: "latest"
  }
});
```

but @isaachinman is right you will need to define all namespaces for serverside preloading yourself.

**Comment by isaachinman** [comment]
I've reworked things a bit with #302 - this should be a lot easier to accomplish. The backend config object is fully customisable now. If you provide `config.ns`, the config creation process will not do a filesystem lookup of namespaces now.

**Comment by haf** [comment]
@jamuhl @isaachinman Thanks for the answers; I've come around to fixing this now. I have a question about @jamuhl 's code sample; does the backend you import mean that you don't use the default file-based/import-based backend when running in the browser?

**Comment by jamuhl** [comment]
It's the same as without - just fs is replaced with remote backend on serverside and xhr backend on clientside is not pointing to the server but to locize -> initialStore, ... are not touched

**Comment by adrai** [comment]
https://github.com/locize/next-i18next-locize
