### ISSUE TITLE
Get negotiated locale statically server/client-side

### ISSUE THREAD

**Issue by haf** [isaachinman/next-i18next#295]
## Is your feature request related to a problem? Please describe.
I'd need the locale for fetching localised content from the blog provider in `static getInitialProps`. `req` is null client-side and `navigator.language`, server-side. Also, I need to take cookies and any other mechanism of lang neg into account. How do I do this?

## Describe the solution you'd like
Being able to see the currently active `language` in the static function.

## Describe alternatives you've considered
- the utils function
- readinig the cookie
- reimplementing lang neg

## Additional context
Would be great to have this in the sample.

**Comment by isaachinman** [comment]
The `withNamespaces` HOC adds a language prop and should be used for this sort of thing.

You should set your cookie preferences via the config. If you find yourself doing imperative stuff with cookies, you've lost a lot of the benefit of this package.

Let me know if you have any other questions.

**Comment by isaachinman** [comment]
Ah, if you need it inside your `static` method you'll need to check `req.lng` or `req.i18n`. Neither of these approaches are recommended or officially supported, though.

**Comment by haf** [comment]
> The withNamespaces HOC adds a language prop and should be used for this sort of thing.

Not statically

> method you'll need to check req.lng or req.i18n

No, that doesn't work on the client

**Comment by isaachinman** [comment]
On the client you can check the actual `i18n` instance I suppose. Can you please explain your use case?

**Comment by haf** [comment]
I'm loading i18n-ed blog posts via; it works both in the browser and on the server https://buttercms.com/docs/api/?javascript#get-your-blog-posts

Some blog posts are in Swedish and therefore not optimal for international consumption, whilst others are in English (all can see) and perhaps going forward, in more languages.

**Comment by haf** [comment]
Current workaround:

```

BlogIndex.getInitialProps = async ({ query, req }: any) => {
  const page = query.page || 1
  const tag_slug = req != null ? req.language : i18next.i18n.language
  const listing = await list({
    page,
    page_size: 10,
    exclude_body: true,
    tag_slug
  })
  return {
    namespacesRequired: [ 'blog', 'common' ],
    ...listing
  }
}
```

However, this doesn't adjust "live" when the language is changed globally, but requires a navigation event away and back again.

**Comment by isaachinman** [comment]
Is this related to #299? I am not sure why users are expecting this package to trigger `getInitialProps`... Perhaps there has been a miscommunication. The `Link` component that `next-i18next` exports is _identical_ to that from the NextJs core, it just does some path correction on top. Whether or not `getInitialProps` is called comes down to how you do navigation.

The reason why we don't have a "global" object where you can check `i18n.lng` is because i18next instances are created and serialised for each network request to allow for concurrency. Simply put, if you are in a SSR environment, you will need to check `req.x`, and obviously that's not possible in the client environment.

What you're doing to generate `tag_slug` there seems reasonable to me, although I'd use a strict equality check.

Let me know if you have any further questions.

**Comment by haf** [comment]
Obviously. But I'd rather have helper function available than, like now, having to debug my way to where the language is placed on the request. Something like `requestLang: Request -> string`

**Comment by isaachinman** [comment]
The `req.language` bit is handled by [i18next-express-middleware](https://github.com/i18next/i18next-express-middleware), so we wouldn't be maintaining anything on the `next-i18next` side. You could open an issue on the middleware, requesting some `req.getLanguage` helper, but in the end it's simple enough to do `req.language`.

**Comment by haf** [comment]
I guess what I'm saying is that this is neither documented in code, or docs and the wishlist here is to address that by adding a utility that bridges client/server rendering logic. I don't find this wish conflicting with anything you've said above.

**Comment by isaachinman** [comment]
It adds scope to the API and increases cost of maintenance. We could certainly improve docs.
