### ISSUE TITLE
No render on export

### ISSUE THREAD

**Issue by ipatate** [isaachinman/next-i18next#296]
next-i18next work fine for ssr but when i export my app, i have juste 
```html
<div id="__next"></div><script id="__NEXT_DATA__" type="application/json">....</script>.
```
The export call getInitialProps but not render the page.

next 8.1.0
next-i18next 0.39.0

My example repo is here : https://github.com/ipatate/next-with-i18n

many thanks

**Comment by isaachinman** [comment]
Your app runs fine as a client-side-only exported app:

<img width="684" alt="Screenshot 2019-05-07 at 11 01 57" src="https://user-images.githubusercontent.com/10575782/57291575-9f924480-70b7-11e9-812d-1a3ab25b856c.png">

Please read the [documentation](https://github.com/isaachinman/next-i18next#notes) before opening new issues:

> `next export` will result in a client-side only React application.

**Comment by ipatate** [comment]
@isaachinman read the bug please, the body on static files has just <div id="__next"></div>.
Yes the list is here on browser but not in source file generated.

![next](https://user-images.githubusercontent.com/46760/57292728-eb96b680-70c2-11e9-80da-57ac1e50407f.jpg)

**Comment by isaachinman** [comment]
There is no SSR when you do `next export`. Perhaps we have had a miscommunication?

**Comment by ipatate** [comment]
If i remove in pages "withNamespaces" and i remove the file _app.js, after export, i have the data is in the html source. Ex: https://github.com/ipatate/next-with-i18n/tree/without-i18n

next-i18next works with the SSR but not with export static html in my code. 

![Capture d’écran 2019-05-07 à 15 56 56](https://user-images.githubusercontent.com/46760/57305251-09731400-70e1-11e9-92e1-2de59e180d2f.jpg)

**Comment by isaachinman** [comment]
I am not sure how else I can communicate this: doing `next export` on a `next-i18next` project results in a client side _only_ application. None of this SSR localisation stuff works without a Node/Express process. Good luck.

**Comment by ipatate** [comment]
ok, thanks
