### ISSUE TITLE
how to set initLanguage from queryString?(?lang=en)

### ISSUE THREAD

**Issue by huanglijiao** [isaachinman/next-i18next#300]
## Is your feature request related to a problem? Please describe.
I want to get lang from queryString, then set the language of i18n instance. the url is: 
http://www.joox.com/zh_my/kplaylist?page=kplaylist&id=444&lang=zh_CN&country=hk

the same on server and client.
so how to set initLanguage of i18n instance from queryString?(?lang=en)

**Comment by isaachinman** [comment]
This behaviour is supported out of the box. You'll need to play with [config.detection](https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.js#L36).

**Comment by huanglijiao** [comment]
I want to get lang from queryString, then set the language of i18n instance. the url is:
http://www.joox.com/zh_my/kplaylist?page=kplaylist&id=444&lang=en&country=hk
 
I want to set the init language by lang and country, for example

initLangauge=`${lang}_${country}`;

I know next-i18next supports adding own detection functionality. 
`export default {
  name: 'myDetectorsName',

  lookup(options) {
    // options -> are passed in options
    return 'en';
  },

  cacheUserLanguage(lng, options) {
    // options -> are passed in options
    // lng -> current language, will be called after init and on changeLanguage

    // store it
  }
};`

but I need to get the params by queryString firstly, then I can set options of i18n. So how to deal with it?

**Comment by isaachinman** [comment]
This is a general i18n question and is not directly related to `next-i18next`. Please either post in one of the appropriate i18next repos, or on StackOverflow.

**Comment by martpie** [comment]
For anyone interested in the actual solution:

in your `next-i18next` config:

```
detection: {
    caches: ['cookie'],
    cookieSameSite: 'strict',
    lookupQuerystring: 'lang', // default is lng
    lookupCookie: 'next-i18next',
    order: ['querystring', 'cookie', 'header'], // IMPORTANT
  },
```

then `?lang=de` will deliver the german page for example.

I also realized `querystring` should always be before `cookie`. I will submit a PR for that.
