### ISSUE TITLE
The response is not ended after redirected to the new Url

### ISSUE THREAD

**Issue by Ktchan825** [isaachinman/next-i18next#304]
## Describe the bug
```
server.use(nextI18NextMiddleware(nextI18next));
...
server.get('/', (req, res) => {
res.setHeader('Content-Type', 'text/html');
...
})
```
The above code will report ```UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client```

## Occurs in next-i18next version
v0.37.0

## Steps to reproduce
https://github.com/Ktchan825/next-i18next
```
git clone https://github.com/Ktchan825/next-i18next
cd examples/simple
yarn && yarn dev
```
In your browser, navigate http://localhost:3000/da or any page not exist
In your server console, You can see res.headersSent is true 

## Expected behaviour
I don't expect a middleware will send the response header to the client, such that I cant use res.setHeader in rest of my route.

## OS (please complete the following information)
 - Device: Mac mini
 - Browser: Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
Can you explain what the status/response being sent by the middleware is? The only thing we do with `res` is perform redirects in the case of a `localeSubpath` mismatch.

**Comment by Ktchan825** [comment]
Hi @isaachinman
The response causing this issue is a 302 redirect.
The middleware is still calling `return next();` after calling `res.redirect(302, xxx);`

I think we should not execute `next();` if we have already redirected the client to a new url.
please correct me if my understanding is incorrect

**Comment by isaachinman** [comment]
Yes, that is completely correct. Not sure how this one slipped by. @capellini Do you have any time to look into this? Looks like this was a joint effort three months ago.

**Comment by capellini** [comment]
@isaachinman yes I can take a look.  Ending the response and not calling `next()` will make the sequence of calling middleware important (e.g. if you intend to log all requests, you should put the logging middleware before ours).  I suppose we can always state that in the docs.  At first glance, I don't see a way around forcing this order to precedence (and, I think, most people put their most critical middleware first anyway).

**Comment by Druux** [comment]
@isaachinman I am still getting the error mentioned  by @Ktchan825 by using the simple environment suggested in the next-i18next example directory. Did I miss something?

**Comment by isaachinman** [comment]
@Druux What error are you referring to? Can you provide more information?

**Comment by Druux** [comment]
@isaachinman I am referencing to the `UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`.
The error occurred when I added `localeSubpaths` to the NextI18Next initialization by requesting next's **_error.js**.

**i18n.js**
```
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
   localePath: 'locales',
   defaultLanguage: 'en',
   otherLanguages: ['de'],
   localeSubpaths: {
      de: 'de'
   }
})
```

The rest of my implementation is virtually identical to the one in the example folder.

**server.js**
```
...
const server = express()
server.use(nextI18NextMiddleware(nextI18next))
server.get('*', (req, res) => handle(req, res))
...
```

**_error.js**
```
import { withTranslation } from 'locales'

const ErrorPage = ({ t }) => (
   <p>{t('test')}</p>
)

ErrorPage.getInitialProps = () => ({
   namespacesRequired: ['common', 'error'],
})

export default withTranslation(['common', 'error'])(ErrorPage)
```

My environment is:
"next": "^9.0.2"
"i18next": "^17.0.11"

**Comment by isaachinman** [comment]
@Druux Following the snippets you've included, I am unable to reproduce this in the simple example dir. Can you please provide a full reproducible repository? If so, I can debug and fix any problems quite quickly.

**Comment by Druux** [comment]
@isaachinman After some further debugging I figured out that the the problem is caused by my custom `localePath` in combination with my webpack config `      config.resolve.modules.push(path.resolve('./'))` in next.config.js.
I make use of this config in order to use absolute imports.
My project structure looks like this:
```
| - locales
| --- de
| --- en
| --- index.js (next-i18n init)
| - pages
| - next.config.js
| - server.js
| - etc.
```

Are you aware of that kind of specific issue or should I rethink the way I want to structure my locales?

**Comment by isaachinman** [comment]
@Druux Glad you isolated it. However, that now means we've gone off topic for this issue. Your `locales` directory needs to be inside the `static` NextJs dir, or available via network requests in some other way.

I don't use absolute imports and can't give any advice there. Good luck!

**Comment by Druux** [comment]
@isaachinman Everything works fine for me new. But I figured out that the Error `UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` still occures when I manually try to call mydomain.com/fnjksf (404 not found) instead of mydomain.com/en/fnjksf. Are you experiencing the same?

**Comment by isaachinman** [comment]
@Druux No, if you set the `localeSubpaths` option to [all](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/i18n.js#L14) in the simple example, you'll see that a redirect occurs when you hit `http://localhost:3000/second-page`.

This behaviour is also covered in our e2e tests.

If you believe you've found a new bug, please open a new issue.
