### ISSUE TITLE
Support for unshallow routing when language has changed

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#305]
Hi,
it would be great if we could provide an option to allow a reload of `getInitialProps` of the active page. Currently, [shallow routing](https://github.com/isaachinman/next-i18next/blob/6f69e7c62dc230cb087e3c3d6749a9858ab053c7/src/hocs/app-with-translation.js#L27) is used.

The problem I'm trying to solve is really common. I have static translation which works great but my product data is fetched from an external source. How should I fix it without to trigger a real browser reload? 

This is also useful if you use `routeChangeComplete` for analytics. Right know, `routeChangeComplete` has to be fired twice if you want to trigger a refetch of `getInitialProps` after a language change. 

Related:
https://github.com/isaachinman/next-i18next/issues/299

### Proposal:

```js
const NextI18NextInstance = new NextI18Next({
  shallowRouteChange: false
})
```

**Comment by lipoolock** [comment]
Hi @StarpTech @isaachinman 
I agree the proposal with a flag. This will let the previous and classic behaviour as expected and allow us (people concerned by full refresh) accessing a way to avoid calling Route in parallel to `i18n.changeLanguage`

**Comment by isaachinman** [comment]
@lipoolock There would never be a "full refresh" from a browser perspective. We're talking about a route re-render at the NextJs level.

**Comment by isaachinman** [comment]
@StarpTech I've added this behaviour to the core functionality without a flag as I believe it's the right way forward. Feel free to review, and let me know what you think.
