### ISSUE TITLE
Support for custom routes and Router.push

### ISSUE THREAD

**Issue by simofacc** [isaachinman/next-i18next#31]
Hi,

I have implemented the code to switch languages but I saw an issue with custom routes and Router.push.

Does this package support either custom routes or Router.push yet?

Thanks!

**Comment by isaachinman** [comment]
1. This package does not support `Router.push` and probably never will. Imperative routing is up to the user, and you should be aware of the `as` property.
2. This package does not support custom routes, but possibly could in the future. At the present moment, I have no idea how we'd achieve that. Again, it's most likely best left up to the user.

To help with both, I could expose [lng-path-corrector](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lng-path-corrector.js) and [lng-path-detector](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lng-path-detector.js).

The corrector takes a path and returns the corrected path based on language, and the detector takes a `req, res` and returns the current language.

Let me know what you think. We certainly won't be supporting either of these features anytime soon, as they're both quite complicated and easy to achieve on your own.

**Comment by simofacc** [comment]
I actually managed to fix both scenarios.

1. For Router.push I created a separate function and I am using that as the main Router.push function

`import { config, i18n } from '../i18n';
import Router from 'next/router';

class RouterHelper {
    push(href) {
        const { defaultLanguage, localeSubpaths } = config;
        let lng = null;
        if (Array.isArray(i18n.languages) && i18n.languages.length > 0) {
            [lng] = i18n.languages;
        }
        if (localeSubpaths && lng && lng !== defaultLanguage) {
            return Router.push(`/${lng}${href}`);
        }
        return Router.push(href);
    }
}

const routerInstance = new RouterHelper();
export default routerInstance;`

2. With regards to custom routes it wasn't that difficult either.

`//Add Language path first
routesArray.forEach(({ page, path }) => routes.add(`/:lang${path}`, page));

//Add non-language paths at the end
routesArray.forEach(({ page, path }) => routes.add(path, page));`

**Comment by isaachinman** [comment]
> easy to achieve on your own

I'm glad you agree, then!

In general you're going to run into problems if you don't use [the `as` option](https://github.com/isaachinman/next-i18next/blob/master/src/components/Link.js#L37).

If you're having problems with i18next, I suggest you create a reproducible example and post on StackOverflow.
