### ISSUE TITLE
"TypeError: Cannot read property 'wait' of null" on production only

### ISSUE THREAD

**Issue by chlec** [isaachinman/next-i18next#311]
## Describe the bug
next-i18next works fine in development, but when I'm building and running it, I got this error server-side: 
```
react-i18next:: You will need pass in an i18next instance either by props, using I18nextProvider or by using i18nextReactModule. Learn more https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow
TypeError: Cannot read property 'wait' of null
```

I checked issue #252 but it doesn't work for me.

## Occurs in next-i18next version
0.37.0

## Expected behaviour
It should translate and not getting error

## Additional context
Here what's my code looks like:

i18n.js:
```javascript
const NextI18Next = require('next-i18next').default

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'fr',
  fallbackLng: "fr",
  otherLanguages: ['en'],
  defaultNS: "common",
})

module.exports = NextI18NextInstance
```

_app.js:
```javascript
import React from 'react'
import App, { Container } from 'next/app'
import { appWithTranslation } from '../i18n'

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    const { hostByLocale } = ctx.req || window.__NEXT_DATA__.props;

    return {
      hostByLocale,
      pageProps: { ...pageProps, hostByLocale },
    };
  }

  render() {
    const { Component, pageProps } = this.props
    return (
      <Container>
        <Component { ...pageProps } />
      </Container>
    )
  }
}

export default appWithTranslation(MyApp)
```

navigation.js (my component, I modified it but it looks like this):
```javascript
import React from 'react'
import { connect } from 'react-redux'
import { withNamespaces } from '../../i18n'

class Navigation extends React.Component {

    render() {
        const { t } = this.props

        return (
            <div>
                <p>{ t('sentence1') }</p>
                <p>{ t('sentence2') }</p>
            </div>
        )
    }
}

function mapStateToProps(state) {
  return {
      ...state
  }
}

export default connect(mapStateToProps)(withNamespaces('common')(Navigation))
```

I also set `server.use(nextI18NextMiddleware(nextI18next))` in my server. All my translations are in the /static/locales folder. I'm also using a HOC to check if the user is signed in but I'm not sure this is related.

Everything works fine when I'm running in development, so I don't know why I'm getting this error in production.

**Comment by isaachinman** [comment]
The error is explanatory and points to your problem. Console log the value of `const NextI18NextInstance`, and you'll most likely see that it's `undefined`.

**Comment by chlec** [comment]
I tested both in dev and in prod, and there is a value

```
NextI18Next {
  config:
   { defaultLanguage: 'fr',
     otherLanguages: [ 'en' ],
     load: 'currentOnly',
     localePath: 'static/locales',
     localeStructure: '{{lng}}/{{ns}}',
     localeSubpaths: 'none',
     ns: [ 'navigation' ],
     use: [],
     defaultNS: 'navigation'
     ...
```

**Comment by isaachinman** [comment]
Reverse the order of your `connect` HOC and please search issues in the future.

**Comment by chlec** [comment]
Thank you for your quick answers, but this is the same thing, I read many issues and tries many different things, I'm facing this issue since 3 days.

```
react-i18next:: You will need pass in an i18next instance either by props, using I18nextProvider or by using i18nextReactModule. Learn more https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow
TypeError: Cannot read property 'wait' of null
TypeError: Cannot read property 'wait' of null
TypeError: Cannot read property 'wait' of null
TypeError: Cannot read property 'wait' of null
```

It's weird because in development it works and translate perfectly...

**Comment by isaachinman** [comment]
If you provide a reproducible repository I can debug it for you.

**Comment by chlec** [comment]
You can see a repo I just made here: https://github.com/chlec/next-18next-issue

This is just a server with the same HOCs I'm using on my project (I just let them blank here).

When you start in development by using 'npm run dev', you'll see 2 buttons with translated texts, but when you build and start the server, you'll see the error I got.

**Comment by isaachinman** [comment]
Not sure why you're [doing this](https://github.com/chlec/next-18next-issue/blob/master/index.js#L10), but don't. Your issue will go away.

**Comment by chlec** [comment]
Well, it solves my problem, I didn't know it was a bad practice, but thank you a lot!

Sorry for the waste of time, I though it was linked to your package...

**Comment by mnill** [comment]
@chlec can you please publish how you resolved this issue?

**Comment by tomaswitek** [comment]
@chlec or @isaachinman could you pls provide more details? Those links are returning 404s :(

**Comment by chlec** [comment]
I had a line of code like this in my project:
`process.env.PORT = process.env.PORT || 80`
and I don’t know why but it’s break the library.
