### ISSUE TITLE
Router can't be used on SSR

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#314]
Hello,
the current approach to access the router

```jsx
import { Router } from '~/i18n';
// in the render function
Router.pathname
```
isn't compatible with SSR. I got following error:

```
Error: No router instance found.
You should only use "next/router" inside the client side of your app.
```

when I use the HOC it works fine!

```jsx
import { withRouter } from 'next/router'
// in the render function
Router.pathname
```

since the current implementation only wraps the next router I would expect the same functionality.

**Comment by isaachinman** [comment]
> Router can't be used on SSR

That's correct. You'll find the same error if you import `Router` from `next/router`.

If you're requesting a wrap of `withRouter`, that's totally separate and is probably related to #4.

**Comment by StarpTech** [comment]
I'm interested in a version similiar to next.js HOC.

> If you're requesting a wrap of withRouter, that's totally separate and is probably related to #4.

The thread discussion has shifted to a imperative solution and there is no point regarding a isomorphic solution.

**Comment by isaachinman** [comment]
The title and entire point of that issue is a HOC, and follows this comment: https://github.com/isaachinman/next-i18next/issues/1#issuecomment-438187263.

If you feel as though you'd like to open a new issue to track the feature request, please do.
