### ISSUE TITLE
next-i18next not work in function component

### ISSUE THREAD

**Issue by huanglijiao** [isaachinman/next-i18next#317]
I used the next-18next example. [example url](https://github.com/isaachinman/next-i18next/tree/master/examples/simple), and modified the i18n.js:
```
const { localeSubpaths } = require("next/config").default().publicRuntimeConfig;
const NextI18Next = require("next-i18next/dist/commonjs");

module.exports = new NextI18Next({
  otherLanguages: ["de"],
  localeSubpaths,
  detection: {
    order: ["querystring", "navigator"],
    lookupQuerystring: "lang"
  }
});

```

I added detection, then it worked well.  the request url : http://localhost:3000/?lang=de

But then I modified the index.js. I changed 'class' into function compnent:
```
import React from "react";
import PropTypes from "prop-types";

import { i18n, Link, withNamespaces } from "../i18n";

function Homepage(props) {
  const { t } = props;
  return (
    <React.Fragment>
      <button
        type="button"
        onClick={() =>
          i18n.changeLanguage(i18n.language === "en" ? "de" : "en")
        }
      >
        {t("h1")}
      </button>
      <Link href="/second-page">
        <button type="button">{t("to-second-page")}</button>
      </Link>
    </React.Fragment>
  );
}

Homepage.getInitialProps = async function(ctx) {
  return {
    namespacesRequired: ["common", "footer"]
  };
};

export default withNamespaces("common")(Homepage);

```

we used the url:  http://localhost:3000/?lang=de,  but detecting querystring was not work well.

**Comment by wcisco17** [comment]
I'm currently facing the same issue any progress? @huanglijiao

**Comment by capellini** [comment]
I can't replicate a problem using the code above, but maybe I'm not looking for the right bug.

When I use the above code and navigate to http://localhost:3000/?lang=de I see German and when I navigate to http://localhost:3000/?lang=en, I see English.  The one thing that I do see that may be an issue is that the '`lang` query parameter does not change when you change the locale by clicking the button.  But, if this was even considered an issue, it would be a react-i18next or i18next issue, I believe.

@wcisco17 and @huanglijiao - Can you elaborate on what is not working?

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by huanglijiao** [comment]
maybe you can refer to the demo. [demo url](https://github.com/huanglijiao/next-i18next-demo)

**Comment by isaachinman** [comment]
@huanglijiao I can't do `npm install` in that repo - it fails with a 404 on some package.

**Comment by huanglijiao** [comment]
@isaachinman maybe you can try! some package can not affect “npm run dev”.

**Comment by isaachinman** [comment]
This works as expected for regular locales. It seems like you may be pointing out that regional locales are not supported yet. See #279.

**Comment by huanglijiao** [comment]
@isaachinman you mean next-i18next can only support en and de ?  not support Chinese?

**Comment by huanglijiao** [comment]
@isaachinman react-i18next can support Chinese?
