### ISSUE TITLE
Storybook can't get translations from static/locales

### ISSUE THREAD

**Issue by RizziWilliam** [isaachinman/next-i18next#324]
After getting next-i18next into the project the stories from storybook wasn't working. The main problem was that storybook couldn't get i18n instance and because of that the storie was getting broken. If you wrapp the component to storie with appWithTranslation it do work, but it can't get the translations from he static/locales. This is how a storie of a component look's like : 

```
const CardSimplesStorie = appWithTranslation(withNamespaces('phrases')(CardSimples))

storiesOf('Card-simples', module).add('default', () => (
  <>
    
    <CardSimplesStorie />
  </>
))
```
In the storybook page you can see that the request to get the translations fails.

There is a way to get around that?

**Comment by isaachinman** [comment]
Currently `next-i18next` depends upon a middleware to load in namespaces. I am not aware of any workaround for storybooks, although it's an interesting point.

**Comment by RizziWilliam** [comment]
Hey @isaachinman after a day of research  i have found the way to do it. The problem was that storybook doesn't get your data from static folder by himself, you have to use the middleware,js config that is available to tell him to use it. This isn't very clear in storybook documentation, find this by dinging into issues in they github. What i did was create a middleware.js file inside storybook folder (.storybook) and then put the config there : 
```
const express = require('express')

const expressMiddleWare = router => {
  router.use('/static', express.static('./static'))
}

module.exports = expressMiddleWare
``` 

In the begging i was thinking that i have to put the nextI18NextMiddleware as we do in the config of next, but this wasn't necessary.

**Comment by isaachinman** [comment]
> This isn't very clear in storybook documentation

This has nothing to do with storybook documentation.

> put the nextI18NextMiddleware as we do in the config of next, but this wasn't necessary

It'd be necessary if you wanted to SSR your components. The workaround you've posted above works because you're exposing your static dir publicly as NextJs does automatically. Your client-wrapped `appWithTranslation` then performs client side network requests against `/static`.

Hope that all makes sense.

**Comment by justincy** [comment]
Here's what I did to get translations working in Storybook: https://gist.github.com/justincy/c1075650b1d5ba448c50eaf83cbb4ffe

**Comment by eric-burel** [comment]
Hi, using the v5 beta version of next-i18next (serverless version), and taking inspiration from @justincy gist posted just above, I've managed to setup i18n + storybook like this:

```js
// In .storybook/preview.js

// I reuse the same config as in my app
import { i18n } from "~/lib/i18n" 

// The decorator
const withI18n = (storyFn) => (
  <React.Suspense fallback={"Loading i18n..."}>
    <I18nextProvider i18n={i18n}>{storyFn()}</I18nextProvider>
  </React.Suspense>
);

addDecorator(withI18n)
```
and my i18n config, usable both in the app and in storybook: 
```js
import I18N from "next-i18next";
import { NextPageContext } from "next";

const i18nInstance = new I18N({
  defaultLanguage: "en",
  otherLanguages: ["fr"],
  localeSubpaths: {},
});

// reexport everything
export const {
  Trans,
  Link,
  Router,
  i18n,
  initPromise,
  config,
  useTranslation,
  withTranslation,
  appWithTranslation,
} = i18nInstance
```

**Comment by InsOpDe** [comment]
it is important that you have only one `react-i18next` version installed (check your `yarn.lock` or `package.lock`), otherwise it will happen that you locales are stored on two different stores not able to access each other

**Comment by rocketnova** [comment]
> it is important that you have only one `react-i18next` version installed (check your `yarn.lock` or `package.lock`), otherwise it will happen that you locales are stored on two different stores not able to access each other

I ran into this issue when attempting to install [`storybook-addon-i18next`](https://github.com/fynncfchen/storybook-addon-i18next) with next-i18next. Thank you @InsOpDe !
