### ISSUE TITLE
Custom server warning in README

### ISSUE THREAD

**Issue by elbotho** [isaachinman/next-i18next#325]
I think the readme should include a clear warning, that next-i18next requires a custom server and can therefore **not be used with `next export` or serverless (e.g. now V2)**.

I guess it's implicitly stated, but it took me quite a long time to piece it together. 
This might affect many next users.

Relevant Issues
#25 and #10

**Comment by isaachinman** [comment]
It _can_ be used with `next export` and there's already a notice about this in the README.

The installation instructions clearly state the process involving a custom server and in no way suggest that these steps are optional. What would be a helpful way to communicate this further?

We are tracking serverless support with #274.

**Comment by elbotho** [comment]
It sure had to do with my steep next-learning curve. I didn't realise that custom servers and now v2 don't go well together at first.
Maybe a note with link to the issue (#274) would be helpful.
