### ISSUE TITLE
localePath with src directory makes locale file request 404

### ISSUE THREAD

**Issue by anhdd-hnl** [isaachinman/next-i18next#328]
## Describe the bug
`localePath` inside `src` dir makes client request for locales file returns 404 due to incorrect path

## Screenshots
My project structure:
![pj-structure](https://user-images.githubusercontent.com/37301129/58700338-f09d0c00-83c9-11e9-8683-6c348d85f148.jpg)

My npm scripts:
```json
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "node ./src/server.js",
    "build": "next build ./src",
    "start": "next start ./src"
  }
```

My i18n.js:
```
const NextI18Next = require('next-i18next/dist/commonjs')

module.exports = new NextI18Next({
  defaultLanguage: 'vi',
  otherLanguages: ['en'],
  localePath: 'src/static/locales'
});
```

Bug:
- Client navigation for locales file returns 404 due to incorrect path:
![incorrect_path](https://user-images.githubusercontent.com/37301129/58700331-ea0e9480-83c9-11e9-81d3-00d8221987f7.png)

**Comment by kachkaev** [comment]
I also noticed this issue after upgrading. Solved like this in the end: https://gitlab.com/kachkaev/website-frontend/blob/master/src/i18n.ts#L54

**Comment by isaachinman** [comment]
@kachkaev Do you think this is a regression? Is this potentially what #327 is about?

Can anyone identify where this regression was introduced?

**Comment by brosbunbo** [comment]
@kachkaev It works for me, thanks alot.

**Comment by kachkaev** [comment]
> Do you think this is a regression?
I first thought it was, but then decided it was me not using the library as documented. Hard to say now which exact version introduced the change.

**Comment by isaachinman** [comment]
> Hard to say now which exact version introduced the change

Do you mind installing some previous versions and finding out, though? It sounds like a regression to me.

**Comment by isaachinman** [comment]
This is indeed a regression between v0.37.0 and v0.38.0.

@capellini This is almost certainly a result of 56363e4e3cf7c89f55675430efe7a251a7207eaa.

**Comment by isaachinman** [comment]
After looking through 56363e4, I'm not actually convinced this is a regression. Previously, we were assuming that all users were loading locales from the filesystem, and we were doing some "magic" with `process.cwd`. You'll need to do that manually now if you are specifying a `config.backend` object.

Here's an example from a working, production project on v0.40.1:

```jsx
const NextI18NextInstance = new NextI18Next({
  ...otherStuff,
  backend: {
    loadPath:
      typeof window === 'undefined'
        ? path.join(
            process.cwd(),
            'src/static/locales/{{lng}}/{{ns}}.json'
          )
        : `/mysubpath/static/locales/{{lng}}/{{ns}}.json`,
  },
})
```

Hope this helps. Let me know if anyone has any questions.

**Comment by radeno** [comment]
I think next-i18next should respect `dir` option for backend https://github.com/zeit/next.js/#custom-server-and-routing

**Comment by isaachinman** [comment]
@radeno How were you thinking that would work? Can you post some pseudo code?

**Comment by radeno** [comment]
We are currently migrating from custom implementation to next-18next and this information is missing. It takes a lot of time until we have find that it doesn't searching in right directory.

All our server settings was separated as independent files and in global `server.js` we have call it
`app` variable is next server, and `server` is express server.
So we were able to get path from `DevServer`
Eg from my localhost
```
DevServer {
  dir:
   '/Users/Rado/Development/myapp/src',
```
But we don't use it. But it should be a way. Our config was simpler. And Backend config was available not globally, but just for server environment. Eg:

```require('./src/server/i18n')(server, app, { isDev });```
```js
const i18nextMiddleware = require('i18next-express-middleware');
const i18nextBackend = require('i18next-node-fs-backend');
const I18n = require('../i18n');

module.exports = function(server, app, { isDev }) {
  I18n.use(i18nextBackend)
    .use(i18nextMiddleware.LanguageDetector)
    .init({
      ...I18n.options,
      preload: I18n.options.whitelist, // preload all languages
      backend: {
        loadPath: path.join(
          __dirname,
          `${localesDirectoryPath}/{{lng}}/{{ns}}.json`
        ),
        addPath: path.join(
          __dirname,
          `/${localesDirectoryPath}/{{lng}}/{{ns}}.missing.json`
        )
      },
      saveMissing: isDev
    });

  server.use(i18nextMiddleware.handle(I18n));

  // serve locales for client
  server.use('/locales', express.static(localesDirectory));

  if (isDev) {
    // missing keys
    server.post(
      '/locales/add/:lang/:ns',
      i18nextMiddleware.missingKeyHandler(I18n)
    );
  }
```

So is there any way how this config file https://github.com/isaachinman/next-i18next/blob/71bc3df4758bfee077ebe870bcae95ed9f5d5eeb/src/config/create-config.js can read from nextjs app?

**Comment by isaachinman** [comment]
Sorry, I do not understand this request. You should get pretty obvious filesystem errors if `next-i18next` isn't looking in the right directory.

What actual improvement would you like to see?

**Comment by radeno** [comment]
There is missing information `localePath` doesn't respect `dir` directive. That's all.
Static directory path is always different if you change `dir`. eg:
```js
const next = require('next');
const app = next({ dir: './src', dev: isDev });
```
Correct path for static directory is then ./src/static. So Locales directory should be looking within ./src/static/locales. but next-i18next finding in parent `./static/locales`

And this is the issue.

**Comment by isaachinman** [comment]
How would we look into the config you passed into `next`? What's wrong with simply providing the full relative path to your locales?
