### ISSUE TITLE
i18next-express-middleware should not be included to the client bundle

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#33]
I noticed that the size of my app's client bundle soared after switching to `next-i18next` from a custom `react-i18next` integration. As it turned out, the reason was that `i18next-express-middleware` ended up included into the bundle, which pulled quite a few other modules and made `_app.js` grow from 5KB gz to 123KB gz.

I tried wrapping `require()` in [create-i18next-client](https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L11) and [next-i18next-middleware](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js#L1) into eval locally, but that did not help.

It feels a bit strange that the export of `i18n.js` contains both a hoc and a middleware – that is hard to three-shake. Can the middleware thing be moved to another file and used in `server.js` only? I mean somehow like this:

```js
// server.js
const i18n = require("./i18n");
const nextI18NextMiddleware = require("next-i18next/express-middleware");
// ...

(async () => {
  await app.prepare();
  const server = express();
  nextI18NextMiddleware(i18n, app, server);

  // ...
})();
```
To achieve that, `i18n` can be an uninitialized instance of the original `i18n`, which gets initialized when it's used as an argument. Same for hoc?

```js
import i18nHoc from "next-i18next/app-hoc";
import i18n from "../i18n";

const MyApp = ...;

export default i18nHoc(i18n)(MyApp);

```

Overall, the idea of exporting a single default object in `i18n.js` and then importing its fields in `server.js` and `_app.js` has compatibility issues with TypeScript (see [example app](https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript), where `server.ts` uses `import` instead of `require`).

**UPD:** Wrapping `i18next-express-middleware` into eval actually helped. Bundle size was not decreasing in my first experiment because there was one more require in my custom middleware that I forgot to eval too.

**Comment by isaachinman** [comment]
This is an interesting point.

In general, I wrote the package to export a single class because most of these things need to share one i18next instance. The same is true of the [express middleware](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L14).

That being said, we could add another eval [here](https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L11), or perhaps just not export the middleware if `isNode` is false [here](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L14).

I'm fine with either approach.

Do you want to test those two ideas, and let me know what you think?

I'm hesitant to change the export structure, and have no idea how we'd even do that while still sharing that i18next instance.

**Comment by kachkaev** [comment]
Wrapping express middleware into `eval` and excluding `this.nextI18NextMiddleware` with an `if` seems to me like a half-way solution. There'll be still code with some server-side logic, which is not desired to expose on the client (see a listing in https://github.com/isaachinman/next-i18next/issues/16#issuecomment-444397728 for instance).

What if `i18n.js` just pre-configures `I18n` for both the client and the server? It will still expose, `withNamespaces`, `appWithTranslation` and `i18n`, but the initialization of `i18n` is somehow delayed? Then a middleware wrapper in `server.ts` will be able to inject additional server-only middlewares and not bloat the bundle size on the client. 🤔

**Comment by isaachinman** [comment]
This package will export an already-initialised i18n instance. That is non-negotiable and is a decision made from quite a lot of experience in this realm.

What "server-side logic" are you referring to that's being exposed to the client? The middleware [is being exposed](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L14), but that's a pretty easy fix. Is that all you're worried about?

**Comment by isaachinman** [comment]
@kachkaev When I run the example in prod mode, the `_app.js` is 4.7kb. Can you please provide a reproducible example? This issue is my top priority and I would appreciate your help. Thanks!

**Comment by isaachinman** [comment]
Update: it looks like adding `next-i18next` to a project will increase your `commons` chunk by just over 400kb (no gzip). That's not great, and as I said it's my top priority now.

**Comment by isaachinman** [comment]
@kachkaev Check out 78ad03e.

This approach reduces the [example](https://github.com/isaachinman/next-i18next/tree/master/example) client commons bundle from 595kb to 276kb.

The raw example commons bundle without `next-i18next` is 173kb, meaning our source here is adding about 100kb of un-gzipped JavaScript to people's projects. That is an acceptable size for me (for now), but obviously can be improved in the future.

I need to clean some export methodology up, and possible start using [lerna](https://github.com/lerna/lerna) to handle multiple packages.

**Comment by kachkaev** [comment]
Thanks for the update @isaachinman! I'll try out your changes this weekend (also hope to finally dig into https://github.com/isaachinman/next-i18next/issues/19 by producing a small shareable example).

**Comment by kachkaev** [comment]
Given that the new version of `next-i18next` is not released, I tried cloning the repo and use `yarn link` to use a local copy of your module. For some reason, I could not make it work because of `Error while running `getDataFromTree` TypeError: Cannot read property 't' of undefined`. It seems like `<Trans>` components are no longer fed with the correct `i18n` any more that this is what is causing the issue. See https://gitlab.com/kachkaev/website-frontend/merge_requests/6 for the changes I've made. The same exception is observed when I replace [`<h1>{this.props.t('h1')}</h1>`](https://github.com/isaachinman/next-i18next/blob/2aa87f3a29f3a933774087c99f24443600cbd626/example/components/Title.js#L7) with `<h1><Trans i18nKey="h1" /></h1>` in the example.

What could be causing this strange behaviour?

**Comment by jamuhl** [comment]
@kachkaev my guess: it's related to this: https://github.com/i18next/i18next/pull/1142#issuecomment-443432293 (but i'm not to deep into typescript) -> what happens is people `import * as i18n from 'i18next'` -> which gives: https://github.com/i18next/i18next/blob/master/src/index.js not a valid instance as that instance is the default export

the usage was never meant to  `import * as i18n from 'i18next'` but to have some `import { init } from 'i18next'` for people hating classes ;)

somehow i think best would be to remove those named exports to reduce that confusion

@kachkaev if you got time i would love your feedback on that PR too: https://github.com/i18next/i18next/pull/1142 (basically this still unclear to me so i can't merge and publish)

**Comment by isaachinman** [comment]
I have no idea about that error, but I don't think it's related to changes in `next-i18next`. We're not doing anything with the `Trans` component at all.

**Comment by kachkaev** [comment]
@jamuhl yeah you're probably right about `import *` stuff. Looking into the [diff](https://github.com/isaachinman/next-i18next/compare/v0.8.0...f3ba78bf610842858d057255aabd5c8b699333b1) between 0.8.0 and today's master, can it be `"add-module-exports"` line in `.babelrc` to blame?

As of https://github.com/i18next/i18next/pull/1142, I'm afraid I don't know TypeScript / import / exports enough to advise anything, sorry.

@isaachinman were you able to reproduce the issue with `Trans`? Interestingly, it only shows up on master, not in `0.8.0`. Once this problem is investigated, it'd be great to use this component in the example to make sure it works in future too.

**Comment by isaachinman** [comment]
@kachkaev Yes, I can reproduce that error with `Trans`. It occurs locally even if I do a `git checkout` as far back as `v0.7.0`. Weirdly, if I install `next-i18next` from the npm cdn instead of locally, the error goes away (as you said). 

If someone thinks this is a genuine problem with the `next-i18next` source, let me know. Otherwise let's leave it to `i18next`.

For the time being, you can test the work without using `Trans`.
