### ISSUE TITLE
Example on how to use customDetectors

### ISSUE THREAD

**Issue by cesarvarela** [isaachinman/next-i18next#333]
Specifically I want to set the language from a query string variable called `locale`

**Comment by isaachinman** [comment]
This information is readily available via i18next documentation and previous discussions in this repository.

**Comment by Fritiof** [comment]
> This information is readily available via i18next documentation and previous discussions in this repository.

Then perhaps should not state this option to be next-i18next specific, no? Creates confusion.

"This table contains options which are specific to next-i18next. All other i18next options can be passed in as well."

**Comment by isaachinman** [comment]
@Fritiof Not sure exactly what you mean. The `customDetectors` array just allows you to push detectors per environment. See [here](https://github.com/isaachinman/next-i18next/blob/88033719baf46dd7bc0ca02f0cc35b0e98bce8af/src/create-i18next-client.ts#L15). There's no proprietary logic otherwise.
