### ISSUE TITLE
Custom NextJS and localePath

### ISSUE THREAD

**Issue by fbarbare** [isaachinman/next-i18next#337]
## Describe the bug
I have a NextJS app and am now using next-i18next. My app's folder structure is like this:
```
root
|_ src
|   |_ client
|   |   |_ components
|   |   |_ pages
|   |   |   |_ ....
|   |   |_ static
|   |   |   |_ locales
|   |   |   |   |_ en
|   |   |   |   |_ fr
|   |   |   |   |_ ...
|   |   |_ routes.js
|   |_ server.js
|_ next.config.js
|_ package.json
```
When configuring next-i18next, I'm having problems with `localePath`:
- I would like to set it to `static/locales`, but the server throws an error saying it can't find the folder/file as it does not automatically go into `src/client`.
- If I set it to `src/client/static/locales`, the middleware does not actually work and does not return me the file, it returns a 404. I have to create a middleware of my own to return it. (+ Urls are of the sort `domain.com/src/client/static/locales/...` which is not ideal)

## Occurs in next-i18next version
0.40.1

## Steps to reproduce
-- I'll provide a repo if no obvious miss configuration is the answer to my problem :)

## Expected behaviour
`static/locales` should be looking in the NextJS static folder automatically.
If it can't be done automatically, maybe having a separate config path for server side would make sense?

## OS (please complete the following information)
 - Device: Any
 - Browser: Any

**Comment by isaachinman** [comment]
Please see https://github.com/isaachinman/next-i18next/issues/328#issuecomment-499008251.

Please search through issues before opening a new one.
