### ISSUE TITLE
i18n.changeLanguage does not change language

### ISSUE THREAD

**Issue by Satish-Lakhani** [isaachinman/next-i18next#338]
## Describe the bug
While changing language from client using i18n.changeLanguage() function initially it shows keys, after refreshing page it shows actual values for those keys.

## Occurs in next-i18next version
"next": "^6.1.2",
"next-i18next": "^0.40.1",

## Steps to reproduce
`
	import Head from 'next/head'
	import { i18n, withNamespaces } from '../../server/i18n'

	class Qz extends React.Component {
	    static async getInitialProps({req, asPath, query, res}) {
		return {
		    namespacesRequired: ['common']
		}
	    }

	    render() {
		console.log(i18n);
		const { t } = this.props;
		return (
		    <React.Fragment>
		        <p>{t('hello')}</p>
		        <p>{t('world')}</p>
		        <button
		            type='button'
		            onClick={() => i18n.changeLanguage(i18n.language === 'en' ? 'de' : 'en')}
		        > Change language </button>

		    </React.Fragment>
		)
	    }
	}

	export default withNamespaces('common')(Qz)

`

## Expected behaviour
It should change language without refresh.

## Screenshots
![Screencast20190611204252](https://user-images.githubusercontent.com/9801442/59284417-d8f73a80-8c89-11e9-9903-6c4b86b3393c.gif)

## OS
 Latest Chrome on ubuntu 18.04

## Additional context
 Also is there any way to detect language from query string and apply / use it?

Thanks
Satish

**Comment by isaachinman** [comment]
Please provide a reproducible repo. This behaviour is working in the `examples/simple` dir.

**Comment by Satish-Lakhani** [comment]
Sorry, This was due to my mistakes. I cached static files to 365 days, which was not getting the latest version of keys from the server.

Sorry and thanks for quick reply.

**Comment by Satish-Lakhani** [comment]
Is there any way to set language in getInitialProps() method?

**Comment by isaachinman** [comment]
You could use the `req.i18n` instance, but this is an unofficial/unsupported approach. Good luck.
