### ISSUE TITLE
lng prop no longer injected by withTranslation HoC

### ISSUE THREAD

**Issue by Averethel** [isaachinman/next-i18next#339]
## Describe the bug
After updating to v0.41.0 the `lng` prop does not seem to be injected anymore by `withTranslation` HoC. Was [the documentation](https://github.com/isaachinman/next-i18next#accessing-the-current-language) updated after migrating to react-i18next 10?

## Occurs in next-i18next version
`0.41.10`

## Steps to reproduce
```javascript
const CurrentLanguage = ({ lng }) => (<div>{lng}</div>)

export default withTranslation("app")(CurrentLanguage)
```

## Expected behaviour
`CurrentLanguage` component renders the current language

## OS 
 - Device: MBP 2018 15"
 - Browser: Chrome 74.0.3729.169 (64-bit)

**Comment by isaachinman** [comment]
You still get `props.i18n`. It's true that that documentation needs to be updated - I wasn't really a fan of that section in the first place.
