### ISSUE TITLE
Using ./ in local imports

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#34]
Me again 😅

I was a bit confused by seeing that local files are imported just like external npm modules throughout the code (e.g. `import createI18NextClient from 'create-i18next-client'` [in `index.js`](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L2)). Seeing this form of notation suggests that there exists an external npm module called `create-i18next-client`, which is not the case.

How about prefixing local files with`./` instead, e.g. `import createI18NextClient from './create-i18next-client'`? This is what I've been usually seeing in other code bases so far.

**Comment by isaachinman** [comment]
It's a babel preset and totally personal preference. Doesn't affect the end user at all. If it confuses other contributors we can reopen this.

**Comment by kachkaev** [comment]
It confused me, which made me open the issue. I've already wasted my five minutes, so am fine with having this issue closed until someone else finds the current style hard to interpret.

**Comment by isaachinman** [comment]
Because it's a matter of preference, we'll let a majority decide. If
another contributor adds their opinion, we'll readdress the issue.

**Comment by isaachinman** [comment]
Because it's a matter of preference, we'll let a majority decide. If another contributor adds their opinion, we'll readdress the issue.
