### ISSUE TITLE
saveMissing breaks language switch with namespaces

### ISSUE THREAD

**Issue by germansokolov13** [isaachinman/next-i18next#347]
## Describe the bug
Adding `saveMissing` option breaks language switching when also using namespaces

## Occurs in next-i18next version
Occurs on `master` branch, also occurs on `0.41.0`

## Steps to reproduce
Just add `saveMissing: true,` to your own example in `NextI18Next` config object. Open and click `Change locale` button.

## Expected behaviour
All text should be translated into German. However `description` key is left untranslated. This is because it's form a different, non-default namespace. There is also an error in console showing a failed atempt to save a not actually missing key.

## OS (please complete the following information)
 - Device: GNU/Linux on Desktop
 - Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
You'll need to play around with `react-i18next` configuration options. For example, try setting your own `missingKeyHandler` function. You'll see that the broken render is fixed - that's probably due to a failing POST to an endpoint which doesn't exist.

In general, the problem here is that the footer description key is being reported as "missing" when you change the language, because briefly while the GET request is pending to fetch the new German translations, the key _is_ missing.

Let me know if you'd like to discuss further, or if you need any more help.

**Comment by germansokolov13** [comment]
Why is it not considered to be a bug? I add a legitimate option and it doesn't work. It doesn't say it shouldn't work. `react-i18next` doesn't say I need to set my own `missingKeyHandler `.

**Comment by isaachinman** [comment]
`next-i18next` uses a subset of the `react-i18next` options. Anything which is not in the README is not officially supported.

If you would like to extend functionality to cover `saveMissing`, feel free to work on a PR.

**Comment by germansokolov13** [comment]
It says `All other i18next options can be passed in as well`. Maybe then add a warning that they may not work?

**Comment by isaachinman** [comment]
They can be passed in indeed. Let me clarify further: `next-i18next` is an opinionated NextJs implementation of `react-i18next`. It's also open source - feel free to get to work if you discover an area in which you would like to see improvement.

I explained the exact reason `saveMissing` is "failing" above, and there is nothing buggy about the behaviour at all. You'll simply need to take into account the fact that JSON files need to be fetched when the language is changed on the client. If you want to use the default behaviour, you'll also need to sent up POST endpoints, etc. I'm not sure what you'd like `next-i18next` to do for you.

`saveMissing` is not a prod or core feature and does not warrant a warning.
