### ISSUE TITLE
Link component not preprending subpath, whereas imperative routing works

### ISSUE THREAD

**Issue by ccambournac** [isaachinman/next-i18next#348]
## Describe the bug
I am unable to make Link component work with automatic locale subpath being prepended, whereas the same example works with imperative routing.

## Occurs in next-i18next version
0.42.0

## Steps to reproduce
Install and start repository below:
https://github.com/ccambournac/next-i18next-minimal-project

## Expected behaviour
Link component should behave as described in the documentation.

## OS (please complete the following information)
 - Device: Windows 7
 - Browser: All

**Comment by keustma** [comment]
I have the same issue but thought it was something I was doing wrong, so I checked out the "examples/simple" project. But the example also doesn't work as described in the docs.

Steps to reproduce, checkout and run: https://github.com/isaachinman/next-i18next/tree/master/examples/simple

**Comment by isaachinman** [comment]
As @keustma has said, I believe this is a regression due to the `lng` prop no longer being passed with `react-i18next` v10.

I'll provide an update shortly.

**Comment by isaachinman** [comment]
@jamuhl Interestingly, the removal of that prop isn't in the [migration docs](https://react.i18next.com/latest/migrating-v9-to-v10).

**Comment by jamuhl** [comment]
@isaachinman if there is something missing - a PR would be welcome...

**Comment by keustma** [comment]
@isaachinman I think I found the issue, will open a PR in few minutes.

**Comment by isaachinman** [comment]
@keustma Already done. Mind reviewing #349?

**Comment by keustma** [comment]
Just reviewed it, was exactly the fix I had in mind.

Thank you for the quick response and fix!

**Comment by ccambournac** [comment]
Thank you all for the quick replies and forthcoming fix :)

**Comment by isaachinman** [comment]
Released with v0.43.0.

**Comment by isaachinman** [comment]
@keustma If you've got time, can you open a docs PR for `react-i18next`? Might also be useful to set a getter on `props.lng` that throws an error, or at least a console warning, to notify users that they need to migrate that prop.

**Comment by ccambournac** [comment]
@isaachinman It is now working as expected with v0.43.0. Thank you!

**Comment by keustma** [comment]
> @keustma If you've got time, can you open a docs PR for `react-i18next`? Might also be useful to set a getter on `props.lng` that throws an error, or at least a console warning, to notify users that they need to migrate that prop.

Done: https://github.com/i18next/react-i18next-gitbook/pull/53

I will make a separate one for the getters.

**Comment by keustma** [comment]
PR for the getters; https://github.com/i18next/react-i18next/pull/872

**Comment by isaachinman** [comment]
@keustma That's great - thank you.
