### ISSUE TITLE
appwithTranslation is not supporting SSR

### ISSUE THREAD

**Issue by Sathya-Appscrip** [isaachinman/next-i18next#35]
![image](https://user-images.githubusercontent.com/32590544/49595148-65543800-f99d-11e8-9d43-5b27c946c627.png)

without appwithTranslation 
![image](https://user-images.githubusercontent.com/32590544/49595245-90d72280-f99d-11e8-871f-3f0c66f5e77c.png)

with appwithTranslation
![image](https://user-images.githubusercontent.com/32590544/49595276-9d5b7b00-f99d-11e8-9b87-79e515bf4370.png)

**Comment by isaachinman** [comment]
First, there's no need for exclamation marks in the issue title.

Second, please provide a reproducible example via CodeSandbox. I will then do my best to debug your problem.

**Comment by isaachinman** [comment]
Closing due to lack of response.
