### ISSUE TITLE
Compilation fails with TypeScript since version 0.40.1

### ISSUE THREAD

**Issue by pamls** [isaachinman/next-i18next#353]
## Bug
Compilation fails with ts-node
`error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/node_modules/next-i18next/middleware")' has no compatible call signatures.`

## Version
next-i18next 0.39.0 works
next-i18next 0.40.1 does not work

## OS
 - Device: Windows 10

## Additional context
My project configuration is inspired by https://gitlab.com/kachkaev/website-frontend.

Compilation error
```
\node_modules\ts-node\src\index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/server.ts(25,16): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/node_modules/next-i18next/middleware")' has no compatible call signatures.

    at createTSError (\node_modules\ts-node\src\index.ts:245:12)
    at reportTSError (\node_modules\ts-node\src\index.ts:249:19)
    at getOutput (\node_modules\ts-node\src\index.ts:362:34)
    at Object.compile (\node_modules\ts-node\src\index.ts:395:32)
    at Module.m._compile (\node_modules\ts-node\src\index.ts:473:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (\node_modules\ts-node\src\index.ts:476:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by isaachinman** [comment]
Have you tried v0.43.0?

@tpinne @Jonesus Any ideas?

**Comment by tpinne** [comment]
0.40.1 introduced the `middleware.d.ts` which normally should make things work better. @pamls could you please post your `server.ts` file?

**Comment by pamls** [comment]
> Have you tried v0.43.0?

Yes, same issue

> 0.40.1 introduced the `middleware.d.ts` which normally should make things work better. @pamls could you please post your `server.ts` file?

```
import {join} from 'path';
import {format, parse} from 'url';
import * as compression from 'compression';
import * as express from 'express';
import * as next from 'next';
import * as nextI18NextMiddleware from 'next-i18next/middleware';
import {env} from './config';
import {nextI18next} from './i18n';

const app: any = next({
    dir: __dirname,
    conf: env.NODE_ENV === 'production' ? {distDir: '../.next', poweredByHeader: false} : undefined,
    dev: env.NODE_ENV !== 'production'
});
const handle: any = app.getRequestHandler();
const rootStaticFiles: string[] = [
    '/browserconfig.xml',
    '/image/favicon/favicon.ico',
    '/manifest.json',
    '/robots.txt'
];
(async () => {
    await app.prepare();
    const server: any = express();
    server.use(nextI18NextMiddleware(nextI18next));
    server.use(compression());

    // handle any other requests
    server.get('*', (req, res) => {
        const {pathname, query} = parse(req.url, true);

        if (rootStaticFiles.indexOf(pathname) > -1) {
            return app.serveStatic(req, res, join(__dirname, 'static', pathname));
        }

        if (
            pathname.length > 1 &&
            pathname.slice(-1) === '/' &&
            pathname.indexOf('/_next/') !== 0
        ) {
            return res.redirect(
                format({
                    pathname: pathname.slice(0, -1),
                    query
                })
            );
        }

        return handle(req, res);
    });

    server.listen(env.PORT, (err) => {
        if (err) {
            throw err;
        }
        console.log(`> Ready on port ${env.PORT}`); // tslint:disable-line
    });
})();
```

**Comment by Jonesus** [comment]
I can't really figure out why it fails just by looking at that file, would you mind sharing a project where this issue exists in a repo or an archive for example so that it could be more easily reproduced?

**Comment by pamls** [comment]
> I can't really figure out why it fails just by looking at that file, @pamls would you mind sharing a project where this issue exists in a repo or an archive for example so that it could be more easily reproduced?

@Jonesus yes, you can clone this repo https://gitlab.com/kachkaev/website-frontend, run `npm update` and `npm run build`

**Comment by Jonesus** [comment]
Hey @pamls , does the issue happen for you when you when you run the commands on a fresh clone still? Everything works out of the box for me 🤔 
> clone this repo https://gitlab.com/kachkaev/website-frontend, run `npm install` and `npm run build`

**Comment by tintounn** [comment]
I had the same issue, i just changed 

`import * as nextI18NextMiddleware from 'next-i18next/middleware';`

to

`import nextI18NextMiddleware from 'next-i18next/middleware';`

**Comment by pamls** [comment]
Thank you @tintounn it solves this compilation error but there are other errors, I have to review my code to support version 10 of react-i18next
