### ISSUE TITLE
Add query object to Router exposed by i18n

### ISSUE THREAD

**Issue by jonathangiamp** [isaachinman/next-i18next#357]
## Is your feature request related to a problem? Please describe.
When we use custom routing, we have to use **Link** and **Router** from i18n instance instead of using next version.
Unfortunately, some methods/properties are missing like *asPath*, *pathname*, *events* or *query*.

## Describe the solution you'd like
Today these method are retrievable from i18n **Router**
> reload, back, beforePopState, ready, prefetch, push, replace

I would like to be able to access to all methods/properties from [next/router](https://github.com/zeit/next.js/#intercepting-popstate) to only use **Router** from next-i18next and don't deal with translation issue. 

## Additional context
For the moment I mixed Router from next-i18next and next/router. Method called with next/router create some translation issues. Sometimes, translation values aren't loaded so only keys are displayed.

**Comment by jonathangiamp** [comment]
Updated 👆

**Comment by isaachinman** [comment]
@jonathangiamp Those methods are there, as getters. Did you try `Router.query`? If you did, you'll see it's exactly what you expect it to be.

For more info, see [here](https://github.com/isaachinman/next-i18next/blob/master/src/router/wrap-router.js).

**Comment by jonathangiamp** [comment]
@isaachinman Thanks for your response, I didn't saw the getter.
I removed `next/router` from my code to use i18n Router. Now, I'm encountering new error.

```
<rejected> Error: No router instance found.
     You should only use "next/router" inside the client side of your app.
     
         at getRouter (/Users/jonathan/workspace/novatopo-website/node_modules/next/dist/client/router.js:97:11)
         at Object.get (/Users/jonathan/workspace/novatopo-website/node_modules/next/dist/client/router.js:62:20)
```

I didn't have any error with `next/router` so I think that I don't call Router instance server-side. Do you have an idea to help me?

**Comment by isaachinman** [comment]
That's a general NextJs problem - feel free to post on StackOverflow.
