### ISSUE TITLE
Typescript translated component

### ISSUE THREAD

**Issue by floflock** [isaachinman/next-i18next#360]
## Describe the bug
In #220 was a discussion about typescript and `appWithTranslation` method coming from the package. I have a similar image on method `withTranslation`, see screenshot below:

![image](https://user-images.githubusercontent.com/3831745/59964051-ac4de900-94fb-11e9-9523-dab522af5db8.png)

## Occurs in next-i18next version
`"next-i18next": "^0.44.0"`

## Steps to reproduce
This is my page component which throws the typescript issue
```typescript
import TopMenuBar from '../components/navigation/topMenuBar2'
import React, { Component } from 'react'
import scss from '../styles/index.scss'
import { withTranslation } from '../lib/i18n'

class IndexPage extends Component {

  static async getInitialProps() {
    return {
      namespacesRequired: ['common'],
    }
  }

  render() {
    return (
      <React.Fragment>
        <TopMenuBar title={'Index Page'} />
        <div className={[scss.hero, scss.hero2].join(' ')}>
          <h1 className={scss.title}>Welcome to create-next-app-cli (Create Next.js App building tools)</h1>
          <p className={scss.description}>To get started, edit <code>pages/index.js</code> and save to reload.
          </p>
          <div className={scss.row}>
            <a href="https://nextjs.org/docs/" className={scss.card}>
              <h3>Getting Stasdsdrted &rarr;</h3>
              <p>Learn more about Next.js on official website</p>
            </a>
            <a href="https://github.com/themodernjavascript/create-next-app-cli" className={scss.card}>
              <h3>Create Next App CLI &rarr;</h3>
              <p>Was this tools helpful?</p>
            </a>
          </div>
        </div>
      </React.Fragment>
    )
  }

}

export default withTranslation('common')(IndexPage)
```

## Expected behaviour
Class component should be vaild for the export with `withTranslation`

Anyone Ideas?

**Comment by ReinoutStevens** [comment]
```
import { WithTranslation } from 'react-i18next';
class IndexPage extends Component<WithTranslation> {
}
```

You need to tell your component expects the props that `withTranslation` injects, if not there is no way your component knows that those props are available.

**Comment by floflock** [comment]
@ReinoutStevens thanks, I extend the props with WithTranslation, see below:

```javascript
interface PageProps extends WithTranslation {}
class LoginPage extends Component<PageProps> {}
```

In the meanwhile, I wrote a PR to re-export `WithTranslation` to have a single point of import. See here: https://github.com/isaachinman/next-i18next/pull/361

With this PR, which is in Version 0.45, importing `WithTranslation` gets more comfortable.

**Comment by isaachinman** [comment]
@floflock Can this issue be closed, then? Or do we need to address something else?

**Comment by EricVanDerDijs** [comment]
Hi, I have just started using your latest versión and this issue seems to ave been reopened, it seems that the "WithTranslation" interface is being exported with the value of the withTranslation type. Currently it is imposible to use the HOC with class components using typescript.

The workaround I found was to Import the "WithTranslation" interface directly from the "react-i18next" directly.

**Comment by Averethel** [comment]
@isaachinman This has been broken since v0.50. Any chance for a fix?

**Comment by isaachinman** [comment]
@Averethel Apologies if that's the case. I've just released v1.0.0 as it happens. Would be very grateful for a fix, and also test coverage to prevent regressions.

**Comment by Averethel** [comment]
@isaachinman I'll try to prepare a fix early next week

**Comment by isaachinman** [comment]
Thanks. Important to say that we probably shouldn't merge bug fixes without accompanying test coverage.

**Comment by Averethel** [comment]
Will keep that in mind. I should be able to provide a failing test.
In the meantime could you reopen the issue?

**Comment by trainto** [comment]
I'm struggling with a similar issue.

I've got a functional component like below:

```
interface IProps {
  onHamburgerMenuClicked: () => void;
}

const NavTop = (props: IProps) => {
  ...
  ...

  return (
    <div>.....</div>
  );
};

export default React.memo(withTranslation('common')(NavTop));
```

And typescript is complaining like below:
```
const NavTop: (props: IProps) => JSX.Element
Argument of type '(props: IProps) => Element' is not assignable to parameter of type 'ComponentType<WithTranslation>'.
  Type '(props: IProps) => Element' is not assignable to type 'FunctionComponent<WithTranslation>'.
    Types of parameters 'props' and 'props' are incompatible.
      Property 'onHamburgerMenuClicked' is missing in type 'PropsWithChildren<WithTranslation>' but required in type 'IProps'.ts(2345)
```

So I tried my IProps inteface like
```
interface IProps extends WithTranslation {
  onHamburgerMenuClicked: () => void;
}

const NavTop: React.FunctionComponent<IProps> = (props: IProps) => {
  ...
  ...
};
```

and now it's complaining like..
````
const NavTop: React.FunctionComponent<IProps>
Argument of type 'FunctionComponent<IProps>' is not assignable to parameter of type 'ComponentType<WithTranslation>'.
  Type 'FunctionComponent<IProps>' is not assignable to type 'FunctionComponent<WithTranslation>'.
    Types of property 'propTypes' are incompatible.
      Type 'WeakValidationMap<IProps> | undefined' is not assignable to type 'WeakValidationMap<WithTranslation> | undefined'.
        Type 'WeakValidationMap<IProps>' has no properties in common with type 'WeakValidationMap<WithTranslation>'.ts(2345)
````

I don't know how to solve this.

Any help?
