### ISSUE TITLE
Can't make it work with Next + Typescript + Redux

### ISSUE THREAD

**Issue by githubdoramon** [isaachinman/next-i18next#365]
## Describe the bug
Can get the lib to work. I followed the basic example, copied the files to my project, but when I ran, I always get the error "react-i18next:: i18n.languages were undefined or empty undefined".

I have no idea if it is indeed related to redux or typescript. 

## Occurs in next-i18next version
0.44.0

## Steps to reproduce
I created the next app, added typescript and redux, and then tried to add next-i18next.

## Expected behaviour
Translations should appear / work

Any ideas where am I doing something wrong?

Regards

**Comment by isaachinman** [comment]
Cannot help in any way unless you provide a reproducible example.

**Comment by githubdoramon** [comment]
Sorry @isaachinman , here it goes: https://github.com/githubdoramon/next-18next-issue

Just clone, yarn install, yarn dev - You will see on the index page a "common.translation" instead of the translation... and on the console the error I mentioned

**Comment by isaachinman** [comment]
Your namespaces are set up incorrectly. You don't need a nested `common` object inside your `common` namespace. I removed this and it appears to work fine.

**Comment by isaachinman** [comment]
Also, your `server.js` file isn't even being run. I suggest you post on StackOverflow for more general help.

**Comment by githubdoramon** [comment]
Forgot to properly configure the server part before sending you.... sorry.

So,  I am starting to understand the namespace issue... 2 questions: 

- What happens if one component / page depends on more than one namespace, I just don't add any to the withTranslation?
- If the namespace prefix is not needed, in the above case, translation jsons can never have the same key right?

Regards and thx for the help

**Comment by isaachinman** [comment]
These are general i18next questions and can be found via the docs or StackOverflow. Good luck!

**Comment by githubdoramon** [comment]
Ah... Makes sense... Thx
