### ISSUE TITLE
Error localeSubpaths config

### ISSUE THREAD

**Issue by edersign** [isaachinman/next-i18next#366]
I updated version 0.41.0 to 0.44.0 and is present a URL error when the `localeSubpaths` configuration is different from the default. It is doubling the language.

`http://localhost:3000/en/enproducts`

**Comment by isaachinman** [comment]
Cannot reproduce. Please provide a reproducible example.

![Screenshot 2019-06-28 at 09 16 36](https://user-images.githubusercontent.com/10575782/60328116-7ab6a100-9985-11e9-9c01-023281e710ff.png)

**Comment by edersign** [comment]
Hi, 
I made a gif with the error to exemplify. Im use a `localeSubpaths: 'all'` config.
![Image of Yaktocat](https://multiportal-site.herokuapp.com/static/images/next-example.gif)

**Comment by isaachinman** [comment]
Well, it looks like you're navigating to `/enprodutos`, not `/en/produtos`.

You will need to provide a reproducible example if you would like help.

**Comment by edersign** [comment]
Hi, 

I did a new installation of the example and update the dependencies and it works fine. I'm going to work to find out what's going on. 

thank you.
