### ISSUE TITLE
[Question] How to deal with dynamic languages?

### ISSUE THREAD

**Issue by Fabiantjoeaon** [isaachinman/next-i18next#367]
Hi there,

I'm currently working on an isomorphic React application that is used for multiple websites, each with a different default language and available set of languages.

It's crucial to have the language defined on the server, however, when trying this, I run into some problems..

The languages that are available have to be fetched from a CMS (this is done in a custom `server.js`), how would I initialize `NextI18Next` (perhaps in a seperate file) with this data so that both the server and client can use it? Is this possible? Perhaps using a different approach?

Example:

```
module.exports = new NextI18Next({
  otherLanguages: supportedLanguages, // async value
  fallbackLng: defaultLang, // async value
});
```

If my question is not clear enough, please let me know.

Thanks in advance!

**Comment by isaachinman** [comment]
The question is not clear enough. What does `async` mean in this context? You need to pass in languages at the time of class construction.

**Comment by Fabiantjoeaon** [comment]
In `server.js`, the supportedLanguages value is fetched from a CMS (a Wordpress instance in this case), which returns `['en', 'nl']` for example. So I don't really see a method of constructing the `NextI18Next` class instance in a seperate file. 

I tried instancing `NextI18Next` in `server.js` where I have access to these values, but then it wouldn't be possible to import this instance inside my React client. I tried this, but then I receive this strange error: `npm run build error: Module not found: Error: Can't resolve 'aws-sdk'`. It also doesn't feel very logical.

So for short; my `NextI18Next` class instance is dependent of data from a external source that is fetched in `server.js`

**Comment by isaachinman** [comment]
Sounds like a general JavaScript question, and very implementation-specific.

Use a global config object and do the setup before class construction, or simply don't have a separate file at all.

Please post on StackOverflow for further questions.
