### ISSUE TITLE
Translation files read from disk on every request

### ISSUE THREAD

**Issue by bywo** [isaachinman/next-i18next#369]
## Describe the bug
On subsequent requests to the same next.js page with the same locale, i18next reads all translations files for all locales from disk and [copies them (via object spread) to the i18next ResourceStore](https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L93).

As far as I can tell, this happens because [useSSR replaces the shared ResourceStore's `data` when `initialI18nStore` is passed](https://github.com/i18next/react-i18next/blob/master/src/useSSR.js#L11). Doing so makes sense on the client-side, where we assume the translation bundles have been serialized somehow in the HTML and we want to initialize the client's i18next with those bundles. However, doing this on the server means that any bundles that were loaded on previous requests get thrown away on the next request, so the next request will trigger resource bundle loads again.

Deploying to production showed memory usage growing rapidly, causing lots of GCs, and a CPU pegged at 100%. Stat'ing and reading files from disk for every request didn't help either.

## Occurs in next-i18next version
Latest (0.43.0)

## Steps to reproduce
* Connect Chrome debugger to your server
  * Launch your next.js server that uses `next-18next`, but add `--inspect`, e.g. `node --inspect myServer.js`
  * Go to `chrome://inspect` in Chrome and you should see a process to connect to
* In the "Search" pane of the debugger, search for `addResourceBundle`. A method from the `i18next` npm package should show up. Add a breakpoint at the top of the method.
* Load a page from your next.js service in the browser
* Observe that `addResourceBundle` is hit on every request, and the async stack trace shows `fs.readFile`

Here's what it looks like for me
![Screen Shot 2019-07-01 at 4 12 40 PM](https://user-images.githubusercontent.com/1434481/60471880-64297780-9c1b-11e9-85c7-44cc16984c7d.png)

## Expected behaviour
The first request to the server process should trigger resource bundle loads. Those bundles should then be cached by i18next's ResourceStore. Any subsequent requests should use the cache and shouldn't trigger any file system reads. `addResourceBundle` shouldn't be called again for any bundles that were already added.

## OS (please complete the following information)
 - Device: Mac
 - Browser: Chrome

**Comment by isaachinman** [comment]
Nice find! I wonder what @jamuhl thinks about this. We're specifically using `withSSR` from `react-i18next`. Although there are many ways we could work around this, I imagine it'd be a problem for every consumer of `withSSR`.

**Comment by jamuhl** [comment]
Guess we just should not run that code on serverside: https://github.com/i18next/react-i18next/blob/master/src/useSSR.js#L10-L18 

Either we could check for i18n.options.isClone (middleware creates a i18n clone per request) or use https://github.com/MatthewNPM/is-node to detect node.js

What do you think?

**Comment by isaachinman** [comment]
`i18n.options.isClone` makes good sense to me. Clones shouldn't handle their own `fs` work, right?

**Comment by jamuhl** [comment]
clones share the resourceStore with its source they were cloned from...will make a new version later today adding that opt out

**Comment by isaachinman** [comment]
Great, can you ping me here when that's out? Will upgrade `next-i18next` and then see if @bywo can do a bit of testing.

**Comment by jamuhl** [comment]
should be solved in react-i18next@10.11.3

**Comment by isaachinman** [comment]
@bywo Do you mind testing #372 and see if the issue is resolved?

**Comment by bywo** [comment]
fix looks good! thanks for the quick turnaround 😃
