### ISSUE TITLE
Replace `eval()` as it is slower and not recommended

### ISSUE THREAD

**Issue by jaqua** [isaachinman/next-i18next#37]
Don't use `eval()` as it is not needed in this context:

- https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js#L10
- https://github.com/isaachinman/next-i18next/blob/f3ba78bf610842858d057255aabd5c8b699333b1/src/config/create-config.js#L15

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/eval#Don't_use_eval_needlessly!

**Comment by isaachinman** [comment]
> not needed in this context

Do you understand the purpose of `eval` here? Do you have another proposal, or any desire to contribute?

**Comment by isaachinman** [comment]
Happy to reopen if something constructive is actually offered.

**Comment by aequasi** [comment]
Out of curiosity, what exactly is the purpose of them here?

**Comment by isaachinman** [comment]
@aequasi To require dependencies at runtime in server contexts, so that they are not included in client side bundles. It's a bit dirty, but works. Open to all suggestions.

**Comment by aequasi** [comment]
i think `process.browser` can be used to not bundle things in client side:

```javascript
if (!process.browser) {
    const something = require('foo');
}
```

But i'm not 100% sure. Maybe @timneutkens can verify?

**Comment by isaachinman** [comment]
Might be able to use [dynamic imports](https://nextjs.org/docs/#dynamic-import), but please remember that this package is not a NextJs project in itself - we have our own build pipeline.

**Comment by aequasi** [comment]
I almost suggested that too.

It's only used *in* nextjs projects though. When it goes through the users build process, it should get stripped

**Comment by isaachinman** [comment]
@aequasi To be honest, I'm not actually sure whether or not it'd work. While `node_modules` definitely are not transpiled (this will change soon), we'd still be importing the function from the NextJs core.

Worth a try, I suppose. Feel like starting a PR?

**Comment by isaachinman** [comment]
PRs welcome. The size of the client bundle must remain unchanged. We _should_ have this covered with `bundlesize`.

**Comment by VityaSchel** [comment]
> Hi there, just chiming in here. In my project, we use a package that uses next.js to create some microfrontend endpoints. Because it is a separate next.js instance from our main project, the eval statements result in a fatal error:
> 
> ```
> ReferenceError: require is not defined
>     at eval (eval at _default (/Users/diegohernandez/project/node_modules/next-i18next/dist/commonjs/config/create-config.js:44:14), <anonymous>:1:1)
>     at eval (<anonymous>)
>     at _default (/Users/diegohernandez/project/node_modules/next-i18next/dist/commonjs/config/create-config.js:43:14)
>     at new NextI18Next (/Users/diegohernandez/project/node_modules/next-i18next/dist/commonjs/index.js:52:46)
> ```
> 
> Replacing the `eval` statements with just the `require` statements seems to fix this problem. Not sure why this works, but it would be ideal if the `eval` statements are replaced.

Mind sharing how you use next-i18next with microfrontends? I can't get this to work
