### ISSUE TITLE
Dubt about dynamic import

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#371]
I have a dubt about how to load dynamicly a dictionary (not in SSR).

In my case I have the `common.json` for the page, and  a modal is loaded dynamicly with all the `privacy.json`. However, I don't want to bring all privacy texts on the page, I want to load dynamicly with the modal.

Is that possible?

Thank you so much

**Comment by aralroca** [comment]
Ok. I solved using

```js
export default withTranslation('myDynamicDictionary')(MyDynamicComponent)
```

and controlling the prop `tReady` inside `MyDynamicComponent`  with `if(!tReady) return null`

**Comment by isaachinman** [comment]
Sure, if you need to add a loading state you can hook into `tReady`.

In general, if you wrap a component with `withTranslation('myDynamicNamespace')`, but don't add that namespace to the page-level `namespacesRequired`, it will be loaded dynamically when the component is mounted.

**Comment by aralroca** [comment]
@isaachinman this is working fine in dev, however in production is like is not downloading dynamically the namespace... :(

**Comment by isaachinman** [comment]
@aralroca I've just tested this behaviour in the simple example and can confirm it works identically in dev and prod. Please provide a reproducible example if you believe you've found a bug.

**Comment by aralroca** [comment]
I see that the problem is that in production I'm using a different `assetPrefix` in my next.js configuration and the dynamic download is trying to load from `/static/...`, getting a 404.

![image](https://user-images.githubusercontent.com/13313058/60504569-20d61400-9cc2-11e9-8993-47721abb17f5.png)

this is my NextI18Next instance:

```js
const i18n = new NextI18Next({
  customDetectors: [langFromDomain],
  defaultLanguage: DEFAULT_LOCALE,
  localeSubpaths: 'all',
  otherLanguages: LOCALES,
  pluralSeparator: '_',
  simplifyPluralSuffix: true,
  loadPath: `${BASE_URL_STATICS}/static/locales/{{lng}}/{{ns}}.json`,
  detection: {
    order: ['querystring', 'cookie', 'from-domain', 'navigator'],
  },
})
```

Where the BASE_URL_STATICS is a ENV variable used in production.

**Comment by isaachinman** [comment]
Okay, would you like to close this issue, then?
