### ISSUE TITLE
next-i18next doesn't export types of i18next

### ISSUE THREAD

**Issue by Janealter** [isaachinman/next-i18next#375]
## Describe the bug
`next-i18next` doesn't export types of `i18next`

## Occurs in next-i18next version
v0.44.0

## Steps to reproduce
1. Install package
2. Try to import any type of `i18next` (TFunction for example)

## Expected behaviour
`next-i18next` exports namespace `i18next` with all types

## OS (please complete the following information)
 - Device: no matter
 - Browser: no matter

**Comment by isaachinman** [comment]
Feel free to open a PR.

**Comment by masone** [comment]
https://github.com/isaachinman/next-i18next/pull/387
