### ISSUE TITLE
The language didn't change when using the backend

### ISSUE THREAD

**Issue by chenbin2015** [isaachinman/next-i18next#376]
## Describe the bug
I download the simple demo,then copy  en to zh in the /static/locales, config the zh ,it works well,but when i modify the config by backend, it failed,just two languages works

## Occurs in next-i18next version
 "i18next": "^14.0.1",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-fetch-backend": "^2.2.0",
    "i18next-xhr-backend": "^3.0.0",
    "js-cookie": "^2.2.0",
    "less": "^3.9.0",
    "net": "^1.0.2",
    "next": "^7.0.2",
    "next-i18next": "0.45.0",

## Steps to reproduce
`const XHR = require('i18next-xhr-backend')
const NextI18Next = require('next-i18next/dist/commonjs')

module.exports = new NextI18Next({
  init: [XHR],
  debug: true,
  defaultLanguage: 'zh',
  otherLanguages: ['de', 'en'],
  preload: ['en'],
  backend: {
    loadPath: 'http://domain/{{lng}}-{{ns}}.json',
    parse: JSON.parse,
  },
})`

`<button type="button" onClick={() => i18n.changeLanguage('en')}>
          en
        </button>
        <button type="button" onClick={() => i18n.changeLanguage('de')}>
          de
        </button>
        <button type="button" onClick={() => i18n.changeLanguage('zh')}>
          zh
        </button>`

## Expected behaviour
all language will work

## Screenshots
click zh
![image](https://user-images.githubusercontent.com/11733622/60679999-4c245300-9ebc-11e9-82c6-8f4219aac5c4.png)
click de
![image](https://user-images.githubusercontent.com/11733622/60680006-59414200-9ebc-11e9-80cf-26e957d45c20.png)
click en
![image](https://user-images.githubusercontent.com/11733622/60680022-62321380-9ebc-11e9-95f1-c14b2b2e3709.png)

The screenshots shows the en didn't work,but sometimes the en didn't work, sometimes  the de didn't work, sometimes the zh didn't work

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Why are you setting `preload`? This could also be an issue with your XHR implementation. You'll need to provide a reproducible example for me to be able to help.

**Comment by chenbin2015** [comment]
> Why are you setting `preload`? This could also be an issue with your XHR implementation. You'll need to provide a reproducible example for me to be able to help.

Thanks a lot for your feedback,I have upload the project to github:https://github.com/chenbin2015/next-i18next-demo,the remote server url is change so ui will not change, but you can see the xhr in the develop tool，just two languages invoke the xhr

**Comment by chenbin2015** [comment]
I add this code,it looks like it's solved
`componentDidMount() {
    i18n.reloadResources()
  }`

**Comment by isaachinman** [comment]
Sorry, I cannot do much with that example because it doesn't reproduce anything... I still don't understand the problem.

**Comment by chenbin2015** [comment]
> reproduce



> Sorry, I cannot do much with that example because it doesn't reproduce anything... I still don't understand the problem.

Mr. isaachinman, I have sent a email to you ,please check it, thanks~

**Comment by isaachinman** [comment]
Hi @chenbin2015 - unfortunately this is OSS and is maintained in our free time. We'll need to reproduce and solve the problem publicly so that other users can benefit from the work.
