### ISSUE TITLE
How to test Next.js translated pages? 

### ISSUE THREAD

**Issue by borisowsky** [isaachinman/next-i18next#377]
This is my page (common.greeting === 'Hello world!').
```ts
import React from 'react';

import { useTranslation } from '../utils/i18n';

const Index = () => {
  const [t] = useTranslation('common');

  return <div>{t('greeting')}</div>;
};

Index.getInitialProps = () => ({
  namespacesRequired: ['common'],
});

export default Index;
```
How to test this page with @testing-library/react?
How to mock language or something like that?

**Comment by isaachinman** [comment]
Please refer to the [react-i18next docs here](https://react.i18next.com/misc/testing).

**Comment by borisowsky** [comment]
I was trying to follow this docs, but stack on next issue: translation file loaded after component was mounted, so I get error on test and later - "Attempted to log "i18next::backendConnector: loaded namespace common for language en { greeting: 'Hello world!' }". Is there is any way to make locales loading sync?

**Comment by isaachinman** [comment]
Please post on StackOverflow or a support forum.

**Comment by mehmetnyarar** [comment]
test/setup.ts:

```ts
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Mock t function
export const t = (key: string, params?: any) => {
  if (key === 'key.with.params') {
    return `key.with.params.${params.param}`
  }

  return key
}


// Mock react-i18next
i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  resources: {
    en: {
      common: {}
    }
  }
})

// Mock your i18n
jest.mock('~/i18n', () => {
  return {
    useTranslation: () => {
      return {
        t,
        i18n: {
          language: 'en',
          onChangeLanguage: jest.fn()
        }
      }
    },
    withTranslation: () => (Component: any) => {
      Component.defaultProps = { ...Component.defaultProps, t }
      return Component
    }
  }
})
```

I don't test my `_app.tsx` since it's only a wrapper with context providers but it's worth to mention that TS typings aren't clear regarding `appWithTranslation`:

```ts
export type AppWithTranslation = <P extends object>(Component: React.ComponentType<P> | React.ElementType<P>) => any
```

- [article](https://react.i18next.com/misc/testing)
- [example](https://github.com/i18next/react-i18next/tree/master/example/test-jest)
