### ISSUE TITLE
I18next for Next 5

### ISSUE THREAD

**Issue by Vadorequest** [isaachinman/next-i18next#378]
This plugin seems to be designed for Next 8, I'm running next 5.
Next 5 is completely outdated and asking for support would be silly, to say the least.

But I wonder if there are any recommandations or "ways to go" in order to use i18next within Next 5. I'm kinda starting there: https://react.i18next.com/guides/quick-start but would be great to have some guidance regarding the important setup steps! :)

**Comment by isaachinman** [comment]
Please post on StackOverflow or forums.
