### ISSUE TITLE
Source of truth of the language selection

### ISSUE THREAD

**Issue by igorbuts** [isaachinman/next-i18next#38]
What is the source of truth of the language selection? 

In my application, I don't want to have locale subpaths. I see that the current language is stored in `cookies` - it this a source of truth?

And I don't see any  API method in docs how to change the current language programmatically (e.g when a user clicks lang switcher).

Could you please suggest how to implement what I need in the right way?

**Comment by igorbuts** [comment]
Sorry, I can't add a `help wanted` label.

**Comment by isaachinman** [comment]
Hi @igorbuts, that exact functionality is [in the example](https://github.com/isaachinman/next-i18next/blob/master/example/pages/index.js#L13).

It has nothing to do with `next-i18next`. This package returns you a running `i18n` instance (among other things), and using it is up to you.
