### ISSUE TITLE
defaultNS throws error when static locales doesn't exist

### ISSUE THREAD

**Issue by keethu24** [isaachinman/next-i18next#381]
## Describe the bug
I don't have static locale file. I want to load the locales using xhr at run-time. But in the latest `v0.45.0`, defaultNS is mandatory and it throws an exception when set.
```
Default namespace not found at C:\work\github\keethu\credit-frontend\packages\apps\private-credit\static\locales\de\common.json
```

## Occurs in next-i18next version
v0.45.0

## Steps to reproduce
i18n configuration:
```
const nextI18n = new NextI18Next({
  // plugin config: https://github.com/isaachinman/next-i18next#options
  defaultLanguage: 'de',
  otherLanguages: ['de', 'fr', 'it'],
  defaultNS: 'common',                 // <--- should be set in v0.45.0

  // official i18next config: https://www.i18next.com/overview/configuration-options
  react: {
    wait: true
  },
  ns: 'common',
  // Add resources manually until the translation service is available
  resources: {
    fr: {
      common: {
        greeting: 'Bonjour le monde'
      }
    },
    de: {
      common: {
        greeting: 'hallo welt'
      }
    }
  }
});
```

## Expected behaviour
I want to start the application without static locales. How can I achieve that?

## OS (please complete the following information)
 - Device: Windows 10
 - Browser: 75.0.3770.100

**Comment by isaachinman** [comment]
You can set `defaultNS` to an empty array.

**Comment by keethu24** [comment]
@isaachinman Yes, that solves the problem. Thank you.

**Comment by keethu24** [comment]
@isaachinman With the upgrade to v0.53.1, there is a type error when I use empty array as you suggested.
```
13:3 Type 'never[]' is not assignable to type 'string'

 11 |     wait: true
 12 |   },
> 13 |   defaultNS: [],
        |   ^
 14 |   ns: 'common',
```

**Comment by isaachinman** [comment]
@keethu24 Can you provide a full block of code to reproduce? Weirdly I'm actually seeing `config` come through as `any`:

![Screen Shot 2019-08-08 at 11 35 08](https://user-images.githubusercontent.com/10575782/62696595-a8552800-b9d0-11e9-9793-eca8a7f674b9.png)

**Comment by keethu24** [comment]
The config file is written in js. Here is the full config:

```
// @ts-check
const NextI18Next = require('next-i18next').default;

const nextI18n = new NextI18Next({
  // plugin config: https://github.com/isaachinman/next-i18next#options
  defaultLanguage: 'de',
  otherLanguages: ['de', 'fr', 'it'],

  // official i18next config: https://www.i18next.com/overview/configuration-options
  react: {
    wait: true
  },
  defaultNS: [],
  ns: 'common',
  detection: {
    lookupFromPathIndex: 0,
    load: 'languageOnly',
    order: ['path', 'navigator', 'cookie', 'header']
  },
  backend: {
   // ... backend config
  }
});

module.exports = nextI18n;

exports.i18n = nextI18n.i18n;
```

**Comment by isaachinman** [comment]
@keethu24 Ah, that's coming directly from i18next typings. Looks like they're not expecting an empty array. Probably better to set `defaultNS` to `null` in those cases.

**Comment by keethu24** [comment]
`null` was also not accepted. but `undefined` did the trick.
Thank you for help.

**Comment by keethu24** [comment]
When defaultNS is undefined, it tries to load undefined namespace using backend plugin. Furthermore, default value of defaultNS is translation. Then it also tries to load translation.
![image](https://user-images.githubusercontent.com/47893296/62883699-fbaed980-bd34-11e9-9deb-eaf6c9aff198.png)

When I give a namespace, then next-i18next library tries to load from file system and throws error. This is not good. You should completely disable loading static locales when using backend option or provide other mechanism.

**Comment by isaachinman** [comment]
Why is an empty array not a suitable solution in your case, @keethu24?

**Comment by MichaelBrog** [comment]
Any updates on how to handle this? I am running into the same issue.

**Comment by keethu24** [comment]
@MichaelBrog We couldn't solve this problem with this library, because it is not flexible enough to configure it. So we modified the code for our need by removing the `i18next-node-fs-backend` code, which is responsible for loading the static files from file system -->
https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.ts#L10

**Comment by isaachinman** [comment]
This is OSS and depends on contribution from the community. PRs are very much welcome.

**Comment by hrahimi270** [comment]
Hi. I have the same problem but in another way. I have static locale files. And I put them in `public/locales`. But I have the same error that says: **Error: Default namespace not found at /public/locales/en/common.json**.

This is my i18next config:
```js
// lib/i18next/index.js

const NextI18Next = require("next-i18next").default;
const path = require('path')

module.exports = new NextI18Next({
	defaultLanguage: "fa",
	otherLanguages: ["en"],
	localeSubpaths: {
		en: "en",
	},
	localePath: path.join(__dirname, '../../', 'public/locales'),
});
```

This is my Next config:
```js
const webpack = require("webpack");
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const localeSubpaths = {
	en: "en"
}

module.exports = {
	rewrites: async () => nextI18NextRewrites(localeSubpaths),
	webpack: (config, { isServer }) => {
		const env = Object.keys(process.env).reduce((acc, curr) => {
			acc[`process.env.${curr}`] = JSON.stringify(process.env[curr]);
			return acc;
		}, {});

		// Fixes npm packages that depend on some modules
		if (!isServer) {
			config.node = {
				fs: "empty",
				child_process: "empty",
			};
		}

		config.plugins.push(new webpack.DefinePlugin(env));
		return config;
	},
};
```

Everything looks OK, but I have that error.

**Comment by Markus357** [comment]
> @MichaelBrog We couldn't solve this problem with this library, because it is not flexible enough to configure it. So we modified the code for our need by removing the `i18next-node-fs-backend` code, which is responsible for loading the static files from file system -->
> https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.ts#L10

Could you post how you modified this code? (The link in your original reply is no longer current)
