### ISSUE TITLE
Error after migrate to Next.js 9.0.0

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#382]
## Describe the bug
After migrate to the latest version of Next.js, the next-i18next package is throwing an error after `npm run dev`

```
TypeError: Cannot read property 'detection' of undefined
```

My i18n config:

```js
{
  "defaultLanguage": "es",
  "localeExtension": "json",
  "localePath": "static/locales",
  "localeStructure": "{{lng}}/{{ns}}",
  "localeSubpaths": "all",
  "otherLanguages": [
    "es",
    "en",
    "de",
    "it",
    "fr"
  ],
  "pluralSeparator": "_",
  "simplifyPluralSuffix": true,
  "detection": {
    "order": [
      "querystring",
      "cookie",
      "navigator"
    ]
  }
}
```

Import using common.js

```js
const NextI18Next = require('next-i18next').default
```

## Occurs in next-i18next version

```
next-i18next@0.45.0
```

## Steps to reproduce

Just migrate from `next@8.1.0` to `next@9.0.0` and run the app with `npm run dev`.

## Expected behaviour

I expect to run the app without any crash. As in next 8.1.0 version.

## Screenshots

![image](https://user-images.githubusercontent.com/13313058/60809728-a149b880-a18b-11e9-9293-7f1a4d55505e.png)

## OS (please complete the following information)
 - Device: MBP 2018 13
 - Node: v11.8.0

**Comment by isaachinman** [comment]
Looks like the NextJs team may have changed some of their Babel internals. I'll take a look when I have time.

**Comment by aralroca** [comment]
I realized that this is happening only using this in my `next.config.js`:

```js
const withTM = require('next-transpile-modules')

// ...

const hasModuleTranspilation = withTM({
  transpileModules: ['next-i18next'],
  ...nextConfig
})
```

That I did to solve this another problem commented here: https://github.com/isaachinman/next-i18next/issues/290#issuecomment-506879668

So I guess is not an issue of this library. I can close it.

**Comment by isaachinman** [comment]
Ah okay, makes sense. It does indeed sound like a module problem. Good luck.
