### ISSUE TITLE
When click back button after page refresh router is not working

### ISSUE THREAD

**Issue by pavel06081991** [isaachinman/next-i18next#389]
## Describe the bug
When click back button after page refresh router is not working. Url in browser is changed to the previous but previous page is not loaded and not opened. It happens when using Link component from i18n file. But if I use Link component from native router(`import Link from 'next/link';`) it works.

## Occurs in next-i18next version
0.37.0

## OS (please complete the following information)
 - Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
Please provide a reproducible repository. In the meantime, I suggest you update to the latest version of `next-i18next`.

**Comment by isaachinman** [comment]
Any update?

**Comment by pavel06081991** [comment]
@isaachinman sorry for delay. I've tried to update to the latest version. The issue still exists. I'll provide repository soon.
