### ISSUE TITLE
NextI18Next doesn't set proper default language to i18n instance

### ISSUE THREAD

**Issue by igorbuts** [isaachinman/next-i18next#39]
Here is the content of my `i18n.js`

```
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
  defaultLanguage: 'ru',
  otherLanguages: ['en'],
})
```

And here is the result I have: in `NextI18Next config` the right default lang is set. But in the Instance of `i18n` I see `en` as a current language

A.R `ru` is set as current language in i18n instance.
E.R. `en` is set as current language in i18n instance.

A.R  `languages  = ["en"]` in i18n instance.
E.R.  `languages  = ["ru", "en"]` in i18n instance.

Here are the screenshots: https://ibb.co/f2HKfdh https://ibb.co/TYDmvsk

Is this a bug. Or it is expected behavior and I am missing something?

package version `"next-i18next": "^0.8.0"`

**Comment by isaachinman** [comment]
I don't understand your question. This may be a misunderstanding of how language detection works. Is your browser language set to English?

**Comment by igorbuts** [comment]
yep, the default language of my browser is English

**Comment by isaachinman** [comment]
Then that is why your language is being set to English. In my opinion this is an incredibly sensible default, however you might be interested in sharing your opinion in #32.

**Comment by igorbuts** [comment]
Thanks. Will stay tuned.
If I've understood #32,  `browser-language detection` will be still turned on by default, but it will be available to opt-out from it. Right?
