### ISSUE TITLE
Can't set defaultLanguage (id) as root / when using localeSubpaths

### ISSUE THREAD

**Issue by iyay** [isaachinman/next-i18next#397]
Hi,

I need to set default language to other language, in this example i use `id` as `defaultLanguage`, i expected when user go to `www.example.com/` the lang is `id`, but in my case, user redirected to `www.example.com/id/` and when user change the lang to `en` they redirected to `www.example.com/`

here's my configuration

```
new NextI18Next({
  defaultLanguage: 'id',
  otherLanguages: ['en'],
  localeSubpaths: 'foreign',
});
```

any clue how to set the root path to `defaultLanguage`? i need some help here

Thanks

**Comment by isaachinman** [comment]
I have recreated this setup in the simple example and it works as expected.

Most likely you have not considered your browser language settings. I would suggest you install a Chrome extension to change your user lang preferences and see how the app behaves.

You'll also want to take a look at the `config.detection` options and play around with that.

If you feel you have found a genuine bug, please reopen and provide a reproducible repository.

Good luck.

**Comment by iyay** [comment]
Hi again,

yep, it works but i forgot to mention the intention with this, basically i need to set `defaultLanguage` based on **.tld**, here's the things -- i have multiple domain to serve my app, this domain had different .tld (eg: .id, .hk, .th, etc) 

can i set the `defaultLanguage` based on those `.tld`?

Thank you in advance

**Comment by isaachinman** [comment]
You'll need to either find a pre-existing i18next detector, or write a custom detector. Or, if each TLD is its own deployment of the app, just run an environment variable. Good luck.
