### ISSUE TITLE
Change 'link' to 'file' in example/simple/package.json 'mac'

### ISSUE THREAD

**Issue by BondoS** [isaachinman/next-i18next#398]
## Describe the bug
when I run 'npm install' in examples/simple directory, it produces this error
ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../../node_modules/react

## Occurs in next-i18next version
i18next@17.0.6
npm -v 6.9.0
react version 16.8.6

## Steps to reproduce
npm install

## Expected behaviour
npm install shouldn't produce errors

## OS (please complete the following information)
 macOS Mojava version 10.14.5
![image](https://user-images.githubusercontent.com/2457873/61370382-93ceb580-a892-11e9-8317-f95eb5c710d9.png)

I fixed this issue by changing 'link' to 'file' in example/simple/package.json

I think you should fix it or add it in the docs for people who use macOS

Thank You

**Comment by isaachinman** [comment]
We use `yarn` internally when developing and testing this package. You are free to:

1. Use `yarn`
2. Install `next-i18next` from the normal npm registry for all non-development use cases
3. Suggest a fix that will allow us to still dev locally and also deploy to a PaaS like Heroku

Let me know what you think.

**Comment by isaachinman** [comment]
Wanted to also note that there are only yarn lockfiles in this repo, and you should have already been receiving warnings if you were using npm to do installs.

**Comment by BondoS** [comment]
Thank you for the prompt reply, Really appreciate it.

Yes, You are right, I had a lot of warnings and I have been searching around to fix them, all fine now, I can run with either npm or yarn

But I cannot reach domain/en or domain/de for either the examples/simple project or my custom-made project
On my project, I need to be able to visit domain/en-us or domain/ar-us and so forth, I need to specify the language and country in URL and it should be reflected from static/locales/ folder
But it doesn't work, and this warning is consistent whether in examples/simple or project or my project
the warning is "react-i18next:: i18n.languages were undefined or empty undefined"

Note, I wanna be able to create
domain/ar-eg > Arabic RTL, Egypt
domain/en-eg > English LTR, Egypt
domain/ar-sa > Arabic RTL, Saudi Arabia
domain/en-sa > English LTR, Saudi Arabia
...... and so on

Thank You and sorry for any inconveniences

**Comment by isaachinman** [comment]
Please search through existing issues for implementation questions, and/or open new issues or post on StackOverflow.

**Comment by isaachinman** [comment]
@BondoS I'm happy to keep this issue open, as the original point about `link:../../node_modules` is valid. Just wanted to maintain focus on one item per issue.

**Comment by BondoS** [comment]
@isaachinman Yes, You're definitely correct.

**Comment by isaachinman** [comment]
Unfortunately it looks like we're not going to be able to do this very easily - a direct swap to `file` results in the "multiple versions of React" errors, so `yarn` and `npm` are behaving very differently here.
