### ISSUE TITLE
Redirect in middleware when locale is missing from url

### ISSUE THREAD

**Issue by keustma** [isaachinman/next-i18next#401]
## Describe the bug
Hi, not a real bug report, but more of a question if I'm misunderstanding a feature or I've found a bug. In my understanding, if I configure `localeSubpaths: 'all'` the locale should always be present in the URL. I visit for `https://www.google.be/hello` it should make sure this is rewritten to `https://www.google.be/en/hello`. This currently kinda works but seems to be handled on the client side and not on the server in the middleware.

## Occurs in next-i18next version
0.45.0

## Expected behaviour
I would expect the middleware to detect that the current request url is missing the locale and redirect the entire request via a 302 redirect.

I've tracked the issue down to the `lng-path-detector.js` file which seems to be not setting the correct `config.correctedUrl`.
I think the issue is in this section: https://github.com/keustma/next-i18next/blob/master/src/utils/lng-path-detector.js#L35

The `if` statement is entered, the `allLanguages.forEach` does not set the correct url. Before leaving the `if` statement, I added a part to the if-statement which seems to fix the issue.

```javascript
if (!languageChanged && languageNeedsSubpath && !req.url.startsWith("/".concat(language, "/"))) {
      allLanguages.forEach(function (lng) {
        if (req.url.startsWith("/".concat(lng, "/"))) {
          config.correctedUrl = req.url.replace("/".concat(lng, "/"), '/');
          languageChanged = true;
        }
      });

      if(!languageChanged) {
        config.correctedUrl = '/' + language + req.url;
      }
}
```

**Comment by isaachinman** [comment]
Yes, that's correct. The middleware should redirect with a 302 via [this util](https://github.com/isaachinman/next-i18next/blob/master/src/utils/redirect-without-cache.js). If you've found a situation where that does not happen, please provide a reproducible example. Thanks!

cc @capellini

**Comment by keustma** [comment]
Hi,

a minimal reproduction case can be found here https://github.com/keustma/next-i18next-redirect-repro, when running `npm run dev` I expect a `GET` to `http://localhost:3000` to receive a status `302 FOUND` status and a redirect to `http://localhost:3000/en/`. But this is not happening.

**Comment by isaachinman** [comment]
Your linked repository doesn't have an `_app.tsx`.

**Comment by keustma** [comment]
I added the `_app.tsx` file.

**Comment by isaachinman** [comment]
Yes, and it's redirecting to `/en/`.

**Comment by isaachinman** [comment]
Ah, got it. Yes, also disabling JavaScript will reproduce this bug.

**Comment by isaachinman** [comment]
After taking a deeper look, the [lng-path-detector](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lng-path-detector.js) util appears to be poorly written and bug-prone.

**Comment by isaachinman** [comment]
@keustma This should be fixed by #404. Can you review and/or test?

**Comment by capellini** [comment]
@isaachinman Please let me know how I may assist.

**Comment by isaachinman** [comment]
Hey @capellini - as this is a bug, it would be great to have test coverage to prevent regressions. Might make sense to have an e2e test covering this and do network interception via Puppeteer.

**Comment by capellini** [comment]
> it would be great to have test coverage to prevent regressions. Might make sense to have an e2e test covering this and do network interception via Puppeteer.

:+1: I'll see if i can come up with some tests to prevent regressions.
