### ISSUE TITLE
ie, edge i18next not working

### ISSUE THREAD

**Issue by arsendev** [isaachinman/next-i18next#412]
hello! @isaachinman 
[chrome, safari, opera, firefox] works fine. But [ie, edge]browser has an error in that part, like a picture below. Can you tell what's the problem?

```
- node -v 10.15.3
-npm -v 6.4.1
-react -v 16.8.6
-next -v 8.1.0
```

### ie console
![ie](https://user-images.githubusercontent.com/51102399/61606484-88f69500-ac85-11e9-8f7c-bbdca5ea4b4d.png)

### edge console
![edge](https://user-images.githubusercontent.com/51102399/61606511-aaf01780-ac85-11e9-959b-3536daeed42c.png)

### index.js code 
```
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { inject, observer } from 'mobx-react'
import HeaderHoc from '../components/Header/HeaderHoc'
import { withTranslation, Trans, Link } from '../lib/i18n'

@inject('store')
@observer
class Index extends Component {

  render() {
    const {
      store: {
        menuStore: {
          windowResize
        }
      }
    } = this.props
    return (
      <>
        {/* <HeaderHoc {...this.props} /> */}
        <div> </div>
      </>
    )
  }
}

Index.getInitialProps = async () => ({
  namespacesRequired: ['common'],
})

Index.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withTranslation('common')(Index)

```

[I apologize for the weirdness of the context by turning the translator around...]

**Comment by isaachinman** [comment]
I've just confirmed that the [simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple) is working fine in latest Edge:

![Screen Shot 2019-07-22 at 08 31 13](https://user-images.githubusercontent.com/10575782/61614261-30120700-ac5b-11e9-9b46-c4d7b8a735ec.png)

I do not understand from your screenshots above what the problem you're experiencing is, but try upgrading to v0.50.0.

**Comment by arsendev** [comment]
Oh, thank you. There was a problem with the package version.
