### ISSUE TITLE
Can you proceed with one JSON file?

### ISSUE THREAD

**Issue by arsendev** [isaachinman/next-i18next#415]
Hello. @isaachinman 
I have a common.json file.
Common.json's file format is shown below.
```
{
    en : {
        common : 'hello'
    },
    ko : {
        common : 'hello'
    },
    jp : {
        common : 'hello'
    },
    zh : {
        common : 'hello'
    }
}
```
It contains multiple languages [en, ko, jp, zh] of one file in that form. Can I use it like that?

**Comment by isaachinman** [comment]
Hi there, this seems like a general i18next question. Please post on StackOverflow or similar. Good luck.
