### ISSUE TITLE
expose full 'loadPath' of 'i18next-xhr-backend'

### ISSUE THREAD

**Issue by drewxiuxiuxiu** [isaachinman/next-i18next#416]
## Is your feature request related to a problem? Please describe.
Normally when the app fetch a `.json` file, if would bring a 'cache control' header back along with it. Therefore the browser can cache it accordingly. One common way to force update the cache is to query the file with an hash like param 
e.g.
`static/locales/en/common.json?88172389182737123817238`

Unfortunately current options (localeExtension/localePath/localeStructure) doesn't allow to do so. 

## Describe the solution you'd like
Somehow allow the user to gain control of the full path, just like the "loadPath" option of `i18next-xhr-backend` this lib internally uses.

## Describe alternatives you've considered
expose another option like 'localeQuery' or 'localePathSuffix' or as such. 

## Additional context

I can submit a PR if this is approved with at least one option you adore.

**Comment by isaachinman** [comment]
Have you tried simply playing with `localeExtension`?

**Comment by drewxiuxiuxiu** [comment]
> Have you tried simply playing with `localeExtension`?

Yes I tried. Like `json?hash123`. And it breaks things. Apparently it was internally used to locate default namespace file on server without trimming the query section with error:

`Error: Default namespace not found at .../static/locales/zh/common.json?123`

**Comment by isaachinman** [comment]
And what happens if you comment out the default namespace check block?

In general I am happy to see improvements in this area, but you will need to lead them.

**Comment by drewxiuxiuxiu** [comment]
> And what happens if you comment out the default namespace check block?

The initial loaded page got no resource to display, showed only bare keys.  But the alternative lang is fine, the ajax calls were straight 200.

> In general I am happy to see improvements in this area, but you will need to lead them.

Good to know. After some digging I found [queryStringParams](https://github.com/i18next/i18next-xhr-backend#backend-options) on `i18next-xhr-backend` side can easily solve issue. 

The only thing this lib has to do is to respect that option in `create-config.js` and update the document. Can you accept a PR doing just that?

**Comment by isaachinman** [comment]
We already allow you to set up your own backend entirely. Just add `config.backend.queryStringParams`.

**Comment by drewxiuxiuxiu** [comment]
> We already allow you to set up your own backend entirely. Just add `config.backend.queryStringParams`.

It seems to be a bug of `create-config.js`: if I do so, localeExtension/localePath/localeStructure are lost.

**Comment by isaachinman** [comment]
It's a bit tricky handling deep merges, because we need to use config values to generate further values. Try passing a full and valid `backend` object.

**Comment by drewxiuxiuxiu** [comment]
Then it works fine. I think this case is solved, but bring out some other issue apparently. 

I was puzzled by how this lib merge other backend options previously . For example, localStorage backend, which still makes a bit sense on Client side.  Since that backend got its own compatibility issue with next, I didn't go further. 

Thanks for your prompt response and instruction! Feel free to close this or let me know anything that I can help with.

**Comment by isaachinman** [comment]
I think the only possible way to support what you're asking for is to deep merge before doing any work, store both the default and user configs thereafter, and then do another deep merge at the end.

That said, for more advanced use cases like this, I don't think it's too much to ask to provide your full and complete `backend` object.

**Comment by drewxiuxiuxiu** [comment]
I agree. 

But there is a caveat if `i18next-chained-backend` was used. the options of this plugin [depends on array order](https://github.com/i18next/i18next-chained-backend#backend-options), which really confused me because I knew this lib use some backend internally already.

I haven't tried much, so probably no issue at all.  Thanks again!
