### ISSUE TITLE
languageChanged is fired refreshing the page

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#417]
## Describe the bug
Using this hook:

```js
export default function useCleanStorageAfterChangeLang() {
  useEffect(() => {
    function cleanStorage() {
      sessionStorage.clear()
    }

   i18n.on('languageChanged', cleanStorage)

    return () => i18n.off('languageChanged', cleanStorage)
  }, [])
}
```

I expect that the event fires the `cleanStorage` callback **only when the language change**. However, looks that every time that the hook is mounted (when I refresh the page), the callback is called although the language is the same.

## Occurs in next-i18next version

I guess is happening from time ago. However, I'm currently using 0.51.0.

## Steps to reproduce

Use the above hook in some page.

## Expected behaviour

Only fire the `languageChanged` event when the language is different. I guess that should fire after refreshing the page only in the case that the user manually rename the lang from the url.

**Comment by isaachinman** [comment]
How is this a problem? Why does your SPA make assertions about state across hard reloads?

I believe that `next-i18next` and `react-i18next` itself will do intentional lang changes on mount to prevent some weird problems that arise if you don't.

Happy to see a PR for this, but it'd be much safer on your side to use a different approach.

**Comment by aralroca** [comment]
> How is this a problem? Why does your SPA make assertions about state across hard reloads?

In my case, I have this problem because there are parts of my platform that are not part of Next.js yet. Of course, navigating between Next.js pages is not a real problem. The problem comes navigating to an old part, and then returning to the new part.


> I believe that `next-i18next` and `react-i18next` itself will do intentional lang changes on mount to prevent some weird problems that arise if you don't.

I don't know... However, the docs say that this event is fired after changing the language, and it's not the current behavior. For this reason, I reported. Of course, If it makes no sense, just close it :)


> Happy to see a PR for this, but it'd be much safer on your side to use a different approach.

I can try to do a PR. But before it, maybe its better if we first clear up what this event should do exactly.

**Comment by isaachinman** [comment]
I misspoke. We're doing a lang change [here](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L82) in `getInitialProps`, but only during SSR.

Can you please trace the stack of the `languageChanged` event which you believe is erroneous, and let me know where it is coming from?

**Comment by aralroca** [comment]
I fixed in my side doing a different approach, without the `languageChanged` event.

I close this issue because I don't want to do a breaking change if the `languageChanged ` is designed in a different way that I was supposing.

**Comment by isaachinman** [comment]
Okay, fair enough. I do indeed believe that the lang change is coming from `react-i18next` itself, as this is part of the `withSSR` HOC.

**Comment by aralroca** [comment]
@isaachinman Sorry I didn't see your last message. I guess that the i18n event is fired after the initialization also. Feel free to reopen it if you think that is not the correct behavior of https://www.i18next.com/overview/api#onlanguagechanged

**Comment by isaachinman** [comment]
@aralroca This repo doesn't deal with the core behaviour of any of the i18next projects. You'd need to open an issue in the `react-i18next` repo based on [this line](https://github.com/i18next/react-i18next/blob/master/src/useSSR.js#L20).

That said, I'm not sure if it's actually a bug. My initial feeling is that it's not reasonable to rely on `languageChanged` being dependable across hard refreshes.
