### ISSUE TITLE
next-i18next cookie name

### ISSUE THREAD

**Issue by afulsamet** [isaachinman/next-i18next#420]
## Is your feature request related to a problem? Please describe.
I tried search cookie name option but i wasn't find. I want change cookie name as `lang` from `next-i18next`

## Describe the solution you'd like
If next-i18next have this option, Can you tell me?

## Describe alternatives you've considered
If next-i18next doesn't have this option, i wants it will be cookie name option.

**Comment by isaachinman** [comment]
https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.js#L38

**Comment by adrai** [comment]
Next.js handles this now: https://nextjs.org/docs/pages/building-your-application/routing/internationalization#leveraging-the-next_locale-cookie
