### ISSUE TITLE
Update to v0.51.0 causes redirect chain

### ISSUE THREAD

**Issue by MrAvantiC** [isaachinman/next-i18next#423]
## Describe the bug
Hey, 
I have the following use case in my application:
My Next.js application itself does not know anything about URLs and what data and components lies behind an URL.
Instead, it works like this:
1) A user visits a given URL
2) During `getInitialProps` in `_app.js` I query my API with the given URL
3) The API return relevant data that let's me determine what kind of page this is (we currently migrate a legacy e-commerce system) and what data is relevant to display the page
4) The data received from the API also tells me what the relevant language for the given URL is
5) After receiving the API response, we manually set the language relevant to the URL like this: `i18n.changeLanguage(pageData.language)`

This worked just fine until I upgraded next-i18next yesterday. Since then we are getting redirect chains on every page.

After further investigation, I found that this is the relevant commit that this is the commit that broke the workflow described above: https://github.com/isaachinman/next-i18next/commit/d7623f6bc9a37dd8aea5fbd9d9838697968e70b0

My guess is, that since you removed `{ shallow: true }` from `router.replace()`, the application now runs through `getInitialProps` again after changing the language, which causes the language to change again, etc.

My questions now are:
1) Is there a specific reason you removed `{ shallow: true }`?
2) If there is and you are set to leave the implementation like it is now, do you see - given the use case described above - another way around this problem?

Right now I have to pin the version to v0.50.0 which is fine for now but of course wouldn't allow us to pull updates in the future.

## Occurs in next-i18next version
v0.51.0

## Expected behaviour
When changing the language based on fetched data in `getInitialProps`, it should not trigger another run of `getInitialProps` and therefore cause internal redirect chains.

Thanks for your help!

**Comment by isaachinman** [comment]
Related to #305.

You should not be calling `changeLanguage` inside `getInitialProps`. That can be thought of as similar to calling `setState` inside `componentDidUpdate`.

If you need to choose a language based on some API call with the current page URL, you should write a custom language detector.

Let me know if you have any other questions - happy to answer them.

**Comment by MrAvantiC** [comment]
Hi @isaachinman ,

thanks for the explanation that the way I use `changeLanguage` currently is kind of an anti-pattern.

To be honest, I'm having some trouble figuring out the integration and lifecycle of a custom language detector.
Most of the documentation points to some already existing middleware but doesn't show how to build one yourself.

Maybe - if you have a couple of minutes - you could give me a hint into the right direction?! :)
I produced a [minimal example repo](https://github.com/MrAvantiC/nextjs-i18next-example) of the use case I described in my original post.

It basically contains of 3 parts:
1. A custom `server.js` which takes any request, parses the URL path and renders the index-page with the given URL-Path.
2. A basic `i18n.js` which currently does no more than exporting the languages:
```javascript
const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de'],
})
```
3. A custom `_app.js` which uses the passed in URL path to fetch some data based on the path. The API call then returns the language that belongs to the URL path which I want to use to set the language of the i18n library.

If you have a look at `_app.js` in [line 24](https://github.com/MrAvantiC/nextjs-i18next-example/blob/master/pages/_app.js#L24), this is where I call `i18n.changeLanguage(pageData)` in the current solution.

Can you maybe point me to an example of how to integrate a custom language detector and how it would fit in a workflow like this?

Kind Regards.

**Comment by isaachinman** [comment]
Maybe this will help: https://github.com/isaachinman/next-i18next/issues/208#issuecomment-468272838

**Comment by MrAvantiC** [comment]
Hi @isaachinman,
that did help getting me started on writing the custom detector, yes, thanks!

What still is unclear to me is the "lifecycle" of the detector.

[I adapted the example](https://github.com/MrAvantiC/nextjs-i18next-example/commit/bebc436dd562b437ebb72d227a307c4ca803fef9) and it raised a couple of questions:
I can see that the `lookup` function is called once on the server and then - on initial hydration(?) - on the client. It seems to work that it changes translation based on the value returned in the `lookup` function on the server-side. So far, so good.

What I'm wondering is:
1. Since I cannot use the information of the current signature `(req, res, options)` to figure out what language I need - instead I would have to pass in the result of the API call in `_app.js` - how can I achieve to have the result of the API call available in `lookup()`? 
Because if I add another `console.log()` in `_app.js` it appears *after* the `console.log()` in the `lookup` function of the detector and therefore seems that the `lookup` runs before `getInitialProps` in `_app.js`. 
2. Quite similar is that every navigation after the initial render should happen on the client and might involve navigating to a page in a different language. So again, I would need to change the language based on the new API response.

I tried to change my `_app.js` to something like that for testing purposes:
```javascript
import { i18n } from '../i18n'

static async getInitialProps({ Component, ctx }) {
    // ...
    const allDetectors = i18n.services.languageDetector.detectors
    const apiDetector = allDetectors['language-detection-api']

    apiDetector.lookup()
   // ....
}
```

While this caused the console output of the `lookup` function to appear on every navigation, it unfortunately did not affect the translation on the client. :(

It feels strange that there is no other example where people try to achieve something like that. is my use case really that odd?

Kind Regards.

**Comment by isaachinman** [comment]
> Since I cannot use the information of the current signature (req, res, options) to figure out what language I need

> is my use case really that odd?

Yes, that seems quite unusual to me. It sounds like you'll need to do your API querying in a custom Express middleware. Sorry, but this is well outside the scope of `next-i18next`. Good luck!

**Comment by MrAvantiC** [comment]
> It sounds like you'll need to do your API querying in a custom Express middleware.

But that would mean that I'm not able to navigate on the client then, wouldn't it?

The goal was to use the same logic/code in `_app.js` on both the client and the server, therefore we called the API there and then used `i18n.changeLanguage` based on the API response.

Since you mentioned that calling `changeLanguage` in `getInitialProps` was kind of an anti-pattern that could be solved with a custom language detector, I thought that it would possible to apply the language detector to both the server and client. :/

**Comment by isaachinman** [comment]
> But that would mean that I'm not able to navigate on the client then, wouldn't it?

Why? The initial language should be set server side.
