### ISSUE TITLE
When upgrading from 0.45 to 0.46 (or higher) getting `Cannot read property 'bind' of undefined`

### ISSUE THREAD

**Issue by emirotin** [isaachinman/next-i18next#424]
## Describe the bug
With 0.46 or higher getting the error `Cannot read property 'bind' of undefined`

## Occurs in next-i18next version
0.46 or higher

## Additional context
I've tracked it down to the lines in transpiled CommonJS where consoleMessage getter is defined.

```
Object.defineProperty(exports, "consoleMessage", {
  enumerable: true,
  get: function get() {
    return _consoleMessage.default;
  }
});
```

It appears that `_consoleMessage` is an empty object so `default` is undefined, and then `.bind` is called on it.

This looks surprising and the only explanation I see is that some circular import is happening in which case some of the modules would indeed obtain an empty object from `require`. But I wasn't able to figure out where such import would happen.

## Environment

macOS 10.14.6

❯ node -v
v8.16.0

❯ npm -v
6.9.0

❯ yarn -v
1.16.0

**Comment by isaachinman** [comment]
Can you please provide a reproducible repo?

**Comment by emirotin** [comment]
I'll try to though the current project is fairly big

**Comment by isaachinman** [comment]
Probably your Node version and environment will also be important on this one, as it seems related to module resolution.

**Comment by emirotin** [comment]
Added

**Comment by emirotin** [comment]
https://www.dropbox.com/s/nvvnsp3g4fmv4rl/bind-undefined-repro.zip?dl=0

can you check this, please?

**Comment by isaachinman** [comment]
The error you are experiencing is because you are re-transpiling `next-i18next` within `node_modules`. Check your `next.config.js` file.

If you want to transpile your own deps, you need to consume the `es` target.

**Comment by emirotin** [comment]
Oh, good catch.
I didn't author that line and didn't realize its effect. For some reason it
used to be needed but can be removed now I think. Thanks!

**Comment by emirotin** [comment]
Okay, 19 days later I've figured out why we had this line (which I _have_ actually authored a long time ago).
Somehow even given the fact this module defines the commonjs as its default export we're getting the ES code in our bundle:

https://monosnap.com/file/dGl0hp5q4Yzqj39RIoOUzK0zyeq4tj

This non-transpiled splat breaks the site in Edge, for example.

Any idea why this is happening? I cannot imagine how and why webpack would prefer to import the `dist/es` version.

**Comment by emirotin** [comment]
UPD: ah, I think I know what's happening. A _dependency_ of our project depends on this module v0.45 that _has_ the _ES_ exports.
