### ISSUE TITLE
How to call/use local files based on domain

### ISSUE THREAD

**Issue by nisargrthakkar** [isaachinman/next-i18next#425]
I have 3 domain based on country.

Like 
www.xyz.com for the **USA**
www.xyz.fr for **France**
www.xyz.de for **Germany**

All 3 Domain is pointed to a single code base and functionality remain the same. Only things change is **language**

Like 
www.xyz.com call **us** local files
www.xyz.fr call **fr** local files
www.xyz.de call **de** local files

How can I implement this thing with next-i18next??

**Comment by isaachinman** [comment]
https://github.com/i18next/i18next/issues/1139

**Comment by kachkaev** [comment]
@nisargrthakkar feel free to use my mini-project as an example: https://gitlab.com/kachkaev/website-frontend/tree/master

It supports two domain-based locales, but I’m sure you’ll be able to adjust the logic for an arbitrary number of locales.

**Comment by nisargrthakkar** [comment]
Thanks, @isaachinman for the quick response 
Thanks, @kachkaev  Sure I will check your project.
