### ISSUE TITLE
Dynamic routing not working

### ISSUE THREAD

**Issue by adascal** [isaachinman/next-i18next#426]
## Describe the bug
I have the following pages structure:
```
pages
  post
    [id].js
  index.js
```
This should work according to the docs:
https://nextjs.org/learn/basics/clean-urls-with-dynamic-routing/dynamic-routing

The router seems to redirect correctly, however I get the following url on client-side transformed from http://localhost:3000/post/5 to http://localhost:3000/post/[id]?id=%5Bid%5D

## Occurs in next-i18next version
#0.52.0

## Steps to reproduce
Checkout example: https://github.com/adascal/next-i18next/tree/dynamic-routing-issue-example
https://github.com/isaachinman/next-i18next/compare/master...adascal:dynamic-routing-issue-example

## Expected behaviour
Routes are not transformed

## Additional context
PR with fix (closed): https://github.com/isaachinman/next-i18next/pull/422
Similar issue: https://github.com/zeit/next.js/issues/8092

**Comment by isaachinman** [comment]
Hey @adascal - thanks for opening an issue. Your diagnosis of the problem is correct, but I've realised we need to hook into `initializedLanguageOnce` and set the `asPath` a little differently. I'll have a fix in for this within an hour or two.

**Comment by isaachinman** [comment]
Note that we still have the problem with `Link` components as described in #413.
