### ISSUE TITLE
lngFromReq always return fallback array not the current language.

### ISSUE THREAD

**Issue by BondoS** [isaachinman/next-i18next#428]
## Describe the bug
I can't get the current language from Request using lngFromReq function from "next-i18next/dist/commonjs/utils"
I'm trying to indicate the language in _document.js file to set some important SEO attributes in <html> and <head> tags

## Occurs in next-i18next version
├── express@4.17.1
├── next@9.0.2
├── next-i18next@0.47.0
├── node-pre-gyp@0.12.0 extraneous
├── react@16.8.6
└── react-dom@16.8.6

## Steps to reproduce
> import { lngFromReq } from "next-i18next/dist/commonjs/utils";
> 
> class MyDocument extends Document {
> 
>   static async getInitialProps(ctx) {
>     const initialProps = await Document.getInitialProps(ctx);
>     let lngggg = await lngFromReq(ctx.req);
> 
>     const additionalProps = await {
>       lngggg
>     };
> 
>     return { ...initialProps, ...additionalProps };
>   }
>  ..........................................
>  }

## Expected behaviour
I'm expecting a string of current language, not an array of fallback.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/2457873/62096804-2dc83200-b285-11e9-81e4-4c097c1ff069.png)

## OS (please complete the following information)
 - Device: 
![image](https://user-images.githubusercontent.com/2457873/62096930-ad560100-b285-11e9-9e9f-c0195a983998.png)

 - Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
The `lngFromReq` util is for internal use. If it doesn't do what you expect it to, simply don't use it. In server contexts, you should use `req.i18n`. In client contexts, you should use the `i18n` instance exported by the `next-i18next` constructor.
