### ISSUE TITLE
`appWithTranslation` not propertly exported

### ISSUE THREAD

**Issue by dhovart** [isaachinman/next-i18next#435]
## Describe the bug
In the latest version of the library appWithTranslation doesn't seem to be correctly exported anymore. Visual Studio Code reports me the following: `Property 'appWithTranslation' does not exist on type 'NextI18Next'` and my app crashes at startup.

## Occurs in next-i18next version
Version 0.53

## Steps to reproduce
Bumping i18next to the latest version (from version 0.44 in my case)

## Expected behaviour
appWithTranslation should be correctly exported.

## OS (please complete the following information)
Device: Mac OS 10.14.4
Browser: Chrome 75.0.3770.142
Node: v10.15.3

**Comment by aequasi** [comment]
withTranslation export on the instance is also an issue

**Comment by isaachinman** [comment]
Fixed and released with v0.53.1. Sorry about this - it's now covered with tests so future regressions should not be possible.
