### ISSUE TITLE
Low text html ratio

### ISSUE THREAD

**Issue by liorvo** [isaachinman/next-i18next#445]
while using SEO measuring tools such as lighthouse, we get a very low score for text/html ratio, because the translations json text is embedded in the page source. I wonder if there is a way to using this library while maintaining a high text/html ratio.
we currently are using version 0.37.0 but we came across this problem throughout all the previous versions as well.

**Comment by isaachinman** [comment]
The only other thing that comes to mind would be a separate network request, which is not something we're going to build in just to please lighthouse.

Open to suggestions but please remember that tools are meant to be interpreted, not taken literally.
