### ISSUE TITLE
Does next-i18next cache locally locale files ?

### ISSUE THREAD

**Issue by Feel-Joy** [isaachinman/next-i18next#447]
By the README.md, I didn't see any description about the cache.

**Comment by isaachinman** [comment]
What is your question?

**Comment by Feel-Joy** [comment]
I want to do something when Node server get request about locale files.
```js
// with next.js and next-i18next
server.get('*', (req, res) => {
  if (req.url.startsWith('/static/locales')) {
    console.log('load locales')
  }
  handle(req, res)
})
```
But I found when server-side render, didn't always console 'load locales', so I want to know whether if there has cache.

**Comment by isaachinman** [comment]
Of course SSR doesn't make a network request. It loads locales from the filesystem and holds them in memory. The `static/locales` route is for client side loads.

I recommend you take a read through the docs to better understand the approach.

**Comment by Feel-Joy** [comment]
OK, Thanks for your reply!
