### ISSUE TITLE
Access t function in _app.js

### ISSUE THREAD

**Issue by danielcooke1996** [isaachinman/next-i18next#449]
Is this possible?

I tried using both HOCs `withTranslation` and `appWithTranslation`

But the `t` function that is injected by `withTranslation` gives this message when used:

`react-i18next:: You will need pass in an i18next instance by using initReactI18next`

**Comment by isaachinman** [comment]
The `appWithTranslation` HOC wraps in the i18next provider. Yes, you should be able to, but I do not recommend it.

Please post on StackOverflow for any further questions.

**Comment by mqtik** [comment]
Why would you not recommend it?

**Comment by isaachinman** [comment]
@mqtik Translated content doesn't really belong in the `_app` file. The `_app` file is mostly used for top-level setup, layout, styles, etc.

**Comment by haggen** [comment]
@isaachinman Just a heads up about consuming or not translation inside `_app`. It's usually where we put our providers, and Ant Design's `ConfigProvider` accepts localized strings for form validation messages, for instance, so it makes sense to load your translations there and give it to the provider.

@mqtik I don't know how you solved it, but I'm using the hook `useTranslation` and it's working. The only thing I'm struggling with is that I'm not getting namespaces loaded other than the default `common`, and only on the client side. The server loads the strings quite alright.
