### ISSUE TITLE
Add memory leak load testing

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/next-i18next#452]
As per #450, we need load tests to ensure heap size is stable over hundreds or thousands of requests.

**Comment by dfvalero** [comment]
Hi! How can I help with this?

**Comment by isaachinman** [comment]
We need to find a way to:

1. Run an npm script, passing in an `--inspect` flag, or similar, holding this process open for later assertion
2. Immediately assert against the memory usage of the process
3. Run artillery against a localhost port
4. Assert again against the memory usage of the process
5. Close the process

**Comment by lucasfeliciano** [comment]
What I did a while back to profile our application when we had memory leaks in the past was to use https://www.npmjs.com/package/heapdump library.

I took two approaches:

1. Take a snapshot of memory when the server starts and one when there is a memory leak

```js
// Start memory reporting block
  if (process.env.NODE_ENV === 'production') {
    heapdump.writeSnapshot(`initial-${Date.now()}.heapsnapshot`)

     memwatch.on('leak', function(info) {
      heapdump.writeSnapshot(`leak-${Date.now()}.heapsnapshot`)

       console.log('-- Memory leak')
      console.log(info)
    })
  }
  // End memory reporting block
```

Then I would get the snapshot from the server and load on chrome inspector to analyze it.
If I'm not wrong, I think this approach didn't give me anything valuable. So I took an approach different approach.

2. I took a snapshot every 30 minutes, and with that, I had more data to work with:

```js
  // Start memory reporting block
  if (process.env.NODE_ENV === 'production') {
    const initialHeapDumpName = `${Date.now()}.initial.heapsnapshot`
    console.log(`>>> Initial snapshot created with name ${initialHeapDumpName}`)
    heapdump.writeSnapshot(initialHeapDumpName)

    // Take a memory snapshot every 30 minutes
    setInterval(function writeHeapSnapshot() {
      const partialHeapDumpName = `${Date.now()}.interval.heapsnapshot`
      heapdump.writeSnapshot(
        `>>> Partial snapshot created with name ${partialHeapDumpName}`
      )
    }, 1000 * 60 * 30)
  }
  // End memory reporting block
```

**Comment by isaachinman** [comment]
@lucasfeliciano Nice - interesting stuff. Depending on how we launch the process, it should be as simple as using `process.memoryUsage().heapUsed`, though, right?

I wonder if there is a util/process-runner that measures heap size over time and allows you to perform assertions. That'd be a really useful package if anyone wants to create and maintain it...

**Comment by lucasfeliciano** [comment]
@isaachinman If I'm not wrong `process.memoryUsage().heapUsed` gives us the total amount of memory.

`heapdump.writeSnapshot()` give us a snapshot file to load on chrome inspector.

![image](https://user-images.githubusercontent.com/968014/64012785-a3424f00-cb1e-11e9-8cdc-5d2dc412b74d.png)

So we can analyze in detail what objects are in the heap.

It is pretty useful

**Comment by isaachinman** [comment]
@lucasfeliciano I'm fully aware of how to analyse via the inspector, but the point is that we need a programmatic way to do this so that it can be run as a blocking step in CI. Is that possible with heap snapshots?

**Comment by lucasfeliciano** [comment]
You can set a listener using `memwatch` pacakge which I also used on the snippet above but forgot to mention.

```js
memwatch.on('leak', (info) => {
  console.error('Memory leak detected:\n', info);
});
```

**Comment by isaachinman** [comment]
@lucasfeliciano Interesting! Does `memwatch` only inspect the process that launched it, or is it also aware of all child processes?
