### ISSUE TITLE
Not found json in client when "localePath" modified

### ISSUE THREAD

**Issue by n00el** [isaachinman/next-i18next#460]
## Describe the bug
When you edit your "**localePath**" option to eg.: 'src/static/locales', the client not found the json file, because its searching it under the following url: "src/static"locales" insted of "static/locales"

## Expected behaviour
The client need to fetch the locale json with the original url, eg.: "http://localhost:3000/static/locales/en-US/common.json" insted of "http://localhost:3000/src/static/locales/en-US/common.json" even if you edited the real localePath

I saw other issues with the same problem, however it's still not fixed.

**Comment by isaachinman** [comment]
This is not a bug. You need to manage `localePath` across environments on your own if you wish to use it that way.

If you believe you have a feature or enhancement to make things easier for other users, feel free to describe the approach.

**Comment by jieliu218** [comment]
> ## Describe the bug
> When you edit your "**localePath**" option to eg.: 'src/static/locales', the client not found the json file, because its searching it under the following url: "src/static"locales" insted of "static/locales"
> 
> ## Expected behaviour
> The client need to fetch the locale json with the original url, eg.: "http://localhost:3000/static/locales/en-US/common.json" insted of "http://localhost:3000/src/static/locales/en-US/common.json" even if you edited the real localePath
> 
> I saw other issues with the same problem, however it's still not fixed.

server.use('/src/static/locales', express.static(path.join(__dirname, 'static/locales')))


Not sure if it is a good way
