### ISSUE TITLE
Translating text with so many tags 

### ISSUE THREAD

**Issue by shakesBeardZ** [isaachinman/next-i18next#463]
I'm always frustrated when it comes to translating text with so many tags in it like a disclaimer page or a privacy policy page, so I have to call the  ``` t() ``` function every time inside every tag
like the following example: 
```
    <ul>
        <li>First item</li>
        <li>Second item</li>
        ...
    </ul>
    <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis porro repel
        <b> Nobis porro repe</b>
        <strong> Nobis porro repe</strong>
        ...
    </p>
```

so if there is a way or a best practice that will make the whole page translated. I really appreciate that u share it with me.
thanks in advance.

**Comment by isaachinman** [comment]
Please post on StackOverflow or similar for these type of questions. This is an issue tracker.

**Comment by kachkaev** [comment]
@shakesBeardZ although I agree with @isaachinman that github issues are for bug reports and feature requests only, the solution is to [use `<Trans />` component](https://react.i18next.com/latest/trans-component).

**Comment by shakesBeardZ** [comment]
@kachkaev thanks, I appreciate the return, I started using it
