### ISSUE TITLE
Modern JS without Core.js

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#464]
## Describe the bug
Using the `experimental.modern = true` in the Next.js `v9.0.4-canary.4` **or upper** (https://github.com/zeit/next.js/pull/7961) next-i18next library is including the core.js shims to the bundle. 

I guess that although is experimental yet, the bundle with modern JS should not include these shims.

## Occurs in next-i18next version
`1.1.0`

## Steps to reproduce
Under canary version, add on the next.config.js file this config:

```js
experimental: {
   modern: true,
},
```

## Expected behaviour
Should not include the shims for modern js.

## Screenshots
![image](https://user-images.githubusercontent.com/13313058/63295624-6cbe3600-c2cd-11e9-8a42-a380b1e99931.png)

**Comment by kachkaev** [comment]
I also see two copies of core-js in the final bundle, even though I don’t use modern flag yet. IMO polyfilling should be done via requiring an enhancer from
this package in  the app’s`next.config.json` rather than by increasing the size of the plugin’s build folder.

**Comment by isaachinman** [comment]
Hi @aralroca, you need to consume the `dist/es` target if you don't want `core-js` in your bundle.

**Comment by isaachinman** [comment]
@aralroca Any update?

**Comment by yogeshkotadiya** [comment]
I'm also having this issue, Multiple copies are bundled in production.

next-i18next: 4.4.1
next: 9.3.5
typescript: 3.7

![image](https://user-images.githubusercontent.com/9676379/81551194-11722d80-939f-11ea-8481-934c91b9753a.png)
