### ISSUE TITLE
[Document] Checking of req object in getInitialProps

### ISSUE THREAD

**Issue by Ktchan825** [isaachinman/next-i18next#467]
## Describe the bug
While browsing with next-i18next router, req could be undefined, So i think we should use
```
import { i18n } from '../i18n'

MyPage.getInitialProps = async({ req }) => {
  const currentLanguage = !req ? i18n.language : req.language
}
```
instead of 
```
import { i18n } from '../i18n'

MyPage.getInitialProps = async({ req }) => {
  const currentLanguage = req === null ? i18n.language : req.language
}
```

## Occurs in next-i18next version
Documentation

## Steps to reproduce
Documentation

## Expected behaviour
N/A

## Screenshots
N/A

## OS (please complete the following information)
Documentation

**Comment by isaachinman** [comment]
Fine with me - it's more of an example anyways and is meant to be adapted to individual use cases. Will accept a PR if you want to put one through.
