### ISSUE TITLE
imported link from 'next-i18next` not effect on link behavior

### ISSUE THREAD

**Issue by Zoha** [isaachinman/next-i18next#468]
Hi.
I using this plugin in my next project and I have an issue. imported link from my next-i18next file is working fine as a regular link but when I have a url like `domain.com/fa` and i want to navigate to another page for example `contact` page I want url to be `domain.com/fa/contact` but instead this will navigate to `domain.com/contact`. even though that language is changed ( because of last request and cookie) but still link not effected on navigating behavior.
how I use code is exactly like example of docs. 

sample code : 

```JAVASCRIPT
import React, { Component } from "react";
import { withTranslation, Router } from "../i18n";

class Index extends Component {
    // states and other stuff
    render() {
        const { t } = this.props;
        return (
            <div className="index-parallax">
		<h1>{t('a translated sample')}</h1>
                <Link href="/contact">
			<a>Contact Link</a>
		</Link>
            </div>
        );
    }
}

export default withTranslation(["common"])(Index);

```
can you guess what the problem is? did I do something wrong?

**Comment by isaachinman** [comment]
Follow the docs.

**Comment by Zoha** [comment]
OK.
problem was the package version.
I have no idea why a prev version was installed
