### ISSUE TITLE
Couldn't POST missing translations

### ISSUE THREAD

**Issue by ivansky** [isaachinman/next-i18next#470]
## Describe the bug
1. POST missing translation doesn't work
i18nextXHRBackend.js:90 POST http://domain/static/locales/en/common.missing.json 404 (Not Found)

## Occurs in next-i18next version
0.53.0, 1.1.0

## Steps to reproduce
```
const nextI18NextConfig: InitConfig = {
    defaultNS: "common",
    localePath: isBrowser ? "static/locales" : "src/static/locales",
    defaultLanguage: "en",
    otherLanguages: ["de"],
    keySeparator: "###",
    saveMissing: process.env.NODE_ENV !== "production",
    saveMissingTo: "all",
    use: [initReactI18next], 
};
```

## Expected behaviour
I expect missing translation are posted as a file.

**Comment by ivansky** [comment]
I'm just guessing that there is a problem with structure, we have src folder for next sources, but CWD is placed one directory behind.

**Comment by ivansky** [comment]
The problem was `missingKeyHandler` wasn't attached to server out of the box here.
@isaachinman Do you have any plans to use it for backward compatibility? 
It already includes middleware package as dependency, I don't see a problem to attach it if config includes missing translation settings.

**Comment by isaachinman** [comment]
@ivansky I don't see a problem changing that. Should be a one-liner, and we can always save it for a v2 release if we're worried about breaking changes.

**Comment by isaachinman** [comment]
@ivansky I'm going to close this, as `missingKeyHandler` will probably require a custom implementation for each user. Thanks for tracking this down.
