### ISSUE TITLE
WithTranslation exported from package seems to behave differently than one from react-i18next

### ISSUE THREAD

**Issue by githubdoramon** [isaachinman/next-i18next#473]
## Describe the bug
When I try to use the WithTranslation type directly from the package on my typescript project, it says that the property 't' does not exist on type. If I import it directly from the react-i18next package (and am using it only for this type) then it works.

## Occurs in next-i18next version
Version 1.1.0

## Steps to reproduce
Just import the WithTranslation from the package, use it in a class interface, and try to access the props.t property

Maybe I am doing something wrong on my side, but not sure what

**Comment by isaachinman** [comment]
@Averethel Can you please explain your recent work?

**Comment by Averethel** [comment]
@githubdoramon I fixed it in https://github.com/isaachinman/next-i18next/pull/459
@isaachinman it seems to me that there was no version release since merging that PR, that would explain the bug report.

**Comment by isaachinman** [comment]
@Averethel Released in v1.1.1.

**Comment by githubdoramon** [comment]
Many thx
