### ISSUE TITLE
Localhost redirect to /fr instead of /fr/

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#476]
## Describe the bug
I don't know if this is a bug or that I'm missing something. Now in the version 1.1.0 when I enter to localhost (or my prod webpage home) instead of redirect to `/fr/` as before is redirecting to `/fr` (without the slash at the end). How can I fix this? (if is not an issue).

## Occurs in next-i18next version
I guess after the `1.0.0`,  after the localeSubpaths change, `0.54.0` is working fine, redirecting to `/fr/`.

## Steps to reproduce

Have version 0.54.0 with:

```
  localeSubpaths: 'all',
```

Migrate to 1.1.0, and change the config to:

```
localeSubpaths: {
    de: 'de',
    en: 'en',
    es: 'es',
    fr: 'fr',
    it: 'it',
  },
```
## Expected behaviour

Redirect to '/fr/' or `/es/` instead of `/fr` `/es`.

**Comment by isaachinman** [comment]
See https://github.com/isaachinman/next-i18next/pull/444#issuecomment-523025254.
