### ISSUE TITLE
Server Error on the very first request from browser

### ISSUE THREAD

**Issue by keethu24** [isaachinman/next-i18next#480]
## Describe the bug

With the integration of nextI18next, the application throws 500 error on the very first call (**even with the static locales files**).
Subsequent calls are successful.

In this repo (branch: bug/runtime-error) https://github.com/keethu24/next-getting-started/tree/bug/runtime-error, you can see the whole setup to reproduce the bug.

![image](https://user-images.githubusercontent.com/47893296/63877835-a7f4ef00-c9c8-11e9-8f99-c6831554faac.png)

## Occurs in next-i18next version
```
    "i18next": "^17.0.11",
    "i18next-express-middleware": "^1.8.0",
    "next": "^9.0.3",
    "next-i18next": "^1.1.1",
```

## Steps to reproduce
- start the app using `npm run dev`
- Go to http://localhost:3001/
- See browser console for the error message
- If it doesn't show the error message, you may have to retry several times. Stop the server and start from the beginning.

## Expected behaviour
- It shouldn't throw 500 error on the very first client call.

**Comment by isaachinman** [comment]
Your config is invalid. You've got `de` as `defaultLanguage` and in `otherLanguages`.

In general, the error you've encountered usual points to user error somewhere along the way.

Let me know if you can figure it out - might be helpful to other users.

**Comment by keethu24** [comment]
I remove 'de', but still showing the error:
![image](https://user-images.githubusercontent.com/47893296/63887514-45f2b480-c9dd-11e9-8b0a-5d6cf5516806.png)

Does this Promise pending message coming from your library?
![image](https://user-images.githubusercontent.com/47893296/63887633-85b99c00-c9dd-11e9-9d41-badb3445add0.png)

By the way, if I remove `lng: "de"` from config, it produces another promise error message **consistently**.
```
VM639 main.js:10914 Uncaught (in promise) Error: The error you provided does not contain a stack trace.
    at B (VM639 main.js:10914)
    at G (VM639 main.js:10914)
    at VM639 main.js:10914
    at Module.le (VM639 main.js:10914)
    at Object.reportRuntimeError (VM639 main.js:6305)
    at _callee3$ (VM639 main.js:8419)
    at tryCatch (VM639 main.js:11237)
    at Generator.invoke [as _invoke] (VM639 main.js:11463)
    at Generator.prototype.<computed> [as next] (VM639 main.js:11289)
    at asyncGeneratorStep (VM639 main.js:201)
    at _next (VM639 main.js:223)
    at VM639 main.js:230
    at new Promise (<anonymous>)
    at new F (VM639 main.js:1723)
```

**Comment by isaachinman** [comment]
Hi @keethu24, you will need to debug your own app. If you end up finding that the root cause is indeed a _bug_ within `next-i18next`, please do report back with full details.

Good luck!

**Comment by keethu24** [comment]
@isaachinman Sad that you can't help further.
But could it be also related to the #374 issue? Because removing the workaround "lng:de" causes an error in my application.

**Comment by isaachinman** [comment]
@keethu24 It simply falls outside the realm of OSS. You're also performing non-standard steps in your `server.js` file, you seem to be mixing js and ts, etc. Too hard to tell exactly where the problem lies without debugging in-depth.

I doubt this is related to #374. #374 is a trivial, non-blocking error.

**Comment by cternes** [comment]
> You're also performing non-standard steps in your server.js file

@isaachinman What do you mean by this?

**Comment by isaachinman** [comment]
@cternes Look at the server file [here](https://github.com/keethu24/next-getting-started/blob/bug/runtime-error/server.js). They're using `app.getRequestHandler` in an unusual way, and they are for some reason importing `i18next-express-middleware` and adding it for a second time after `nextI18nMiddleware`. I'm not at all surprised that they are experiencing issues.

I suggest taking a step back and following the docs. Help requests for specific use cases can be posted on StackOverflow.
