### ISSUE TITLE
Test against all supported node versions

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#482]
Circlecli has the capability to test against a matrix with the help of [workflows](https://circleci.com/blog/introducing-workflows-on-circleci-2-0/).
I propose to test the same matrix as next.js does.

[Next.js .circleci/config.yml](https://github.com/zeit/next.js/blob/canary/.circleci/config.yml)

In future we could also improve to test against browser environments instead node only.

**Comment by isaachinman** [comment]
To clarify, this issue is only concerned with testing against:

1. Our lowest supported NodeJs version
2. Our highest supported NodeJs version

Any browser testing is unrelated and can be handled separately.
