### ISSUE TITLE
Link, i18n is not export from '../i18n'

### ISSUE THREAD

**Issue by s0d-d** [isaachinman/next-i18next#488]
## Describe the bug

In `pages/index.js`, imported as 
`import { i18n, Link, withTranslation } from '../i18n'`

but I get Failed to compile error: 

```
./pages/index.js
Attempted import error: 'Link' is not exported from '../i18n'.
```

## Occurs in next-i18next version
^1.1.2

## Steps to reproduce

I installed next-i18next with `npm i next-i18next` command in my next.js project and my `i18n.js` file is copied from the example: 

```
import NextI18Next from 'next-i18next'

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de']
})

export default NextI18NextInstance

/* Optionally, export class methods as named exports */
export const {
  appWithTranslation,
  withTranslation,
} = NextI18NextInstance 
```

**Comment by isaachinman** [comment]
For general JavaScript questions, please post on StackOverflow.
