### ISSUE TITLE
Site Redirection based on Browser's language?

### ISSUE THREAD

**Issue by AhmedAbdulrahman** [isaachinman/next-i18next#489]
This is not a feature request or bug report, I would like to what is the best way to implement  redirection based on user's browser language. So if the use is visiting the browser from Japan how to redirect to JA version of site ? any example to check :) 

Thanks

**Comment by isaachinman** [comment]
Please post on StackOverflow or similar. This is an issue tracker, not a help forum. Thanks and good luck!
