### ISSUE TITLE
i18n.changeLanguage is not working properly with Next dynamic page

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#490]
## Describe the bug
Calling i18n.changeLanguage(foo) in dynamic page is not working properly. The language is changed but the url is not.

## Occurs in next-i18next version
version: 1.1.2

## Steps to reproduce
1. Open a dynamic page with localSubpath (eg. `/en/product/[id]`)
2. Calling i18n.changeLanguage('ge')

## Expected behaviour
- Language is change to 'ge'
- Url is changed to `/ge/product/[id]`
- No error

## Actual behaviour
- Language is change to 'ge'
- Url is not changed
- Get an error `Your <Link> 's as value is incompatible with the href value. This is invalid.`

## OS (please complete the following information)
 - Device: PC Windows 10
 - Browser: Chrome version 76.0.3809.132

**Comment by isaachinman** [comment]
Thanks for opening this. After reading through it, it does indeed seem to be the same problem as #413.
