### ISSUE TITLE
Allow to init with external resources

### ISSUE THREAD

**Issue by pedrobslisboa** [isaachinman/next-i18next#491]
## Is your feature request related to a problem? Please describe.
I have a project using local and external resources and I'm facing the problem to init the resources because the library forces me to use a unique localePath to set my resources, but I also have locales from another library. With 'pure' i18next we could do:

```
const extLocales  = require('library/locales');
const locales = {
   en: { ... },
   es: { ... },
}
//...
const resources = mergeDeep(...locales, extLocales)

i18next.init({
  lng: 'en',
  resources
}
```

but with localePath we cannot do such thing

## Describe the solution you'd like
It could be solved with the possibility to give manually the resources instead of localePath

**Comment by isaachinman** [comment]
This package simply passes the config options on directly to the i18next initialiser. Have you tried this setup?

I suggest you play around until you reach a point where `next-i18next` is blocking you in some way, and then we can proceed from there, once you have provided a specific bug report.

**Comment by pedrobslisboa** [comment]
Yeah, mah mistake. Maybe it could be more explicit on the README, I now that we have to try it, but since everyone that was working with me on it have the same doubt, it could have this on the documentation.

Thank you, @isaachinman and sorry to bother you

**Comment by isaachinman** [comment]
What exactly would you like to add to the README?
