### ISSUE TITLE
The changeLanguage will cause rerender

### ISSUE THREAD

**Issue by nuanyang233** [isaachinman/next-i18next#492]
## Describe the bug
My Application Page will save the language type in the localStorage when the user switch language.The purpose of this feature is to ensure that users do not need to switch languages again the next time they enter the page after switching languages.I do the changelanguage in `_app.js` 

```
// pages/_app.js 
componentDidMount() {
    const language = localStorage.getItem('language')
    if (language) i18n.changeLanguage(language)
  }
```

But it will cause the page Rerender and fetch Data.how can i fix it ?
## Occurs in next-i18next version

"next": "^9.0.5",
"next-i18next": "^1.1.2",

**Comment by isaachinman** [comment]
I suggest you look through the documentation [here](https://github.com/i18next/i18next-browser-languageDetector#detector-options) instead of trying to create your own implementation.

**Comment by nuanyang233** [comment]
Sorry, I can't understand you. Should I use the options written in the documentation you provided to pass into the config of the next-i18next constructor

**Comment by isaachinman** [comment]
Yes, exactly.
