### ISSUE TITLE
defaultLanguage not working on FireFox

### ISSUE THREAD

**Issue by Aledenn** [isaachinman/next-i18next#493]
defaultLanguage is zh-CN, but on FireFox the value is en
// i18n
```
const NextI18Next = require('next-i18next').default

const { localeSubpaths } = require('next/config').default().publicRuntimeConfig

const localeSubpathVariations = {
  none: {},
  foreign: {
    en: 'en',
  },
  all: {
    en: 'en',
    zh_CN: 'zh_CN',
  },
}

module.exports = new NextI18Next({
  defaultLanguage:'zh_CN', // 默认中文
  otherLanguages: ['en'],
  localeSubpaths: localeSubpathVariations[localeSubpaths],
})
```

on firefox
![image](https://user-images.githubusercontent.com/19233912/64256220-9629c380-cf55-11e9-84ad-74f7c5be67a2.png)

on chrome
![image](https://user-images.githubusercontent.com/19233912/64256183-7e523f80-cf55-11e9-8937-bcfda4b69413.png)

## Occurs in next-i18next version
   "next-i18next": "^1.1.2"

## OS (please complete the following information)
 - Device: MBP2018
 - Browser: Chrome 76.0.3809.132 FireFox 68.0.2

**Comment by isaachinman** [comment]
That is almost certainly due to your browser language setting. Please do let me know if that's not the case, and you've found a genuine bug.

**Comment by Aledenn** [comment]
thank u; 
```
request:
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
```
I change "zh_CN" to "zh-CN" and I fixed it;
