### ISSUE TITLE
No inputs were found in config file

### ISSUE THREAD

**Issue by arshdkhn1** [isaachinman/next-i18next#495]
<img width="684" alt="Screenshot 2019-09-06 at 3 07 53 AM" src="https://user-images.githubusercontent.com/16819670/64383993-8c868580-d053-11e9-921d-bda820c4404f.png">
No inputs were found in config file. I get this warning after installing next-i18next

**Comment by isaachinman** [comment]
Please provide the full error message and a way to reproduce it.
