### ISSUE TITLE
localeStructure not accounted for when searching for default namespace

### ISSUE THREAD

**Issue by hgezim** [isaachinman/next-i18next#496]
## Describe the bug

I'm getting this error `Error: Default namespace not found at /usr/src/app/static/locales/en/common.json` which is an invalid path because when initializing next-i18next, I set localeStructure as follows `{{lng}}/{{ns}}.{{lng}}` as follows:

```
const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['cs', 'de'],
  localeSubpaths: localeSubpathVariations['foreign'],
  fallbackLng: 'en',
  defaultNS: 'common',
  localeStructure: '{{lng}}/{{ns}}.{{lng}}',
  localePath: 'static/locales',
  localeExtension: 'json'
} as any)
```

The path it should be looking for is `/usr/src/app/static/locales/en/common.en.json`

## Occurs in next-i18next version
1.1.2

## Steps to reproduce
See above.

## Expected behaviour
I expected my directory structure and file name structure to work:

```
static/locales/cs:
common.cs.json

static/locales/de:
common.de.json

static/locales/en:
common.en.json
```

## OS (please complete the following information)
 - Device: iMac (27-inch, Late 2012)
 - Browser: Firefox 69

## Additional Context

Full stack trace:

```
 Error: Default namespace not found at /usr/src/app/static/locales/en/common.json
     at _default (/usr/src/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:54:15)
     at new NextI18Next (/usr/src/app/node_modules/next-i18next/dist/commonjs/index.js:52:46)
     at Object.<anonymous> (/usr/src/app/dist/server/i18n.js:14:27)
     at Module._compile (internal/modules/cjs/loader.js:816:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
     at Module.load (internal/modules/cjs/loader.js:685:32)
     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
     at Module.require (internal/modules/cjs/loader.js:723:19)
     at require (internal/modules/cjs/helpers.js:14:16)
     at Object.<anonymous> (/usr/src/app/dist/server/server.js:12:30)
```

**Comment by isaachinman** [comment]
@hgezim The offending line can be found [here](https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L39).

Feel free to contribute a fix, accompanied by test coverage.

**Comment by radeno** [comment]
@hgezim i had PR but was closed. Just use symlink as i do.

**Comment by isaachinman** [comment]
@radeno That PR was unrelated to this issue.

**Comment by radeno** [comment]
@isaachinman it was related. Same behaviour as `dir` property in next-js https://github.com/zeit/next.js/#custom-server-and-routing

Then there is also no need to overwrite `loadPath` and `addPath` paths for backend, if you set where your app sources are located.

**Comment by isaachinman** [comment]
@radeno Your PR is unrelated, and the bug described in this issue would still occur given your diff. Let's stay on topic.

**Comment by radeno** [comment]
@isaachinman you are right about issue. sorry

**Comment by ashtagged** [comment]
Any action on this? I'm facing same issue.

**Comment by isaachinman** [comment]
> Feel free to contribute a fix, accompanied by test coverage.

**Comment by phakphumi** [comment]
I have tried to find out for half of the last day what am I doing wrong about changing the localeStructure?

LOL

**Comment by isaachinman** [comment]
@hgezim Any update on this issue? After taking a second look, it seems likely that your `{{lng}}` param is simply not being replaced in the second occurrence.

**Comment by hgezim** [comment]
@isaachinman I'm unclear on what you want me to check.

**Comment by isaachinman** [comment]
@hgezim The relevant source code is found [here](https://github.com/isaachinman/next-i18next/blob/b0c22994fea8e59360025e70ae5ea0eee27561ec/src/config/create-config.ts#L48).
