### ISSUE TITLE
Extended withNamespaces not delivering up-to-date t prop

### ISSUE THREAD

**Issue by isaachinman** [isaachinman/next-i18next#5]
As demonstrated in the [example here](https://github.com/isaachinman/next-i18next/blob/master/example/pages/index.js#L12), I'm currently having to pass the current lang from `this.props.lng` into the `t` function to get [this extended version of withNamespaces](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/with-namespaces.js) to work correctly after a language change.

**To reproduce:**

1. Clone the repo
2. Do `yarn && yarn run-example`
3. Open a browser to `localhost:3000`
4. Reload a few times, observe behaviour
5. Press the button to change language
6. Do a reload - SSR language will be incorrect, and client will correct it

It's important to note that both `initialLanguage` and `initialI18nStore` appear to be correct during this SSR process, it's _just_ the `t` function that is returning a translation in a different language than the current language. This is why overriding the current lang to `this.props.lng` works.

Somehow, either via the context provided by `I18nextProvider`, or some other reason, the reference that `withNamespaces` has to the current lang is not being updated. It could be that there are multiple i18n instances existing simultaneously that I'm not aware of.

I'm quite sure this is user error on my part, but @jamuhl if you had a short moment to check this out and let me know what you think, I would be very grateful.

**Comment by jamuhl** [comment]
@isaachinman will take a look when back home later today.

**Comment by jamuhl** [comment]
@isaachinman ok i guess i found the cause...

https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L30

You set the language on the one main instance used on server and pass that to the `I18nextProvider`. There is a second place `i18next.translator.language` which is the language really used for translations  (so a i18next.changeLanguage triggers a change there too: https://github.com/i18next/i18next/blob/master/src/i18next.js#L187)

So adding:

```js
if (req && req.i18n) {
        [initialLanguage] = req.i18n.languages
        i18n.language = initialLanguage
        i18n.translator.language = initialLanguage // <--- this
        req.i18n.languages.forEach((l) => {
        // ...
```

Will make it work...but honestly i'm not sure this is a good idea. If i see it right: https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L7 is not the i18n instance req.i18n but just something like require('i18next')....right?

If so any async process done during rendering leads to a chance that the language on that main instance gets changed by another request - this is why the req.i18n is always a own cloned instance.

**Comment by isaachinman** [comment]
@jamuhl The i18n instance in `app-with-translation` is the instance initialised with user options. It's bound to the `app-with-translation` function as `this.i18n` [here](https://github.com/isaachinman/next-i18next/blob/master/src/index.js#L12).

This should be the exact same setup as the [working NextJs example](https://github.com/i18next/react-i18next/blob/master/example/nextjs/pages/_app.js)... Not sure what is different here.

What would be wrong with setting `i18n.translator.language`? But that aside, why is it not updating on its own? It seems as though `withNamespaces` is consuming / connected to a different i18n instance than expected.

**Comment by jamuhl** [comment]
ah...didn't catch that in the example...

setting i18n.language does not set language on translator -> only calling i18n.changeLanguage does.

the problem with setting that is...requests are asynchronous...as long you do no async data fetching during SSR there won't be any issue...as long there are not a lot of request there is no issue - but if there are:

- req1 -> set lng to "de" -> calls fetch data -> waits for callback
- req2 -> set lng to "fr" -> calls fetch data -> waits for callback
- req1 gets data -> starts rendering -> i18n.language = "fr" as it was set by req2 

so it will work in development and brake in production

**Comment by isaachinman** [comment]
Yes, I understand that. The language is being changed on the client via `i18n.changeLanguage`, and then on the next full reload, the SSR process does not respect the newly set language - despite the cookie being changed correctly, etc.

> It's important to note that both initialLanguage and initialI18nStore appear to be correct during this SSR process, it's just the t function that is returning a translation in a different language than the current language.

Anyways, I will keep looking into it now.

**Comment by jamuhl** [comment]
like said you will need to set i18next.translator.language too, if not using changeLanguage like here: https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L30

regarding the express requests: https://github.com/i18next/i18next-node/blob/master/test/i18next.server.reqCollision.spec.js#L80 that was a test in v1 asserting that we get right results

**Comment by isaachinman** [comment]
Okay, I understand. Doing an `await i18n.changeLanguage(initialLanguage)` seems to work fine. Curious as to how this is not broken in [the example](https://github.com/i18next/react-i18next/blob/master/example/nextjs/pages/_app.js#L72) for the `react-i18next` repo though.

**Comment by jamuhl** [comment]
believe it's broken there too -> we just not noticed yet as not in production and no async data fetching in the sample (no apollo or similar) --- at least we would have a problem if react.renderToString is not synchron (as i'm not an expert on that i'm not sure - but i guess it does not block as that would kill server performance)

eventual we lost using req.i18n down the road of updates: https://github.com/i18next/react-i18next/blob/v8.0.0/example/nextjs_withAppJS/i18n.js#L54

**Comment by isaachinman** [comment]
I am not so sure what you mean about async fetching. We can do any async actions inside NextJs's `getInitialProps`, and that will all happen before any `renderToString` calls.

This package is getting close to being ready for initial testing by the way, if you feel like trying it out. Even after spending several weeks now focusing on NextJs and `react-i18next`, I still do not feel as though I am an expert at all, and can always use your advice!

There are definitely some smaller problems I've noticed already (including "codesplitting" namespaces when using ES modules, etc) that don't necessarily need to be solved ASAP. I want to start with a solid base first.

Sometime soon I will also add a `withI18nRouter` method to the class to support routing via props as well.

**Comment by jamuhl** [comment]
sounds awesome. Yes, i can help with the react-i18next part - and with testing. For nextjs i always got a  less comfortable feeling...i feel save when i use this things myself in production at some point - just doing samples always leave me with the feeling i might have missed something.

**Comment by jamuhl** [comment]
@isaachinman we got the same issue on the react-i18next/example/nextjs when we upgrade react-i18next to latest...

steps:
- toggle client language so it is de
- refresh the page

=> the serverside render will show en while client will show correctly de

the commit causing it: https://github.com/i18next/react-i18next/commit/2028d0ae3d96c5988dfca276f5424c4b87ea1d56

Not sure why setting language again and again fixes it - as that seems wrong. Not sure but guess the problem is related to mixing req.i18n and the global instance on serverside.

I really would say this: https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L78 should be req.i18n

**Comment by isaachinman** [comment]
Ah yeah. Same fix as what I did for [next-i18next](https://github.com/isaachinman/next-i18next), we simply need to use `changeLanguage` instead of mutating the object directly. Example can be seen here:

https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L44

I'll submit a PR for this repo shortly.
