### ISSUE TITLE
Extendig React config overwrites default configuration

### ISSUE THREAD

**Issue by MiguelFreire** [isaachinman/next-i18next#502]
## Describe the bug
When creating the i18NextInstance with react-i18n config the default values such as "wait" and "useSuspense" are overwritten by the config merge. 

## Occurs in next-i18next version
v1.2.0

## Steps to reproduce
When creating the i18n instance just pass the following config:
``` const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['es'],
  react: {
    transKeepBasicHtmlNodesFor: ['br', 'strong', 'i', 'p', 'b'],
  },
})
```

## Expected behaviour
useSuspense should be false by default even when you add additional configuration to react-i18next

## OS (please complete the following information)
 - Device: MBP 2017 13
 - Browser: Chrome 76.0.3809.132

**Comment by isaachinman** [comment]
We won't deep merge objects. If you want to get into advanced configs you'll need to provide your full config as you would to `react-i18next`.
