### ISSUE TITLE
Translation not used, if key has a period in it

### ISSUE THREAD

**Issue by stevewillard** [isaachinman/next-i18next#508]
## Describe the bug
If you have a locale, for example: `static/locales/en/common.json`
```
{
    "Do something.": "here!",
}
```
If the key has a `.` (period) in it, the string doesn't translate properly.

## Occurs in next-i18next version
`1.2.0`

## Steps to reproduce
See the JSON above

## Expected behaviour
The string is translated.

**Comment by isaachinman** [comment]
Sounds like an upstream issue. Can you open a bug report in `react-i18next`?

**Comment by serranoarevalo** [comment]
If anyone stumbles upon this, I found the solution here: https://github.com/i18next/i18next/issues/1060#issuecomment-394100024
