### ISSUE TITLE
Is cimode supported?

### ISSUE THREAD

**Issue by keethu24** [isaachinman/next-i18next#510]
Does the library support `cimode`? If yes, how to configure it with `next-i18next` properly?

**Comment by isaachinman** [comment]
The `config` object is passed directly into the i18next constructor. So yes, anything i18next supports is supported here.

**Comment by andfk** [comment]
I've tried with version `6.0.1` and using `cimode` tries to get the translations files so it throws an error. Something somewhere is not handling such option correctly

**Comment by isaachinman** [comment]
@andfk Feel free to debug and let me know what you think the problem is.
