### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by sb-bilal-dev** [isaachinman/next-i18next#511]
## Is your feature request related to a problem? no.
Not finding any typescript example spent about ten hours trying to integrate simple example to my typescript project.

## Describe the solution you'd like
Add with-typescript to examples directory.

## Additional context
I already manage to add it with typescript; can handle this issue myself.

**Comment by isaachinman** [comment]
The main concern with this is duplication of language, and unnecessary dev overhead for maintaining a separate build process in that sort of example.

In reality there is very little difference in implementation and it should absolutely not take ten hours if you have experience with TypeScript.

Please do feel free to share a link to your repo though, I am sure it will be very helpful to others!
