### ISSUE TITLE
Keys are displayed in a moment

### ISSUE THREAD

**Issue by youkyll** [isaachinman/next-i18next#513]
## Describe the bug
Keys are displayed in a moment at first on client side and then correct words are rendered,  even if words are rendered correctly on server side.
According to debug log, it seems that keys are rendered before the i18next is initialized and namespaces are loaded by i18n backend connector.

## Occurs in next-i18next version
next-i18next: 1.2.1
next: 9.0.6

## Steps to reproduce
I set it up in accordance with project setup on the README. Nothing else is changed.

## Expected behaviour
I would not like to display keys, only display words.

## Screenshots
debug log
![image](https://user-images.githubusercontent.com/5962244/65481340-e6020780-decf-11e9-80b5-261bd142e2b8.png)

## OS (please complete the following information)
 - Device: MBP 2018 "13"
 - Browser: Chrome 76.0.3809.132

Thank you for reading this.

**Comment by isaachinman** [comment]
You'll need to provide a repo.

**Comment by youkyll** [comment]
I created the sample below.
https://github.com/youkyll/next-i18next-testing

debug info says below
![image](https://user-images.githubusercontent.com/5962244/65486057-6d567780-dede-11e9-927b-cde2a40b6845.png)

**Comment by isaachinman** [comment]
You don't appear to be using the `next-i18next` middleware.

**Comment by mqtik** [comment]
Isn't the middleware deprecated?

**Comment by isaachinman** [comment]
Yes, but it was not when I wrote that comment.
