### ISSUE TITLE
Type 'TFunctionResult' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by sb-bilal-dev** [isaachinman/next-i18next#515]
Why is TFunctionResult is not assignable to 'string'?
I have to pass it as {t("my-translation") as string} as a workaround.
Does anyone know any other workarounds?

**Comment by isaachinman** [comment]
If you search across this entire repo for `TFunctionResult`, you will not find it. I suggest you open an issue in the appropriate repo.

**Comment by vitalix89** [comment]
I passed type string to t function as t is generic function like this -> {t<string>("my-translation") }

**Comment by nazimjamil** [comment]
I ended up specifying t as `any` to get past this issue. No idea why it is happening and it's also not happening for all translation usage in the entire app, just a few spots.
```
const { t }: { t: any } = useTranslation()
```

**Comment by mugwump** [comment]
It happened to us after an update of several libs, we're still trying to figure out, what's the underlying cause here, as this code has compiled this way before....

**Comment by omonk** [comment]
@mugwump - root declaration is here https://github.com/i18next/i18next/blob/master/index.d.ts#L653

**Comment by omonk** [comment]
Also this comment might be of some interest? https://github.com/i18next/i18next/issues/1504#issuecomment-742727015

**Comment by karladler** [comment]
It depends how you define your `children` prop type of the wrapping component. If you use ReactNode it's not complaining anymore, because it also allows `null` and `undefined` as children.

minimal example wrapper component
```typescript
import React from 'react';

interface Props {
  children: React.ReactNode;
}

function MyComponent({ children }: Props) {
  return (<div>{children}</div>);
}

export default LoadingButton;
```

**Comment by alkismavridis** [comment]
Also affected. Problem started after updating some libs (specifically, material-ui).
The error only occurs on some instances only, particularly the ones where the result is passed to a MaterialUIComponent prop:`<FormControlLabel label={t(...)} >`

**Comment by kitsunekyo** [comment]
isnt this just wrongly typed? even if the key cannot be found, the function will just return the translation key, which is just a string. or am i missing something?

**Comment by ConcernedHobbit** [comment]
> isnt this just wrongly typed? even if the key cannot be found, the function will just return the translation key, which is just a string. or am i missing something?

With `returnObjects` set to true, `t()` can return an array or an object, which probably shouldn't be blindly cast to string. You're correct in that the base `t()` without `returnObjects` set to true will always return a string (even if it's just `key 'example' returned an object instead of a string`)

Technically `i18next` could be typed with conditional typing to return a `string` when `returnObjects` is not set, but it would be hard to make work with global settings (i.e. `init({ returnObjects: true })`.

Ref: 
https://www.i18next.com/translation-function/objects-and-arrays
https://www.i18next.com/overview/api#init

**Comment by ludalex** [comment]
I'm having luck with the workaround suggested [here](https://github.com/i18next/next-i18next/issues/1781#issuecomment-1092620082) by @heikomat
