### ISSUE TITLE
defaultLanguage not work

### ISSUE THREAD

**Issue by BoChao-Hsu** [isaachinman/next-i18next#516]
## Describe the bug
When I set defaultLanguage and start a new browser, I find that the default language is always en
![image](https://user-images.githubusercontent.com/34178564/65653785-0dc8ab00-e049-11e9-9720-c459ffd57a6c.png)

**Comment by isaachinman** [comment]
I think you want to disable browser language detection. This is an issue tracker, not a help forum.

**Comment by BoChao-Hsu** [comment]
no .. defaultLanguage set "zh_TW" not work for me

**Comment by Lexiwu** [comment]
I got same problem, even I disable browser language detection!

**Comment by isaachinman** [comment]
What headers is your browser sending? Do you have server language detection set to look for headers?

Please post on StackOverflow or similar.
