### ISSUE TITLE
Middleware causes server.js to hang

### ISSUE THREAD

**Issue by 0x54321** [isaachinman/next-i18next#521]
## Describe the bug
I have a custom server, and added the `server.use(nextI18NextMiddleware(nextI18next));` middleware, as instructed. But this just causes the server to hang; apparently it never gets to `server.listen`.

## Occurs in next-i18next version
1.2.1

## Steps to reproduce
Here are the relevant portions of my server.js file:

```
const nextI18NextMiddleware = require("next-i18next/middleware").default;
const nextI18next = require("./utils/i18");
```
...
```
app.prepare().then(() => {
  const server = express();
  const { Sentry } = require("./utils/sentry")(app.buildId);

  server.use(Sentry.Handlers.requestHandler());
  server.use(cookieParser());
  server.use(sessionCookie);

  server.use(nextI18NextMiddleware(nextI18next));

  server.get(...
```

## Expected behaviour
Expected the middleware to process normally. 

## OS (please complete the following information)
 - Device: MacBook Pro
 - Browser: N/A

## Additional context
I'm using babel/register to transpile my server.js file, if that makes any difference.
I tried changing the position of the middleware in the file, but it made no difference.

**Comment by isaachinman** [comment]
Hi there. We have end to end tests which perform assertions against the example directory whilst it's running.

Therefore, by definition, the code you see in `examples/simple` is functional.

If you believe you've found a bug, you will need to provide an actual bug report.

**Comment by 0x54321** [comment]
@isaachinman, thanks for your response.

Most likely I am doing something wrong, or my setup is atypical in some way. I'm looking for some some guidance on how to troubleshoot this issue. Any advice would be greatly appreciated.

Thanks!

**Comment by isaachinman** [comment]
Best to post on StackOverflow or similar. Good luck!
