### ISSUE TITLE
How we can set language json file from S3 in localePath?

### ISSUE THREAD

**Issue by jashan-preet-singh-dhanoa** [isaachinman/next-i18next#526]
I am trying to load language JSON file from S3 AWS. I have tried to set localePath as 
localePath: "https://xxx.s3.amazonaws.com/v2/locales", 
localeStructure: "{{lng}}/{{ns}}"

But it did not work, Is it feasible to load locales language file from the S3 server? If so How we can achieve it

Please suggest,

**Comment by isaachinman** [comment]
This question has been asked and solved many times. Please search around.

**Comment by jashan-preet-singh-dhanoa** [comment]
Can you please provide some links.  Where the issued is fixed.
