### ISSUE TITLE
Use translation (tFunction) in _document

### ISSUE THREAD

**Issue by jankarres** [isaachinman/next-i18next#527]
I have integrated this well done package into a project. So far a very good experience. But there is one thing for which I haven't found a solution.

I integrated `appWithTranslation` into the `_app.tsx` (see code below). If I use a page in `pages/` with `withTranslation()` or a component nested inside a page, it works fine. But I want to use a wrapper for all the pages in `_document.tsx`. Elements (e.g. header or footer) regardless of the page content should be rendered. That's why I created an (example) `layout.tsx` and used the HOC `withTranslation()`.

Current: The `i18n` object, the `t` function and the `tReady` value are passed to the `Layout` component. `tReady` is `true`. However, the `t` function does not translate the keys of the selected namespace.

Current: The `i18n` object, the `t` function and the `tReady` value are passed to the `Layout` component. `tReady` is `true`. The `t` function translates the key of the selected namespace.

I tried debugging it myself, but did not find the case of this behavior. But maybe this could be intentional. I am grateful for any help :)

_app.tsx
```
import App from "next/app";
import { appWithTranslation } from "../i18n";

class MyApp extends App {
  public render() {
    const { Component, pageProps } = this.props;

    return <Component {...pageProps} />;
  }
}

export default appWithTranslation(MyApp);
```

_document.tsx
```
import React from "react";
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentContext,
  DocumentInitialProps
} from "next/document";

import Layout from "../components/layout";

class MyDocument extends Document {
  public static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps> {
    let initialProps = await Document.getInitialProps(ctx);

    return { ...initialProps };
  }
  public render() {
    return (
      <Html>
        <Head />
        <body>
          <Layout>
            <Main />
          </Layout>
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

layout.tsx
```
import React, { Fragment } from "react";
import { withTranslation, IWithTranslation } from "../../app";

interface IProps extends IWithTranslation {}


const Layout: React.FC<IProps> = (props) => {
  const { t, children } = props;

  return (
    <Fragment>
      <div>
        <header>{t("helloWorld")}</header>
        <main>{children}</main>
        <footer>© {new Date().getFullYear()}</footer>
      </div>
    </Fragment>
  );
};

export default withTranslation("common")(Layout);
```

**Comment by isaachinman** [comment]
You cannot render translated content from `_document.tsx`, because that would be outside the i18next provider. You need to render translated content from within children of `_app.tsx`, or come up with another solution.

Hope that helps.

**Comment by jankarres** [comment]
I have found a little hacky solution. From my first impression I can not recognize any disadvantage, if the provider is (with this hack) a HOC of `_document`.

layout.tsx
```
import React from "react";
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentContext,
  DocumentInitialProps
} from "next/document";
import { Request } from "express";

import Layout from "../components/layout";

import { I18nextProvider } from "react-i18next";

interface IProps {
  i18nInstance: any;
}

class MyDocument extends Document<IProps> {
  public static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps & IProps> {
    let initialProps = await Document.getInitialProps(ctx);

    let i18nInstance = null;
    const req = ctx.req as Request;
    if (req && req.i18n) {
      i18nInstance = req.i18n;
    }

    return { ...initialProps, i18nInstance };
  }

  public render() {
    const { i18nInstance } = this.props;

    return (
      <I18nextProvider i18n={i18nInstance}>
        <Html>
          <Head />
          <body>
            <Layout>
              <Main />
            </Layout>
            <NextScript />
          </body>
        </Html>
      </I18nextProvider>
    );
  }
}

export default MyDocument;
```

**Comment by isaachinman** [comment]
Yes, that's fine.

**Comment by jankarres** [comment]
What's the reason for the behaviour of `next-i18next` that it provides a HOC for `_app` and not for `_document`? In my opinion it makes much more to provide a HOC for `_document` instead of for `_app`.

If this behaviour is wished, I can prepare a PR @isaachinman.

**Comment by isaachinman** [comment]
Hi @jankarres. The `_document` override only executes on the server - that's what it's for. We need our HOC to wrap in a universal way, because we have both client and server side behaviour.

Your "hacky solution" above will work for SSR, but will not work if you enter that route on the client side.

In my opinion, you should not be putting actual content inside `_document`.

Can you use your `Layout` component in `_app`? It'll be within the provider at that level. Best of luck!

**Comment by jankarres** [comment]
Thanks for the explanation. To use the `Layout` component in the `_app` file instead of in `enhanceComponent` (see: https://github.com/zeit/next.js/#customizing-renderpage) or as HOC of each page was exactly the solution I was looking for. With this position to inject the `Layout` component no flickering effect appears and translations are available.

Thanks again for your support :)

**Comment by symi** [comment]
Hi @isaachinman is it possible to use the tFunction within `_app` itself? Rather than having to nest another layout component beneath it? 

i.e if I wanted to use a translation in the render function of _app itself.
```
return (
  <header>t('some.tag')</header>
  <Component { ...pageProps } />       
);
```

Using the standard setup from the sample project with a call to `appWithTranslation` wrapping the custom _app component.

**Comment by symi** [comment]
nevermind answered my own question `appWithTranslation(withTranslation('common')(MyApp))`
