### ISSUE TITLE
Allow to specify custom browser and server dectors

### ISSUE THREAD

**Issue by carlosds731** [isaachinman/next-i18next#531]
## Is your feature request related to a problem? Please describe.
Every language detector in the array of custom detectors is added to both browser and server detectors. It causes a problem because they do not share the same API.

Server detectors should implement two functions, with the following API:

````typescript
lookup: function(req, res, options) {
    // options -> are passed in options
    return 'en';
  },

cacheUserLanguage: function(req, res, lng, options) {
    // options -> are passed in options
    // lng -> current language, will be called after init and on changeLanguage

    // store it
  }
````

(described [here](https://github.com/i18next/i18next-express-middleware#interface))

while browser detectors should use:

````typescript
lookup(options) {
    // options -> are passed in options
    return 'en';
  },

cacheUserLanguage(lng, options) {
    // options -> are passed in options
    // lng -> current language, will be called after init and on changeLanguage

    // store it
  }
````

(taken from [here](https://github.com/i18next/i18next-browser-languageDetector#interface)).

## Describe the solution you'd like
I would like to be able to specify a collection of server detector and browser detectors, for instance, I would like to initialize the NextI18Next library like this

````typescript
export const nextI18next = new NextI18Next({
    defaultLanguage: LANGUAGES.ENGLISH,
    otherLanguages: [LANGUAGES.SPANISH],
    customServerDetectors: [myCustomServerDetector],
    browserServerDetectors: [myCustomBrowserDetector]
    /* other options */   
});
````

## Describe alternatives you've considered
I've tried to write universal detectors but the code gets confusing, especially with `cacheUserLanguage` because you need to do stuff like this

````typescript
if (!isNode){
    const _lng = req;
    const _options = res;
}
````

**Comment by isaachinman** [comment]
Can't you just populate the `customDetectors` array based on env?

**Comment by kachkaev** [comment]
Perhaps, my example could help answering your question @carlosds731 

* https://gitlab.com/kachkaev/website-frontend/blob/dc2ca9958f30867c66fa8bec1313b1fa90d7f729/src/i18n.ts

* https://gitlab.com/kachkaev/website-frontend/blob/dc2ca9958f30867c66fa8bec1313b1fa90d7f729/next.config.js#L21-22

**Comment by carlosds731** [comment]
Ok @kachkaev I'll use that approach. Thanks
