### ISSUE TITLE
Language lookup, req.language and valid language mismatch

### ISSUE THREAD

**Issue by martpie** [isaachinman/next-i18next#532]
## Describe the bug

It's a bit tricky and I hope I will describe this issue well. It is not a *bug* per se, but more an issue.

In the "Access current language section", it is said to use the following snippet to get the current language:

```js
const currentLanguage = req ? req.language : i18n.language
```

The problem is `req.language` may not be a whitelisted/valid language. Having a look at `i18next-express-middleware`'s code, `req.language` is set based on the user language, independently from what the valid languages of your app are:

- https://github.com/i18next/i18next-express-middleware/blob/ea4989b183b31ad5bd58e7a6b71300f722f45cd5/src/index.js#L21
- https://github.com/i18next/i18next-express-middleware/issues/139#issuecomment-342465691
- https://github.com/i18next/react-i18next/issues/797#issuecomment-476073445

I would expect a way to get the first valid language in `i18n.languages` for the given `req.language` instead of using `req.language` directly, which may be `en-US` for example, when the app can just accept `en` due to `load: languageOnly`.

## Occurs in next-i18next version
 
`1.2.1`

## Steps to reproduce

Any setup, where `xx-XX` `accept-language` header is set before `xx`

## Expected ~behaviour~ snippet

Any way to get the valid lang the page will be actually rendered with

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: MBP 2016 13'
 - Browser: Chrome (but reproducible with any browser

## Additional context
n/a

**Comment by isaachinman** [comment]
Sure, feel free to submit a PR updating the docs. That's not a bug though - ultimately it's up to the end user to consume i18next in whatever way they feel is necessary.

**Comment by martpie** [comment]
cool, I'll have a deeper look at how to solve this issue 🤔

**Comment by martpie** [comment]
Quick question, is it normal that with:

```
{
  defaultLanguage: 'fr',
  otherLanguages: ['de', 'it']
}
```

I get `preload: [ 'de', 'it', 'fr', 'fr-FR' ],` server-side on some browser?

**Comment by isaachinman** [comment]
Not sure what you mean exactly, but the `preload` array is set [here](https://github.com/isaachinman/next-i18next/blob/7ac73e62005c4b8777530be514ab8cc4473be902/src/config/create-config.ts#L53).
