### ISSUE TITLE
Add localsubpath to url in react-i18next like in next-i18next

### ISSUE THREAD

**Issue by shakesBeardZ** [isaachinman/next-i18next#534]
(I know it's not the right place but no one answered me in stackoverflow and in react-i18next repo ,  I'll be thankful if anyone can help)
I'm trying to show the current language in the URL when using react-i18next like: example.com/en , I'm used to that in next-i18next, example:

```
new NextI18Next({
  localeSubpaths: {
    fr: 'fr',
    de: 'german',
    en: 'eng',
  }
})
```

**Comment by isaachinman** [comment]
Not sure what you're even asking. There is no subpath functionality in `react-i18next`.
