### ISSUE TITLE
Specify namespacesRequired without getInitialProps

### ISSUE THREAD

**Issue by ckeeney** [isaachinman/next-i18next#544]
Specifying namespacesRequired is optional, but recommended for performance reasons.  Currently, the only way to set `namespacesRequired` is from `getInitialProps`.  

There are several pages in my projects that only have a `getInitialProps` to specify `namespacesRequired`, and [using `getInitialProps` prevents `next.js` from performing automatic static optimization and pre-rendering HTML](https://nextjs.org/docs#automatic-static-optimization).

This makes it unclear which has better performance:
 - setting `namespacesRequired`, only sending the fewest translations required to the page, but sacrificing static optimization
- Not setting `namespacesRequired`, sending all the translations to the page but letting next.js perform static optimization and prerender the HTML.

I think it's worth considering exposing `namespacesRequired` with static properties on the page.  [`hoist-non-react-statics`](https://github.com/mridgway/hoist-non-react-statics) may be helpful in this instance.

**Comment by isaachinman** [comment]
As far as I'm aware, there's currently no way to prerender anything unless you split your different languages into different files, etc. Localisation happens per request and therefore cannot be prerendered.

This could change in the future, I suppose.

A static is an interesting idea. I think I tried to implement it that way originally, but recall running into some problems. If you want to work on a PR, I would be happy to take a look at that and merge it if it seems sensible.

**Comment by ckeeney** [comment]
I didn't realize `appWithTranslation` adds a [`getInitialProps`](https://github.com/isaachinman/next-i18next/blob/7ac73e62005c4b8777530be514ab8cc4473be902/src/hocs/app-with-translation.tsx#L68-L156) to `_app.js` anyways.  

`next-i18next` needs to do a lot of processing on the request object here so I don't know if it is possible to do all this without `getInitialProps`, but maybe with the `userRouter` hook or the `withRouter` hoc.

Eliminating `getInitialProps` is a much bigger undertaking than I thought when I opened this issue and I am probably not going to contribute a PR for this feature in the near future. 

Feel free to close this issue if you like, it really isn't critical but there are performance compromises made when `getInitialProps` is used and it may be worth leaving the issue open for discussion.

**Comment by ebs12345** [comment]
--- render happens ----
i18next::translator: missingKey de common search_btn_name search_btn_name
i18next.js:27 i18next::translator: missingKey de common plhd_location plhd_location
i18next.js:27 i18next::translator: missingKey de common home_available_jobs home_available_jobs
i18next.js:27 i18next::translator: missingKey de common home_section1_title home_section1_title
i18next: languageChanged en
i18next: initialized { debug: true /* .. */ }
how to do i fix missing key value issues .

**Comment by mercteil** [comment]
This is actually the most interesting question for this package at the moment.

Next introduced the new bomb ass static methods that can separately handle different pages as static, dynamic and in between as long as _app.js has no getInitialProps set.

Unfortunately the only package I basically need getInitialProps in _app.js for is next-i18next and `namespacesRequired`... 

We should definitely work on a solution to be able to stay up-to-date with the newest Next.js features.

I will try to take a look.

**Comment by isaachinman** [comment]
This package will eventually be converted into a NextJs plugin once that functionality lands.

**Comment by janus-reith** [comment]
Maybe close this, IMHO it's misleading for people searching with a similar issues, as there would probably be no performance gain by removing getInitalProps from each page, as it still is present on _app as discussed. #586 is closer to the actual concern here, which is static optimization.

**Comment by ckeeney** [comment]
@janus-reith agreed.  Closed and discussion moved to #586, though that title could be improved.
