### ISSUE TITLE
Warning: Text content did not match. Server: "AR" Client: "EN"

### ISSUE THREAD

**Issue by sanishkr** [isaachinman/next-i18next#545]
## Describe the bug
The locales appear on the screen for a split of a second and then goes away.

## Steps to reproduce
https://github.com/sanishkr/next-tailwind-styled-components.git
npm i
npm run dev
http://localhost:3000/ar/page2

## Expected behaviour
All translated locales in Header and ArticlelList

## OS (please complete the following information)
 - Device: [Mac Catalina]
 - Browser: [Chrome Latest]

**Comment by isaachinman** [comment]
The repo you've linked is far too complex to debug. Please provide a simple repro, or explain your issue in more detail.
