### ISSUE TITLE
Add support for fully localized routes

### ISSUE THREAD

**Issue by jm18457** [isaachinman/next-i18next#547]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

Current implementation supports locale subpaths by adding a prefix, but does not support fully localized urls.

```
// What is currently
/en/product
/de/product

// What would be improvement
/en/product
/de/produkte
```

## Describe alternatives you've considered
I was thinking of trying with something combined with `next-routes`

## Additional context
If this feature is in roadmap or does not go against any current plans, I can make a pull request when I make if I can.

**Comment by isaachinman** [comment]
See #199.

If you're not satisfied with that, please explain what you're hoping to see.

**Comment by jm18457** [comment]
Yes, I know we can write custom handler.

I was hoping to have it integrated within next-i18next initialization.

```
new NextI18Next({
  localeSubpaths: {
    en: 'en',
    de: 'de'
  },
  localeRoutes: {
    // this would be an ID of some kind
    product: {
      en: 'product',
      de: 'produkte'
    }
  }
})
```

Now in code we would `<Link href="/produkt" />` while language would be `de` and it would redirect to `/de/produkte`

**Comment by isaachinman** [comment]
Sorry, I do not foresee that happening. That's getting into an area which is way too opinionated. If you have localised routes, why do you need locale subpaths? How would we handle this sort of automatic linking you're proposing?

In general, nearly every single user is going to have different business requirements when it comes to routes/URLs, and it's simply easier if those users roll it themselves.

Open to simple solutions, of course, but I don't see any.

**Comment by jm18457** [comment]
We need locale subpaths with localization, because what happens when URL has same translation in different languages.

This package is already handling locale subpaths `Link` as we dont have to `<Link href='/en/producte' />`

**Comment by LucasMatuszewski** [comment]
Hi

I have quite similar problem and I tried to solve it with Custom Routes in server.js file.

My routes used to work fine with Next.js 8 and react-i18next, but when I switched to **Next.js 9.1** and next-i18next I found few issues on routes which are not equal to `/page/fileName.js`
1. When I click on the Link to go to other page I see full page reload on browser (just like when I click normal `<a>` link)
2. My Context user data is gone (or rather React creates new empty context) and user is logged out. But when I come back to home page, after another full page reload I have user data back in Context.

My example routes:
`/trainers` (EN, works fine, equal to file name `/pages/trainers.js`)
`/trenerzy` (PL, server.js custom route)

My server.js route:
```
// TRAINERS
    const getTrainersList = (req, res) => {
      return app.render(req, res, '/trainers');
    };
    // server.get('/trainers, getTrainersList); // en (path = page file name = default route)
    server.get('/trenerzy', getTrainersList); // pl
```

My Component with Link (from /i18n.js) and custom path as a string (send from parent in props):
```
        <Link href={`/${actionButtonUrl}`}>
          <a className="noUnderline">
            <Button variant="outlined">{actionButtonTxt}</Button>
          </a>
        </Link>
```

When I use /trainers it works fine:
```
        <Link href={'/trainers'}>
          <a className="noUnderline">
            <Button variant="outlined">{actionButtonTxt}</Button>
          </a>
        </Link>
```

Do you have some examples / clues how to do it correctly with next-i18next ?

**Comment by isaachinman** [comment]
@LucasMatuszewski It sounds like there may be a mismatch between your server routes and client side routes. You may need to use the `as` prop in your `Link` components, or debug your client side router.

**Comment by simplenotezy** [comment]
Although I'm aware this has been asked multiple times, I still think it could be quite helpful, and there defiantly exist ways that other frameworks, such as Nuxt.js have done. How they do it, is pretty similar to what's been suggested here.

Have a look at: https://i18n.nuxtjs.org/routing/#modules-configuration

```
['nuxt-i18n', {
  parsePages: false,   // Disable babel parsing
  pages: {
    about: {
      en: '/about-us', // -> accessible at /about-us (no prefix since it's the default locale)
      fr: '/a-propos', // -> accessible at /fr/a-propos
      es: '/sobre'     // -> accessible at /es/sobre
    }
  }
}]
```
