### ISSUE TITLE
localExtension in JavaScript doesn't work 

### ISSUE THREAD

**Issue by Pierre-CLIND** [isaachinman/next-i18next#548]
## Describe the bug
localExtension in JavaScript doesn't work on client side.

## Occurs in next-i18next version 2.0

**Using:**

- "next": "^9.1.2",
- "next-i18next": "^2.0.0",
- "react": "^16.11.0",

- node v12.13.0

## Steps to reproduce
Using the sample source, with `localeExtension: 'json'`, everything works but using `localeExtension: 'js'` not.

**My locale file**

Json:
```
{
  "description": "This is a non-page component that requires its own namespace"
}
```

JS:
```
module.exports = {
  "description": "This is a non-page component that requires its own namespace"
}
```

## Expected behaviour
localeExtension works on the same way with json or js

## Screenshots
**SSR or in json:**

![image](https://user-images.githubusercontent.com/56550362/68411886-a0518380-018b-11ea-8c7a-52cf32a955c9.png)

**Changing the local:**

![image](https://user-images.githubusercontent.com/56550362/68411960-b8c19e00-018b-11ea-9a63-5513481c59f9.png)

## OS (please complete the following information)
 - Browser: [e.g. Chrome 70.0.3538.77]

I don't find any info about that, maybe I don't use correctly the local Extension in JS. But all my locale files are already like that :/

Thanks for your help

**Comment by isaachinman** [comment]
It sounds like you should read up on how module systems work in NodeJs vs browsers.

Regardless, this is not a question for `next-i18next`.

**Comment by Pierre-CLIND** [comment]
Thanks. So, I have to use JSON, which works on both sides

**Comment by eperezcfg** [comment]
@Pierre-CLIND Hello! How did you solve this?
