### ISSUE TITLE
lowerCaseLng and cleanCode option

### ISSUE THREAD

**Issue by RoyLiou** [isaachinman/next-i18next#554]
## Is your feature request related to a problem? Please describe.
In my case, sometimes url subpath include zh-tw or zh-TW by user. I created file in `/static/locals/zh-tw` and added localSubpath but zh-TW doesn't working.
`localeSubpaths: {
    'zh-tw': 'zh-tw',
    'zh-TW': 'zh-tw',
  },`

## Describe the solution you'd like
I think maybe add lowerCaseLng and cleanCode options (like react-i18next options), filter subpath in next-i18next-middleware

## Describe alternatives you've considered
I write the middleware
`server.use((req, res, _next) => {
    const reg = /^\/ZH-TW|^\/zh-TW|^\/ZH-tw/g;
    const result = req.path.match(reg);
    if (result) {
      const parsedUrl = parse(req.originalUrl);
      parsedUrl.pathname = parsedUrl.pathname.replace(reg, result[0].toLowerCase());
      res.redirect(format(parsedUrl));
    } else {
      _next();
    }
  });`

## Additional context
English not my natural language if make you confuse I apologize.

**Comment by isaachinman** [comment]
URLs are indeed case sensitive. I don't really understand your point here. You should not create multiple `localeSubpaths` unless you actually have multiple locales.

This should be handled via plugins, etc. You can just fall back from `zh-TW` to `zh-tw` within a detection plugin or similar.
