### ISSUE TITLE
defaultLanguage is not working

### ISSUE THREAD

**Issue by josecao** [isaachinman/next-i18next#555]
Hi, 

I run the simple, it work ok

But defaultLanguage is not work 

/*
  Do not copy/paste this file. It is used internally
  to manage end-to-end test suites.
*/

const NextI18Next = require("next-i18next").default;

module.exports = new NextI18Next({
  defaultNS: "common",
  defaultLanguage: "de",
  otherLanguages: ["en"]
});

It always to run "en" for first load

Tks! Looking forward to replying from you.

**Comment by isaachinman** [comment]
That's most likely because your browser language is set to English. Please take some time to read some of the i18next documentation.

**Comment by josecao** [comment]
Hi admin ,

i add  browserLanguageDetection: false , but it run english first load

**Comment by michelegera** [comment]
@josecao try also adding `serverLanguageDetection: false` to the configuration object.

```js
module.exports = new NextI18Next({
  // …
  browserLanguageDetection: false,
  serverLanguageDetection: false,
  // …
});
