### ISSUE TITLE
Set Custom Locale path for browser loading - CDN

### ISSUE THREAD

**Issue by sanjitbauli** [isaachinman/next-i18next#556]
## Is your feature request related to a problem? Please describe.
Unable to set CDN path for browser ajax loading

## Describe the solution you'd like
Add an option to pass which will be used as localePath in ajax call in browser

## Describe alternatives you've considered
No

## Additional context
I want to host my json files to another CDN, but no way to set it up correctly. If i use loadPath then SSR is not working as it is searching in the file system

**Comment by isaachinman** [comment]
This question is asked repeatedly. Please search through the issues to find solutions, and feel free to contribute via a PR.
