### ISSUE TITLE
Router from i18n is causing a TypeError

### ISSUE THREAD

**Issue by shaxaaa** [isaachinman/next-i18next#558]
## Describe the bug
Using { Router } from '../i18n'; causes "TypeError: Cannot read property '0' of undefined" when used from getInitialProps of a HOC which is wrapping _app.js

## Occurs in next-i18next version
2.0.0

## Steps to reproduce
1. Use the next-i18next example for Next JS.
2. In _app.js wrap the App with one more HOC. So that it becomes for example -> 
export default withRouteAccess(appWithTranslation(MyApp));
3. In withRouteAccess HOC add getInitialProps and do the following:
`if (context.res) {
    context.res.writeHead(302, { Location: '/' });
    context.res.end();
  } else {
    Router.replace('/');
  }`

where Router is "**import { Router } from '../i18n';**"

On refresh of the page you will get the following error:
**TypeError: Cannot read property '0' of undefined**
52 | if ((0, _utils.subpathIsRequired)(config, i18n.languages[0])) {

## Expected behavior
The expected behavior is that the Router is working fine.

## Screenshots
https://prnt.sc/pwrjvl

**Comment by isaachinman** [comment]
The order of your HOCs matters.

**Comment by shaxaaa** [comment]
I have changed the order, it doesn't fix this.

**Comment by isaachinman** [comment]
What is `withRouteAccess`? You will need to provide a reproducible example.

**Comment by shaxaaa** [comment]
It's just a simple HOC. I have described how it is reproduced. Basically its the next-i18next example and added only the hoc which is doing router redirect. I can do some fiddle if you need, though.

**Comment by isaachinman** [comment]
This package is being used in many real world applications with many different HOCs - both user-built and from other packages like Redux and Apollo. A reproducible example would be great.

**Comment by shaxaaa** [comment]
Please find a reproducible repo here [https://github.com/shaxaaa/router-next-i18next](url). Just visit the index page to see the error.

**Comment by isaachinman** [comment]
You seem to have misunderstood what `hoist-non-react-statics` does. You need to use that on a class. If I change your `WithRouteAccess` HOC to a class, everything is fine.

Good luck!

**Comment by shaxaaa** [comment]
Thanks, @isaachinman for taking your time, but I can't still make it work. I have changed the example and HOC is now a class and still the same error.  [see here](https://github.com/shaxaaa/router-next-i18next/blob/master/lib/routeAccess.js)

Can you show me how it worked for you?

**Comment by isaachinman** [comment]
Okay, if you believe you've found a bug and can articulate what exactly is wrong, please do let me know! Happy to look at that. At the moment I'm not sure if this is an implementation issue or not.

**Comment by shaxaaa** [comment]
Ok, here is an example where you can see that this is not an implementation issue. It's a really really basic example. Just visit "/" page and you will see the error. [see here](https://github.com/shaxaaa/router-next-i18next)

**Comment by isaachinman** [comment]
If you believe you have found a bug, PRs are always welcome. I unfortunately don't have any more time to invest in debugging this issue. Thanks!

**Comment by shaxaaa** [comment]
Can you at least remove Closed status, so others can also review it.

**Comment by isaachinman** [comment]
So far, there is no bug report. Just a proprietary HOC that doesn't seem to work with `next-i18next`.

> This package is being used in many real world applications with many different HOCs - both user-built and from other packages like Redux and Apollo

**Comment by shaxaaa** [comment]
I don't get it how does a repo with 10 lines of custom code which is showing the bug is not a bug report. And the custom code used is the one from the next-i18next package. What should be a bug report then?

**Comment by isaachinman** [comment]
Had a moment to actually look through the source. You've misunderstood the function signature of `getInitialProps`. You need to destructure `ctx` like so:

```jsx
static async getInitialProps({ ctx })
```

The whole point of this issue is that you were calling `Router` on the server side, which is not something you should be doing anyways. The `Router` instance is client side only.

Please post any further questions on StackOverflow.
