### ISSUE TITLE
Error message on missing namespacesRequired calls twice, second time with undefined Component.displayName

### ISSUE THREAD

**Issue by MathiasKandelborg** [isaachinman/next-i18next#56]
The title says it all, I'll leave the duplicate messages here:

```plain
You have not declared a namespacesRequired array on your page-level component: WithStyles(LoadNamespace(Home Page)).
This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app.
For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies

You have not declared a namespacesRequired array on your page-level component: undefined.
This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app.
For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies
```

I define displayName on all my components, and I'm using decorators for `withNamespaces` in TS and are wrapping the page component with a `withStyles` HoC.

This issue might be resolved be reordering the HoC structure of my app. But... I thought this might be an issue somewhere else, as the message is rendered correctly first, then again but without (at least) displayName. I know my lack of knowledge and experience with the internals of both next.js & i18n-next shines through here, but the double rendering seems to be a bug/issue. I haven't tried anything yet and are willing to provide examples if needed.

**Comment by isaachinman** [comment]
It's probably a 404 on the favicon, or something similar? If you don't mind debugging, it should be very easy to figure out what's going on.

Duplicate messages fine - we're often going to see multiple renders in dev. Undefined shouldn't happen, ideally.

**Comment by kachkaev** [comment]
The second error might be coming from `_error.js`, which always gets pre-fetched.

**Comment by MathiasKandelborg** [comment]
It has been resolved on my end, by adding displayName to my `_error.tsx` (in which I'd actually forgotten to add `withNamespaces`).

Simply adding displayName to my already made `_error`page solved the double rendering.

**Comment by isaachinman** [comment]
Yeah, I can't reproduce the undefined `displayName` in the example. The double render happens though - not sure why.
