### ISSUE TITLE
Detecting default language on other languages

### ISSUE THREAD

**Issue by codesignist** [isaachinman/next-i18next#560]
## Is your feature request related to a problem?
My config:
```javascript
module.exports = new NextI18Next({
  defaultLanguage: "tr",
  otherLanguages: ["en", "ar"],
  localeSubpaths: {
    en: "en",
    ar: "ar"
  }
});
```

```
myapp.com         ---> Homepage (Turkish)
myapp.com/en/     ---> Homepage (English)
myapp.com/ar/     ---> Homepage (Arabic)
```

If default lang (Turkish) is selected and someone trying to enter "about" page:
**Lang: Turkish**
```
myapp.com/tr/about   redirects to ---> myapp.com/tr/about (404)
myapp.com/en/about   redirects to ---> myapp.com/en/about (Changes the language and perfectly works fine)
```
Let's say I've changed the language to English and someone tries to enter "about" page:
**Lang: English**
```
myapp.com/tr/about   redirects to ---> myapp.com/en/tr/about (404, thinks "tr" is a page)
myapp.com/en/about   redirects to ---> myapp.com/en/about (Works normal as expected)
```

## Describe the solution you'd like
next-i18next should understand default language (tr) on server-side and redirects as expected:
```
myapp.com/tr/about         redirects to ---> myapp.com/about
```

## Describe alternatives you've considered
Alternative solution on express:
```javascript
server.get("/tr/*", (req, res) => {
  //changing language here
  res.redirect(req._parsedUrl.href.replace("tr/", ""));
});
```

## Additional context
Automatic detect language would be perfect.
Thank you.

**Comment by isaachinman** [comment]
Feel free to set up whatever Express redirects you'd like.

This packages does not infer routes from locales. You must explicitly provide all routes in the `localeSubpaths` map.

**Comment by codesignist** [comment]
I couldn't change the language on server-side.

```javascript
server.get("/tr/*", (req, res) => {
  i18n.changeLanguage("tr"); // this isn't work
  //I don't know how to change language
  res.redirect(req._parsedUrl.href.replace("tr/", ""));
});
```

**Comment by a-eid** [comment]
@codesignist you probably need to disable cookie caching.
