### ISSUE TITLE
Warning: Failed prop type: Link: unknown props found: forwardedRef

### ISSUE THREAD

**Issue by blacksrc** [isaachinman/next-i18next#561]
## Bug description
I'm not sure it's a bug or not. But I've been digging around for a while and couldn't find any solution. Here is what happens in console. (The generated link is just fine and working)

`Warning: Failed prop type: Link: unknown props found: forwardedRef`

![error](https://user-images.githubusercontent.com/1394580/68992307-e17a1f80-087e-11ea-9db1-98d26bab3466.png)

This only happens when I'm trying to use `Link` exported from `i18n.js` config file. If I import it from 'next/link' no warning happens. This is `i18n.js` file: 
```
const NextI18Next = require('next-i18next').default;
const locales = require('./static/locales');

const otherLanguages = [];
const localeSubpaths = [];

Object.keys(locales).map(value => {
  otherLanguages.push(value);
  localeSubpaths[value] = value;
  return true;
});

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: locales.en.value,
  otherLanguages,
  ignoreRoutes: ['/_next/', '/static/', 'robots.txt'],
  localeSubpaths: { ...localeSubpaths }
});

module.exports = NextI18NextInstance;
```

## Occurs in next-i18next version
`^2.0.0`

## Steps to reproduce
I'm using styled-component. Not sure it's relevant or not. However, this is the code that make this happen: 
```
<Link href="/">
    <a>
        <Logo src="/img/logo.svg" />
    </a>
</Link>
```

This will produce a tag like below which is working fine:
```
<a href="/en/">
  <img src="/img/logo.svg">
</a>
```

**Comment by isaachinman** [comment]
> I'm using styled-component. Not sure it's relevant or not

It clearly is, based on that stack trace. Let me know if you investigate further!

**Comment by blacksrc** [comment]
I guess It was a problem with the dependencies. I did the steps below to fix the issue.

- I removed `node_modules` directory.
- I checkout to the commit that everything was working fine
- On that stage I installed the dependencies that I need for the next commits (react-select, toastify, ...)
- I copied the content of `package.json` and indeed `yarn.lock` to a temp file.
- I checked out to the last commit. And replaced the `package.json` and `yarn.lock` with the copied content.
- I installed dependencies again with the new `package.json` and `yarn.lock`.

The warning is now gone and code is working correctly. I'm not sure why this issue happened. But my guess is, It happened due to a mess in `yarn.lock` file.

**Comment by felixmosh** [comment]
I've installed a clean version of my app, and got `react-i18next` 11.2.1, since then I get the same warning.

I've checked the changes log, and saw this [PR](https://github.com/i18next/react-i18next/pull/992) that passes this new prop to `Link` component.

We should filter it out, WDYT? should I PR it?

**Comment by isaachinman** [comment]
@felixmosh PRs welcome!

**Comment by felixmosh** [comment]
> @felixmosh PRs welcome!

https://github.com/isaachinman/next-i18next/pull/563 :]
