### ISSUE TITLE
react-i18next:: i18n.languages were undefined or empty undefined

### ISSUE THREAD

**Issue by tranthaison1231** [isaachinman/next-i18next#562]
I have error when i use "next start" after building. And In production I see text render twice. 

i18n.js
```
const NextI18Next = require('next-i18next').default;

module.exports = new NextI18Next({
  defaultLanguage: 'vi',
  otherLanguages: ['en'],
});
```

server.js
```
const express = require('express');
const next = require('next');
const nextI18NextMiddleware = require('next-i18next/middleware').default;

const nextI18next = require('./i18n');

const port = process.env.PORT || 3000;
const app = next({ dev: process.env.NODE_ENV !== 'production' });
const handle = app.getRequestHandler();

(async () => {
  await app.prepare();
  const server = express();

  server.use(nextI18NextMiddleware(nextI18next));

  server.get('*', (req, res) => handle(req, res));

  await server.listen(port);
  console.log(`> Ready on http://localhost:${port}`); // eslint-disable-line no-console
})();
```

Script:
```
"scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "next start",
    "lint": "eslint ./"
  },
```

package
```
 "next-i18next": "^2.0.0",
 "react-i18next": "11.2.1",
```

**Comment by Kingdutch** [comment]
It looks like you're using `"start": "next start",` instead of starting your custom server as described in the README.

Does changing that fix the issue?

**Comment by tranthaison1231** [comment]
Oh, thank you, it's working and not redender twice, but I still have error react-i18next:: i18n.languages were undefined or empty undefined.

**Comment by jonathangiamp** [comment]
I used this trick to bypass the issue you encountered.

```javascript
// i18next.js
const NextI18Next = require('next-i18next').default;

const languages = ['fr-FR', 'en-GB'];
const options = {
  ...
};

const NextI18NextInstance = new NextI18Next(options);

/* react-i18next needed this extra property */
NextI18NextInstance.i18n.languages = languages;

module.exports = NextI18NextInstance;
```

**Comment by Kingdutch** [comment]
@isaachinman I initially commented on this issue because we also encountered this issue (with the correct usage). Since @tranthaison1231 indicates that he's also still experiencing this issue, perhaps we can keep this open?

I feel like @jonathangiamp is more a workaround that hides a bug somewhere then an actual fix. If that is considered the right way to fix this then perhaps we should document it? However, I don't think mutating an inner object of a class is the right way to go.

**Comment by isaachinman** [comment]
@Kingdutch The "trick" @jonathangiamp is employing actually will break server side language detection in some cases. This exact same issue has been opened and discussed many times - feel free to search.

I closed this issue because it is not coherently describing a single bug/problem.

**Comment by Kingdutch** [comment]
I do see that this is a duplicate of #374 which is closed. Although the issue doesn't actually seem fixed.

We made a test repo for you as small as possible to reproduce the error in `adam7918/next-i18n-undefined-langs`

Running `yarn install` and `yarn dev` should give you the following error

```
react-i18next:: i18n.languages were undefined or empty undefined
```

If this is an error on our part then perhaps we can get this documented because more people seem to be running into it. If it is still an existing bug we'd like to know how we can help you debug it :)

**Comment by isaachinman** [comment]
@Kingdutch Read [this section](https://github.com/isaachinman/next-i18next#3-project-setup) of the docs a bit more carefully!

**Comment by Kingdutch** [comment]
Thanks for the pointer @isaachinman , with the minimally reproducible repo apparently the exports are really important ^^'

@tranthaison1231 change your `i18n.js` to this:
```
const NextI18Next = require("next-i18next").default;

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: "en",
  otherLanguages: ["nl"]
});

module.exports = {
  default: NextI18NextInstance,
  appWithTranslation: NextI18NextInstance.appWithTranslation,
  withTranslation: NextI18NextInstance.withTranslation,
};
```

**Comment by isaachinman** [comment]
@Kingdutch Your problem had nothing to do with exports. You were not running your `server.js` file in dev mode. You need to update your npm scripts.

**Comment by imagine10255** [comment]
`Remind this question`

https://github.com/imagine10255/imnext-js/blob/master/docs/using-next-i18next.md#next-export-first-render-cant-change-language

**Comment by isaachinman** [comment]
@imagine10255 Not sure what your point is, and please remember that this is a public issue for discussion. Anyways, we now dedupe the `allLanguages` array.

**Comment by imagine10255** [comment]
@isaachinman 
I mean when I next export, if I18Next.i18n.languages defaultLanguage is repeated, it will not be able to use the language switching function when the page cannot be opened.

```js
// this is success:
const I18Next = new NextI18Next({
    defaultLanguage: ['en-US'],
    otherLanguages: ['en-US', 'zh-CN'],
});
I18Next.i18n.languages = ['zh-CN']; // <~ No defaultLanguage
```

It ’s just that I met, just to remind everyone, it's okay

**Comment by sigalor** [comment]
I finally managed to find a solution for this issue that worked for me: install the NPM package [`i18next-browser-languagedetector`](https://github.com/i18next/i18next-browser-languageDetector), then simply use it:

```javascript
import NextI18Next from 'next-i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const NextI18NextInstance = new NextI18Next({
  use: [LanguageDetector, initReactI18next],  // LanguageDetector here!
  // + other options
});

// exports etc.
```
