### ISSUE TITLE
Did not expect server HTML to contain a <h1> in <div> in example and our project

### ISSUE THREAD

**Issue by dayze** [isaachinman/next-i18next#57]
I'm trying to integrate next-i18next in our project, but I encountered the following message: 
```
Warning: Did not expect server HTML to contain a <div> in <div>.
```

I tried to use the example in the next-i18next project and on "second-page", I've got the same error message
```
Warning: Did not expect server HTML to contain a <h1> in <div>.
```

**Steps to reproduce the error**
```
npm i
npm run run-example
```
Go to localhost:3000
click on "to second page" 
reload the page

### The key files in our project

**My server.js**
```
const express = require('express');
const next = require('next');
const cookieParser = require('cookie-parser');
const nextI18next = require('./i18n');
const nextI18NextMiddleware = require('next-i18next/middleware')

const app = next({dev: process.env.NODE_ENV !== 'production'});
const handler = app.getRequestHandler();

(async () => {
    await app.prepare();
    const server = express();
    server.use(cookieParser());
    nextI18NextMiddleware(nextI18next, app, server);

    server.get('*', (req, res) => {
        return handler(req, res);
    });

    await server.listen(1664);
    console.log(`> Ready on http://localhost:1664`);
})();
```
**My i18n.js**
```
const NextI18Next = require('next-i18next');

const options = {
    otherLanguages: ['fr']
};
module.exports = new NextI18Next(options);
```

**My app.js**
```
import React from 'react';
import App, {Container} from 'next/app';
import {Provider} from 'react-redux';
import withRedux from 'next-redux-wrapper';
import configureStore from '/redux/store/configureStore.js';
import initializeTokenWithCookie from '/lib/initializeTokenWithCookie';
import api from '/lib/api';
import 'flexboxgrid/dist/flexboxgrid.min.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
import 'static/css/main.scss';
import {appWithTranslation} from '/i18n';

class MyApp extends App {

    static async getInitialProps({Component, ctx}) {
        // Recompile pre-existing pageProps
        const {req} = ctx;

        initializeTokenWithCookie(ctx, api);
        let pageProps = {};
        if (Component.getInitialProps) {
            pageProps = await Component.getInitialProps({ctx});
        }
        return {
            pageProps: {
                ...pageProps,
            },
        };
    }

    render() {
        const {Component, pageProps, store} = this.props;
        return (
            <Container>
                <Provider store={store}>
                    <Component {...pageProps} />
                </Provider>
            </Container>
        );
    }
}

export default withRedux(configureStore(api))(appWithTranslation(MyApp));
```

**My index.js**

```
import React, {Component} from 'react';


class Index extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>
                Index page
            </div>
        );
    }
}

export default Index;
```

The index.js is small on purpose to eliminate other error sources.

**Comment by isaachinman** [comment]
@dayze What version of `next-i18next` are you on?

**Comment by dayze** [comment]
Hi @isaachinman,
Currently on ```^0.10.3```

**Comment by isaachinman** [comment]
Yes, that's correct. Sorry about that - `next-i18next` is still a relatively unstable pre-production project with ongoing rapid development.

**Comment by dayze** [comment]
No problem, thanks for your work !

**Comment by isaachinman** [comment]
@dimensi Please provide a reproducible example in the _latest_ version of `next-i18next`.

**Comment by mvirbicianskas** [comment]
@isaachinman I'm still encountering this issue on 4.3.0, sorry, can't provide reproducible example right now, but it seems it's some kind of a racing condition and it's not possible to consistently reproduce it, sometimes it happens 15 page refreshes consecutively sometimes it doesn't happen for half an hour. If I get to the bottom of it, I'll provide a reproducible example. I have a feeling this is somehow related with when nextjs builds the html during SSR 🤔

**Comment by mvirbicianskas** [comment]
@isaachinman I think found where the issue comes from, in `server.js` while middleware is being initialised 
I think there's some racing conditions with this:
`server.use(nextI18NextMiddleware(nextI18next));`
to fix this you basically need to await for it before server can start resolving requests with this:
`await server.use(nextI18NextMiddleware(nextI18next));`

🤔 I'll keep an eye if the issue still persists, but for an hour or so I didn't get this error after modifying the server config ✌️

**Comment by Maadtin** [comment]
Im having this problem when adding to my config the "react.transSupportBasicHtmlNodes" property :S can someome help please?
