### ISSUE TITLE
"en" is duplicated in "allLanguages"

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#571]
## Describe the bug
With the following configuration, `en` is duplicated in `allLanguages`. If you rely on that value e.g to generate alternate links it will be an issue.

```
const nextI18nConfig = {
  localePath: 'static/locales',
  otherLanguages: ['de', 'fr', 'en'],
  detection: {
    lookupCookie: 'lang',
    checkWhitelist: true,
    order: ['querystring', 'cookie', 'header'],
    caches: ['cookie']
  },
  localeSubpaths: {
    de: 'de',
    en: 'en',
    fr: 'fr'
  },
  debug: process.env.LCA_I18N_DEBUG === '1'
};
```

results in 

```
i18n.options.allLanguages = ['de', 'fr', 'en', 'en']
```

## Occurs in next-i18next version
2.0.0

## Steps to reproduce
Use the config above

## Expected behaviour
`en` should not be duplicated

**Comment by isaachinman** [comment]
You haven't set a default language, and English is the default language by default.

**Comment by StarpTech** [comment]
I think you didn't understand the issue. My question is: Why is `en` two times in the list `['de', 'fr', 'en', 'en']` ? A duplicate should not be passed.

**Comment by isaachinman** [comment]
Ah I think I see what you mean. The short answer is because it was unintentionally passed twice by the user. We don't do any deduping. Not sure it makes sense to get that involved in data sanitisation. What are your thoughts?

**Comment by StarpTech** [comment]
I would dedupe `allLanguages` property.

I see there is a comment about duplication but we don't dedupe it.

https://github.com/isaachinman/next-i18next/blob/b2efc642ed374a3be7bf4ea3b90007ef2319d892/src/config/create-config.ts#L18-L19

**Comment by isaachinman** [comment]
That comment is about users not having to duplicate default values - not the way you interpreted it.

I would be happy to see a PR that dedupes the array as long as it has test coverage. Thanks!

**Comment by StarpTech** [comment]
Please reopen, I will create a PR.
