### ISSUE TITLE
.po files support

### ISSUE THREAD

**Issue by jonathangiamp** [isaachinman/next-i18next#572]
## Describe the bug
Despite the fact that next-i18next has a localeExtension parameter to supports other extension than _json_, the famous _po_ extension doesn't seem supported.

## Occurs in next-i18next version
next-i18next: 2.0.0

## Steps to reproduce
You'll find here a minimalist codesanbox to reproduce my issue.
 
[![Edit next-i18next_po-support](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hello-world-6t1pu?fontsize=14&hidenavigation=1&theme=dark)

## Expected behaviour
As next-i18next has a localeExtension parameter, _po_ extension should works as _json_ extension works.

## OS (please complete the following information)
 - Device: MBP 2018 13"
 - Browser: Chrome 78.0.3904.108

## Additional context
I tried to use some i18 plugins without success ([this](https://www.npmjs.com/package/babel-plugin-convert-to-i18next) one for example)

**Comment by isaachinman** [comment]
I don't have any experience with this file type, but you might need to use a plugin like [i18next-gettext-converter](https://github.com/i18next/i18next-gettext-converter).

**Comment by jonathangiamp** [comment]
I'm seeking for something which will be able to use *.po* files on the fly. This plugin look more like a node tool to convert *po* files to *json* files than a plugin to add on the fly *.po* files compatibility. *.po* extension are very popular and useful to manipulate translation files.

Can I ask you which values are accepted by the **localeExtension** options exposed by `next-i18next`? I'm seeking for a *.json* alternative

**Comment by isaachinman** [comment]
The config gets passed directly into an i18next instance, so the answer is: whatever file extensions are supported by i18next.

I would recommend you look through the i18next documentation or post on StackOverflow. As far as I'm aware there are a number of `next-i18next` users who use other extensions (eg yaml), so I doubt it's an issue in our source code here.

**Comment by jonathangiamp** [comment]
Thanks for your response, I'll take a look deeper on i18next and post a message on StackOverflow if needed.
