### ISSUE TITLE
TypeScript 3.7 compile error: error TS2440

### ISSUE THREAD

**Issue by hgezim** [isaachinman/next-i18next#574]
## Describe the bug
Getting a compile time error as follows:

`node_modules/next-i18next/types.d.ts(8,3): error TS2440: Import declaration conflicts with local declaration of 'WithTranslation'.`

## Occurs in next-i18next version
2.1.0

## Steps to reproduce

Set typescript 3.7.2 as you TS version.

## Expected behaviour
It should compile without issues.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
You'll need to provide actual repro steps. An example repository is best. Thanks.
