### ISSUE TITLE
Translate address

### ISSUE THREAD

**Issue by PanLydka** [isaachinman/next-i18next#579]
> With this link, we would expect someone whose language is set to French to automatically be directed to /fr/some-page.

Is there a way to navigate to _/fr/une-page_ or _/de/eine-seite_ and others language? Or even without a subpath, for example: _/une-page_ or _/eine-seite_. I would also like to translate the address.

**Comment by isaachinman** [comment]
Currently your option is stated [here](https://github.com/isaachinman/next-i18next#custom-routing).
