### ISSUE TITLE
defaultNS throws error when static locales doesn't exist

### ISSUE THREAD

**Issue by MichaelBrog** [isaachinman/next-i18next#584]
Same issue as this one here: https://github.com/isaachinman/next-i18next/issues/381
Using version 1.2.1

I am not using static files but each page will attempt to load the static defaultNS and fail at loading it.

## Steps to reproduce
I am using the following config
```
const nextI18n = new NextI18Next({
  defaultLanguage: 'de',
  otherLanguages: ['de', 'fr', 'it'],
  defaultNS: 'common',            
```

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: MBP OSX 10.14.6
 - Browser: Chrome 78.0.3904.108

**Comment by isaachinman** [comment]
If that's your config, then you _are_ using filesystem localisation data by way of default configuration options.

Please communicate what problem you are experiencing, and what outcome you'd like to see.
