### ISSUE TITLE
How to in next export mode, wait language change done add loading before

### ISSUE THREAD

**Issue by imagine10255** [isaachinman/next-i18next#585]
# Describe the bug
How to in next export mode, wait language change done add loading before

# Occurs in next-i18next version
next-i18next version: 2.1.1

# Steps to reproduce
I set up a repository here:
https://github.com/imagine10255/imnext-js

```bash
# test step
$ yarn
$ yarn export && yarn export:start
```

# Expected behaviour
first en-US, then i change locale in zh-CN,
reload
then en-US flicke 0.5 sec, auto switch in zh-CN.
I hope there can be statuses that allow me to increase loading icon

![Dec-13-2019 14-20-17](https://user-images.githubusercontent.com/5771353/70773915-bae2d200-1db3-11ea-919b-8ab80cbfa13d.gif)

OS (please complete the following information)
Device: OSX 10.14
Browser: Chrome 79.0.3945
Node: v12

**Comment by isaachinman** [comment]
This package does not have first-class support for exports at the moment. It relies on server side language detection and rendering.

**Comment by DenisDov** [comment]
Try this: https://github.com/zeit/next.js/tree/canary/examples/with-loading

**Comment by imagine10255** [comment]
@DenisDov Thank you for your reply, but this should be used for the switch of route monitoring,
Language download should be irrelevant
