### ISSUE TITLE
Add flag to set language cookie as secure

### ISSUE THREAD

**Issue by urkopineda** [isaachinman/next-i18next#587]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Change from `document.cookie = "next-i18next=es";` to `document.cookie = "next-i18next=es;secure";`. This behaviour should only be applied in production and when a flag from options is active, because the secure flag need HTTPS to work.

## Describe alternatives you've considered
In our case, we use `apache` as server and we could add to all cookies generated the secure flag, but it would be fine to add that flag directly from the JS.

## Additional context
I ask for this feature because I got this warning on dareboost.com, a web for performance analytics.
<img width="1000" alt="Captura de pantalla 2019-12-13 a las 13 20 27" src="https://user-images.githubusercontent.com/9933709/70800062-9682f780-1dab-11ea-9314-9fc32a737ddb.png">

**Comment by isaachinman** [comment]
https://github.com/i18next/i18next-express-middleware#detector-options
