### ISSUE TITLE
static pages in .next not found when localeSubpaths are used

### ISSUE THREAD

**Issue by sebarthel89** [isaachinman/next-i18next#588]
## Describe the bug
I want to use localSubpaths that changes my url structure to /de/site and /en/site

I use the Link tag from next-i18n and when I click a link in the browser I see 404s in my network panel like this:

`http://localhost:3000/_next/static/flzTFJIFNsTTbpNag1kdD/pages/en/coaching.js`

My choaching .js is located in `http://localhost:3000/_next/static/flzTFJIFNsTTbpNag1kdD/pages/coaching.js`.

## Occurs in next-i18next version
"i18next": "19.0.1",

## Steps to reproduce
Just use a multiple pages example

## Expected behaviour
There should be no reloads and links should work flawless.

**Comment by isaachinman** [comment]
I don't understand the issue. Please provide a reproducible example.

**Comment by sebarthel89** [comment]
nevermind

I had links like `/${i18n.language}/my-page` in my component. It caused some weird effects like not prefetched views and 404s. Maybe adding a message might be helpful for some people.
