### ISSUE TITLE
Does next-i18next also work with languages fetched form headless cms?

### ISSUE THREAD

**Issue by asherccohen** [isaachinman/next-i18next#589]
My project has a custom way to handle i18next in next.js, similar to your approach). As a plus we have languages coming from a Contentful instance and I was curious to know if your package could handle something like that.

You might also want to update the docs for more info about this topic.

Thanks!

**Comment by isaachinman** [comment]
I have no idea what sort of help you could expect from such a vague two sentences.

**Comment by asherccohen** [comment]
Sorry, should have given some context.

I read from your docs that next-i18next picks translations from static json files. My setup requires translations fetched from a CMS, I would like to know if this is possible out-of-the-box with your solution.

Thank you.

**Comment by isaachinman** [comment]
So if I understand correctly, you want to be able to consume JSON (or similar) locale files from a remote source, is that correct?

Yes, it's absolutely possible, but you will need to ensure that the files are structured as expected, or else get into some i18next plugin config.

Feel free to post on StackOverflow for further information.
