### ISSUE TITLE
Custom Routing support with next-routes

### ISSUE THREAD

**Issue by sanishkr** [isaachinman/next-i18next#590]
## Describe the bug
Custom routing with next-routes patterns are giving 404

## Occurs in next-i18next version
current version

## Steps to reproduce
install next-routes
add routes.js in project dir
```
const routes = require('next-routes')();
routes.add({
    name: 'product',
    pattern:
      '/:language(en|ar)/product/:productName/:id?/:param(param)?',
    page: 'product'
  }) // a route for example
```
in custom server.js -> import routes.js
and add these lines before listening to app on server
```
   const handler = routes.getRequestHandler(
      app,
      ({ req, res, route, query }) => {
        app.render(req, res, route.page, query);
      }
    );
    server.use(nextI18NextMiddleware(nextI18next));
    server.use(handler);
```

## Expected behaviour
the given pattern should be served from product.js in pages dir

I know we can do this logic in this library as shown in example. But, Since I have a lot of routes to be defined so I prefer to use next-routes as a separation of concern. It really simplifies the routing logic.

Any help is appreciated.

**Comment by hrahimi270** [comment]
Same request as well.

**Comment by sanishkr** [comment]
I solved it by removing language in the routes pattern.
```
const routes = require('next-routes')();
routes.add({
    name: 'product',
    pattern:
      '/product/:productName/:id?/:param(param)?',
    page: 'product'
  }) // like this for above product route I mentioned
```

language is pushed in and handled by below line from nextI18next middleware in server.js:

`    server.use(nextI18NextMiddleware(nextI18next));
`

**Comment by hrahimi270** [comment]
Thanks.
But when you want to use `Link` to navigate between pages, you import it from `next-i18next` or `next-routers`?

**Comment by sanishkr** [comment]
Until now I have used
`import Link from 'next/link';
`
or from next-i18next like below
`import { Link } from '../i18n';
`
Both have worked fine for me.

**Comment by hrahimi270** [comment]
Thanks.
I would test it.
