### ISSUE TITLE
How to handle 'as' in Link prop ?

### ISSUE THREAD

**Issue by VictorBaudot** [isaachinman/next-i18next#595]
Hello, how can I make this Link work: `<Link href="/s/[id]/[slug]" as={`/s/${id}/${slug}`}>`?

![image](https://user-images.githubusercontent.com/33088396/71304470-8da3ae80-23c7-11ea-94d5-b09bf8ce0ed6.png)

**Comment by VictorBaudot** [comment]
Solved like this: `<Link href={`${i18n.language || "fr"}/s/[id]/[slug]`} as={`/s/${id}/${slug}`}>``

Is it the best way to do it ?

**Comment by isaachinman** [comment]
Most likely a duplicate of #413.
