### ISSUE TITLE
[FEATURE REQUEST] route translation: "site.com/en/about" to "site.com/pt/sobre"

### ISSUE THREAD

**Issue by rrfaria** [isaachinman/next-i18next#597]
## Is your feature request related to a problem? Please describe.

I would like to translate my routes url to get better SEO

Example:

in english
thesite.com/en/about

in portuguese
thesite.com/pt/sobre

**Comment by isaachinman** [comment]
This question has been answered numerous times and is also addressed in the documentation.

**Comment by rrfaria** [comment]
I ask appologize about that 

but in documentation is showing just how to create the url on server 
but it is not so clear how I could link this.

I know I sould set this on server.js:

```js
  server.get('/sobre', (req, res) => {
    const { query, params } = req;

    return app.render(req, res, '/about', { ...query, id: params.id });
  });
```

but it is not clear how can I create the link on frontend.
should I do a conditional to create link depending on the language or there is any property I could define?


Maybe you could update your example with more complex usage. I believe it will help so much people and reduce big amount of questions

I found out thoses questions similar to this:
#199
#547

**Comment by isaachinman** [comment]
@rrfaria I'm not sure what you mean by "create the link on frontend". You can check the custom routing docs [here](https://nextjs.org/docs#custom-routes-using-props-from-url). There's nothing specific to `next-i18next` in this case, unless I am misunderstanding you.

**Comment by rrfaria** [comment]
I already did a solution for that:

NOTE: it is an alias to folder
@components
@services 

I added to server:

```js
const express = require('express');
const next = require('next');
const nextI18NextMiddleware = require('next-i18next/middleware').default;

const nextI18next = require('./services/i18n');

const port = process.env.PORT || 8080;
const app = next({ dev: process.env.NODE_ENV !== 'production' });
const handle = app.getRequestHandler();

(async () => {
  await app.prepare();
  const server = express();

  server.use(nextI18NextMiddleware(nextI18next));

  /* para criar rotas traduzidas */
  server.get('/logino/', (req, res) => {
    const { query, params } = req;

    return app.render(req, res, '/login', { ...query, id: params.id });
  });

  server.get('*', (req, res) => handle(req, res));

  await server.listen(port);
  console.log(`> Ready on http://localhost:${port}`); // eslint-disable-line no-console
})();

```
I created:
components/Link.js

```js
import PropTypes from 'prop-types';
import React from 'react';
import { i18n, Link } from '@services/i18n';

function LinkLang({ children, langUrls = {} }) {
  const defaultLang = (i18n.options || {}).defaultLanguage;
  const url = langUrls[i18n.language] || langUrls[defaultLang] || '/';
  return <Link href={url}>{children}</Link>;
}

LinkLang.propTypes = {
  children: PropTypes.node,
  langUrls: PropTypes.objectOf(PropTypes.string)
};

export default LinkLang;
```

My Menu component:

```js
import React from 'react';
import PropTypes from 'prop-types';
import Link from '@components/Link';
import { withTranslation } from '@services/i18n';
import './index.scss';

const aboutLinks = {
  en: '/about',
  pt: '/sobre'
};

const Menu = ({ active, t }) => (
  <div className={`menu ${active ? 'menu--open' : ''}`}>
    <ul className="menu__list">
      <li className="menu__item">
        <Link>Home</Link>
      </li>
      <li className="menu__item">
        <Link langUrls={aboutLinks}>{t('about')}</Link>
      </li>
    </ul>
    <div className="menu__actions">
      <button className="menu__action menu--login">LOGIN</button>
      <button className="menu__action menu--sign">SIGN UP</button>
    </div>
  </div>
);

Menu.propTypes = {
  active: PropTypes.bool.isRequired,
  t: PropTypes.func.isRequired
};

export default withTranslation('common')(Menu);
```

look at this part on code above:
```js
const aboutLinks = {
  en: '/about',
  pt: '/sobre'
};
```

it enumerate the links with each language and I pass this to my link though the props langUrls

and when I change the language to pt or en

it will change the url according the language:
site.com/en/about 
site.com/pt/sobre

**Comment by isaachinman** [comment]
If this is a feature request for route translation, it will not be completed. Thanks for explaining your use case though, I'm sure it will be helpful to others.
