### ISSUE TITLE
Link href can't be undefined

### ISSUE THREAD

**Issue by Fonger** [isaachinman/next-i18next#599]
## Describe the bug
In normal `<Link>` from `next/router`, it works when you don't provide href props.
When we use 1-1 replacement from next/router to next-i18next router, it doesn't work anymore

## Occurs in next-i18next version
2.1.3

## Steps to reproduce

Example 1:
```js
<Link>Hello World </Link>
// 'href' type must be either 'string' or 'object', but it is undefined
```

Example 2 from Real Case
```js
let href, as;
let text = 'loading'
setTimeout(() => {
  const id = '5';
  href = `/test/${id}`;
  as = {{ pathname: '/test/test-detail', query: { id }}};
  text = 'Loaded';
}, 1000);
return (
  <Link href={href} as={as}>
    { text }
  </Link>
);

// 'href' type must be either 'string' or 'object', but it is undefined
```

## Expected behaviour
The behavior should be the same with next/router which allow undefined href.
The use case is that when you may not have the href during render. 

## Screenshots
https://github.com/isaachinman/next-i18next/blob/5e5ef787dbfb243ecb7a63bcf0de6dccc32c8b94/src/utils/lng-path-corrector.ts#L26-L40

## OS (please complete the following information)
 - Device: MBP 2013 13"
 - Browser: Google Chrome 79.0.3945.88

## Additional context
This worked on older version of next-i18next `0.44.0`

**Comment by isaachinman** [comment]
Quite a strange use case, but if it's possible in NextJs we should support it. A sensible PR is welcome.

By the way, due to JavaScript weirdness, I think you could probably pass `null` in your undefined cases, as its type is `object`.

**Comment by Fonger** [comment]
> Quite a strange use case, but if it's possible in NextJs we should support it. A sensible PR is welcome.
> 
> By the way, due to JavaScript weirdness, I think you could probably pass `null` in your undefined cases, as its type is `object`.

Yeah in my real case, it's from graphql which is undefined during loading.
`null` is `object` but the code snippet shown above has
`href.query = ...` //TypeError: Cannot set property 'query' of null

and in lngPathCorrector function
`delete href.search` //TypeError: Cannot convert undefined or null to object

We cannot assign a property if the object is null.
