### ISSUE TITLE
Persist language subpath across requests (especially to root) with localeSubpaths enabled

### ISSUE THREAD

**Issue by ushastikchb1** [isaachinman/next-i18next#60]
Hello
I wanted to ask whether you can somehow implement this behavior:

1. User came to / page (default language ru)

2. The user has changed the language in <select> to en. Route changed to /en/

3. User left and came back to /

1. User came to / page (default language ru)
2. The user has changed the language in <select> to en. Route changed to /en/
3. User left and came back to /

In stage 3, the user will have the default language ru in spite of the fact that he chose en the last time (en is written in the cookie after changing the language). I would like to be redirected to /en/ at the entrance to /, if the language specified in the cookie is not the default and is in the list.

Thank you for your help.

**Comment by isaachinman** [comment]
Funny, I just got the same request from my team internally yesterday.

Yes, this is certainly possible but will require changes in the core of `next-i18next`. It's not currently possible with the `localeSubpaths` option for end users.

What you're proposing is respecting the current language over the path - the current implementation of `localeSubpaths` assumes that if a users lands on a route (either the default lang or another one) that they arrived there intentionally and wish to view that language.

The question is if this is a sensible default or not.

I wonder if anyone else can weigh in their opinions here?

**Comment by congaductq** [comment]
Any update?

**Comment by isaachinman** [comment]
Hi @congaductq - the update is that I'm waiting for people to express their opinion, so that I can get a sense of what the majority of users might like. Is this something you would like as a default?

**Comment by congaductq** [comment]
Hi @isaachinman,

I think users would like to save the the last language they chose.

More technically:
1. User go to home page: `/` (en)
2. User change to other language like `/ru` (ru)
3. The next time user visit, web will be directed to `/ru`

Thanks for your help!

**Comment by isaachinman** [comment]
@congaductq and @ushastikchb1 Do either of you have an ongoing project that you can test this in? I'd like to work on a fix for this on a separate branch and have a couple devs test it before we start thinking about merging to master.

@capellini Any idea if it's possible to cover this behaviour with tests? I've never tested against cookies before but assume it's straightforward.

**Comment by ushastikchb1** [comment]
@isaachinman  There is a local project in which I can test

**Comment by isaachinman** [comment]
@ushastikchb1 I'm not sure why you are doing [this](https://github.com/ushastikchb1/next-i18next-test/blob/master/server.js#L16) or [this](https://github.com/ushastikchb1/next-i18next-test/blob/master/next.config.js#L3). If I disable those two things, it works fine.
