### ISSUE TITLE
Render flashing in common nav links header component during browser refresh

### ISSUE THREAD

**Issue by wakemup** [isaachinman/next-i18next#604]
## Describe the bug
I have been struggling with your next-i18next framework for a month or two now.  It looks really promising and I truly think it will be very nice when I get it setup correctly.  **I am seeing all kinds of flashing and weird rendering behavior in a common nav links header component** and I am hoping @isaachinman or anyone else can show me what I am doing wrong.  I have setup a bare bones, publicly available site that demonstrates the issues (see below).

When you open any page on the demo site below, you will see all kinds of flashing with the Header component.  It even appears to show the path to the resource string for a moment ("MENUITEMS.HOME.TITLE" for example).  You can trigger the symptom by hitting F5 or the browser's refresh button.  The symptom appears on any of the 3 pages and in any language.  The issue appears to be only in the Header part of the pages as there is no flashing on the resource retrieval in the main part of the page (the one line below the navigation links is on the each of the individual pages).  _**Please note - there's no UI way in this demo to switch between languages, outside of changing the URL segment to en, es or nl - as I didn't want to complicate this demo with that capability.**_ 

Thank you so much for any time anyone can give me and I'm so sorry I am not smart enough to figure this out myself. I am preparing an "actual" demo product for a venture capital pitch and multi-language is a must have feature.  I would be very appreciative if someone could help straighten this out, as I am running out of time!

## Occurs in next-i18next version

**Deployed Issue Demonstration Web Site:**
http://wakemup-klk.azurewebsites.net/es

**GitHub Repo:**
https://github.com/wakemup/wakemup-klk
Commit SHA: fed755eac3ca2c955bf1f20b05d84d08de3011a4
https://github.com/wakemup/wakemup-klk/tree/fed755eac3ca2c955bf1f20b05d84d08de3011a4

npm version: 6.9.0
Node version: 12.9
next-i18next version: 3.0.1

Other versions

+-- ava@2.4.0
+-- babel-eslint@10.0.3
+-- coveralls@3.0.9
+-- eslint@6.8.0
+-- express@4.17.1
+-- i18next@19.0.2
+-- next@9.1.6
+-- next-i18next@3.0.1
+-- react@16.12.0
+-- react-dom@16.12.0
+-- react-icons@3.8.0
`-- standard@14.3.1

## Steps to reproduce
Open the URL:
http://wakemup-klk.azurewebsites.net/es

Click F5 or browser refresh.  See flashing during rendering.

## Expected behaviour
I expect there to be no flashing or multiple **visible** rendering passes.  The Header component should render smoothly on any page, just as the page content does.

## Screenshots
![gif-1577638874](https://user-images.githubusercontent.com/54385834/71560152-acd7b700-2a2b-11ea-82cd-7c0c7ec1526f.GIF)

## OS (please complete the following information)
 - Device: Windows Server 2016 Standard 10.0.14393
 - Browser: Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)

## Additional context

**Architecture:**

Custom Express server in server.js
i18n.js file, per your "simple" example is also there in the root.

3 pages: Home, Test, Test 2
3 languages under /public/static/locales per "simple" example: en, es, nl   Please note - there's no UI way to switch between languages, outside of changing the URL segment to en, es or nl. 

**Components**
_app.js - boilerplate, per your example
Layout.js - used by _app.js - to layout pages
Header.js - used by Layout.js - has navigation links

**Pages**
index.js - Home page
test.js - Test page
test2.js - Test2 page

**Comment by wakemup** [comment]
SOLVED!  So easy!!

Since I was using the Header component on the 3 pages, I needed to include the 'header' namespace in the namespacesRequired property returned from getInitialProps.  So, by page, that property value became:

index - namespacesRequired: ['home', 'header']
test - namespacesRequired: ['test', 'header']
test2 - namespacesRequired: ['test2', 'header']

Once I added this, the flashing disappeared.

DOH!  Lesson learned!  Thanks for all the work on this, it is really nice.

**Comment by wakemup** [comment]
I am not quite clear on the difference between the namespaces that should be listed in the withTranslation HOC and those that should be listed in the namespacesRequired.  In your sample, for the pages, you list only the page namespace in withTranslation, but both the page namespace and the 'footer' namespace in namespaceRequired.  For now, I have just followed your lead, but I don't really know the difference, honestly.

**Comment by isaachinman** [comment]
The docs read, verbatim:

> withTranslation provides namespaces to the component that it wraps. However, namespacesRequired provides the total available namespaces to the entire React tree and belongs on the page level. Both are required (although you can use Trans instead of withTranslation if desired).

Issues with flashing of untranslated content can normally be debugged via the network tab, as you'll see the missing resources requested there.
