### ISSUE TITLE
Allow config.otherLanguages to be empty

### ISSUE THREAD

**Issue by samhastings** [isaachinman/next-i18next#606]
Currently when I create a new instance of NextI18Next with the `otherLanguages` option not set (or set to an empty array), I get the following error in my console:

    To properly initialise a next-i18next instance you must provide one or more locale codes in config.otherLanguages.

The app requires exactly one locale to start with – additional locales will not be rolled out until a few months after launch. Nevertheless, I still have to deliver a fully internationalised app so my client can add the translations later on, as and when required.

Is there any way around this restriction?

**Comment by isaachinman** [comment]
Hm, unusual use case. I suppose you can just put any random string in there, and: (1) never change the language, (2) disable browser and server language detection.

**Comment by isaachinman** [comment]
Let me know if the suggestion above does not work for you. Good luck!

**Comment by LordZardeck** [comment]
I disagree that this is an unusual case. Lots of projects I work on want i18n considerations already implemented, despite translations not being added until later. While, yes, your workaround could work, why the requirement for other languages to present? I feel like this is a common case in agile/product development. At least it has been in my experience

**Comment by isaachinman** [comment]
Sure, that's debatable and more or less anecdotal. If you feel strongly about it, feel free to submit a PR!

**Comment by WesSouza** [comment]
> more or less anecdotal

I have a project requirement for this at this exact moment. It's real.

**Comment by isaachinman** [comment]
@WesSouza Feel free to submit a PR.
