### ISSUE TITLE
Links are not working after changing language

### ISSUE THREAD

**Issue by hrahimi270** [isaachinman/next-i18next#609]
## Describe the bug
Links are not working after changing language using `i18n.changeLanguage()`.
Throws an error that said:

> Your `<Link>`'s `as` value is incompatible with the `href` value. This is invalid.
But it's lying (:

I'm sure that `as` and `href` props are compatible. It's working in **EN** language. Not working after changing language!!!

For example:
```js
<Link href"/blog/[slug]" as="/blog/this-is-a-test-slug">
    <a href="/blog/this-is-a-test-slug">click on me</a>
</Link>
```

## Occurs in next-i18next version
I'm using next-i18next version 1.2.1.
I know it's not updated but I checked out the new versions commit and I don't think so it's the reason for this problem. But I would test it with the new version too.

## Steps to reproduce
Unfortunentlay, I can't.
But if it would help you, I exported `<Link />` from the `next-i18next` instance.
I also passed "as" and 'href' props both.

## Expected behavior
Links should work fine after changing the language!

## OS (please complete the following information)
 - Device: in all devices
 - Browser: in all browsers

## Additional context
I'm using **styled-components** for creating my components.
I have Buttons and other components that linked using the LInk component.
At first, I thought it's because of using styled-components.
But now I have native `<a />` tags that have the same issue.
So, It's not a problem with styled-components.

I used default `<Link />` of `next/link`. And it works fine.
I also find out something else!
This problem is for `<Link/>`s with `as` prop only. If I don't use `as`, the page navigates fine.

**Comment by isaachinman** [comment]
Please:

1. Use the latest version of the package
2. Provide a reproducible example
3. Take a look at previous and open issues, and ensure this is not a duplicate

**Comment by d2c-sean-li** [comment]
I am having the same problem with latest version (4.0.0) 
when trying to use `changeLanguage` to change the language after initialization in my footer component, e.g. 

```
const { i18n } = useTranslation();
const handleOnChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    i18n.changeLanguage(event.target.value);
};

return (
 <div>
        <select onChange={handleOnChange}>
          <option value="en">English</option>
          <option value="de">German</option>
        </select>
 </div>
)
```

i got error message ```Uncaught (in promise) Error: The provided `as` value is incompatible with the `href` value```

**Comment by isaachinman** [comment]
@d2c-sean-li You should be using the `i18n` instance on the NextI18Next class.
