### ISSUE TITLE
Issue with Router event

### ISSUE THREAD

**Issue by krish-dev** [isaachinman/next-i18next#614]
## Describe the bug
Router event not working

## Occurs in next-i18next version
3.0.1

## Steps to reproduce
just normal setup and this event on any page 
`Router.events.on("routeChangeComplete", url => {
    console.log('routeChangeComplete', url);
  });`

## Expected behaviour
event should not break

## OS
 - macOS Catakina
 - Browser: Chrome 79.0.3945.117

## Additional context
- I'm not using `localeSubpaths`
- Also found an issue with the dynamic path. `pages/[zone]/about.js` then URL pattern will be `xyz.com/us/about`. router.push not working properly. current behavior: if we push with `in` then again `us`. `us` will not be updating. actually it breaks default routing behavior. 
- This is a query: how we can archive this URL pattern with `localeSubpaths` `xyz.com/[zone]/en/about`?

**Comment by isaachinman** [comment]
Please provide a reproducible example.
