### ISSUE TITLE
Cannot read namespace JSON filenames including ":"

### ISSUE THREAD

**Issue by daniellin215** [isaachinman/next-i18next#618]
## Describe the bug
My project includes different themes, and uses different text files depending on the theme (ie. 'common' and 'SPECIAL:common'). The text is not showing when it is looking for 'SPECIAL:common' and in the network requests tab it will show 'SPECIAL:common.missing.json' instead. 

## Occurs in next-i18next version
3.0.1

## Temporary solution
I was able to circumvent the problem by changing the file name to 'SPECIAL-common'. So it seems to me that it cannot read ':'.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Sounds like an upstream problem with one of the i18next packages. If you can isolate it to this package, please do let me know.
