### ISSUE TITLE
Support interpolation options "prefix" and "suffix"

### ISSUE THREAD

**Issue by jackocnr** [isaachinman/next-i18next#620]
The readme says "All other i18next options can be passed in as well", but when I pass in interpolation options "prefix" and "suffix", it just stops working. Are these options supported?

```js
interpolation: {
    prefix: '%{',
    suffix: '}',
  }
```

Thanks for your help.

**Comment by isaachinman** [comment]
Please link to those i18next options in the docs, bearing in mind we are on [v19.x.x](https://github.com/isaachinman/next-i18next/blob/master/package.json#L106).

**Comment by jackocnr** [comment]
Sure https://www.i18next.com/translation-function/interpolation#all-interpolation-options

Thanks.

**Comment by isaachinman** [comment]
Well, if you take a look at the [config options in the docs](https://github.com/isaachinman/next-i18next#options) you will clearly see a double curly braces represented in `localeStructure`.

To achieve what you want, you'll need to also change `localeStructure`:

```
localeStructure: '%{lng}/%{ns}',
interpolation: {
  prefix: '%{',
  suffix: '}',
}
```

We could check for the existence of `interpolation.prefix` and `interpolation.suffix` and insert those values if they exist into the default value of `localeStructure`. I won't be doing that work personally as it's easy to get around for users that really want it, but a PR with test coverage would be accepted.

**Comment by jackocnr** [comment]
Thanks Isaac, that worked. I didn't spot that other options were using the same interpolation syntax - good to know! 👍

**Comment by isaachinman** [comment]
Glad to help.

**Comment by whysbiz** [comment]
Any idea how to support this format :item?

i try to put prefix as ":" and suffix as "" and it doesn't work. Any idea?
