### ISSUE TITLE
I have a problem about next-i18next auto remove constant from locale file

### ISSUE THREAD

**Issue by WoraponU** [isaachinman/next-i18next#622]
## Describe the bug
My text  is removed when It has {{constant}} in sentence

## Occurs in next-i18next version
4.0.0

## Steps to reproduce
set locale resource about 
```
{
"product-detail.day-working": "{{date}} day working",
}
```

## Expected behaviour
it should be display `{{date}} day working` when I print console.log(this.props.t('product-detail.day-working')) but I see ` day working`

## Screenshots
![image](https://user-images.githubusercontent.com/13904659/73008130-7af61c80-3e40-11ea-84ea-e61e47302182.png) But I expect to see `{{date}} day working` in console.log

## OS (please complete the following information)
 - Browser: chrome lastest version

## Additional context
please help

**Comment by isaachinman** [comment]
Double curly brackets are, by default, for interpolation. This has nothing to do with `next-i18next`. I suggest you read up on the i18next docs and post on StackOverflow if needed. Good luck!

**Comment by WoraponU** [comment]
thank you.
