### ISSUE TITLE
[routing] localeSubpaths without 302 redirect to default language subpath on root `/`

### ISSUE THREAD

**Issue by ortonomy** [isaachinman/next-i18next#625]
## Describe the bug
It's important for our app that for the default language (en) that when we load the root path `/' that it should stay on the root, not redirect to the `localeSubPath`

However, we do want all other route requests (e.g. `/articles/2020/10/article-name`) to go to the subpath `/en/articles/2020/10/article-name` when using `<Link></Link>`

## Occurs in next-i18next version
4.1.0

## Steps to reproduce
1. `./i18n.js`

```
const NextI18Next = require('next-i18next').default

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['zh-hans'],
  localeSubpaths: {
    en: 'en',
    "zh-hans": 'zh-hans'
  },
  serverLanguageDetection: true,
  browserLanguageDetection: true
})


/* Optionally, export class methods as named exports */
const funcs = {
  appWithTranslation,
  withTranslation,
  useTranslation
} = NextI18NextInstance

module.exports = {
  ...funcs,
  NextI18NextInstance
}
```

2. Example `server.js` from this project

3. go to root `/` => redirects to `/en`

## Expected behaviour
go to root `/` => stays at `/` unless a non default language is selected

## OS (please complete the following information)
 - Device: MBP 13 2017
 - Browser: Chrome Latest

**Comment by isaachinman** [comment]
Sounds like you have non-standard business requirements and will need to fork/roll your own implementation!

**Comment by rumsky** [comment]
I have the same problem. 
root router redirect default language path.
