### ISSUE TITLE
Property 't' does not exist on type

### ISSUE THREAD

**Issue by jemunk** [isaachinman/next-i18next#627]
This is probably not a bug, but I can't seem to find an example anywhere that explains me what to do. 

The thing is, that the component is based on the NextPage, but then the compiler won't recognize the t property

Typescript compiler gives this error:
 > Property 't' does not exist on type

Occurs in next-i18next NPM version 4.1.0

```
import PropTypes from 'prop-types'
import {  NextPage } from 'next';
import Head from 'next/head'
import { withTranslation } from '../utils/i18n'


const Home: NextPage = ({t}) => {
  return(
    <>
    <Head>
      <title>Home</title>
    </Head>
    <div className="row border border bg-light rounded my-4 p-3">
      <div className="col-12">
        <h1>{t("AllStudentsMarked")}</h1>
      </div>
    </div>
    </>
  )
}

Home.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withTranslation('common')(Home);
```

**Comment by jemunk** [comment]
ok. If I add the any type, it works. 
`const Home: NextPage = ({t}: any) => {`
But is there a way avoid the _any_?

**Comment by isaachinman** [comment]
You're importing `NextPage` directly from `next`. If you want to use that type/interface, you'll need to extend it.

I take it you're somewhat new to TS? Feel free to also take a look at [the types that `next-i18next` exports](https://github.com/isaachinman/next-i18next/blob/master/types.d.ts).

**Comment by jemunk** [comment]
Thanks. Yes, I am quite new to Typescript. In that case examples means a lot, which is hard to dig up.

**Comment by isaachinman** [comment]
What you're looking for is the `TFunction` type.

**Comment by jemunk** [comment]
This seems to solve it:
`const Home: NextPage<WithTranslation> = ({t}) => {`
