### ISSUE TITLE
it will be displayed "en" content When I build your example with {defaultLanguage: "de"} in SSR mode.(Incognito)

### ISSUE THREAD

**Issue by WoraponU** [isaachinman/next-i18next#632]
## Describe the bug
it will be displayed "en" content When I build your example with {defaultLanguage: "de"}. (Incognito) https://github.com/isaachinman/next-i18next/tree/master/examples/simple

## Occurs in next-i18next version
my dependencies are lastest version at today
![image](https://user-images.githubusercontent.com/13904659/73936052-8a7f6600-4914-11ea-9252-5e3c1212a9c5.png)

## Steps to reproduce
my config is
![image](https://user-images.githubusercontent.com/13904659/73935662-a1718880-4913-11ea-9c08-792949b7755a.png)
I add defaultLanguage: "de" to NextI18Next config but when I run yarn run dev and then I see "i18next: languageChanged en" in my console.log
![image](https://user-images.githubusercontent.com/13904659/73936226-eba73980-4914-11ea-8d3a-56b4e39809bb.png)

and i setup my server.js with
![image](https://user-images.githubusercontent.com/13904659/73936115-abe05200-4914-11ea-9c7a-4d0c37c6fa6c.png)

## Expected behaviour
my expectation is content will be show "de" content

## Screenshots

![image](https://user-images.githubusercontent.com/13904659/73935765-e09fd980-4913-11ea-8d75-749010fe44f2.png)

## OS (please complete the following information)
chrome lastest version

## Additional context
help me please. thank you verymuch

**Comment by WoraponU** [comment]
So I found step to fix my issue
add 
```detection: {
    lookupCookie: 'next-i18next',
    order: ['cookie', 'querystring', 'localStorage', 'path', 'subdomain'],
    caches: ['cookie'],
  },```
to my configuration

it is correct way?

**Comment by isaachinman** [comment]
I suggest you read up on how language detection works. Good luck!
