### ISSUE TITLE
forwardRef can't work when using withTranslation

### ISSUE THREAD

**Issue by bcjohnblue** [isaachinman/next-i18next#633]
## Describe the bug
forwardRef can not work when using withTranslation.

## Occurs in next-i18next version
latest (4.2.0)

## Steps to reproduce
1. clone and run [withTranslation_forwardRef](https://github.com/bcjohnblue/next-i18next_withTranslation_forwardRef)

2. The index page will break totally (you can see a lot of error messages in console)

## Expected behaviour
1. `withTranslation('common', { withRef: true })(Input);` should be work just like [withtranslation-use-ref](https://react.i18next.com/latest/withtranslation-hoc#use-ref-greater-than-v-10-6-0) shows.

## OS (please complete the following information)
 - Device: Mac catalina 10.15.2
 - Browser: Chrome 79.0.3945.130

**Comment by isaachinman** [comment]
Cannot reproduce in the simple example. If I change [this line](https://github.com/isaachinman/next-i18next/blob/9295d048a5d750d9ae1909287a1eb108fe3d93de/examples/simple/pages/index.js#L41) to:

```jsx
export default withTranslation('common', { withRef: true })(Homepage)
```

The page renders without errors.

Regardless, the primary error is coming from React itself: `Function components cannot be given refs`.

Moreover, `next-i18next` simply [re-exports directly from `react-18next`](https://github.com/isaachinman/next-i18next/blob/8fcf5552e5bce03ae42a2232ab8043cfe0542f8f/src/index.ts#L47).

This is either a version mismatch, a user error, or an upstream bug.
