### ISSUE TITLE
Using only hooks without withTranslation HOC?

### ISSUE THREAD

**Issue by jesperjohansson** [isaachinman/next-i18next#634]
Hello! I'm wondering if its possible to use only the `useTranslation` hook without the `withTranslation` HOC on page level?

Like:
```javascript
export default function MyPage() {
  const { t } = useTranslation('common')
  return <div>{t('hello')}</div>
}
```

When I try doing so I get the warning in console:
```
You have not declared a namespacesRequired array on your page-level component: withI18nextTranslation(Index). This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app. For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies
```

It works but I don't want to compromise the app's performance. Do I need to use the HOC `withTranslation` then?

EDIT:
It seems like I get the warning message when I use `withTranslation` and `useTranslation` at the same time in a page component too.

EDIT2:
I get the warning message if I use the `useTranslation` hook anywhere.

**Comment by isaachinman** [comment]
I suggest reading the docs. Search for `namespacesRequired` in the README.

**Comment by thanhdevapp** [comment]
it's work
`import { useTranslation, i18n } from "../i18n";`

inside function 

`const { t } = useTranslation(['common'], { i18n });`

**Comment by jesperjohansson** [comment]
Yes, thank you. I got it working after reading about `namespacesRequired`. I was missing `getInitialProps`:

```javascript
MyPage.getInitialProps = async () => ({
  namespacesRequired: ['common', 'start'],
})
```
