### ISSUE TITLE
i18next "load" option not respected when initialising store on SSR

### ISSUE THREAD

**Issue by rjoaopereira** [isaachinman/next-i18next#635]
## Describe the bug
When [initialising](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L147) the store, only the current language is taken into account.
As per i18next [docs](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources), languages and locales (and dev) should be considered if `load: all` is the option (default behaviour).

## Occurs in next-i18next version
4.1.0 

## Steps to reproduce
I think the link to the code is self explanatory, if not, I will provide the code to reproduce.

## Expected behaviour
when a locale is selected and the option to load `all` (which is the default) is set, the language should also be added to the `initialI18nStore` object (dev as well)

## Screenshots
N/A

## OS (please complete the following information)
 - Device: MBP 2017 13"
 - Browser: Chrome 80.0.3987.87

**Comment by isaachinman** [comment]
What's your use case? This package is an opinionated approach to translate NextJs apps via i18next packages.

**Comment by rjoaopereira** [comment]
Thank you for the fast reply.

On the server side:

I have static files with translations and I need to load another set dynamically and add them through `addResources`. 
I can see the translations under the `en` language but since the current language is `en-US` they will never be sent to the client.

I actually have more languages and locales at this point which I would benefit from sending immediately to the client, if possible.

**Comment by isaachinman** [comment]
So you are loading namespaces via the filesystem and also via some network requests, is that right?

My initial feeling is that you should be doing this declaratively via a valid config, and not imperatively at runtime.

However, if you have an idea for a PR here to introduce the i18next functionality you need, I would be happy to review that. Thanks!

**Comment by rjoaopereira** [comment]
That is right.

> My initial feeling is that you should be doing this declaratively via a valid config, and not imperatively at runtime.

I only know what translations to query after another query is made.

> However, if you have an idea for a PR here to introduce the i18next functionality you need, I would be happy to review that. Thanks!

I'll try to find the best way to achieve this. Thanks

**Comment by isaachinman** [comment]
Okay, let me know if I can provide any help. You might want to check out the [available backends](https://www.i18next.com/overview/plugins-and-utils#backends).

**Comment by rjoaopereira** [comment]
This is a false issue. Languages are [loaded](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lngs-to-load.ts#L28) according to the rules (except for dev but I don't care for it). When a locale is present, the language it belongs to is also loaded.

Sorry for the inconvenience.

A mistake on my part where the fallback language was not defined led me to the initial problem.
