### ISSUE TITLE
Add Support for Subfolders (localeStructure)

### ISSUE THREAD

**Issue by DovahBrownies** [isaachinman/next-i18next#636]
## Is your feature request related to a problem? Please describe.
No.

## Describe the solution you'd like
Add support for subfolders such as, instead of:
```
.
└── locales
    └── en
        ├── home.json
        └── header.json
```
we can do
```
.
└── locales
    └── en
        ├── pages
        |   └── home.json
        └── components
            └── header.json
```

by setting the `localStructure` as something like: `{{lng}}/{{dir}}/{{ns}}

I think this would open up doors for a neater structure.

**Comment by isaachinman** [comment]
That's entirely an i18next concern and should be raised in an upstream repo.
