### ISSUE TITLE
Jumping translations on load

### ISSUE THREAD

**Issue by gwendall** [isaachinman/next-i18next#637]
Hello - here is a problem I have been struggling on for a few days. My server-rendered pages run fine with translations; loading them with javascript disabled generates them with the right text. However, once javascript is enabled, all the translated strings briefly "jump" from their json-related keys to their actual translated values on load. I don't know exactly where to investigate. Any idea ?

Here is a screenshot of the problem : 
![Bug](https://media.giphy.com/media/j4qOdX5nCs39RwvzTR/giphy.gif)

And here is my `next-i18next` config :
```
// i18n.js
const NextI18Next = require('next-i18next').default

const availableLocales = ['fr', 'en']
const defaultLocale = 'fr'

const NextI18NextInstance = new NextI18Next({
  preload: [defaultLocale],
  fallbackLng: defaultLocale,
  defaultLanguage: defaultLocale,
  otherLanguages: availableLocales.filter(l => l !== defaultLocale),
  localePath: 'public/static/locales',
  localeStructure: '{{lng}}/{{ns}}',
  localeSubpaths: {
    en: 'en',
  },
  detection: {
    order: ['header', 'querystring'],
  },
  defaultNS: 'common',
})
NextI18NextInstance.i18n.languages = availableLocales
module.exports = NextI18NextInstance
module.exports.availableLocales = availableLocales
module.exports.defaultLocale = defaultLocale
```
```
// server.js
const express = require('express')
const cookieParser = require('cookie-parser')
const next = require('next')
const nextI18NextMiddleware = require('next-i18next/middleware').default

const nextI18next = require('./i18n')

const port = process.env.PORT || 3000
const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler()

;(async () => {
  await app.prepare()
  const server = express()
  await nextI18next.initPromise
  server.use(nextI18NextMiddleware(nextI18next))
  server.use(cookieParser())
  server.get('*', (req, res) => handle(req, res))
  await server.listen(port)
  console.log(`> Client is running on localhost:${port}`) // eslint-disable-line no-console
})()
```
Versions :
`next-i18next@4.2.0`
`next@9.2.1`

**Comment by gwendall** [comment]
Thanks for the quick response @isaachinman. Same problem when I remove `preload`, I ended up setting it whilst investigating to solve this problem.

**Comment by isaachinman** [comment]
@gwendall If you can provide a reproducible repository, I'll debug it for you.

**Comment by gwendall** [comment]
Awesome. Here it is : https://github.com/gwendall/next-i18next-bug

**Comment by gwendall** [comment]
Ok, fixed it. The problem came from here : https://github.com/gwendall/next-i18next-bug/blob/872b49a7ab4d771be1d2efea16c73bf123663948/src/pages/_app.js#L6

Somehow, it screwed something up. Passing directly the following worked :
```
export default appWithTranslation(App);
```

Thanks !

**Comment by eric-burel** [comment]
@gwendall what happens when you have a missing key in a secondary language? I can repro the flashing with a similar config as yours, say when I define an `hello` key in English but I forget to add it in French too.

Client-side I can fallback to english but not server-side.That's kind of an edge case but I'd rather avoid client/server discrepancies as they are often terrible in production.

**Comment by isaachinman** [comment]
@eric-burel Fallback logic should work identically between server and client - the i18n instance is literally the same. It gets serialised to the client.
