### ISSUE TITLE
Do I really need to include namespace via namespacesRequired on each page?

### ISSUE THREAD

**Issue by meliborn** [isaachinman/next-i18next#638]
Could you please clarify me with one moment. 
Let's say a have a Header component. It's using on every page. Without including it's namespace in namespacesRequired of page's initialProps I'm getting 
`Warning: Prop "alt" did not match. Server: "CompanyName" Client: "logoAlt"`
Even If passing header namespace to the withTranslation(). 
What I'm doing wrong? It can be annoying to pass it's namespace on every page of my app. And Header not the only one component that using on every page.

```javascript
export default NextI18NextInstance.withTranslation('header')(Header);
```

**Comment by isaachinman** [comment]
> What I'm doing wrong?

You're specifying `namespacesRequired`. This tells `next-i18next` _exactly_ the namespaces you need to render that page. If you miss one, you will miss translations.

You can either include all the namespaces you need, or omit `namespacesRequired` entirely.

In the future, `next-i18next` will likely convert localisation keys into named exports and perform tree shaking in that way.

For now, you can always create a default area and spread it in, or do whatever you want. Good luck!
