### ISSUE TITLE
Redirecting to translated routes on language switching

### ISSUE THREAD

**Issue by alexandrepaivaa** [isaachinman/next-i18next#640]
Hi,

I'm sorry if I shouldn't create this kind of post here but I have asked this on some FB groups and also StackOverflow without any success. Is there anyway where I could be automatically redirected to translated routes when changing the language? For example:

example.com/en/home -> example.com/pt/inicio
example.com/en/contact -> example.com/pt/contato
(etc...)

Currently when I'm on example.com/en/home and hit the language switcher it redirects to example.com/pt/home when I'd like to redirect to example.com/pt/inicio instead. The only way to achieve this would be creating manually the respective files inside of en/pt folders? Or there is any better approach for that?

Thank you very much

**Comment by isaachinman** [comment]
That's not something that `next-i18next` currently supports. You'll need to set up custom routes in your server file.
