### ISSUE TITLE
Type for objects and arrays

### ISSUE THREAD

**Issue by ghost** [isaachinman/next-i18next#641]
## Describe the bug
When using [objects and arrays](https://www.i18next.com/translation-function/objects-and-arrays) with standard types, I encountered an error:

> Property 'map' does not exist on type 'string'.

I tried using different types of library.

## Occurs in next-i18next version
```json
"next-i18next": "^4.2.0"
```

## Steps to reproduce
[https://codesandbox.io/s/next-i18next-example-uv98b](https://codesandbox.io/s/next-i18next-example-uv98b)

**Comment by isaachinman** [comment]
Please post a full stack trace.

**Comment by BrandonWeber** [comment]
Sorry, I’ve been trying to find the right type all day, so I wrote the problem incorrectly. Added a sandbox.

**Comment by isaachinman** [comment]
@BrandonWeber Unless I'm mistaken, all of these types come from `i18next` and `react-i18next` directly.
