### ISSUE TITLE
 Cannot read property 'displayName' of undefined 

### ISSUE THREAD

**Issue by Marszht** [isaachinman/next-i18next#642]
## Describe the bug
after i run the  app  it comes to the followwing bug :
            Cannot read property 'displayName' of undefined 
           at getDisplayName (C:\CodeZoom\芦苇\海外招聘\overseas-recruitment-pc\node_modules\react-i18next\dist\commonjs\utils.js:98:20)
![image](https://user-images.githubusercontent.com/38552120/75304397-2d753100-587e-11ea-85a7-8ac1e4a06627.png)

## Occurs in next-i18next version
4.2.0

## i18n.js Configuration

```
const NextI18Next = require('next-i18next').default;

module.exports = new NextI18Next({
  defaultLanguage: 'en',
  debug: false,
  otherLanguages: ['cn'],
  // localeSubpaths: 'foreign',
  localeSubpaths: {},
  // localePath: `${isBrowser() ? '' : 'app/'}static/locales`,
  localePath: 'public/static/locales',
});
```
## _app.js Configuration

```
import { appWithTranslation } from '../i18n';
export default appWithTranslation()(MyApp);

```

**Comment by isaachinman** [comment]
That error is coming from `react-i18next`. Please open an issue there.
