### ISSUE TITLE
Support for localize route.

### ISSUE THREAD

**Issue by chiqui3d** [isaachinman/next-i18next#643]
## Describe the bug
This library does not support localize route.

Even in the same example you can see perfectly that not https://next-i18next.com/.

I don't think I will ever create a website where the languages are loaded in the **same URL**. If for example my default language is `en `if I want to show the **Spanish** language I should redirect to `next-i18next.com/es`, not load on the same page. These in the eyes of Google are always seeing the same page.

Please provide an example of how to do the redirection to the correct URL with the `localeSubpaths`

**Comment by isaachinman** [comment]
Not quite sure what you're asking. I highly suggest you read the documentation! Good luck.

**Comment by chiqui3d** [comment]
Thanks
