### ISSUE TITLE
TypeError: Property 'allLanguages' does not exist on type 'InitOptions'.

### ISSUE THREAD

**Issue by onderceylan** [isaachinman/next-i18next#648]
## Describe the bug
NextI18Next [class interface in types.d.ts](https://github.com/isaachinman/next-i18next/blob/master/types.d.ts#L57) is missing `options: Config` in type definitions.

The instance of NextI18Next does not have the correct types for options hence it throws `TypeError: Property 'allLanguages' does not exist on type 'InitOptions'.` TypeScript compilation error.

## Occurs in next-i18next version
4.2.0

## Steps to reproduce
The following implementation in a TS file will reproduce the exception:
```
const NextI18NextInstance = new NextI18Next({
  browserLanguageDetection: false,
  defaultLanguage: 'nl',
  localeSubpaths: {
    en: 'en',
  },
  otherLanguages: ['en'],
  serverLanguageDetection: false,
  shallowRender: true,
});

export const {
  appWithTranslation,
  withTranslation,
  i18n,
  Link,
} = NextI18NextInstance;

const { options } = i18n;
const myNewArray = [...options.allLanguages]; // Error:(47, 39) TS2339: Property 'allLanguages' does not exist on type 'InitOptions'.
```

## Expected behaviour
I'd expect `options` having the types of `Config` for the class instance as well. This can be fixed by extending the `i18n` property's type as:

```
declare class NextI18Next {
  constructor(config: InitConfig);
  Trans: Trans
  Link: Link
  Router: Router
  //  The line below fixes the issue
  i18n: I18n & { 
    options: Config;
  }
  initPromise: InitPromise
  config: Config
  useTranslation: UseTranslation
  withTranslation: WithTranslationHocType
  appWithTranslation: AppWithTranslation
}
```

## Screenshots
N/A

## OS (please complete the following information)
 - Device: MBP 2019 15"
 - TypeScript version: 3.8.3

## Additional context
Tsconfig:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ]
}
```

**Comment by onderceylan** [comment]
First of all, thanks for the great library! If you think this is a valid case, I'd be happy to create a PR with the fix.

**Comment by isaachinman** [comment]
Hm, it's a bit of a grey area. The `allLanguages` array is something used internally and not really intended for user consumption. What's your use case? Why not manage the array in userland?
