### ISSUE TITLE
How do I make this work with Typescript?

### ISSUE THREAD

**Issue by jonashendrickx** [isaachinman/next-i18next#651]
## Describe the bug
Can't seem to fix the i18n and Link references in pages/index.tsx based on example. I have a feeling this needs to be done in i18n.ts.

## Occurs in next-i18next version
Latest

## Steps to reproduce
I added tsconfig.json and upgraded to typescript based on the next.js documention using your sample.

/*
  Do not copy/paste this file. It is used internally
  to manage end-to-end test suites.
*/

const NextI18Next = require('next-i18next').default;
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;

const localeSubpathVariations = {
  none: {},
  foreign: {
    de: 'de',
  },
  all: {
    en: 'en',
    de: 'de',
  },
};

const NextI18NextInstance = new NextI18Next({
  otherLanguages: ['de'],
  localeSubpaths: localeSubpathVariations[localeSubpaths],
});

export default NextI18NextInstance;
export const {
  appWithTranslation,
  withTranslation,
} = NextI18NextInstance;

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by kachkaev** [comment]
@jonashendrickx you might find an answer in this non-official example app: https://gitlab.com/kachkaev/website-frontend

Please note that github issues are for bugs and feature requests, not for questions related to the library. Please close it as it is not actionable on 😉
