### ISSUE TITLE
Usage of useTranslation hook inside components cause rerender

### ISSUE THREAD

**Issue by srgvrnv** [isaachinman/next-i18next#654]
## Describe the bug
When I use useTranslation hook inside function component it causes multiple rerenders. Can't reproduce it with create-react-app and react-i18next. So it should be landed here. If I use react profiler I see that it takes 1102 render, but with create-react-app and react-i18next it takes only 2. Am I missing something or this is a bug?

## Occurs in next-i18next version
4.2.1

## Steps to reproduce
```js
# i18n.js

const NextI18Next = require('next-i18next').default

module.exports = new NextI18Next({
    defaultLanguage: 'fi',
    otherLanguages: ['en', 'ru'],
    localeSubpaths: {
        en: 'en',
        ru: 'ru',
    },
})

```

```js
# _app.js

import React from 'react';
import './App.css';
import Test from './components/test';
import i18n from './i18n';

const Locales = () => (
  <>
    {['fi', 'en', 'ru'].map(locale => (
      <button type="button" key={locale} onClick={() => { i18n.changeLanguage(locale); }}>
        {locale}
      </button>
    ))}
  </>
);

function App() {
  let tests = [];

  for (let index = 0; index < 100; index++) {
    let testsinner = [];
    for (let index2 = 0; index2 < 10; index2++) {
      testsinner.push(<Test key={`${index}_${index2}`} />);
    }
    tests.push(<Test key={index}>{testsinner}</Test>);
  }

  return (
    <>
      <Locales />
      <div>
        {tests}
      </div>
    </>
  );

}

export default App;
```

```js
# components/test.jsx

import i18n from '../i18n';

let count = 0;

const Test = ({ children }) => {
    count++;

    const [t, { language }] = i18n.useTranslation();

    return (
        <>
            <p>{t('catalog')} + {count} + {language}</p>
            <div>{children}</div>
        </>
    )
}

export default Test;
```

## Expected behaviour
Shouldn't be rendered so much times

## OS (please complete the following information)
 - OS: macOS Catalina
 - Browser: Chrome 80.0.3987.132

**Comment by isaachinman** [comment]
Hi @srgvrnv - thanks for this report. Do you mind quickly setting up a demo repo that we can reproduce this and track down the issue?

**Comment by srgvrnv** [comment]
Hi!
Sure, here is it https://github.com/srgvrnv/test-use-translation-bug

**Comment by srgvrnv** [comment]
@isaachinman Hello! Any updates on this issue?

**Comment by isaachinman** [comment]
@srgvrnv I don't really know what you expect, you're rendering 1100 components in a loop.

**Comment by srgvrnv** [comment]
@isaachinman 

Size of loop is ridiculously huge just to demonstrate a problem. I face this issue while rendering nested set of 50 entities with nesting level of 2 using of `useTranslation()` hook inside each of them. 

Anyway react-i18next have no issue to render "1100 components in a loop" while next-i18next have some problems with it

Maybe there is some misunderstanding but I expect it to work same way

Am I missing something here?

**Comment by ricardobrandao** [comment]
I'm having the same issue. @srgvrnv were you able to understand what the issue was?

Best,

**Comment by srgvrnv** [comment]
@ricardobrandao Unfortunately not. For now I solve it with using static class which I setup in `_app.tsx` instead of using `useTranslation()`
```js
LocaleHandler.locale = language;
LocaleHandler.t = t;
```

**Comment by chrisinajar** [comment]
The example repository posted above clearly demonstrates that `next-i18n` results in 1 extra render per language change than `react-i18n` does. Each full re-render using the react variant causes 1,100 renders -- one each. The next variant causes each component to render twice, 2,200 renders total.

This seems to be caused by the entire App tree being re-rendered instead of just the components that change. You'll notice that in the example above, the core app component in the CRA version never renders again after the first render, while in the next version the App renders every single time and then re-renders all of the children once more as well (needlessly double rendering all of them).

This can be very easily observed by simply adding log statements to the render methods:
![image](https://user-images.githubusercontent.com/422331/81743940-55286e00-9457-11ea-9557-4483bf72f890.png)
Here you can see all of the components render with the new language after the change, and then the app itself re-renders causing them all to render once more. My guess is something to do with putting the language in the url...

Anyway, I hope this additional information helps. This ticket should be re-opened as there is clearly either an undocumented inconsistency or an actual bug.

**Comment by isaachinman** [comment]
Don't have a lot of spare time at the moment, but very happy to hear any suggestions/ideas.

**Comment by SalahAdDin** [comment]
Is it possible to use `react-i18n` instead of this package?

**Comment by isaachinman** [comment]
@SalahAdDin Of course.

**Comment by SalahAdDin** [comment]
@isaachinman It just occupy to change the language, as we are using in a plain **react** website we are working too.

But there is a problem:
I'm getting the language by `const lng = () => localStorage.getItem("language") || "en"`.

But when i try in this way i get:
`TypeError: Cannot read property 'use' of undefined`, also `localStorage` is not defined.

Why?

**Comment by ddhp** [comment]
I found out whenever the language is changed, the router would be replaced which is causing the extra rerendering ([source code](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L46)). Probably this is the expected behavior, since next.js also handles the routing part but `create-react-app` doesn't?

**Comment by k4mr4n** [comment]
I have the same issue and [whydidyourender](https://www.npmjs.com/package/@welldone-software/why-did-you-render) library point it out very well.
it seems like the "t" function exported from "useTranslation" hook has not been memoized.

<img width="785" alt="Screen Shot 2020-11-06 at 9 28 05 AM" src="https://user-images.githubusercontent.com/5468009/98377200-818e0300-2012-11eb-945d-314ea03af93f.png">

**Comment by csinig** [comment]
I guess i'm facing almost the same issue .
When the language is changed, components are re-rendered with the new locale => to this point, this is fine
But then the url is updated causing the whole app to refresh and the state to be lost. This is actually very annoying as the users lose all their input.
Any idea or any chance this issue could be fixed soon ? Thanks

**Comment by tquiroga** [comment]
Same issue pointed by whydidyourender, when you use the hook across your app and realize most re-render are caused by the `useTranslation` hook, ouch 😬

**Comment by isaachinman** [comment]
Does anyone mind testing this issue in `next-i18next@8.0.0` to see if it is still relevant?

**Comment by zcmgyu** [comment]
I don't know why but I got the same issue with react-i18next. LOL

**Comment by k4mr4n** [comment]
@isaachinman upgrading to v8.0.0 from v6 is really painful. would there be any patch for the v6 to fix this issue?

**Comment by isaachinman** [comment]
@k4mr4n As with all previous releases, I won't be actively working on maintenance, but if users want to open PRs, I will certainly review, merge, and publish them.

**Comment by andrei-scripcaru** [comment]
For anyone interested, re-render still happening (probably should at some point), but I ended up using `next-translate` and it seems to be working fine.

**Comment by SalahAdDin** [comment]
@andrei-scripcaru why did you switched to `next-translate`?

**Comment by andrei-scripcaru** [comment]
> @andrei-scripcaru why did you switched to `next-translate`?

Switching the language was causing children (not sure exactly which ones) to re-render and there's no re-rendering with `next-translate`. I believe it has to do something with `getStaticProps` since if commented it works as expected.

**Comment by SalahAdDin** [comment]
> > @andrei-scripcaru why did you switched to `next-translate`?
> 
> Switching the language was causing children (not sure exactly which ones) to re-render and there's no re-rendering with `next-translate`. I believe it has to do something with `getStaticProps` since if commented it works as expected.

@isaachinman

**Comment by isaachinman** [comment]
@SalahAdDin What was the intention of the @?

If anyone can provide reproducible examples of faulty behaviour, issues will be fixed quickly.

**Comment by muhammadabdulazim** [comment]
any solution ?

**Comment by houssemmimoun27** [comment]
Create a file Translate.js 
import { useTranslation } from "react-i18next";

function Translate(props) {
  const { t } = useTranslation();
  return t(props.value);
}
export default Translate;

then add this function in the component 
 <Translate value="address" />
Thats solution fix the problem of rerendering the component.

**Comment by Poyoman39** [comment]
There is this effect in source code causing useTranslation to refresh the "t" function

```
  useEffect(function () {
    if (isMounted.current && !isInitial.current) {
      setT(getT);
    }

    isInitial.current = false;
  }, [i18n]);
```

**Comment by Poyoman39** [comment]
Guys ... could it be your bug ??? (this was mein)
https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode

Try disabling React.StrictMode !!!! ;)

**Comment by isaachinman** [comment]
@Poyoman39 That is not `next-i18next` code.

**Comment by npearson72** [comment]
I know this is a pretty old thread, but I've found that `useTranslation` causes a double render when the component is used within React Router.

**Comment by kasapvictor** [comment]
> з "react-i18ne

Only i18n - and we have 2 renders. Why?

https://codesandbox.io/s/i18next-10-rerender-not-fixed-4eydfm?file=/src/App.js

**Comment by allangrds** [comment]
The problem persists:

https://codesandbox.io/s/heuristic-agnesi-9t91nh

![Captura de Tela 2023-01-17 às 11 53 00](https://user-images.githubusercontent.com/4103305/212930994-8f1113da-9565-425a-8189-29fa95af2efa.png)

I now React's StrictMode will cause a double render, but if we divide the Children's render by 2, we'll still have a render.

**Comment by adrai** [comment]
without strict mode i see only 1 render:
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1086194/212998363-ab5a1527-d3d1-4737-aacb-15cc744f26a3.png">
