### ISSUE TITLE
Adding and retrieving router query params using exported Router instance.

### ISSUE THREAD

**Issue by mohamedraqeeb** [isaachinman/next-i18next#655]
## Describe the bug
I have used this library's Router instance to navigate to pages with query params. It navigates to page as expected. I can even read the query params from the navigated page. But once i refresh the browser from the navigated page i get the following error.
![image](https://user-images.githubusercontent.com/26220032/76940348-11662c00-6920-11ea-8117-097f11eda76c.png)

## Occurs in next-i18next version
4.2.0

## Steps to reproduce
1)Import Router instance from the library.
2)Navigate to page with query params
`Router.push({
      pathname: '/page',
      query: { orderOptions: JSON.stringify(orderOptions) },
    })`
3)Read query params from the navigated page.
`const options = Router.query?.orderOptions
    ? JSON.parse(Router.query.orderOptions)
    : {}`
4)Refresh the browser
## Expected behaviour
I should be able to read query params from the navigated page even after page refresh.
## OS (please complete the following information)
 - Browser: [ 80.0.3987.132 ]

**Comment by markolofsen** [comment]
same

**Comment by isaachinman** [comment]
Hi there, I have just released `next-i18next@8.0.0`, which uses the internationalised routing built into NextJs v10+. This new version of `next-i18next` is quite different, thus making this PR no longer relevant. Thanks!
