### ISSUE TITLE
Disable I18n redirect for /public assets

### ISSUE THREAD

**Issue by VictorBaudot** [isaachinman/next-i18next#656]
I have my website on example.com and example.com/fr and when I'm on /fr all my images and files coming from the /public folder are found but after a redirection to example.com/fr/img.jpg instead of example.com/img.jpg.

How can I disable those redirections for the files of the /public folder ?

**Comment by isaachinman** [comment]
You can use the `ignoreRoutes` option. It'll be much easier if you put non-root assets into a subpath.

**Comment by VictorBaudot** [comment]
@isaachinman 
> You can use the `ignoreRoutes` option. It'll be much easier if you put non-root assets into a subpath.
I already use this option, adding the public folder into it, but still the same redirections.
`ignoreRoutes: ["/_next/", "/static/", "/public/", "/api/"],`

I don't understand "It'll be much easier if you put non-root assets into a subpath." Can you explain a bit?

**Comment by isaachinman** [comment]
Adding the `public` directory to that array won't do anything. The `ignoreRoutes` array is for _routes_ to ignore. I suggest putting your assets inside `public/static`.
