### ISSUE TITLE
Request to public folder without lang prefix

### ISSUE THREAD

**Issue by denny7** [isaachinman/next-i18next#657]
Hello,
I would like to make requests to public folder without lang prefix. For example If I am in fr language (which is not default) to get logo I make request to http://localhost:3000/fr/images/logos/logo.svg. Because I want to cache all images in production I would like to make all image requests to  http://localhost:3000/images/... How can I achieve that. Thanks.

**Comment by isaachinman** [comment]
Duplicate of #656.
