### ISSUE TITLE
It conflicts with official apollo examples

### ISSUE THREAD

**Issue by ElForastero** [isaachinman/next-i18next#658]
First of all, I would like to thank everyone working on this package.
It's really nice library that gives a nice experience out of the box.  🙏

## Describe the bug
When trying to setup it with the official next.js apollo examples, it leads to broken SSR data fetching.
Spent a whole day trying to discover the problem.

It partially works this way: 

```tsx
import { I18nextProvider } from 'react-i18next';
import { i18n } from 'src/i18n';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <I18nextProvider i18n={i18n}>
      <Component {...pageProps} />
    </I18nextProvider>
  );
}
```

But I have said "partially", because client translations are broken. SSR works well in tandem with apollo, data is fetched on the server, but client translations behave strangely - languages are switched right after page load, some of the namespaces wasn't injected...

I don't have enough expertise in the next.js to dig deeper. But looks like the problem is in HOC that don't wait for the data.

## Occurs in next-i18next version
4.2.1

Technically this issue is a duplicate of #247 
But since it was closed almost a year age, I desided to open a new one.

**Comment by isaachinman** [comment]
There's no guarantee that various open source packages will be compatible. If you have specific suggestions I would be happy to hear them!
