### ISSUE TITLE
Add support for default language based on TLD

### ISSUE THREAD

**Issue by cereallarceny** [isaachinman/next-i18next#663]
## Is your feature request related to a problem? Please describe.
I understand there's support for localeSubpaths, but I'd rather use the TLD as the indicator of what the default language should be.

## Describe the solution you'd like
example.com --> default language is English
example.nl --> default language is Dutch
example.pt --> default language is Portuguese

Of course, the user should still be able to show preference to their default language. If they speak Russian as their primary language (defined in the browser), and we have a Russian translation (even if we don't have an `ru` TLD), then we should load the Russian translation. However, if we don't have a Russian translation, the default language should be scoped to the TLD.

## Describe alternatives you've considered
None at the moment because this functionality doesn't seem to be allowed

**Comment by kachkaev** [comment]
I solved it by adding a custom language detector: https://gitlab.com/kachkaev/website-frontend/-/blob/61c8c7559d204e4ec36bccbb9c008bb9fe6a9b38/src/i18n.ts#L34-44

Having this as a built-in feature would be useful indeed.

**Comment by cereallarceny** [comment]
Very interesting, I'll take a look. If this doesn't deserve to be a feature, since there's an existing solution, feel free to close the issue. Otherwise, I think it'd be a great addition!

**Comment by isaachinman** [comment]
This kind of functionality absolutely belongs in the custom detector realm. Thanks @kachkaev!
