### ISSUE TITLE
When page is loaded I see Russian translation, but in html-mode still english.

### ISSUE THREAD

**Issue by markolofsen** [isaachinman/next-i18next#664]
## Describe the bug
When page is loaded I see Russian translation, but in html-mode still english but should be Russian.

## Steps to reproduce
Check [this repo](https://github.com/markolofsen/i18next-demo)
`$ yarn dev`
open http://localhost:3000/ru

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by markolofsen** [comment]
In my sample query props are works!

Check [this repo](https://github.com/markolofsen/i18next-demo)
$ yarn dev
open http://localhost:3000/ru

What do we see? English translation in SSR, but should to be a Russian.

**Comment by isaachinman** [comment]
I assume that has something to do with your use of `next-routes`. Sorry, can't help much further as I have not personally used that package. Feel free to post on StackOverflow or similar. Good luck!

**Comment by markolofsen** [comment]
@isaachinman I solved it. Thanks
