### ISSUE TITLE
Query props is empty

### ISSUE THREAD

**Issue by markolofsen** [isaachinman/next-i18next#665]
## Describe the bug
Query props is empty. Strange.

## Steps to reproduce
Repo here: [https://github.com/markolofsen/i18next-demo](https://github.com/markolofsen/i18next-demo)
$ yarn dev
http://localhost:3000/en

If remove `localeSubpaths: localeSubpathVariations[localeSubpaths],` in `i18.js` then ok, but language detection from url is brokening.

## Expected behaviour
Income props should be:
```
query: {
  lang: 'en',
}
```
Now I'm getting `query {}`

**Comment by isaachinman** [comment]
You copied the example dir directly instead of learning from it: most likely `process.env.LOCALE_SUBPATHS` was undefined.
