### ISSUE TITLE
LocaleSubpath not working. What am I doing wrong?

### ISSUE THREAD

**Issue by monicasalamanca** [isaachinman/next-i18next#666]
I am not sure what else I can do to make the LocaleSubpath work. Translations work and actually there are no bugs in the code, but when I need to see http://localhost:3000/en or http://localhost:3000/fr. Nothing!

If someone can point me to the right direction, or if I am missing something, or if I am doing something wrong, I'll appreciate it very much.

[https://github.com/monicasalamanca/next-i18next-demo](url)

**Comment by isaachinman** [comment]
This is an issue tracker, not a help forum. It looks like you're using a custom `i18next-express-middleware` approach, so you'll need to debug for yourself. Good luck!
