### ISSUE TITLE
change cookie name

### ISSUE THREAD

**Issue by AAlhusaini** [isaachinman/next-i18next#668]
## Is your feature request related to a problem? Please describe.
the regular cookie name could allow attackers to identify the tech stack that im using therefore allowing the attacker to try vulnerabilities specific to nodejs

## Describe the solution you'd like
use a more generic cookie name having the package name in the cookie will tell the attacker a lot of information about the tech stack im using

## Describe alternatives you've considered
allow the user to add the language to a prexisting cookie this solution is unfavorable due to it being complex to implement 

# THANK YOU FOR CREATING THIS AMAZING LIBRARY YOU MADE I18N WITH NEXTJS POSSIBLE

**Comment by isaachinman** [comment]
Duplicate of #420. See [here](https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.ts#L30). No intention to change the cookie name at the source level. Plenty of OSS packages insert information into cookies and headers.
