### ISSUE TITLE
'browserLanguageDetection' option is not giving me the browser default language 

### ISSUE THREAD

**Issue by amr3ssam** [isaachinman/next-i18next#673]
this is my config component 

`const NextI18Next = require('next-i18next').default;

module.exports = new NextI18Next({
  browserLanguageDetection: true,
  defaultLanguage: 'de',
  otherLanguages: [ 'en', 'it', 'fr'],
  defaultNS: [],
  localeSubpaths: {
    de: 'de',
    en: 'en',
    fr: 'fr',
    it: 'it'
  },
  // workaround until next-i18next support public path
  // https://github.com/isaachinman/next-i18next/issues/523
  localePath: typeof window === 'undefined' ? 'public/locales' : 'locales'
});`

even so the website always taking the default language and not detecting the browser language . i even tried to remove the default language

**Comment by isaachinman** [comment]
Please provide a reproducible repository.
