### ISSUE TITLE
Not finding URL working with sub locales on production 

### ISSUE THREAD

**Issue by jatsgit** [isaachinman/next-i18next#674]
## Describe the bug
You must provide a clear and concise description of what the bug is.
not able to load the urls for the sub locales on production

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.
"next-i18next": "^4.2.1",

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.
Code I am using on production with npm run build && npm run export of similar repo
https://github.com/jatsgit/multi-doable-form

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.
Page should load find with url hit with sub locales, means to 
http://localhost:8080/id/ or http://localhost:8080/en/

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
<img width="812" alt="Screenshot 2020-04-01 at 21 27 28" src="https://user-images.githubusercontent.com/1294763/78148923-9e040480-745f-11ea-8d97-d0ce0f180790.png">

## OS (please complete the following information)
 - Device: Mac OS Mojovave 10.14.6
 - Browser: Chrome Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
It's port 3000, not 8080.

**Comment by jatsgit** [comment]
Its not related to port buddy 3000 I tried running with port still same.

**Comment by isaachinman** [comment]
Well then, I cannot reproduce. Because if I clone your repo, and do `npm i && npm run build && npm start`, I can see your web app at `http://localhost:3000/en/`.

**Comment by jatsgit** [comment]
First, thanks for replying. Its works that way even on my local, but if we
try building app using,  npm run build && npm run export and then I run
*out* folder using serve command, then issue comes what I mentioned and
same on Production environment i have deployed code from *out* folder and
running using port serve -l 8080, so its not working, sub locales, I am not
sure what i missed!

**Comment by isaachinman** [comment]
Oh, I see what you mean. Of course locale subpaths will not work with a static deployment - they depend upon an Express middleware. If you have any further questions please feel free to post on StackOverflow. Good luck!

**Comment by jsbimra** [comment]
Quick questions, I should deploy full code base how I run the app locally i
should run it same on prod too instead of deploying a static will it work
or i have remove serverless from target and rebuild the app and deploy?
