### ISSUE TITLE
Translations not working for Googlebot or Facebook

### ISSUE THREAD

**Issue by alexandrepaivaa** [isaachinman/next-i18next#675]
## Describe the bug
I'm exporting static HTML pages from Nextjs and Google/Facebook crawlers can't read the translations so my page title on Google searches is not being translated. When accessing the page through the browser the translation works fine.

## Occurs in next-i18next version
"dependencies": {
    "@tanem/react-nprogress": "^3.0.19",
    "@zeit/next-sass": "^1.0.1",
    "leaflet": "^1.6.0",
    "next": "9.2.2",
    "next-i18next": "^4.2.0",
    "node-sass": "^4.13.1",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-icons": "^3.9.0",
    "react-leaflet": "^2.6.3",
    "react-reveal": "^1.2.2"
  }

## Steps to reproduce
`<Head>
	<title>MyWebsite.com | {t('title')}</title>
</Head>`

## Expected behaviour
MyWebsite.com | Hi welcome to my website

but the title is being crawled as:

MyWebsite.com | title

How to fix that? Thank you

**Comment by isaachinman** [comment]
I suggest you read [the documentation](https://github.com/isaachinman/next-i18next#notes).

> next export will result in a client-side only React application.

**Comment by yonirosenbaum** [comment]
This doesn't seem to have been resolved
