### ISSUE TITLE
How to use this if default exporting doesn't work?

### ISSUE THREAD

**Issue by Leviathan91** [isaachinman/next-i18next#676]
I am trying to include this into an existing software app. The files which need translation already have an `export default`, so I cannot use `export default withTranslation('common')(LanguageExample)`.

But if I rewrite it to a regular export, of course it doesn't work and give me
`The default export is not a React Component in page: "/language"`:

Is there a workaround?
Apart from all that, this is exactly why people should avoid using default exports, there have been some articles about this already.

**Comment by Leviathan91** [comment]
Thanks for your help I guess?

**Comment by isaachinman** [comment]
Hi there. This is an issue tracker, not a help forum. Your questions seem to be general ones about how the JavaScript module system(s) work. Please post on StackOverflow. Good luck!
