### ISSUE TITLE
Not working on a Next.js app created using Expo, Cannot use import statement outside a module

### ISSUE THREAD

**Issue by 5ervant** [isaachinman/next-i18next#678]
## Description
I'm trying to use `next-i18next` to translate my Next.js app made with `@expo/next-adapter`: https://docs.expo.io/versions/latest/guides/using-nextjs/

## Occurs in next-i18next version
```
"dependencies": {
  "expo": "~36.0.0",
  "next": "^9.2.2",
  "next-i18next": "^4.2.1",
  // ...
}
```

## Steps to reproduce
* First is to create a `next-expo` app with this approach: https://docs.expo.io/versions/latest/guides/using-nextjs/#tldr
* Second is to implement `next-i18next`: https://github.com/isaachinman/next-i18next#setup

## Expected behavior
By implementing those, my `t('getting-started')` should now output the paragraph that's listed on my _"/public/static/locales/en/common.json"_ instead of just _"getting-started"_.

I'm also getting this terminal output even though my _"/public/static/locales/en/common.json"_ isn't empty:

```
react-i18next:: i18n.languages were undefined or empty _undefined_
```

Is it because of how we start our Next.js app, i.e. `yarn next dev`? https://docs.expo.io/versions/latest/guides/using-nextjs/#tldr

It should work by running it with `npm run dev`. But unfortunate, I'm getting this `SyntaxError: Cannot use import statement outside a module`:

```
> @ dev C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME
> node server.js

C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\src\apis\i18n-next.js:1
import NextI18Next from 'next-i18next';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\server.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `node server.js`
npm ERR! Exit status 1
```

## OS
 - Device: Windows 10
 - Browser: Chromium-based browser: 80.0.3987.122 (Official Build) (64-bit)

## Additional context
* "Using next.js?" section of `react-i18next` SSR documentation: https://react.i18next.com/latest/ssr#using-next-js
* "Using a custom server" section of Using Next.js with Expo for Web's Documentation: https://docs.expo.io/versions/latest/guides/using-nextjs/#using-a-custom-server
* My raised `expo-cli` issue related about this: https://github.com/expo/expo-cli/issues/1807

**Comment by adrai** [comment]
`react-i18next:: i18n.languages were undefined or empty _undefined_` comes from here: https://github.com/i18next/react-i18next/blob/4b61cfb2a28527b5714856cbff6164dabed9aa1d/react-i18next.js#L548
So seems like the languages are not initialized or the language detector does not work correctly 🤷‍♂️

**Comment by 5ervant** [comment]
@adrai Thanks for the help.

One of the contributors of `expo-cli` recommends not to create a custom Next.js server with Expo for Web, for now: https://github.com/expo/expo-cli/issues/1807#issuecomment-609096402

Any best alternative for the internationalization or translation of a serverless Next.js app?

**Comment by adrai** [comment]
https://stackoverflow.com/questions/59591125/initialize-i18next-in-azure-function/59634847#59634847

**Comment by 5ervant** [comment]
https://github.com/i18next/react-i18next/tree/master/example/react-native and not `next-i18next` will work.

**Comment by boogeymanCoder** [comment]
This may be late but for those who are looking for answer, I made it work somehow.
`
var NextI18Next =  require("next-i18next").default;
`
