### ISSUE TITLE
Server language detection not working in Safari (dependency update needed)

### ISSUE THREAD

**Issue by timonweber** [isaachinman/next-i18next#682]
## Describe the bug
Safari is sending the `Accept-Language` in a lowercase manner (e.g. `en-us`). Because the current used version of `i18next-express-middleware` detects this string as `en-` instead of `en` the sever language detection is not working as expected.

## Occurs in next-i18next version
4.2.1

## Additional context
This issue has been discussed [here](https://github.com/i18next/i18next-express-middleware/issues/171) and got fixed in `i18next-express-middleware@1.7.1`. Is it possible to bump the dependency to a recent version? Thanks!

**Comment by isaachinman** [comment]
@timonweber Presently, [this line](https://github.com/i18next/i18next-express-middleware/blob/master/index.d.ts#L9) creates a type clash between `next-i18next` and `i18next-express-middleware`, preventing that upgrade.

Any good with TS? Feel like contributing?

**Comment by timonweber** [comment]
@isaachinman Not good enough probably, I’m still learning. But I guess you solved that issue already by yourself. Thank you very much for the fast action! 🙂

**Comment by Kenpa** [comment]
It's still not working for me after updating to 4.3.0

**Comment by isaachinman** [comment]
@Kenpa Can you create a reproducible example? @timonweber Is the issue resolved on your end?

**Comment by Kenpa** [comment]
I just updated to 4.3.0, run next server.js (custom server), and still got english content instead of french in Safari... Works fine in Chrome and Firefox

**Comment by timonweber** [comment]
@isaachinman Sorry for the late reply. Unfortunately the problem is still present on my end. But I had a deeper look into it and it seems that this issue is not only related to the casing of the language string but also to the presence of a region code.

For example: When I configure an app with a default language of `en` and a subpath for both `en` and `de` I getting a redirect to `/en` when I send `Accept-Language: de-DE`. But when I send `Accept-Language: de` the redirection correctly points to `/de`. That’s odd because when I manually test the [original regex](https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/header.js#L16) of `i18next-express-middleware` everything gets detected as expected.

So this issue seems to be not only present in Safari, but in every client where the only parameter in `Accept-Language` contains a region code. For example: Chrome sends `Accept-Language: de-DE,de` so the second option is successfully matched.

But maybe this issue should be addressed to `i18next-express-middleware` directly, sorry for the inconvenience.

**Comment by isaachinman** [comment]
Check the [configuration options](https://github.com/isaachinman/next-i18next/pull/689). Specifically, `load: languageOnly`.

**Comment by timonweber** [comment]
@isaachinman Sorry, I totally missed that option! I tested it again and yes, everything is working as expected after the update. Both `Accept-Language: de-DE` and `Accept-Language: de-de` are correctly pointing to `/de`.

Thanks again! 🙂

**Comment by Kenpa** [comment]
@isaachinman Sorry, missed that option too! Works fine now! Just one thing that seems odd to me in Safari: when i try to get the current language with `i18n.language`, it also returns me the region, `en-US`, instead of only `en` in Chrome and Firefox

**Comment by isaachinman** [comment]
Please raise any questions like that via StackOverflow, or via the relevant i18next repository.

**Comment by ricamgar** [comment]
Hi @timonweber @isaachinman, could you please explain where to put that option to get the current language? Thanks!
