### ISSUE TITLE
Locize integration doc

### ISSUE THREAD

**Issue by samuelcastro** [isaachinman/next-i18next#685]
## Is your feature request related to a problem? Please describe.
Right now as far as I could see, there is no documentation about how to integrate with Locize.

## Describe the solution you'd like
I'd super helpful describe it or to have a simple Locize code example.

## Describe alternatives you've considered
Can't find anything

**Comment by isaachinman** [comment]
Not sure what you expect - they are categorically different things. There are many tools available for managing your translation content, and presumably any that can read/write JSON are compatible with `next-i18next`. The specifics of your own implementation will be up to you!

If you opened this issue because you intend to _add_ documentation about how to integrate with Locize, let's leave it open. Otherwise, please do post your question on StackOverflow or similar. Good luck!

**Comment by samuelcastro** [comment]
Thanks for the quick reply @isaachinman, so yes I'm integrating Locize and I think it could be helpful to have it documented here somewhere or even as a example code.

**Comment by isaachinman** [comment]
Okay, let us know how it goes!

**Comment by adrai** [comment]
@samuelcastro Aren't you just downloading the translations before you build your app?
something like: `locize download --project-id=locize-project-id --ver=latest --clean=true --path=./public/static/locales` => [locize-cli](https://github.com/locize/locize-cli#download-current-published-files)

**Comment by chris0610** [comment]
Please add an example on how to integrate Locize with Next.js

**Comment by adrai** [comment]
@chris0610 this is the example: https://github.com/isaachinman/next-i18next/pull/705/files#diff-298f611f00b8b2af48be7437472270aef3e5b04c22279ef40f1b85e418ab7662R1
but there is currently an issue => https://github.com/isaachinman/next-i18next/issues/854#issuecomment-707955951 (@cheunjm)

**Comment by chris0610** [comment]
I saw a [YouTube video](https://www.youtube.com/watch?v=kw-GEQbgmSc) where the Locize editor shows up and untranslated keys get sent to Locize automatically but there is a server.js file. Is that required for the above 2 features to work? Sorry, I'm new to this and thanks for the fast reply.

**Comment by samuelcastro** [comment]
The best way to use next + i8next + locize I found was through [Next Right Now](https://github.com/UnlyEd/next-right-now), and it does support serverless, it's a different and and opinionated approach, maybe @Vadorequest might add more info here.

**Comment by Vadorequest** [comment]
@chris0610 Depending on what you're working on and how familiar you're with Next.js, you might indeed take a closer look at Next Right Now. Whether you end up using it or just get inspired from it should save you a lot of time.

Regarding Locize + i18next, here is what we do:
https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/src/utils/i18n/i18nextLocize.ts

It supports auto key creation as you mentioned, those are only auto-created when working in localhost and having selected the main language.

General NRN documentation: https://unlyed.github.io/next-right-now/

**Comment by adrai** [comment]
> I saw a [YouTube video](https://www.youtube.com/watch?v=kw-GEQbgmSc) where...

The video was recorded on an older version of next-i18next.

The current working option is to:

- use [next-right-now](https://unlyed.github.io/next-right-now/)
- wait for this [PR](https://github.com/isaachinman/next-i18next/pull/861) to be merged and released and use next-i18next
- create your own thing

**Comment by chris0610** [comment]
Thank you @samuelcastro @adrai @Vadorequest ! Love the Github community. I was able to get Locize to auto translate from the reference language! But facing the https://github.com/isaachinman/next-i18next/issues/854 warning that is being worked on.

**Comment by isaachinman** [comment]
Is this issue still relevant?

**Comment by Vadorequest** [comment]
Maybe not? Wasn't it awaiting https://github.com/isaachinman/next-i18next/pull/861 to be merged? (which is the case now)

@isaachinman Maybe having an example would help close this issue definitively? That's what the OP asked for in the first place.

**Comment by adrai** [comment]
currently afk, but if using the i18next-http-backend as custom backend works, also i18next-locize-backend will work.

**Comment by Vadorequest** [comment]
I'm not sure that's compatible with the Next.js serverless mode. (`i18next-http-backend`)

**Comment by adrai** [comment]
@isaachinman is there an example using i18next-http-backend via [use option](https://github.com/isaachinman/next-i18next#options)?

**Comment by adrai** [comment]
> I'm not sure if that's compatible with the Next.js serverless mode. (`i18next-http-backend`)

If using the i18next-http-backend does not work, the only way to use locize with next-i18next is to download the translations and bundle them with the app: 

https://github.com/isaachinman/next-i18next/issues/685#issuecomment-624878789
https://github.com/isaachinman/next-i18next/pull/705/files#diff-298f611f00b8b2af48be7437472270aef3e5b04c22279ef40f1b85e418ab7662R19

**Comment by isaachinman** [comment]
I don't have an explicit example, but any i18next config should be possible. Passing `i18next-http-backend` into `config.use` should work.

**Comment by adrai** [comment]
@isaachinman can you check? https://github.com/locize/next-i18next-locize
especially if this is really needed: https://github.com/locize/next-i18next-locize/blob/main/next-i18next.config.js#L16

**Comment by isaachinman** [comment]
If the namespaces aren't present on the filesystem, `next-i18next` will have no way of knowing the complete list.

That being said, if you pass your namespaces correctly into `serverSideTranslations`, there would be no need to put namespaces into your top-level config.

**Comment by adrai** [comment]
> That being said, if you pass your namespaces correctly into `serverSideTranslations`, there would be no need to put namespaces into your top-level config.

tried... but that seems not to work... maybe you have a bit of time to check it yourself?

**Comment by isaachinman** [comment]
@adrai Yeah, that is correct – I misspoke. We are currently just checking against `config.ns`, and aren't doing any special logic in `serverSideTranslations` to pipe `namespacesRequired` into `config.ns`.

I'd suggest that the current behaviour is expected/appropriate, but am open to suggestions.

The total list of namespaces can either be:

1. Declared via filesystem
2. Declared via config

**Comment by adrai** [comment]
@samuelcastro do you think because of https://github.com/locize/next-i18next-locize this issue can be closed now?
