### ISSUE TITLE
Dynamic routes doesnt work in production

### ISSUE THREAD

**Issue by DziyanaYarmoliuk** [isaachinman/next-i18next#691]
Hi, guys! I integrated  next-i18next in my next app, and was run into problem with routes. 
So my case is:
in localhost when I'm starting app for developments, it works correct. But when I'm push it in server, all dynamic routes doesn't work, and I'm getting 404 error.

**Comment by isaachinman** [comment]
Probably a misconfiguration in your `package.json` scripts. Please provide a reproducible repository.

**Comment by DziyanaYarmoliuk** [comment]
my comands in package.json
`  "scripts": {
    "switch": "./scripts/switch-env.sh",
    "dev": "nodemon -w server.js server.js",
    "test": "node server.js",
    "export": "next export",
    "build": "next build",
    "start": "NODE_ENV=production node --max-old-space-size=8142 server.js",
    "fix-memory-limit": "cross-env LIMIT=2048 increase-memory-limit"
  },`
when I'm starting `npm run dev` or `node server.js ` it wirking. But `npm run build && npm run start` doesnt work. I'm getting 404 error for all dynamic pages. p.s. static pages are working correct at the same case.

**Comment by isaachinman** [comment]
Please provide a reproducible repository.
