### ISSUE TITLE
Firefox warning next-i18next cookie not secure

### ISSUE THREAD

**Issue by marco-000** [isaachinman/next-i18next#692]
I'm getting this warning in Firefox 76 with next-i18next 4.3.0:

`
Cookie “next-i18next” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies
`

**Comment by isaachinman** [comment]
Read [the docs](https://github.com/i18next/i18next-http-middleware#detector-options).

```
  // optional expire and domain for set cookie
  cookieExpirationDate: new Date(),
  cookieDomain: 'myDomain',
  cookieSecure: true // if need secure cookie
```

**Comment by martpie** [comment]
It looks like `SameSite` cannot be easily overridden: https://github.com/i18next/i18next-http-middleware/blob/5a2ee9a8188ce5d108ce3ee158054cf5ecb47d45/lib/languageLookups/cookie.js#L78-L83

I guess `cookieDomain` is the way to go for now.

Sidenote: because the config options are not merged, you'll need to re-add all the default options from next-i18next in your config:

```
new NextI18next({
  // ...
  detection: {
    lookupCookie: 'next-i18nextt',
    order: ['cookie', 'header', 'querystring'],
    caches: ['cookie'],
    cookieDomain: 'yourwebsite.com',
  },
})
```

**Comment by rparree** [comment]
I am not able to make this work, the `SameSite` remains `none`.

I'm using version 4.5.0

Here's my initisalisation code:

```js
const nextI18Next = new NextI18Next({
    defaultLanguage: 'en',
     otherLanguages: [],
    localePath: 'src/public/static/locales',
    localeSubpaths: {
        en: 'en',
    },
    serverLanguageDetection: false,
    // debug: true
    detection: {
        lookupCookie: 'lang',
        caches: ['cookie'],
        cookieExpirationDate: new Date().setMonth(new Date().getMonth()+2),
        cookieSameSite: 'strict',
    },
 

});

```

**Comment by martpie** [comment]
Yes, I need to submit a PR with the updated dependency, but we fixed it upstream.

**Comment by isaachinman** [comment]
@martpie We do [deep merge](https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L120) some nested objects. What sort of PR did you have in mind?

**Comment by martpie** [comment]
Didn't we want to backport this at some point? https://github.com/i18next/i18next-http-middleware/pull/8

**Comment by isaachinman** [comment]
@martpie We might just need to bump `i18next-http-backend` to v2.0.0?

**Comment by martpie** [comment]
should do the trick indeed 🤔

**Comment by isaachinman** [comment]
Looks like v3.0.2 is the latest. Do you want to open a PR, or shall I?
