### ISSUE TITLE
Locale Sub Path Question

### ISSUE THREAD

**Issue by samuelcastro** [isaachinman/next-i18next#694]
Hi, this is not a bug but a question about locale subpath, I'm not sure whether or not this is the best place to put it, sorry if it's not, so the question is:

What's the recommendation about whether or not we should use locale sub-paths, I've seen many sites using subpaths and others not, and this raises the question what's the best approach and what's the main difference between both approach (besides the additional path in the url).

Thanks!

**Comment by isaachinman** [comment]
The issue tracker of this repository is not the right place to ask that sort of question.

My personal opinion is: it depends. There is no real industry consensus, although splitting your different languages across _some sort_ of locale subpath/subdomain/domain is preferable for many reasons, most notably SEO.

**Comment by samuelcastro** [comment]
Thanks @isaachinman!

**Comment by samuelcastro** [comment]
Just to add some color, I found this that could be useful: https://webmasters.stackexchange.com/questions/403/how-should-i-structure-my-urls-for-both-seo-and-localization
