### ISSUE TITLE
Add custom language detector

### ISSUE THREAD

**Issue by lucasfeliciano** [isaachinman/next-i18next#7]
Is there a way to add custom detectors ?

https://github.com/i18next/i18next-express-middleware#adding-own-detection-functionality

I can always add them at the file that I'll export the i18n instance, but does it support these option object?

```js
detection: {
  order: [],
  cache: false
}
```

**Comment by lucasfeliciano** [comment]
Just took a look at the code and I saw how do you handle the options and think the best way to do it would be passing to options.

```js
options: {
  clientDetectors: [],
  ssrDetectors: []
}
```

I'll prepare a PR for that

**Comment by isaachinman** [comment]
#8
