### ISSUE TITLE
Error URLSearchParams is not defined when loading

### ISSUE THREAD

**Issue by DonovanCharpin** [isaachinman/next-i18next#702]
## Describe the bug
I updated the library, seems to work fine with my macbook and chrome browser but I have an Internal Server Error that occurs when I open the same url with my iPhone using Safari. I was not able to do more tests because I got the issue in production so I had to rollback. The trace below should help.

## Occurs in next-i18next version
It happens with the version v4.4.1

## Steps to reproduce
Seems to be linked to i18next-http-middleware library behaviour. To reproduce, update to the last version and open a website using next-i18next on Safari mobile. This bug happened in production though and I don't have more information on other browsers as I had to rollback asap.

## Trace
```
 "ReferenceError: URLSearchParams is not defined
    at Object.lookup (/opt/node_modules/i18next-http-middleware/cjs/languageLookups/querystring.js:18:25)
    at /opt/node_modules/i18next-http-middleware/cjs/LanguageDetector.js:95:56
    at Array.forEach (<anonymous>)
    at LanguageDetector.detect (/opt/node_modules/i18next-http-middleware/cjs/LanguageDetector.js:92:22)
    at i18nextMiddleware (/opt/node_modules/i18next-http-middleware/cjs/index.js:89:92)
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
```
## OS (please complete the following information)
 - iPhone Pro Max (13.4.1)
 - Safari

**Comment by adrai** [comment]
I've just released a new version of i18next-http-middleware with an additional querystring fallback... that should work also without URLSearchParams...
so, just `rm -rf node_modules` and `npm install` again...
But my question is: What is your server environment, not having URLSearchParams?
Which node.js version are you using? is it lower v10.0.0 ?

**Comment by isaachinman** [comment]
Yeah this is a curious one. The middleware shouldn't be running in browser envs, and even if it _were_, `URLSearchParams` is [supported by most iOS devices](https://caniuse.com/#search=URLSearchParams).

@DonovanCharpin Perhaps you can help us understand how you believe this is browser-specific?

**Comment by DonovanCharpin** [comment]
@adrai my environment is lower than 10.0.0, actually running 8.12.0. I think I will upgrade it soon!

@isaachinman The error was on the server side, but maybe created because of some headers sent by the browser? Also, I'm not 100% sure it's browser specific, maybe the server was sending me back a cache version on my chrome browser. That could be totally related to my node environment as @adrai mentioned.

**Comment by isaachinman** [comment]
Although Node 8 is no longer in LTS, it's nice to have fallbacks in place - thanks @adrai. I don't believe there's anything else to do here - @DonovanCharpin let us know if you feel otherwise.

**Comment by DonovanCharpin** [comment]
Thanks for your help.

FYI, I was updating my node and I was not in version 8.12.0 but 10.15.1. It was late, I don't know where I got this version from...
