### ISSUE TITLE
Simple test with Link component return Cannot update a component (`withI18nextTranslation(NextStaticProvider)`) while rendering a different component (`withI18nextSSR(MyApp)`)

### ISSUE THREAD

**Issue by alexllao** [isaachinman/next-i18next#703]
## Describe the bug
1.) When using the own component Link generates an error in the following landing page.
2.) When refresh routed "localhost:3000/es/test" entire page with F5, shows 404 error.
3.) i18n.languages were undefined or empty undefined

## Occurs in next-i18next version
Last version.

## Steps to reproduce
It is a very basic example that I have not uploaded to any repository. You can look at the code here.
https://www.dropbox.com/s/dy4bco6a25laebu/test-i18n.zip?dl=0
"npm install" and "npm run dev".

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
![imagen](https://user-images.githubusercontent.com/8004573/81060960-c7d39f80-8ed3-11ea-86cd-e3673552d0b0.png)

## OS (please complete the following information)
 - Device: MBP 2020 16
 - Browser: Firefox 75.0

**Comment by isaachinman** [comment]
Well, you haven't followed the documentation. You need to either use a custom server, or try out the beta/serverless release.
