### ISSUE TITLE
Help with basic server.js implemented using fastify

### ISSUE THREAD

**Issue by JuanSebastanCho** [isaachinman/next-i18next#706]
Hello, I have used i18n for a website but the express server is quite slow for the implementation. Could someone help me with a simple "server.js" to use in Next.js and i18n but using fastify server? Couldn't got it to work... Thank you :D

**Comment by isaachinman** [comment]
This is an issue tracker, not a help forum. Please post on StackOverflow or similar. Good luck!

**Comment by adrai** [comment]
https://github.com/i18next/i18next-http-middleware/blob/master/example/fastify/index.js
