### ISSUE TITLE
Wildcard or RegExp in ignoreRoutes

### ISSUE THREAD

**Issue by JohnCido** [isaachinman/next-i18next#709]
## Is your feature request related to a problem? Please describe.
> Locale subpaths enabled

I'm using [next-pwa](https://github.com/shadowwalker/next-pwa) with `dest: public` enabled, which generates two js files in /public directory dynamically. And since the sw.js is required strictly served from the server without any redirects, the problem comes with the `workbox-*.js`. I can't use * to disabled redirect for this file, so it's impossible for the service worker works correctly.

## Describe the solution you'd like

- Allow wildcard inside the paths like '/workbox-*.js'
- Allow RegExp in the ignoreRoutes

## Describe alternatives you've considered
I tried the server solution, but the files are still redirected to the locale subpath.

## Additional context
No.

**Comment by isaachinman** [comment]
Sounds reasonable - feel free to open a PR.

**Comment by ShadOoW** [comment]
> I tried the server solution, but the files are still redirected to the locale subpath.

There is an example project on how to implement the server solution: https://github.com/shadowwalker/next-pwa/tree/master/examples/next-i18next
I've just tried it, seems to works properly.
