### ISSUE TITLE
solving dynamic route issue

### ISSUE THREAD

**Issue by bahmanbs** [isaachinman/next-i18next#710]
## Is your feature request related to a problem? Please describe.

**** description ***********************************************
as you know, adding sub path to the route, will cause an error about matching "as" and "href" attributes.
because the folder structure will be different than "href" and "as" attributes
**** *********** ***********************************************

## Describe the solution you'd like

**** maybe solution *******************************************************
to resolve this, we must strongly assume that the developer who is installing and using the next-i18next, is going to make he's website available in several languages.

by this assumption, my suggestion is, to also add sub path for default language. this is what happened about microsoft's website.
the default language is microsoft.com/en-us

now by correcting folder structure, i believe next-i18next will work properly
*****************************************************************************

## Describe alternatives you've considered

the problem happens when we want switch from  <<  /blog/[page]  >>  to  <<  /en/blog/[page]  >> for example. 

the language param is not apart of our main route and by adding this param later, the problem happens.

but if i put for example [language] param as a global param in my folder structure, the problem will not happen any more i believe.

**Comment by isaachinman** [comment]
We won't be making any assumptions about users' locale subpath setups.

**Comment by bahmanbs** [comment]
thank you for your attention.

in the current version, what is the solution to use next-i18next with nextJs dynamic routing?
i couldn't find solution for this issue

i know we can not make any assumption about subpath .

it's obvious at the end, by using sub path, the url will be like this for default language /path/to/[page]
and for other languages it will be like /en/path/to/[page]

this makes problem by using dynamic routing
cause href and as are now invalid

by transfering the contents of pages folder to a subfolder like [language] , next-i18next will work without assue

at the end, the routes will be just like before.
but defalut language will be shown as a part of route


for the default language
/defalut-language/path/to/[page]
and for other languages it will be like 
/other-language/path/to/[page]

the difference will be just in default language.
