### ISSUE TITLE
"i18n.languages were undefined or empty undefined"

### ISSUE THREAD

**Issue by mateuspv** [isaachinman/next-i18next#712]
## Describe the bug
I'm facing a issue where `next-i18next` not always interpolating the translations.

On the video bellow, I'm using `t('description')` and `t('header.h1')`, but the values are not always interpolated.

Later, I open the same page on chrome incognito mod, on the first load the values are show correctly., eg:
t('description') -> `Hello i18n`
t('header.h1') -> `its working`

The console logs: `react-i18next:: i18n.languages were undefined or empty undefined`

Notes: 
1. this may be a bug on `react-i18next` itself.
2. My OS and Browser are using english lang.

**Video**:
https://www.dropbox.com/s/99zqlmm1pnx9809/Screen%20Recording%202020-05-13%20at%2011.41.44.mov?dl=0

## Occurs in next-i18next version
```
"next": "9.3.6",
"next-i18next": "4.4.2",
```
## OS (please complete the following information)
 - Device: Docker, Linux
 - Browser: Chrome  81.0.4044.138

## i18n.ts
```
import NextI18Next from 'next-i18next'

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  fallbackLng: 'en',
  otherLanguages: ['de']
})

export default NextI18NextInstance

```

## Server.js
```
import express from 'express'
import next from 'next'
import nextI18NextMiddleware from 'next-i18next/middleware'
import nextI18next from './i18n'

const port = process.env.PORT || 3000
const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler()

;(async () => {
  await app.prepare()
  const server = express()

  await nextI18next.initPromise
  server.use(nextI18NextMiddleware(nextI18next))

  server.get('*', (req, res) => handle(req, res))

  await server.listen(port)
  console.log(`> Ready on http://localhost:${port}`) // eslint-disable-line no-console
})()

```

## Locales json
```
web/public/static
└── locales
    └── en
        ├── auth.json
        └── common.json
```

## Page tsx
```
import React from 'react'
import i18n from '../../i18n'

interface Props {
  t: any
}

const Page = ({ t }: Props): JSX.Element => {
  return (<div>
    <h1>{t('description')}</h1>
    <h1>{t('header.h1')}</h1>
  </div>)
}

Page.getInitialProps = async () => ({
  namespacesRequired: ['header']
})

export default i18n.withTranslation('auth')(Page)
```

**Comment by isaachinman** [comment]
Please provide a reproducible example.

**Comment by mateuspv** [comment]
@isaachinman Tried again today and it works.
Meanwhile I've update my`nextjs` version and installed a fresh version of `getStaticProps`.

Thank you.
