### ISSUE TITLE
Cannot set headers after they are sent to the client - ^ 4.3.0

### ISSUE THREAD

**Issue by cfaure004** [isaachinman/next-i18next#716]
## Describe the bug
Error on server middleware (server.use(nextI18NextMiddleware(nextI18next))) when res.writeHead({ Location: "/" }) from _app.tsx happen in version  4.3.0 (next-i18next) but works fine in 4.2.0 (next-i18next)

## Occurs in next-i18next version
next-i18next - 4.3.0
yarn - 1.22.4

## Steps to reproduce
Basic setup and add res.writeHead(302, { Location: "/" }); in _app.jsx

## Screenshot
<img width="588" alt="Capture d’écran 2020-05-15 à 13 09 23" src="https://user-images.githubusercontent.com/23209488/82044264-5226bb00-96ad-11ea-8a11-05e9e4285417.png">

## Expected behaviour
Should work normally like in version  4.3.0 (next-i18next)

## OS (please complete the following information)
 - Device: MBP 2019 16
 - Browser: Chrome  81.0.4044.138

**Comment by isaachinman** [comment]
Please provide a reproducible repo.

**Comment by adrai** [comment]
Maybe related: https://github.com/i18next/i18next-http-middleware/pull/4#issuecomment-627270885

**Comment by cfaure004** [comment]
I'm sorry, i just noticed i give you the wrong version. The issue was happening on version  "next-i18next": "^4.3.0".

With 4.4.2, all works fine i just have a message "no possibility found to set header"

**Comment by kachkaev** [comment]
_no possibility found to set header_ is quite annoying, especially given that [it is printed unconditionally](https://github.com/i18next/i18next-http-middleware/blob/5f93b45243fa1cdf68e9d63b716a86d15ad7c9d0/lib/httpFunctions.js#L77), both in dev and prod 🤔 @cfaure004, did you manage to find the workaround or the root cause?

**Comment by adrai** [comment]
@kachkaev This is a different issue... The log comes from here: https://github.com/i18next/i18next-http-middleware/blob/master/lib/httpFunctions.js
PRs are welcome

**Comment by adrai** [comment]
Ahh you mean the second time... when the header is already sent...?
Will probably change the logic to return in that case

**Comment by adrai** [comment]
@kachkaev should be better with i18next-http-middleware@1.0.7

**Comment by kachkaev** [comment]
Many thanks for releasing the new version @adrai! I can confirm that I no longer see log statements with `i18next-http-middleware@1.0.7` and `next-i18next@4.4.2` 🎉

**Comment by adrai** [comment]
This must be somewhere in next-i18next or in userland... 🤷‍♂️
any help is welcome

**Comment by isaachinman** [comment]
We'll need @cfaure004 to provide a reproducible example.

**Comment by cfaure004** [comment]
About what ? The message "no possibility found to set header" ? 

This initial issue is not happening on latest version.

**Comment by cfaure004** [comment]
I think we can close this issue.

**Comment by adrai** [comment]
Can you create an example with the old version which reproduces the error?
This would be very helpful to investigate the root cause.

**Comment by cfaure004** [comment]
Ok no problem, i'll do that

**Comment by adrai** [comment]
👍 make sure you use i18next-http-middleware <= 1.0.6

**Comment by cfaure004** [comment]
On my side, i've always used middleware included in next-18next package

`const next = require('next')
const nextI18NextMiddleware = require('next-i18next/middleware').default`

**Comment by cfaure004** [comment]
I've been able to reproduced the message "no possibility found to set header" but not to reproduce the initial error

https://github.com/cfaure004/next-i18next-issues-716

**Comment by cfaure004** [comment]
Finally i've been able to reproduce the initial issue using i18next-http-middleware@1.0.4, all is in my repo 👍

**Comment by isaachinman** [comment]
> On my side, i've always used middleware included in next-i18next package

Yes, that's what you _should_ be doing. We need a repro of that, not using `i18next-http-middleware/cjs` directly.

**Comment by adrai** [comment]
thx @cfaure004 I found somethig... it's caused by the redirect... here: https://github.com/cfaure004/next-i18next-issues-716/blob/master/pages/_app.jsx#L48
which seems correct (I'm not a nextjs expert)...

I also found in i18next-http-middleware that certain header values can be set twice (because of the languageChanged event), so I tried to optimize this with i18next-http-middleware@1.1.0

**Comment by cfaure004** [comment]
> > On my side, i've always used middleware included in next-i18next package
> 
> Yes, that's what you _should_ be doing. We need a repro of that, not using `i18next-http-middleware/cjs` directly.

@isaachinman  I have not been able to reproduce the issue using previous versions of next-i18next library, i think it was an outdated dependency. I just created this exemple to help @adrai to identify where does the issue was coming from.

Great @adrai !
