### ISSUE TITLE
i18next - notReadyT - react-i18next:: You will need pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by d3tr1tus** [isaachinman/next-i18next#718]
Hi I want to use in my project translation and I made everythink just like in docs but in console I am getting warn 

```
react-i18next:: You will need pass in an i18next instance by using initReactI18next
```

and if I log props 

```
i18n: {}
t: ƒ notReadyT(k)
tReady: false
```

`home.ts`

```
export default withTranslation('common')(Home)
```

`i18n.js`

```
const NextI18Next = require('next-i18next').default

const languages = ['de', 'cs']

const NextI18NextInstance = new NextI18Next({
	defaultLanguage: 'en',
	otherLanguages: ['de', 'cs'],
})

NextI18NextInstance.i18n.languages = languages

module.exports = {
	default: NextI18NextInstance,
	withTranslation: NextI18NextInstance.withTranslation,
}
```

`server.js`

```
/* eslint-env node */
/* eslint-disable @typescript-eslint/no-var-requires */
const express = require('express')
const {join} = require('path')
const {parse} = require('url')
const compression = require('compression')
const nextI18NextMiddleware = require('next-i18next/middleware').default

const next = require('next')
require('dotenv').config()

const PORT = process.env.PORT || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({dev})
const handle = app.getRequestHandler()

const i18nextConfig = require('../src/i18n').default

app
	.prepare()
	.then(async () => {
		const server = express()

		if (!dev) server.use(compression())

		await i18nextConfig.initPromise
		server.use(nextI18NextMiddleware(i18nextConfig))

		server.get('*', (req, res) => {
			const parsedUrl = parse(req.url, true)
			const {pathname} = parsedUrl

			// handle GET request to /service-worker.js
			if (pathname === '/service-worker.js') {
				const filePath = join(__dirname, '.next', pathname)

				return app.serveStatic(req, res, filePath)
			} else {
				return handle(req, res, parsedUrl)
			}
		})

		server.listen(PORT, err => {
			if (err) {
				throw err
			}
			console.log('> Ready on http://localhost:' + PORT) // eslint-disable-line no-console
		})
	})
	.catch(ex => {
		console.error(ex.stack)
		process.exit(1)
	})
```

`composer.json`

```
    "start": "NODE_ENV=production node server/index.js",
    "build": "next build",
    "dev": "node server/index.js",
```

Can someone help me please?

**Comment by isaachinman** [comment]
You need to wrap your `_app`. Please follow the docs.

**Comment by d3tr1tus** [comment]
You are right! When I read docs I had to somehow skip this step. Thank you @isaachinman

**Comment by sandrooco** [comment]
I'm having this issue too but I properly wrapped it with `appWithTranslation`. 
I'm on next 10.0.7 and next-i18next 8.0.6. Any ideas?

**Comment by plevavas** [comment]
I'm having this issue too since i have updated react-i18next to 11.8.9 instead of 11.8.8.

**Comment by borispoehland** [comment]
Having the same issue even though I wrapped my app with the hoc.

**Comment by takirami** [comment]
Also having this issue, App is wrapped

**Comment by KingfishX23** [comment]
Same here. anyone tried previous versions?

**Comment by axelity** [comment]
I encountered the same issue until I realized I have forgotten to insert the following code on the page. Have a look in the simple example of this project, too. It is also mentioned in the READ.ME, but I was confused because of the title "serverSideTranslation", so I skipped reading this important part. BTW, it works with the latest versions of Next.JS and next-i18next.

Insert this code and add the names of your locale files to the array. It seems the default must have the name 'common.json'

```
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

// add your functional component here and don't forget to export it

export const getStaticProps = async ({ locale }) => ({
  props: {<br/>
    ...await serverSideTranslations(locale, ['common']),  
  },  
})

```

**Comment by Shariaty** [comment]
Despite wrapping _app, I receive react-i18next:: You will need to pass in an i18next instance by using initReactI18next
On the bottom of my _app.js file I do
export default wrapper.withRedux(appWithTranslation(MyApp));
However, I receive the above mentioned warning and the useTranslation returns NotReady
next Version : 10.0.9,
next-i18next Version : 8.1.2

**Comment by giacomoalonzi** [comment]
> Despite wrapping _app, I receive react-i18next:: You will need to pass in an i18next instance by using initReactI18next
> On the bottom of my _app.js file I do
> export default wrapper.withRedux(appWithTranslation(MyApp));
> However, I receive the above mentioned warning and the useTranslation returns NotReady
> next Version : 10.0.9,
> next-i18next Version : 8.1.2

Same here, I'm stuck!

**Comment by LauraBenz** [comment]
Same problem here.
It might make more sense to discuss this in an open issue that's why I opened one.

**Comment by KingfishX23** [comment]
> 
> 
> Despite wrapping _app, I receive react-i18next:: You will need to pass in an i18next instance by using initReactI18next
> On the bottom of my _app.js file I do
> export default wrapper.withRedux(appWithTranslation(MyApp));
> However, I receive the above mentioned warning and the useTranslation returns NotReady
> next Version : 10.0.9,
> next-i18next Version : 8.1.2

I have the same setup with redux but using compose from redux, as in:

```
import { compose } from 'redux'
...
export default compose(appWithTranslation, wrapper.withRedux)(MyApp);
```

yet my problem was solved by solving errors in getServerSideProps, and making sure to add these in the response props
```
props: {
   ... , //other props you have
   ...await serverSideTranslations(ctx.locale, ['library']),
},
```

**Comment by Shariaty** [comment]
@KingfishX23 
Thank you so much for your answer, However, I do not understand why should I use getServerSideProps and where exactly? in my _app.js cause I need translations in the header of my website? Is it mandatory to be used? What if I need to translate one of my simple static pages which do not need to implement any methods such as getServerSideProps when my translation files located in my public folder?

**Comment by sandrooco** [comment]
@Shariaty You might have misunderstood the purpose of next - the goal is to "render" the translation into the template **on the server** so the client receives a complete html with content and doesn't have to load/parse/display translations.
`getServerSideProps` allows you to load data, in this case the translations, on the server.

**Comment by mdegrees** [comment]
@sandrooco Next js comes also with [persisting components](https://nextjs.org/docs/advanced-features/custom-app), how would one go about this?

**Comment by Shariaty** [comment]
@mdegrees This is exactly my question too

**Comment by mdegrees** [comment]
@Shariaty here is the fix https://github.com/isaachinman/next-i18next/issues/1118#issuecomment-813344424

**Comment by spyshower** [comment]
For anyone not getting useTranslation ready, I moved

```
export const getServerSideProps = async ({ locale }) => {
  const fs = require('fs');
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
    },
  }
};
```

from my page-level component in `src`, to `pages` (`footer` in the case). Also, here's my config:

_app.js:

```
import '../styles/globals.css'
import { appWithTranslation } from 'next-i18next'
import nextI18NextConfig from '../next-i18next.config.js'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default appWithTranslation(MyApp, nextI18NextConfig)
```

next-i18next.config.js:

```
const path = require('path')
const { initReactI18next } = require('react-i18next');
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'el'],
  },
  serializeConfig: false,
  use: [ initReactI18next ]
}
```

next.config.js:

```
const { i18n } = require('./next-i18next.config')

module.exports = {
  webpack: (config, { isServer }) => {
    // Fixes npm packages that depend on `fs` module
    if (!isServer) {
      config.node = {
        fs: 'empty'
      }
    }

    return config
  },
  i18n
}

```

**Comment by Steffi3rd** [comment]
Hello guys, 

I had the same issue, and found why I had this warning : 
`react-i18next:: You will need to pass in an i18next instance by using initReactI18next`


The error was cause by the fact one of my component had an useTranslation whereas this component what no

Here is my _app.tsx 👍

**Comment by Steffi3rd** [comment]
Hello guys 👋

I had the same issue, and found why I had this warning :
`react-i18next:: You will need to pass in an i18next instance by using initReactI18next`

The warning was caused by `useTranslation` inside my component `<Navigation />`. In fact, this component is not a child component of my page component (which use `serverSideTranslations`).

So, I guess if you try to use `useTranslation` in your components but sure that those components are children of a page component (_/pages/*.tsx_) with the props `serverSideTranslations`.

**Problem :** 
Here is my `_app.tsx` : 

```
function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Navigation /> // In my case, this component has an useTranslation('common') and causes this warning.
      <Component {...pageProps} />
    </>
  )
}
```

**Solution :** 
My solution is to move down `<Navigation />` to my `<Component />`

**Comment by samfromaway** [comment]
I solved the issue by overwriting to NOT use the new webpack 5, instead use webpack 4.
I did it this way, maybe there is a better way.

next.config.js

`module.exports = {
  webpack: config => config,
  }`
  
  That's probably also why @Steffi3rd 's solution worked.

**Comment by keremcanb** [comment]
I'm getting this warning as well. I tried using Webpack 4 instead of 5 as the above user suggested, but it didn't help.

Also, my deployment works fine on Heroku, but Vercel throws 404 not found errors. When I look at logs, Heroku has this warning 1 time and Vercel 3 times. I think Vercel 404 error is related to next-i18next and maybe because of this specific warning.

**Comment by natterstefan** [comment]
> @Shariaty here is the fix [#1118 (comment)](https://github.com/isaachinman/next-i18next/issues/1118#issuecomment-813344424)

Hi @Shariaty,

can you explain that in more detail, please? How does this resolve https://github.com/isaachinman/next-i18next/issues/718#issuecomment-813328844?

Thanks for your help. I appreciate it.

**Comment by BrandonEscamilla** [comment]
Is there a solution for this? I am trying to use useTranslation hook within my layouts and it's not working, I would like to know If there is a way to use the hook within _app.tsx?

**Comment by laclance** [comment]
did you try adding `serverSideTranslations` to _app?

**Comment by isaachinman** [comment]
You cannot add `serverSideTranslations` to `_app`.

**Comment by VityaSchel** [comment]
What is the point of using this library if you have to write

```js
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common']),
  },  
})
```

in every page where you use t()? Not even in components? If you can't write it in _app and reduce files size? If you can't customize locales folder structure? 
Am I really seeing such a popular module that is not maintained but used by majority of translated websites built on next.js? Is there any built-in technical next.js limitation preventing you from stop using getStaticProps on every page? 
Is it possible to add repeating getStaticProps to next.config? Maybe with babel plugin? Is it possible to use \<Component /\> props to pass translations object to all pages?

**Comment by VityaSchel** [comment]
Also I just found that you have to restart server everytime localization file changed, and https://github.com/felixmosh/i18next-hmr/ is not working after next-i18next update.

**Comment by sandrooco** [comment]
@VityaSchel If everything is so bad and a library with 176k weekly downloads and monthly releases is unmaintained in your opinion: just do it yourself, develop an alternative solution.

Also: fk russia

**Comment by VityaSchel** [comment]
> @VityaSchel If everything is so bad and a library with 176k weekly downloads and monthly releases is unmaintained in your opinion: just do it yourself, develop an alternative solution.
> 
> Also: fk russia

I'm not skilled enough to develop native modules for next.js and in my opinion it's far easier to maintain existing repository instead of creating similar from scratch

crimea is russian 🇺🇦+🇷🇺=🇷🇺

**Comment by laclance** [comment]
> You cannot add `serverSideTranslations` to `_app`.

so how do i useTranslation() in _app?

**Comment by bryantobing12** [comment]
getting this warning when running `next build` 

This warning happens when I have translation inside `next.js` layout
https://nextjs.org/docs/basic-features/layouts

It's working fine in local, only in build

I wrap my component like this
```
<Layout>
    <Component {...pageProps}/>
</Layout>
```
