### ISSUE TITLE
Using Link with getServerSideProps page will be reloaded

### ISSUE THREAD

**Issue by hieusmiths** [isaachinman/next-i18next#721]
## Describe the bug
I'm use Link of Next/link and i have a page with getServerSideProps.
When click page not reload => as well
Then i config with myapp.com/lng/news
At right i change Link's Next to Link of i18n
Then i click into it news will be reloaded.

I cannot understand how to reload -.-.

Thank you so much

**Comment by mercteil** [comment]
This is way too less information to be able to help.
