### ISSUE TITLE
ref error for functional children of the Link component

### ISSUE THREAD

**Issue by ckeeney** [isaachinman/next-i18next#723]
## Describe the bug
If you have a functional component child of the `<Link/>` component created by `new NextI18Next()`, the following error is logged to the console:

```js
react-dom.development.js:88 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `Context.Consumer`.
    in A (created by Context.Consumer)
    in EmotionCssPropInternal (created by Link)
    in Link (created by Link)
    in Link (created by withI18nextTranslation(Link))
    in withI18nextTranslation(Link) (created by withnextI18NextInternals(withI18nextTranslation(Link)))
    in withnextI18NextInternals(withI18nextTranslation(Link)) (created by NavLink)
    in NavLink (created by Header)
```

## Occurs in next-i18next version
```
next-i18next@4.2.1:
  version "4.2.1"
  resolved "https://registry.yarnpkg.com/next-i18next/-/next-i18next-4.2.1.tgz#6ace3a58fb72ef4ae73451e4df32f1437bb5579d"
  integrity sha512-77FCTcBj+36tm3K8iUTYRbBVlc/qM+rnQw23hm7czgNj0Jp+yynxE/w4I1cFWUmGh7VjrfadKVl8b+u6t4AoWg==
```
## Steps to reproduce

This is the code in my repo that demonstrates the problem.  
```js
import React from 'react';
import { Link } from '../../i18n';

const MyFunctionalA = ({ children, href }) => (
  <a
    href={href}
  >
    { children }
  </a>
);

const NavLink = ({ href, children }) => (
  <Link href={href}>
    <MyFunctionalA>
      {children}
    </MyFunctionalA>
  </Link>
);

```

## OS (please complete the following information)
 - Device: Windows 10
 - Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

## Additional context
- Related next.js issue: https://github.com/zeit/next.js/issues/7915
- Related next.js discussion: https://github.com/zeit/next.js/discussions/11764

Wrapping the functional component with `react.forwardRef()` is a workaround, but ideally this would be fixed upstream from consumers of this library.

**Comment by isaachinman** [comment]
Hi there, I have just released `next-i18next@8.0.0`, which uses the internationalised routing built into NextJs v10+. This new version of `next-i18next` is quite different, thus making this PR no longer relevant. Thanks!
