### ISSUE TITLE
Prevent settings cookies to static files

### ISSUE THREAD

**Issue by geryit** [isaachinman/next-i18next#725]
## Describe the bug
Cookies are set to images/css for some reason (see set-cookie tab).  This is preventing cloudflare to cache files by default.

<img width="970" alt="Screen Shot 2020-05-27 at 2 52 13 PM" src="https://user-images.githubusercontent.com/514149/83076092-cd7f5980-a029-11ea-8dbb-f1a508bca544.png">

## Occurs in next-i18next version
version: 4.4.2

## Steps to reproduce
server.js
```js
const nextI18NextMiddleware = require("next-i18next/middleware").default;
const nextI18next = require("./src/i18n");
(async () => {
  await app.prepare();
  const server = express();
  await nextI18next.initPromise;
  server.use(nextI18NextMiddleware(nextI18next));
})
```

i18n.js
```js
const NextI18Next = require("next-i18next").default;
module.exports =new NextI18Next({
  defaultNS: "website",
  defaultLanguage: "en",
  otherLanguages: ["es","zh"],
  load: "languageOnly",
  nsSeparator: false,
  keySeparator: false,
  react: {
    wait: false,
    useSuspense: false,
    transKeepBasicHtmlNodesFor: [],
  },
})
```

**Comment by isaachinman** [comment]
Please use `ignoreRoutes`.

**Comment by geryit** [comment]
Same with `ignoreRutes`
```
const NextI18Next = require("next-i18next").default;
module.exports =new NextI18Next({
  defaultNS: "website",
  defaultLanguage: "en",
  otherLanguages: ["es","zh"],
  load: "languageOnly",
  nsSeparator: false,
  keySeparator: false,
  react: {
    wait: false,
    useSuspense: false,
    transKeepBasicHtmlNodesFor: [],
  },
  ignoreRoutes: ['/_next/', '/static/', '/public/', '/api/', '/static/'],
})
```

**Comment by isaachinman** [comment]
@geryit What exact paths are receiving cookies?

**Comment by geryit** [comment]
All files under `/static` and `/_next` like `/static/css/site.css`

**Comment by geryit** [comment]
> @geryit What exact paths are receiving cookies?

All files under /static and /_next like /static/css/site.css

**Comment by isaachinman** [comment]
@geryit Please have a read through https://github.com/isaachinman/next-i18next/issues/374. Let me know what you think!

**Comment by geryit** [comment]
> @geryit Please have a read through #374. Let me know what you think!

I dont see this error `react-i18next:: i18n.languages were undefined or empty undefined`

Everything works good except cookies are set to static files

**Comment by isaachinman** [comment]
[These](https://github.com/isaachinman/next-i18next/pull/541/files) are the exact changes required to fix that bug.

Those are also the exact changes that cause the cookie behaviour you are describing.

**Comment by geryit** [comment]
> [These](https://github.com/isaachinman/next-i18next/pull/541/files) are the exact changes required to fix that bug.
> 
> Those are also the exact changes that cause the cookie behaviour you are describing.

Didn't understand what I should change exactly. Do I need to play with `ignoreRoutes` ?

**Comment by hassench** [comment]
Same issue. I don't understand why there is a `set-cookie` on static resources like images

**Comment by isaachinman** [comment]
@hassench Cookies are no longer handled by `next-i18next` whatsoever.
