### ISSUE TITLE
namespacesRequired even for components that are not using withTranslation

### ISSUE THREAD

**Issue by stopyransky** [isaachinman/next-i18next#726]
## Describe the bug
I get multiple warnings when navigating to pages that do not use translations by design. 

## Occurs in next-i18next version
4.4.2

## Steps to reproduce

1. Create a page.tsx in /pages with translation like below
```
import { i18n, withTranslation } from '../i18n';

const Page = ({ t }) => (
   <div>
        <h1>{t('welcome')}</h1>
        <button onClick={() => i18n.changeLanguage(i18n.language === 'en' ? 'pl' : 'en')}>
           {t('change-locale')}
        </button>
    </div>
);

Page.getInitialProps = async () => ({namespacesRequired: ['common'] })
export default withTranslation('common')(Page);
```

2. Create other page2.tsx without use of i18n. 
```
export default () => (<p>No translation here</p>);
```

When Page2  loads the warning is present saying that it's missing the `namespacesRequired` in Page2.

## Expected behaviour
Pages that do not use withTranslation HOC should not cause the warning.

## Additional context
In my app i have many pages and some of them do not have translation. It should be fine for next-i18next to ignore components that do not use translations.

**Comment by isaachinman** [comment]
Hi there. You can either set `strictMode` to `false`, or feel free to submit a PR. Thanks!

**Comment by mkkeffeler** [comment]
adding a little color, all this does is get the warning out of the console. the effects are still present. I too ran into this error and have not found a solution, so just wanted to share that yes the above will resolve the error in your console, but it will still load all namespaces.
