### ISSUE TITLE
Some locales may not be getting recognized appropriately

### ISSUE THREAD

**Issue by darosale** [isaachinman/next-i18next#727]
## Describe the bug
When setting a locale to 'ja-jp', the locale is not getting recognized correctly and reverts to the set defaults instead.

## Occurs in next-i18next version
4.4.2

## Steps to reproduce
Specify 'ja-jp' as a language in 'otherLanguages' in your config. Switch locale to 'ja-jp'.

## Expected behaviour
The locale should get recognized and handled respective to configuration. 

## Screenshots
![Screen Shot 2020-06-01 at 5 58 08 PM](https://user-images.githubusercontent.com/3640410/83462903-03f61380-a432-11ea-858b-d7749830cecb.png)

## OS (please complete the following information)
 - Browser: This appears to affect all browser.

## Additional context
Initially I was testing Safari and could not get Japanese translations to render. Safari uses 'ja-jp' as the locale code instead of 'ja'. I tested on Chrome 83.0.4103.61 using custom locales and was able to reproduce the issue. To ensure this was not a config issue, I tested using a custom locale 'ffff' and this was handled appropriately.

**Comment by isaachinman** [comment]
Sounds like potentially an upstream i18next issue. The `next-i18next` package doesn't do any sort of locale validation. Please do open this issue in the respective i18next repo.
