### ISSUE TITLE
Ability to append localeSubpaths after a subdirectory

### ISSUE THREAD

**Issue by colloquet** [isaachinman/next-i18next#728]
Hi,

Thanks for the awesome library, however I am having a hard time trying to achieve a certain effect.

Here's my current setup:
- My app will be hosted on a domain like this: `app.myapp.com/dashboard`
- Nginx will reverse proxy `/dashboard` -> `localhost:3000`

Here's what I am trying to achieve:
- When user navigate to `app.myapp.com/dashboard` or `app.myapp.com/dashboard/users`, it should automatically redirect to `app.myapp.com/dashboard/en` or `app.myapp.com/dashboard/en/users`

I noticed that instead of redirecting to `app.myapp.com/dashboard/en`, it redirects to `app.myapp.com/en/dashboard`. I assume this is because the library only account for hosting at the root directory, that's why it's adding the localeSubpath at the first `/` occurance.

So my question is, is there any ways to treat `app.myapp.com/dashboard` as a base path? Like all the redirections and url manipulations should take into account that the app is hosted under a subdirectory?

**Comment by isaachinman** [comment]
Sure that should be possible, but is mostly an nginx and NextJs concern - not specific to `next-i18next`. Good luck!
