### ISSUE TITLE
i18n cloned instance affects original instance

### ISSUE THREAD

**Issue by andfk** [isaachinman/next-i18next#730]
I've tried to use multiple `I18nextProvider` as `react-i18next` [suggest](https://react.i18next.com/latest/i18nextprovider#when-to-use) in order to force a language for a specific container. I do cloning the original instance `i18n.cloneInstance({ lng: 'de' })` but doing this the global language gets changed too, so i think there should be a way to prevent this behavior to happen. 

PS: At first it may look it works as expected in the codesandbox example but there is cookie lang change and sometimes it renders the cloned instance lang instead on first page load.

## Occurs in next-i18next version
`4.4.2`

## Steps to reproduce
https://codesandbox.io/s/next-i18next-multiple-providers-59oq2?file=/pages/index.js:760-912

There is a clone instance of i18n in `:10` of index.js that gets passed to the second provider.

## Expected behaviour
The cloned instance shouldn't affect the global state.

Hopefully i get some light to create a PR to prevent the cloned instances to no affect the global state if possible.

Many thanks for all the work done with this module!

**Comment by isaachinman** [comment]
What is your use case here? I think supporting this sort of functionality would require rethinking some of the patterns in place. You may be better off using `react-i18next` directly.

**Comment by andfk** [comment]
@isaachinman my use case is to force an specific portion of a page in a specific language instead of the detected by `next-i18next` but the issue exposed above happens. I'll follow your suggestion and use the base library directly. Hopefully at some point later i came with a solution and create a PR. 

Many thanks for your help!
