### ISSUE TITLE
Support for Subnamespaces on SSR

### ISSUE THREAD

**Issue by dingxizheng** [isaachinman/next-i18next#732]
## Is your feature request related to a problem? Please describe.
Currently I'm using one translation file per page and the way how I manage the files is like this:
```
public/static/locales
  - en
    - common.json
    - my-account/info.json
    - my-account/payment.json
    - my-account.json
```
Client side works fine but pages with subroutes (e.g. `my-account/info`) are not translated on SSR .

## Describe the solution you'd like
Preload files in subdirectories at init time

## Describe alternatives you've considered
Currently, the only alternative to me is stop using nested namespaces and putting all files under the same language root folder

## Additional context
No.

**Comment by haggen** [comment]
@isaachinman I just tested it now and it still doesn't work on SSR, but once on the client it loads another language just fine. Why was it closed?

**Comment by isaachinman** [comment]
Hey @haggen, I assume this is related to #874? Let's just track the fix in upstream i18next packages.
