### ISSUE TITLE
404 with localeSubpaths for all routes with locale included.

### ISSUE THREAD

**Issue by stelasido** [isaachinman/next-i18next#733]
All URLs with locales return 404.
For the example: 
http://localhost:3000/de/second-page = 404
http://localhost:3000/en/second-page = 404
http://localhost:3000/de = 404
http://localhost:3000/en = 404

http://localhost:3000/second-page = 200
http://localhost:3000 = 200

This is from your sample, but and in my project is the same, with or without custom server .
* you can try it with your sample.

Is this library supports locales in URL or I need to search another ?

**Comment by isaachinman** [comment]
We've got both e2e tests and a running application that all have this functionality. Please either post a reproducible repo, or request help on places like StackOverflow. Good luck!

**Comment by pixelass** [comment]
@stelasido did you figure this one out? We are having the same problem (currently investigating)

**Comment by pixelass** [comment]
In our case, we were missing this snippet: in next.config.js

```
 publicRuntimeConfig: {
      localeSubpaths:
        typeof process.env.LOCALE_SUBPATHS === "string"
          ? process.env.LOCALE_SUBPATHS
          : "none",
    },
```
