### ISSUE TITLE
Translation of content inside _document.js

### ISSUE THREAD

**Issue by charlieshumsa** [isaachinman/next-i18next#734]
I have a custom _document.js in my implementation and there are some content need to be translated

When I use withTranslation() on the Document class component, the t function fails to get the values

When I use the i18n object to get the current language, it returns undefined

What is the proper way to translate the component returned by _document.js?

**Comment by isaachinman** [comment]
It's been discussed several times before - please do search issues before posting. However, the short answer is that this isn't directly possible, as the i18next provider is wrapped over `_app`, which is one layer "beneath" `_document`. There are workarounds, though! Good luck.
