### ISSUE TITLE
Serverless Dynamic Routing with LocaleSubpath not working

### ISSUE THREAD

**Issue by sebastienlabine** [isaachinman/next-i18next#735]
## Describe the bug
When using the serverless version of next-i18next, dynamic routing works fine without locale subpaths, but as soon as we add localesubpaths to the i18n config we get 404 on both the index and [slug] pages. Also, we can't create a production build because we get this error:

![image](https://user-images.githubusercontent.com/8888846/84405277-ea915c00-abd5-11ea-9748-358c735cf38c.png)

## Occurs in next-i18next version
Beta

## Steps to reproduce
**i18n.js**
```javascript
const NextI18Next = require('next-i18next').default
module.exports = new NextI18Next({
  localePath: "public/locales",
  otherLanguages: ['fr'],
  localeSubpaths: { en: "en", fr: "fr" },
  defaultLanguage: "en",
  shallowRender: true,
})
```

**next.js**
```javascript
const { nextI18NextRewrites } = require('next-i18next/rewrites')

const localeSubpaths = { en: "en", fr: "fr" },

module.exports = {
  publicRuntimeConfig: {
  localeSubpaths
},
  experimental: {
    async rewrites() {
      return [
        ...nextI18NextRewrites(localeSubpaths)
      ]
    }
  }
}
```
**[slug].tsx**
```typescript
class Test extends React.Component<WithTranslation & { slug: string }> {
    public render() {
        return (
            <Fragment>
                test
            </Fragment >
        );

    }
}
export const getStaticProps = async (context) => {
    return {
        props: {
            slug: "test"
        }
    }
}
export const getStaticPaths = async () => {
    return {
        paths: [{
            params: {
                slug: "test"
            }
        }],
        fallback: false
    };
}
export default withTranslation()(Test);
```

## Expected behaviour
Show dynamic pages with localsubpath in url.

## Additional context
The same problems occurs without adding nextI18NextRewrites in the next config. Also, next seems to hang forever when accessing directly the /[slug.tsx] instead of the /[lang]/[slug]

**Comment by isaachinman** [comment]
Mind providing a reproducible repo?

**Comment by sebastienlabine** [comment]
There you go: [https://github.com/sebastienlabine/next-i18next-bug](https://github.com/sebastienlabine/next-i18next-bug). You should not be able to access /blog & /blog/lol when localesubpaths are enabled.

**Comment by sebastienlabine** [comment]
Were you able to reproduce? @isaachinman

**Comment by isaachinman** [comment]
@sebastienlabine Just taking a look now. If anything, this potentially looks like an issue with the actual `rewrites` functionality coming from NextJs. I don't see any hanging when accessing `/blog/lol` directly - I get an immediate redirect to `/en/blog/lol`, which then 404s.

Can you take a read through https://github.com/vercel/next.js/discussions/9081, and check out some of the other people using dynamic routing?

We may want to adapt `nextI18NextRewrites` to optionally take some information about dynamic paths, but you should definitely be able to pass that route info in on your own.

Good luck!

**Comment by sebastienlabine** [comment]
I took a dive in the issue and seems like there's not so much information related to this. To be honest, i'm out of my field with everything releated to NextJs.

**Comment by isaachinman** [comment]
@sebastienlabine There are some examples of "advanced rewrites" in the discussion which I linked above:

```jsx
// Advanced rewrite
// Query object shape: { id: string } (in addition to dynamic route param)
{ source: "/u/:id", destination: "/user/:id" }
```

However, I'd caution that the serverless beta of `next-i18next` and the core NextJs `rewrites` functionality are both still under development, so if you're new to the space I would suggest going with more well-established methods of translating your app(s).

I took a deeper look at your repo, and found that if you actually set up your `next.config.js` correctly, most things work as expected:

```jsx
const { nextI18NextRewrites } = require('next-i18next/rewrites')

const localeSubpaths = { en: "en", fr: "fr" }

module.exports = {
  publicRuntimeConfig: {
    localeSubpaths
  },
  experimental: {
    async rewrites() {
      return [
        ...nextI18NextRewrites(localeSubpaths),
      ]
    }
  }
}
```

From there, we only have issues with the `/blog/[slug]` route - a dynamic route. The first thing to do when poking around is to set `fallback: true`. If you do that and try to load the page, you'll see the following error:

```
Server Error
Error: Rewrites don't support dynamic pages with getStaticProps yet. Using this will cause the page to fail to parse the params on the client for the fallback page 
```

So, this is an upstream NextJs issue. For the time being, I'd suggest you simply just _don't_ use `getStaticProps`.
