### ISSUE TITLE
Weird errors on server restart

### ISSUE THREAD

**Issue by GainorB** [isaachinman/next-i18next#736]
## Describe the bug

Not sure if these errors are happening at any other time, but I notice them when I make a change when developing and the server restarts.

## Occurs in versions

next-i18next: ^4.4.2
next: 9.4.1

## Steps to reproduce

Let me know what to provide to give more context on this issue. Unfortunately, I can't provide a repo. 

## Expected behaviour

I don't expect this error to happen when server restarts (or at any other point)

## Screenshots

<img width="1035" alt="Screen Shot 2020-06-11 at 12 52 17 PM" src="https://user-images.githubusercontent.com/26068225/84416904-d9028100-abe2-11ea-9369-ad654938074a.png">

<img width="1015" alt="Screen Shot 2020-06-11 at 12 52 29 PM" src="https://user-images.githubusercontent.com/26068225/84416939-e455ac80-abe2-11ea-8d92-13c28d7bce5a.png">

<img width="1209" alt="Screen Shot 2020-06-11 at 12 56 58 PM" src="https://user-images.githubusercontent.com/26068225/84417040-10712d80-abe3-11ea-86b4-91891815b962.png">

## OS (please complete the following information)
 - Device: MBP 2019 15"
 - Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by isaachinman** [comment]
Mind providing a reproducible repo?

**Comment by GainorB** [comment]
> Mind providing a reproducible repo?

Unfortunately, I can't provide a repo, but I can provide code snippets if you know where I should look
