### ISSUE TITLE
Rendering twice when first page is loaded

### ISSUE THREAD

**Issue by aykr01** [isaachinman/next-i18next#737]
## Describe the bug
Hello, thanks for all the hard work on this project. 

I was working with the simple example and I noticed an intermittent issue that seems to be occurring in both Chrome and FF. When any page is initially loaded, it looks like the pages are occasionally rendered twice. This seems to be only occurring for me on the client side.

This can be reproduced by duplicating the simple example and inserting a console.log in the main component in any page (Homepage and SecondPage components in the example). Doing a hard refresh on the page a few times (less than 10 in my case) is usually sufficient to show the console.log displaying twice on the client side. In these cases the server will show only a single log message, while the client shows the log message twice.

I also noticed whenever the double render occurs the client side network traffic shows 21 requests. When it is functioning correctly (only a single render/log message) there are only 20 requests. The extra file in the double render situation is common.json.

## Occurs in next-i18next version
4.4.2

## Steps to reproduce
1. Duplicate the example/simple found in the repo.
2. Add a console.log("page rendered") just above the return statement in the main page component for both pages (index.js and second-page.js - screenshots for reference).
3. Launch the application and do a hard refresh until the console logs display "page rendered" twice in a row.

## Expected behaviour
Expected behaviour is that the "page rendered" log message would only show once after a hard refresh.

## Screenshots
package.json
![Screen Shot 2020-06-17 at 12 49 26 PM](https://user-images.githubusercontent.com/67066692/84926239-165e8700-b099-11ea-9af5-787c7049505e.png)

page component with console.log
![Screen Shot 2020-06-17 at 12 51 39 PM](https://user-images.githubusercontent.com/67066692/84926390-4efe6080-b099-11ea-9496-640edef33384.png)

Single render (expected behavour)

![single_render](https://user-images.githubusercontent.com/67066692/84927135-67bb4600-b09a-11ea-8b34-408f80b66525.png)

Double render
![double_render](https://user-images.githubusercontent.com/67066692/84927185-786bbc00-b09a-11ea-90ea-712a39d6416a.png)

## OS (please complete the following information)
 - Device: MBP 2015 15"
 - Browser: Chrome 83.0.4103.97, Firefox 77.0

**Comment by isaachinman** [comment]
Looks like `common.json` is getting loaded in, in the second case, indicating the translations for some reason are not present. Can you reproduce this in prod mode, or just dev?

**Comment by aykr01** [comment]
Thanks for the quick response. It looks like it's happening in both dev and prod mode. It seems much less frequent in prod with Chrome. However, the double render is happening on every reload in FF with prod mode.

**Comment by isaachinman** [comment]
I do see two render cycles in prod, as you described. However, I am not concerned about this on its own - this could be caused by any number of things.

I would be concerned if `common.json` was being fetched after a client side load in prod, but I cannot reproduce that behaviour.
