### ISSUE TITLE
Refactor to Typescript

### ISSUE THREAD

**Issue by Nelrohd** [isaachinman/next-i18next#74]
Hello,

Just as a reference for later since I didn't find one ticket dedicated to typescript.

Thanks.

**Comment by kachkaev** [comment]
Hi @Nelrohd! You can find some thoughts in #42 (there is currently a TS compatibility issue with what i18n.js exports)

**Comment by isaachinman** [comment]
As I've stated in various places, I prefer to have single issues for single bugs / feature requests. Let's discuss Typescript support here.

Thanks @Nelrohd, we're looking forward to your suggestions and assistance!

**Comment by tkow** [comment]
I locate this definition file in my project as the library is external module.

```next-i18nnext.d.ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

declare module 'next-i18next' {
  import {ComponentType, ReactNode} from 'react'
  import {Trans,withNamespaces} from 'react-i18next'
  import App from 'next/app'
  type UserConfig = Omit<Config,'ns'|'backend'|'preload'>
  interface Config {
    defaultLanguage: 'string'
    otherLanguages: string[]
    preload: string[]
    fallbackLng: string|null
    load: string
    localePath: string
    localeStructure: string
    localeSubpaths: boolean
    ns: string[]
    use: any[]
    interpolation: {
      escapeValue: boolean
      formatSeparator: string
      format(value:string, format:string):string
    },
    browserLanguageDetection: boolean,
    ignoreRoutes: string[],
    detection: {
      order: string[],
      caches: string[],
    },
    backend: {
      loadPath: string,
      addPath: string,
    },
    react: {
      wait: boolean,
    },
  }
  interface LinkProps {
    as?: string
    children: ReactNode
    href: string
  }
  export default class NextI18Next {
    constructor(userConfig:UserConfig);
    appWithTranslation<Props=any>(WrappedComponent:App<Props>):App<Props>;
    withNamespaces: typeof withNamespaces
    config: Config
    Trans: typeof Trans
    Link: ComponentType<LinkProps>
  }
  export {App}
}

declare module 'next-i18next/middleware' {
  import {default as NextI18Next, App} from 'next-i18next'
  export default function <Server=any,Props = any>(nexti18next:NextI18Next, app:App<Props>, server:Server):void;
}
```
This can be applied with some modifications as internal modules' definition.
I think we can do it split this to dist/middleware/index.d.ts and next-i18next/index.d.ts and change declare to export .

**Comment by isaachinman** [comment]
I have not previously used Typescript on any significant projects, but will very soon be beginning professional work with it. I'd prefer to wait on this for awhile, and potentially properly convert the whole project.

Until then, if someone does want to create a PR with typings that does not affect any of the codebase, I'd happily accept it.

**Comment by tkow** [comment]
I apologize that middleware second argument is not next/app's App, so I modified above example as App is typeparameter.

**Comment by tkow** [comment]
I have found my .d.ts file  wrong. This library are exported in commonjs modules and not using module.exports.default, thus  we must import the way like
```
import * as NextI18Next from 'next-i18next';
```
or
```
with module.exports.default = NextI18Next
"allowSyntheticDefaultImports": true, 
```
 are needed about tsconfig.json and index.js.
So, above my .d.ts is not correct. Sorry for that and try to fix it.

**Comment by isaachinman** [comment]
Hi @tkow, c424b06 should fix that import issue.

**Comment by isaachinman** [comment]
I briefly started to look into TypeScript conversion on a branch called `typescript-conversion`. As expected it's going to be a relatively lengthy process to get all the types laid out and working nicely together. Some of the approaches currently taken may need to be completely rethought out as well.

If anyone feels like championing this effort, I can provide collaborator access. Otherwise I'll handle this myself slowly over several weeks.

**Comment by capellini** [comment]
I would love to learn some TypeScript, but would be starting at the ground floor (as in I have programmed in typed languages before C/C++/Java, but never TypeScript) and, so, probably am not the best person to champion this effort.  I'm more than willing to help out, though.

**Comment by isaachinman** [comment]
I'm rethinking if this is appropriate prior to a 1.0 release. We've got a lot else going on at the moment, and a TypeScript rewrite is going to be a very intensive activity. I'll post in this thread when I have updates.
