### ISSUE TITLE
Help: Want to include html tags in a translation

### ISSUE THREAD

**Issue by ElGoorf** [isaachinman/next-i18next#740]
Hi

Thanks so far for your effort making this plugin. I have a text which needs to be translated, which contains a link and some other formatting, eg:

`"Go to the <a...>home page</a> and enter <span class=...>this code</span>"`

I want to make this translatable, right now I have the string broken down into it's individually translatable parts, but in practise this won't make sense as the parts might break down differently per language. 

Do you have any examples which show how this can be done?

Thanks.

**Comment by isaachinman** [comment]
Please read the [react-i18next docs](https://react.i18next.com/latest/trans-component).
