### ISSUE TITLE
i got two different version of Link.js warning

### ISSUE THREAD

**Issue by handrei** [isaachinman/next-i18next#743]
## Describe the bug
i have this warning after i installed next-i18next 

warn  - ./node_modules/next/Link.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
- here i got two different versions of Link.js, one from next and on from your package.

## Occurs in next-i18next version
"next-i18next": "^4.5.0",

## OS (please complete the following information)
 - Device: [e.g. MBP 2017 15"]
 - Browser: [e.g. Chrome ]

**Comment by isaachinman** [comment]
Sorry, I don't understand what you mean. Can you explain further, or provide a reproducible repo?

**Comment by handrei** [comment]
so, i installed the next-i18next package and configured and when i run yarn dev i receive a warning in the console.
the warning is this:
warn - ./node_modules/next/Link.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /path_to_app/node_modules/next/Link.js
    Used by 1 module(s), i. e.
    /path_to_app/components/navigation/desktop/Desktop.js
* /path_to_app/node_modules/next/link.js
    Used by 1 module(s), i. e.
    /path_to_app/node_modules/next-i18next/dist/commonjs/components/Link.js

**Comment by isaachinman** [comment]
Take a look in `path_to_app/node_modules/next`. There is no `Link.js` file. It's `link.js`.
