### ISSUE TITLE
Is there a way to make localeSubpaths from the beta compatible with getStaticPaths/-Props?

### ISSUE THREAD

**Issue by borispoehland** [isaachinman/next-i18next#747]
> The use of `publicRuntimeConfig` is mostly to facilitate e2e tests internally. How you propagate `localeSubpaths` is entirely up to you.

@isaachinman is there an alternate way (you can think of) to propagate `localeSubpaths` that's **compatible** with `getStaticPaths`?

_Originally posted by @borispoehland in https://github.com/isaachinman/next-i18next/issues/274#issuecomment-636643671_

**Comment by isaachinman** [comment]
Why not hard code it, or treat it as any other variable?

**Comment by borispoehland** [comment]
The problem is this snippet:
```
experimental: {
    async rewrites() {
      return [
        ...nextI18NextRewrites(localeSubpaths),
      ];
    },
  },
```
because it calls `res.writeHead`, which is not available with pages prerendered with getStaticProps/getStaticPaths.
The build-error is: `TypeError: res.writeHead is not a function`

Can you think of any solution or workaround?

**Comment by isaachinman** [comment]
@borispoehland I don't understand what you mean. `localeSubpaths` is just a normal JavaScript object.

**Comment by borispoehland** [comment]
Yes, I know. 

When running `next build` with localeSubpaths being empty, everything works fine.
When running it with localeSubpaths being populated, the `TypeError: res.writeHead is not a function` is thrown.

I don't know **why** this is the case, tho...

**Comment by isaachinman** [comment]
Can you provide a reproducible repo?

**Comment by borispoehland** [comment]
Yes, here: https://github.com/borispoehland/next-i18next-getStaticProps-Error

npm run build leads to an error.

Thanks Isaac for investigating!!

**Comment by isaachinman** [comment]
@borispoehland Very strange that they don't provide a stack trace with that error.

Anyways, it looks like the problem here is that `redirectWithoutCache` relies on `res.writeHead` (naturally), and this is incompatible with a fully static app. If you want locale subpaths, we need some sort of server (or serverless) runtime in which we can execute a redirect when necessary.

Hope that makes sense!

**Comment by borispoehland** [comment]
@isaachinman but my app isn't fully static, only one single page of it is (the page with getStaticProps).

I'm relatively new to next.js, for the particular situation that I'm stuck in, can you provide some configurational workaround?

**Comment by isaachinman** [comment]
We cannot generate a static page _at all_ if you desire `localeSubpaths`. That's just a natural conclusion of the functionality itself.

There is no workaround - the redirect functionality has to exist at some level. If you wanted a static app that still supports `localeSubpaths`, you'd need to move that functionality up a level, and rewrite it at, for example, an nginx level.

**Comment by borispoehland** [comment]
@isaachinman thanks, that's the clear answer I was looking for! 

Fortunately, I was able to replace `getStaticProps` with an API call. So I basically found a workaround myself, but I wanted to make sure that they are indeed incompatible (localeSubPaths and getStaticProps)

Thank you for your support!

**Comment by isaachinman** [comment]
No problem. The question of redirects is an interesting one, and may end up being the last piece of the puzzle when it comes to static/SSG locale subpath support. I can discuss with the NextJs team.

Good luck with your project!

**Comment by borispoehland** [comment]
@isaachinman Is there a bank account of you that I can donate some euros to? I think you make great work

**Comment by isaachinman** [comment]
@borispoehland You can sponsor my work via GitHub sponsors, or contact me directly via email. Thanks!
