### ISSUE TITLE
Add optional assetPrefix when used via CDN

### ISSUE THREAD

**Issue by nsmith7989** [isaachinman/next-i18next#748]
## Is your feature request related to a problem? Please describe.
In my setup we use a CDN and NextJS's option `assetPrefix`. We have several different nextjs apps all running on the same origin and we add an assetPrefix so our CDN knows which origin to route the requests back to. We strip the assetPrefix when we statically serve the resource. 

## Describe the solution you'd like
We'd like to do the same with next-i18next and provide an asset prefix that affects the clientSide loadPaths only. 

Add a new option called `assetPrefix` that gets prepended to the client here: https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L88, but not the server fs backend as that a disk path.

## Describe alternatives you've considered
I tried changing `localePath` but that affected the server fs backend as well. 

## Additional context
I'd be happy to open a PR if you feel this is the right solution. Thanks, and I really appreciate this package!

**Comment by isaachinman** [comment]
I don't really understand - why not just do something like this:

```jsx

**Comment by nsmith7989** [comment]
Good idea. Thanks, I'll do what you suggested.
