### ISSUE TITLE
i18n-fs-backend causes problems

### ISSUE THREAD

**Issue by borispoehland** [isaachinman/next-i18next#750]
## Describe the bug
Hi again,
today, [next.js proposed an idea of how to make serverless deployments to vercel work. ](https://github.com/vercel/next.js/issues/13624#issuecomment-655326365). However, when trying to deploy to vercel using [this minimal boilerplate](https://github.com/borispoehland/next-i18next-boilerplate), the lambda function still complains: `Cannot find module 'i18next-fs-backend/cjs'`

Of course I then tried several things:
- Include i18next-fs-backend as plugin --> cannot resolve 'fs'
- Setting 'fs: empty' in the webpack config -->  [ERR_REQUIRE_ESM]: Must use import to load ES 

I think I'm missing a part of the puzzle. It'd be great if you could try to get my boilerplate deployed to vercel.

All these errors can be reproduced (including stack trace) by deploying to vercel using [my boilerplate](https://github.com/borispoehland/next-i18next-boilerplate)

## Occurs in next-i18next version
See boilerplate

## Steps to reproduce
- Clone boilerplate
- Deploy to vercel
- Check realtime function logs

## Expected behaviour
Deployment to vercel works

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Sure, I will take a look as soon as I have a chance. Joe's response makes sense.

**Comment by isaachinman** [comment]
I'm going to close this, as it will be handled by the general serverless effort.

**Comment by manhthepixta** [comment]
Same issue here. Any updates?

**Comment by borispoehland** [comment]
Yes, check out this project:

https://github.com/isaachinman/next-i18next-vercel

Not that in order for it to work, you need the beta 5.0.0-beta.3

**Comment by manhthepixta** [comment]
@borispoehland Thanks a lot. It works.
I installed latest beta `5.0.0-beta.4`
