### ISSUE TITLE
Server Error TypeError: namespacesRequired.push is not a function

### ISSUE THREAD

**Issue by kaleemullah-innovo** [isaachinman/next-i18next#751]
i am using Next.js with react and redux and my app.js return is 
// import "./styles/styles.css";
import Header from "../components/Header/Header";
import { createStore } from "redux";
import reducer from "../store/reducers/reducers";
import PropTypes from "prop-types";
import { Provider } from "react-redux";
import { I18nextProvider } from "react-i18next";
import { appWithTranslation } from "../i18n";
// This default export is required in a new `pages/_app.js` file.
const store = createStore(reducer);
const App = ({ Component, pageProps }) => {
  return (
    <React.Fragment>
      <Header />
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
      <Header />
    </React.Fragment>
  );
};
export default appWithTranslation(App);
![Screenshot (116)](https://user-images.githubusercontent.com/64018535/86959712-c2b2fb00-c177-11ea-8743-db39593ca94a.png)

**Comment by isaachinman** [comment]
Please post on StackOverflow for help. This is an issue tracker. If you feel as though you've found a genuine bug, please open a detailed bug report.
