### ISSUE TITLE
how to write namespacesRequired when you have other things in getInitialtProps ?

### ISSUE THREAD

**Issue by handrei** [isaachinman/next-i18next#752]
## Describe the bug
how to write the namespacesRequired when you already have an getInitialProps like this ?

Component.getInitialProps = async ({ req }) => {
  const { origin } = absoluteUrl(req);

  return { origin };
};

I tried to write it twice but it doesn't take the first one

**Comment by isaachinman** [comment]
This is an issue tracker, not a help forum. Please post on StackOverflow or similar. Good luck!
