### ISSUE TITLE
Still doesn’t support Now 2.0?

### ISSUE THREAD

**Issue by JerryGreen** [isaachinman/next-i18next#754]
I’ve just read the readme, and it sounds weird that Now 2.0 isn’t supported. Is that still true? Or is it just outdated readme?

The lib seems to be alive, maintainable, so I wonder

**Comment by isaachinman** [comment]
Just outdated. "Now" doesn't exist anymore, and Zeit has rebranded as Vercel.

As of #274, `next-i18next@beta` supports serverless platforms. As soon as it's determined to be stable enough, we'll release it in v5.
