### ISSUE TITLE
Multiple namespaces don't work 

### ISSUE THREAD

**Issue by beqramo** [isaachinman/next-i18next#756]
when i use ``   const { t, i18n } = useTranslation(['common', 'header']);`` for example, ``t``  functions don't work for the strings which is in second element of the array,  if I switch places it works well. Btw both namespace is  loaded in ``i18n.store.data`` object but don't work

I use 
```tsx
Home.getInitialProps = async () => ({
  namespacesRequired: ['header', 'common'],
});
```

and  ``t`` function as 

```tsx
{t('title')} // where title is in header.json file
```

**Comment by paulintrognon** [comment]
I am having a similar problem with `.withTranslation([])` HOC. Only the first namespace is working.

For example:
```typescript
const Foo = ({ t }) => <p>{t('fromTest1')} ; {t('fromTest2')}</p>
export default withTranslation(['test1', 'test2'])(Foo)
// Will output "<p>Translated Test 1 ; fromTest2</p>"
```

whereas
```typescript
const Foo = ({ t }) => <p>{t('fromTest1')} ; {t('fromTest2')}</p>
export default withTranslation(['test2', 'test1'])(Foo)
// Will output "<p>fromTest1 ; Translated Test 2</p>"
```

**Comment by isaachinman** [comment]
Please read the i18next documentation. You will need to denote the second (non default) namespace with a colon separator.

**Comment by JasonLamv-t** [comment]
I have another solution for using multiple namespaces in the same file：
```ts
# in page
export const getStaticProps = async ({ locale }: { locale: string }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common', 'test1', 'test2'])),
  },
});

# in page or component
const { t } = useTranslation('common')
const t1 = useTranslation('test1').t
const t2 = useTranslation('test2').t
```

I just started using i8next. I don't know if this is in line with the specification. But It works well in my project.

**Comment by GoldJns** [comment]
For me it worked after taking a look at the docs regarding defaultNS/fallbackNS
https://www.i18next.com/overview/configuration-options


```
const namespaces = ["foo", "bar"];
// then
  .init({
    ns: namespaces,
    supportedLngs,
    fallbackNS: namespaces, => all namespaces as fallback, if this is configured key will always be found
    defaultNS: [],
    resources: i18nResources,
    fallbackLng,
  });
```
