### ISSUE TITLE
Cookie options get overwritten 

### ISSUE THREAD

**Issue by borispoehland** [isaachinman/next-i18next#757]
## Describe the bug
Hi, I set some cookie options inside the `detection` object. However, when loading the page, even though the options are set to the cookie (e.g. `cookieSecure true, cookieSameSite strict`, I could see that in my browser console flickering up for a second), the cookie instantly gets overwritten with another cookie that doesn't have this options set (`cookieSecure false, cookieSameSite none`) 

## Occurs in next-i18next version
5.0.0-beta.4

## Steps to reproduce
Take the next-i18next vercel project, change the detection options and check the browser's cookie tab.

## Expected behaviour
The cookie shouldn't get overwritten with the "standard" cookie any time the page loads or the language changes

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
Can you provide a reproducible repo? Is this specific to the beta release, or can you repro on `master` as well?

**Comment by borispoehland** [comment]
Hi Isaac,
The same thing happens on the master. I tested this on your (normal) simple example. The reproducible example is your next-i18next-vercel project: https://github.com/isaachinman/next-i18next-vercel

**Comment by isaachinman** [comment]
Can you reproduce the issue with just `react-i18next`? I'm not sure how this could be a `next-i18next` bug, as we don't explicitly handle anything cookie-related.

**Comment by borispoehland** [comment]
I don't use react-i18next, so no idea. I don't know if react-i18next also has this "everything renders twice" problem, but I think that's our problem. 

The first render sets the cookie correctly and the second render overwrites it with the default configuration

**Comment by isaachinman** [comment]
I assume this is because you're setting `cookieSecure: true`. Secure cookies aren't visible to the browser, so the client side app is setting the cookie separately.

**Comment by borispoehland** [comment]
Okay, so now I tried the following configuration:

```
detection: {
   cookieSameSite: "strict"
}
```

On the master, it works fine. On the beta, however, it doesn't work. So even though turning off secure solved a part of the problem, the beta still has a problem, I guess

**Comment by isaachinman** [comment]
Relevant: https://github.com/i18next/i18next-http-middleware/pull/8. @adrai Any idea if we've had a regression here in `i18next-http-middleware`?

**Comment by adrai** [comment]
afk...
would be nice to have an example with i18next-http-middleware only, if this is the problem

**Comment by borispoehland** [comment]
I investigated the problem further and not only sameSite isn't working, but all detection options. E.g. using cookieExpirationDate also doesn't work, but once again, it flashes shortly before it gets overwritten with the standard config.

When unactivating the browserLanguageDetection, all options start working again, but that brings up a new problem: The cookie isn't updated anymore when the page changes.

**Comment by adrai** [comment]
Can you debug where the problem could be?
is it on clientside? Serverside?
Is it on passing options for i18next-browser-language-detector or on i18next-http-middleware?
Or while creating the options?

I have only my mobile phone with me currently. 🤷‍♂️

**Comment by borispoehland** [comment]
@adrai certainly I'd like to help, but unfortunately I neither know anything about i18n, nor I know how to debug next.js applications at all...

It'd be nice if anyone of you could take a look at this **when you have time**, until then I can wait, no problem. I think, provided that you can reproduce that problem, that this is something that'll affect many to all users.

Maybe someone else reads this that knows more or shares the same problem?

**Comment by isaachinman** [comment]
@borispoehland If you can provide a reproducible repository that I can clone and debug directly, as well as a description of the exact problem you are experiencing, I would be happy to debug it.

**Comment by borispoehland** [comment]
@isaachinman Thank you very much, I appreciate it.

Here's the link: https://github.com/borispoehland/next-i18next-cookie-problem

The problem is documented inside the i18n.js file. If you have any leftover questions, just ask.

**Comment by isaachinman** [comment]
So, this just looks to me like an inconsistency in the i18next world. The `config.detection` options are being consumed by `i18next-http-middleware` on the server side, but then consumed by `i18next-browser-languageDetector` on the client side, and the config API is not 1:1.

@adrai What are your thoughts?

@borispoehland To be absolutely clear, `cookieSecure` will _never_ work, and there's no good reason to want to set `cookieExpirationDate`. Setting `cookieSameSite` seems completely reasonable, though.

**Comment by borispoehland** [comment]
@isaachinman but when I don't set an expiration date, then it's only a session cookie. What when I want my user to land on the right language after being absent for a few days? Isn't that a use case where `cookieExpirationDate` could be useful?

**Comment by adrai** [comment]
Ohhhhh. You are passing the same detection options to both libs?
I don't think this is a good idea...
need to ask @jamuhl

**Comment by isaachinman** [comment]
Well, we initialise an i18n instance both on the server and client, and the two packages mentioned above both look into the `config.detection` object. It appears like intentional design from the i18next side to have client/server parity. If that's wrong, let's discuss via Slack/email.

**Comment by adrai** [comment]
I would separate them, but I don't think having to separate options will change this...
Isn't one executed in client and the other on server side?
Can you check what happens, when you set the options individually?

**Comment by isaachinman** [comment]
Sorry, just now coming back to this. It doesn't look like conditionally setting the options based on server/client env makes any difference (as expected).

I cannot get `i18next-http-middleware` to set a `sameSite` cookie with any set of config options at all, actually. @adrai Any ideas?

**Comment by adrai** [comment]
Can you create a test, like: https://github.com/i18next/i18next-http-middleware/blob/master/test/languageDetector.js#L38 or a reproducable example with i18next-http-middleware only?

**Comment by isaachinman** [comment]
So, I think I've figured this out – at least the root problem, not necessarily a solution.

First, the i18next deps needed to be updated. I think that's going to need to result in another major for `next-i18next`.

Secondly, `i18next-browser-languageDetector` cannot be used if we want to do `cookieSameSite: 'strict'`. I haven't dug into why this is, but at the `next-i18next` level, if we upgrade the i18next deps and set:

```
config = {
  browserLanguageDetection: false,
  detection: {
    ....stuff
    cookieSameSite: 'strict',
  }
}
```

Everything seems to work as expected. @adrai Any thoughts?

**Comment by adrai** [comment]
I have no idea...

Can you elaborate on what does not work, when using `cookieSameSite: 'strict'`?

I just now, i18next-browser-languageDetector and i18next-http-middleware use both the same lookupCookie name 'i18next', maybe manipulating (in the client) the same cookie, that was requested by the server is not always allowed?

**Comment by isaachinman** [comment]
For anyone coming across this in the future: from v6.0.0 and onward, if you simply set `browserLanguageDetection` to `false`, the `SameSite` value will remain `Strict`.

@adrai We do still have the problem of `i18next-http-middleware` and `i18next-browser-languageDetector` presenting inconsistent behaviour, though. Let me know if you need any help – to see the error simply clone this repo and run the example without any changes.

**Comment by adrai** [comment]
> @adrai We do still have the problem of i18next-http-middleware and i18next-browser-languageDetector presenting inconsistent behaviour, though. Let me know if you need any help – to see the error simply clone this repo and run the example without any changes.

What should I look at in the example to see the error?

**Comment by isaachinman** [comment]
Firefox tends to have good dev tools – if you open the example in FF you will see a warning in the console about the `SameSite` usage. If you then set `browserLanguageDetection` to false in `examples/simple/i18n.js`, you'll see that the issue is resolved. Essentially, `i18next-browser-languageDetector` is overwriting the cookie in an unexpected way when it inits on the client.

**Comment by adrai** [comment]
Ok, I think this is not because of options overwrite...
I try to explain:
Because of the shared options: https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.ts#L30
with this config: `caches: ['cookie']` you tell to both languageDetectors, they need to cache the cookie...
So i18next-http-middleware will send a Set-Cookie header and i18next-browser-languageDetector also tries to write a cookie via browser's: `document.cookie =`
Now, the logic for the cookieOptions in i18next-browser-languageDetector was not prepared for the sameSite option...
I just published a new version 5.0.1 of the i18next-browser-languageDetector module.
With this it should work.

**Comment by isaachinman** [comment]
@adrai Thanks, just looking at this now: https://github.com/i18next/i18next-browser-languageDetector/commit/902cfa1e95ae2ccf56053aa2fd0158c28c814c35. I think it would still be the case that `i18next-browser-languageDetector` overwrites the cookie set by `i18next-http-middleware` via `document.cookie =`, although now it's just setting `sameSite` by default, right?

**Comment by adrai** [comment]
I don't think/know how the options would be overwritten one i18next instance is on serverside and one one clientside...
Sorry but I have no clue how Next.js works... so there might be some object sharing magic I don't know. 🤷‍♂️

**Comment by isaachinman** [comment]
@adrai I was asking if `i18next-browser-languageDetector` will still call `document.cookie =`, even if the cookie already exists?

**Comment by adrai** [comment]
Yes, because normally you use language detection in the server or in the client, but not both...
Btw: is the browser language detection useful if already detected on serverside for next?

**Comment by isaachinman** [comment]
The browser language detection is essentially only useful for _updating_ the cookie value when the language is changed on the client side. That's mainly what we use it for. As long as it's respecting the `cookieSameSite` value from the config options, I don't see any problem with `i18next-browser-languageDetector` overwriting the cookie on the client.
