### ISSUE TITLE
Link to index route/page does not work after page refresh

### ISSUE THREAD

**Issue by slissner** [isaachinman/next-i18next#76]
Following scenario:

The user has navigated to a page/route other than the index route:

For instance: `http://localhost:3000/contact`

On this page, there is a "back" button to the index page/route:

```
import { withNamespaces, Link } from "../../i18n";

const BackButton = props => (
  <Link href="/">
    <button>{props.t("back")}</button>
  </Link>
);

export default withNamespaces("common")(BackButton);
```

Bug:

If I refresh the `/contact` route and then click on the button, nothing is happening (thus the route does not change as expected to the index route). On the contrary, if  I navigate from `/` (index) to `/contact` and then press the "back" button, everything works fine.

**Comment by isaachinman** [comment]
Funny, I did mean to include a link back to the index from `second-page` in the example, but it appears I forgot until now, with b6a9659.

Anyways, I've updated the example with this exact behaviour and cannot reproduce the bug. Please provide a reproducible repo that I can debug with.

**Comment by isaachinman** [comment]
Hi @slissner, any update?

**Comment by slissner** [comment]
Hi @isaachinman thanks for your quick reply and trying to reproduce the issue.

I believe, without having been able to spent too much time with analysis, that the problem stems from hot module replacement.

See for example: https://github.com/zeit/next.js/issues/5598

> Either Link or Router stops working when doing client side routing. It seems that HMR may be interrupting the transition between pages.

I am receiving the following error in the console: `Warning: Did not expect server HTML to contain a <noscript> in <div>.` (see https://stackoverflow.com/questions/45350360/react-16-warning-warning-js36-warning-did-not-expect-server-html-to-contain-a) 

For now I would suggest to close the issue as it seems to have nothing to do with `next-i18next`.
