### ISSUE TITLE
Add option to specify clientLocalePath in config to support approach "One Domain — Multiple Next.js Apps"

### ISSUE THREAD

**Issue by DavydenkovM** [isaachinman/next-i18next#761]
## Is your feature request related to a problem? Please describe.
It looks like currently there's no way to provide i18n support for "Multiple Next.js Apps" hosted on one server 
(behind a single reverse proxy).

I have the following next.js apps:

```
next_js_1
  static / locales / en / common.json ...

next_js_2
  static / locales / en / common.json ...
```

Everything is fine on server-side, but I can't find a way to specify locales prefix, so that my Nginx server can return correct locales for each app (for request `/static/locales/en/common.json`). Is there any way to change client request path from `/static/locales/en/common.json` to `APP_PREFIX/static/locales/en/common.json`?

I've tried to change `localePath` or `localeStructure` config options, but then SSR is broken because there's no such directories in FS.

https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L73
https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L101

## Describe the solution you'd like
Could you please add additional props `clientLocalePath` && `serverLocalePath` in `create-config.ts` to provide more flexibility for `next-i18next` config

Thanks in advance for your attention!

**Comment by isaachinman** [comment]
```jsx
const localePath = typeof window === 'undefined' ? serverPath : clientPath
```

**Comment by DavydenkovM** [comment]
Thanks!
