### ISSUE TITLE
Can't get current language with version 5.0.0

### ISSUE THREAD

**Issue by lsembolini** [isaachinman/next-i18next#769]
## Describe the bug
I have updated my project to the version 5 and now I can't get the current language from Server Side Rendering
## Occurs in next-i18next version
v5.0.0
## Steps to reproduce
Using the example on the repository https://github.com/isaachinman/next-i18next/tree/master/examples/simple
Adding 
` Homepage.getInitialProps = async({ req }) => {
  const currentLanguage = req ? req.language : i18n.language;
  console.log(currentLanguage)
}`
 in the index.js or on any other pages. The value of currentLanguage is always undefined. 
In the v4.5 it was working and after the update to the 5.0.0 it's not working anymore even in your example.
## Expected behaviour
The result should be the current language selected or detected from the server.

Thank You

**Comment by isaachinman** [comment]
Ah, this makes sense, because the middleware is essentially running inside `getInitialProps` now, as opposed to before your component runs, so the `req` object isn't mutated.

Regardless, the `req.language` thing was always a bit hacky.

Instead, how about we export a `I18nContext` from `next-i18next`, so that you can consume in the normal way:

```jsx
import { I18nContext } from 'next-i18next'

const { i18n: { language } } = useContext(I18nContext)
```

**Comment by lsembolini** [comment]
> Ah, this makes sense, because the middleware is essentially running inside `getInitialProps` now, as opposed to before your component runs, so the `req` object isn't mutated.
> 
> Regardless, the `req.language` thing was always a bit hacky.
> 
> Instead, how about we export a `I18nContext` from `next-i18next`, so that you can consume in the normal way:
> 
> ```js-jsx
> import { I18nContext } from 'next-i18next'
> 
> const { i18n: { language } } = useContext(I18nContext)
> ```

Thank you for the fast response but I've tried it and It's not working. We can't use useContext in SSR and even in client side it doesn't give me back the language value. In client side I get this error "Cannot read property '_context' of undefined"

Thank You

**Comment by isaachinman** [comment]
@lsembolini It will function exactly as a React context would, no little and no different. I'm not sure what you think you tested, as I haven't released the functionality yet.

**Comment by isaachinman** [comment]
This is now released in v5.1.0. I am also investigating if it will be possible to again support `req.i18n`.

**Comment by gpessa** [comment]
Do we have a way to fix this?
I also need the locale in the getInitialProps

**Comment by isaachinman** [comment]
@gpessa The `req.i18n` value should be accessible.
