### ISSUE TITLE
[Question] Multilanguage Blog

### ISSUE THREAD

**Issue by zeyuri** [isaachinman/next-i18next#772]
Hello,

I understood perfectly how to localize specific pages through the example project. But it is still not clear to me how to make a blog in several languages, how would I do it using an api or through several markdown files?

**Comment by isaachinman** [comment]
Hi @zeyuri, sorry but I do not understand your question at all. This is an issue tracker though, where people can report bugs they find in open source software. If you have general implementation questions, you are better off posting on StackOverflow, etc. Good luck!

**Comment by zeyuri** [comment]
Hey, @isaachinman,

First of all thanks for the very fast response and sorry if my english is not so good, it's not my first language.

I opened this issue because I saw your comments [here](https://github.com/vercel/next.js/discussions/10651) and your project does support serverless, so I wanted to use your solution, but this repository didn't have a place to initiate a discussion.

I want to make a blog that is in portuguese and english. I know how to setup the translations for everything, but not how to setup the localization folder estructure to use getStaticPaths and places the blog urls under the proper subpaths in the urls and serverless. If you can give me some guidance on how to setup this, I can make an example and make a PR in the future on your project with this example. I've searched online but I didn't find any related example of this with Next Js.

**Comment by isaachinman** [comment]
No problem at all!

First, this issue tracker isn't really for asking questions – it's mostly a place where we post bugs/feature requests/etc.

Second, it now sounds like you're asking about static/SSG, is that correct? If so, please see #586.
