### ISSUE TITLE
Shows keys instead of value in NextJS with ReactJS

### ISSUE THREAD

**Issue by jamal-rahimzadegan** [isaachinman/next-i18next#773]
I'm using it with react js but it gives me the keys instead of values

![Untitled](https://user-images.githubusercontent.com/52101670/88771380-69e1eb80-d194-11ea-92b3-435d2bc2c246.png)

**Comment by isaachinman** [comment]
Please provide a reproducible repo.

**Comment by jamal-rahimzadegan** [comment]
> Please provide a reproducible repo.

package.json:
{
  "name": "behineh",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "axios": "^0.19.2",
    "bootstrap": "^4.5.0",
    "i18next": "^19.6.3",
    "next": "9.5.0",
    "next-i18next": "^5.1.0",
    "next-redux-wrapper": "^6.0.2",
    "react": "16.13.1",
    "react-bootstrap": "^1.2.2",
    "react-dom": "16.13.1",
    "react-icons": "^3.10.0",
    "react-lottie-web": "^1.3.2",
    "react-multi-carousel": "^2.5.5",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "i18next-browser-languagedetector": "^5.0.0"
  }
}
---------------------------------------------------------------
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const localeSubpaths = {}
module.exports = {
    rewrites: async () => nextI18NextRewrites(localeSubpaths),
    publicRuntimeConfig: {
        localeSubpaths,
    },
}
---------------------------------------------------------------
const NextI18Next = require('next-i18next').default
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig
const path = require('path')
module.exports = new NextI18Next({
    defaultLanguage: ["en"],
    otherLanguages: ['de'],
    localeSubpaths,
    localePath: path.resolve('./public/static/locales')
})
---------------------------------------------------------------
_app.js
import React from 'react';
import store from "../redux/store";
import {Provider} from "react-redux";
import withRedux from "next-redux-wrapper";
import "bootstrap/dist/css/bootstrap.css";
import "react-multi-carousel/lib/styles.css";
import { withTranslation } from '../i18n'
import App from "next/app";
const MyApp = ({t,Component, pageProps}) => (
    <p>  {    t('h1'   } </p>
);
const makeStore = () => store;

MyApp.getInitialProps = async (appContext) => ({...await App.getInitialProps(appContext)})
export default withTranslation('common')(MyApp)

**Comment by isaachinman** [comment]
@jamal-rahimzadegan That setup looks fine, I will need a repo, as I already mentioned, to help you debug.

**Comment by jamal-rahimzadegan** [comment]
> @jamal-rahimzadegan That setup looks fine, I will need a repo, as I already mentioned, to help you debug.

https://github.com/jamal-rahimzadegan/behine_lang

**Comment by isaachinman** [comment]
There are many problems with the repo you've just linked, the the first thing that stands out to me is that you're not using `withTranslation` on your `Home.js` component.

Please post on StackOverflow for help. Good luck!

**Comment by jamal-rahimzadegan** [comment]
> There are many problems with the repo you've just linked, the the first thing that stands out to me is that you're not using `withTranslation` on your `Home.js` component.
> 
> Please post on StackOverflow for help. Good luck!

It isn't good answer for the owner, you could just use the _app.js with statick <p> tag

**Comment by isaachinman** [comment]
Sorry, I do not understand what you mean.

**Comment by jamal-rahimzadegan** [comment]
I'm saying you could test the translation by using an HTML p tag on _app.js page

**Comment by isaachinman** [comment]
So, first and foremost this is an issue tracker, where people can post bugs/problems that they have found in a piece of open source software. Second, if you _did_ want to use an issue tracker to request help on implementation, it would be up to _you_ to make it as easy as possible for the maintainer(s) to do that, as you're literally asking for them to spend unpaid time assisting you.

Third, the repo you linked doesn't even compile/run in its current state. I'd start by rereading the `next-i18next` docs thoroughly. You need to use `appWithTranslation`, not `withTranslation`, in your `_app` file, for example.
