### ISSUE TITLE
Next export is broken with v6.0.0

### ISSUE THREAD

**Issue by clement-faure** [isaachinman/next-i18next#780]
## Describe the bug
Trying to next export the application using latest version of next-i18next (v6.0.0)

## Occurs in next-i18next version
"next-i18next": "^6.0.0"

## Steps to reproduce
https://github.com/clement-faure/next-antd-graphql-starter/commit/c2b8f0bc2a2cbe0bc947dadf0e4185877c609265

Git clone next-antd-graphql-starter and run next export

## Screenshots
![image](https://user-images.githubusercontent.com/23209488/88900518-c0f8c680-d24f-11ea-81f4-7ebaa29346cb.png)

## OS
 - Device: MBP 2019 16"

**Comment by isaachinman** [comment]
Next export is not something this package can easily support. If you want fully static websites, you're better off rolling dynamic directories on your own.

If you'd like to investigate and contribute though, you are more than welcome!

**Comment by clement-faure** [comment]
Thank you for the quick response @isaachinman !

**Comment by isaachinman** [comment]
No problem. Bit more context: `next export` apps represent a pretty small proportion of NextJs apps – most are hybrid apps. On top of that, certain data fetching methods (including `getServerSideProps`, etc) are incompatible with `next export`. There are no plans to support `next export`.

We managed to make it work (result was client side only app) in the past, but even that was not a very good idea – you may as well use CRA with `react-i18next`, or something.

I'll remove [that line](https://github.com/isaachinman/next-i18next#notes) from the docs.

**Comment by eric-burel** [comment]
Ha @clement-faure great minds think alike.

@isaachinman You might want to take a look at this issue I've just opened https://github.com/vercel/next.js/issues/15674

`next export` might be a minor usage in proportion, but not necessarily small usage at all. I hope that in the future `getServerSideProps` becomes available again with `next export`, by just being ignored.

**Comment by isaachinman** [comment]
@eric-burel I thought that Tim was quite clear about the incompatibility?

**Comment by isaachinman** [comment]
Fairly soon, `next-i18next` will support static/SSG outputs from `next build`. I don't have any plans to put effort into supporting `next export`, but if anyone wants to lead that effort, I can certainly reopen this issue and answer any questions they may have.

**Comment by eric-burel** [comment]
Technically if it works for next static build on your side, it should work with `next export` with no additional work, provided `getServerSideProps` is left compatible with `next export`. So yeah, the solution is most probably on Next side, will wait for their answer.
First step is to make my case in favour of supporting both `next export` and dynamic server side rendering in the same codebase ^^

**Comment by yingqi-chen** [comment]
> No problem. Bit more context: `next export` apps represent a pretty small proportion of NextJs apps – most are hybrid apps. On top of that, certain data fetching methods (including `getServerSideProps`, etc) are incompatible with `next export`. There are no plans to support `next export`.
> 
> We managed to make it work (result was client side only app) in the past, but even that was not a very good idea – you may as well use CRA with `react-i18next`, or something.
> 
> I'll remove [that line](https://github.com/isaachinman/next-i18next#notes) from the docs.

Can you explain what CRA in `react-i18next` is? Thanks!

**Comment by idrisakmal** [comment]
> Can you explain what CRA in `react-i18next` is? Thanks!

Basically he's saying just use create-react-app with any i18n package
