### ISSUE TITLE
importing the middleware in `app-with-translation` is causing that code to be pulled into the client bundle

### ISSUE THREAD

**Issue by dcodus** [isaachinman/next-i18next#784]
> Ah: something I'm not currently sure of, is if [importing the middleware in `app-with-translation`](https://github.com/isaachinman/next-i18next/pull/689/files#diff-50324ee6dc18a21a8f300593055776e4R7) is causing that code to be pulled into the client bundle. That would be something to investigate. We may have to do more env-specific dynamic imports.

_Originally posted by @isaachinman in https://github.com/isaachinman/next-i18next/pull/689#issuecomment-617902384_

This is indeed the case. Will result in ~ 5kb added to bundle.

On 4.5.0
<img width="638" alt="Screen Shot 2020-07-30 at 7 37 07 PM" src="https://user-images.githubusercontent.com/12925816/88984681-4013ec00-d29c-11ea-88b2-604f9d2f534e.png">

On 6.0.1
<img width="537" alt="Screen Shot 2020-07-30 at 7 36 44 PM" src="https://user-images.githubusercontent.com/12925816/88984683-41451900-d29c-11ea-83fe-63e035c9fe25.png">

**Comment by isaachinman** [comment]
Good catch. We probably need to split all cross-env files with a `package.json`, like I've done in the `create-client` dir.

I can get to this next week, or you can work on a PR in the meantime.

**Comment by isaachinman** [comment]
Hi there, I have just released `next-i18next@8.0.0`, which uses the internationalised routing built into NextJs v10+. This new version of `next-i18next` is quite different, thus making this PR no longer relevant. Thanks!
