### ISSUE TITLE
Update docs on custom routes via rewrites

### ISSUE THREAD

**Issue by mqtik** [isaachinman/next-i18next#785]
Hi.
I see in the example that the languages are splitted by language and by element such as footer, ..

I'm looking for something more simple, like so:

```
about: {
  en: 'About us',
  es: 'Acerca de'
},
search: {
  en: 'Search',
  es: 'Buscar'
},
...
```

Can this be done?

**Comment by isaachinman** [comment]
@mqtik You can establish custom routes. Check out this user's comment: https://github.com/isaachinman/next-i18next/pull/689#issuecomment-666605215.

We should update the docs to answer this question, as it will be a common one.

**Comment by mqtik** [comment]
I'm sorry if I didn't explain myself well, no custom routes.
Keys and values.

You can trigger them like t('search'), t('about').

I did a library for React Native for this, so you could call the keys like `language.about[getLang()]` and I'm looking for somethig similar. Since this library seems to handle everything, it would be a cool feature, so translation can get done pretty quickly.

**Comment by isaachinman** [comment]
Oh, I see. Have a look at the i18next documentation. This package doesn't handle any of the actual localisation work. Good luck!
