### ISSUE TITLE
`Cannot read property 'ru' of undefined` when using `next-compose-plugins`

### ISSUE THREAD

**Issue by goodok21** [isaachinman/next-i18next#786]
## Describe the bug
`Cannot read property 'ru' of undefined` when using `next-compose-plugins`

## Occurs in next-i18next version
"next-i18next": "^6.0.1",
"i18next": "^14.0.1",
"next-compose-plugins": "^2.2.0",

## Steps to reproduce
1. use `examples/simple` project in this repo
2. `yarn add next-compose-plugins`
3. in `next.config.js`:
```
const withPlugins = require('next-compose-plugins');
const nextPWA = require('next-pwa');
const nextEnv = require('next-env');
const dotenvLoad = require('dotenv-load');
dotenvLoad();

const { nextI18NextRewrites } = require('next-i18next/rewrites');

const localeSubpaths = { en: 'en', ru: 'ru' };

const nextConfiguration = () => ({
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
});

module.exports = withPlugins(
  [
    nextEnv,
    [
      nextPWA,
      {
        pwa: {
          disable: process.env.NODE_ENV === 'development',
          register: true,
          scope: '/app',
          sw: 'service-worker.js',
          dest: 'public',
        },
      },
    ],
  ],
  nextConfiguration
);

```

## Expected behaviour
Work without errors

## Screenshots
```
TypeError: Cannot read property 'en' of undefined
    at subpathFromLng (/Users/user/Test/project/node_modules/next-i18next/dist/commonjs/utils/subpath-from-lng.js:13:38)
    at /Users/user/Test/project/node_modules/next-i18next/dist/commonjs/middlewares/next-i18next-middleware.js:61:57
    at /Users/user/Test/project/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:249:38
    at new Promise (<anonymous>)
    at _loop$ (/Users/user/Test/project/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:248:36)
    at tryCatch (/Users/user/Test/project/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/user/Test/project/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/user/Test/project/node_modules/regenerator-runtime/runtime.js:118:21)
    at tryCatch (/Users/user/Test/project/node_modules/regenerator-runtime/runtime.js:63:40)
    at maybeInvokeDelegate (/Users/user/Test/project/node_modules/regenerator-runtime/runtime.js:356:18)
```

## OS (please complete the following information)
 - Device: MBP 2017 13"
 - Browser: Chrome 84.0.4147.105

## Additional context
The problem is when we using `next-compose-plugins` and `nextConfiguration` is a Function instead Object. The point to use nextConfiguration as a function is to get `webpack` instance and etc

**Comment by isaachinman** [comment]
Sorry, I don't understand this issue. `next-i18next` does not modify the webpack config, or do anything outside of normal user presets. Can you explain how/why you think `next-i18next` could be causing an issue? This is most likely user error.

**Comment by goodok21** [comment]
@isaachinman yes, I understand that `next-i18next` does not modify the webpack config, but I need to modify it. To modify webpack config in `next.config.js` I need to get webpack instance. So I need to define `nextConfiguration` as a function and it throw error (see Screenshot section).

All works fine if I define `nextConfiguration` as an object.

**Comment by isaachinman** [comment]
It sounds like you should open an issue in the `next-compose-plugins` repo, not here. I'm not sure what you would like `next-i18next` to do to "fix" this error.
