### ISSUE TITLE
You have not declared a namespacesRequired array on your page-level component

### ISSUE THREAD

**Issue by saurabhguptarock** [isaachinman/next-i18next#787]
## Describe the bug
I have tried everything but this error is not going away.
That is why i stopped using your package and don't know any other similar package.

Please fix this bug .

**Comment by isaachinman** [comment]
First, it's not an error but rather a helpful warning to let you know that your implementation is not as optimal as it could be. The warning message does not affect your ability to use the package or deploy your app.

Second, instructions on how to use `namespacesRequired` can be found in the main README.

**Comment by saurabhguptarock** [comment]
I already said that nothing is working
i don't know why

**Comment by saurabhguptarock** [comment]
I am using typescript

**Comment by isaachinman** [comment]
@saurabhguptarock Please post on StackOverflow for help. Good luck!
