### ISSUE TITLE
Flashing GET translations file 500 issue while navigating through the app

### ISSUE THREAD

**Issue by powerczuk** [isaachinman/next-i18next#788]
## Bug report
I'm facing 500 issue after click on the navigation link and just before the page reload
`GET https://domain.com/_next/data/development/en/publication.json 500`

The url works fine when I remove the language code from it.
`GET https://domain.com/_next/data/development/publication.json 500`

## Steps to reproduce
next: 9.4.4
next-i18next: 4.2.0

**My next-i18next instance setup**
```javascript
const NextI18NextInstance = new NextI18Next({
  ns: ["common"],
  defaultNS: "common",
  defaultLanguage: "en",
  otherLanguages: ["en", "de-CH", "de-DE", "fr"],
  strictMode: false,
  localeSubpaths: {
    en: "en",
    "de-CH": "de-CH",
    "de-DE": "de-DE",
    fr: "fr"
  },
  serverLanguageDetection: false,
  debug: true
});
```

## Expected behaviour
Application can access the translation file without causing any errors

## OS (please complete the following information)
 - Any device
 - Any browser

**Comment by isaachinman** [comment]
Can you provide a reproducible repo? If so, I can debug.

**Comment by powerczuk** [comment]
While preparing a new repo noticed that the issue is related only to the page which using the `getServerSideProps` method. 

Index -> Second Page (getServerSideProps) -> 500 issue
Second Page -> Index (no getServerSideProps) -> No issue

Please have a look: [example repo](https://github.com/powerczuk/next-i18next-test)

**Comment by isaachinman** [comment]
@powerczuk Sounds interesting indeed, but you're using an older version of `next-i18next`. Can you reproduce this using v6? And, why have you disabled `serverLanguageDetection`?

**Comment by powerczuk** [comment]
@isaachinman hmm just jumped into the update of the `next-i18next` and after checking the documentation and some examples noticed there is no longer support for custom express servers?

**Comment by isaachinman** [comment]
That's correct, it's serverless only now.

**Comment by isaachinman** [comment]
@powerczuk Any update?
