### ISSUE TITLE
typescript I18nContext 

### ISSUE THREAD

**Issue by tokomeno** [isaachinman/next-i18next#789]
## Describe the bug
typescript  I18nContext type is not working correctly I got this error

import { I18nContext } from "next-i18next";

export const useActiveLang = () => {
  const {
    i18n: { language: activeLang },
  } = useContext(I18nContext);
  return { activeLang };
};

![image](https://user-images.githubusercontent.com/34988363/89342314-aab99300-d6b3-11ea-872c-e7eae025b81f.png)

## Occurs in next-i18next version
"next-i18next": "^6.0.1",

https://github.com/isaachinman/next-i18next#accessing-the-current-language 

Here is provided code from the documentation I guess it has to be working without any issue but same error

![image](https://user-images.githubusercontent.com/34988363/89342636-21ef2700-d6b4-11ea-95d3-6f49b6cdaa06.png)

![image](https://user-images.githubusercontent.com/34988363/89342700-36332400-d6b4-11ea-8bf5-347f60ef09bc.png)

**Comment by isaachinman** [comment]
Interesting. It definitely [is exported](https://github.com/isaachinman/next-i18next/blob/master/src/index.ts#L14), but it seems like there's an issue with TS/module resolution here.

**Comment by tokomeno** [comment]
As I see in types.d.ts file I18nContext is exported as a type but for this specific scenario we need as value to pass useContext as an argument

![image](https://user-images.githubusercontent.com/34988363/89413234-87d1c200-d739-11ea-9e1c-d43d464a4ec7.png)

**Comment by isaachinman** [comment]
@tokomeno Yes, it's exported as a type because _it is_ a type. If you remove that line in `types.d.ts`, TypeScript will simply complain that `next-i18next` has no exported member named `I18nContext`, even though it does – TS is simply failing to pick up the export. As far as I can tell it doesn't actually have anything to do with the types.

**Comment by haggen** [comment]
Can we get a bump to i18n-react's version so we can have this fix?

**Comment by isaachinman** [comment]
@haggen #799 introduces a bunch of other changes which shouldn't be necessary. If you open a PR just to bump `react-i18next`, I'll merge it immediately.

**Comment by seaneking** [comment]
Done @isaachinman

**Comment by seanplwong** [comment]
finally got some time for this

@isaachinman it is exported in the implementation, but in the typedef, it is reexported as type only, that's why the tsc error: `'I18nContext refers to a type, but used as a variable'`

I could create an minimally viable PR later
