### ISSUE TITLE
Page Routing not using the language defined in the URL.

### ISSUE THREAD

**Issue by nicolaslair** [isaachinman/next-i18next#791]
## Bug description
Hi there,

I did a test integration of next-18next v6.0.2 with next 9.5.0.

When I launch the EN version of the homepage, I see that that FR language (which is the default language) is still applied: https://utopix-marketplace-frontend-git-implementation-i18next.utopix.vercel.app/en - the "next-i18next" cookie is still set to fr. If I then click a few times on the "change language" button, the UI gets updated in EN but reloading the page sets in back in FR.

So the page router is not updating the i18n Language in memory / cookie based on the language defined in the route.

## Expected behaviour
When I launch https://utopix-marketplace-frontend-git-implementation-i18next.utopix.vercel.app/en the language / UI should be displayed in EN.

### next.config.js
```
const { nextI18NextRewrites } = require('next-i18next/rewrites');

const localeSubpaths = {
  en: 'en',
  nl: 'nl',
};

module.exports = {
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
};
```

### i18n.ts
```
import NextI18Next from 'next-i18next';
import path from 'path';

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'fr',
  defaultNS: 'common',
  localePath: path.resolve('./public/static/locales'),
  otherLanguages: ['en', 'nl'],
  localeSubpaths: { en: 'en', nl: 'nl' },
});

export const {
  i18n,
  Link,
  appWithTranslation,
  withTranslation,
  useTranslation,
} = NextI18NextInstance;

export default NextI18NextInstance;
```
### _app.tsx - defined with the appWithTranslation HOC

```
import { appWithTranslation } from '../i18n';
...
export default appWithTranslation(App);
```
### Home Page - defined with the withTranslation HOC
```
import { i18n, withTranslation } from '../i18n';
const IndexPage = ({ t }: { t: any }): JSX.Element => (
    <h1>{t('common:welcome')}</h1>
);

export async function getInitialProps(): Promise<any> {
  return { namespacesRequired: ['common'] };
}

export default withTranslation('common')(IndexPage);
```

Don't hesitate to let me know if you need more info, thanks in advance!

**Comment by isaachinman** [comment]
Can you please provide a reproducible repository?

**Comment by nicolaslair** [comment]
Thanks @isaachinman, by creating the repo, I found out that the bug was coming from a conflict with another dependency - so it's all working by default. Here is the default setup with Typescript if someone is interested: https://github.com/nicolaslair/next-i18next-ts-demo
