### ISSUE TITLE
Catch-all-route takes precedence over predefined routes when using rewrites.

### ISSUE THREAD

**Issue by kekami** [isaachinman/next-i18next#793]
## Describe the bug
After upgrading from 4.5.0, I've encountered an issue where it seems like a catch-all-route takes precedence over a predefined route when used in combination with a rewrite.

My setup:
```
// next.config.js
const { nextI18NextRewrites } = require('next-i18next/rewrites');

const localeSubpaths = { se: 'se', en: 'en' };

module.exports = {
  rewrites: async () => {
    return [
      ...nextI18NextRewrites(localeSubpaths),
      {
        source: '/gardening/london',
        destination: '/services/gardening/london',
      },
    ];
  },
  publicRuntimeConfig: {
    localeSubpaths,
  },
};

```
```
const NextI18Next = require('next-i18next').default;
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;
const path = require('path');

module.exports = new NextI18Next({
  otherLanguages: ['se'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales'),
});

```
```
// Folder tree
├── i18n.js
├── next.config.js
├── package.json
└── pages
    ├── [...slug].js
    ├── _app.js
    ├── api
    │   └── hello.js
    ├── index.js
    └── services
        └── [service]
            └── [city]
                └── index.js
```

So for example, if I navigate to `http://localhost:3000/en/gardening/london` I expect to land in `services/[service]/[city]/index.js` but instead the `[...slug].js` page is shown. It works as expected when not using `nexti18next`, then the `services/[service]/[city]/index.js` page is correctly shown for `http://localhost:3000/gardening/london`.

Repo: https://github.com/kekami/nexti18n-bug

## Occurs in next-i18next version
`"next-i18next": "^6.0.2",`

## OS (please complete the following information)
 - Device: MBP 15 2017
 - Browser: Chrome 84.0.4147.105

**Comment by isaachinman** [comment]
Hey @kekami – not sure how `next-i18next` can help here. The output of `nextI18NextRewrites` is just an array of rewrites, which you're more than welcome to have a look at or modify. Please let me know what sort of "fix" you had in mind here.

**Comment by kekami** [comment]
Hi @isaachinman, please correct me if I'm wrong, but I believe this must be a bug within next-i18next. As it worked as expected in earlier versions (4.5.0) as well as if I disable next-i18next by removing the `appWithTranslation` hoc. So it seems to me that the latest version does something differently? Sorry if it is a bit diffuse, I'm not that well versed with the internals of the lib.

**Comment by kekami** [comment]
Just tested and it seems to be connected to the use of localeSubpaths, if I remove them, the rewrite works and the correct page is shown.

**Comment by isaachinman** [comment]
Of course it's related to `localeSubpaths`. Can you please post the output of your `nextI18NextRewrites` call?

**Comment by kekami** [comment]
Sure, the output is:
```
[
  { source: '/:lang(se){/}?', destination: '/' },
  { source: '/:lang(se)/:path*', destination: '/:path*' },
  { source: '/:lang(en){/}?', destination: '/' },
  { source: '/:lang(en)/:path*', destination: '/:path*' }
]
```

**Comment by isaachinman** [comment]
So, something about that output is not playing well with your dynamic route setup.

Feel free to have a play around and let me know what it is. [Relevant code is here](https://github.com/isaachinman/next-i18next/blob/master/src/utils/generate-rewrites.ts).

**Comment by kekami** [comment]
I believe I now understand what the issue is. Multiple rewrites of one request does not work, it simple takes the first matching rewrite. In my case it was `{ source: '/:lang(en)/:path*', destination: '/:path*' }`.

So it works if I add my rewrite above `...nextI18NextRewrites(localeSubpaths)` while also manually adding the localeSubpath for it, e.g.
```
module.exports = {
  rewrites: async () => {
    return [
      {
        source: '/en/gardening/london',
        destination: '/services/gardening/london',
      },
      ...nextI18NextRewrites(localeSubpaths),
    ];
  },
  publicRuntimeConfig: {
    localeSubpaths,
  },
};
```

**Comment by isaachinman** [comment]
@kekami Yup, that seems right. I suppose `nextI18NextRewrites` could optionally take an array of custom routes? Not quite sure how that'd work though. Annoying as it may seem, it might be best if users just manage their own rewrites, as everyone will want to do something slightly different. Let me know what you think.
