### ISSUE TITLE
Optional locale subpaths

### ISSUE THREAD

**Issue by St1myL** [isaachinman/next-i18next#794]
next-i18next allows us to set locale subpaths but in some cases it would be nice to make them optional.
I read the documentation, but did not find an answer to this question, so if next-i18next already have this feature, the question will be settled. I am not familiar with i18n, perhaps such a feature is implemented there

For example I have 3 locale versions of website:

- `<link rel="alternate" hreflang="en" href="/">`
- `<link rel="alternate" hreflang="de" href="/de">`
- `<link rel="alternate" hreflang="fr" href="/fr">`

When the user opens `https://example.com/de`, the site should set the cookie `next-i18next=de`, and then if the user removes `/ de` from the url, it will keep the same locale (and the link will look like this: `https://example.com` without subpath)

**Comment by isaachinman** [comment]
That's a very unusual use case, and not one that this package will support out of the box. You might be best off forking and making the changes you need.

**Comment by St1myL** [comment]
Thanks for the quick response!
