### ISSUE TITLE
saving common.json doesn't reload the translations.

### ISSUE THREAD

**Issue by ktjd123** [isaachinman/next-i18next#796]
## Describe the bug
saving common.json doesn't reload the translations. I'm using custom server.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.

## Steps to reproduce
    "next-i18next": "^6.0.2",

## Expected behaviour
update translations.

## OS (please complete the following information)
 - Device: MacBook Pro (15-inch, 2016)
 - Browser: Chrome, major: 83, minor: 0, build: 4103, patch: 97

## Additional context
Always appreciate your works. Thank you.

**Comment by isaachinman** [comment]
There are several issues pertaining to this. Essentially you'll want to restart your Node process via nodemon or similar. Good luck!

**Comment by ktjd123** [comment]
@isaachinman Thank you.

**Comment by armspkt** [comment]
> There are several issues pertaining to this. Essentially you'll want to restart your Node process via nodemon or similar. Good luck!

Is there any solution that doesn't have to reload Node process for good DX?

thanks

**Comment by isaachinman** [comment]
You can call `i18n.reloadResources()` if you don't want to restart your Node process.
