### ISSUE TITLE
i18n.t is not working in placeholder

### ISSUE THREAD

**Issue by ktjd123** [isaachinman/next-i18next#797]
## Describe the bug
i18n.t is not working in input placeholder, it's just showing string param inside t,

but when I save the code and fast refresh, it works perfectly.

## Occurs in next-i18next version
"next-i18next": "^6.0.2",

## Steps to reproduce
use t in placeholder

## Expected behaviour
load from json

## OS (please complete the following information)
 - Device: MacBook Pro (15-inch, 2016)
 - Browser: Chrome

## Additional context
Thanks.

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by ktjd123** [comment]
@isaachinman https://github.com/ktjd123/next-18next-ts-example. 

yarn d for start.

pls check / route.

In my case of this project, placeholder changed to correct value after changing code inside i18n.js then save it.

Thank you.

**Comment by isaachinman** [comment]
@ktjd123 That's not a minimal example. Can you please create a new, simple, repo that exemplifies the problem? Also, you've got `"en"` as both your default language and within `otherLanguages`. That's not going to work.

**Comment by ktjd123** [comment]
@isaachinman Thank you for reply. I force pushed to repository. check please.

**Comment by isaachinman** [comment]
Follow the docs. Use `withTranslation`, not `i18n.t` directly.
