### ISSUE TITLE
How to load only requested translation?

### ISSUE THREAD

**Issue by paveldpetrov** [isaachinman/next-i18next#798]
Hello,

I configured next-i18next like in the simple-example repo. However, I noticed that when I change the language, namespaces for all languages are loaded. I also tested this on your simple-example and the result is the same. The idea is to load only the requested translation json file, is it not? Or am I missing some configuration?

## Steps to reproduce

1. Open http://next-i18next.com/ and the dev-tool of the browser
2. Check the network tab while changing the language (filter .json files only, since translations are in json)

## Expected behaviour
Only the requested translation files are loaded (e.g: German)

## Screenshots
![image](https://user-images.githubusercontent.com/68463028/90013878-cb36ae00-dcae-11ea-8a6a-bae8750447bd.png)
![image](https://user-images.githubusercontent.com/68463028/90013901-d4c01600-dcae-11ea-943b-a83330facad5.png)

**Comment by isaachinman** [comment]
Sorry, not sure what you mean. If you changed from English to German, the English locales would have already been loaded. Can you explain in more detail what the problem is?

**Comment by paveldpetrov** [comment]
Yes, the English locales have not been loaded initially. At least I don't see them in the XHR. When I change to German, I see both English and German loaded.

**Comment by paveldpetrov** [comment]
Here's the result of going to the second page:

![image](https://user-images.githubusercontent.com/68463028/90015420-439e6e80-dcb1-11ea-993f-3a3cc2ff4b63.png)

It loads both json files (for English and German). I think it should be loading only the German one, since I changed it on the first page.

**Comment by isaachinman** [comment]
Ah, got it. This is somewhat of an edge case, but an important optimisation nonetheless. Most likely, there is a render happening before the actual language change via the i18next provider, thus causing the English locale network requests to fire.

Contributions welcome.

**Comment by isaachinman** [comment]
Hi there, I have just released `next-i18next@8.0.0`, which uses the internationalised routing built into NextJs v10+. This new version of `next-i18next` is quite different, thus making this PR no longer relevant. Thanks!
