### ISSUE TITLE
Sublocale returns 404

### ISSUE THREAD

**Issue by aaronsnig501** [isaachinman/next-i18next#800]
I have configured the subLocale settings as per step 5 in the README, however, when I try to go to one of the subpaths I receive a 404.

On the index level route (http://localhost:3000/), when I set English as my default language and set the sub locale for Portuguese (pt), it will load the English from the correct JSON, however, when I try to view the Portuguese version of the site (http://localhost:3000/pt) I get a 404. Similarly, when I switch them around and change the default language on my browser to Portuguese and add `en` as the second language, the index page loads the Portuguese correctly but returns a 404 when I try to access `localhost:3000/en`

My repo is [here](https://github.com/aaronsnig501/casamento). I've tried to follow the instructions as best I can:

```javascript
// i18n.js
const NextI18Next = require("next-i18next").default;
const path = require("path");

module.exports = new NextI18Next({
  defaultLanguage: "en",
  localeSubpaths: {
    pt: "pt",
  },
  localePath: path.resolve("./public/static/locales"),
});
```

```javascript
// next.config.js
const { nextI18NextRewrites } = require("next-i18next/rewrites");

const localeSubpaths = {};

module.exports = {
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
};
```

The site is also hosted on Netlify - 
[Index URL](https://clever-edison-4db4e6.netlify.app/)
[Portuguese](https://clever-edison-4db4e6.netlify.app/pt)

What's strange here is that I've tested it on a device where Portuguese is the only language, by going to the index URL and it only returns English.

I don't see anything wrong with my configuration, and I would very much like to be able to test /pt in development even if my browser's language is set to English.

Thanks

**Comment by isaachinman** [comment]
> I don't see anything wrong with my configuration

Your `localeSubpaths` objects are completely different. Please follow the documentation and example. Good luck!

**Comment by aaronsnig501** [comment]
Okay, I got it working as I missed the part about updating the `next.config.js`. I've hardcoded the dict, but it would good if you could provide an of what the code in the `next.config.js` file should look like, rather than having the dict defined in multiple files. There's also no example of this, which I think would be really helpful for people that are new to this.

After updating this, once I test it, both pages work fine, however, it's not possible to get back to the English version of the site after going to '/pt'. All subsequent attempts to go back to the index just redirect back to '/pt'

**Comment by isaachinman** [comment]
> what the code in the next.config.js file should look like, rather than having the dict defined in multiple files. There's also no example of this

That's incorrect. Look at the [example](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/i18n.js#L2).

> All subsequent attempts to go back to the index just redirect back to '/pt'

This is intentional behaviour which you can opt out of. For any further help requests, please post on StackOverflow.

**Comment by aaronsnig501** [comment]
It's not clear from the documentation that you need that line of code in order to get the subLocales working

> This functionality is not enabled by default, and must be passed as an option into the NextI18Next constructor as a config option:
> 
> new NextI18Next({
>   localeSubpaths: {
>     de: 'de'
>   }
> })
> The localeSubpaths object must also be passed into next.config.js, via the nextI18NextRewrites util, which you can import from next-i18next/rewrites.

The documentation gives the impression that the `subLocale` object should be defined within `NextI18Next`, but in the example that you've shown, it's the other way around.

And the documentation doesn't mention what the different options actually do, so I don't what default behaviour can be modified.

I really feel the documentation here needs to be beefed and made clearer in certain points

**Comment by isaachinman** [comment]
No idea what `subLocale` is. It's entirely up to the user how they persist a `localeSubpaths` object. Using `next/config` is just one option.

PRs to improve documentation are always welcomed.

**Comment by anialamo** [comment]
> I have configured the subLocale settings as per step 5 in the README, however, when I try to go to one of the subpaths I receive a 404.
> 
> On the index level route (http://localhost:3000/), when I set English as my default language and set the sub locale for Portuguese (pt), it will load the English from the correct JSON, however, when I try to view the Portuguese version of the site (http://localhost:3000/pt) I get a 404. Similarly, when I switch them around and change the default language on my browser to Portuguese and add `en` as the second language, the index page loads the Portuguese correctly but returns a 404 when I try to access `localhost:3000/en`
> 
> My repo is [here](https://github.com/aaronsnig501/casamento). I've tried to follow the instructions as best I can:
> 
> ```js
> // i18n.js
> const NextI18Next = require("next-i18next").default;
> const path = require("path");
> 
> module.exports = new NextI18Next({
>   defaultLanguage: "en",
>   localeSubpaths: {
>     pt: "pt",
>   },
>   localePath: path.resolve("./public/static/locales"),
> });
> ```
> 
> ```js
> // next.config.js
> const { nextI18NextRewrites } = require("next-i18next/rewrites");
> 
> const localeSubpaths = {};
> 
> module.exports = {
>   rewrites: async () => nextI18NextRewrites(localeSubpaths),
>   publicRuntimeConfig: {
>     localeSubpaths,
>   },
> };
> ```
> 
> The site is also hosted on Netlify -
> [Index URL](https://clever-edison-4db4e6.netlify.app/)
> [Portuguese](https://clever-edison-4db4e6.netlify.app/pt)
> 
> What's strange here is that I've tested it on a device where Portuguese is the only language, by going to the index URL and it only returns English.
> 
> I don't see anything wrong with my configuration, and I would very much like to be able to test /pt in development even if my browser's language is set to English.
> 
> Thanks

@aaronsnig501 did you find some solution for this error? Please some help or idea! Thanks!

**Comment by aaronsnig501** [comment]
@anialamo From what I recall, no. Because of the scope that I needed for this specific project the automatic detection was sufficient for what I needed and getting answers here was like pulling teeth, and the documentation wasn't very helpful.

NextJS 10 was just released with internationalization support, so if it's possible for you, I'd probably recommend going down that route. [https://nextjs.org/docs/advanced-features/i18n-routing](https://nextjs.org/docs/advanced-features/i18n-routing)

**Comment by anialamo** [comment]
thanks! @aaronsnig501
