### ISSUE TITLE
Using localeSubpaths & redirects for selected pages

### ISSUE THREAD

**Issue by calspre** [isaachinman/next-i18next#801]
I'd like to use localeSubpaths & redirects for some pages only (e.g. marketing pages) and leave as-is for other pages (e.g. dashboard) -- so dashboard pages only change content without URL redirections.

**Example pages with redirects and localSubpaths: (for users whose preferred language is German)**
- `/` --> `/de`
- `/about` --> `/de/about`
- `/features` --> `/de/features`

**Example pages without redirects and localSubpaths: (only content is translated to German)**
- `/account/settings`
- `/projects/[projectId]`
- `/teams/[teamId]`

Can I implement both in a single app? Could you provide some guidance if that's the case?

**Comment by isaachinman** [comment]
You will need to manually inspect the output of `nextI18NextRewrites` and make whatever changes you need, based on the NextJs docs. Once you figure out a solution, it'd be nice if you can post it back here so that other users can see what you've done. Good luck!

**Comment by calspre** [comment]
Thanks for your prompt answer. I think it boils down to two issues:

- When users hit `/account/settings`, they shouldn't be redirected to `/de/account/settings`
- When users hit `/de/account/settings`, next.js should map the request to `account/settings.js`

While the latter is handled in `rewrites` key in `next.config.js` (the output of `nextI18NextRewrites` as you've mentioned) the former seems to be handled in next-i18next -- please correct me if I am wrong. Doesn't [this line of code](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L63) have to do with it?

**Comment by isaachinman** [comment]
That's loosely correct. We don't have a way of opting into `localeSubpaths` per route, so you'll need to make use of some combination of changes to `rewrites` and `ignoreRoutes`.
