### ISSUE TITLE
Way to load translations from remote server

### ISSUE THREAD

**Issue by krcaltomas99** [isaachinman/next-i18next#802]
I'm working on a project and I'm building the frontend (react) and my colleagues are building the backend (laravel) and one of the requirements is editable text and we've achieved that previously using react-i18next through 

```typescript
i18n
	.use(I18nextBrowserLanguageDetector)
         .init({
		backend: {
			// for all available options read the backend's repository readme file
			loadPath: 'http://remoteserver/locales'
		}
	});
```

## Describe the solution you'd like
It would be nice if there was a way to specify same backend path

## Describe alternatives you've considered
Right now the only way to fix this is to generate the files and somehow get them in the project directory from the server

**Comment by isaachinman** [comment]
You can pass your own `backend` object into the `next-i18next` config.

**Comment by krcaltomas99** [comment]
@isaachinman I'm sorry but i don't understand what you mean?

import NextI18Next from 'next-i18next';
import path from 'path';

```typescript
export const i18n = new NextI18Next({
  otherLanguages: ['cs', 'en'],
  localePath: path.resolve('./public/static/locales'), // This is required for the SSR to work
  defaultLanguage: 'cs',
});

Is there a way to achieve SSR with loading translations from my own backend?

**Comment by isaachinman** [comment]
See #537, and numerous other issues where people have asked the same question over and over.

It's trivial to put this into a build step. If you really want to do this at runtime, there's a small piece of work to remove filesystem lookups, which no one has decided to work on, as of yet.

**Comment by rjoaopereira** [comment]
@isaachinman Could you point me in the direction of what is necessary to remove the filesystem lookups?

**Comment by isaachinman** [comment]
Hey @rjoaopereira – if you just omit the `public/static/locales` dir, you should see a stacktrace that points you in the right direction. There are a couple validation lookups done via fs that just need to be disabled via a new config flag.

**Comment by rjoaopereira** [comment]
> Hey @rjoaopereira – if you just omit the `public/static/locales` dir, you should see a stacktrace that points you in the right direction. There are a couple validation lookups done via fs that just need to be disabled via a new config flag.

After playing around with the code, I propose:

1. Only adding the HTTPBackend and FSBackend when no `backend` modules are present
2. Moving the FS fallback into `create-client` node version if the FSBackend is going to be used (I would remove the error as the fs.read will throw the error anyhow).
3. The users provide their own backends. Only node would be necessary but if we provide one, we have to provide the other as well depending on the platform being targeted.

Your thoughts @isaachinman

**Comment by isaachinman** [comment]
@rjoaopereira The first and second points sound fine. Not sure I understand the third. We need to maintain current behaviour without any breaking changes.

Keep in mind that the current setup for `next-i18next` is in its last days, and a new iteration will land with [this RFC](https://github.com/vercel/next.js/discussions/17078).

**Comment by rjoaopereira** [comment]
I was unaware of this RFC. Thanks for bringing it up! In this case I think that the changes can wait.

**Comment by nouh** [comment]
> @rjoaopereira The first and second points sound fine. Not sure I understand the third. We need to maintain current behaviour without any breaking changes.
> 
> Keep in mind that the current setup for `next-i18next` is in its last days, and a new iteration will land with [this RFC](https://github.com/vercel/next.js/discussions/17078).

this official RFC will be implemented in the plugin,  or it will be nextjs builtin ?
