### ISSUE TITLE
Property 'language' does not exist on type 'IncomingMessage' 

### ISSUE THREAD

**Issue by gpessa** [isaachinman/next-i18next#803]
I have a project with typescript.
When I try to access the language in the initial properties, I get a TS error because is not defined.
Do you know how to fix it (but keep the typing?)

```js
const Index: NextPage = () => {
...
}

Index.getInitialProps = async ({ store, req }) => {
  const locale = req ? req.language : i18n.language; // req not defined
};
```

**Comment by isaachinman** [comment]
Use the `NextI18NextRequest` type which we export.
