### ISSUE TITLE
Error 404 in pages with localeSubpaths

### ISSUE THREAD

**Issue by hrahimi270** [isaachinman/next-i18next#806]
## Describe the bug
After changing language and when URL updates with subpaths, if I refresh the page (hard-reload), Nextjs can't access to that page. It shows an error of 404.

## Occurs in next-i18next version
Next: ^9.5.2
Next-i18next: ^6.0.2
Node: 10.16.2

## Steps to reproduce
I just set up my project using documents. The previous version was using a custom nodejs server. But in this version and current config, using next config rewrites. I doubled check with the documents, and everything seems ok.

## Expected behavior
Open pages with subpaths.

## OS (please complete the following information)
 - Device: Macbook pro 2017 with Mac os 10.15.4 (19E287)
 - Browser: Chrome Version 84.0.4147.135 (Official Build) (64-bit)

## Additional context
It works fine in **development mode**. But not working expected in **production mode**, especially in exported mode (`next export` command).

**Comment by Hamzakh777** [comment]
I got the same issue

**Comment by alonn24** [comment]
I get the same problem as well. Started at v5.
I'm using a custom server + `next-i18next-middleware` and looks like this was the change:
https://github.com/isaachinman/next-i18next/commit/a43d9c8330996be9485a7c663fa0a9170e20cede#diff-6b7305035a7a21c6e43bf5c11b06f0d0L83

Should I use something else to support url subpath?

**Comment by aboudicheng** [comment]
Having the exact same issue after upgrading to v6.0.2, except it happens in development mode as well

**Comment by hrahimi270** [comment]
Hi @isaachinman, any idea on this issue?

**Comment by isaachinman** [comment]
Can someone provide a reproducible repository? `next-i18next` does not support `next export` at this time.

**Comment by seaneking** [comment]
I'm also seeing this, in development as well as prod, using a standard serverless config and `next-i18next`s rewrite helper. Locale paths just 404.

**Comment by aboudicheng** [comment]
Hi @isaachinman , I have created a sandbox here: https://codesandbox.io/s/trusting-stallman-qwyb3

The language switching functionality seems to be working well, and the locale subpaths also update accordingly. If you try to hard-reload the page when the current language is not the default language (English), it returns 404.

Please have a look at it. Thank you in advance!

**Comment by isaachinman** [comment]
You need to use Next v9.5+ if you want to leverage rewrites, as that's the version that introduced the functionality as stable.

**Comment by anialamo** [comment]
> Hi @isaachinman , I have created a sandbox here: https://codesandbox.io/s/trusting-stallman-qwyb3
> 
> The language switching functionality seems to be working well, and the locale subpaths also update accordingly. If you try to hard-reload the page when the current language is not the default language (English), it returns 404.
> 
> Please have a look at it. Thank you in advance!

@aboudicheng did you find some solution? Please some help please! in this case for 404 error page not found when you changes manually the url?

**Comment by anialamo** [comment]
> ## Describe the bug
> After changing language and when URL updates with subpaths, if I refresh the page (hard-reload), Nextjs can't access to that page. It shows an error of 404.
> 
> ## Occurs in next-i18next version
> Next: ^9.5.2
> Next-i18next: ^6.0.2
> Node: 10.16.2
> 
> ## Steps to reproduce
> I just set up my project using documents. The previous version was using a custom nodejs server. But in this version and current config, using next config rewrites. I doubled check with the documents, and everything seems ok.
> 
> ## Expected behavior
> Open pages with subpaths.
> 
> ## OS (please complete the following information)
> * Device: Macbook pro 2017 with Mac os 10.15.4 (19E287)
> * Browser: Chrome Version 84.0.4147.135 (Official Build) (64-bit)
> 
> ## Additional context
> It works fine in **development mode**. But not working expected in **production mode**, especially in exported mode (`next export` command).

@hrahimi270 did you find some solution for this error? only this happen in production mode for me.

**Comment by aboudicheng** [comment]
@anialamo I somehow got it fixed after upgrading Next to v9.5.3 back then, but still not sure why the sandbox I provided isn't working
