### ISSUE TITLE
How can I make a specific language for a specific path (urls)?

### ISSUE THREAD

**Issue by AXLLLOW** [isaachinman/next-i18next#807]
Hello.

We have `localeSubpaths`. With this, we will add our languages to the url for all paths.
```
const { nextI18NextRewrites } = require('next-i18next/rewrites');

const localeSubpaths = {
  'ru': 'ru',
  'ge': 'ge'
};

module.exports = {
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths
  }
};
```

How can I make specific languages for specific urls and not all?
(en - default)

**For example:**
`/news` - valid
`/ru/news` - valid
`/ge/news` - invalid

`/info` - valid
`/ru/info` - valid
`/ge/info` - valid

`/bio` - valid
`/ru/bio` - invalid
`/ge/bio` - invalid

**Comment by isaachinman** [comment]
The `nextI18NextRewrites` function is merely a helper utility. Your rewrites are entirely up to you. Check the output of `nextI18NextRewrites` and modify as desired.
