### ISSUE TITLE
defaultLanguage isn't loaded from the settings

### ISSUE THREAD

**Issue by handrei** [isaachinman/next-i18next#808]
## Describe the bug
defaultLanguage is by default en, even if i set it to 'ro'. everything else is working fine, the translations are ok
before the update to next-i18next to version 6, everything was fine, maybe i mixed up something.

## Occurs in next-i18next version
"next": "^9.5.1",
"next-i18next": "^6.0.2",
"node": "12.18.3"

## Steps to reproduce
next.config.js: 
```
const { nextI18NextRewrites } = require('next-i18next/rewrites');
const localeSubpaths = { en: 'en' };

module.exports = rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  }
```

i18n.js:

```
const NextI18Next = require('next-i18next').default;
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;
const path = require('path');

module.exports = new NextI18Next({
  defaultLanguage: 'ro',
  otherLanguages: ['en'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales'),
});
```

## Expected behaviour
default language must be 'ro'

**Comment by isaachinman** [comment]
Can you please provide a reproducible repo?

**Comment by handrei** [comment]
unfortunately my repo isn't public :(

**Comment by isaachinman** [comment]
No one will be able to assist until you can provide a reproducible repo.

**Comment by handrei** [comment]
ok, then you can close this issue .. i'll figure it out somehow

**Comment by isaachinman** [comment]
@handrei You can try recreating an example of the problem with a fresh/simple repo. Otherwise, if you do end up discovering the issue on your own, please let us know what it was, to help future users. Good luck!

**Comment by handrei** [comment]
Hello again, @isaachinman. i created a repo and did all the configurations like in my project, but in the clean repo is working fine. something must be wrong in my actual project. dont know what else to say. but thank you for your time

**Comment by RezaZR** [comment]
@isaachinman I have this problem too, cannot set default language other than 'en'. 
my **i18n.js** is exactly like in the example:
```
const NextI18Next = require("next-i18next").default;
const { localeSubpaths } = require("next/config").default().publicRuntimeConfig;
const path = require("path");

module.exports = new NextI18Next({
  defaultLanguage: "id", //Indonesia
  otherLanguages: ["en"],
  localeSubpaths,
  localePath: path.resolve("./public/static/locales"),
});
```
when I restart the server, then go to my localhost and its default language still English.

I'm using next-redux-wrapper too, and I wrapped my **_app.js** like this:
```
export default wrapper.withRedux(appWithTranslation(App));
```
Am I wrapping it wrong? But it works tho, just not for the default language.

Looking forward for your answer

**Comment by handrei** [comment]
i wonder if that's a way to re-open the issue. @isaachinman can u help please ? :)

**Comment by isaachinman** [comment]
Check your browser language settings. Most likely you're seeing English because your browser is set to English.

**Comment by handrei** [comment]
@isaachinman can you check this repo please ? https://github.com/handrei/next-translate . it's about the issue i opened this ticket ? i made a repo for it

**Comment by isaachinman** [comment]
@handrei If I clone that repo, and go to the index route with my browser locale set to `ro`, I see the homepage without any locale subpath, in Romanian.

As I said, please read up on how language detection works.
