### ISSUE TITLE
3 bugs (fallback language, redirection error, defaultLanguage as subpath)

### ISSUE THREAD

**Issue by benpetsch** [isaachinman/next-i18next#81]
Thanks for working on this simple solution for internationalization. 
I'm encountering three bugs or at least unexpected behaviours.

Priority of questions for me (1., 2., 3.). Maybe those issues are related, for the reason of my missunderstanding. 

----

My config:
```
{
  otherLanguages: ['an', 'de', 'en'],
  localeSubpaths: true,
  defaultLanguage: 'en-us',
  browserLanguageDetection: true,
  fallbackLng: 'en-us'
}
```

----

### 1. browserLanguageDetection without fallback

**Expected behaviour:**

Browser language is: 'fr'
Request for `http://localhost:3001/faq` should be redirected to `http://localhost:3001/fr/faq`.

Because  'fr' is not present within 'defaultLanguage' or 'otherLanguages' configuration, I expect a fallback to 'fallbackLng'. This should result in `http://localhost:3001/en-us/faq` or `http://localhost:3001/faq` (with en-us language).

**Actual behaviour:**

Browser language is: 'fr'
Request for `http://localhost:3001/faq` is redirected to `http://localhost:3001/fr/ERROR_PAGE` with error message: `Error: Invalid configuration: Current language is not included in all languages array`

Any user with an non-default ('defaultLanguage' or 'otherLanguages') won't be able to use the website.

---

### 2. redirection error after changing language in browser path

**Expected behaviour:**

Browser language is: 'de'
First request for `http://localhost:3001/faq` is redirected to `http://localhost:3001/de/faq` -> 200 OK.
Second  request for `http://localhost:3001/an/faq -> 200 OK.

**Actual behaviour:**

Browser language is: 'de'
First request for `http://localhost:3001/faq` is redirected to `http://localhost:3001/de/faq` -> 200 OK.
Second  request for `http://localhost:3001/an/faq` -> 3XX Redirection Error.
Refresh the page  for `http://localhost:3001/an/faq` -> 200 OK.

error: `The connection http://localhost:3001/_next/webpack-hmr was interrupted, while loading the page.`

---

### 3. defaultLanguage not working as subpath

**Expected behaviour:**

A configuration like this:
```
{
  otherLanguages: ['an', 'de'],
  localeSubpaths: true,
  defaultLanguage: 'en',
  browserLanguageDetection: true,
  fallbackLng: 'en'
}
```

should enable those routes:
```
myapp.com
myapp.com/an/  
myapp.com/de/
myapp.com/en/
```

**Actual behaviour:**

The shown config above does result in:
```
myapp.com
myapp.com/an/  
myapp.com/de/
```
With `browserLanguageDetection: true` the page does automatic redirect to `myapp.com/<DETECTED_LANGUAGE>`. For me it is not possible to get `myapp.com`. Therefore defaultLanguage is not available for user (unless detected by browser).

**Comment by isaachinman** [comment]
If you believe you have found three bugs, please open three different issues.
