### ISSUE TITLE
[country]/[language]

### ISSUE THREAD

**Issue by mykhailo-roshchyna-vp** [isaachinman/next-i18next#811]
Hey, I used additional segment([country) before [language], and after reload the page I loose my translation, url I have http://localhost:3000/IT/it_IT/media (http://localhost:3000/[country]/[language]/media)
translations I have in Italian lang
when I reload the page, I still have: 
http://localhost:3000/IT/it_IT/media
but translation I have in English lang, so I loose translation. 
I try to set up 

next.config.js

const { nextI18NextRewrites } = require('next-i18next/rewrites');

const localeSubpaths = {
  it_IT: '[country]/it_IT/',
  sp_SP: '[country]/gp_SP/',
  pl_PL: '[country]/pl_PL/',
  de_DE: '[country]/de_DE/',
  tr_TR: '[country]/tr_TR/',
  en_UK: '[country]/en_UK',
  ar_EG: '[country]/ar_EG/',
  pg_BR: '[country]/pg_BR/',
};

module.exports = {
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
};

i18next.js

const NextI18Next = require('next-i18next').default;
const path = require('path');
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;

module.exports = new NextI18Next({
  otherLanguages: ['it_IT', 'sp_SP', 'pl_PL', 'de_DE', 'tr_TR', 'en_UK', 'ar_EG', 'pg_BR'],
   localeSubpaths,
  localePath:
    typeof window === 'undefined' ? path.resolve('./public/static/locales') : '/static/locales',
  shallowRender: true,
  ns: ['common', 'footer', 'nav-links'],
  defaultLanguage: 'en_US',
  browserLanguageDetection: false,
});

   
## Occurs in next-i18next version
"next-i18next": "^6.0.2",

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
<img width="1181" alt="Screenshot 2020-08-28 at 17 05 04" src="https://user-images.githubusercontent.com/62095455/91577066-dea17480-e950-11ea-95b5-82abc99be356.png">

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: Chrome 7

**Comment by isaachinman** [comment]
Please post on StackOverflow for help requests. Good luck!
