### ISSUE TITLE
Will there be documentation of how this can be used with Typescript ?

### ISSUE THREAD

**Issue by gromov-io** [isaachinman/next-i18next#813]
I spent 1 hour integrating this into the project, but I came across a lot of incomprehensible obstacles that are not mentioned in the documentation.

I still don't know where to get the types for `t` and the rest of the functions.

**Comment by ljosberinn** [comment]
`t` is probably the `TFunction` from `react-i18next`

**Comment by isaachinman** [comment]
@gromov-io We've got quite a few TS users. What obstacles did you encounter specifically? It would be helpful if you opened issues for each individual problem.
