### ISSUE TITLE
{help} HOC or Hook?

### ISSUE THREAD

**Issue by Pierre-CLIND** [isaachinman/next-i18next#814]
In the documentation you are talking about HOC (withTranslation) but in my code I'm using the hook (useTranslation()), it's work perfectly for now.

There is a difference or it's the same thing? 

(I'm not talking about HOC vs hooks in React, but about how to use Next-i18Next for the best)

**Comment by gromov-io** [comment]
As I understand it, they have absolutely no up-to-date documentation, for example, the project is written in Typescript, and they can't document the use with TS.

At first I used HOC, but then I saw Hook and rewrote everything to hooks, as it is more convenient. I didn't notice any difference.

**Comment by isaachinman** [comment]
The `withTranslation` HOC and the `useTranslation` hook achieve the same thing. Both come from `react-i18next`.

@gromov-io If you feel the documentation is lacking, please open a PR.

**Comment by peterchealse** [comment]
i am lucky to search for this issue

**Comment by Xoce51** [comment]
> As I understand it, they have absolutely no up-to-date documentation, for example, the project is written in Typescript, and they can't document the use with TS.
> 
> At first I used HOC, but then I saw Hook and rewrote everything to hooks, as it is more convenient. I didn't notice any difference.

I also start to change HOC to HOOK, but since when I refresh the page I'm seing a white page with `loading...` text in the top left of the page, am I the only one to have this difference between HOC & HOOK ?
