### ISSUE TITLE
Can't access outside of class

### ISSUE THREAD

**Issue by fuzunspm** [isaachinman/next-i18next#816]
## Describe the bug
I can't access t('key') outside React class it's just outputs key name. It works when i call it with `this.props.t("name")` inside of class

## Occurs in next-i18next version
    "next-i18next": "^4.5.0"

## OS (please complete the following information)
 - Device: MBP 2015 15"
 - Browser: Firefox 80.0.1

```
import { i18n, Link, withTranslation } from "../../i18n";

const columns = [
  {
    name: i18n.t("name"),
  },
]

class Test extends React.Component {} ..
export default withTranslation("common")(Test);
```

**Comment by isaachinman** [comment]
That's down to how React context works. Most likely, the `i18n` import isn't initialised at the time when you declare `columns`, and therefore returns the key instead of the value. You'll need to await the `initPromise`.

**Comment by utiq** [comment]
@fuzunspm how did you solve this?

**Comment by fuzunspm** [comment]
my old solution is not working at the moment with the latest update. I'm using getServerSideProps now and moved all most of variables inside render() method

**Comment by utiq** [comment]
@isaachinman could you provide an example of how to deal with that?

**Comment by isaachinman** [comment]
The `i18n` import will be initialised once the React component tree renders for the first time. So you will need to assign your variable after that point in time.
