### ISSUE TITLE
nameSpacesRequired warning always shows up 

### ISSUE THREAD

**Issue by longquan0104** [isaachinman/next-i18next#820]
![image](https://user-images.githubusercontent.com/24205959/92232656-1c664600-eed9-11ea-8f7c-9a29dcad14f9.png)

Mine is always showing up. Any ideas on how to stop this !? Thank you guys for stopping by

**Comment by isaachinman** [comment]
Can you please provide a reproducible repository?

**Comment by Darkweak** [comment]
Due to NextJS migration from getInitialProps to getServerProps or getStaticProps function

**Comment by nouh** [comment]
use getServerSideProps to provide namespaceRequired seems to be warned

**Comment by gajet5** [comment]
![image](https://user-images.githubusercontent.com/3825412/93854510-90b52d80-fcbe-11ea-8169-c8b47f26c983.png)

I have the same problem.

1) I installed and configured the default plugin.
2) Created a page with parameters.
3) I go to this page in my browser.

The result is up to date:
I get a warning.

Expected:
There is no warning.

**Comment by Darkweak** [comment]
Must lock nextjs version to lower 9.2

**Comment by isaachinman** [comment]
`next-i18next` does not (yet) support `getServerProps`. You need to use `getInitialProps` to pass `namespacesRequired`.

**Comment by gajet5** [comment]
In my situation, I use getInitialProps, you can see it in the screenshot.

**Comment by Darkweak** [comment]
getInitialProps is supported by nextjs lower 9.2. You have to lock nextjs to 9.2 or lower, that's really bad to do that due to lack of performance updates. I opened a PR to support getServerProps and getStaticProps functions according to nextjs support

**Comment by isaachinman** [comment]
@Darkweak The `getInitialProps` method is available in the latest version of NextJs. There is no need to pin to a lower version.

Your PR will be reviewed when it passes all status checks.

**Comment by gajet5** [comment]
@Darkweak As the author has already written above, getInitialProps is still supported and the nextjs command recommends that you switch to the new properties.
https://nextjs.org/docs/api-reference/data-fetching/getInitialProps

**Comment by gajet5** [comment]
Okay, I found out what my problem was.
I was wrong. Instead of importing the function withTranslate from the configured plugin, I imported the function from the library.
Mb the bug author has the same problem?
![image](https://user-images.githubusercontent.com/3825412/93860131-471d1080-fcc7-11ea-80b3-9d7aade4648f.png)

**Comment by Maczuga** [comment]
Might be related, I have same issue with getInitialProps, but using useTranslations (from NextI18Next) hook instead of HOC.
