### ISSUE TITLE
404 Error when trying to access any page with localeSubpaths config provided

### ISSUE THREAD

**Issue by powerczuk** [isaachinman/next-i18next#824]
I'm facing the 404 issue when trying to access any page of my Next.js application.

**Next.js** latest
**next-i18next** latest

App works fine when no localeSubpaths config is provided.
After setup of localeSubpaths config:

**next.config.js**:
```javascript
const localeSubpaths = {
  en: "en",
  "de-DE": "de-DE",
  "de-CH": "de-CH",
  fr: "fr"
};
```

app is not working any more.

Every time I'm trying to access main root `/` or any of the locale pages fr, de-DE browser displays the `404 Error Page` (Customized Next.js error page - translation works for the error page).

Error Page contains also a link to the `/` Home Page. When I'm navigating to the Home Page by clicking on the link -> Home Page loads correctly (including related translations). After another page reload I'm facing again the 404 issue.

**i18n config file:**

```javascript
import NextI18Next from "next-i18next";
import getConfig from "next/config";
import path from "path";

const { publicRuntimeConfig } = getConfig();
const { localeSubpaths } = publicRuntimeConfig;

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: "en",
  ns: ["common"],
  defaultNS: "common",
  otherLanguages: ["de-DE", "de-CH", "fr"],
  strictMode: false,
  localeSubpaths,
  localePath: path.resolve("./public/static/locales")
});

export default NextI18NextInstance;

const {
  appWithTranslation,
  i18n,
  Link,
  withTranslation,
  Router
} = NextI18NextInstance;

export { appWithTranslation, i18n, Link, withTranslation, Router };
```

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by DamianBusz** [comment]
I gotta pin up myself to this. I got the exactly same issue and Im not sure what is going on. 
I got pretty much fresh setup with next higher than 9.5+ and latest next-i18next.

**Comment by isaachinman** [comment]
@DamianBusz Can you provide a reproducible repo?

**Comment by DamianBusz** [comment]
@isaachinman I'm currently not home and to setup an reproducible repo might take me some time as our project is quite big.
I will try to get back here in the morning. 

Right now all I can say is that next is 9.5+ and I'm getting 404 and also having custom _error.js.
Seems like next.js routing is not getting correct paths as if we dummy creame a /de folder and put routes into this it catches it correctly.

**Comment by powerczuk** [comment]
@isaachinman I also prepared small example [reproductible repo](https://github.com/powerczuk/next-i18next-test )

**Comment by DamianBusz** [comment]
> @isaachinman I also prepared small example [reproductible repo](https://github.com/powerczuk/next-i18next-test)

404 on the repo, perhaps u did it as private?

**Comment by powerczuk** [comment]
> 404 on the repo, perhaps u did it as private?

right, now should be fine

**Comment by TroyTae** [comment]
I have same issue.
If I enter page with `Link` component, it works fine.
But if I write url directly or refresh page, I get 404 page in dev mode.

**Comment by isaachinman** [comment]
@powerczuk I have cloned that repo, and cannot reproduce any 404 by switching locales and hard reloading. Can you provide any more information?

@TroyTae Please make sure you're using Next v9.5+.

**Comment by TroyTae** [comment]
@isaachinman 
Yes now I'm using v9.5.3

**Comment by isaachinman** [comment]
I will need a reproducible example to be able to debug this.

**Comment by DamianBusz** [comment]
@isaachinman any idea what happends in the codesandbox I provided?
Getting 404 on /en regardless of good next version.

**Comment by powerczuk** [comment]
@isaachinman  hmm it's really strange. I've just checked it on two separate machines and the issue is still there.

node 12.5.0
next. 9.5.3
next-i18next 6.0.2

I've tried both dev and start commands.

**Comment by Axiol** [comment]
I have the exact same error, 404 on all pages. I have a repo with the code, but it's part of company project, so I can't really share it.

next 9.5.3
next-i18next 6.0.2
react 16.13.1
apollo/react-hooks 3.1.5

**Comment by isaachinman** [comment]
@DamianBusz If I clone [this sandbox](https://codesandbox.io/s/clever-galois-4w1ty) and run immediately, I do indeed see the "error", but that's because the Next version is below v9.5. If I do a `yarn add next` and run again, the error goes away.

@powerczuk If I clone [this repo](https://github.com/powerczuk/next-i18next-test) and run, I do not experience any 404s at all.

**Comment by powerczuk** [comment]
> @powerczuk In your repo, you've put `rewrites` inside `publicRuntimeConfig` in your `next.config.js`, instead of at the top level, where it should be.

omg... my bad. Many thanks for pointing the problem.!

**Comment by lgarro** [comment]
In my case the issue was migrating from an old version to a new white label project, and left the `experimental` with rewrites on it. So I was getting 404's on localeSubpaths

**Comment by mlnima** [comment]
same issue here, I use Express in the backend, and I get 404, ant solution, or example repo?
