### ISSUE TITLE
TypeScript documentation enhancement

### ISSUE THREAD

**Issue by allan2** [isaachinman/next-i18next#825]
## Is your feature request related to a problem? Please describe.
I think more explicit TypeScript documentation and additional examples would be helpful to users of `next-i18next`.

For example, even a short one like:

JS:
```jsx
const Component = ({ t }) => <p>{t('hello')}</p>
```
TS:
```tsx
import { TFunction } from 'next-i18next';
const Component = ({ t }: { readonly t: TFunction }) => <p>{t('hello')}</p> 
```
would be helpful to users in https://github.com/isaachinman/next-i18next/issues/627 and https://github.com/isaachinman/next-i18next/issues/813. I know it's right there in the `types.d.ts` file but writing it out in English/example code would make this great package _friendlier_ to use.

I read [here](https://github.com/isaachinman/next-i18next/issues/623#issuecomment-595673328) that @isaachinman doesn't want to recommend how to type `t`. I like how they do it in the [React TypeScript Cheatsheet](https://github.com/typescript-cheatsheets/react):
```tsx
// Example 1: typing on props
const App = ({ message }: AppProps) => <div>{message}</div>;

// Example 2: explicit return. Some minor differences like implicit children 
const App: React.FunctionComponent<{ message: string }> = ({ message }) => (
  <div>{message}</div>
);
```
giving you some options and pratfalls and stating whether (or not) there are any differences.

## Describe the solution you'd like

- a section in the README on TypeScript support
    - descriptions for commonly-used exported types
    - some short examples
- the simple example fully-typed
    - including `i18n.ts` example

I'll make a PR soon with some proposed docs. Let me know what you think!

**Comment by isaachinman** [comment]
Sure, I wouldn't mind creating a `TYPESCRIPT.md` doc file for this.

**Comment by isaachinman** [comment]
TypeScript example here:

https://github.com/isaachinman/next-i18next-typescript
