### ISSUE TITLE
I think you don't need to `warn` message if namespacesRequired provide at page level.

### ISSUE THREAD

**Issue by sithu05** [isaachinman/next-i18next#828]
Firstly, I think `every` page level need to provider `getInitialProps`. that is very confused at `above Next 9` version. 
And, `react.i18next` also support the `useTranslation (hook)`. 
So, I think we should force to use `hook` instead of `HOC`. 
thanks for you supporting

**Comment by isaachinman** [comment]
You can opt out of warning messages by setting `strictMode` in the config to `false`.

**Comment by sithu05** [comment]
noted, thanks.
