### ISSUE TITLE
sub links url not working with static files

### ISSUE THREAD

**Issue by beqramo** [isaachinman/next-i18next#829]
Hi, first of all, thanks for this library.
but I have encountered this problem :
<img width="177" alt="Screen Shot 2020-09-12 at 12 28 04" src="https://user-images.githubusercontent.com/40486471/92991243-99a24400-f4f3-11ea-8a7c-0c3ce3794087.png">
I use this kind of URL configuration, but when I enter on this link I get this error:
<img width="647" alt="Screen Shot 2020-09-12 at 12 30 53" src="https://user-images.githubusercontent.com/40486471/92991266-d40be100-f4f3-11ea-8eb6-e9b987a1d6b3.png">
URL is wrong for static files, I checked on pure next js project and it creates correct URLs.

**Comment by isaachinman** [comment]
You'll need to use the `ignoreRoutes` option.

**Comment by beqramo** [comment]
Thanks for your answer but I haven't found it helpful.
I added ``blogs/``, ``blogs/repair``, ``blogs/repair/`` in ``ignoreRoutes ``  but none of them was ideal. it throwing the same error.

**Comment by beqramo** [comment]
@isaachinman can you tell me exactly how is it possible? in above link ``ka`` is language

**Comment by beqramo** [comment]
I found it. It was my mistake, I was loading my static files without ``/`` in front of `static` directory
