### ISSUE TITLE
redirection error after changing language in browser path

### ISSUE THREAD

**Issue by benpetsch** [isaachinman/next-i18next#83]
**Expected behaviour:**

Browser language is: 'de'
First request for `http://localhost:3001/faq` is redirected to `http://localhost:3001/de/faq` -> 200 OK.
Second  request for `http://localhost:3001/an/faq -> 200 OK.

**Actual behaviour:**

Browser language is: 'de'
First request for `http://localhost:3001/faq` is redirected to `http://localhost:3001/de/faq` -> 200 OK.
Second  request for `http://localhost:3001/an/faq` -> 3XX Redirection Error.
Refresh the page  for `http://localhost:3001/an/faq` -> 200 OK.

error: `The connection http://localhost:3001/_next/webpack-hmr was interrupted, while loading the page.`

----

My config:
```
{
  otherLanguages: ['an', 'de', 'en'],
  localeSubpaths: true,
  defaultLanguage: 'en-us',
  browserLanguageDetection: true,
  fallbackLng: 'en-us'
}
```

**Comment by isaachinman** [comment]
Not sure I understand this one. Can you please provide a reproducible example (repo)?

**Comment by isaachinman** [comment]
Hi there, any update?

**Comment by benpetsch** [comment]
will provide an repo tomorrow

**Comment by isaachinman** [comment]
Any update? Is this related to #92?

**Comment by benpetsch** [comment]
Yes version 0.19.0 looks good for this one.
