### ISSUE TITLE
Example app fails on generate-rewrites

### ISSUE THREAD

**Issue by Seybo** [isaachinman/next-i18next#830]
## Describe the bug
Example app doesn't run
`Error: Cannot find module './dist/commonjs/utils/generate-rewrites'`

## Occurs in next-i18next version
it's the example app

## Steps to reproduce
`cd next-i18next/examples/simple`
`yarn`
`yarn add react react-dom`
`yarn dev`

## Expected behaviour
the app should start

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/10584167/92997996-d80c2300-f534-11ea-9c56-d718cb3dc5ab.png)

## OS (please complete the following information)
 - Device: Ubuntu 18.04

**Comment by isaachinman** [comment]
There are contributing docs [here](https://github.com/isaachinman/next-i18next/blob/master/CONTRIBUTING.md). The simple example is online at next-i18next.com, it definitely runs.
