### ISSUE TITLE
Automatic detection doesn't work in every browser.

### ISSUE THREAD

**Issue by arguiot** [isaachinman/next-i18next#832]
## Describe the bug
Automatic language detection doesn't work in Safari and browsers that protect privacy.

## Occurs in next-i18next version
v6.0.2

## Steps to reproduce
Use Safari and see.

## Expected behaviour
I expect next-18nect to be using `navigator.language` when possible or the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header for language detection. Theses things are **always** working.

## OS (please complete the following information)
 - Device: [e.g. MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)]
 - Browser: [e.g. Safari 14.0 (16610.2.2.4)]

## Additional context
Default config is used.

**Comment by isaachinman** [comment]
This package doesn't handle any of the actual detection logic itself. I recommend you open an issue in `i18next-http-middleware`.

**Comment by CusthomeDev** [comment]
Hi @isaachinman,

You said the issue with Safari come from `i18next-http-middleware`, but after hours spent to understand what's going wrong with Safari it seems to come from your package.

When I download the basic exemple from `i18next-http-middleware` here [Basic example](https://github.com/i18next/i18next-http-middleware/tree/master/example/basic). The locale detection works perfectly in Safari.

But when I download your `next-i18next` example here [Simple example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple), the locale detection doesn't work.

So, is it possible for you to look closer at this issue ?

Regards

**Comment by isaachinman** [comment]
@CusthomeDev Is the `i18nextMiddleware` configuration _identical_ in those two examples? It doesn't seem so to me.
