### ISSUE TITLE
Why doesn't import nextI18NextMiddleware in server?

### ISSUE THREAD

**Issue by JEONGJIHUN** [isaachinman/next-i18next#833]
## Describe the bug
You must provide a clear and concise description of what the bug is.

Why doesn't import nextI18NextMiddleware in server?

I couldn't find middleware route in `next-i18next`.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.
"next-i18next": "^6.0.2",

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

```js
const next = require('next');

const http = require('http');
const express = require('express');
const app = next({ dev: process.env.NODE_ENV !== 'production' });
const nextI18NextMiddleware = require("next-i18next/middleware").default; //
const nextI18next = require('./I18n').default;
const handle = app.getRequestHandler();
const port = process.env.PORT || 8080;

(async () => {
  await app.prepare();
  const server = express();

  await nextI18next.initPromise;
  server.use(nextI18NextMiddleware(nextI18next));

  server.all('*', (req, res) => {
    return handle(req, res);
  });

  server.get('*', handle);
  server.post('*', handle);

  http.createServer(server).listen(port, err => {
    if (err) throw err;
    console.log(`> Server is listening on port ${port}`);
  });
})();
```

I was tried using this code. but failed. and then I was tried route change.

```js
const nextI18NextMiddleware = require('next-i18next/dist/es/middlewares')
  .nextI18NextMiddleware;
```

The error message is SyntaxError: Unexpected token 'export'.
```js
export { default as nextI18NextMiddleware } from './next-i18next-middleware';
^^^^^^
```

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2017 15"]
 - Browser: [e.g. Chrome 79.0.3945.130]

## Additional context

Thank you in advance.

**Comment by isaachinman** [comment]
This question has been asked and answered several times. `next-i18next` no longer requires users to have custom servers. You can still use a custom server if you want, but there's no middleware requirement. Read the docs! Good luck.
