### ISSUE TITLE
req.i18n is not defined if navigate to a page using Link component

### ISSUE THREAD

**Issue by hrahimi270** [isaachinman/next-i18next#834]
## Describe the bug
If I open a page with entering the URL in the browser, and that page has the `getInitialProps`, it opens fine.
But, if I navigate to that same page, using the `<Link />` component, it throws an error that `ctx.req.i18n` is not defined.

## Occurs in next-i18next version
6.0.2

## Steps to reproduce
```jsx
MyPage.getInitialProps = async (ctx) => {
	const namespacesRequired = ["common"];
	const lang = lngFromReq(ctx.req);

	// ... other codes

	return {
		namespacesRequired,
		// ... other props
	}
}
```

## Expected behavior
Works fine like when it opens manually by entering the URL in the browser.

## Screenshots
<img width="988" alt="Screen Shot 2020-09-17 at 3 54 48 PM" src="https://user-images.githubusercontent.com/38007163/93464367-4e769f80-f8fe-11ea-822d-a3178a3157b1.png">

## OS (please complete the following information)
 - Device: Macbook pro 2017, 13inch
 - Browser: Chrome last version

**Comment by isaachinman** [comment]
That's because the context object is only exposed during SSR. Please read up on the NextJs docs. Good luck!
