### ISSUE TITLE
defaultLanguage not working as subpath

### ISSUE THREAD

**Issue by benpetsch** [isaachinman/next-i18next#84]
**Expected behaviour:**

A configuration like this:
```
{
  otherLanguages: ['an', 'de'],
  localeSubpaths: true,
  defaultLanguage: 'en',
  browserLanguageDetection: true,
  fallbackLng: 'en'
}
```

should enable those routes:
```
myapp.com
myapp.com/an/  
myapp.com/de/
myapp.com/en/
```

**Actual behaviour:**

The shown config above does result in:
```
myapp.com
myapp.com/an/  
myapp.com/de/
```
With `browserLanguageDetection: true` the page does automatic redirect to `myapp.com/<DETECTED_LANGUAGE>`. For me it is not possible to get `myapp.com`. Therefore defaultLanguage is not available for user (unless detected by browser). 

----

My config:
```
{
  otherLanguages: ['an', 'de', 'en'],
  localeSubpaths: true,
  defaultLanguage: 'en-us',
  browserLanguageDetection: true,
  fallbackLng: 'en-us'
}
```

**Comment by isaachinman** [comment]
@benpetsch This is [explained in the README](https://github.com/isaachinman/next-i18next#5-locale-subpaths). Presently, we are not creating a locale subpath for the default lang. If you'd like to help get this functionality merged, feel free to check out the long-standing PR: #24.
