### ISSUE TITLE
Build warning: appWithTranslation  opted-out Automatic Static Optimization due to getInitialProps in pages/_app

### ISSUE THREAD

**Issue by nataliaroque77** [isaachinman/next-i18next#840]
## Describe the bug
_app.tsx has not getInitialProps but we get a build, but appWithTranslation has getInitialProps

Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`

## Occurs in next-i18next version
"next-i18next": "^4.2.1"

## Steps to reproduce
docker-compose up

## Expected behaviour
No opted-out Automatic Static Optimization warnings

**Comment by nataliaroque77** [comment]
@isaachinman  do you know a solution regarding this waring, I read different reports about this, but there is not solution.

Thank you, kindly

**Comment by isaachinman** [comment]
Hi there, please search through previous issues.

**Comment by nataliaroque77** [comment]
@isaachinman 

Please re-open issue.   
Is related to appWithTranslation HOC  getInitialProps.  I found related issues, but there is not solution yet, this one is the closes one. https://github.com/isaachinman/next-i18next/issues/77

**Comment by fillon** [comment]
@nataliaroque77 how did you fix it?

**Comment by nataliaroque77** [comment]
There is not fix for this yet,  people with similar issues were worst, they app was not doing translations, etc.   Our app is doing translations, things work fine - but the warning is not nice.  Team that do the deployment raised to us.  They don't want warnings :(

**Comment by SalahAdDin** [comment]
> since we cant use serverSideProps together with initialProps. we can make use of React FunctionComponent.defaultProps
> here is the workaround that works for me, and it still works with initialProps ([#615 (comment)](https://github.com/isaachinman/next-i18next/issues/615#issuecomment-575578375))
> 
> 1. particular page
> 
> ```
> Page.defaultProps = {
>       i18nNamespaces: ['home-page']
> }
> ```
> 
> 1. main app / _app.tsx
> 
> ```
> MyApp.getInitialProps = async (appContext: AppContextType<Router>) => {
>     const appProps = await App.getInitialProps(appContext)
>     const defaultProps = appContext.Component.defaultProps
>     return {
>         ...appProps,
>         pageProps: {
>             namespacesRequired: [...(appProps.pageProps.namespacesRequired || []), ...(defaultProps?.i18nNamespaces || [])]
>         }
>     }
> }
> ```

Well, i thought it would work good, but it works with delay:
![Screen Capture_select-area_20201201232330](https://user-images.githubusercontent.com/5034215/100793054-a5cfda80-342c-11eb-9493-1c493057b88d.gif)

At the first loading, it does not load the `skill-test` namespaces, i need to reload it to get that namespace active and the proper localization strings.

Inspecting it for the first time we get this:
![Screen Capture_select-area_20201201232220](https://user-images.githubusercontent.com/5034215/100793222-dc0d5a00-342c-11eb-8217-fdc183a570c5.jpg)

After reloading, we can find the required namespace:
![image](https://user-images.githubusercontent.com/5034215/100793400-17a82400-342d-11eb-999f-9289e1f6ea9a.png)

Both namespaces are in the option, but just the first one, defined on `_app.js` by `getInitialProps`, is loaded.

Why does this happen?

**Comment by isaachinman** [comment]
@SalahAdDin This will be solved by #869.
