### ISSUE TITLE
Save the chosed language in cookie longer than a session

### ISSUE THREAD

**Issue by Divlo** [isaachinman/next-i18next#842]
## Is your feature request related to a problem? Please describe.

Currently, the chosed language is saved under a cookie called "next-i18next" but it's only for the Session, If I close my browser and comeback the langage is not saved...

## Describe the solution you'd like

I would love an option in `NextI18Next` class, under the `detection` object maybe we can call it `cookieExpiresIn` and we can put in ms or minutes when the cookie should expired.

## Describe alternatives you've considered

Do you think I can achieve what I want with customDetectors ?
I have no idea how to do it.

**Comment by isaachinman** [comment]
This sounds like an issue to raise in the [i18next-http-middleware](https://github.com/i18next/i18next-http-middleware) repo, as that's where those options come from.

**Comment by Divlo** [comment]
> This sounds like an issue to raise in the [i18next-http-middleware](https://github.com/i18next/i18next-http-middleware) repo, as that's where those options come from.

Alright thanks for your help, I'll take a look but where can I pass options for i18next-http-middleware in next-i18next ?

**Comment by Divlo** [comment]
I found out how to do it, in case anyone wanted to do the same here is my NextI18Next instance i'm exporting : 
```ts
import NextI18Next from 'next-i18next'
import path from 'path'

export const nextI18Next = new NextI18Next({
  browserLanguageDetection: true,
  serverLanguageDetection: true,
  defaultLanguage: 'en',
  otherLanguages: ['fr'],
  localePath: path.resolve('public', 'locales'),
  detection: {
    cookieMinutes: 24 * 60 * 365, // 1 year
    cookieSecure: true,
    cookiePath: '/',
    cookieSameSite: 'strict',
    lookupCookie: 'lang',
    lookupQuerystring: 'lang',
    caches: ['cookie'],
    order: ['querystring', 'cookie', 'header']
  }
})

```
