### ISSUE TITLE
Manually enter URL works in dev mode but not in the production mode

### ISSUE THREAD

**Issue by yingqi-chen** [isaachinman/next-i18next#852]
## Describe the bug

I used the example, and add localSubpaths. When in dev mode, I can go to a page through both clicking on the link on the page and manually input the URL, but when I run `next build && next export` to build and deploy to firebase, I can only go to a page by clicking on the link on the page, by manually input the URL will display errors and on the console, I get error of `Failed to load resource: the server responded with a status of 404 ()`.

Not sure if I misuse localSubpaths or it is firebase problem.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.

```
Versions:
     npm: 6.14.4
    "i18next": "^14.0.1",
    "next": "^9.5.4",
    "next-i18next": "^6.0.2"
```

## Steps to reproduce

1. Go to 'https://github.com/yingqi-chen/next-i18next-problem-demo'
2. Git clone and run npm install
3. Enter npm run dev and when you click on the pricing on the right top corner, it will work.
4. Set up with firebase: Run firebase init and choose hosting, pick out as the public folder, choose no to both overwrite requests to index.html and 404.html, and pick any projects in your firebase(because we will not deploy, but we need a project to run firebase serve)
5. Run npm run build.
6. Run firebase serve
7. Then open the browser and go to the host address, manually enter "[the host address]/pricing", it will fail, but when you click on the pricing on the right top corner, it will work.
8. Open the console and see errors

## Expected behaviour
Manually input URL will work too.

## OS (please complete the following information)
 - Device: [windows 10]
 - Browser: [Chrome 85]

**Comment by isaachinman** [comment]
[next export is not supported](https://github.com/isaachinman/next-i18next#notes).

**Comment by yingqi-chen** [comment]
Thanks for your quick response! @isaachinman I saw the other discussion and wonder what CRA in react-i18next is? Thanks!

**Comment by yingqi-chen** [comment]
For who has the same question, just build another copy for EACH language under pages. That's the only thing I can find. 
So Next.js can find it according to the route `/zh/`

```
pages
  --zh
     --pricing.js
  --pricing.js
```
