### ISSUE TITLE
using getstaticprops

### ISSUE THREAD

**Issue by saeedPadyab** [isaachinman/next-i18next#853]
Hello.
my application redirects to default language in production environment. i have two locales "en and fa". default is en but when i enter url with "/fa" it redirect to en which is default. the point is that before adding getstaticprops function to index page it had been working .

next-i18next == latest version
next == latest version
--------------
`const NextI18Next = require("next-i18next").default;
const { localeSubpaths } = require("next/config").default().publicRuntimeConfig;
const path = require("path");

module.exports = new NextI18Next({
  otherLanguages: ["fa"],
  defaultLanguage: "en",
  localeSubpaths,
  localePath: path.resolve("./public/static/locales"),
  detection: {
    lookupFromPathIndex: 0,
    load: "languageOnly",
    order: [],
  },
});`

**Comment by isaachinman** [comment]
Duplicate of #586.
