### ISSUE TITLE
Default namespace not found at "/public/static/locales/en/common.json" when using Locize backend

### ISSUE THREAD

**Issue by cheunjm** [isaachinman/next-i18next#854]
## Describe the bug
You must provide a clear and concise description of what the bug is.

When backend (Locize) is provided, it is expected to find the namespace from the provided backend. However, its trying to search inside the /public/static folder.

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.

"next-i18next": 6.0.3

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

1. npx create-next-app
2. Add i18n.js with LocizeBackend
```
const NextI18Next = require('next-i18next').default
const LocizeBackend = require('i18next-locize-backend');

module.exports = new NextI18Next({
  use: [
    LocizeBackend
  ],
  backend: {
    projectId: PROJECT_ID
    apiKey: API_KEY
    version: process.env.LOCIZE_VERSION || 'latest',
  },
})
```
3. Update _app.js
```
import '../styles/globals.css'

import { appWithTranslation} from '../i18n'

function MyApp({ Component, pageProps }) {
  return <Component {...pageProps} />
}

export default appWithTranslation(MyApp)
```

## Expected behaviour
You must provide a clear and concise description of what you expected to happen.

It should import the namespace and translations from the backend

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/2954778/95828811-47b72e80-0cea-11eb-894b-95dd689a064b.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

## Additional context

Tried to follow https://stackoverflow.com/questions/55994799/how-to-integrate-next-i18next-nextjs-locize, @adrai's https://github.com/isaachinman/next-i18next/pull/705, but not working.

**Comment by adrai** [comment]
Did you have a look at this example?

https://github.com/isaachinman/next-i18next/pull/705/files#diff-298f611f00b8b2af48be7437472270aef3e5b04c22279ef40f1b85e418ab7662

Set debug to true and check the logs, maybe this helps.

**Comment by cheunjm** [comment]
@adrai Hi, I did take a look at the example, and tried setting require('i18next-locize-backend/cjs') as plugin, but it still gives me 

```
Error: Default namespace not found at /public/static/locales/en/common.json
    at createConfig (/Users/jaemincheun/Documents/coding/test-i18n/node_modules/next-i18next/dist/commonjs/config/create-config.js:94:17)
    at new NextI18Next (/Users/jaemincheun/Documents/coding/test-i18n/node_modules/next-i18next/dist/commonjs/index.js:57:48)
    at eval (webpack-internal:///./i18n.js:5:18)
```

It seems like it's still trying to find the translations in the locale path

**Comment by adrai** [comment]
You are right, there might have been a change that prevents the usage of other i18next backends... any idea @isaachinman ?

@cheunjm the alternative possibility should still work => download the json and include in the app https://github.com/isaachinman/next-i18next/pull/705/files#diff-b62ea49349550876c39d7358d1cf0e5d8a773549e8305c440a038b0ba3a58a06R10

**Comment by isaachinman** [comment]
@cheunjm You can check the logic for the fs lookup [here](https://github.com/isaachinman/next-i18next/blob/a43d9c8330996be9485a7c663fa0a9170e20cede/src/config/create-config.ts#L64). I think some users have run into issues with this in the past, but no one has ever put forth a PR. Happy to answer any questions you might have!

**Comment by adrai** [comment]
Probably doing something like this would fix the problem:
![image](https://user-images.githubusercontent.com/1086194/95885693-dde86480-0d7d-11eb-96ce-bb67064a0b31.png)

**Comment by isaachinman** [comment]
Yep, that'd work fine.

**Comment by adrai** [comment]
@cheunjm Do you like to create a PR?

**Comment by cheunjm** [comment]
@adrai @isaachinman yeah happy to submit one over the weekend
