### ISSUE TITLE
How do you get access to i18n (t, changeLanguage) in an /page/api route ?

### ISSUE THREAD

**Issue by fillon** [isaachinman/next-i18next#857]
I need to have access to i18n inside an api route (serverless).

```js
module.exports = new NextI18Next ({
  // ignoreRoutes: ['/data/', '/_next/', '/static/', '/public/', '/api/'],
  ignoreRoutes: [ '/data/', '/_next/', '/static/', '/public/' ],
  localePath: path.resolve ('./public/static/locales'),
  localeSubpaths,
  otherLanguages: [
    'de',
    'fr',
  ],
});
```

I have removed '/api' in the ignoreRoutes. The req object doesn't seem to be populated with i18n.

Am i missing something?

**Comment by isaachinman** [comment]
The middleware logic occurs on the `appWithTranslation` HOC, so your API routes won't work in this way. Please check the RFC below for future support.

https://github.com/vercel/next.js/discussions/17078
