### ISSUE TITLE
Custom detectors documentation

### ISSUE THREAD

**Issue by doliG** [isaachinman/next-i18next#859]
## Describe the bug

Not sure it is a bug, but it's not a feature request either.

I want to implement _custom detectors_ and _use a specific cookie_ for i18n. We already use a cookie for i18n which is formatted like this: `id.lang.currency` (I.E `6.us.USD`).

[This article](https://dev.to/justincy/locale-specific-domains-for-i18n-in-next-js-with-next-i18next-54hi) was really helpful to understand how custom detectors works, and thanks to it I have managed to make one for my cookies.

However, the cookie next-i18next is still set, and is not relevant.

Also, I have a lot of questions:
- If my detector return nothing, what happens ? (my bet: it will use default locale)
- If all my detectors returns nothing, what happens ? (my bet: it will use default locale)
- If I have multiple detectors which returns differents locales, what happens ? (my bet: it will use the first one which return a valid locale)
- How can I use my custom cookie _instead of_ next-i18next cookie ?

## Expected behaviour

I can find in the Readme a section explaining what I need to do, and where I need to look for, if I want to customize cookie usage and browser detection.

---

I have to admit that between i18next, react-i18next and next-i18next I am lost and do not know where to look for answers.

Thanks for reading, and for your help 🙏

**Comment by isaachinman** [comment]
Please post on StackOverflow, or similar. Good luck!

**Comment by doliG** [comment]
Thanks for your quick response 🙃 

I am afraid my first message was drafty, sot let me clarify.

I have a lot of custom needs in my application. To do so, I'm trying the `customDetectors` functionality. It looks like customDetectors are part of `next-i18next`, as mentioned in the Readme:

> This table contains options which are specific to next-i18next. All other i18next options can be passed in as well.
> From https://github.com/isaachinman/next-i18next#options

My main problem is that I don't fully understand how I'm supposed to implement a `customDetector`, what side effects it can have, and I can't find anything in the Readme on that topic.

Not sure StackOverflow is a suitable replacement of a proper documentation.

Thanks for helping 🙏

**Comment by davidwgrossman** [comment]
@doliG this issue helped me out https://github.com/isaachinman/next-i18next/issues/531

Also, check out [this minimal example](https://github.com/davidwgrossman/next-i18next/blob/master/examples/simple/i18n.js#L6-L31) I set up. Hope that helps!

This Express guide helped out too https://expressjs.com/en/guide/writing-middleware.html

**Comment by doliG** [comment]
Hello @davidwgrossman ,

Thanks a lot for your help ! Indeed, the minimal example is useful. I finally came up with this solution (which works, at least for my needs):

```js
const domainLocaleMap = {
  'localhost': 'en',
 // other domains
};

export default {
  name: 'domainDetector',
  lookup(req, res, options) {
    const hostname = (typeof window !== 'undefined')
      ? window.location.hostname
      : req.headers.host?.split(':')[0]

    return domainLocaleMap[hostname] // TODO need fallback ? or not ?
  }
};
```

I still think that there should be a documentation of how the `detector` object works, or at least an API reference.
