### ISSUE TITLE
Translation usage outside React components

### ISSUE THREAD

**Issue by andylacko** [isaachinman/next-i18next#86]
Hello, I didn't find how to use t() function inside for example redux action file, something like import t from 'i18n' and then use as in components, is it possible to use it outside component with withNamespaces defined?

**Comment by isaachinman** [comment]
The `NextI18Next` class has an entire `i18n` instance on it. Perhaps you should ask this question in the `react-i18next` repo, it's not specific to the source code here. I'm afraid I don't have an answer for you, except that you probably shouldn't need to imperatively translate content.

**Comment by isaachinman** [comment]
@andylacko It seems you can use the `t` func directly off the `i18n` instance:

```jsx
import { i18n } from '../i18n'

const translation = i18n.t('hello-world')
```

**Comment by andylacko** [comment]
oh, great, it works 👌 Thanks for replying here, I know this is not stackoverflow...
