### ISSUE TITLE
NextJS base path setting is not used on client

### ISSUE THREAD

**Issue by Bastian** [isaachinman/next-i18next#860]
## Describe the bug

When using the [`basePath`](https://nextjs.org/docs/api-reference/next.config.js/basepath) config option of NextJS, I get the following error when trying to change the language using `i18n.changeLanguage(...)`:
![image](https://user-images.githubusercontent.com/5033001/96463002-89823080-1226-11eb-9dff-42eeefd6780d.png)

I think this is related to this part of the code: https://github.com/isaachinman/next-i18next/blob/a538ad4b4fb9357c36b189849e351190ed138013/src/config/create-config.ts#L98-L113
It just removes the `/public` part from the `localePath` but does not add the `basePath` if it is set.

## Occurs in next-i18next version

Latest version (6.0.3)

## Steps to reproduce

Please tell me if you want me to create a small example project.

**Comment by rafaelakiyoshi** [comment]
I'm having the same problem here...

**Comment by isaachinman** [comment]
Will be fixed by #869.
