### ISSUE TITLE
Support for loading translation data via resources field

### ISSUE THREAD

**Issue by Markus357** [isaachinman/next-i18next#863]
My use-case requires that the translation strings be loaded into the app from an API.

Previously I had success initializing things this way:

```
const resources = fetchTranslations()
const lng = 'en'

i18n
  .use( initReactI18next )
  .init({ resources, lng })
})
```

Using next-i18next it appears that loading locales using json files is a hard requirement.

**Comment by isaachinman** [comment]
Nope, not a hard requirement. You can use any i18next backend you like. Good luck!
