### ISSUE TITLE
localeSubpaths with other dynamic routes

### ISSUE THREAD

**Issue by jamiechong** [isaachinman/next-i18next#864]
I have the use case where my URL structure can't have `:lang` at the base of the path. I need this: 

`https://example.com/:market/:country/:lang/something/:slug`

Is there a way to setup `localeSubpaths` as well as `Link` to be able to work with extra dynamic route params?

**Comment by isaachinman** [comment]
There isn't anything out of the box to support arbitrary patterns like this, unfortunately.

I recommend you take a look at [this RFC](https://github.com/vercel/next.js/discussions/17078) as support for it will be landing very soon.

If you cannot change your URL structure, I would suggest you fork `next-i18next` and make the necessary changes. Good luck!
