### ISSUE TITLE
Can't localize strings with HTML

### ISSUE THREAD

**Issue by AliRain** [isaachinman/next-i18next#868]
## Describe the bug
I have a string that contains HTML. Whenever I try to render it, it just outputs the key rather than the string.

## Occurs in next-i18next version
next-i18next@6.0.3

## Steps to reproduce
public/static/locales/en/signup.json
```json
{
"accept-terms": "By clicking below to create your account, you are agreeing to our <a href=\"agreement\" target=\"_blank\">Terms of Service</a>"
}
```
src/pages/signup.tsx
```jsx
import { TFunction } from 'next-i18next';
import { withTranslation } from '../../i18n';
const Signup = ({ t }: { t: TFunction; i18n: I18n }) => {
  return (
    <div>{t('accept-terms')}</div>
  );
}
Signup.getInitialProps = async () => ({ namespacesRequired: ['signup', 'common'] });
export default withTranslation(['signup', 'common'])(Signup);
```

I also tried this as an alternative (I tried both with and without passing `i18n={i18n}` to the `Trans` component:
```jsx
import { I18n } from 'next-i18next';
import { withTranslation, Trans } from '../../i18n';
const Signup = ({ i18n }: { i18n: I18n }) => {
  return (
    <div>
      <Trans i18n={i18n} i18nKey="accept-terms" />
    </div>
  );
}
Signup.getInitialProps = async () => ({ namespacesRequired: ['signup', 'common'] });
export default withTranslation(['signup', 'common'])(Signup);
```

## Expected behaviour
In all cases, it outputted: `accept-terms` onto the screen rather than `By clicking below to create your account, you are agreeing to our <a href=\"agreement\" target=\"_blank\">Terms of Service</a>`.

## OS (please complete the following information)
 - Device: MacBook Pro (16-inch, 2019)
 - Browser: Brave Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (x86_64)

**Comment by isaachinman** [comment]
`next-i18next` uses i18next packages under the hood to handle actual translation/interpolation/etc. This sounds like an issue with an upstream package – please have a look at the i18next docs. Good luck!
