### ISSUE TITLE
Netlify serverless

### ISSUE THREAD

**Issue by aboveyunhai** [isaachinman/next-i18next#870]
## Describe the bug
This seems like a bug from platform, at least not a bug from this package. But I saw many issues seem to relate to this and cannot get a solution around. After my personal deployment on both `Netlify` and `Vercal`.  I felt its good to share and let @isaachinman know, focus more on the real functionalities and take a rest from similar issues, and as a ref for other developers who try to do the same thing like me.

It seems like `Netlify` does not support `next.js` very well in terms of routing when there is not a server. 

So when we set up everything with multiple languages such as `[ "en", "cn" ]` (Assuming `en` is the default language)
You are able to change the `url` to something like `myapp.com/cn` through the `changeLanguage` function and continue browse the website with this `sublocale` prefix , but it will never generate a static page or route for this `url`.  

So what it means it's that when you try to directly access the `url` with the `myapp.com/cn` prefix on `Netlify` host without a sever, or even refresh from the current **”working“** `sublocale` pages, you will immediatly get a `404` status.

you can add `lng` to your `i18next.init()` to force the redirect back to default language without the `sublocale`, but of course it's not what we want.

However, the exactly project works fine on `Vercel` (of course it should be all good since next.js is made by Vercel ). 

## Steps to reproduce
Just deploy the basic example `next-i18next/examples/simple/` from this package on both platforms, then try to access the `sublocale` url.
`Vercel` handles everything perfectly as expect. But `Netlify` does not.

**Comment by isaachinman** [comment]
Although I have not attempted to deploy a `next-i18next` app on Netlify, I assume it's possible. Any platform that supports a NodeJs runtime should be able to run a NextJs app via `yarn build && yarn start`. However, all serverless platforms are indeed different, so there may be strange issues, as you describe.

If anyone in the future reading this has successfully deployed a `next-i18next` app on Netlify, please let us know!

**Comment by 90zlaya** [comment]
Has anyone succeeded deploying `Next.js` with `next-i18next` to `Netlify` in the past nine months?

I had small experiment. Simple landing page with button to toggle between two locales. I pushed this code to two branches: 

* **i18next** which uses `next-i18next`
* **no-i18next** which contains hardcoded text

Build script completed successfully for both branches on `Netlify`. **i18next** branch displays *Page not found* message, while **no-i18next** displays page properly. On `localhost` build script completed successfully and both branches are working as expected. 

I tried same thing on `Vercel` and succeeded within five minutes.

Now I understand why this is the case, but I wonder why nobody felt challenged to solve this issue. :raised_eyebrow:

**Comment by ismailinico** [comment]
I was having trouble deploying my next.js with next-i18next to netlify and it took me **2 full work days** to find [this solution](https://github.com/netlify/netlify-plugin-nextjs/issues/223#issuecomment-832977548) which fixes both building locale pages automatic locale redirects when deployed to netlify. 

So I thought I'd leave this comment here for people having the problem in the future. 

Hope it helps! <3
