### ISSUE TITLE
auto add localPath when user typing url and enter

### ISSUE THREAD

**Issue by ittroller** [isaachinman/next-i18next#875]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when I change language without localeSubpaths

## Describe the solution you'd like
When I change language by typing url and enter

## Describe alternatives you've considered
I change language by typing url and enter, please don't add localePath to url

## Additional context
I had url: http://localhost:3000/en/location/contact

and localeSubpaths is: en / jp

when i change 'en' to 'us' : http://localhost:3000/us/location/contact
and enter
url look like :    http://localhost:3000/en/us/location/contact
and return 404 page

I want url look like : http://localhost:3000/us/location/contact  and return 404 page

**Comment by isaachinman** [comment]
Not exactly sure what you're asking, but `us` is not a valid two letter ISO.
