### ISSUE TITLE
Nextjs-18next not working if I change language in url

### ISSUE THREAD

**Issue by anialamo** [isaachinman/next-i18next#876]
Hi! I have deployed in my localhost this project next-i18next-vercel and this working fine if I change manually my language in browser url bar  from "/" root (english) and "/de" (german). Also works fine if I use switcher buttons.
But when I deploy this to my server in AWS Cloudfront as a serverless component, also works fine if I change the language using switcher buttons but this returns "404 page not found" if I change from my default lang "english" "/" (root) to language "/de".
Some help please? What is wrong?
Regards,
Ani

**Comment by isaachinman** [comment]
Hi there, please post on StackOverflow or similar for help. Good luck!
