### ISSUE TITLE
Setting `serverLanguageDetection: false` and changing language on server does not include the new language in `initialI18nStore`

### ISSUE THREAD

**Issue by davidwgrossman** [isaachinman/next-i18next#878]
## Describe the bug
If a user sets `serverLanguageDetection` to `false` and changes the language using `i18n.changeLanguage('de')`, the new language is not included in `initialI18nStore`.

## Occurs in next-i18next version
7.0.1

## Steps to reproduce
This repository reproduces the issue: https://github.com/davidwgrossman/next-i18next/tree/minimalReproducibleExample
1. Clone the repo and run `yarn && yarn run-example`
2. Go to `view-source:http://localhost:3000/` in Chrome and check that `initialI18nStore` does not have the `de` language present. The client then must fetch the same language if the client is using the same pattern to opt out of language detection.

Note: Why does the page render in English, the `i18n.language === 'de'` check on render?

## Expected behaviour
When changing the language on server, the `initialI18nStore` should include the language in which the page is rendered when opting out of `serverLanguageDetection`. 

## Screenshots
The page is rendered in German, however `initialI18nStore` does in include German.

<img width="1644" alt="Screen Shot 2020-11-06 at 6 11 41 PM" src="https://user-images.githubusercontent.com/1361444/98395543-b4f57f80-205c-11eb-9177-431548f7e4d4.png">
<img width="1677" alt="Screen Shot 2020-11-06 at 6 11 20 PM" src="https://user-images.githubusercontent.com/1361444/98395723-f5ed9400-205c-11eb-9ac2-55aefd567c2c.png">

## Additional context
In `next-i18next-middleware.ts`:
```
  if (!config.serverLanguageDetection) {
    middleware.push((req: NextI18NextRequest, _res: Response, next: NextFunction) => {
      if (isI18nRoute(req)) {
        req.lng = config.defaultLanguage
      }
      next()
    })
  }
```
This language is then used to populate `initialI18nStore` in [Steps 1 through 3](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L104-L192).

One approach I have tried to support this flow is to add an `i18nOverrideLanguage` to `getInitialProps`. This approach also provides a better interface for opting out of `i18next`'s language detection strategies. If this is an approach that you would consider, I would be happy to put up a PR :). [Here's the change.](https://github.com/isaachinman/next-i18next/compare/master...davidwgrossman:aFix#diff-f6e0e9460e8d5bfdf4e86b0c3fcf4063a471c86c52e1518831e6c94157eae6fe)

**Comment by isaachinman** [comment]
What's your reasoning for setting `serverLanguageDetection: false`?

**Comment by davidwgrossman** [comment]
I was able to find a way around setting `serverLanguageDetection: false` so I didn't have an issue in the end. I didn't want to use express middleware to handle language detection, however I ended up using `customDetectors` in the end. Possibly some documentation on how to set up a custom detector could be useful. Would you consider a PR with an example custom detector?

It does seem to be that there are some rough edges with `serverLanguageDetection: false`. Is that the case?

**Comment by davidwgrossman** [comment]
I would note that I could not follow the example from the `i18next` documentation [here](https://www.i18next.com/misc/creating-own-plugins#languagedetector).
They suggest creating an Object with this format:
```javascript
{
  type: 'languageDetector',
  async: true, // If this is set to true, your detect function receives a callback function that you should call with your language, useful to retrieve your language stored in AsyncStorage for example
  init: function(services, detectorOptions, i18nextOptions) {
    /* use services and options */
  },
  detect: function(callback) { // You'll receive a callback if you passed async true
    /* return detected language */
    // callback('de'); if you used the async flag
    return 'de';
  },
  cacheUserLanguage: function(lng) {
    /* cache language */
  }
}
```

Instead, I needed to use the following language detector:
```
const detector = {
  name: 'always-serve-german',
  lookup: (req, res, options) => {
    // You can add anything here (import custom files, etc.)
    return 'de';
  },
  // This method is optional
  cacheUserLanguage: (lng, options) => {
    // options -> are passed in options
    // lng -> current language, will be called after init and on changeLanguage

    // store it
  }
};
``` 
and configure it like in this example:
https://github.com/davidwgrossman/next-i18next/blob/master/examples/simple/i18n.js#L6-L31

**Comment by isaachinman** [comment]
> It does seem to be that there are some rough edges with serverLanguageDetection: false. Is that the case?

Yes, of course. We use server side detection to both do initial language detection based on headers, and also do synchronisation for subsequent requests based on a cookie value.

I don't understand – if you always want to serve German, why do you need localisation in the first place?

I am going to mark this as closed because it seems like you can achieve what you need just via i18next configuration options, but let me know if you feel there is something more to be done here.
