### ISSUE TITLE
App reload require when adding new translation files

### ISSUE THREAD

**Issue by underfisk** [isaachinman/next-i18next#881]
## Describe the bug
I find it strange that i need to restart the app in order for i18next to load the new files or new fields within the existing files, that is quite hard to be doing and I think this is not supposed to happen

## Occurs in next-i18next version
You must provide the npm module version, git tag, or even better the explict commit causing the issue.
Latest version

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.
Simply use the official documentation example, I even tested with that and happens the same, I need to close the app and open again in order for the files to be resolved

## Expected behaviour
Maybe not having to reload the app and next18n be able to load from fs while in development mode

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by isaachinman** [comment]
There have been several previous issues in regards to this, eg #796. This is easy to achieve with `nodemon`.

**Comment by kachkaev** [comment]
I'd be interesting to consider this as part of #869 TBH. Imagine `<NextI18nextProvider>` polling some dev-only API endpoint and updating the translation data without page reload, when it changes. The API endpoint, in turn, just tracks for the file changes.

**Comment by underfisk** [comment]
@kachkaev Indeed, but behind the scenes, it only needs to listen to the given fs path, and in case the file differs, it invokes the reloading and this could also be provided as a prop to the Provider in order to allow the usage of fs watcher
As you can imagine this can be "annoying" when you are adding translations and instead of waiting for the app hot-reload, you have to reload the whole app (and in large apps, this takes up some minutes to boot)

**Comment by riywo** [comment]
This discussion seems insightful. https://github.com/vercel/next.js/discussions/11419

**Comment by riywo** [comment]
I got a pretty simple solution. I just added a few tricks on my page component only for `next dev`: 1. Add `i18n.reloadResources()` to `getStaticProps`, 2. Add timer to the client to reload the page component periodically.

```ts
import { GetStaticProps } from "next";
import { i18n } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/dist/client/router";
import { useEffect } from "react";
import Home from "../components/home";

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  if (process.env.NODE_ENV === "development") {
    await i18n?.reloadResources();
  }
  return {
    props: {
      ...(await serverSideTranslations(locale!, ["common"])),
    },
  };
};

const Index = () => {
  if (process.env.NODE_ENV === "development") {
    const router = useRouter();
    useEffect(() => {
      const timer = setInterval(() => {
        router.replace(router.asPath);
      }, 5000);
      return () => clearTimeout(timer);
    });
  }
  return <Home />;
};

export default Index;
```

With this code, the client application try to reload the page component every 5 seconds but most of the time it's almost noop because the prop is the same. When the translation files are updated, the prop returns different content so that React just re-render the components required to update. This is much faster than full app reload like `nodemon` or full page reload like `next-remote-watch`.

**Comment by dcporter44** [comment]
@isaachinman It seems that calling `i18n.reloadResources` in `getStaticProps` successfully solves the issue of not seeing translation updates on page refresh. Which leads me to wonder what if `i18n.reloadResources` was called in `serversideTranslations`? Given that `serverSideTranslations` is only called in `getStaticProps`, it really wouldn't affect app performance. 

Perhaps during development on larger projects, calling `reloadResources` may slow loading each page. But I think for the majority of developers, it would be better. I really wouldn't see harm in adding this functionality to `serverSideTranslations`, perhaps as optional via a config option.

**Comment by isaachinman** [comment]
The `serverSideTranslations` function can be called both in `getStaticProps` and `getServerSideProps`.

A config option may be OK, if the logic is simple enough. Feel free to have a go at it if you want, and I can review the PR.
