### ISSUE TITLE
How to implement localization for static site generated (SSG) pages?

### ISSUE THREAD

**Issue by afzaalahmad** [isaachinman/next-i18next#882]
I have implemented next-i18next in our next app and it is working absolutely fine for pages, that are being server rendered but it is not working for static site generation (SSG) pages. For SSG pages, app is stuck at loading the route and never fetches the page. So, I have following questions:

1. Can I achieve localization for SSG pages or not?
2. If yes, can you elaborate through some example? Because there is no SSG page in current example.

**Comment by isaachinman** [comment]
Please search previous issues before opening a new one. See #586 and #869.
