### ISSUE TITLE
Always EN Text is shown

### ISSUE THREAD

**Issue by tahaygun** [isaachinman/next-i18next#883]
## Describe the bug
I have an example project here: https://github.com/tahaygun/nextjs-i18n-example

It is really simple app, I copied everything from docs, but somehow it doesn't work as expected. 

It works only in English mode, even though the default language is set to NL, I still get the EN version of the text.

## Occurs in next-i18next version
7.0.1
## Steps to reproduce
Run the app briefly.

## Expected behaviour
It should show the NL text instead of EN.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: Chrome

**Comment by isaachinman** [comment]
You don't have any locale subpaths, and most likely your browser language is set to English.

**Comment by tahaygun** [comment]
> You don't have any locale subpaths, and most likely your browser language is set to English.

- First of all, I have browserLanguageDetection flag.
https://github.com/tahaygun/nextjs-i18n-example/blob/618fd5164d76aeb51dd1ec37d9ecc50a64519d1f/i18n.js#L8

Secondly,  I have added the localesubpathes, it still doesn't work. I am forcing it to go `/nl` but I am ending up in `/en/nl` which is 404.

@isaachinman 


https://github.com/tahaygun/nextjs-i18n-example/tree/test

**Comment by tahaygun** [comment]
Alright, adding localesubpath for EN solved my issue. Thanks :)

**Comment by isaachinman** [comment]
I've cloned your project and cannot reproduce that error. Please post on StackOverflow. Good luck!

**Comment by tahaygun** [comment]
Oops, no. I still en up in `/en` somehow 😞
