### ISSUE TITLE
localeSubPath with trailingSlash throws a 404

### ISSUE THREAD

**Issue by ynaveed** [isaachinman/next-i18next#884]
## Describe the bug
Define localeSubpaths and set the `trailingSlash` to `true` in next.config.js. Then the server-side routing only works for index route. It breaks for every other route. If you navigate from index to any other route, it works through the router but refreshing the page will throw a 404.
## Occurs in next-i18next version
Happens in v6.0 and above
## Steps to reproduce
It can be reproduced in the example/simple project.  Use the following as `next.config.js`
```
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const localeSubpaths = {
  'de': 'german',
  'en': 'english'
};
module.exports = {
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
  trailingSlash: true
}
```

Navigate to `localhost:3000/english/`. It works fine. Try navigating to `second-page`, it also works fine.

Try refreshing the page or going directly to `localhost:3000/english/second-page/` throws a 404.

Set `trailingSlash` to `false` in `next.config.js` and everything works as expected.

## Expected behaviour
Routing should work with or without trailingSlash.

## OS (please complete the following information)
 - Device: [ MBP 2019 15"]
 - Browser: [All browsers]

**Comment by isaachinman** [comment]
Actually, `next-i18next` already enforces trailing slashes, and has done so long before NextJs offered it as a config option. This conflict here will be handled in #869.

**Comment by eminx** [comment]
I don't know if the beta branch in #869 could, as of now, fix this issue? 
I'd be very pleased if someone could point to me how. I have exactly the same problem as @ynaveed .
Thanks!
