### ISSUE TITLE
appWithTranslation in _app.ts cause vercel deployment error

### ISSUE THREAD

**Issue by goffxnca** [isaachinman/next-i18next#885]
![image](https://user-images.githubusercontent.com/71051032/99254876-a3bf2680-2845-11eb-8f7d-5e0d4d28d126.png)
![image](https://user-images.githubusercontent.com/71051032/99255240-39f34c80-2846-11eb-89fa-a1aeab87d153.png)

This is code in _app.tsx
```
import App, { AppProps } from "next/app";
import "../styles/index.css";
import Layout from "../components/Layout";
import { appWithTranslation } from "../i18n";

const CustomApp = ({ Component, pageProps }: AppProps) => {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );
};
export default appWithTranslation(CustomApp)
```

only one last line of code by wrapping App with appWithTranslation HOC cause vercel deployment error any help?

**The translation running locally is working fine, yarn build > yarn start also working fine, only not working on Vercel

**Comment by sonsor** [comment]
try like this
```
import App, { AppProps } from "next/app";
import "../styles/index.css";
import Layout from "../components/Layout";
import { appWithTranslation } from "../i18n";

const CustomApp = ({ Component, pageProps }: AppProps) => {
    const LayoutWithTranslation = appWithTranslation(Layout)
  return (
    <LayoutWithTranslation>
      <Component {...pageProps} />
    </LayoutWithTranslation>
  );
};
export default CustomApp

```

**Comment by goffxnca** [comment]
Thanks, @sonsor I have tried with your code, still get the same error, same log on Vercel

**Comment by isaachinman** [comment]
If you believe you have found a bug in the `next-i18next` package, please provide a repro via a repository. For help, please post on StackOverflow.

**Comment by goffxnca** [comment]
> If you believe you have found a bug in the `next-i18next` package, please provide a repro via a repository. For help, please post on StackOverflow.

I am not really sure if this is a next-i18next bug or not, from what I have read other similar issues, seem like it's the limitation of the libs not a bugs and still waiting the implementation to support getServersideProps.

**Comment by goffxnca** [comment]
Alright, this is proved as not next-i18next bugs, I forget to add  publicRuntimeConfig: {localeSubpaths} in next.config thanks for all people involved here.
