### ISSUE TITLE
storybook-nextI18NextInternals.config.localeSubpaths-undefined

### ISSUE THREAD

**Issue by hxxiaolong** [isaachinman/next-i18next#886]
## Describe the bug
I want to use storybook in next-i18next，but，when use to the Link component, storybook reported an error
```js
console:
'nextI18NextInternals.config.localeSubpaths` is marked as required in `Link`, but its value is `undefined'
at subpathIsRequired (subpath-is-required.js:9)

subpath-is-required.js inner code

var subpathIsRequired = function subpathIsRequired(config, language) {
  return typeof config.localeSubpaths[language] === 'string';
};

error:Uncaught TypeError: Cannot read property 'tw' of undefined
```

storybook may not be able to start the server, how compatible with this error

## Occurs in next-i18next version
"6.0.3

**Comment by isaachinman** [comment]
Hi there, I have just released `next-i18next@8.0.0`, which uses the internationalised routing built into NextJs v10+. This new version of `next-i18next` is quite different, thus making this PR no longer relevant. Thanks!
