### ISSUE TITLE
Update default Language to a specific page with "no change effect"

### ISSUE THREAD

**Issue by anialamo** [isaachinman/next-i18next#888]
Hi! Is it possible to change default language for a specific page? I ask this because now I use i18n.changeLanguage in page Y (e.g. I changed to "spanish" when my default language is "english" but I see an ugly effect during 1 second while languages are changing, first I see the page in english and in the next second I see the page in spanish. Or maybe for this page I shouldn't use translations? (I think aloud because it's a Landing)
Thanks!

**Comment by isaachinman** [comment]
No, that's not a feature that is supported, and most likely will not be. I encourage you to take a look at NextJs v10, and see the direction that the Vercel team are pushing for.
