### ISSUE TITLE
Unable to use withTranslation with FC that already take other props

### ISSUE THREAD

**Issue by prabu-ssb** [isaachinman/next-i18next#889]
## Describe the bug
Typescript reports incompatible FC-signature when using withTranslation with an FC that already takes other props.

## Occurs in next-i18next version
next-i18next : v6.0.3
i18next: v19.8.2

## Steps to reproduce
```javascript
// components/MyComp.tsx
const MyComp = ({ t, myProp }) => {
   ...
};

export default withTranslation('mybundle')(MyComp);
```

Typescript reports --

```
Type '{ myProp: any[]; }' is not assignable to type 
    'IntrinsicAttributes & Pick<WithTranslation, never> & WithTranslationProps & { children?: ReactNode; }'.   
    Property 'myProp' does not exist on type 
      'IntrinsicAttributes & Pick<WithTranslation, never> & WithTranslationProps & { children?: ReactNode; }'.
```

## Expected behaviour
Accept FC with other props; examples.

**Comment by isaachinman** [comment]
Please check the `react-i18next` TypeScript documentation. Good luck!
