### ISSUE TITLE
Passing href as object in Link causing wrong navigation when enable Locale subpaths

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#89]
When enable Locale subpaths and passing href as object in Link like below
```
<Link href={{ pathname: '/foo', query: { bar: '123' } }} passHref>
   ...
</Link>
```
When we are on default language path like `http://localhost:3000/`. It will correctly navigate to `http://localhost:3000/foo?bar=123`

But when we are on the other language path like `http://localhost:3000/fr/`. It will navigate to wrong path like `http://localhost:3000/fr/fr[object%20Object]`

**Comment by isaachinman** [comment]
Good catch. Any chance you want to submit a bug fix and test coverage for this?

**Comment by capellini** [comment]
@vimutti77 @isaachinman I hope you don't mind, but I was also effected by this, so I took the liberty of submitting PR #95.
