### ISSUE TITLE
Change language in link page using Link component

### ISSUE THREAD

**Issue by MichalKalita** [isaachinman/next-i18next#890]
## Is your feature request related to a problem? Please describe.
I want to create a link to other language. Because of seo I have to create real links. I cannot just i18n.changeLanguage()

## Describe the solution you'd like
```
<Link href="/page" as="/cs/page" locale="cs">whatever...</Link>
```
Locale is next js parameter to change language, so it will be api compatible.

## Additional context
Link with `as` links to other language is now not possible, because language in url is rewriten every time. It must be fixed.

The change of url not change i18next language, so in link must be `onClick` action to call `changeLanguage`.

**Comment by isaachinman** [comment]
Please check Next v10 and the new i18n features it offers. What are you proposing here would be covered by #869.
