### ISSUE TITLE
Translation outside React Component 

### ISSUE THREAD

**Issue by eman-b** [isaachinman/next-i18next#891]
**Is your feature request related to a problem?**
I want to use translation outside React components, inside utils functions and sagas. But, it doesn't seem to work.

 **Describe the solution you'd like**
It would be helpful if we can use "t" outisde components

 **Describe alternatives you've considered**
I tried to use what people do with i18next, but nothing worked. 

 **Additional context**
Thank you for your support guys!

**Comment by kachkaev** [comment]
You can pass `t` or `i18n` into your function as an arg. That would be a safe and a straightforward way of solving this problem.
