### ISSUE TITLE
Preserve cookie value and give priority to it.

### ISSUE THREAD

**Issue by ktjd123** [isaachinman/next-i18next#893]
## Is your feature request related to a problem? Please describe.
When user changes language, I try to save it to next-i18next. but when user refreshes the cookie is overwritten to other language

## Describe the solution you'd like
give priority to previously saved cookie.

Thank you.

**Comment by isaachinman** [comment]
Priority is given to the route above all else – if you want to switch a user's language, please follow the example. Good luck!
