### ISSUE TITLE
next-i18next Warning: Text content did not match. Server: "..." Client: "..."

### ISSUE THREAD

**Issue by danny-dang** [isaachinman/next-i18next#895]
## Describe the bug
Warning: Text content did not match. Server: "HOME" Client: "home"
![image](https://user-images.githubusercontent.com/47047158/101133072-a8078400-363a-11eb-8101-2b18685228a6.png)

## Occurs in next-i18next version
Version: 
"next-i18next": "^7.0.1",
npm v6.13.7

## Screenshots
Where I get the error: `.../Navbar.js`
```javascript
...
import { withTranslation, Link } from 'i18n'
....
const Navbar = (props) => {
  const { t } = props
  const router = useRouter()
  return (
    ...
          <Nav.Item >
            <Link href="/">
              <Nav.Link href="/" className={`nav-item__link ${router.pathname === '/' ? 'active' : ''}`}>
                <div>{t('home')}</div>
              </Nav.Link>
            </Link>
          </Nav.Item>
...
  )
}
export default withTranslation('navbar')(Navbar)
```
`/public/locales/en/navbar.json`:
```json
{
  "home": "HOME",
  "opportunities": {
    "base": "OPPORTUNITIES",
    "real-estate": "REAL ESTATE",
    "vehicles": "VEHICLES",
    "job-search": "JOB SEARCH",
    "personal-company": "PERSONAL COMPANY",
    "invest": "INVEST IN IDEA"
  },
  "help": "HELP & SUPPORT",
  "sign-in": "SIGN IN",
  "register": "REGISTER",
  "add-listing": "ADD LISTING"
}
```

`next.config.js`:
```javascript
const withSass = require('@zeit/next-sass')
const withCSS = require('@zeit/next-css')
const withImages = require('next-images')
const path = require('path')
const { nextI18NextRewrites } = require('next-i18next/rewrites')

module.exports =
  withCSS(
    withSass(
      withImages({
        env: {
          API_ENDPOINT: process.env.API_ENDPOINT,
          API_SUFFIX: process.env.API_SUFFIX,
        },
        rewrites: async () => nextI18NextRewrites({
          de: 'de',
          fr: 'fr',
        }),
        webpack: config => {
          config.resolve.alias['components'] = path.join(__dirname, 'components')
          config.resolve.alias['public'] = path.join(__dirname, 'public')

          return config
        }
      }
      )))
```

`i18n.js`:
```javascript
const NextI18Next = require('next-i18next').default
const path = require('path')
module.exports = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['de', 'fr'],
  localeSubpaths: {
    de: 'de',
    fr: 'fr',
  },
  localePath: path.resolve('./public/static/locales')
})
```
## OS
 - Device: Windows
 - Browser: .Chrome  87.0.4280.88

**Comment by isaachinman** [comment]
You say your asset is in `/public/locales/en/navbar.json`, but you also have `localePath: path.resolve('./public/static/locales')`. You need to add the `static dir`, or change your `localePath`. Good luck!

**Comment by danny-dang** [comment]
> You say your asset is in `/public/locales/en/navbar.json`, but you also have `localePath: path.resolve('./public/static/locales')`. You need to add the `static dir`, or change your `localePath`. Good luck!

I have just checked, my asset is actually in `public/static/locales/en/navbar.json`
![image](https://user-images.githubusercontent.com/47047158/101152152-40126700-3655-11eb-84f0-ca7987e0e26e.png)

**Comment by isaachinman** [comment]
Then can you please provide a reproducible repo?

**Comment by danny-dang** [comment]
Here's my repo: https://github.com/danny-dang/placifull-test

**Comment by danny-dang** [comment]
I were able to reproduce the issue and fixed it.
I render the `Navbar` inside `pages/_app.js` like this, so that every page I go, I will have this Navbar and I don't have to render it in every page:

```javascript
....
function App({ Component, pageProps }) {
  const store = useStore(pageProps.initialReduxState)
  return (
    <Provider store={store}>
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </Provider>
  )
}
....
```

What I was missing: I did not include `navbar` namespace in `namespacesRequired`.
So I'll have to include the `navbar` in every single file in folder `/pages` like this:
```javascript
Home.getInitialProps = async () => ({
  namespacesRequired: ['common', 'home', 'navbar', 'footer'],
})

Home.propTypes = {
  t: PropTypes.func.isRequired,
}

export default withTranslation('home')(Home)
```
