### ISSUE TITLE
How to load correct lang at first

### ISSUE THREAD

**Issue by cCastaing** [isaachinman/next-i18next#897]
Hi,
Thanks for this plugin. But I can't find an answer to load the good language at first with a session parameter.
I get my session info in my <html> tag and initialize everything this way in JS :
```
i18next.use(window.i18nextXHRBackend).init({
            lng:$('html').attr("lang"),
            fallbackLng: $('html').attr("lang"),
            debug: true,
            backend: {loadPath: "assets/locales/{{lng}}/{{ns}}.json"},
            returnObjects: true,
        }, function (err, t) {
            jqueryI18next.init(i18next, $)
        });
```
The debug give me this infos in my console :
![image](https://user-images.githubusercontent.com/75615883/101344118-48e97f80-3885-11eb-808d-0a08e83f64dd.png)
with my session set to 'es'.
SO it seems to find and detect that I want es translation but everything in my page stay in french. Any idea why?
Thanks in adavance for your help,
Best regards,
Cécile.

**Comment by isaachinman** [comment]
Hi @cCastaing – not sure why you are calling `i18next.use` yourself, that behaviour is not supported. I recommend you read through the i18next documentation. Good luck!
