### ISSUE TITLE
Cannot use props with components using translations

### ISSUE THREAD

**Issue by martonlederer** [isaachinman/next-i18next#898]
## Describe the bug
Using custom props next to the translation function `t()` throws an error with typescript. 

## Occurs in next-i18next version
`7.0.1`

## Steps to reproduce
Create a component with custom props
```ts
function Nav({ propName, t }) {
   ...
}
export default withTranslation('nav')(Nav)
```
Use it in another component:
```ts
<Nav propName="test" />
```

## Expected behaviour
No errors on compile.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/30638105/101347089-d16a1f00-3889-11eb-8c56-c231513ded05.png)
![image](https://user-images.githubusercontent.com/30638105/101348266-a7196100-388b-11eb-8d83-e9cd009236fe.png)

**Comment by Poitrin** [comment]
Yes, I had the same problem.

In https://github.com/isaachinman/next-i18next/issues/647#issuecomment-596451214, one developer switched to Hooks instead, which are also used [in Next.js' react-i18next sample app](https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/no-namespaces/src/App.tsx).

Therefore, one way is to do it like this:

```ts
export const nextI18Next = new NextI18Next({ … });
export const useTranslation = nextI18Next.useTranslation;
```

… and then …

```ts
import { useTranslation } from 'config/i18next';

const MyComponent = () => {
  const { t } = useTranslation();

  …
```

I have no idea if this is the best solution, but it feels like it is the solution
- that needs the least code
- and that fits well into this React Hooks mentality.

**Comment by isaachinman** [comment]
This is a problem that is not specific to `next-i18next`, but HOCs in TypeScript in general. Using hooks avoids this issue, but otherwise you'll need to have a look at how to type HOCs in TS. Good luck!
