### ISSUE TITLE
Critical / breaking - appWithTranslation export not found on next-i18next

### ISSUE THREAD

**Issue by MisterEmpyrean** [isaachinman/next-i18next#900]
## Describe the bug
Trying to migrate for Next 10, following all the steps of your docs and your example, but getting the same error in _app.tsx, both in my code and in your cloned example

## Occurs in next-i18next version
"next": "^10.0.0",
"next-i18next": "^7.0.1",

## Steps to reproduce
// _app.tsx
```typescript
import { appWithTranslation } from "next-i18next";
import { Provider } from "react-redux";
import { withApollo } from "../helpers/utils/withApollo";

const MyApp = ({ Component, pageProps }: any) => {
    return (
        <Provider store={store}>
            <ThemeProvider theme={theme}>
                {/* <ColorModeProvider> */}
                <GlobalStyle />
                <CSSReset />
                <Notifications />
                <Chrome>
                    <Component {...pageProps} />
                </Chrome>
                {/* </ColorModeProvider> */}
            </ThemeProvider>
        </Provider>
    );
};

MyApp.getInitialProps = async (
    appContext: AppContextType<Router>,
) => {
    const appProps: AppInitialProps = await App.getInitialProps(
        appContext,
    );
    return {
        ...appProps,
        namespacesRequired: ["common"],
    };
};

export default withApollo({ ssr: true })(
    appWithTranslation(MyApp),
);
```
// next.config.js
```typescript
const withSass = require("@zeit/next-sass");

module.exports = withSass({
    i18n: {
        defaultLocale: "en",
        locales: ["en", "de"],
    },
    cssModules: false,
    webpack(config) {
        config.module.rules.push({
            test: /\.svg$/,
            issuer: {
                test: /\.(js|ts)x?$/,
            },
            use: ["@svgr/webpack"],
        });

        return config;
    },
});
```

// next-i18next.config.js
```typescript
const path = require("path");

module.exports = {
    defaultLanguage: "en",
    otherLanguages: ["el"],
    localePath: path.resolve("./public/static/locales"),
};
```

## Expected behaviour
Can wrap component with existing `appWithTranslation` import

## Screenshots
![image](https://user-images.githubusercontent.com/17225794/102558472-66a8b700-40c5-11eb-9ac2-26717e8886e7.png)

## OS (please complete the following information)
 - Device: MBP (Retina, 13", early 2015)
 - Browser: Version 87.0.4280.88 (Official Build) (x86_64)

## Additional context
Same issue on https://github.com/isaachinman/next-i18next/tree/next-v10/examples/simple

**Comment by isaachinman** [comment]
#869

**Comment by MisterEmpyrean** [comment]
@isaachinman Hi there. So I should discontinue next-i18next from my repertiore then and just use Next's routing?

**Comment by isaachinman** [comment]
Hey @MisterEmpyrean. We are working to support NextJs v10 in the issue I linked to. The routing provided by NextJs v10 is not a complete solution. You will need some sort of third party package to solve the other half of the localisation problem. Good luck!
