### ISSUE TITLE
Deep Key support

### ISSUE THREAD

**Issue by Toumani** [isaachinman/next-i18next#902]
I can't figure out why deep key doesn't work.
Let's say I have `{ button: { save: "Save" } }` in my locale file `en.json`, I would like to access it by doing `t('button.save')`.
I tried solutions like adding `keySeparator` to the config file but it doesn't work. In fact, adding nested object make the whole file fail the translation.
I'm sure I'm not the only one facing this issue but it looks like a missing feature. Am I missing something ?

**Comment by isaachinman** [comment]
This is an i18next issue, as `next-i18next` doesn't handle any low-level API details like that. Good luck!

**Comment by tomevans18** [comment]
I don't believe this is due to `i18next`, I feel there is an issue somewhere in `next-i18next` that is causing this.

When a deep key is added the entire JSON is effectively discarded client side.
I've been through the `next-i18next` code/config and I can't work out whats causing the issue.

The same setup when using `react-i18next` seems to work based on their examples.

@isaachinman do you have a working example of `next-i18next` with deep keys?

I have forked the `next-i18next` repo and added a deep key example:
https://github.com/tomevans18/next-i18next/tree/master/examples/deep%20key%20example

**Comment by isaachinman** [comment]
@tomevans18 What unexpected behaviour are you experiencing?

**Comment by tomevans18** [comment]
The translations are picked up client side when there is a deep key within the JSON.

So when translating between languages nothing happens.

It seems like having any nested values breaks the setup.

**Comment by tomevans18** [comment]
https://www.loom.com/share/b9c6676591f44f09865083b6f5388d2b

**Comment by isaachinman** [comment]
Not sure how that could possibly be related to `next-i18next`, as it seems the component is failing to rerender, and the `useTranslation` hook comes from `react-i18next` directly.

**Comment by isaachinman** [comment]
@tomevans18 Can you see what happens if you play around with a `key` set to `locale`, similar to [here](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L65)?

**Comment by tomevans18** [comment]
> Not sure how that could possibly be related to `next-i18next`, as it seems the component is failing to rerender, and the `useTranslation` hook comes from `react-i18next` directly.

This is whats confusing me as `react-i18next` on its own works with this setup (there are lots of examples doing this), which is why I'm looking at `next-i18next` as the possible cause but I can't see what would cause this.


> @tomevans18 Can you see what happens if you play around with a `key` set to `locale`, similar to [here](https://github.com/isaachinman/next-i18next/blob/master/src/appWithTranslation.tsx#L65)?

I'm not sure I follow what you mean here

**Comment by isaachinman** [comment]
@tomevans18 Unfortunately I lost about 10 minutes on this one, until realising that [your JSON is invalid](https://github.com/tomevans18/next-i18next/blob/master/examples/deep%20key%20example/public/locales/de/common.json#L9). Perhaps you might want to request the upstream i18next packages emit a warning when encountering invalid JSON.

**Comment by tomevans18** [comment]
Damn, sorry. I can't believe it was down to a trailing common. Same issue in my main repo, at least its Friday!
