### ISSUE TITLE
Using getInitialProps

### ISSUE THREAD

**Issue by MSefer** [isaachinman/next-i18next#903]
## Is your feature request related to a problem? Please describe.
Next.js team recommend that you use getStaticProps or getServerSideProps instead of getInitialProps. But next-i18next library documentation says _app.js file use getInitialProps. And you need to return a namespacesRequired array via getInitialProps on your page-level component. Why we use getInitialProps?

## Describe the solution you'd like
Use getStaticProps or getServerSideProps instead of getInitialProps.

**Comment by kachkaev** [comment]
Hi @MSefer! Please see an ongoing discussion in #869

**Comment by MSefer** [comment]
Thank you! @kachkaev
