### ISSUE TITLE
Support passing in a query string for cache-busting

### ISSUE THREAD

**Issue by jackocnr** [isaachinman/next-i18next#906]
## Is your feature request related to a problem? Please describe.
AFAICS, currently there is no easy way to enable cache-busting when the client fetches translation files, which means when you deploy changes to your translation files, some users will continue using the stale cached version.

## Describe the solution you'd like
Support passing in a query string (e.g. '?v=123') so that we can cache-bust old translation files when they have changed. Seems to be the simplest way to support this feature - avoids having to rename all of the translation files to include the hash, and then have to handle that in the routing.

## Describe alternatives you've considered

- https://github.com/isaachinman/next-i18next/issues/265#issuecomment-481843999 shows a way to add the hash to the filename, but that requires renaming all of the translation files.
- I also tried adding the query string to localeStructure e.g. `localeStructure: '{{lng}}/{{ns}}?v=123'` - this seemed to build ok, but the query part was not included when the client requested the file.

**Comment by isaachinman** [comment]
This issue should be raised in the appropriate upstream i18next package, as http fetching is not something `next-i18next` actually handles. Most likely you should have a look at [i18next-http-backend](https://github.com/i18next/i18next-http-backend). Good luck!
