### ISSUE TITLE
Can JSX be used within the value of a translation

### ISSUE THREAD

**Issue by pmaier983** [isaachinman/next-i18next#909]
I'm working to convert a documentation site built in Gatsby to nextjs. Of the available options next-i18next is clearly the best. 

The current gatsby site uses a massive tsx file that housed all the translations while also having a bunch of biz logic written as jsx within. (<bold>; <button/> etc.).

Is my only option to convert this massive tsx file into json & use Interpolation (https://www.i18next.com/translation-function/interpolation) or can I use `localeExtension = "tsx"` and have translations interspersed with jsx? 

I read this issue: https://github.com/isaachinman/next-i18next/issues/548. Which seems to say that only json will work, but the amount the work I'm up against is too daunting not to ask. 

Thank you for taking the time to read this
As this is not really a feature request (I'm not sure how possible this is) I will close this issue when the questions is answered!

**Comment by isaachinman** [comment]
Hi @pmaier983 – any functionality you are describing would be a question to ask within the i18next repo, as `next-i18next` does not actually handle any of that core functionality. Good luck!
