### ISSUE TITLE
Support multiple subpaths for same language

### ISSUE THREAD

**Issue by yusufkinatas** [isaachinman/next-i18next#910]
## Is your feature request related to a problem? Please describe.
I need to combine achieving the url structure below and using `localeSubpaths` support
I have three restaurants, 

- Restaurant A -> targets English customers 
- Restaurant B -> targets both English and Spanish customers
- Restaurant C  -> targets Spanish customers

### What I'm trying to achieve
- https://mysite.com/restaurant-a/products  (locale /en, products for A)
- https://mysite.com/restaurant-b/products  (locale /en, products for B)
- https://mysite.com/restaurant-b-es/products  (locale /es, products for B)
- https://mysite.com/restaurant-c/products  (locale /es, products for C)

## Describe the solution you'd like
I think having an option to use same locale file for different custom subpaths like snippet below will be good.

```
const NextI18Next = require("next-i18next").default;
const path = require("path");

module.exports = new NextI18Next({
  otherLanguages: ["es"],
  defaultLanguage: "en",
  localeSubpaths: {
    en: ["restaurant-a", "restaurant-b"],
    es: ["restaurant-b-es", "restaurant-c"],
  },
  localePath: path.resolve("./public/static/locales"),
});
```

## Describe alternatives you've considered
Maybe some way of doing the same thing above, but with using `nextI18NextRewrites`.

**Comment by isaachinman** [comment]
Please check #869. All routing functionality now belongs to the NextJs core.

**Comment by shakesBeardZ** [comment]
@yusufkinatas find any solution for your issue?

**Comment by yusufkinatas** [comment]
@shakesBeardZ Yes, I found a solution. Following code did the work for me.

```
const NextI18Next = require('next-i18next').default;
const path = require('path');

module.exports = new NextI18Next({
  otherLanguages: ['es', 'restaurant-a', 'restaurant-b', 'restaurant-b-es', 'restaurant-c'],
  defaultLanguage: 'en',
  localeSubpaths: {
    en: 'en',
    es: 'es',
    'restaurant-a': 'restaurant-a',
    'restaurant-b': 'restaurant-b',
    'restaurant-b-es': 'restaurant-b-es',
    'restaurant-c': 'restaurant-c',
  },
  fallbackLng: {
    'restaurant-a': ['en'],
    'restaurant-b': ['en'],
    'restaurant-b-es': ['es'],
    'restaurant-c': ['es'],
  },
  localePath: path.resolve('./public/static/locales'),
});
```

With this implementation, you can use any subpaths you want in your browser, even configure them using a backend. And you don't have to manipulate your locales folder in project. This is how my locales folder looks like
![image](https://user-images.githubusercontent.com/39553853/104799333-588ea900-57df-11eb-9ee6-2c3f2a8028ab.png)
