### ISSUE TITLE
Question Beta

### ISSUE THREAD

**Issue by chrys1110** [isaachinman/next-i18next#912]
I am currently setting up a new nextjs 10 project and would like to use next-i18next. Therefore using your current BETA.

The simple-example in the BETA branch doesn't work for me with several error messages.
After experimenting with setting localePath in a next-i18next.config.js
(otherwise it used "/public/static/locales" - which used C:/ as it's root folder - instead of "public/static/locales" - which then worked)

But now react-i18next says there aren't any languages defined. Currently only defined inside next.config.js ({ i18n: {locales: ['en-US', 'de'], defaultLocale: 'en-US') }}.

Not sure if a bug, since it's a beta I didn't want to bother you with a bug.

**Comment by chrys1110** [comment]
Just needed to put

  defaultLocale: "en",
  locales: ["en", "ae"],

inside the next-i18next.config.js

**Comment by isaachinman** [comment]
Can you confirm if you were deploying on Vercel?
