### ISSUE TITLE
Cannot read property 'includes' of undefined with babel-plugin-i18next-extract

### ISSUE THREAD

**Issue by haapti** [isaachinman/next-i18next#914]
## Describe the bug

I'm trying to get [babel-plugin-i18next-extract](https://github.com/gilbsgilbs/babel-plugin-i18next-extract) to work with i18next, but ending always up a type error `Cannot read property 'includes' of undefined` when starting the next dev environment. The error is most likely caused by [allLanguages being undefined](https://github.com/isaachinman/next-i18next/blob/master/src/utils/lng-from-req.ts#L16).

## Occurs in next-i18next version
I'm running next 10.0.3, i18next 7.0.1 and i18next-extract 0.8.2.

## Steps to reproduce

**.babelrc**
```
{
	"presets": ["next/babel"],
	"plugins": [
		["i18next-extract", { "outputPath": "public/static/locales/{{locale}}/common.missing.json" }]
	]
}
```

**i18n.js**
```
const NextI18Next = require('next-i18next').default;
const path = require('path');

const DEFAULT_LOCALE = 'en-GB';
const supportedLangs = ['en-GB', 'fi-FI', 'da-DK', 'no-NO', 'sv-SE'];

const domainLocaleMap = {
	'domain.co.uk': 'en-GB',
	'domain.fi': 'fi-FI',
	'domain.dk': 'da-DK',
	'domain.no': 'no-NO',
	'domain.se': 'sv-SE',
};

const domainDetector = {
	// We use the name to refer to it later when we want to tell i18next when to use it.
	name: 'domain',
	lookup(req, res, options) {
		let locale = DEFAULT_LOCALE;
		let host;
		// In the browser, get the hostname from window.location.
		if (typeof window !== 'undefined') {
			host = window.location.hostname;
		}
		// On the server, get the hostname from the request headers.
		// We use the host header which is available on IncomingMessage.
		// https://nodejs.org/api/http.html#http_class_http_incomingmessage
		// But the host header may include the port so first we take that off, if it exists.
		else {
			const hostname = req.headers.host?.split(':')[0];
			host = hostname;
		}

		Object.keys(domainLocaleMap).forEach((domain) => {
			if (host.indexOf(domain) !== -1) {
				locale = domainLocaleMap[domain];
			}
		});

		return locale;
	},
};

module.exports = new NextI18Next({
	defaultLanguage: DEFAULT_LOCALE,
	otherLanguages: supportedLangs,
	localePath: path.resolve('./public/static/locales'),
	customDetectors: [domainDetector],
	detection: {
		order: ['domain'],
	},
	saveMissing: false,
	keySeparator: false,
	debug: false,
});
```

## Expected behaviour
i18next-extract should extract the translations into given file.

## Additional context

**Error and call stack**
```
Server Error
TypeError: Cannot read property 'includes' of undefined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///var/www/node_modules/next-i18next/dist/commonjs/utils/lng-from-req.js (30:25)
Array.find
<anonymous>
lngFromReq
file:///var/www/node_modules/next-i18next/dist/commonjs/utils/lng-from-req.js (29:37)
<unknown>
file:///var/www/node_modules/next-i18next/dist/commonjs/middlewares/next-i18next-middleware.js (60:46)
<unknown>
file:///var/www/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js (249:38)
new Promise
<anonymous>
_loop$
file:///var/www/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js (248:36)
tryCatch
file:///var/www/node_modules/regenerator-runtime/runtime.js (63:40)
Generator.invoke [as _invoke]
```

**Comment by isaachinman** [comment]
Can you check #913?

**Comment by haapti** [comment]
> Can you check #913?

Tried this .babelrc but it has no effect for the original problem.

```
{
	"presets": ["next/babel"],
	"plugins": [
		[
			"i18next-extract",
			{
				"outputPath": "public/static/locales/{{locale}}/common.missing.json",
				"customUseTranslationHooks": [["next-i18next", "useTranslation"]]
			}
		]
	]
}
```

**Comment by ivnmood** [comment]
i have same issues

**Comment by ivnmood** [comment]
@isaachinman why does the library try to check for a language in the _req$i18n$options.allLanguages (path: node_modules/next-i18next/dist/commonjs/utils/lng-from-req.js) (screen 1), if _req$i18n$options does not have this property
![image](https://user-images.githubusercontent.com/62379919/107623197-061f9b80-6c6a-11eb-972a-2ba4b95d2624.png)
However, if you disable this plugin (screen 2), this object has this property and everything works fine. The problem is in the initialization of the language. If you add a plugin after compilation, the keys extract well.
![image](https://user-images.githubusercontent.com/62379919/107624019-4c292f00-6c6b-11eb-9050-c45901c9eab1.png)

**Comment by haapti** [comment]
> i have same issues. @haapti have you solved this problem?

i have not looked into this for a while. issue is not solved.

**Comment by isaachinman** [comment]
@haapti Can you let me know if this issue is still relevant in `next-i18next@8.0.0`?

**Comment by haapti** [comment]
> @haapti Can you let me know if this issue is still relevant in `next-i18next@8.0.0`?

with version 8.0.0 i get `TypeError: NextI18Next is not a constructor`

im using a domain detector for selecting the language, as i explained on initial message. the setup is done by this example https://github.com/justincy/nextjs-domain-locales/blob/master/src/i18n.js

**Comment by isaachinman** [comment]
@haapti That is correct, please check out the updated documentation. This package has changed a lot in the v8 release.

**Comment by isaachinman** [comment]
@haapti Do we need to keep this issue open?

**Comment by tursucu** [comment]
@isaachinman Can you give an example of how to use it.
I just want to use cookie and header detector.
