### ISSUE TITLE
Generic type 'TransProps<K, N, E>' requires between 1 and 3 type arguments.

### ISSUE THREAD

**Issue by tuankyo5696** [isaachinman/next-i18next#915]
## Describe the bug
It will get an error when import nextI18NextMiddleware from 'next-i18next/middleware' or import NextI18Next from 'next-i18next';

## Steps to reproduce
I18n.ts
`import NextI18Next from 'next-i18next';

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['hi']
})

export const { appWithTranslation, withTranslation } = NextI18NextInstance;

export default NextI18NextInstance;`

main.ts
`
import nextI18NextMiddleware from 'next-i18next/middleware';
import nextI18next from './i18n';
import { NestExpressApplication } from '@nestjs/platform-express';
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { join } from 'path';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  app.useStaticAssets(join(__dirname, '..' ,'client/public/static'));
  app.use(nextI18NextMiddleware(nextI18next));
  await app.listen(3000);
}
bootstrap();
`

## Screenshots
![image](https://user-images.githubusercontent.com/44392560/104989356-dacfd500-5a4c-11eb-81b6-61b545a12cb4.png)

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

**Comment by tuankyo5696** [comment]
I fixed it

**Comment by amelzer** [comment]
@tuankyo5696 Pleas tell us how

**Comment by abhijit945** [comment]
If anyone comes here looking for a replacement for `TransProps` then you can use `TFunction` instead
```
import { TFunction } from 'i18next';
```
