### ISSUE TITLE
About react-intl integration

### ISSUE THREAD

**Issue by chenrui333** [isaachinman/next-i18next#916]
👋  my org is using `react-intl` for the previous `react` applications, and now we are trying to experiment with nextjs application development (that is how we found this project for localization support).

Considering my organization experience of integrating with `react-intl`, we are curious if there is a way to use this project for routing capabilities (due to the fact we are still using react-16, we cannot use nextjs10 for now) while using `react-intl` to pull the translations.

Thanks!

**Comment by isaachinman** [comment]
Unfortunately no, `next-i18next` relies on the i18next ecosystem and doesn't support `react-intl`. Good luck!
