### ISSUE TITLE
Usage from api routes?

### ISSUE THREAD

**Issue by pgayvallet** [isaachinman/next-i18next#918]
Hello,

This seems like a basic need (well, at least imho), but I don't see any example of it, and looking at the code, it doesn't seem like this is supported, so I'm asking: 

Is it possible to use `next-i18next` from api routes? Is there an easy way to plug the middleware to inject the i18next instance to the `request` of a given API route?

If that's not the case, could I have some pointers on how to achieve that? Ideally, the locale would be deduced from the incoming request's `Referrer`, to avoid having per-locale prefix on the api routes.

**Comment by isaachinman** [comment]
Checkout #869 – the direction `next-i18next` is heading is to allow NextJs itself to [handle localised routing](https://nextjs.org/docs/advanced-features/i18n-routing). This request sounds very reasonable, and there may already be issues/discussions opened on the NextJs repo about it. Hope that helps!

**Comment by aequasi** [comment]
Even with the localised routing, how are we supposed to translate things in the API call? Importing i18n from 'next-i18next', i18n is always null on the first request (and will continue to be until a normal page is able to render)

**Comment by isaachinman** [comment]
> always null on the first request

Well, that'll depend on when the first request is, won't it?

There are properties on any i18n instance like `i18n.init` and `i18n.isInitialized`, which you could make use of.

Alternatively, `next-i18next` does create an `initPromise`, which currently isn't being exposed for the global i18n instance – that could be modified if desired.

**Comment by aequasi** [comment]
Its always null on the first request to the endpoint in question, assuming its the first endpoint to ever be hit on the nextjs app, because the global instance is never set, until a request is made to a page that uses app.tsx/app.jsx

`i18n` is *null*. there is no `i18n.init` or `i18n.isInitialized`

**Comment by isaachinman** [comment]
> i18n is null. there is no i18n.init or i18n.isInitialized

I understand that. A simple: `i18n?.isInitialized` would do.

> the global instance is never set, until a request is made to a page that uses app.tsx/app.jsx

Is your app primarily SSR or SSG?

And forgive me for lack of context, but is there any official communication from the NextJs/Vercel team about how they expect devs to localise API endpoints?

**Comment by aequasi** [comment]
Its not acceptable in our use case for it to be null though. The endpoint needs to always work. Long periods of time may pass without hitting an endpoint that uses app.

Its currently SSR, but I'm looking to move it towards ISR/SSG.

Im not sure. I'm not even sure who to ask anymore.

**Comment by isaachinman** [comment]
I understand, but I think we're talking past each other slightly. Even in the _best case_ scenario, an i18n instance will need to initialise on process boot, and your API endpoints may or may not receive requests before the i18n instance has initialised. This should be a very short-window race condition though, and should have nothing to do with view routes / React pages.

`next-i18next` could certainly provide a way to boot the global i18n instance manually/etc.

The main question the NextJs team needs to answer is: how do we determine current locale in NextJs API endpoints? Do we need to manually use accept-lang header logic, or will the framework provide this functionality?

Looks like there's a discussion here: https://github.com/vercel/next.js/discussions/21798

**Comment by aequasi** [comment]
> `next-i18next` could certainly provide a way to boot the global i18n instance manually/etc.

This would be the best option IMO. 

> This should be a very short-window race condition though, and should have nothing to do with view routes / React pages.

In our use case, this isn't true. Very likely going to be MANY API requests before a page request

**Comment by isaachinman** [comment]
@aequasi I think we misunderstood each other again. I am not suggesting it is appropriate to introduce a race condition between first API request and first HTML request. I am saying there will _always_ be a race condition between first API request and i18next initialisation, even for an API completely independent of NextJs.

> next-i18next could certainly provide a way to boot the global i18n instance manually/etc.

PRs welcome!

**Comment by Noitidart** [comment]
Hey @aequasi were you able to find out a solution on how to use in api routes. I don't use internationalized routing. I'm struggling with this as well.

**Comment by isaachinman** [comment]
@Noitidart The global `i18n` instance is created [here](https://github.com/isaachinman/next-i18next/blob/master/src/createClient/node.ts#L6) inside `createClient`, so if you're not using `serverSideTranslations`, that will never occur.

You could import the `createClient` function directly and use it yourself, hypothetically. If this use case is of interest to you, it would be great to open a PR to properly export this function in a first-class way.

**Comment by Noitidart** [comment]
> @Noitidart The global `i18n` instance is created [here](https://github.com/isaachinman/next-i18next/blob/master/src/createClient/node.ts#L6) inside `createClient`, so if you're not using `serverSideTranslations`, that will never occur.
> 
> You could import the `createClient` function directly and use it yourself, hypothetically. If this use case is of interest to you, it would be great to open a PR to properly export this function in a first-class way.

Thank you very very much @isaachinman - I did `i18n.createInstance` route! I think the direction I'm taking it is a different use-case though, so might be a different library. It's not internationalized routing, but just respecting the accept-language or preselected cookie. To each request, I want to attach it's own `i18n` instance. And each frontend page should get the i18n language from there.

I'm still trying to work out how to do this in a clean way, lots of things broken, but thanks for sharing that, it really got me on a track that works for my usecase!

**Comment by sagargulati** [comment]
Any example for using `useTranslation` on /api/ route endpoints with Next.js?

I tried `import { i18n } from 'next-i18next';`

but `i18n?.init()` always returns `null`

**Comment by jackhkmatthews** [comment]
I also needed an i18n instance on some API routes which generate email markup.

I opted for this:

`src/utils/api-i18n.ts`
```ts
import { createConfig } from "next-i18next/dist/commonjs/config/createConfig";
import * as createClient from "next-i18next/dist/commonjs/createClient/node";

import nextI18nextConfig from "@/../next-i18next.config";

const config = createConfig({ ...nextI18nextConfig, lng: "nb" });

export const { i18n, initPromise } = createClient(config);
```

I can then reference this i18n in my API routes. In my case providing to the i18n provider (similar to what the app wrapper does)

```ts
import { i18n, initPromise } from "@utils/api-i18n";

// await initPromise in some way
// return component I want to render wrapped in provider
<I18nextProvider i18n={i18n}>{mjmlComponent}</I18nextProvider>
```

No real idea if this is recommended. If someone could confirm or deny that would be great 😄

**Comment by riccardolardi** [comment]
Has anyone in the meantime found another solution to get translations in api routes?
