### ISSUE TITLE
Error with getServerSideProps and next-i18next@^8.0.0-beta.2

### ISSUE THREAD

**Issue by Achaak** [isaachinman/next-i18next#919]
## Describe the bug
Error 502 in vercel, when using getServerSideProps with next-i18next@^8.0.0-beta.2 

## Occurs in next-i18next version
next-i18next@^8.0.0-beta.2 

## Steps to reproduce
Create dynamic page with next-i18next and getServerSideProps 

## Screenshots
![image](https://user-images.githubusercontent.com/39270779/105691162-2e369d00-5efd-11eb-95fb-79cdb0c12296.png)
![image](https://user-images.githubusercontent.com/39270779/105690875-d0a25080-5efc-11eb-96f5-f81bd19858b5.png)

## OS
 - Browser: Chrome 87.0.4280.141

**Comment by isaachinman** [comment]
@Achaak The error seems pretty straightforward – the `/public/static/locales/fr` dir is missing. For reference, [this repo](https://github.com/isaachinman/next-i18next-vercel) is deployed on Vercel without any issues. Let me know if you still feel as though there's a bug here.

**Comment by Achaak** [comment]
This is precisely the problem.
The file /public/static/locales/en exists.
The other static pages work very well.

**Comment by isaachinman** [comment]
Do you have a reproducible repo?

**Comment by Achaak** [comment]
Repo: [https://github.com/Achaak/next-i18next-issue](https://github.com/Achaak/next-i18next-issue)
Page work: https://next-i18next-issue.vercel.app/fr
Page not work: https://next-i18next-issue.vercel.app/fr/123

Error: 
![image](https://user-images.githubusercontent.com/39270779/105703966-5084e680-5f0e-11eb-9111-7f91277eead0.png)

**Comment by destruc7i0n** [comment]
I am encountering the same problem using Incremental Static Regeneration and deploying on Vercel. Version 8.0.0-beta.4

**Comment by isaachinman** [comment]
This looks to me like a transient filesystem issue which is probably pretty specific to Vercel. @Achaak or @destruc7i0n can you open a support ticket with Vercel and ask them why these files are available during SSG but not during SSR?

**Comment by yovanoc** [comment]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/7302317/107051698-0da7f600-67cd-11eb-901b-29c8ff6c479a.png">

**Comment by isaachinman** [comment]
Not sure how you phrased the support ticket, but you'll need to make it clear this is a _filesystem_ issue, and is not specifically related to third-party packages.

**Comment by yovanoc** [comment]
Yes, maybe we could try again but I've said exactly this:

```
Hello, there is a potential transient filesystem issue during SSG but not during SSR

https://github.com/isaachinman/next-i18next/issues/919
```

**Comment by destruc7i0n** [comment]
I was able to resolve this by placing the following call above the usage of `serverSideTranslations` in my `getStaticPaths`. 
```
path.resolve('./public/locales')
```

They appear to be using [vercel/nft](https://github.com/vercel/nft) to see which files to include in the serverless runtime.

**Comment by isaachinman** [comment]
Yep, that makes sense, and that is why `path.resolve` [is in the docs for the current v7 version](https://github.com/isaachinman/next-i18next#3-project-setup).

**Comment by Achaak** [comment]
I have test but with next-i18next-config.js or path.resolve (in getServerSideProps) and not work for me.

**Version:** next-i18next@^8.0.0-beta.4

**Check my repo :**
Repo: https://github.com/Achaak/next-i18next-issue
Page work: https://next-i18next-issue.vercel.app/fr
Page not work: https://next-i18next-issue.vercel.app/fr/123

![image](https://user-images.githubusercontent.com/39270779/107215620-da06df00-6a0b-11eb-813a-8dd87654b870.png)

**Comment by ASgmbv** [comment]
> Did anybody got the solution?
> 
> Facing the same when using SSR, works well with SSG

module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  **localePath: path.resolve('./my/custom/path'),** // add this line in next-i18next.config.js file
};
