### ISSUE TITLE
301 redirects are cached in browser

### ISSUE THREAD

**Issue by petertulala** [isaachinman/next-i18next#92]
Switching of languages is sometimes not working correctly in Chrome.

Example: After invoking `i18n.changeLanguage('de')`, the url is redirected to `/de/path`. But because the Chrome has a cache for URL value `/de/path`, it's redirected back.

<img width="363" alt="screenshot 2019-01-12 at 03 06 28" src="https://user-images.githubusercontent.com/613623/51067930-273ed980-1617-11e9-81b5-184944713aa9.png">

After cleaning browser cache, all invocations of `i18n.changeLanguage` work as expected.

Proposed fix in #91.

**Comment by isaachinman** [comment]
Can you explain the actual bug you're seeing? Not sure I understand, or have seen this behaviour. At least initially, it seems like a bad idea to disable caching.

**Comment by petertulala** [comment]
Steps to reproduce:
1. Clear browser cache and set default language to `en`.
2. Call `i18n.changeLanguage('de')`.
2. Navigate to `/page`. Redirect `/page` -> `/de/page` is triggered here: https://github.com/isaachinman/next-i18next/blob/417314736320e4c35fd467e952355ddd6180ca5f/src/utils/lng-path-detector.js#L29
The redirect is with code `301 Moved Permanently` and is stored in the browser cache -- i.e. any future requests to `/page` will be automatically redirected to `/de/page` without even asking the server.
3. Open `/page`. The page now just blink and is redirected back to `/de/page` because of 301 cache.
4. Any further call to `i18n.changeLanguage('en')` does not work, because the page is immediately redirected to `/de/page` according to 301 cache.

**Comment by isaachinman** [comment]
Those aren't the full steps and don't involve the example dir. Please provide a reproducible example. It sounds like we might want to use a 302 potentially.

**Comment by isaachinman** [comment]
I think a 302 is the safest bet, but I still need a reproducible example. I'm quite sure we won't be modifying cache headers - we shouldn't need to do that.

**Comment by capellini** [comment]
> I still need a reproducible example

If we know that browsers cache 301 redirects, and we agree that we don't want the browser to cache these redirects, is there any harm in changing it to 302 without a reproducible example?

**Comment by isaachinman** [comment]
I ended up figuring out how to reproduce this locally. @petertulala In the future it'd be great if you can just fork a repo, make the required changes, and link it to us to reproduce.

This should be fixed by 53d866b. Can one or both of you please verify that?

**Comment by capellini** [comment]
I am now humbled.  I just tested 53d866b and it appears as though, despite be a **temporary** redirect, that Chrome and Firefox (and perhaps other browsers) _also_ store 302 redirects in cache.

![screenshot from 2019-01-16 12-57-06](https://user-images.githubusercontent.com/75311/51268531-56927500-198e-11e9-9c38-a7fbc548b245.png)

Morever, looking at [this bug report page](https://bugs.chromium.org/p/chromium/issues/detail?id=91740), I saw this as a proposed solution:

> You can add cache control headers...and we'll follow them (expiration etc)

Looking at Firefox forums, it appears as though they also obey cache control headers.  So, many apologies to @petertulala as it seems that setting cache control headers is also needed.

That said, a 302 is a more appropriate status code, so I don't think that 53d866b is for naught (and I can confirm that it  does work, both in `forceTrailingSlash` and `lngPathDetector`).

My suggestion is to have another util method that `forceTrailingSlash` and `lngPathDetector` call that handles the redirect logic in one location.  To ensure thoroughness, set the following cache headers:

```
Cache-control: no-cache, no-store
Pragma: no-cache
Expires: -1
```

Thoughts?

**Comment by isaachinman** [comment]
I tested this in FF on OSX and did not see 302s cached. However to be safe, I've added cache headers with 5352521. We're now using 302s _and_ setting no-cache headers aggressively on those specific requests.

@capellini Do you mind double checking me here? It was quick work.

**Comment by capellini** [comment]
Using the example in our repo:
1. To test `forceTrailingSlash`, switch locale to `de` then navigate to `http://localhost:3000/de` (should be redirected to `http://localhost:3000/de/`)
2. To test 'lngPathDetector`:
    1. While locale is still `de`, navigate to `http://localhost:3000/second-page` (should be redirected to `http://localhost:3000/de/second-page`)
    2. Switch locale to `en`, navigate to `http://localhost:3000/en/second-page` (should be redirected to `http://localhost:3000/second-page`)

In all cases, I can confirm that:
1. they are 302 redirects
2. they contain the appropriate headers
3. the redirects are not cached in the browser

![screenshot from 2019-01-17 10-30-42](https://user-images.githubusercontent.com/75311/51329476-910a1980-1a43-11e9-9ce4-481942eff4dd.png)

Looks good to me.

**Comment by isaachinman** [comment]
Great, thanks for taking a look at that.
