### ISSUE TITLE
V10-8.0.0.beta2 :: react-i18next:: You will need to pass in an i18next instance

### ISSUE THREAD

**Issue by FBosler** [isaachinman/next-i18next#920]
## Describe the bug
I am using v10.beta. Even though I wrapped the app like this:

```
// don't convert to <1></1> if simple react elements. Allows for usage of simple html elements in translations
const i18nOptions = {
    react: { transKeepBasicHtmlNodesFor: ['br', 'i', 'b', 'p', 'strong', 'bold'] },
}

export default appWithTranslation(App, i18nOptions)
```
I am getting the error:
`react-i18next:: You will need to pass in an i18next instance`

From inspecting the components I see that the wrapping wors, but no Instance is provided
![image](https://user-images.githubusercontent.com/14016698/105890473-b1e0ae80-600f-11eb-8afa-5c015474ed19.png)

## Occurs in next-i18next version
https://github.com/isaachinman/next-i18next/tree/next-v10

## Steps to reproduce
I hope the pasted code suffices

## Expected behaviour
Would expect the i18n object to be available/instantiated, am I missing something?

## OS (please complete the following information)
 - Device: MBpro 2020 16"
 - Browser: latest Chrome

## Additional context
I am loading components dynamically (i.e. `dynamic(import('....'))` ) in a chat app, the page does not contain any text, however the components do, they would love to have access to i18n.

**Comment by isaachinman** [comment]
Do you have a reproducible repository?

**Comment by FBosler** [comment]
@isaachinman would take some time to set up (as my project is quite large). But will do, if we can't figure it out. I thought that maybe the bug was known since the v10 beta version is quite new (I got that from another post).

**Comment by FBosler** [comment]
@isaachinman here you go:
https://github.com/FBosler/next-i18n-dynamicComponents

This should be the bare minimum. I hope you see where my problem is coming from.

Cheers
Fabian

**Comment by FBosler** [comment]
I guess as a related question. How can `serverSideTranslations` set up in such a way that it passes all namespaces (i.e. translation files) but also accepts i18nOptions?

**Comment by isaachinman** [comment]
@FBosler This sounds like a general architectural problem, and not related to `next-i18next`. Please feel free to post on StackOverflow or similar. Best of luck!

**Comment by FBosler** [comment]
@isaachinman yea, I guess you are right. One question though is there a way to get all translation namespaces for `serverSideTranslations` or alternatively only load the needed namespaces dynamically?

**Comment by isaachinman** [comment]
Yes, check [the docs](https://github.com/isaachinman/next-i18next/tree/next-v10#4-declaring-namespace-dependencies). If the docs are unclear, please post in #869. Thanks!
