### ISSUE TITLE
loading translate not working a server side

### ISSUE THREAD

**Issue by eeeman1** [isaachinman/next-i18next#924]
## 🐛 Bug Report

HttpApi doesn't work server side (I can't see translations on first page load)

## To Reproduce

https://codesandbox.io/s/smoosh-thunder-o0fuw

just add plugin i18next-http-backend specify url to download translation

```js
const NextI18Next = require('next-i18next').default;
import HttpApi from 'i18next-http-backend';
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;
const path = require('path');

module.exports = new NextI18Next({
  use: [HttpApi],
  backend: {
    loadPath: `https://pobeda37.io/api/gettranslate?lng={{lng}}&ns={{ns}}`,
    crossDomain: true
  },
  otherLanguages: ['de'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales')
});

```

## Expected behavior

I expected translations to be loaded in the same way on the server side

## Your Environment

- *node* v14.15.4
- *i18next version*: ^14.0.1
- *os*: Windows

**Comment by isaachinman** [comment]
I am assuming you are not using `next-i18next@beta`. In which case, `next-i18next` handles use of `i18next-http-backend` for you. To load translations from an API, please search through past issues or post on StackOverflow. Best of luck!

**Comment by eeeman1** [comment]
> Я предполагаю, что вы не используете `next-i18next@beta`. В этом случае он `next-i18next`обрабатывает использование `i18next-http-backend`за вас. Чтобы загрузить переводы из API, поищите в прошлых выпусках или разместите сообщение на StackOverflow. Удачи!

what do past releases mean? previous versions could work with a remote api but the current version cannot?
Could you show me an example of the code where the request for translations from a remote api is carried out?
