### ISSUE TITLE
Deduping translations between pages

### ISSUE THREAD

**Issue by filipesmedeiros** [isaachinman/next-i18next#925]
## Is your feature request related to a problem? Please describe.

As I understand, this new version (Nextjs10) is creating a new i18next client on the server for every page request, as seen by this "stack trace"

https://github.com/isaachinman/next-i18next/blob/next-v10/examples/simple/pages/index.js#L44
https://github.com/isaachinman/next-i18next/blob/next-v10/src/serverSideTranslations.ts#L25
https://github.com/isaachinman/next-i18next/blob/next-v10/src/createClient/node.ts#L7
https://github.com/i18next/i18next/blob/master/src/i18next.js#L499

This should mean that if I go to page A that requires namespace A and then move to page AB that requires namespaces A _and_ B, I will be loading (from the filesystem in this case) two times, right?

## Describe the solution you'd like
Shouldn't we be doing something like storing the instance between requests (if possible of course, I think serverless would make it impossible) and just adding new translations/namespaces to the already created instance?

**Comment by isaachinman** [comment]
Translations in `next-i18next@beta` are passed into pages merely as normal props. The issue you are describing is interesting, and certainly valid, but is more of a general request about deduping _props_ in general. Perhaps you can open an issue or discussion on the NextJs repo?

**Comment by filipesmedeiros** [comment]
I understand what you said and while it is true, my issue is that AFAIK we fetch all namespaces each page, regardless of if we've fetched them before or not. The deduping of props in general is in fact another issue and can be handled in the Next repo yeah!

**Comment by isaachinman** [comment]
My point is that this is not specific to `next-i18next` at all. Presumably lots of SSG NextJs apps have pages which share large amounts of "static" props which could be deduped. I do not think there would be a good way to solve this problem outside of changes to the actual NextJs core.

**Comment by filipesmedeiros** [comment]
I see what you mean. But what happens "beyond" gSP is no longer Next's responsibility, and right now this "double fetching" could be avoided if we shared the same translations on the server, because right now neither the app or Next is able to hook into `next-i18next` to avoid it, because neither know what's going on inside, right? Now, I investigated a bit further and this actually seems like a problem that `i18next` themselves could solve/have solved, because the Resource Storage layer might cache resources, even between I18next instances.

**Comment by filipesmedeiros** [comment]
I think indeed this is `i18next`'s responsibility. Thank you for your time!

**Comment by ShaySong99** [comment]
> My point is that this is not specific to `next-i18next` at all. Presumably lots of SSG NextJs apps have pages which share large amounts of "static" props which could be deduped. I do not think there would be a good way to solve this problem outside of changes to the actual NextJs core.

I want to share some common locale in each page. But it seems I need to add  getStaticProps in each page. And these common locale will be loaded repeatedly when router change.  Similar issue with @ #1215 .

I think the next-i18next is used to add translations owned by a specific page conveniently. I haven't found out how to import the public translations separately.

 If appWithTranslation support baseResoure, to provide the public resource to i18n context when app init. The public translations can be import and I don’t need to use getStaticProps in unnecessary page.  Will there be any problem？ Hope to get your answer.
