### ISSUE TITLE
FS backend being used conditionally

### ISSUE THREAD

**Issue by filipesmedeiros** [isaachinman/next-i18next#927]
## Is your feature request related to a problem? Please describe.
Hey again,

As far as I can tell, with the new version v^8.0.0 you want to allow custom backends to disable the default FS backend when the users provides one: https://github.com/isaachinman/next-i18next/blob/next-v10/src/config/createConfig.ts#L35

https://github.com/isaachinman/next-i18next/blob/next-v10/src/createClient/node.ts#L11
Problem is: doesn't this use FS no matter what we pass as config?

## Describe the solution you'd like
Just a check like:

```js
if(!(userConfig.use && userConfig.use.find((b) => b.type === 'backend'))) // same as on the other side
      instance.use(i18nextFSBackend)
```

## Additional context
Maybe I'm wrong about this, just let me know!

**Comment by isaachinman** [comment]
> doesn't this use FS no matter what we pass as config?

Not sure I understand your point. Are you saying that the `hasCustomBackend` variable is incorrectly assigned?

**Comment by filipesmedeiros** [comment]
Oh sorry, I copied the wrong line, the second link should be: https://github.com/isaachinman/next-i18next/blob/next-v10/src/createClient/node.ts#L11

I'll edit the original post, also

**Comment by isaachinman** [comment]
Ah yes, that's a good catch. Would you be able to open a PR for this fix?
