### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by yacineb** [isaachinman/next-i18next#929]
According to https://bundlephobia.com/result?p=next-i18next@7.0.1  , the bundle is quite big for such a puropose (i18n) , is there a way to reduce it/enable webpack treeshaking ?

Seems so weird having core-js and @types/express  in dependencies...

**Comment by isaachinman** [comment]
Hey @yacineb – a few points to make:

1. `core-js` is already included by NextJs itself
2. TypeScript type declarations will never impact your distributed bundle size
3. The upcoming release, `next-i18next@beta`, is [about half the size of v7.0.1](https://bundlephobia.com/result?p=next-i18next@8.0.0-beta.3)

Hope that helps to answer some of your questions! If you'd like to follow up on further optimisations for `next-i18next@beta`, please comment in #869.
