### ISSUE TITLE
Accessing otherLanguages prop returns languages string within array

### ISSUE THREAD

**Issue by peacefulseeker** [isaachinman/next-i18next#93]
//
import {i18n, Link, withNamespaces} from '../i18n';
//
const {otherLanguages} = i18n.options;
//
Expected `otherLanguages` to be equal `['en', 'de']`;
In reality `otherLanguages = ['en, de']`

**Comment by isaachinman** [comment]
@peacefulseeker Closing due to lack of response. Happy to reopen if a reproducible example is provided.
