### ISSUE TITLE
Auto defining fallbackLng in production build breaks v4.5

### ISSUE THREAD

**Issue by felixmosh** [isaachinman/next-i18next#932]
## Describe the bug
Since [this change](https://github.com/i18next/i18next/commit/ad88092292cc32fe250c6352f796dd710705d0da) of `i18next` v19.8.5 & the [default config](https://github.com/isaachinman/next-i18next/blob/188296f184501261275a586fe69b6d64631e2a20/src/config/create-config.ts#L111) of `next-i18next` v4.5.0 in prod build it is not able to "stay" in the secondary language, SSR renders the secondary language but at client side, it changes to `fallbackLng` which is the `defaultLanguage` (which is the primary language)

## Occurs in next-i18next version
v4.5.0

I'm not able to update to latest since my app uses custom server not just for translations

## Steps to reproduce
1. clone https://github.com/felixmosh/next-i18next-bug-fallbackLng
2. yarn install
3. yarn build
4. yarn start
5. open http://localhost:3000
6. change to `de` (check that there is `de` subpath)
7. reload the page
8. the page shows in english

## Expected behaviour
After reloading the page, it should remain on the Dutch lang 

## Additional context
It is not possible to turnoff this `fallbackLng` behavior since [the fix](https://github.com/isaachinman/next-i18next/blob/master/src/config/create-config.ts#L128) is not available in v4.5.0

**Comment by isaachinman** [comment]
Hey @felixmosh – what exactly are you hoping for here? Not sure we can reasonably support previous major versions.

**Comment by felixmosh** [comment]
Is it possible to add the fix to v4?

**Comment by isaachinman** [comment]
Can you elaborate on why your custom server requirement prevents you from upgrading past v4?

**Comment by felixmosh** [comment]
If I remember correctly, starting v5 there is no lng middleware usage, which  do need for my custom server.

All of my app urls are coming from CMS, so I need to know the current lng.

**Comment by isaachinman** [comment]
And is `next-i18next@beta` not an option for you? I assume the Vercel team have taken custom servers into account?

**Comment by felixmosh** [comment]
They can custom servers into account since its handles are the first the get the response, therefore they need to handle lng.

**Comment by isaachinman** [comment]
Do you mean that the internationalisation in Next v10 doesn't support custom servers at all?

**Comment by felixmosh** [comment]
Think of that, custom server is the first thing that handles the request, and next.js handlers may come later in the pipe line.
For sure Next.js i18n doesn't work out of the box with custom servers...

**Comment by isaachinman** [comment]
I'd be curious to hear feedback on that from the Vercel team. In the meantime, if you'd like to open a PR against a v4 branch, I can publish the fix you need. Otherwise you'll need to maintain a fork.

**Comment by felixmosh** [comment]
Thanx, I will do...

**Comment by felixmosh** [comment]
I doesn't allows me to open a PR agains tag, can you open a branch from v4.5?

**Comment by felixmosh** [comment]
BTW, currently I am patching the lib with patch-package, it works as expected, if you don't want to maintain v4.5 anymore, it is ok to close this issue.

I just wanted to update that with latest i18next there is more chance to get that bug that I've described.

**Comment by isaachinman** [comment]
@felixmosh I've created a `v4` branch. I won't be actively maintaining past versions myself, but if users want to do so, I'm fine with that!

**Comment by felixmosh** [comment]
The branch is based on v7 :]

**Comment by isaachinman** [comment]
Updated.

**Comment by isaachinman** [comment]
@felixmosh Do you want to keep this open?

**Comment by felixmosh** [comment]
Will you publish updates to v4? if so, I will make cleaner pr for it :]

**Comment by isaachinman** [comment]
Yep, as I said, I'll merge it if you want to do the work!

**Comment by felixmosh** [comment]
I'm closing this issue, since many tests are failing and i don't have much time to solve them.

Currently i'm patching the lib with patch-package.
