### ISSUE TITLE
How to disable/ignore internationalisation for a single page and remove language prefix.

### ISSUE THREAD

**Issue by vinit03** [isaachinman/next-i18next#936]
I tried using ignoreRoutes in configuration for a static page but on client side redirection it still appends language prefix. The page I want to remove internationalisation is a dynamic page which is directly in pages directory.
/pages/[dynamic-page]
I want all the URLs for that page to not have any language prefix

**Comment by isaachinman** [comment]
The `ignoreRoutes` config option should do exactly what you are describing. Can you please provide a reproducible repo?
