### ISSUE TITLE
changeLanguage method doesn't adapt the URL with new language

### ISSUE THREAD

**Issue by ThaoD5** [isaachinman/next-i18next#938]
Hello, 

I have been looking for hours now on a fix on why the `changeLanguage` method doesn't replace the previous language slug by the new one in the URL.

Using : `i18n.changeLanguage('es');`

I found [this](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L39), the condition on `initializedLanguageOnce` but I have absolutely no idea AND didn't found anything related to this parameter that needs to be `true`.

The locale changing is happening correctly 

Am I missing something ? Is this intended ? Is there something manually to add ? 

Thanks a lot 

______ 
( issue created based on someone having the same error in 2019 ) 

@vimutti77 That might be a separate issue. Any client side calls to `changeLanguage` should trigger [this](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.tsx#L39) callback. If you think you're experiencing a bug there, please do open a separate issue.

_Originally posted by @isaachinman in https://github.com/isaachinman/next-i18next/issues/413#issuecomment-527364135_

**Comment by isaachinman** [comment]
Hi @ThaoD5, have you seen the [simple example](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L13)? If you add `localeSubpaths`, you'll be able to see the language changing the routing.

We have this behaviour covered by end-to-end tests.

If you believe you have found a bug, please provide a reproducible repository. Thanks!

**Comment by ThaoD5** [comment]
Hey @isaachinman 
I have indeed worked with the `localeSubpaths` params you're talking about.
Here is a recap of my setup : 
`Next.config.js`
```
// Locales route rewriting
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const localeSubpaths = {
  es: 'es',
  en: 'en'
}

module.exports = withImages({
  // Locales Options
  rewrites: async () => nextI18NextRewrites(localeSubpaths),
  publicRuntimeConfig: {
    localeSubpaths,
  },
  i18n: {
    locales: ['en', 'es'],
    localeDetection: true,
    defaultLocale: 'en'
  },
  ```
  const { localeSubpaths } = require('next/config').default().publicRuntimeConfig;
  const i18n = new NextI18Next({
  ...
  defaultNS: 'translation',
  defaultLanguage: DEFAULT,
  localePath: '/locales',
  localeStructure: '{{lng}}/{{ns}}',
  localeExtension: 'json',
  otherLanguages: LANGUAGES,
  localeSubpaths,
  ...
  });
  ```
  
  That should be right, no ? Are there some known configs that breaks this ? We're building our new internal stack to include next I18next inside of it, but so far, the only issue remaining is this slug not getting replaced.
  
  Thanks again for your help & time.

**Comment by ThaoD5** [comment]
On an additional note @isaachinman I saw that the example does have the same issue that I have ( and apparently it is supposed to be the "simple" example you just sent ) 
The slug is not added in the URL

https://next-i18next.com/

**Comment by isaachinman** [comment]
I believe you are confusing the built-in NextJs internationalisation, and `next-i18next`. You do not need to put `i18n` in your `next-config` if you are using `next-i18next@master`. Please post on StackOverflow for help. Best of luck!
