### ISSUE TITLE
fallbackLng is always enforced client-side even if SSR correctly detected/rendered another language

### ISSUE THREAD

**Issue by romaincointepas** [isaachinman/next-i18next#939]
## Describe the bug
`fallbackLng` is always enforced client-side even if SSR correctly detected/rendered another language.

`/` redirects to `/fr` with french translations, then another redirect to `/` with `fallbackLng` translations.

## Occurs in next-i18next version
7.0.1

## Steps to reproduce
```js
module.exports = new NextI18Next({
  ns: 'global',
  defaultNS: 'global',
  browserLanguageDetection: false,
  otherLanguages: ['fr'],
  fallbackLng: 'en',
  localeSubpaths,
  localePath: path.resolve('./public/locales'),
  debug: true,
});
```

## Expected behaviour
`/` should redirect to `/fr`, and `/fr` should stay on `/fr` with french translations.

## Screenshots
Debug shows:
```
i18next: languageChanged fr
i18next: languageChanged en
i18next: initialized
```

## OS (please complete the following information)
 - Device: MacBook Pro (15-inch, 2016)
 - Browser: Chrome 88.0.4324.150

## Additional context
Could be related to the following?
https://github.com/i18next/i18next/commit/ad88092292cc32fe250c6352f796dd710705d0da
https://github.com/isaachinman/next-i18next/issues/932

**Comment by isaachinman** [comment]
If you want to disable `browserLanguageDetection`, you'll need to modify your [detection scheme](https://www.i18next.com/overview/configuration-options#plugin-options). Good luck!

**Comment by romaincointepas** [comment]
@isaachinman this seems to be a regression though (probably due to a change upstream?), it used to work perfectly fine a few weeks ago, and even the current behavior right now feels buggy:

1. the correct language is detected server-side (because `serverLanguageDetection` defaults to `true`).
2. the page is rendered (SSR) using the language detected server-side, everything works as expected (the right locale is added to the path, etc.).
3. `browserLanguageDetection` is set to false, and somehow after the page is rendered, without doing anything, everything is refreshed using the `fallbackLng`.

Is that a new expected behavior?

**Comment by isaachinman** [comment]
@romaincointepas Between which releases did you begin to experience this regression?

**Comment by romaincointepas** [comment]
@isaachinman trying older versions of `next-i18next` that used to work doesn't anymore, so I'm assuming it has to do with changes in one of the dependencies (mentioned in the original issue)?
