### ISSUE TITLE
Add support for shallow prop

### ISSUE THREAD

**Issue by AleVul** [isaachinman/next-i18next#94]
The next Link component has shallow prop to not trigger a server render, but Link component from next-i18next does not pass that prop to next Link.

**Comment by isaachinman** [comment]
Fixed with fadd81f. Released with v0.18.2.

**Comment by a-barbieri** [comment]
Cannot get it to work with version `0.36.4`. The page refresh even though `shallow` is set to true and I going from a `page` to a `page` just changing the `slug`. 

Am I missing some requirement?

I'm implementing it this way:

```js
<Link href={`/page/${page.slug}`} shallow><a>{page.title}</a></Link>
```
or: 
```js
<Link href={`/page/${page.slug}`} shallow={true}><a>{page.title}</a></Link>
```

**Comment by a-barbieri** [comment]
Ok, I had to look [in the code](https://github.com/isaachinman/next-i18next/blob/master/src/components/Link.js#L10) to find how to actually implement it.

You should put that in the documentation. 

```js
<Link href="/product?slug=something" as="/products/something">
```

No need to add `shallow`.

**Comment by isaachinman** [comment]
Not sure we'd want to support `shallow`. At the moment, `next-i18next` looks for `namespacesRequired` returned from `getInitialProps`.

Those two options would conflict with each other.

That said, the `shallow` prop would indeed get passed on automatically as per fadd81f.

**Comment by isaachinman** [comment]
Hi @a-barbieri, what exactly do you feel we should put in the documentation? Is the href/as usage any different than normal NextJs usage?

**Comment by a-barbieri** [comment]
> what exactly do you feel we should put in the documentation?

`href/as` usage isn't so clear in the current doc not even in NextJS one, infact you also specify it in [your code](https://github.com/isaachinman/next-i18next/blob/master/src/components/Link.js#L6-L7). When you [talk about Link](https://github.com/isaachinman/next-i18next/blob/8bf6fb4899e3baab7f1e76f540f2a1c8c04c13e3/README.md#5-locale-subpaths) you should probably place a [reference to that NextJS comment](https://github.com/zeit/next.js/issues/2833#issuecomment-414919347).

---

Anyway I think it's a broader lack of documentation. The more I'm looking into this library the more I found there's no documented way to get **custom routing** right.

> I would need to think more about how to do the client-side routing, but my initial inclination is that, with Next's router object, withRouter HoC, and something similar to what we do in appWithTranslation in PR #96, it can be done.

[from this thread](https://github.com/isaachinman/next-i18next/issues/126#issuecomment-457555654)

Even though @capellini has guessed something, that's way too far from knowing how to implement custom routing. Infact `i18n.changeLanguage()` still doesn't get it right if `page.slug` is different for every language. 

So adding a way to use `Link` like I mentioned above won't be sufficient.

**Comment by a-barbieri** [comment]
BTW this isn't the right thread to get this in depth. In case you are willing to get deeper into the matter I can open another issue.

**Comment by isaachinman** [comment]
@a-barbieri Yes, please feel free to open a new issue to continue this discussion. We're open to any/all suggestions you might have.
