### ISSUE TITLE
Set Key Separator and Namespace Separator

### ISSUE THREAD

**Issue by Kent27** [isaachinman/next-i18next#943]
Hi, is there a way to change the keySeparator and nsSeparator? thanks

**Comment by isaachinman** [comment]
Hi @Kent27 — you can pass any i18next options into the config object. Best of luck!

**Comment by ripvannwinkler** [comment]
This doesn't work in typescript. Using the following config:

```
i18n: {
    locales: ['en-US'],
    defaultLocale: 'en-US',
    keySeparator: false,
    nsSeparator: false,
},
```

Typescript complains thusly:

`
Type '{ locales: string[]; defaultLocale: string; keySeparator: boolean; nsSeparator: boolean; }' is not assignable to type 'NextJsI18NConfig'.\n  Object literal may only specify known properties, and 'keySeparator' does not exist in type 'NextJsI18NConfig'.`


Seems like the `NextJsI18NConfig` type needs to be expanded.

Technically, it still compiles, but expanding the type to get rid of the warning seems appropriate.
