### ISSUE TITLE
Is next-i18next compatible with static rendering?

### ISSUE THREAD

**Issue by j4nos** [isaachinman/next-i18next#950]
I got this error when building for Next.js and using getStaticProps() along with next-i18next: 

> Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error

Maybe next-i18next module is not compatible with Static Rendering?

**Comment by isaachinman** [comment]
Hi @j4nos – this package is certainly compatible with static rendering. Please do post on StackOverflow for further help. Good luck!

**Comment by tomevans18** [comment]
This seems to happen when you add a custom `_error` page with `getInitialProps`.
I believe this is a limitation of Next.js custom error component as it doesn't support `getServerProps` or `getStaticProps`.

**Comment by tomevans18** [comment]
My recommendation is to remove `_error`.
Then create a `400` and `500` page using `getStaticProps`.
