### ISSUE TITLE
[8.0.0-beta.6] Unable to read translation of locale with hyphen

### ISSUE THREAD

**Issue by cynthiachanky** [isaachinman/next-i18next#963]
## Describe the bug
The translation folders of locale with hyphen, such as zh-cn and en-us, cannot be read.

## Occurs in next-i18next version
8.0.0-beta.6

## Steps to reproduce
`next-i18next.config.js`
```
module.exports = {
  i18n: {
    defaultLocale: 'en-us',
    locales: [ 'en-us', 'zh-cn' ],
  },
}
```

## Expected behaviour
Common language tag formats should be supported.

## Screenshots
![image](https://user-images.githubusercontent.com/77741190/108685312-f6883880-752e-11eb-8cc4-a2f7349bb6cf.png)

## OS
 - OS: Windows 10
 - Browser: Chrome

## Additional context
N/A

**Comment by isaachinman** [comment]
@cynthiachanky Those are not valid regional locale ISO codes. If I change the [simple example](https://github.com/isaachinman/next-i18next/tree/next-v10/examples/simple) to run on `en-US` and `de-DE`, I see no issues with `initialI18nStore` population. Please let me know if this fixes your issue. We can add some more helpful validation.

**Comment by cynthiachanky** [comment]
Thanks for your prompt reply. Capitalizing the country code solves the issues, aka `zh-CN` and `en-US`.
