### ISSUE TITLE
8.0.0 how to send down ALL namespaces?

### ISSUE THREAD

**Issue by macrozone** [isaachinman/next-i18next#981]
## Describe the bug

https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies

describes that by default next-i18next will send down all namespaces without `serverSideTranslations` as in 7.x, but I saw that i get no translations at all unless i specify serverSideTranslations.

We relied on getting all namespaces, because they are small and its really challenging and error prone when a page needs to know what translations will be used by any component.

## Occurs in next-i18next version

8.0.0

we use a custom server

## Steps to reproduce

maybe i can create a reproduction, but i think its easy to reproduce

## Expected behaviour

without specifying serverSideTranslations, it should use all namespaces

**Comment by isaachinman** [comment]
That documentation is actually inaccurate, and I forgot to update it. The default behaviour in `next-i18next` is now to send down _no_ namespaces if the array isn't provided.

I would suggest keeping this in userland – you can easily [write a function that uses `fs`](https://github.com/isaachinman/next-i18next/blob/349d7569c7848c5a01ba1d53e931edbbe5730f4b/src/config/create-config.ts#L101) to gather up your array of namespaces.

Let me know your thoughts.

**Comment by isaachinman** [comment]
@macrozone I've decided to restore this functionality, and will release it in v8.0.1.
