### ISSUE TITLE
Can't have non serializable options in i18next in v8

### ISSUE THREAD

**Issue by haggen** [isaachinman/next-i18next#982]
## Describe the bug

Now that i18next's options provided are serialized as JSON and sent to the client, it effectively block non serializable values like functions. @zalcode [mentioned this in the Next.js 10 issue](https://github.com/isaachinman/next-i18next/issues/869#issuecomment-777193296).

## Occurs in next-i18next version

`v8.0.0`

## Steps to reproduce

Provide a function value in i18next options like:

```js
// next-i18next.config.js

module.exports = {
  i18n: ...,
  overloadTranslationOptionHandler: function() {},
};
``` 

See an error while compiling:

```
SerializableError: Error serializing `._nextI18Next.userConfig.overloadTranslationOptionHandler` returned from `getServerSideProps` in "/test".
Reason: `function` cannot be serialized as JSON. Please only return JSON serializable data types.
``` 

## Expected behaviour

I expected i18next to be configured successfully no matter what types it accepts in its settings.

**Comment by isaachinman** [comment]
This is [specifically mentioned in the docs](https://github.com/isaachinman/next-i18next#5-advanced-configuration). You need to set `serializeConfig` to `false` and pass the config into `appWithTranslation` yourself.

Let me know if you have any issues!
