### ISSUE TITLE
locize and next-i18next

### ISSUE THREAD

**Issue by mvlach** [isaachinman/next-i18next#987]
Hi,

I would like to thank you for the work you are doing.

I'm trying to use a localization framework that can automatically download resources from locize. I saw many google results on how to integrate other frameworks but I can't find any helpful resource on how to do it with the new version.

I follow this https://github.com/isaachinman/next-i18next/pull/705/files#diff-bda3f4b5c1b38db2dcde53a9832453e3R1 but I'm not successful.

I would like to ask you if you can provide any resources on how to connect your library to this service. I would like to use "create if missing" feature and I don't want to download resources at build time with the locize-cli.

Kindly, Míla

**Comment by isaachinman** [comment]
@adrai Wondering if you have any input? Should be a very straightforward i18next setup at this point.

**Comment by adrai** [comment]
https://github.com/locize/next-i18next-locize

**Comment by mvlach** [comment]
thank you guys, very much. I'll look.

**Comment by mvlach** [comment]
@adrai your example works correctly. But when I tried to apply to my project I got this error
```
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```
I can't find where is the problem

Any ideas?

Thanks Míla

**Comment by mvlach** [comment]
![image](https://user-images.githubusercontent.com/6176546/109185931-bf18c680-7790-11eb-852d-6cf00c71bf35.png)

**Comment by adrai** [comment]
a reproducible example would help

**Comment by mvlach** [comment]
It looks like the problem is with the Auth0 security. When I remove this implementation it looks like it is working.
```
i18next::translator: missingKey cs common Profile53čččč Profile53čččč
```
When I give back the 
```
    <Auth0Provider
      domain={publicRuntimeConfig.AUTH0_DOMAIN}
      clientId={publicRuntimeConfig.AUTH0_CLIEND_ID}
      redirectUri={publicRuntimeConfig.AUTH0_REDIRECT_URI}
    >
      <Component {...pageProps} />
    </Auth0Provider>
```
and add to page new key then no translator log in console.

**Comment by mvlach** [comment]
@adrai  - confirmed
This index page works
```import React from 'react';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { withAuthenticationRequired } from '@auth0/auth0-react';

function Profile({ auth0 }) {
  const { t } = useTranslation();

  return (
    <div>
      <h1>{t('Profile')}</h1>
      <h1>{t('Profile4')}</h1>
      <h1>{t('new.1')}</h1>
      <p>This is the profile page.</p>
    </div>
  );
}

export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});

export default Profile;
```
and when I change the last row to 

```
export default withAuthenticationRequired(Profile);
```

it is not working...
I'll investigate further

**Comment by mvlach** [comment]
When I use ```export default Profile;``` then I see in next logs information that i18next miss keys and upload them to the locize.
When I use ```export default withAuthenticationRequired(Profile);``` then I see in browser POST to the /public/locales/cs/common.missing.json  ending with the 404.

**Comment by mvlach** [comment]
![Uploading image.png…]()

**Comment by mvlach** [comment]
![image](https://user-images.githubusercontent.com/6176546/109201092-b381cb80-77a1-11eb-8783-1cf2868db825.png)

**Comment by mvlach** [comment]
I think it is working. I have to add addPath to the backend

```module.exports = {
  i18n: {
    defaultLocale: 'cs',
    locales: ['en', 'cs'],
  },
  // this will download the translations from locize directly, in client (browser) and server (node.js)
  // DO NOT USE THIS if having a serverless environment => this will generate too much download requests
  //   => https://github.com/locize/i18next-locize-backend#important-advice-for-serverless-environments---aws-lambda-google-cloud-functions-azure-functions-etc
  backend: {
    projectId: 'xxx',
    apiKey: 'xxx',
    referenceLng: 'cs',
    private: false,
    allowedAddOrUpdateHosts: ['localhost'],
    onSaved: (lng, ns) => {
      console.log(`Saved ${lng}, ${ns}`);
    },
    addPath: 'https://api.locize.app/update/{{projectId}}/{{version}}/{{lng}}/{{ns}}',
  },
  use: [require('i18next-locize-backend/cjs')],
  ns: ['common'], // the namespaces nees to be listed here, to make sure they got preloaded
  serializeConfig: false, // because of the custom use i18next plugin
  saveMissing: true,
  debug: true,
};

// for a serverless environment bundle the translations first. See downloadLocales script in package.json
// and configre this file like this:
// module.exports = {
//   i18n: {
//     defaultLocale: 'en',
//     locales: ['en', 'de'],
//   }
// }```

**Comment by dohomi** [comment]
@mvlach as I coincidently using Auth0 as well consider to use their official https://github.com/auth0/nextjs-auth0 which just got a final 1.x release. Are you using SSG / SSR approach of NextJS? I think you could re-run before the build the npm script mentioned in the i18next-locize project and don't use the backend method but the CLI if you could add it to the build script

**Comment by adrai** [comment]
@mvlach you may want to check this out: https://github.com/isaachinman/next-i18next/pull/1000

**Comment by isaachinman** [comment]
Closing in favour of #685.
