### ISSUE TITLE
Load all translations from a central location

### ISSUE THREAD

**Issue by overdub60** [isaachinman/next-i18next#989]
## Is your feature request related to a problem? Please describe.
I'm in the process of upgrading to v8 and I've got everything going but I'm wondering if there's a better way to load translations. I have a pretty small project so there is no need for dedicated namespaces for each page. I'd rather load all translations at once and not have to worry about it on each individual page. This worked out of the box with v7 from `_app.tsx` but now I have to add `getServerSideProps` or `getStaticProps` to each page, which is kind of a hassle. 

Is there a way around this already or will I really have to add loading of translations to each page individually? Loading them manually from `_app.tsx` doesn't work I assume since custom apps don't support `getServerSideProps` or `getStaticProps`.

**Comment by isaachinman** [comment]
Hi @overdub60 – you will always need to pass `serverSideTranslations` into each of your page components. That is just how `next-i18next@8` works.

There were similar patterns/requirements at the page level in previous versions, as well.

I suppose we could consider a config option to omit namespaces entirely, and always pass all translation content to every page. Is that what you're requesting? I'd be hesitant to do that, as it encourages non-optimal patterns.

**Comment by overdub60** [comment]
> I suppose we could consider a config option to omit namespaces entirely, and always pass all translation content to every page. Is that what you're requesting? I'd be hesitant to do that, as it encourages non-optimal patterns.

@isaachinman Thanks for getting back to me! Yeah, I think what you're suggesting is actually what we would like. Like I said, we only have about 100 lines of translations so it seems like overkill to separate all of these into namespaces and I think there is a use case for it for smaller projects.

**Comment by isaachinman** [comment]
You don't have to separate anything out into namespaces if you don't want to! I've just added "send all namespaces" behaviour with #984.

Outside of that, `serverSideTranslations` is needed as it is how we pass the actual translation data into pages. The only other option would be what is being proposed in #993.
