### ISSUE TITLE
Use lng or i18n prop in withNamespaces inside of Link component

### ISSUE THREAD

**Issue by capellini** [isaachinman/next-i18next#99]
Instead of [doing this](https://github.com/isaachinman/next-i18next/blob/7fbae9a3e765374a5310380662ab4315ae011bb2/src/components/Link.js#L34-L37) to find the locale, `withNamespaces` exposes an `lng` prop to it's wrapped component. Perhaps we should use the exposed prop instead?

**Comment by isaachinman** [comment]
Fixed with c0f2a4d. @capellini Do you mind double checking my work here?

**Comment by capellini** [comment]
> Do you mind double checking my work here?

:+1: on it

**Comment by capellini** [comment]
@isaachinman LGTM
