### ISSUE TITLE
Question: Translating entire pages

### ISSUE THREAD

**Issue by pillowfication** [isaachinman/next-i18next#994]
I have an information-heavy page full of links/pictures/tables/nested lists/custom components that I'd like to translate, and I'm not sure the best approach to it. It seems impractical to put every string into a translation key, and some parts are too complex for the Trans component. I think ideally I want to declare a page for each language so that

```
/about    -> renders about-en.tsx
/ja/about -> renders about-ja.tsx
/de/about -> renders about-de.tsx
/fr/about -> fallsback to about-en.tsx if about-fr.tsx doesn't exist
```

Currently I'm imitating that with

```tsx
const About = () => {
  const { i18n } = useTranslation()
  switch (i18n.language) {
    case 'ja': return AboutJA
    case 'de': return AboutDE
    default: return AboutEN
  }
}
```

but this has the problem of sending all the translated pages down.

**Comment by isaachinman** [comment]
Not sure I understand your question. What is the issue?
