### ISSUE TITLE
Error module 8.02

### ISSUE THREAD

**Issue by Achaak** [isaachinman/next-i18next#996]
## Describe the bug
```
   1 | import React from 'react'
> 2 | import hoistNonReactStatics from 'hoist-non-react-statics'
      |                                  ^
   3 | import { I18nextProvider } from 'react-i18next'
   4 | 
   5 | import { createConfig } from './config/createConfig'
```

## Occurs in next-i18next version
8.0.2

## Steps to reproduce
next build

**Comment by isaachinman** [comment]
Hi @Achaak – this is not a full or helpful bug report. Please do feel free to post a comprehensive account of what you believe went wrong.
