### ISSUE TITLE
Question: in 8.x, do i need to add `serverSideTranslations` to EVERY page?

### ISSUE THREAD

**Issue by macrozone** [isaachinman/next-i18next#999]
Hi, sorry this is not really a bug, but rather a question:

do i need now to add `serverSideTranslations` to every single page? is there no other easier way to do that? After all its just boilerplate and easy to forget.

**Comment by isaachinman** [comment]
Yes, as we have no way of wrapping `_app` without using `getInitialProps`, which is not something `next-i18next` will be supporting going forward.

If you're worried about boilerplate, I would encourage users to create their own `withServerSideTranslations` HOCs, if you'd like to reuse code!

**Comment by ronfogel** [comment]
> withServerSideTranslations

@isaachinman 

I tried to create such HOC, but I am unable to get the locale from ctx.
Any idea why or what I am doing wrong?

`import React from 'react';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { NextComponentType } from 'next';

const withServerSideTranslations = (ns: string[]) => (WrappedComponent: NextComponentType) => {
  return class WithServerSideTranslations extends React.Component {
    static async getInitialProps(ctx) {
      const pageProps = WrappedComponent.getInitialProps && (await WrappedComponent.getInitialProps(ctx));
      const { locale } = ctx;
      const translations = locale && (await serverSideTranslations(locale, ns));

      return {
        ...pageProps,
        ...translations,
      };
    }

    render() {
      return <WrappedComponent {...this.props} />;
    }
  };
};

export default withServerSideTranslations;
`

**Comment by isaachinman** [comment]
You won't be able to use `serverSideTranslations` within `getInitialProps`, as `getInitialProps` also runs client side after browser navigation.

**Comment by SwapnilSoni1999** [comment]
So we have to add that on every page?

**Comment by adrai** [comment]
yes, unless you can ant to lazy load translations: https://github.com/i18next/next-i18next#client-side-loading-of-translations-via-http
